tinymce.addI18n('ar_SA', {
  "-Language Not Set-": "-لم يتم تحديد اللغة-",
  "Choose from list": "اختيار من القائمة",
  "Choose languages": "اختيار اللغات",
  "Choose up to six languages": "اختيار حتى ست لغات",
  "Configure languages": "إعداد اللغات",
  "Current language:": "اللغة الحالية:",
  "Enter a valid language code with no spaces. Or, press cancel.": "أدخل رمز لغة صحيح بدون مسافات. أو اضغط إلغاء.",
  "Enter manually": "إدخال يدوي",
  "Enter new lang code (e.g., \"en-US\"):": "أدخل رمز اللغة الجديد (مثال: \"ar-SA\"):",
  "Indicate current language": "تحديد اللغة الحالية",
  "Manually enter language {{number}}:": "إدخال اللغة {{number}} يدوياً:",
  "New Language:": "لغة جديدة:",
  "None": "لا شيء",
  "Other - Enter manually": "أخرى - إدخال يدوي",
  "Really remove all language markup from the document?": "هل تريد حقاً إزالة جميع تمييزات اللغة من المستند؟",
  "Remove All lang markup": "إزالة جميع تمييزات اللغة",
  "Remove Language Markup": "إزالة تمييز اللغة",
  "Remove current lang value": "إزالة قيمة اللغة الحالية",
  "Reveal lang markup": "إظهار تمييز اللغة",
  "Select language {{number}}:": "اختيار اللغة {{number}}:",
  "Select the document's default language.": "قم بتحديد اللغة الافتراضية للمستند.",
  "Set default document language": "تحديد اللغة الافتراضية للمستند",
  "Set text language": "تحديد لغة النص",
  "Afrikaans": "الأفريقانية",
  "Afrikaans": "الأفريقانية (جنوب أفريقيا)",
  "Akan": "الأكانية",
  "Amharic": "الأمهرية",
  "Arabic": "العربية",
  "Arabic (Egypt)": "العربية (مصر)",
  "Arabic (Morocco)": "العربية (المغرب)",
  "Arabic (Saudi Arabia)": "العربية (السعودية)",
  "Azerbaijani": "الأذربيجانية",
  "Belarusian": "البيلاروسية",
  "Bulgarian": "البلغارية",
  "Bulgarian (Bulgaria)": "البلغارية (بلغاريا)",
  "Bhojpuri": "البهوجبورية",
  "Bambara": "البامبارا",
  "Bangla": "البنغالية",
  "Tibetan": "التبتية",
  "Bosnian": "البوسنية",
  "Catalan": "الكتالانية",
  "Coptic": "القبطية",
  "Cree": "الكرى",
  "Czech": "التشيكية",
  "Church Slavic": "السلافية الكنسية",
  "Welsh": "الويلزية",
  "Danish": "الدانمركية",
  "German": "الألمانية",
  "German (Austria)": "الألمانية (النمسا)",
  "German (Switzerland)": "الألمانية (سويسرا)",
  "German (Germany)": "الألمانية (ألمانيا)",
  "Divehi": "المالديفية",
  "Greek": "اليونانية",
  "English": "الإنجليزية",
  "English (Australia)": "الإنجليزية (أستراليا)",
  "English (Canada)": "الإنجليزية (كندا)",
  "English (United Kingdom)": "الإنجليزية (المملكة المتحدة)",
  "English (Ireland)": "الإنجليزية (أيرلندا)",
  "English (India)": "الإنجليزية (الهند)",
  "English (Trinidad)": "الإنجليزية (ترينيداد)",
  "English (United States)": "الإنجليزية (الولايات المتحدة)",
  "English (South Africa)": "الإنجليزية (جنوب أفريقيا)",
  "Esperanto": "الإسبرانتو",
  "Spanish": "الإسبانية",
  "Spanish (Argentina)": "الإسبانية (الأرجنتين)",
  "Spanish (Chile)": "الإسبانية (تشيلي)",
  "Spanish (Colombia)": "الإسبانية (كولومبيا)",
  "Spanish (Costa Rica)": "الإسبانية (كوستاريكا)",
  "Spanish (Spain)": "الإسبانية (إسبانيا)",
  "Spanish (Mexico)": "الإسبانية (المكسيك)",
  "Spanish (Peru)": "الإسبانية (بيرو)",
  "Estonian": "الإستونية",
  "Basque": "الباسكية",
  "Persian": "الفارسية",
  "Dari": "الدارية",
  "Persian (Iran)": "الفارسية (إيران)",
  "Fula": "الفولانية",
  "Finnish": "الفنلندية",
  "Finnish (Finland)": "الفنلندية (فنلندا)",
  "Filipino": "الفلبينية",
  "French": "الفرنسية",
  "French (Belgium)": "الفرنسية (بلجيكا)",
  "French (Canada)": "الفرنسية (كندا)",
  "French (Switzerland)": "الفرنسية (سويسرا)",
  "Irish": "الأيرلندية",
  "Galician": "الجاليكية",
  "Greek (Ancient)": "اليونانية (القديمة)",
  "Hausa": "الهوسا",
  "Hebrew": "العبرية",
  "Hebrew (Israel)": "العبرية (إسرائيل)",
  "Hindi": "الهندية",
  "Croatian": "الكرواتية",
  "Croatian (Croatia)": "الكرواتية (كرواتيا)",
  "Haitian Creole": "الكريولية الهايتية",
  "Hungarian": "الهنغارية",
  "Hungarian (Hungary)": "الهنغارية (هنغاريا)",
  "Armenian": "الأرمنية",
  "Indonesian": "الإندونيسية",
  "Igbo": "الإيجبو",
  "Icelandic": "الأيسلندية",
  "Italian": "الإيطالية",
  "Italian (Italy)": "الإيطالية (إيطاليا)",
  "Inuktitut": "الإينكتيتت",
  "Japanese": "اليابانية",
  "Japanese (Japan)": "اليابانية (اليابان)",
  "Georgian": "الجورجية",
  "Kabyle": "القبيلية",
  "Kazakh": "الكازاخية",
  "Khmer": "الخميرية",
  "Kannada": "الكانادا",
  "Korean": "الكورية",
  "Korean (Korea)": "الكورية (كوريا)",
  "Latin": "اللاتينية",
  "Lakota": "لاكوتا",
  "Lao": "اللاوية",
  "Lithuanian": "الليتوانية",
  "Latvian": "اللاتفية",
  "Māori": "الماورية",
  "Mongolian": "المنغولية",
  "Marathi": "الماراثية",
  "Malay": "الماليزية",
  "Maltese": "المالطية",
  "Burmese": "البورمية",
  "Norwegian (Bokmål)": "النرويجية (بوكمال)",
  "Norwegian (Bokmål, Norway)": "النرويجية (بوكمال، النرويج)",
  "Nepali": "النيبالية",
  "Dutch": "الهولندية",
  "Flemish": "الفلمنكية",
  "Norwegian (Nynorsk)": "النرويجية (نينورسك)",
  "Navajo": "النافاجو",
  "Turkish (Ottoman)": "التركية (العثمانية)",
  "Punjabi": "البنجابية",
  "Persian (Old)": "الفارسية (القديمة)",
  "Polish": "البولندية",
  "Pashto": "البشتو",
  "Portuguese": "البرتغالية",
  "Portuguese (Brazil)": "البرتغالية (البرازيل)",
  "Portuguese (Portugal)": "البرتغالية (البرتغال)",
  "Quechua": "الكيشوا",
  "Romanian": "الرومانية",
  "Russian": "الروسية",
  "Kinyarwanda": "الكينيارواندا",
  "Sanskrit": "السنسكريتية",
  "Sami (Northern)": "السامي (الشمالية)",
  "Sinhala": "السنهالية",
  "Slovak": "السلوفاكية",
  "Slovak (Slovakia)": "السلوفاكية (سلوفاكيا)",
  "Slovenian": "السلوفينية",
  "Slovenian (Slovenia)": "السلوفينية (سلوفينيا)",
  "Sami (Southern)": "السامي (الجنوبية)",
  "Sami (Northern)": "السامي (الشمالية)",
  "Sami (Lule)": "السامي (لولي)",
  "Shona": "الشونا",
  "Serbian": "الصربية",
  "Serbian (Latin)": "الصربية (لاتينية)",
  "Swedish": "السويدية",
  "Swedish (Sweden)": "السويدية (السويد)",
  "Swahili": "السواحيلية",
  "Swahili (Kenya)": "السواحيلية (كينيا)",
  "Swahili (Tanzania)": "السواحيلية (تنزانيا)",
  "Syriac (Classical)": "السريانية (الكلاسيكية)",
  "Tamil": "التاميلية",
  "Telugu": "التيلوجو",
  "Tajik": "الطاجيكية",
  "Thai": "التايلاندية",
  "Thai (Thailand)": "التايلاندية (تايلاند)",
  "Turkmen": "التركمانية",
  "Tagalog": "التاجالوجية",
  "Turkish": "التركية",
  "Turkish (Turkey)": "التركية (تركيا)",
  "Tatar": "التترية",
  "Uyghur": "الأويغورية",
  "Ukrainian": "الأوكرانية",
  "Urdu": "الأوردية",
  "Uzbek": "الأوزبكية",
  "Vietnamese": "الفيتنامية",
  "Wolof": "الولوفية",
  "Xhosa": "الخوسا",
  "Yiddish": "اليديشية",
  "Yoruba": "اليوروبا",
  "Maya (Yucatec)": "المايا (يوكاتيك)",
  "Chinese": "الصينية",
  "Chinese (Simplified)": "الصينية (المبسطة)",
  "Chinese (Simplified)": "الصينية (المبسطة)",
  "Chinese (Traditional)": "الصينية (التقليدية)",
  "Chinese (Hong Kong)": "الصينية (هونغ كونغ)",
  "Chinese (Singapore)": "الصينية (سنغافورة)",
  "Chinese (Traditional)": "الصينية (التقليدية)",
  "Zulu": "الزولو",
  "Zulu": "الزولو (جنوب أفريقيا)"
});