tinymce.addI18n("cs", {
  "-Language Not Set-": "-Jazyk není nastaven-",
  "Choose from list": "Vybrat ze seznamu",
  "Choose languages": "Vybrat jazyky",
  "Choose up to six languages": "Vyberte až šest jazyků",
  "Configure languages": "Konfigurovat jazyky",
  "Current language:": "Aktuální jazyk:",
  "Enter a valid language code with no spaces. Or, press cancel.":"Zadejte platný kód jazyka bez mezer. Nebo stiskněte zrušit.",
  "Enter manually": "Zadat ručně",
  "Enter new lang code (e.g., \"en-US\"):": "Zadejte nový kód jazyka (např. \"cs-CZ\"):",
  "Indicate current language": "Označit aktuální jazyk",
  "Manually enter language {{number}}:": "Ručně zadat jazyk {{number}}:",
  "New Language:": "Nový jazyk:",
  "None": "Žádný",
  "Other - Enter manually": "Jiný - Zadat ručně",
  "Really remove all language markup from the document?": "Opravdu odstranit všechny jazykové značky z dokumentu?",
  "Remove All lang markup": "Odstranit všechny jazykové značky",
  "Remove Language Markup": "Odstranit jazykové značky",
  "Remove current lang value": "Odstranit aktuální hodnotu jazyka",
  "Reveal lang markup": "Zobrazit jazykové značky",
  "Select language {{number}}:": "Vybrat jazyk {{number}}:",
  "Select the document's default language.": "Vyberte výchozí jazyk dokumentu.",
  "Set default document language": "Nastavit výchozí jazyk dokumentu",
  "Set text language": "Nastavit jazyk textu",
  "Afrikaans": "afrikánština",
  "Afrikaans": "afrikánština (Jižní Afrika)",
  "Akan": "akanština",
  "Amharic": "amharština",
  "Arabic": "arabština",
  "Arabic (Egypt)": "arabština (Egypt)",
  "Arabic (Morocco)": "arabština (Maroko)",
  "Arabic (Saudi Arabia)": "arabština (Saúdská Arábie)",
  "Azerbaijani": "ázerbájdžánština",
  "Belarusian": "běloruština",
  "Bulgarian": "bulharština",
  "Bulgarian (Bulgaria)": "bulharština (Bulharsko)",
  "Bhojpuri": "bhódžpurština",
  "Bambara": "bambarština",
  "Bangla": "bengálština",
  "Tibetan": "tibetština",
  "Bosnian": "bosenština",
  "Catalan": "katalánština",
  "Coptic": "koptština",
  "Cree": "kríjština",
  "Czech": "čeština",
  "Church Slavic": "staroslověnština",
  "Welsh": "velština",
  "Danish": "dánština",
  "German": "němčina",
  "German (Austria)": "němčina (Rakousko)",
  "German (Switzerland)": "němčina (Švýcarsko)",
  "German (Germany)": "němčina (Německo)",
  "Divehi": "maledivština",
  "Greek": "řečtina",
  "English": "angličtina",
  "English (Australia)": "angličtina (Austrálie)",
  "English (Canada)": "angličtina (Kanada)",
  "English (United Kingdom)": "angličtina (Velká Británie)",
  "English (Ireland)": "angličtina (Irsko)",
  "English (India)": "angličtina (Indie)",
  "English (Trinidad)": "angličtina (Trinidad)",
  "English (United States)": "angličtina (USA)",
  "English (South Africa)": "angličtina (Jižní Afrika)",
  "Esperanto": "esperanto",
  "Spanish": "španělština",
  "Spanish (Argentina)": "španělština (Argentina)",
  "Spanish (Chile)": "španělština (Chile)",
  "Spanish (Colombia)": "španělština (Kolumbie)",
  "Spanish (Costa Rica)": "španělština (Kostarika)",
  "Spanish (Spain)": "španělština (Španělsko)",
  "Spanish (Mexico)": "španělština (Mexiko)",
  "Spanish (Peru)": "španělština (Peru)",
  "Estonian": "estonština",
  "Basque": "baskičtina",
  "Persian": "perština",
  "Dari": "darí",
  "Persian (Iran)": "perština (Írán)",
  "Fula": "fulbština",
  "Finnish": "finština",
  "Finnish (Finland)": "finština (Finsko)",
  "Filipino": "filipínština",
  "French": "francouzština",
  "French (Belgium)": "francouzština (Belgie)",
  "French (Canada)": "francouzština (Kanada)",
  "French (Switzerland)": "francouzština (Švýcarsko)",
  "Irish": "irština",
  "Galician": "galicijština",
  "Greek (Ancient)": "starořečtina",
  "Hausa": "hauština",
  "Hebrew": "hebrejština",
  "Hebrew (Israel)": "hebrejština (Izrael)",
  "Hindi": "hindština",
  "Croatian": "chorvatština",
  "Croatian (Croatia)": "chorvatština (Chorvatsko)",
  "Haitian Creole": "haitština",
  "Hungarian": "maďarština",
  "Hungarian (Hungary)": "maďarština (Maďarsko)",
  "Armenian": "arménština",
  "Indonesian": "indonéština",
  "Igbo": "igboština",
  "Icelandic": "islandština",
  "Italian": "italština",
  "Italian (Italy)": "italština (Itálie)",
  "Inuktitut": "inuktitutština",
  "Japanese": "japonština",
  "Japanese (Japan)": "japonština (Japonsko)",
  "Georgian": "gruzínština",
  "Kabyle": "kabylština",
  "Kazakh": "kazaština",
  "Khmer": "khmérština",
  "Kannada": "kannadština",
  "Korean": "korejština",
  "Korean (Korea)": "korejština (Korea)",
  "Latin": "latina",
  "Lakota": "lakotština",
  "Lao": "laoština",
  "Lithuanian": "litevština",
  "Latvian": "lotyština",
  "Māori": "maorština",
  "Mongolian": "mongolština",
  "Marathi": "maráthština",
  "Malay": "malajština",
  "Maltese": "maltština",
  "Burmese": "barmština",
  "Norwegian (Bokmål)": "norština (bokmål)",
  "Norwegian (Bokmål, Norway)": "norština (bokmål, Norsko)",
  "Nepali": "nepálština",
  "Dutch": "nizozemština",
  "Flemish": "vlámština",
  "Norwegian (Nynorsk)": "norština (nynorsk)",
  "Navajo": "navažština",
  "Turkish (Ottoman)": "turečtina (osmanská)",
  "Punjabi": "paňdžábština",
  "Persian (Old)": "perština (stará)",
  "Polish": "polština",
  "Pashto": "paštština",
  "Portuguese": "portugalština",
  "Portuguese (Brazil)": "portugalština (Brazílie)",
  "Portuguese (Portugal)": "portugalština (Portugalsko)",
  "Quechua": "kečuánština",
  "Romanian": "rumunština",
  "Russian": "ruština",
  "Kinyarwanda": "kiňarwandština",
  "Sanskrit": "sanskrt",
  "Sami (Northern)": "sámština (severní)",
  "Sinhala": "sinhálština",
  "Slovak": "slovenština",
  "Slovak (Slovakia)": "slovenština (Slovensko)",
  "Slovenian": "slovinština",
  "Slovenian (Slovenia)": "slovinština (Slovinsko)",
  "Sami (Southern)": "sámština (jižní)",
  "Sami (Northern)": "sámština (severní)",
  "Sami (Lule)": "sámština (lulejská)",
  "Shona": "šonština",
  "Serbian": "srbština",
  "Serbian (Latin)": "srbština (latinka)",
  "Swedish": "švédština",
  "Swedish (Sweden)": "švédština (Švédsko)",
  "Swahili": "svahilština",
  "Swahili (Kenya)": "svahilština (Keňa)",
  "Swahili (Tanzania)": "svahilština (Tanzanie)",
  "Syriac (Classical)": "syrština (klasická)",
  "Tamil": "tamilština",
  "Telugu": "telugština",
  "Tajik": "tádžičtina",
  "Thai": "thajština",
  "Thai (Thailand)": "thajština (Thajsko)",
  "Turkmen": "turkmenština",
  "Tagalog": "tagalog",
  "Turkish": "turečtina",
  "Turkish (Turkey)": "turečtina (Turecko)",
  "Tatar": "tatarština",
  "Uyghur": "ujgurština",
  "Ukrainian": "ukrajinština",
  "Urdu": "urdština",
  "Uzbek": "uzbečtina",
  "Vietnamese": "vietnamština",
  "Wolof": "wolofština",
  "Xhosa": "xhoština",
  "Yiddish": "jidiš",
  "Yoruba": "jorubština",
  "Maya (Yucatec)": "mayština (yukatéčtina)",
  "Chinese": "čínština",
  "Chinese (Simplified)": "čínština (zjednodušená)",
  "Chinese (Simplified)": "čínština (zjednodušená)",
  "Chinese (Traditional)": "čínština (tradiční)",
  "Chinese (Hong Kong)": "čínština (Hongkong)",
  "Chinese (Singapore)": "čínština (Singapur)",
  "Chinese (Traditional)": "čínština (Tchaj-wan)",
  "Zulu": "zuluština",
  "Zulu": "zuluština (Jižní Afrika)"
});