tinymce.addI18n('cy', {
  "-Language Not Set-": "-Iaith heb ei gosod-",
  "Choose from list": "Dewis o'r rhestr",
  "Choose languages": "Dewis ieithoedd",
  "Choose up to six languages": "Dewis hyd at chwe iaith",
  "Configure languages": "Ffurfweddu ieithoedd",
  "Current language:": "Iaith bresennol:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Rhoi cod iaith dilys heb fylchau. Neu, pwyswch canslo.",
  "Enter manually": "Rhoi i mewn â llaw",
  "Enter new lang code (e.g., \"en-US\"):": "Rhoi cod iaith newydd (e.e., \"cy-GB\"):",
  "Indicate current language": "Nodi'r iaith bresennol",
  "Manually enter language {{number}}:": "Rhoi iaith {{number}} i mewn â llaw:",
  "New Language:": "Iaith newydd:",
  "None": "Dim",
  "Other - Enter manually": "Arall - Rhoi i mewn â llaw",
  "Really remove all language markup from the document?": "Wir dynnu'r holl farcio iaith o'r ddogfen?",
  "Remove All lang markup": "Tynnu'r holl farcio iaith",
  "Remove Language Markup": "Tynnu marcio iaith",
  "Remove current lang value": "Tynnu gwerth iaith bresennol",
  "Reveal lang markup": "Datgelu marcio iaith",
  "Select language {{number}}:": "Dewis iaith {{number}}:",
  "Select the document's default language.": "Dewis iaith rhagosodedig y ddogfen.",
  "Set default document language": "Gosod iaith rhagosodedig y ddogfen",
  "Set text language": "Gosod iaith y testun",
  "Afrikaans": "affricaneg",
  "Afrikaans": "affricaneg (De Affrica)",
  "Akan": "acaneg",
  "Amharic": "amhareg",
  "Arabic": "arabeg",
  "Arabic (Egypt)": "arabeg (Aifft)",
  "Arabic (Morocco)": "arabeg (Moroco)",
  "Arabic (Saudi Arabia)": "arabeg (Saudi Arabia)",
  "Azerbaijani": "aserbaijaneg",
  "Belarusian": "belarwseg",
  "Bulgarian": "bwlgareg",
  "Bulgarian (Bulgaria)": "bwlgareg (Bwlgaria)",
  "Bhojpuri": "bhojpuri",
  "Bambara": "bambareg",
  "Bangla": "bengaleg",
  "Tibetan": "tibeteg",
  "Bosnian": "bosnieg",
  "Catalan": "catalaneg",
  "Coptic": "copteg",
  "Cree": "cri",
  "Czech": "tsieceg",
  "Church Slavic": "hen slafoneg",
  "Welsh": "cymraeg",
  "Danish": "daneg",
  "German": "almaeneg",
  "German (Austria)": "almaeneg (Awstria)",
  "German (Switzerland)": "almaeneg (y Swistir)",
  "German (Germany)": "almaeneg (Almaen)",
  "Divehi": "difehi",
  "Greek": "groeg",
  "English": "saesneg",
  "English (Australia)": "saesneg (Awstralia)",
  "English (Canada)": "saesneg (Canada)",
  "English (United Kingdom)": "saesneg (Prydain Fawr)",
  "English (Ireland)": "saesneg (Iwerddon)",
  "English (India)": "saesneg (India)",
  "English (Trinidad)": "saesneg (Trinidad)",
  "English (United States)": "saesneg (Unol Daleithiau)",
  "English (South Africa)": "saesneg (De Affrica)",
  "Esperanto": "esperanto",
  "Spanish": "sbaeneg",
  "Spanish (Argentina)": "sbaeneg (Ariannin)",
  "Spanish (Chile)": "sbaeneg (Chile)",
  "Spanish (Colombia)": "sbaeneg (Colombia)",
  "Spanish (Costa Rica)": "sbaeneg (Costa Rica)",
  "Spanish (Spain)": "sbaeneg (Sbaen)",
  "Spanish (Mexico)": "sbaeneg (Mecsico)",
  "Spanish (Peru)": "sbaeneg (Periw)",
  "Estonian": "estoneg",
  "Basque": "basgeg",
  "Persian": "perseg",
  "Dari": "dari",
  "Persian (Iran)": "perseg (Iran)",
  "Fula": "ffwla",
  "Finnish": "ffinneg",
  "Finnish (Finland)": "ffinneg (y Ffindir)",
  "Filipino": "ffilipineg",
  "French": "ffrangeg",
  "French (Belgium)": "ffrangeg (Gwlad Belg)",
  "French (Canada)": "ffrangeg (Canada)",
  "French (Switzerland)": "ffrangeg (y Swistir)",
  "Irish": "gwyddeleg",
  "Galician": "galisieg",
  "Greek (Ancient)": "groeg (hynafol)",
  "Hausa": "hawsa",
  "Hebrew": "hebraeg",
  "Hebrew (Israel)": "hebraeg (Israel)",
  "Hindi": "hindi",
  "Croatian": "croateg",
  "Croatian (Croatia)": "croateg (Croatia)",
  "Haitian Creole": "creol Haiti",
  "Hungarian": "hwngareg",
  "Hungarian (Hungary)": "hwngareg (Hwngari)",
  "Armenian": "armeneg",
  "Indonesian": "indoneseg",
  "Igbo": "igbo",
  "Icelandic": "islandeg",
  "Italian": "eidaleg",
  "Italian (Italy)": "eidaleg (yr Eidal)",
  "Inuktitut": "inwctitwt",
  "Japanese": "japaneeg",
  "Japanese (Japan)": "japaneeg (Japan)",
  "Georgian": "georgeg",
  "Kabyle": "cabileg",
  "Kazakh": "casacheg",
  "Khmer": "chmereg",
  "Kannada": "kannada",
  "Korean": "coreeg",
  "Korean (Korea)": "coreeg (Corea)",
  "Latin": "lladin",
  "Lakota": "lakota",
  "Lao": "laoeg",
  "Lithuanian": "lithwaneg",
  "Latvian": "latfieg",
  "Māori": "māori",
  "Mongolian": "mongoleg",
  "Marathi": "marathi",
  "Malay": "maleieg",
  "Maltese": "malteg",
  "Burmese": "byrmaneg",
  "Norwegian (Bokmål)": "norwyeg (bokmål)",
  "Norwegian (Bokmål, Norway)": "norwyeg (bokmål, Norwy)",
  "Nepali": "nepaleg",
  "Dutch": "iseldireg",
  "Flemish": "fflemeg",
  "Norwegian (Nynorsk)": "norwyeg (nynorsk)",
  "Navajo": "nafaho",
  "Turkish (Ottoman)": "tyrceg (otoman)",
  "Punjabi": "pwnjabeg",
  "Persian (Old)": "perseg (hynafol)",
  "Polish": "pwyleg",
  "Pashto": "pashto",
  "Portuguese": "portiwgaleg",
  "Portuguese (Brazil)": "portiwgaleg (Brasil)",
  "Portuguese (Portugal)": "portiwgaleg (Portiwgal)",
  "Quechua": "quechua",
  "Romanian": "rwmaneg",
  "Russian": "rwseg",
  "Kinyarwanda": "ciniarŵandeg",
  "Sanskrit": "sansgrit",
  "Sami (Northern)": "sami (gogleddol)",
  "Sinhala": "sinhaleg",
  "Slovak": "slofaceg",
  "Slovak (Slovakia)": "slofaceg (Slofacia)",
  "Slovenian": "slofeneg",
  "Slovenian (Slovenia)": "slofeneg (Slofenia)",
  "Sami (Southern)": "sami (deheuol)",
  "Sami (Northern)": "sami (gogleddol)",
  "Sami (Lule)": "sami (lwle)",
  "Shona": "shona",
  "Serbian": "serbeg",
  "Serbian (Latin)": "serbeg (lladin)",
  "Swedish": "swedeg",
  "Swedish (Sweden)": "swedeg (Sweden)",
  "Swahili": "swahili",
  "Swahili (Kenya)": "swahili (Kenya)",
  "Swahili (Tanzania)": "swahili (Tanzania)",
  "Syriac (Classical)": "syrieg (clasurol)",
  "Tamil": "tamileg",
  "Telugu": "telugu",
  "Tajik": "tajiceg",
  "Thai": "thai",
  "Thai (Thailand)": "thai (Gwlad Thai)",
  "Turkmen": "tyrcmeneg",
  "Tagalog": "tagalog",
  "Turkish": "tyrceg",
  "Turkish (Turkey)": "tyrceg (Twrci)",
  "Tatar": "tatareg",
  "Uyghur": "uighur",
  "Ukrainian": "wcreineg",
  "Urdu": "wrdw",
  "Uzbek": "wsbeceg",
  "Vietnamese": "fietnameg",
  "Wolof": "woloff",
  "Xhosa": "xhosa",
  "Yiddish": "iddew-almaeneg",
  "Yoruba": "iorwba",
  "Maya (Yucatec)": "maya (yucatec)",
  "Chinese": "tsieinëeg",
  "Chinese (Simplified)": "tsieinëeg (symledig)",
  "Chinese (Simplified)": "tsieinëeg (symledig)",
  "Chinese (Traditional)": "tsieinëeg (traddodiadol)",
  "Chinese (Hong Kong)": "tsieinëeg (Hong Kong)",
  "Chinese (Singapore)": "tsieinëeg (Singapore)",
  "Chinese (Traditional)": "tsieinëeg (traddodiadol)",
  "Zulu": "swlw",
  "Zulu": "swlw (De Affrica)"
});