tinymce.addI18n('da_x_k12', {
  "-Language Not Set-": "-Intet sprog valgt-",
  "Choose from list": "Vælg fra liste",
  "Choose languages": "Vælg sprog",
  "Choose up to six languages": "Vælg op til seks sprog",
  "Configure languages": "Indstil sprog",
  "Current language:": "Nuværende sprog:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Skriv en gyldig sprogkode uden mellemrum. Eller tryk annuller.",
  "Enter manually": "Skriv selv",
  "Enter new lang code (e.g., \"en-US\"):": "Skriv ny sprogkode (f.eks. \"da-DK\"):",
  "Indicate current language": "Vis nuværende sprog",
  "Manually enter language {{number}}:": "Skriv sprog {{number}} selv:",
  "New Language:": "Nyt sprog:",
  "None": "Ingen",
  "Other - Enter manually": "Andet - Skriv selv",
  "Really remove all language markup from the document?": "Vil du virkelig fjerne al sprogmærkning fra dokumentet?",
  "Remove All lang markup": "Fjern al sprogmærkning",
  "Remove Language Markup": "Fjern sprogmærkning",
  "Remove current lang value": "Fjern nuværende sprog",
  "Reveal lang markup": "Vis sprogmærkning",
  "Select language {{number}}:": "Vælg sprog {{number}}:",
  "Select the document's default language.": "Vælg dokumentets standardsprog.",
  "Set default document language": "Vælg standardsprog for dokumentet",
  "Set text language": "Vælg sprog for tekst",
  "Afrikaans": "afrikaans",
  "Afrikaans": "afrikaans (Sydafrika)",
  "Akan": "akan",
  "Amharic": "amharisk",
  "Arabic": "arabisk",
  "Arabic (Egypt)": "arabisk (Egypten)",
  "Arabic (Morocco)": "arabisk (Marokko)",
  "Arabic (Saudi Arabia)": "arabisk (Saudi-Arabien)",
  "Azerbaijani": "aserbajdsjansk",
  "Belarusian": "belarusisk",
  "Bulgarian": "bulgarsk",
  "Bulgarian (Bulgaria)": "bulgarsk (Bulgarien)",
  "Bhojpuri": "bhojpuri",
  "Bambara": "bambara",
  "Bangla": "bengali",
  "Tibetan": "tibetansk",
  "Bosnian": "bosnisk",
  "Catalan": "catalansk",
  "Coptic": "koptisk",
  "Cree": "cree",
  "Czech": "tjekkisk",
  "Church Slavic": "kirkeslavisk",
  "Welsh": "walisisk",
  "Danish": "dansk",
  "German": "tysk",
  "German (Austria)": "tysk (Østrig)",
  "German (Switzerland)": "tysk (Schweiz)",
  "German (Germany)": "tysk (Tyskland)",
  "Divehi": "divehi",
  "Greek": "græsk",
  "English": "engelsk",
  "English (Australia)": "engelsk (Australien)",
  "English (Canada)": "engelsk (Canada)",
  "English (United Kingdom)": "engelsk (Storbritannien)",
  "English (Ireland)": "engelsk (Irland)",
  "English (India)": "engelsk (Indien)",
  "English (Trinidad)": "engelsk (Trinidad)",
  "English (United States)": "engelsk (USA)",
  "English (South Africa)": "engelsk (Sydafrika)",
  "Esperanto": "esperanto",
  "Spanish": "spansk",
  "Spanish (Argentina)": "spansk (Argentina)",
  "Spanish (Chile)": "spansk (Chile)",
  "Spanish (Colombia)": "spansk (Colombia)",
  "Spanish (Costa Rica)": "spansk (Costa Rica)",
  "Spanish (Spain)": "spansk (Spanien)",
  "Spanish (Mexico)": "spansk (Mexico)",
  "Spanish (Peru)": "spansk (Peru)",
  "Estonian": "estisk",
  "Basque": "baskisk",
  "Persian": "persisk",
  "Dari": "dari",
  "Persian (Iran)": "persisk (Iran)",
  "Fula": "fulah",
  "Finnish": "finsk",
  "Finnish (Finland)": "finsk (Finland)",
  "Filipino": "filippinsk",
  "French": "fransk",
  "French (Belgium)": "fransk (Belgien)",
  "French (Canada)": "fransk (Canada)",
  "French (Switzerland)": "fransk (Schweiz)",
  "Irish": "irsk",
  "Galician": "galicisk",
  "Greek (Ancient)": "græsk (oldtids)",
  "Hausa": "hausa",
  "Hebrew": "hebraisk",
  "Hebrew (Israel)": "hebraisk (Israel)",
  "Hindi": "hindi",
  "Croatian": "kroatisk",
  "Croatian (Croatia)": "kroatisk (Kroatien)",
  "Haitian Creole": "haitisk",
  "Hungarian": "ungarsk",
  "Hungarian (Hungary)": "ungarsk (Ungarn)",
  "Armenian": "armensk",
  "Indonesian": "indonesisk",
  "Igbo": "igbo",
  "Icelandic": "islandsk",
  "Italian": "italiensk",
  "Italian (Italy)": "italiensk (Italien)",
  "Inuktitut": "inuktitut",
  "Japanese": "japansk",
  "Japanese (Japan)": "japansk (Japan)",
  "Georgian": "georgisk",
  "Kabyle": "kabylsk",
  "Kazakh": "kasakhisk",
  "Khmer": "khmer",
  "Kannada": "kannada",
  "Korean": "koreansk",
  "Korean (Korea)": "koreansk (Korea)",
  "Latin": "latin",
  "Lakota": "lakota",
  "Lao": "lao",
  "Lithuanian": "litauisk",
  "Latvian": "lettisk",
  "Māori": "maori",
  "Mongolian": "mongolsk",
  "Marathi": "marathi",
  "Malay": "malajisk",
  "Maltese": "maltesisk",
  "Burmese": "burmesisk",
  "Norwegian (Bokmål)": "norsk (bokmål)",
  "Norwegian (Bokmål, Norway)": "norsk (bokmål, Norge)",
  "Nepali": "nepalesisk",
  "Dutch": "nederlandsk",
  "Flemish": "flamsk",
  "Norwegian (Nynorsk)": "norsk (nynorsk)",
  "Navajo": "navajo",
  "Turkish (Ottoman)": "tyrkisk (osmannisk)",
  "Punjabi": "punjabi",
  "Persian (Old)": "persisk (oldtids)",
  "Polish": "polsk",
  "Pashto": "pashto",
  "Portuguese": "portugisisk",
  "Portuguese (Brazil)": "portugisisk (Brasilien)",
  "Portuguese (Portugal)": "portugisisk (Portugal)",
  "Quechua": "quechua",
  "Romanian": "rumænsk",
  "Russian": "russisk",
  "Kinyarwanda": "kinyarwanda",
  "Sanskrit": "sanskrit",
  "Sami (Northern)": "samisk (nord)",
  "Sinhala": "singalesisk",
  "Slovak": "slovakisk",
  "Slovak (Slovakia)": "slovakisk (Slovakiet)",
  "Slovenian": "slovensk",
  "Slovenian (Slovenia)": "slovensk (Slovenien)",
  "Sami (Southern)": "samisk (syd)",
  "Sami (Northern)": "samisk (nord)",
  "Sami (Lule)": "samisk (lule)",
  "Shona": "shona",
  "Serbian": "serbisk",
  "Serbian (Latin)": "serbisk (latin)",
  "Swedish": "svensk",
  "Swedish (Sweden)": "svensk (Sverige)",
  "Swahili": "swahili",
  "Swahili (Kenya)": "swahili (Kenya)",
  "Swahili (Tanzania)": "swahili (Tanzania)",
  "Syriac (Classical)": "syrisk (klassisk)",
  "Tamil": "tamil",
  "Telugu": "telugu",
  "Tajik": "tadsjikisk",
  "Thai": "thai",
  "Thai (Thailand)": "thai (Thailand)",
  "Turkmen": "turkmensk",
  "Tagalog": "tagalog",
  "Turkish": "tyrkisk",
  "Turkish (Turkey)": "tyrkisk (Tyrkiet)",
  "Tatar": "tatarisk",
  "Uyghur": "uygurisk",
  "Ukrainian": "ukrainsk",
  "Urdu": "urdu",
  "Uzbek": "usbekisk",
  "Vietnamese": "vietnamesisk",
  "Wolof": "wolof",
  "Xhosa": "xhosa",
  "Yiddish": "jiddisch",
  "Yoruba": "yoruba",
  "Maya (Yucatec)": "maya (yucatec)",
  "Chinese": "kinesisk",
  "Chinese (Simplified)": "kinesisk (forenklet)",
  "Chinese (Simplified)": "kinesisk (forenklet)",
  "Chinese (Traditional)": "kinesisk (traditionelt)",
  "Chinese (Hong Kong)": "kinesisk (Hong Kong)",
  "Chinese (Singapore)": "kinesisk (Singapore)",
  "Chinese (Traditional)": "kinesisk (traditionelt)",
  "Zulu": "zulu",
  "Zulu": "zulu (Sydafrika)"
});