tinymce.addI18n('en_GB', {
  "-Language Not Set-": "-Language Not Set-",
  "Choose from list": "Choose from list",
  "Choose languages": "Choose languages",
  "Choose up to six languages": "Choose up to six languages",
  "Configure languages": "Configure languages",
  "Current language:": "Current language:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Enter a valid language code with no spaces. Or, press cancel.",
  "Enter manually": "Enter manually",
  "Enter new lang code (e.g., \"en-US\"):": "Enter new lang code (e.g., \"en-GB\"):",
  "Indicate current language": "Indicate current language",
  "Manually enter language {{number}}:": "Manually enter language {{number}}:",
  "New Language:": "New Language:",
  "None": "None",
  "Other - Enter manually": "Other - Enter manually",
  "Really remove all language markup from the document?": "Really remove all language markup from the document?",
  "Remove All lang markup": "Remove All lang markup",
  "Remove Language Markup": "Remove Language Markup",
  "Remove current lang value": "Remove current lang value",
  "Reveal lang markup": "Reveal lang markup",
  "Select language {{number}}:": "Select language {{number}}:",
  "Select the document's default language.": "Select the document's default language.",
  "Set default document language": "Set default document language",
  "Set text language": "Set text language",
  "Afrikaans": "Afrikaans",
  "Afrikaans": "Afrikaans",
  "Akan": "Akan",
  "Amharic": "Amharic",
  "Arabic": "Arabic",
  "Arabic (Egypt)": "Arabic (Egypt)",
  "Arabic (Morocco)": "Arabic (Morocco)",
  "Arabic (Saudi Arabia)": "Arabic (Saudi Arabia)",
  "Azerbaijani": "Azerbaijani",
  "Belarusian": "Belarusian",
  "Bulgarian": "Bulgarian",
  "Bulgarian (Bulgaria)": "Bulgarian (Bulgaria)",
  "Bhojpuri": "Bhojpuri",
  "Bambara": "Bambara",
  "Bangla": "Bangla",
  "Tibetan": "Tibetan",
  "Bosnian": "Bosnian",
  "Catalan": "Catalan",
  "Coptic": "Coptic",
  "Cree": "Cree",
  "Czech": "Czech",
  "Church Slavic": "Church Slavic",
  "Welsh": "Welsh",
  "Danish": "Danish",
  "German": "German",
  "German (Austria)": "German (Austria)",
  "German (Switzerland)": "German (Switzerland)",
  "German (Germany)": "German (Germany)",
  "Divehi": "Divehi",
  "Greek": "Greek",
  "English": "English",
  "English (Australia)": "English (Australia)",
  "English (Canada)": "English (Canada)",
  "English (United Kingdom)": "English (United Kingdom)",
  "English (Ireland)": "English (Ireland)",
  "English (India)": "English (India)",
  "English (Trinidad)": "English (Trinidad)",
  "English (United States)": "English (United States)",
  "English (South Africa)": "English (South Africa)",
  "Esperanto": "Esperanto",
  "Spanish": "Spanish",
  "Spanish (Argentina)": "Spanish (Argentina)",
  "Spanish (Chile)": "Spanish (Chile)",
  "Spanish (Colombia)": "Spanish (Colombia)",
  "Spanish (Costa Rica)": "Spanish (Costa Rica)",
  "Spanish (Spain)": "Spanish (Spain)",
  "Spanish (Mexico)": "Spanish (Mexico)",
  "Spanish (Peru)": "Spanish (Peru)",
  "Estonian": "Estonian",
  "Basque": "Basque",
  "Persian": "Persian",
  "Dari": "Dari",
  "Persian (Iran)": "Persian (Iran)",
  "Fula": "Fula",
  "Finnish": "Finnish",
  "Finnish (Finland)": "Finnish (Finland)",
  "Filipino": "Filipino",
  "French": "French",
  "French (Belgium)": "French (Belgium)",
  "French (Canada)": "French (Canada)",
  "French (Switzerland)": "French (Switzerland)",
  "Irish": "Irish",
  "Galician": "Galician",
  "Greek (Ancient)": "Greek (Ancient)",
  "Hausa": "Hausa",
  "Hebrew": "Hebrew",
  "Hebrew (Israel)": "Hebrew (Israel)",
  "Hindi": "Hindi",
  "Croatian": "Croatian",
  "Croatian (Croatia)": "Croatian (Croatia)",
  "Haitian Creole": "Haitian Creole",
  "Hungarian": "Hungarian",
  "Hungarian (Hungary)": "Hungarian (Hungary)",
  "Armenian": "Armenian",
  "Indonesian": "Indonesian",
  "Igbo": "Igbo",
  "Icelandic": "Icelandic",
  "Italian": "Italian",
  "Italian (Italy)": "Italian (Italy)",
  "Inuktitut": "Inuktitut",
  "Japanese": "Japanese",
  "Japanese (Japan)": "Japanese (Japan)",
  "Georgian": "Georgian",
  "Kabyle": "Kabyle",
  "Kazakh": "Kazakh",
  "Khmer": "Khmer",
  "Kannada": "Kannada",
  "Korean": "Korean",
  "Korean (Korea)": "Korean (Korea)",
  "Latin": "Latin",
  "Lakota": "Lakota",
  "Lao": "Lao",
  "Lithuanian": "Lithuanian",
  "Latvian": "Latvian",
  "Māori": "Māori",
  "Mongolian": "Mongolian",
  "Marathi": "Marathi",
  "Malay": "Malay",
  "Maltese": "Maltese",
  "Burmese": "Burmese",
  "Norwegian (Bokmål)": "Norwegian (Bokmål)",
  "Norwegian (Bokmål, Norway)": "Norwegian (Bokmål, Norway)",
  "Nepali": "Nepali",
  "Dutch": "Dutch",
  "Flemish": "Flemish",
  "Norwegian (Nynorsk)": "Norwegian (Nynorsk)",
  "Navajo": "Navajo",
  "Turkish (Ottoman)": "Turkish (Ottoman)",
  "Punjabi": "Punjabi",
  "Persian (Old)": "Persian (Old)",
  "Polish": "Polish",
  "Pashto": "Pashto",
  "Portuguese": "Portuguese",
  "Portuguese (Brazil)": "Portuguese (Brazil)",
  "Portuguese (Portugal)": "Portuguese (Portugal)",
  "Quechua": "Quechua",
  "Romanian": "Romanian",
  "Russian": "Russian",
  "Kinyarwanda": "Kinyarwanda",
  "Sanskrit": "Sanskrit",
  "Sami (Northern)": "Sami (Northern)",
  "Sinhala": "Sinhala",
  "Slovak": "Slovak",
  "Slovak (Slovakia)": "Slovak (Slovakia)",
  "Slovenian": "Slovenian",
  "Slovenian (Slovenia)": "Slovenian (Slovenia)",
  "Sami (Southern)": "Sami (Southern)",
  "Sami (Northern)": "Sami (Northern)",
  "Sami (Lule)": "Sami (Lule)",
  "Shona": "Shona",
  "Serbian": "Serbian",
  "Serbian (Latin)": "Serbian (Latin)",
  "Swedish": "Swedish",
  "Swedish (Sweden)": "Swedish (Sweden)",
  "Swahili": "Swahili",
  "Swahili (Kenya)": "Swahili (Kenya)",
  "Swahili (Tanzania)": "Swahili (Tanzania)",
  "Syriac (Classical)": "Syriac (Classical)",
  "Tamil": "Tamil",
  "Telugu": "Telugu",
  "Tajik": "Tajik",
  "Thai": "Thai",
  "Thai (Thailand)": "Thai (Thailand)",
  "Turkmen": "Turkmen",
  "Tagalog": "Tagalog",
  "Turkish": "Turkish",
  "Turkish (Turkey)": "Turkish (Turkey)",
  "Tatar": "Tatar",
  "Uyghur": "Uyghur",
  "Ukrainian": "Ukrainian",
  "Urdu": "Urdu",
  "Uzbek": "Uzbek",
  "Vietnamese": "Vietnamese",
  "Wolof": "Wolof",
  "Xhosa": "Xhosa",
  "Yiddish": "Yiddish",
  "Yoruba": "Yoruba",
  "Maya (Yucatec)": "Maya (Yucatec)",
  "Chinese": "Chinese",
  "Chinese (Simplified)": "Chinese (Simplified)",
  "Chinese (Simplified)": "Chinese (Simplified)",
  "Chinese (Traditional)": "Chinese (Traditional)",
  "Chinese (Hong Kong)": "Chinese (Hong Kong)",
  "Chinese (Singapore)": "Chinese (Singapore)",
  "Chinese (Traditional)": "Chinese (Traditional)",
  "Zulu": "Zulu",
  "Zulu": "Zulu"
});