tinymce.addI18n('fi_FI', {
  "-Language Not Set-": "-Kieltä ei asetettu-",
  "Choose from list": "Valitse listasta",
  "Choose languages": "Valitse kielet",
  "Choose up to six languages": "Valitse enintään kuusi kieltä",
  "Configure languages": "Määritä kielet",
  "Current language:": "Nykyinen kieli:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Syötä kelvollinen kielikoodi ilman välilyöntejä. Tai paina peruuta.",
  "Enter manually": "Syötä käsin",
  "Enter new lang code (e.g., \"en-US\"):": "Syötä uusi kielikoodi (esim. \"fi-FI\"):",
  "Indicate current language": "Ilmoita nykyinen kieli",
  "Manually enter language {{number}}:": "Syötä kieli {{number}} käsin:",
  "New Language:": "Uusi kieli:",
  "None": "Ei mitään",
  "Other - Enter manually": "Muu - Syötä käsin",
  "Really remove all language markup from the document?": "Poistetaanko todella kaikki kielimerkinnät dokumentista?",
  "Remove All lang markup": "Poista kaikki kielimerkinnät",
  "Remove Language Markup": "Poista kielimerkinnät",
  "Remove current lang value": "Poista nykyinen kieliarvo",
  "Reveal lang markup": "Näytä kielimerkinnät",
  "Select language {{number}}:": "Valitse kieli {{number}}:",
  "Select the document's default language.": "Valitse dokumentin oletuskieli.",
  "Set default document language": "Aseta dokumentin oletuskieli",
  "Set text language": "Aseta tekstin kieli",
  "Afrikaans": "afrikaans",
  "Afrikaans": "afrikaans (Etelä-Afrikka)",
  "Akan": "akan",
  "Amharic": "amhara",
  "Arabic": "arabia",
  "Arabic (Egypt)": "arabia (Egypti)",
  "Arabic (Morocco)": "arabia (Marokko)",
  "Arabic (Saudi Arabia)": "arabia (Saudi-Arabia)",
  "Azerbaijani": "azeri",
  "Belarusian": "valkovenäjä",
  "Bulgarian": "bulgaria",
  "Bulgarian (Bulgaria)": "bulgaria (Bulgaria)",
  "Bhojpuri": "bhodžpuri",
  "Bambara": "bambara",
  "Bangla": "bengali",
  "Tibetan": "tiibet",
  "Bosnian": "bosnia",
  "Catalan": "katalaani",
  "Coptic": "kopti",
  "Cree": "cree",
  "Czech": "tšekki",
  "Church Slavic": "kirkkoslaavi",
  "Welsh": "kymri",
  "Danish": "tanska",
  "German": "saksa",
  "German (Austria)": "saksa (Itävalta)",
  "German (Switzerland)": "saksa (Sveitsi)",
  "German (Germany)": "saksa (Saksa)",
  "Divehi": "divehi",
  "Greek": "kreikka",
  "English": "englanti",
  "English (Australia)": "englanti (Australia)",
  "English (Canada)": "englanti (Kanada)",
  "English (United Kingdom)": "englanti (Iso-Britannia)",
  "English (Ireland)": "englanti (Irlanti)",
  "English (India)": "englanti (Intia)",
  "English (Trinidad)": "englanti (Trinidad)",
  "English (United States)": "englanti (Yhdysvallat)",
  "English (South Africa)": "englanti (Etelä-Afrikka)",
  "Esperanto": "esperanto",
  "Spanish": "espanja",
  "Spanish (Argentina)": "espanja (Argentiina)",
  "Spanish (Chile)": "espanja (Chile)",
  "Spanish (Colombia)": "espanja (Kolumbia)",
  "Spanish (Costa Rica)": "espanja (Costa Rica)",
  "Spanish (Spain)": "espanja (Espanja)",
  "Spanish (Mexico)": "espanja (Meksiko)",
  "Spanish (Peru)": "espanja (Peru)",
  "Estonian": "viro",
  "Basque": "baski",
  "Persian": "persia",
  "Dari": "dari",
  "Persian (Iran)": "persia (Iran)",
  "Fula": "fulani",
  "Finnish": "suomi",
  "Finnish (Finland)": "suomi (Suomi)",
  "Filipino": "filipino",
  "French": "ranska",
  "French (Belgium)": "ranska (Belgia)",
  "French (Canada)": "ranska (Kanada)",
  "French (Switzerland)": "ranska (Sveitsi)",
  "Irish": "iiri",
  "Galician": "galicia",
  "Greek (Ancient)": "kreikka (muinainen)",
  "Hausa": "hausa",
  "Hebrew": "heprea",
  "Hebrew (Israel)": "heprea (Israel)",
  "Hindi": "hindi",
  "Croatian": "kroatia",
  "Croatian (Croatia)": "kroatia (Kroatia)",
  "Haitian Creole": "haiti",
  "Hungarian": "unkari",
  "Hungarian (Hungary)": "unkari (Unkari)",
  "Armenian": "armenia",
  "Indonesian": "indonesia",
  "Igbo": "igbo",
  "Icelandic": "islanti",
  "Italian": "italia",
  "Italian (Italy)": "italia (Italia)",
  "Inuktitut": "inuktitut",
  "Japanese": "japani",
  "Japanese (Japan)": "japani (Japani)",
  "Georgian": "georgia",
  "Kabyle": "kabyyli",
  "Kazakh": "kazakki",
  "Khmer": "khmer",
  "Kannada": "kannada",
  "Korean": "korea",
  "Korean (Korea)": "korea (Korea)",
  "Latin": "latina",
  "Lakota": "lakota",
  "Lao": "lao",
  "Lithuanian": "liettua",
  "Latvian": "latvia",
  "Māori": "maori",
  "Mongolian": "mongoli",
  "Marathi": "marathi",
  "Malay": "malaiji",
  "Maltese": "malta",
  "Burmese": "burma",
  "Norwegian (Bokmål)": "norja (bokmål)",
  "Norwegian (Bokmål, Norway)": "norja (bokmål, Norja)",
  "Nepali": "nepali",
  "Dutch": "hollanti",
  "Flemish": "flaami",
  "Norwegian (Nynorsk)": "norja (nynorsk)",
  "Navajo": "navajo",
  "Turkish (Ottoman)": "turkki (osmani)",
  "Punjabi": "pandžabi",
  "Persian (Old)": "persia (muinainen)",
  "Polish": "puola",
  "Pashto": "paštu",
  "Portuguese": "portugali",
  "Portuguese (Brazil)": "portugali (Brasilia)",
  "Portuguese (Portugal)": "portugali (Portugali)",
  "Quechua": "ketšua",
  "Romanian": "romania",
  "Russian": "venäjä",
  "Kinyarwanda": "ruanda",
  "Sanskrit": "sanskrit",
  "Sami (Northern)": "saame (pohjoinen)",
  "Sinhala": "sinhala",
  "Slovak": "slovakki",
  "Slovak (Slovakia)": "slovakki (Slovakia)",
  "Slovenian": "sloveeni",
  "Slovenian (Slovenia)": "sloveeni (Slovenia)",
  "Sami (Southern)": "saame (eteläinen)",
  "Sami (Northern)": "saame (pohjoinen)",
  "Sami (Lule)": "saame (luulaja)",
  "Shona": "šona",
  "Serbian": "serbia",
  "Serbian (Latin)": "serbia (latinalainen)",
  "Swedish": "ruotsi",
  "Swedish (Sweden)": "ruotsi (Ruotsi)",
  "Swahili": "swahili",
  "Swahili (Kenya)": "swahili (Kenia)",
  "Swahili (Tanzania)": "swahili (Tansania)",
  "Syriac (Classical)": "syyria (muinainen)",
  "Tamil": "tamili",
  "Telugu": "telugu",
  "Tajik": "tadžikki",
  "Thai": "thai",
  "Thai (Thailand)": "thai (Thaimaa)",
  "Turkmen": "turkmeeni",
  "Tagalog": "tagalog",
  "Turkish": "turkki",
  "Turkish (Turkey)": "turkki (Turkki)",
  "Tatar": "tataari",
  "Uyghur": "uiguuri",
  "Ukrainian": "ukraina",
  "Urdu": "urdu",
  "Uzbek": "uzbekki",
  "Vietnamese": "vietnam",
  "Wolof": "wolof",
  "Xhosa": "xhosa",
  "Yiddish": "jiddiš",
  "Yoruba": "joruba",
  "Maya (Yucatec)": "maya (jukateekin)",
  "Chinese": "kiina",
  "Chinese (Simplified)": "kiina (yksinkertaistettu)",
  "Chinese (Simplified)": "kiina (yksinkertaistettu)",
  "Chinese (Traditional)": "kiina (perinteinen)",
  "Chinese (Hong Kong)": "kiina (Hongkong)",
  "Chinese (Singapore)": "kiina (Singapore)",
  "Chinese (Traditional)": "kiina (perinteinen)",
  "Zulu": "zulu",
  "Zulu": "zulu (Etelä-Afrikka)"
});