tinymce.addI18n('fr_CA', {
  "-Language Not Set-": "-Langue Non Définie-",
  "Choose from list": "Choisir dans la liste",
  "Choose languages": "Choisir les langues",
  "Choose up to six languages": "Choisir jusqu'à six langues",
  "Configure languages": "Configurer les langues",
  "Current language:": "Langue actuelle :",
  "Enter a valid language code with no spaces. Or, press cancel.": "Entrer un code de langue valide sans espaces. Ou appuyer sur annuler.",
  "Enter manually": "Entrer manuellement",
  "Enter new lang code (e.g., \"en-US\"):": "Entrer le nouveau code de langue (ex. \"fr-CA\") :",
  "Indicate current language": "Indiquer la langue actuelle",
  "Manually enter language {{number}}:": "Entrer manuellement la langue {{number}} :",
  "New Language:": "Nouvelle Langue :",
  "None": "Aucun",
  "Other - Enter manually": "Autre - Entrer manuellement",
  "Really remove all language markup from the document?": "Vraiment supprimer tout le balisage de langue du document ?",
  "Remove All lang markup": "Supprimer tout le balisage de langue",
  "Remove Language Markup": "Supprimer le Balisage de Langue",
  "Remove current lang value": "Supprimer la valeur de langue actuelle",
  "Reveal lang markup": "Révéler le balisage de langue",
  "Select language {{number}}:": "Sélectionner la langue {{number}} :",
  "Select the document's default language.": "Sélectionner la langue par défaut du document.",
  "Set default document language": "Définir la langue par défaut du document",
  "Set text language": "Définir la langue du texte",
  "Afrikaans": "afrikaans",
  "Afrikaans": "afrikaans (Afrique du Sud)",
  "Akan": "akan",
  "Amharic": "amharique",
  "Arabic": "arabe",
  "Arabic (Egypt)": "arabe (Égypte)",
  "Arabic (Morocco)": "arabe (Maroc)",
  "Arabic (Saudi Arabia)": "arabe (Arabie Saoudite)",
  "Azerbaijani": "azerbaïdjanais",
  "Belarusian": "biélorusse",
  "Bulgarian": "bulgare",
  "Bulgarian (Bulgaria)": "bulgare (Bulgarie)",
  "Bhojpuri": "bhodjpouri",
  "Bambara": "bambara",
  "Bangla": "bengali",
  "Tibetan": "tibétain",
  "Bosnian": "bosniaque",
  "Catalan": "catalan",
  "Coptic": "copte",
  "Cree": "cri",
  "Czech": "tchèque",
  "Church Slavic": "slavon d'église",
  "Welsh": "gallois",
  "Danish": "danois",
  "German": "allemand",
  "German (Austria)": "allemand (Autriche)",
  "German (Switzerland)": "allemand (Suisse)",
  "German (Germany)": "allemand (Allemagne)",
  "Divehi": "maldivien",
  "Greek": "grec",
  "English": "anglais",
  "English (Australia)": "anglais (Australie)",
  "English (Canada)": "anglais (Canada)",
  "English (United Kingdom)": "anglais (Royaume-Uni)",
  "English (Ireland)": "anglais (Irlande)",
  "English (India)": "anglais (Inde)",
  "English (Trinidad)": "anglais (Trinité)",
  "English (United States)": "anglais (États-Unis)",
  "English (South Africa)": "anglais (Afrique du Sud)",
  "Esperanto": "espéranto",
  "Spanish": "espagnol",
  "Spanish (Argentina)": "espagnol (Argentine)",
  "Spanish (Chile)": "espagnol (Chili)",
  "Spanish (Colombia)": "espagnol (Colombie)",
  "Spanish (Costa Rica)": "espagnol (Costa Rica)",
  "Spanish (Spain)": "espagnol (Espagne)",
  "Spanish (Mexico)": "espagnol (Mexique)",
  "Spanish (Peru)": "espagnol (Pérou)",
  "Estonian": "estonien",
  "Basque": "basque",
  "Persian": "persan",
  "Dari": "dari",
  "Persian (Iran)": "persan (Iran)",
  "Fula": "peul",
  "Finnish": "finnois",
  "Finnish (Finland)": "finnois (Finlande)",
  "Filipino": "filipino",
  "French": "français",
  "French (Belgium)": "français (Belgique)",
  "French (Canada)": "français (Canada)",
  "French (Switzerland)": "français (Suisse)",
  "Irish": "irlandais",
  "Galician": "galicien",
  "Greek (Ancient)": "grec ancien",
  "Hausa": "haoussa",
  "Hebrew": "hébreu",
  "Hebrew (Israel)": "hébreu (Israël)",
  "Hindi": "hindi",
  "Croatian": "croate",
  "Croatian (Croatia)": "croate (Croatie)",
  "Haitian Creole": "créole haïtien",
  "Hungarian": "hongrois",
  "Hungarian (Hungary)": "hongrois (Hongrie)",
  "Armenian": "arménien",
  "Indonesian": "indonésien",
  "Igbo": "igbo",
  "Icelandic": "islandais",
  "Italian": "italien",
  "Italian (Italy)": "italien (Italie)",
  "Inuktitut": "inuktitut",
  "Japanese": "japonais",
  "Japanese (Japan)": "japonais (Japon)",
  "Georgian": "géorgien",
  "Kabyle": "kabyle",
  "Kazakh": "kazakh",
  "Khmer": "khmer",
  "Kannada": "kannada",
  "Korean": "coréen",
  "Korean (Korea)": "coréen (Corée)",
  "Latin": "latin",
  "Lakota": "lakota",
  "Lao": "lao",
  "Lithuanian": "lituanien",
  "Latvian": "letton",
  "Māori": "maori",
  "Mongolian": "mongol",
  "Marathi": "marathi",
  "Malay": "malais",
  "Maltese": "maltais",
  "Burmese": "birman",
  "Norwegian (Bokmål)": "norvégien (bokmål)",
  "Norwegian (Bokmål, Norway)": "norvégien (bokmål, Norvège)",
  "Nepali": "népalais",
  "Dutch": "néerlandais",
  "Flemish": "flamand",
  "Norwegian (Nynorsk)": "norvégien (nynorsk)",
  "Navajo": "navajo",
  "Turkish (Ottoman)": "turc ottoman",
  "Punjabi": "pendjabi",
  "Persian (Old)": "vieux perse",
  "Polish": "polonais",
  "Pashto": "pachto",
  "Portuguese": "portugais",
  "Portuguese (Brazil)": "portugais (Brésil)",
  "Portuguese (Portugal)": "portugais (Portugal)",
  "Quechua": "quechua",
  "Romanian": "roumain",
  "Russian": "russe",
  "Kinyarwanda": "kinyarwanda",
  "Sanskrit": "sanskrit",
  "Sami (Northern)": "same du Nord",
  "Sinhala": "cingalais",
  "Slovak": "slovaque",
  "Slovak (Slovakia)": "slovaque (Slovaquie)",
  "Slovenian": "slovène",
  "Slovenian (Slovenia)": "slovène (Slovénie)",
  "Sami (Southern)": "same du Sud",
  "Sami (Northern)": "same du Nord",
  "Sami (Lule)": "same de Lule",
  "Shona": "shona",
  "Serbian": "serbe",
  "Serbian (Latin)": "serbe (latin)",
  "Swedish": "suédois",
  "Swedish (Sweden)": "suédois (Suède)",
  "Swahili": "swahili",
  "Swahili (Kenya)": "swahili (Kenya)",
  "Swahili (Tanzania)": "swahili (Tanzanie)",
  "Syriac (Classical)": "syriaque classique",
  "Tamil": "tamoul",
  "Telugu": "télougou",
  "Tajik": "tadjik",
  "Thai": "thaï",
  "Thai (Thailand)": "thaï (Thaïlande)",
  "Turkmen": "turkmène",
  "Tagalog": "tagalog",
  "Turkish": "turc",
  "Turkish (Turkey)": "turc (Turquie)",
  "Tatar": "tatar",
  "Uyghur": "ouïghour",
  "Ukrainian": "ukrainien",
  "Urdu": "ourdou",
  "Uzbek": "ouzbek",
  "Vietnamese": "vietnamien",
  "Wolof": "wolof",
  "Xhosa": "xhosa",
  "Yiddish": "yiddish",
  "Yoruba": "yoruba",
  "Maya (Yucatec)": "maya du Yucatan",
  "Chinese": "chinois",
  "Chinese (Simplified)": "chinois (simplifié)",
  "Chinese (Simplified)": "chinois (simplifié)",
  "Chinese (Traditional)": "chinois (traditionnel)",
  "Chinese (Hong Kong)": "chinois (Hong Kong)",
  "Chinese (Singapore)": "chinois (Singapour)",
  "Chinese (Traditional)": "chinois (traditionnel)",
  "Zulu": "zoulou",
  "Zulu": "zoulou (Afrique du Sud)"
});