tinymce.addI18n('ga', {
  "-Language Not Set-": "-Teanga gan Socrú-",
  "Choose from list": "Roghnaigh ó liosta",
  "Choose languages": "Roghnaigh teangacha",
  "Choose up to six languages": "Roghnaigh suas le sé theanga",
  "Configure languages": "Cumraigh teangacha",
  "Current language:": "Teanga reatha:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Iontráil cód teanga bailí gan spásanna. Nó, brúigh cealaigh.",
  "Enter manually": "Iontráil de láimh",
  "Enter new lang code (e.g., \"en-US\"):": "Iontráil cód teanga nua (m.sh., \"ga-IE\"):",
  "Indicate current language": "Taispeáin teanga reatha",
  "Manually enter language {{number}}:": "Iontráil teanga {{number}} de láimh:",
  "New Language:": "Teanga Nua:",
  "None": "Faic",
  "Other - Enter manually": "Eile - Iontráil de láimh",
  "Really remove all language markup from the document?": "Bain gach marcáil teanga ón gcáipéis i ndáiríre?",
  "Remove All lang markup": "Bain gach marcáil teanga",
  "Remove Language Markup": "Bain Marcáil Teanga",
  "Remove current lang value": "Bain luach teanga reatha",
  "Reveal lang markup": "Nocht marcáil teanga",
  "Select language {{number}}:": "Roghnaigh teanga {{number}}:",
  "Select the document's default language.": "Roghnaigh teanga réamhshocraithe na cáipéise.",
  "Set default document language": "Socraigh teanga réamhshocraithe cáipéise",
  "Set text language": "Socraigh teanga téacs",
  "Afrikaans": "Afracáinis",
  "Afrikaans": "Afracáinis (an Afraic Theas)",
  "Akan": "Acáinis",
  "Amharic": "Amáiris",
  "Arabic": "Araibis",
  "Arabic (Egypt)": "Araibis (an Éigipt)",
  "Arabic (Morocco)": "Araibis (Maracó)",
  "Arabic (Saudi Arabia)": "Araibis (an Araib Shádach)",
  "Azerbaijani": "Asarbaiseáinis",
  "Belarusian": "Bealarúisis",
  "Bulgarian": "Bulgáiris",
  "Bulgarian (Bulgaria)": "Bulgáiris (an Bhulgáir)",
  "Bhojpuri": "Vóispiris",
  "Bambara": "Bambairis",
  "Bangla": "Beangáilis",
  "Tibetan": "Tibéidis",
  "Bosnian": "Boisnis",
  "Catalan": "Catalóinis",
  "Coptic": "Coptais",
  "Cree": "Craís",
  "Czech": "Seicis",
  "Church Slavic": "Slavais na hEaglaise",
  "Welsh": "Breatnais",
  "Danish": "Danmhairgis",
  "German": "Gearmáinis",
  "German (Austria)": "Gearmáinis (an Ostair)",
  "German (Switzerland)": "Gearmáinis (an Eilvéis)",
  "German (Germany)": "Gearmáinis (an Ghearmáin)",
  "Divehi": "Divéihis",
  "Greek": "Gréigis",
  "English": "Béarla",
  "English (Australia)": "Béarla (an Astráil)",
  "English (Canada)": "Béarla (Ceanada)",
  "English (United Kingdom)": "Béarla (an Ríocht Aontaithe)",
  "English (Ireland)": "Béarla (Éire)",
  "English (India)": "Béarla (an India)",
  "English (Trinidad)": "Béarla (Oileán na Tríonóide)",
  "English (United States)": "Béarla (Stáit Aontaithe Mheiriceá)",
  "English (South Africa)": "Béarla (an Afraic Theas)",
  "Esperanto": "Esperanto",
  "Spanish": "Spáinnis",
  "Spanish (Argentina)": "Spáinnis (an Airgintín)",
  "Spanish (Chile)": "Spáinnis (an tSile)",
  "Spanish (Colombia)": "Spáinnis (an Cholóim)",
  "Spanish (Costa Rica)": "Spáinnis (Cósta Ríce)",
  "Spanish (Spain)": "Spáinnis (an Spáinn)",
  "Spanish (Mexico)": "Spáinnis (Meicsiceo)",
  "Spanish (Peru)": "Spáinnis (Peiriú)",
  "Estonian": "Eastóinis",
  "Basque": "Bascais",
  "Persian": "Peirsis",
  "Dari": "Dairis",
  "Persian (Iran)": "Peirsis (an Iaráin)",
  "Fula": "Fuláinis",
  "Finnish": "Fionlainnis",
  "Finnish (Finland)": "Fionlainnis (an Fhionlainn)",
  "Filipino": "Filipínis",
  "French": "Fraincis",
  "French (Belgium)": "Fraincis (an Bheilg)",
  "French (Canada)": "Fraincis (Ceanada)",
  "French (Switzerland)": "Fraincis (an Eilvéis)",
  "Irish": "Gaeilge",
  "Galician": "Gailísis",
  "Greek (Ancient)": "Gréigis (Ársa)",
  "Hausa": "Hásais",
  "Hebrew": "Eabhrais",
  "Hebrew (Israel)": "Eabhrais (Iosrael)",
  "Hindi": "Hiondúis",
  "Croatian": "Cróitis",
  "Croatian (Croatia)": "Cróitis (an Chróit)",
  "Haitian Creole": "Críol Háítí",
  "Hungarian": "Ungáiris",
  "Hungarian (Hungary)": "Ungáiris (an Ungáir)",
  "Armenian": "Airméinis",
  "Indonesian": "Indinéisis",
  "Igbo": "Íogbóis",
  "Icelandic": "Íoslainnis",
  "Italian": "Iodáilis",
  "Italian (Italy)": "Iodáilis (an Iodáil)",
  "Inuktitut": "Ionúitis",
  "Japanese": "Seapáinis",
  "Japanese (Japan)": "Seapáinis (an tSeapáin)",
  "Georgian": "Seoirsis",
  "Kabyle": "Caibílis",
  "Kazakh": "Casaicis",
  "Khmer": "Ciméiris",
  "Kannada": "Cannadais",
  "Korean": "Cóiréis",
  "Korean (Korea)": "Cóiréis (an Chóiré)",
  "Latin": "Laidin",
  "Lakota": "Lacótais",
  "Lao": "Laoisis",
  "Lithuanian": "Liotuáinis",
  "Latvian": "Laitvis",
  "Māori": "Maorais",
  "Mongolian": "Mongóilis",
  "Marathi": "Maraitis",
  "Malay": "Malaeis",
  "Maltese": "Máltais",
  "Burmese": "Burmais",
  "Norwegian (Bokmål)": "Ioruais (Bokmål)",
  "Norwegian (Bokmål, Norway)": "Ioruais (Bokmål, an Iorua)",
  "Nepali": "Neipeailis",
  "Dutch": "Ollainnis",
  "Flemish": "Pléimeannais",
  "Norwegian (Nynorsk)": "Ioruais (Nynorsk)",
  "Navajo": "Navachóis",
  "Turkish (Ottoman)": "Tuircis (Otamánach)",
  "Punjabi": "Puinseáibis",
  "Persian (Old)": "Peirsis (Ársa)",
  "Polish": "Polainnis",
  "Pashto": "Paistis",
  "Portuguese": "Portaingéilis",
  "Portuguese (Brazil)": "Portaingéilis (an Bhrasaíl)",
  "Portuguese (Portugal)": "Portaingéilis (an Phortaingéil)",
  "Quechua": "Ceatsuais",
  "Romanian": "Rómáinis",
  "Russian": "Rúisis",
  "Kinyarwanda": "Ciniaruaindis",
  "Sanskrit": "Sanscrait",
  "Sami (Northern)": "Sáimis (Tuaisceart)",
  "Sinhala": "Siolóinis",
  "Slovak": "Slóvaicis",
  "Slovak (Slovakia)": "Slóvaicis (an tSlóvaic)",
  "Slovenian": "Slóivéinis",
  "Slovenian (Slovenia)": "Slóivéinis (an tSlóivéin)",
  "Sami (Southern)": "Sáimis (Deisceart)",
  "Sami (Northern)": "Sáimis (Tuaisceart)",
  "Sami (Lule)": "Sáimis (Lule)",
  "Shona": "Seoinis",
  "Serbian": "Seirbis",
  "Serbian (Latin)": "Seirbis (Laidineach)",
  "Swedish": "Sualainnis",
  "Swedish (Sweden)": "Sualainnis (an tSualainn)",
  "Swahili": "Svahaílis",
  "Swahili (Kenya)": "Svahaílis (an Chéinia)",
  "Swahili (Tanzania)": "Svahaílis (an Tansáin)",
  "Syriac (Classical)": "Siríacais (Clasaiceach)",
  "Tamil": "Tamailis",
  "Telugu": "Teileagúis",
  "Tajik": "Taidsícis",
  "Thai": "Téalainnis",
  "Thai (Thailand)": "Téalainnis (an Téalainn)",
  "Turkmen": "Tuircméinis",
  "Tagalog": "Tagálaigis",
  "Turkish": "Tuircis",
  "Turkish (Turkey)": "Tuircis (an Tuirc)",
  "Tatar": "Tatairis",
  "Uyghur": "Uigiúiris",
  "Ukrainian": "Úcráinis",
  "Urdu": "Urdúis",
  "Uzbek": "Úisbéiceastáinis",
  "Vietnamese": "Vítneaimis",
  "Wolof": "Volaifis",
  "Xhosa": "Cóisis",
  "Yiddish": "Giúdais",
  "Yoruba": "Iarúibis",
  "Maya (Yucatec)": "Maidhis (Iúcatáin)",
  "Chinese": "Sínis",
  "Chinese (Simplified)": "Sínis (Shimplithe)",
  "Chinese (Simplified)": "Sínis (Shimplithe)",
  "Chinese (Traditional)": "Sínis (Traidisiúnta)",
  "Chinese (Hong Kong)": "Sínis (Hong Cong)",
  "Chinese (Singapore)": "Sínis (Singeapór)",
  "Chinese (Traditional)": "Sínis (Traidisiúnta)",
  "Zulu": "Súlúis",
  "Zulu": "Súlúis (an Afraic Theas)"
});