tinymce.addI18n('he_IL', {
  "-Language Not Set-": "-שפה לא נקבעה-",
  "Choose from list": "בחר מרשימה",
  "Choose languages": "בחר שפות",
  "Choose up to six languages": "בחר עד שש שפות",
  "Configure languages": "הגדר שפות",
  "Current language:": "שפה נוכחית:",
  "Enter a valid language code with no spaces. Or, press cancel.": "הזן קוד שפה תקין ללא רווחים. או לחץ ביטול.",
  "Enter manually": "הזן ידנית",
  "Enter new lang code (e.g., \"en-US\"):": "הזן קוד שפה חדש (למשל, \"he-IL\"):",
  "Indicate current language": "ציין שפה נוכחית",
  "Manually enter language {{number}}:": "הזן ידנית שפה {{number}}:",
  "New Language:": "שפה חדשה:",
  "None": "ללא",
  "Other - Enter manually": "אחר - הזן ידנית",
  "Really remove all language markup from the document?": "האם באמת להסיר את כל סימוני השפה מהמסמך?",
  "Remove All lang markup": "הסר את כל סימוני השפה",
  "Remove Language Markup": "הסר סימון שפה",
  "Remove current lang value": "הסר ערך שפה נוכחי",
  "Reveal lang markup": "חשף סימון שפה",
  "Select language {{number}}:": "בחר שפה {{number}}:",
  "Select the document's default language.": "בחר את שפת ברירת המחדל של המסמך.",
  "Set default document language": "קבע שפת ברירת מחדל למסמך",
  "Set text language": "קבע שפת טקסט",
  "Afrikaans": "אפריקאנס",
  "Afrikaans": "אפריקאנס (דרום אפריקה)",
  "Akan": "אקאן",
  "Amharic": "אמהרית",
  "Arabic": "ערבית",
  "Arabic (Egypt)": "ערבית (מצרים)",
  "Arabic (Morocco)": "ערבית (מרוקו)",
  "Arabic (Saudi Arabia)": "ערבית (ערב הסעודית)",
  "Azerbaijani": "אזרית",
  "Belarusian": "בלארוסית",
  "Bulgarian": "בולגרית",
  "Bulgarian (Bulgaria)": "בולגרית (בולגריה)",
  "Bhojpuri": "בוג׳פורי",
  "Bambara": "במבארה",
  "Bangla": "בנגלית",
  "Tibetan": "טיבטית",
  "Bosnian": "בוסנית",
  "Catalan": "קטלאנית",
  "Coptic": "קופטית",
  "Cree": "קרי",
  "Czech": "צ׳כית",
  "Church Slavic": "סלאבית כנסייתית עתיקה",
  "Welsh": "וולשית",
  "Danish": "דנית",
  "German": "גרמנית",
  "German (Austria)": "גרמנית (אוסטריה)",
  "German (Switzerland)": "גרמנית (שווייץ)",
  "German (Germany)": "גרמנית (גרמניה)",
  "Divehi": "דיבהי",
  "Greek": "יוונית",
  "English": "אנגלית",
  "English (Australia)": "אנגלית (אוסטרליה)",
  "English (Canada)": "אנגלית (קנדה)",
  "English (United Kingdom)": "אנגלית (בריטניה)",
  "English (Ireland)": "אנגלית (אירלנד)",
  "English (India)": "אנגלית (הודו)",
  "English (Trinidad)": "אנגלית (טרינידד)",
  "English (United States)": "אנגלית (ארצות הברית)",
  "English (South Africa)": "אנגלית (דרום אפריקה)",
  "Esperanto": "אספרנטו",
  "Spanish": "ספרדית",
  "Spanish (Argentina)": "ספרדית (ארגנטינה)",
  "Spanish (Chile)": "ספרדית (צ׳ילה)",
  "Spanish (Colombia)": "ספרדית (קולומביה)",
  "Spanish (Costa Rica)": "ספרדית (קוסטה ריקה)",
  "Spanish (Spain)": "ספרדית (ספרד)",
  "Spanish (Mexico)": "ספרדית (מקסיקו)",
  "Spanish (Peru)": "ספרדית (פרו)",
  "Estonian": "אסטונית",
  "Basque": "בסקית",
  "Persian": "פרסית",
  "Dari": "דארי",
  "Persian (Iran)": "פרסית (איראן)",
  "Fula": "פולה",
  "Finnish": "פינית",
  "Finnish (Finland)": "פינית (פינלנד)",
  "Filipino": "פיליפינית",
  "French": "צרפתית",
  "French (Belgium)": "צרפתית (בלגיה)",
  "French (Canada)": "צרפתית (קנדה)",
  "French (Switzerland)": "צרפתית (שווייץ)",
  "Irish": "אירית",
  "Galician": "גליציאנית",
  "Greek (Ancient)": "יוונית (עתיקה)",
  "Hausa": "האוסה",
  "Hebrew": "עברית",
  "Hebrew (Israel)": "עברית (ישראל)",
  "Hindi": "הינדי",
  "Croatian": "קרואטית",
  "Croatian (Croatia)": "קרואטית (קרואטיה)",
  "Haitian Creole": "קריאולית (האיטי)",
  "Hungarian": "הונגרית",
  "Hungarian (Hungary)": "הונגרית (הונגריה)",
  "Armenian": "ארמנית",
  "Indonesian": "אינדונזית",
  "Igbo": "איגבו",
  "Icelandic": "איסלנדית",
  "Italian": "איטלקית",
  "Italian (Italy)": "איטלקית (איטליה)",
  "Inuktitut": "אינוקטיטוט",
  "Japanese": "יפנית",
  "Japanese (Japan)": "יפנית (יפן)",
  "Georgian": "גאורגית",
  "Kabyle": "קבילה",
  "Kazakh": "קזחית",
  "Khmer": "חמרית",
  "Kannada": "קנאדה",
  "Korean": "קוריאנית",
  "Korean (Korea)": "קוריאנית (קוריאה)",
  "Latin": "לטינית",
  "Lakota": "לקוטה",
  "Lao": "לאו",
  "Lithuanian": "ליטאית",
  "Latvian": "לטבית",
  "Māori": "מאורית",
  "Mongolian": "מונגולית",
  "Marathi": "מראטהית",
  "Malay": "מלאית",
  "Maltese": "מלטית",
  "Burmese": "בורמזית",
  "Norwegian (Bokmål)": "נורווגית (ספרותית)",
  "Norwegian (Bokmål, Norway)": "נורווגית (ספרותית, נורווגיה)",
  "Nepali": "נפאלית",
  "Dutch": "הולנדית",
  "Flemish": "פלמית",
  "Norwegian (Nynorsk)": "נורווגית (חדשה)",
  "Navajo": "נאוואחו",
  "Turkish (Ottoman)": "טורקית (עות׳מנית)",
  "Punjabi": "פנג׳אבי",
  "Persian (Old)": "פרסית (עתיקה)",
  "Polish": "פולנית",
  "Pashto": "פאשטו",
  "Portuguese": "פורטוגזית",
  "Portuguese (Brazil)": "פורטוגזית (ברזיל)",
  "Portuguese (Portugal)": "פורטוגזית (פורטוגל)",
  "Quechua": "קצ׳ואה",
  "Romanian": "רומנית",
  "Russian": "רוסית",
  "Kinyarwanda": "קנירואנדית",
  "Sanskrit": "סנסקריט",
  "Sami (Northern)": "סמי (צפונית)",
  "Sinhala": "סינהלה",
  "Slovak": "סלובקית",
  "Slovak (Slovakia)": "סלובקית (סלובקיה)",
  "Slovenian": "סלובנית",
  "Slovenian (Slovenia)": "סלובנית (סלובניה)",
  "Sami (Southern)": "סמי (דרומית)",
  "Sami (Northern)": "סמי (צפונית)",
  "Sami (Lule)": "סמי (לולה)",
  "Shona": "שונה",
  "Serbian": "סרבית",
  "Serbian (Latin)": "סרבית (לטינית)",
  "Swedish": "שוודית",
  "Swedish (Sweden)": "שוודית (שוודיה)",
  "Swahili": "סווהילי",
  "Swahili (Kenya)": "סווהילי (קניה)",
  "Swahili (Tanzania)": "סווהילי (טנזניה)",
  "Syriac (Classical)": "סירית (קלאסית)",
  "Tamil": "טמילית",
  "Telugu": "טלוגו",
  "Tajik": "טג׳יקית",
  "Thai": "תאית",
  "Thai (Thailand)": "תאית (תאילנד)",
  "Turkmen": "טורקמנית",
  "Tagalog": "טאגאלוג",
  "Turkish": "טורקית",
  "Turkish (Turkey)": "טורקית (טורקיה)",
  "Tatar": "טטרית",
  "Uyghur": "אויגורית",
  "Ukrainian": "אוקראינית",
  "Urdu": "אורדו",
  "Uzbek": "אוזבקית",
  "Vietnamese": "וייטנאמית",
  "Wolof": "וולוף",
  "Xhosa": "קוסה",
  "Yiddish": "יידיש",
  "Yoruba": "יורובה",
  "Maya (Yucatec)": "מאיה (יוקטנית)",
  "Chinese": "סינית",
  "Chinese (Simplified)": "סינית (פשוטה)",
  "Chinese (Simplified)": "סינית (פשוטה)",
  "Chinese (Traditional)": "סינית (מסורתית)",
  "Chinese (Hong Kong)": "סינית (הונג קונג)",
  "Chinese (Singapore)": "סינית (סינגפור)",
  "Chinese (Traditional)": "סינית (מסורתית)",
  "Zulu": "זולו",
  "Zulu": "זולו (דרום אפריקה)"
});