tinymce.addI18n('hi', {
  "-Language Not Set-": "-भाषा निर्धारित नहीं-",
  "Choose from list": "सूची से चुनें",
  "Choose languages": "भाषाएँ चुनें",
  "Choose up to six languages": "छह तक भाषाएँ चुनें",
  "Configure languages": "भाषाएँ कॉन्फ़िगर करें",
  "Current language:": "वर्तमान भाषा:",
  "Enter a valid language code with no spaces. Or, press cancel.": "बिना स्पेस के एक वैध भाषा कोड दर्ज करें। या रद्द करें दबाएं।",
  "Enter manually": "मैन्युअल रूप से दर्ज करें",
  "Enter new lang code (e.g., \"en-US\"):": "नया भाषा कोड दर्ज करें (जैसे, \"hi-IN\"):",
  "Indicate current language": "वर्तमान भाषा इंगित करें",
  "Manually enter language {{number}}:": "भाषा {{number}} मैन्युअल रूप से दर्ज करें:",
  "New Language:": "नई भाषा:",
  "None": "कोई नहीं",
  "Other - Enter manually": "अन्य - मैन्युअल रूप से दर्ज करें",
  "Really remove all language markup from the document?": "वास्तव में दस्तावेज़ से सभी भाषा मार्कअप हटाना है?",
  "Remove All lang markup": "सभी भाषा मार्कअप हटाएं",
  "Remove Language Markup": "भाषा मार्कअप हटाएं",
  "Remove current lang value": "वर्तमान भाषा मान हटाएं",
  "Reveal lang markup": "भाषा मार्कअप दिखाएं",
  "Select language {{number}}:": "भाषा {{number}} चुनें:",
  "Select the document's default language.": "दस्तावेज़ की डिफ़ॉल्ट भाषा चुनें।",
  "Set default document language": "डिफ़ॉल्ट दस्तावेज़ भाषा सेट करें",
  "Set text language": "टेक्स्ट भाषा सेट करें",
  "Afrikaans": "अफ़्रीकी",
  "Afrikaans": "अफ़्रीकी (दक्षिण अफ्रीका)",
  "Akan": "अकन",
  "Amharic": "अम्हेरी",
  "Arabic": "अरबी",
  "Arabic (Egypt)": "अरबी (मिस्र)",
  "Arabic (Morocco)": "अरबी (मोरक्को)",
  "Arabic (Saudi Arabia)": "अरबी (सऊदी अरब)",
  "Azerbaijani": "अज़रबैजानी",
  "Belarusian": "बेलारूसी",
  "Bulgarian": "बुल्गारियाई",
  "Bulgarian (Bulgaria)": "बुल्गारियाई (बुल्गारिया)",
  "Bhojpuri": "भोजपुरी",
  "Bambara": "बाम्बारा",
  "Bangla": "बंगाली",
  "Tibetan": "तिब्बती",
  "Bosnian": "बोस्नियाई",
  "Catalan": "कातालान",
  "Coptic": "कॉप्टिक",
  "Cree": "क्री",
  "Czech": "चेक",
  "Church Slavic": "चर्च स्लाविक",
  "Welsh": "वेल्श",
  "Danish": "डेनिश",
  "German": "जर्मन",
  "German (Austria)": "जर्मन (ऑस्ट्रिया)",
  "German (Switzerland)": "जर्मन (स्विट्जरलैंड)",
  "German (Germany)": "जर्मन (जर्मनी)",
  "Divehi": "दिवेही",
  "Greek": "यूनानी",
  "English": "अंग्रेज़ी",
  "English (Australia)": "अंग्रेज़ी (ऑस्ट्रेलिया)",
  "English (Canada)": "अंग्रेज़ी (कनाडा)",
  "English (United Kingdom)": "अंग्रेज़ी (ब्रिटेन)",
  "English (Ireland)": "अंग्रेज़ी (आयरलैंड)",
  "English (India)": "अंग्रेज़ी (भारत)",
  "English (Trinidad)": "अंग्रेज़ी (त्रिनिदाद)",
  "English (United States)": "अंग्रेज़ी (संयुक्त राज्य)",
  "English (South Africa)": "अंग्रेज़ी (दक्षिण अफ्रीका)",
  "Esperanto": "एस्पेरेंतो",
  "Spanish": "स्पेनिश",
  "Spanish (Argentina)": "स्पेनिश (अर्जेंटीना)",
  "Spanish (Chile)": "स्पेनिश (चिली)",
  "Spanish (Colombia)": "स्पेनिश (कोलंबिया)",
  "Spanish (Costa Rica)": "स्पेनिश (कोस्टा रिका)",
  "Spanish (Spain)": "स्पेनिश (स्पेन)",
  "Spanish (Mexico)": "स्पेनिश (मेक्सिको)",
  "Spanish (Peru)": "स्पेनिश (पेरू)",
  "Estonian": "एस्टोनियाई",
  "Basque": "बास्क",
  "Persian": "फ़ारसी",
  "Dari": "दारी",
  "Persian (Iran)": "फ़ारसी (ईरान)",
  "Fula": "फुलाह",
  "Finnish": "फ़िनिश",
  "Finnish (Finland)": "फ़िनिश (फिनलैंड)",
  "Filipino": "फ़िलिपीनो",
  "French": "फ़्रेंच",
  "French (Belgium)": "फ़्रेंच (बेल्जियम)",
  "French (Canada)": "फ़्रेंच (कनाडा)",
  "French (Switzerland)": "फ़्रेंच (स्विट्जरलैंड)",
  "Irish": "आयरिश",
  "Galician": "गैलिशियन",
  "Greek (Ancient)": "यूनानी (प्राचीन)",
  "Hausa": "हौसा",
  "Hebrew": "हिब्रू",
  "Hebrew (Israel)": "हिब्रू (इस्राएल)",
  "Hindi": "हिन्दी",
  "Croatian": "क्रोएशियाई",
  "Croatian (Croatia)": "क्रोएशियाई (क्रोएशिया)",
  "Haitian Creole": "हैतियाई क्रिओल",
  "Hungarian": "हंगेरियाई",
  "Hungarian (Hungary)": "हंगेरियाई (हंगरी)",
  "Armenian": "आर्मेनियाई",
  "Indonesian": "इंडोनेशियाई",
  "Igbo": "ईग्बो",
  "Icelandic": "आइसलैंडिक",
  "Italian": "इतालवी",
  "Italian (Italy)": "इतालवी (इटली)",
  "Inuktitut": "इनुक्टिटुट",
  "Japanese": "जापानी",
  "Japanese (Japan)": "जापानी (जापान)",
  "Georgian": "जॉर्जियाई",
  "Kabyle": "कबाइल",
  "Kazakh": "कज़ाख़",
  "Khmer": "खमेर",
  "Kannada": "कन्नड़",
  "Korean": "कोरियाई",
  "Korean (Korea)": "कोरियाई (दक्षिण कोरिया)",
  "Latin": "लैटिन",
  "Lakota": "लैकोटा",
  "Lao": "लाओ",
  "Lithuanian": "लिथुआनियाई",
  "Latvian": "लातवियाई",
  "Māori": "माओरी",
  "Mongolian": "मंगोलियाई",
  "Marathi": "मराठी",
  "Malay": "मलय",
  "Maltese": "माल्टीज़",
  "Burmese": "बर्मीज़",
  "Norwegian (Bokmål)": "नॉर्वेजियाई (बोकमाल)",
  "Norwegian (Bokmål, Norway)": "नॉर्वेजियाई (बोकमाल, नॉर्वे)",
  "Nepali": "नेपाली",
  "Dutch": "डच",
  "Flemish": "डच (बेल्जियम)",
  "Norwegian (Nynorsk)": "नॉर्वेजियाई (न्यूनॉर्स्क)",
  "Navajo": "नवाहो",
  "Turkish (Ottoman)": "तुर्की (ओटोमान)",
  "Punjabi": "पंजाबी",
  "Persian (Old)": "फ़ारसी (पुरानी)",
  "Polish": "पोलिश",
  "Pashto": "पश्तो",
  "Portuguese": "पुर्तगाली",
  "Portuguese (Brazil)": "पुर्तगाली (ब्राज़ील)",
  "Portuguese (Portugal)": "पुर्तगाली (पुर्तगाल)",
  "Quechua": "क्वेचुआ",
  "Romanian": "रोमानियाई",
  "Russian": "रूसी",
  "Kinyarwanda": "किन्यारवांडा",
  "Sanskrit": "संस्कृत",
  "Sami (Northern)": "सामी (उत्तरी)",
  "Sinhala": "सिंहली",
  "Slovak": "स्लोवाक",
  "Slovak (Slovakia)": "स्लोवाक (स्लोवाकिया)",
  "Slovenian": "स्लोवेनियाई",
  "Slovenian (Slovenia)": "स्लोवेनियाई (स्लोवेनिया)",
  "Sami (Southern)": "सामी (दक्षिणी)",
  "Sami (Northern)": "सामी (उत्तरी)",
  "Sami (Lule)": "सामी (ल्युल)",
  "Shona": "शोणा",
  "Serbian": "सर्बियाई",
  "Serbian (Latin)": "सर्बियाई (लैटिन)",
  "Swedish": "स्वीडिश",
  "Swedish (Sweden)": "स्वीडिश (स्वीडन)",
  "Swahili": "स्वाहिली",
  "Swahili (Kenya)": "स्वाहिली (केन्या)",
  "Swahili (Tanzania)": "स्वाहिली (तंजानिया)",
  "Syriac (Classical)": "सिरिएक (शास्त्रीय)",
  "Tamil": "तमिल",
  "Telugu": "तेलुगू",
  "Tajik": "ताजिक",
  "Thai": "थाई",
  "Thai (Thailand)": "थाई (थाईलैंड)",
  "Turkmen": "तुर्कमेन",
  "Tagalog": "टैगलॉग",
  "Turkish": "तुर्की",
  "Turkish (Turkey)": "तुर्की (तुर्की)",
  "Tatar": "तातार",
  "Uyghur": "उइगर",
  "Ukrainian": "यूक्रेनियाई",
  "Urdu": "उर्दू",
  "Uzbek": "उज़्बेक",
  "Vietnamese": "वियतनामी",
  "Wolof": "वोलोफ़",
  "Xhosa": "ख़ोसा",
  "Yiddish": "यिडिश",
  "Yoruba": "योरूबा",
  "Maya (Yucatec)": "माया (युकाटेक)",
  "Chinese": "चीनी",
  "Chinese (Simplified)": "चीनी (सरलीकृत)",
  "Chinese (Simplified)": "चीनी (सरलीकृत)",
  "Chinese (Traditional)": "चीनी (पारंपरिक)",
  "Chinese (Hong Kong)": "चीनी (हांग कांग)",
  "Chinese (Singapore)": "चीनी (सिंगापुर)",
  "Chinese (Traditional)": "चीनी (पारंपरिक, ताइवान)",
  "Zulu": "ज़ुलू",
  "Zulu": "ज़ुलू (दक्षिण अफ्रीका)"
});