tinymce.addI18n('hr', {
  "-Language Not Set-": "-Jezik nije postavljen-",
  "Choose from list": "Odaberite s popisa",
  "Choose languages": "Odaberite jezike",
  "Choose up to six languages": "Odaberite do šest jezika",
  "Configure languages": "Konfiguriraj jezike",
  "Current language:": "Trenutni jezik:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Unesite valjani kod jezika bez razmaka. Ili pritisnite odustani.",
  "Enter manually": "Unesite ručno",
  "Enter new lang code (e.g., \"en-US\"):": "Unesite novi kod jezika (npr. \"en-US\"):",
  "Indicate current language": "Označi trenutni jezik",
  "Manually enter language {{number}}:": "Ručno unesite jezik {{number}}:",
  "New Language:": "Novi jezik:",
  "None": "Nijedan",
  "Other - Enter manually": "Ostalo - Unesite ručno",
  "Really remove all language markup from the document?": "Stvarno ukloniti sve označavanje jezika iz dokumenta?",
  "Remove All lang markup": "Ukloni sve oznake jezika",
  "Remove Language Markup": "Ukloni označavanje jezika",
  "Remove current lang value": "Ukloni trenutnu vrijednost jezika",
  "Reveal lang markup": "Prikaži označavanje jezika",
  "Select language {{number}}:": "Odaberite jezik {{number}}:",
  "Select the document's default language.": "Odaberite zadani jezik dokumenta.",
  "Set default document language": "Postavi zadani jezik dokumenta",
  "Set text language": "Postavi jezik teksta",
  "Afrikaans": "afrikaans",
  "Afrikaans": "afrikaans (Južna Afrika)",
  "Akan": "akanski",
  "Amharic": "amharski",
  "Arabic": "arapski",
  "Arabic (Egypt)": "arapski (Egipat)",
  "Arabic (Morocco)": "arapski (Maroko)",
  "Arabic (Saudi Arabia)": "arapski (Saudijska Arabija)",
  "Azerbaijani": "azerbajdžanski",
  "Belarusian": "bjeloruski",
  "Bulgarian": "bugarski",
  "Bulgarian (Bulgaria)": "bugarski (Bugarska)",
  "Bhojpuri": "bhojpuri",
  "Bambara": "bambara",
  "Bangla": "bangla",
  "Tibetan": "tibetski",
  "Bosnian": "bosanski",
  "Catalan": "katalonski",
  "Coptic": "koptski",
  "Cree": "cree",
  "Czech": "češki",
  "Church Slavic": "crkvenoslavenski",
  "Welsh": "velški",
  "Danish": "danski",
  "German": "njemački",
  "German (Austria)": "njemački (Austrija)",
  "German (Switzerland)": "njemački (Švicarska)",
  "German (Germany)": "njemački (Njemačka)",
  "Divehi": "divehi",
  "Greek": "grčki",
  "English": "engleski",
  "English (Australia)": "engleski (Australija)",
  "English (Canada)": "engleski (Kanada)",
  "English (United Kingdom)": "engleski (Velika Britanija)",
  "English (Ireland)": "engleski (Irska)",
  "English (India)": "engleski (Indija)",
  "English (Trinidad)": "engleski (Trinidad)",
  "English (United States)": "engleski (Sjedinjene Države)",
  "English (South Africa)": "engleski (Južna Afrika)",
  "Esperanto": "esperanto",
  "Spanish": "španjolski",
  "Spanish (Argentina)": "španjolski (Argentina)",
  "Spanish (Chile)": "španjolski (Čile)",
  "Spanish (Colombia)": "španjolski (Kolumbija)",
  "Spanish (Costa Rica)": "španjolski (Kostarika)",
  "Spanish (Spain)": "španjolski (Španjolska)",
  "Spanish (Mexico)": "španjolski (Meksiko)",
  "Spanish (Peru)": "španjolski (Peru)",
  "Estonian": "estonski",
  "Basque": "baskijski",
  "Persian": "perzijski",
  "Dari": "dari (Afganistan)",
  "Persian (Iran)": "perzijski (Iran)",
  "Fula": "fula",
  "Finnish": "finski",
  "Finnish (Finland)": "finski (Finska)",
  "Filipino": "filipinski",
  "French": "francuski",
  "French (Belgium)": "francuski (Belgija)",
  "French (Canada)": "francuski (Kanada)",
  "French (Switzerland)": "francuski (Švicarska)",
  "Irish": "irski",
  "Galician": "galicijski",
  "Greek (Ancient)": "starogrčki",
  "Hausa": "hausa",
  "Hebrew": "hebrejski",
  "Hebrew (Israel)": "hebrejski (Izrael)",
  "Hindi": "hindski",
  "Croatian": "hrvatski",
  "Croatian (Croatia)": "hrvatski (Hrvatska)",
  "Haitian Creole": "haićanski kreolski",
  "Hungarian": "mađarski",
  "Hungarian (Hungary)": "mađarski (Mađarska)",
  "Armenian": "armenski",
  "Indonesian": "indonezijski",
  "Igbo": "igbo",
  "Icelandic": "islandski",
  "Italian": "talijanski",
  "Italian (Italy)": "talijanski (Italija)",
  "Inuktitut": "inuktitut",
  "Japanese": "japanski",
  "Japanese (Japan)": "japanski (Japan)",
  "Georgian": "gruzijski",
  "Kabyle": "kabilski",
  "Kazakh": "kazaški",
  "Khmer": "kmerski",
  "Kannada": "karnatački",
  "Korean": "korejski",
  "Korean (Korea)": "korejski (Koreja)",
  "Latin": "latinski",
  "Lakota": "lakota",
  "Lao": "laoski",
  "Lithuanian": "litavski",
  "Latvian": "latvijski",
  "Māori": "maorski",
  "Mongolian": "mongolski",
  "Marathi": "marathski",
  "Malay": "malajski",
  "Maltese": "malteški",
  "Burmese": "burmanski",
  "Norwegian (Bokmål)": "norveški (bokmål)",
  "Norwegian (Bokmål, Norway)": "norveški (bokmål, Norveška)",
  "Nepali": "nepalski",
  "Dutch": "nizozemski",
  "Flemish": "flamanski",
  "Norwegian (Nynorsk)": "norveški (nynorsk)",
  "Navajo": "navajo",
  "Turkish (Ottoman)": "turski (otomanski)",
  "Punjabi": "pandžapski",
  "Persian (Old)": "perzijski (stari)",
  "Polish": "poljski",
  "Pashto": "paštunski",
  "Portuguese": "portugalski",
  "Portuguese (Brazil)": "portugalski (Brazil)",
  "Portuguese (Portugal)": "portugalski (Portugal)",
  "Quechua": "kečuanski",
  "Romanian": "rumunjski",
  "Russian": "ruski",
  "Kinyarwanda": "kinyarwanda",
  "Sanskrit": "sanskrtski",
  "Sami (Northern)": "sami (sjeverni)",
  "Sinhala": "sinhaleški",
  "Slovak": "slovački",
  "Slovak (Slovakia)": "slovački (Slovačka)",
  "Slovenian": "slovenski",
  "Slovenian (Slovenia)": "slovenski (Slovenija)",
  "Sami (Southern)": "sami (južni)",
  "Sami (Northern)": "sami (sjeverni)",
  "Sami (Lule)": "sami (lule)",
  "Shona": "shona",
  "Serbian": "srpski",
  "Serbian (Latin)": "srpski (latinica)",
  "Swedish": "švedski",
  "Swedish (Sweden)": "švedski (Švedska)",
  "Swahili": "svahili",
  "Swahili (Kenya)": "svahili (Kenija)",
  "Swahili (Tanzania)": "svahili (Tanzanija)",
  "Syriac (Classical)": "sirski (klasični)",
  "Tamil": "tamilski",
  "Telugu": "teluški",
  "Tajik": "tadžički",
  "Thai": "tajlandski",
  "Thai (Thailand)": "tajlandski (Tajland)",
  "Turkmen": "turkmenski",
  "Tagalog": "tagalog",
  "Turkish": "turski",
  "Turkish (Turkey)": "turski (Turska)",
  "Tatar": "tatarski",
  "Uyghur": "ujgurski",
  "Ukrainian": "ukrajinski",
  "Urdu": "urdski",
  "Uzbek": "uzbečki",
  "Vietnamese": "vijetnamski",
  "Wolof": "volof",
  "Xhosa": "xhosa",
  "Yiddish": "jidiš",
  "Yoruba": "jorupski",
  "Maya (Yucatec)": "maja (jukateški)",
  "Chinese": "kineski",
  "Chinese (Simplified)": "kineski (pojednostavljeni)",
  "Chinese (Simplified)": "kineski (pojednostavljeni)",
  "Chinese (Traditional)": "kineski (tradicionalni)",
  "Chinese (Hong Kong)": "kineski (Hong Kong)",
  "Chinese (Singapore)": "kineski (Singapur)",
  "Chinese (Traditional)": "kineski (Tajvan)",
  "Zulu": "zulu",
  "Zulu": "zulu (Južna Afrika)"
});