tinymce.addI18n('ht', {
  "-Language Not Set-": "-Lang la pa chwazi-",
  "Choose from list": "Chwazi nan lis la",
  "Choose languages": "Chwazi lang yo",
  "Choose up to six languages": "Chwazi jiska sis lang",
  "Configure languages": "Konfigire lang yo",
  "Current language:": "Lang kounye a:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Antre yon kòd lang ki valab san espas. Oswa, peze sou anile.",
  "Enter manually": "Antre ak men ou",
  "Enter new lang code (e.g., \"en-US\"):": "Antre nouvo kòd lang lan (egzanp, \"en-US\"):",
  "Indicate current language": "Endike lang kounye a",
  "Manually enter language {{number}}:": "Antre ak men ou lang {{number}}:",
  "New Language:": "Nouvo Lang:",
  "None": "Anyen",
  "Other - Enter manually": "Lòt bagay - Antre ak men ou",
  "Really remove all language markup from the document?": "Ou kwè ou vle retire tout mak lang yo nan dokiman an?",
  "Remove All lang markup": "Retire tout mak lang yo",
  "Remove Language Markup": "Retire mak lang yo",
  "Remove current lang value": "Retire valè lang kounye a",
  "Reveal lang markup": "Montre mak lang yo",
  "Select language {{number}}:": "Chwazi lang {{number}}:",
  "Select the document's default language.": "Chwazi lang dokiman an pa defo a.",
  "Set default document language": "Chwazi lang dokiman an pa defo",
  "Set text language": "Chwazi lang tèks la",
  "Afrikaans": "afrikaans",
  "Afrikaans": "afrikaans (Afrik disid)",
  "Akan": "akan",
  "Amharic": "amharik",
  "Arabic": "arab",
  "Arabic (Egypt)": "arab (Ejip)",
  "Arabic (Morocco)": "arab (Maròk)",
  "Arabic (Saudi Arabia)": "arab (Arabi Sawoudit)",
  "Azerbaijani": "azerbaïdjanè",
  "Belarusian": "byeloris",
  "Bulgarian": "bilgar",
  "Bulgarian (Bulgaria)": "bilgar (Bilgari)",
  "Bhojpuri": "bhodjpouri",
  "Bambara": "bambara",
  "Bangla": "bengali",
  "Tibetan": "tibetè",
  "Bosnian": "bosniak",
  "Catalan": "katalan",
  "Coptic": "kòpt",
  "Cree": "kri",
  "Czech": "tchèk",
  "Church Slavic": "slavon legliz",
  "Welsh": "galwa",
  "Danish": "danwa",
  "German": "almè",
  "German (Austria)": "almè (Otrich)",
  "German (Switzerland)": "almè (Swis)",
  "German (Germany)": "almè (Almay)",
  "Divehi": "divehi",
  "Greek": "grèk",
  "English": "angle",
  "English (Australia)": "angle (Ostrali)",
  "English (Canada)": "angle (Kanada)",
  "English (United Kingdom)": "angle (Wayòm Ini)",
  "English (Ireland)": "angle (Iland)",
  "English (India)": "angle (Enn)",
  "English (Trinidad)": "angle (Trinidad)",
  "English (United States)": "angle (Etazini)",
  "English (South Africa)": "angle (Afrik disid)",
  "Esperanto": "esperanto",
  "Spanish": "panyòl",
  "Spanish (Argentina)": "panyòl (Ajantin)",
  "Spanish (Chile)": "panyòl (Chili)",
  "Spanish (Colombia)": "panyòl (Kolonbi)",
  "Spanish (Costa Rica)": "panyòl (Kosta Rika)",
  "Spanish (Spain)": "panyòl (Pany)",
  "Spanish (Mexico)": "panyòl (Meksik)",
  "Spanish (Peru)": "panyòl (Perou)",
  "Estonian": "estonyen",
  "Basque": "bask",
  "Persian": "pèsan",
  "Dari": "dari",
  "Persian (Iran)": "pèsan (Iran)",
  "Fula": "pèl",
  "Finnish": "finwa",
  "Finnish (Finland)": "finwa (Finland)",
  "Filipino": "filipino",
  "French": "franse",
  "French (Belgium)": "franse (Bèljik)",
  "French (Canada)": "franse (Kanada)",
  "French (Switzerland)": "franse (Swis)",
  "Irish": "ilandè",
  "Galician": "galisyen",
  "Greek (Ancient)": "grèk (ansyen)",
  "Hausa": "haoussa",
  "Hebrew": "ebrè",
  "Hebrew (Israel)": "ebrè (Izrayèl)",
  "Hindi": "hindi",
  "Croatian": "kwoyat",
  "Croatian (Croatia)": "kwoyat (Kwoyasi)",
  "Haitian Creole": "kreyòl ayisyen",
  "Hungarian": "hongrwa",
  "Hungarian (Hungary)": "hongrwa (Ongri)",
  "Armenian": "amenyen",
  "Indonesian": "endonezyen",
  "Igbo": "igbo",
  "Icelandic": "islandè",
  "Italian": "italyen",
  "Italian (Italy)": "italyen (Itali)",
  "Inuktitut": "inuktitut",
  "Japanese": "japonè",
  "Japanese (Japan)": "japonè (Japon)",
  "Georgian": "jewojyen",
  "Kabyle": "kabil",
  "Kazakh": "kazak",
  "Khmer": "kmè",
  "Kannada": "kannada",
  "Korean": "koreyen",
  "Korean (Korea)": "koreyen (Kore)",
  "Latin": "latin",
  "Lakota": "lakota",
  "Lao": "lao",
  "Lithuanian": "lityenyen",
  "Latvian": "leton",
  "Māori": "maori",
  "Mongolian": "mongolyen",
  "Marathi": "marathi",
  "Malay": "malè",
  "Maltese": "maltè",
  "Burmese": "biman",
  "Norwegian (Bokmål)": "nòvejyen (Bokmål)",
  "Norwegian (Bokmål, Norway)": "nòvejyen (Bokmål, Nòvèj)",
  "Nepali": "nepalè",
  "Dutch": "ollandè",
  "Flemish": "flamè",
  "Norwegian (Nynorsk)": "nòvejyen (Nynorsk)",
  "Navajo": "navajo",
  "Turkish (Ottoman)": "tik (otomàn)",
  "Punjabi": "pendjabi",
  "Persian (Old)": "pèsan (ansyen)",
  "Polish": "polonè",
  "Pashto": "pachto",
  "Portuguese": "pòtigè",
  "Portuguese (Brazil)": "pòtigè (Brezil)",
  "Portuguese (Portugal)": "pòtigè (Pòtigal)",
  "Quechua": "ketchwa",
  "Romanian": "woumen",
  "Russian": "ris",
  "Kinyarwanda": "kinyarwanda",
  "Sanskrit": "sanskrit",
  "Sami (Northern)": "sami (kote nò)",
  "Sinhala": "sinhala",
  "Slovak": "slovak",
  "Slovak (Slovakia)": "slovak (Slovaki)",
  "Slovenian": "slovenyen",
  "Slovenian (Slovenia)": "slovenyen (Sloveni)",
  "Sami (Southern)": "sami (kote sid)",
  "Sami (Northern)": "sami (kote nò)",
  "Sami (Lule)": "sami (Lule)",
  "Shona": "shona",
  "Serbian": "sèb",
  "Serbian (Latin)": "sèb (Latin)",
  "Swedish": "swedwa",
  "Swedish (Sweden)": "swedwa (Swèd)",
  "Swahili": "swahili",
  "Swahili (Kenya)": "swahili (Kenya)",
  "Swahili (Tanzania)": "swahili (Tanzani)",
  "Syriac (Classical)": "siryen (klasik)",
  "Tamil": "tamil",
  "Telugu": "telougu",
  "Tajik": "tadjik",
  "Thai": "tay",
  "Thai (Thailand)": "tay (Taylann)",
  "Turkmen": "tikmen",
  "Tagalog": "tagalog",
  "Turkish": "tik",
  "Turkish (Turkey)": "tik (Tiki)",
  "Tatar": "tata",
  "Uyghur": "ouyghour",
  "Ukrainian": "ikrenyen",
  "Urdu": "ourdou",
  "Uzbek": "ouzbèk",
  "Vietnamese": "vyetnamyen",
  "Wolof": "wolof",
  "Xhosa": "xhosa",
  "Yiddish": "yidich",
  "Yoruba": "yoruba",
  "Maya (Yucatec)": "maya (Youkatan)",
  "Chinese": "chinwa",
  "Chinese (Simplified)": "chinwa (senplif)",
  "Chinese (Simplified)": "chinwa (senplif)",
  "Chinese (Traditional)": "chinwa (tradisyonèl)",
  "Chinese (Hong Kong)": "chinwa (Hong Kong)",
  "Chinese (Singapore)": "chinwa (Singapou)",
  "Chinese (Traditional)": "chinwa (tradisyonèl)",
  "Zulu": "zoulou",
  "Zulu": "zoulou (Afrik disid)"
});