tinymce.addI18n('hu', {
  "-Language Not Set-": "-Nyelv nincs beállítva-",
  "Choose from list": "Kiválasztás listából",
  "Choose languages": "Nyelvek kiválasztása",
  "Choose up to six languages": "Válasszon ki legfeljebb hat nyelvet",
  "Configure languages": "Nyelvek konfigurálása",
  "Current language:": "Jelenlegi nyelv:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Adjon meg egy érvényes nyelvkódot szóközök nélkül. Vagy nyomja meg a mégsem gombot.",
  "Enter manually": "Kézi bevitel",
  "Enter new lang code (e.g., \"en-US\"):": "Adja meg az új nyelvkódot (pl. \"en-US\"):",
  "Indicate current language": "Jelenlegi nyelv jelzése",
  "Manually enter language {{number}}:": "Adja meg kézzel a(z) {{number}}. nyelvet:",
  "New Language:": "Új nyelv:",
  "None": "Nincs",
  "Other - Enter manually": "Egyéb - Kézi bevitel",
  "Really remove all language markup from the document?": "Valóban eltávolítja az összes nyelvi jelölést a dokumentumból?",
  "Remove All lang markup": "Minden nyelvi jelölés eltávolítása",
  "Remove Language Markup": "Nyelvi jelölés eltávolítása",
  "Remove current lang value": "Jelenlegi nyelvi érték eltávolítása",
  "Reveal lang markup": "Nyelvi jelölés megjelenítése",
  "Select language {{number}}:": "Válassza ki a(z) {{number}}. nyelvet:",
  "Select the document's default language.": "Válassza ki a dokumentum alapértelmezett nyelvét.",
  "Set default document language": "Alapértelmezett dokumentumnyelv beállítása",
  "Set text language": "Szöveg nyelvének beállítása",
  "Afrikaans": "afrikaans",
  "Afrikaans": "afrikaans (Dél-Afrika)",
  "Akan": "akan",
  "Amharic": "amhara",
  "Arabic": "arab",
  "Arabic (Egypt)": "arab (Egyiptom)",
  "Arabic (Morocco)": "arab (Marokkó)",
  "Arabic (Saudi Arabia)": "arab (Szaúd-Arábia)",
  "Azerbaijani": "azerbajdzsáni",
  "Belarusian": "belarusz",
  "Bulgarian": "bolgár",
  "Bulgarian (Bulgaria)": "bolgár (Bulgária)",
  "Bhojpuri": "bodzspuri",
  "Bambara": "bambara",
  "Bangla": "bangla",
  "Tibetan": "tibeti",
  "Bosnian": "bosnyák",
  "Catalan": "katalán",
  "Coptic": "kopt",
  "Cree": "krí",
  "Czech": "cseh",
  "Church Slavic": "egyházi szláv",
  "Welsh": "walesi",
  "Danish": "dán",
  "German": "német",
  "German (Austria)": "német (Ausztria)",
  "German (Switzerland)": "német (Svájc)",
  "German (Germany)": "német (Németország)",
  "Divehi": "divehi",
  "Greek": "görög",
  "English": "angol",
  "English (Australia)": "angol (Ausztrália)",
  "English (Canada)": "angol (Kanada)",
  "English (United Kingdom)": "angol (Nagy-Britannia)",
  "English (Ireland)": "angol (Írország)",
  "English (India)": "angol (India)",
  "English (Trinidad)": "angol (Trinidad)",
  "English (United States)": "angol (Egyesült Államok)",
  "English (South Africa)": "angol (Dél-Afrika)",
  "Esperanto": "eszperantó",
  "Spanish": "spanyol",
  "Spanish (Argentina)": "spanyol (Argentína)",
  "Spanish (Chile)": "spanyol (Chile)",
  "Spanish (Colombia)": "spanyol (Kolumbia)",
  "Spanish (Costa Rica)": "spanyol (Costa Rica)",
  "Spanish (Spain)": "spanyol (Spanyolország)",
  "Spanish (Mexico)": "spanyol (Mexikó)",
  "Spanish (Peru)": "spanyol (Peru)",
  "Estonian": "észt",
  "Basque": "baszk",
  "Persian": "perzsa",
  "Dari": "dari (Afganisztán)",
  "Persian (Iran)": "perzsa (Irán)",
  "Fula": "fulani",
  "Finnish": "finn",
  "Finnish (Finland)": "finn (Finnország)",
  "Filipino": "filippínó",
  "French": "francia",
  "French (Belgium)": "francia (Belgium)",
  "French (Canada)": "francia (Kanada)",
  "French (Switzerland)": "francia (Svájc)",
  "Irish": "ír",
  "Galician": "gallego",
  "Greek (Ancient)": "ógörög",
  "Hausa": "hausza",
  "Hebrew": "héber",
  "Hebrew (Israel)": "héber (Izrael)",
  "Hindi": "hindi",
  "Croatian": "horvát",
  "Croatian (Croatia)": "horvát (Horvátország)",
  "Haitian Creole": "haiti kreol",
  "Hungarian": "magyar",
  "Hungarian (Hungary)": "magyar (Magyarország)",
  "Armenian": "örmény",
  "Indonesian": "indonéz",
  "Igbo": "igbó",
  "Icelandic": "izlandi",
  "Italian": "olasz",
  "Italian (Italy)": "olasz (Olaszország)",
  "Inuktitut": "inuktitut",
  "Japanese": "japán",
  "Japanese (Japan)": "japán (Japán)",
  "Georgian": "grúz",
  "Kabyle": "kabije",
  "Kazakh": "kazah",
  "Khmer": "khmer",
  "Kannada": "kannada",
  "Korean": "koreai",
  "Korean (Korea)": "koreai (Dél-Korea)",
  "Latin": "latin",
  "Lakota": "lakota",
  "Lao": "lao",
  "Lithuanian": "litván",
  "Latvian": "lett",
  "Māori": "maori",
  "Mongolian": "mongol",
  "Marathi": "maráthi",
  "Malay": "maláj",
  "Maltese": "máltai",
  "Burmese": "burmai",
  "Norwegian (Bokmål)": "norvég (bokmål)",
  "Norwegian (Bokmål, Norway)": "norvég (bokmål, Norvégia)",
  "Nepali": "nepáli",
  "Dutch": "holland",
  "Flemish": "holland (flamand)",
  "Norwegian (Nynorsk)": "norvég (nynorsk)",
  "Navajo": "navahó",
  "Turkish (Ottoman)": "oszmán-török",
  "Punjabi": "pandzsábi",
  "Persian (Old)": "óperzsa",
  "Polish": "lengyel",
  "Pashto": "pastu",
  "Portuguese": "portugál",
  "Portuguese (Brazil)": "portugál (Brazília)",
  "Portuguese (Portugal)": "portugál (Portugália)",
  "Quechua": "kecsua",
  "Romanian": "román",
  "Russian": "orosz",
  "Kinyarwanda": "kinyarvanda",
  "Sanskrit": "szanszkrit",
  "Sami (Northern)": "északi számi",
  "Sinhala": "szingaléz",
  "Slovak": "szlovák",
  "Slovak (Slovakia)": "szlovák (Szlovákia)",
  "Slovenian": "szlovén",
  "Slovenian (Slovenia)": "szlovén (Szlovénia)",
  "Sami (Southern)": "déli számi",
  "Sami (Northern)": "északi számi",
  "Sami (Lule)": "lulei számi",
  "Shona": "sona",
  "Serbian": "szerb",
  "Serbian (Latin)": "szerb (latin betűs)",
  "Swedish": "svéd",
  "Swedish (Sweden)": "svéd (Svédország)",
  "Swahili": "szuahéli",
  "Swahili (Kenya)": "szuahéli (Kenya)",
  "Swahili (Tanzania)": "szuahéli (Tanzánia)",
  "Syriac (Classical)": "klasszikus szír",
  "Tamil": "tamil",
  "Telugu": "telugu",
  "Tajik": "tadzsik",
  "Thai": "thai",
  "Thai (Thailand)": "thai (Thaiföld)",
  "Turkmen": "türkmén",
  "Tagalog": "tagalog",
  "Turkish": "török",
  "Turkish (Turkey)": "török (Törökország)",
  "Tatar": "tatár",
  "Uyghur": "ujgur",
  "Ukrainian": "ukrán",
  "Urdu": "urdu",
  "Uzbek": "üzbég",
  "Vietnamese": "vietnámi",
  "Wolof": "volof",
  "Xhosa": "xhosza",
  "Yiddish": "jiddis",
  "Yoruba": "joruba",
  "Maya (Yucatec)": "jukatan maja",
  "Chinese": "kínai",
  "Chinese (Simplified)": "kínai (egyszerűsített)",
  "Chinese (Simplified)": "kínai (egyszerűsített)",
  "Chinese (Traditional)": "kínai (hagyományos)",
  "Chinese (Hong Kong)": "kínai (Hongkong)",
  "Chinese (Singapore)": "kínai (Szingapúr)",
  "Chinese (Traditional)": "kínai (Tajvan)",
  "Zulu": "zulu",
  "Zulu": "zulu (Dél-Afrika)"
});