tinymce.addI18n('hy', {
  "-Language Not Set-": "-Լեզուն չի սահմանված-",
  "Choose from list": "Ընտրել ցանկից",
  "Choose languages": "Ընտրել լեզուներ",
  "Choose up to six languages": "Ընտրել մինչև վեց լեզու",
  "Configure languages": "Կարգավորել լեզուները",
  "Current language:": "Ներկայիս լեզու․",
  "Enter a valid language code with no spaces. Or, press cancel.": "Մուտքագրել վավեր լեզվի կոդ առանց բացատների։ Կամ սեղմել չեղարկել։",
  "Enter manually": "Մուտքագրել ձեռքով",
  "Enter new lang code (e.g., \"en-US\"):": "Մուտքագրել նոր լեզվի կոդը (օր․՝ \"en-US\")․",
  "Indicate current language": "Ցույց տալ ներկայիս լեզուն",
  "Manually enter language {{number}}:": "Ձեռքով մուտքագրել {{number}} լեզուն․",
  "New Language:": "Նոր լեզու․",
  "None": "Ոչինչ",
  "Other - Enter manually": "Այլ - Մուտքագրել ձեռքով",
  "Really remove all language markup from the document?": "Իսկապե՞ս հեռացնել բոլոր լեզվական նշանակումները փաստաթղթից։",
  "Remove All lang markup": "Հեռացնել բոլոր լեզվական նշանակումները",
  "Remove Language Markup": "Հեռացնել լեզվական նշանակումը",
  "Remove current lang value": "Հեռացնել ներկայիս լեզվի արժեքը",
  "Reveal lang markup": "Ցույց տալ լեզվական նշանակումը",
  "Select language {{number}}:": "Ընտրել {{number}} լեզուն․",
  "Select the document's default language.": "Ընտրել փաստաթղթի լռելյայն լեզուն։",
  "Set default document language": "Սահմանել փաստաթղթի լռելյայն լեզուն",
  "Set text language": "Սահմանել տեքստի լեզուն",
  "Afrikaans": "աֆրիկաանս",
  "Afrikaans": "աֆրիկաանս (Հարավային Աֆրիկա)",
  "Akan": "աքան",
  "Amharic": "ամհարերեն",
  "Arabic": "արաբերեն",
  "Arabic (Egypt)": "արաբերեն (Եգիպտոս)",
  "Arabic (Morocco)": "արաբերեն (Մարոկկո)",
  "Arabic (Saudi Arabia)": "արաբերեն (Սաուդյան Արաբիա)",
  "Azerbaijani": "ադրբեջաներեն",
  "Belarusian": "բելառուսերեն",
  "Bulgarian": "բուլղարերեն",
  "Bulgarian (Bulgaria)": "բուլղարերեն (Բուլղարիա)",
  "Bhojpuri": "բհոպուրի",
  "Bambara": "բամբարա",
  "Bangla": "բենգալերեն",
  "Tibetan": "տիբեթերեն",
  "Bosnian": "բոսնիերեն",
  "Catalan": "կատալաներեն",
  "Coptic": "ղպտերեն",
  "Cree": "կրի",
  "Czech": "չեխերեն",
  "Church Slavic": "եկեղեցական սլավոներեն",
  "Welsh": "ուելսերեն",
  "Danish": "դանիերեն",
  "German": "գերմաներեն",
  "German (Austria)": "գերմաներեն (Ավստրիա)",
  "German (Switzerland)": "գերմաներեն (Շվեյցարիա)",
  "German (Germany)": "գերմաներեն (Գերմանիա)",
  "Divehi": "դիվեհի",
  "Greek": "հունարեն",
  "English": "անգլերեն",
  "English (Australia)": "անգլերեն (Ավստրալիա)",
  "English (Canada)": "անգլերեն (Կանադա)",
  "English (United Kingdom)": "անգլերեն (Մեծ Բրիտանիա)",
  "English (Ireland)": "անգլերեն (Իռլանդիա)",
  "English (India)": "անգլերեն (Հնդկաստան)",
  "English (Trinidad)": "անգլերեն (Տրինիդադ)",
  "English (United States)": "անգլերեն (ԱՄՆ)",
  "English (South Africa)": "անգլերեն (Հարավային Աֆրիկա)",
  "Esperanto": "էսպերանտո",
  "Spanish": "իսպաներեն",
  "Spanish (Argentina)": "իսպաներեն (Արգենտինա)",
  "Spanish (Chile)": "իսպաներեն (Չիլի)",
  "Spanish (Colombia)": "իսպաներեն (Կոլումբիա)",
  "Spanish (Costa Rica)": "իսպաներեն (Կոստա Ռիկա)",
  "Spanish (Spain)": "իսպաներեն (Իսպանիա)",
  "Spanish (Mexico)": "իսպաներեն (Մեքսիկա)",
  "Spanish (Peru)": "իսպաներեն (Պերու)",
  "Estonian": "էստոներեն",
  "Basque": "բասկերեն",
  "Persian": "պարսկերեն",
  "Dari": "դարի",
  "Persian (Iran)": "պարսկերեն (Իրան)",
  "Fula": "ֆուլահ",
  "Finnish": "ֆիններեն",
  "Finnish (Finland)": "ֆիններեն (Ֆինլանդիա)",
  "Filipino": "ֆիլիպիներեն",
  "French": "ֆրանսերեն",
  "French (Belgium)": "ֆրանսերեն (Բելգիա)",
  "French (Canada)": "ֆրանսերեն (Կանադա)",
  "French (Switzerland)": "ֆրանսերեն (Շվեյցարիա)",
  "Irish": "իռլանդերեն",
  "Galician": "գալիսերեն",
  "Greek (Ancient)": "հին հունարեն",
  "Hausa": "հաուսա",
  "Hebrew": "եբրայերեն",
  "Hebrew (Israel)": "եբրայերեն (Իսրայել)",
  "Hindi": "հինդի",
  "Croatian": "խորվաթերեն",
  "Croatian (Croatia)": "խորվաթերեն (Խորվաթիա)",
  "Haitian Creole": "հայիթյան կրեոլ",
  "Hungarian": "հունգարերեն",
  "Hungarian (Hungary)": "հունգարերեն (Հունգարիա)",
  "Armenian": "հայերեն",
  "Indonesian": "ինդոնեզերեն",
  "Igbo": "իգբո",
  "Icelandic": "իսլանդերեն",
  "Italian": "իտալերեն",
  "Italian (Italy)": "իտալերեն (Իտալիա)",
  "Inuktitut": "ինուկտիտուտ",
  "Japanese": "ճապոներեն",
  "Japanese (Japan)": "ճապոներեն (Ճապոնիա)",
  "Georgian": "վրացերեն",
  "Kabyle": "կաբիլերեն",
  "Kazakh": "ղազախերեն",
  "Khmer": "քմերերեն",
  "Kannada": "կաննադա",
  "Korean": "կորեերեն",
  "Korean (Korea)": "կորեերեն (Կորեա)",
  "Latin": "լատիներեն",
  "Lakota": "լակոտա",
  "Lao": "լաոսերեն",
  "Lithuanian": "լիտվերեն",
  "Latvian": "լատվիերեն",
  "Māori": "մաորի",
  "Mongolian": "մոնղոլերեն",
  "Marathi": "մարաթի",
  "Malay": "մալայերեն",
  "Maltese": "մալթայերեն",
  "Burmese": "բիրմայերեն",
  "Norwegian (Bokmål)": "նորվեգերեն (բուկմոլ)",
  "Norwegian (Bokmål, Norway)": "նորվեգերեն (բուկմոլ, Նորվեգիա)",
  "Nepali": "նեպալերեն",
  "Dutch": "հոլանդերեն",
  "Flemish": "ֆլամանդերեն",
  "Norwegian (Nynorsk)": "նորվեգերեն (նյունոշք)",
  "Navajo": "նավախո",
  "Turkish (Ottoman)": "օսմաներեն",
  "Punjabi": "փենջաբերեն",
  "Persian (Old)": "հին պարսկերեն",
  "Polish": "լեհերեն",
  "Pashto": "փուշթու",
  "Portuguese": "պորտուգալերեն",
  "Portuguese (Brazil)": "պորտուգալերեն (Բրազիլիա)",
  "Portuguese (Portugal)": "պորտուգալերեն (Պորտուգալիա)",
  "Quechua": "կեչուա",
  "Romanian": "ռումիներեն",
  "Russian": "ռուսերեն",
  "Kinyarwanda": "կինյառուանդա",
  "Sanskrit": "սանսկրիտ",
  "Sami (Northern)": "հյուսիսային սաամի",
  "Sinhala": "սինհալերեն",
  "Slovak": "սլովակերեն",
  "Slovak (Slovakia)": "սլովակերեն (Սլովակիա)",
  "Slovenian": "սլովեներեն",
  "Slovenian (Slovenia)": "սլովեներեն (Սլովենիա)",
  "Sami (Southern)": "հարավային սաամի",
  "Sami (Northern)": "հյուսիսային սաամի",
  "Sami (Lule)": "լուլե սաամի",
  "Shona": "շոնա",
  "Serbian": "սերբերեն",
  "Serbian (Latin)": "սերբերեն (լատիներեն)",
  "Swedish": "շվեդերեն",
  "Swedish (Sweden)": "շվեդերեն (Շվեդիա)",
  "Swahili": "սուահիլի",
  "Swahili (Kenya)": "սուահիլի (Քենիա)",
  "Swahili (Tanzania)": "սուահիլի (Տանզանիա)",
  "Syriac (Classical)": "դասական սիրիական",
  "Tamil": "թամիլերեն",
  "Telugu": "թելուգու",
  "Tajik": "տաջիկերեն",
  "Thai": "թայերեն",
  "Thai (Thailand)": "թայերեն (Թաիլանդ)",
  "Turkmen": "թուրքմեներեն",
  "Tagalog": "տագալերեն",
  "Turkish": "թուրքերեն",
  "Turkish (Turkey)": "թուրքերեն (Թուրքիա)",
  "Tatar": "թաթարերեն",
  "Uyghur": "ույղուրերեն",
  "Ukrainian": "ուկրաիներեն",
  "Urdu": "ուրդու",
  "Uzbek": "ուզբեկերեն",
  "Vietnamese": "վիետնամերեն",
  "Wolof": "վոլոֆ",
  "Xhosa": "քոսա",
  "Yiddish": "իդիշ",
  "Yoruba": "յորուբա",
  "Maya (Yucatec)": "յուկատեկ մայա",
  "Chinese": "չինարեն",
  "Chinese (Simplified)": "չինարեն (պարզեցված)",
  "Chinese (Simplified)": "չինարեն (պարզեցված)",
  "Chinese (Traditional)": "չինարեն (ավանդական)",
  "Chinese (Hong Kong)": "չինարեն (Հոնկոնգ)",
  "Chinese (Singapore)": "չինարեն (Սինգապուր)",
  "Chinese (Traditional)": "չինարեն (Թայվան)",
  "Zulu": "զուլուերեն",
  "Zulu": "զուլուերեն (Հարավային Աֆրիկա)"
});