tinymce.addI18n('id', {
  "-Language Not Set-": "-Bahasa Tidak Diatur-",
  "Choose from list": "Pilih dari daftar",
  "Choose languages": "Pilih bahasa",
  "Choose up to six languages": "Pilih hingga enam bahasa",
  "Configure languages": "Konfigurasi bahasa",
  "Current language:": "Bahasa saat ini:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Masukkan kode bahasa yang valid tanpa spasi. Atau tekan batal.",
  "Enter manually": "Masukkan secara manual",
  "Enter new lang code (e.g., \"en-US\"):": "Masukkan kode bahasa baru (contoh, \"id-ID\"):",
  "Indicate current language": "Tunjukkan bahasa saat ini",
  "Manually enter language {{number}}:": "Masukkan secara manual bahasa {{number}}:",
  "New Language:": "Bahasa Baru:",
  "None": "Tidak ada",
  "Other - Enter manually": "Lainnya - Masukkan secara manual",
  "Really remove all language markup from the document?": "Benar-benar hapus semua markup bahasa dari dokumen?",
  "Remove All lang markup": "Hapus semua markup bahasa",
  "Remove Language Markup": "Hapus Markup Bahasa",
  "Remove current lang value": "Hapus nilai bahasa saat ini",
  "Reveal lang markup": "Tampilkan markup bahasa",
  "Select language {{number}}:": "Pilih bahasa {{number}}:",
  "Select the document's default language.": "Pilih bahasa default dokumen.",
  "Set default document language": "Atur bahasa dokumen default",
  "Set text language": "Atur bahasa teks",
  "Afrikaans": "Afrikaans",
  "Afrikaans": "Afrikaans (Afrika Selatan)",
  "Akan": "Akan",
  "Amharic": "Amharik",
  "Arabic": "Arab",
  "Arabic (Egypt)": "Arab (Mesir)",
  "Arabic (Morocco)": "Arab (Maroko)",
  "Arabic (Saudi Arabia)": "Arab (Arab Saudi)",
  "Azerbaijani": "Azerbaijan",
  "Belarusian": "Belarus",
  "Bulgarian": "Bulgaria",
  "Bulgarian (Bulgaria)": "Bulgaria (Bulgaria)",
  "Bhojpuri": "Bhojpuri",
  "Bambara": "Bambara",
  "Bangla": "Bengali",
  "Tibetan": "Tibet",
  "Bosnian": "Bosnia",
  "Catalan": "Katalan",
  "Coptic": "Koptik",
  "Cree": "Kree",
  "Czech": "Ceko",
  "Church Slavic": "Slavonia Gereja",
  "Welsh": "Welsh",
  "Danish": "Denmark",
  "German": "Jerman",
  "German (Austria)": "Jerman (Austria)",
  "German (Switzerland)": "Jerman (Swiss)",
  "German (Germany)": "Jerman (Jerman)",
  "Divehi": "Divehi",
  "Greek": "Yunani",
  "English": "Inggris",
  "English (Australia)": "Inggris (Australia)",
  "English (Canada)": "Inggris (Kanada)",
  "English (United Kingdom)": "Inggris (Britania Raya)",
  "English (Ireland)": "Inggris (Irlandia)",
  "English (India)": "Inggris (India)",
  "English (Trinidad)": "Inggris (Trinidad)",
  "English (United States)": "Inggris (Amerika Serikat)",
  "English (South Africa)": "Inggris (Afrika Selatan)",
  "Esperanto": "Esperanto",
  "Spanish": "Spanyol",
  "Spanish (Argentina)": "Spanyol (Argentina)",
  "Spanish (Chile)": "Spanyol (Chili)",
  "Spanish (Colombia)": "Spanyol (Kolombia)",
  "Spanish (Costa Rica)": "Spanyol (Kosta Rika)",
  "Spanish (Spain)": "Spanyol (Spanyol)",
  "Spanish (Mexico)": "Spanyol (Meksiko)",
  "Spanish (Peru)": "Spanyol (Peru)",
  "Estonian": "Estonia",
  "Basque": "Basque",
  "Persian": "Persia",
  "Dari": "Dari",
  "Persian (Iran)": "Persia (Iran)",
  "Fula": "Fula",
  "Finnish": "Finlandia",
  "Finnish (Finland)": "Finlandia (Finlandia)",
  "Filipino": "Filipino",
  "French": "Prancis",
  "French (Belgium)": "Prancis (Belgia)",
  "French (Canada)": "Prancis (Kanada)",
  "French (Switzerland)": "Prancis (Swiss)",
  "Irish": "Irlandia",
  "Galician": "Galisia",
  "Greek (Ancient)": "Yunani (Kuno)",
  "Hausa": "Hausa",
  "Hebrew": "Ibrani",
  "Hebrew (Israel)": "Ibrani (Israel)",
  "Hindi": "Hindi",
  "Croatian": "Kroasia",
  "Croatian (Croatia)": "Kroasia (Kroasia)",
  "Haitian Creole": "Kreol Haiti",
  "Hungarian": "Hungaria",
  "Hungarian (Hungary)": "Hungaria (Hungaria)",
  "Armenian": "Armenia",
  "Indonesian": "Indonesia",
  "Igbo": "Igbo",
  "Icelandic": "Islandia",
  "Italian": "Italia",
  "Italian (Italy)": "Italia (Italia)",
  "Inuktitut": "Inuktitut",
  "Japanese": "Jepang",
  "Japanese (Japan)": "Jepang (Jepang)",
  "Georgian": "Georgia",
  "Kabyle": "Kabyle",
  "Kazakh": "Kazakh",
  "Khmer": "Khmer",
  "Kannada": "Kannada",
  "Korean": "Korea",
  "Korean (Korea)": "Korea (Korea)",
  "Latin": "Latin",
  "Lakota": "Lakota",
  "Lao": "Lao",
  "Lithuanian": "Lithuania",
  "Latvian": "Latvia",
  "Māori": "Māori",
  "Mongolian": "Mongolia",
  "Marathi": "Marathi",
  "Malay": "Melayu",
  "Maltese": "Malta",
  "Burmese": "Burma",
  "Norwegian (Bokmål)": "Norwegia (Bokmål)",
  "Norwegian (Bokmål, Norway)": "Norwegia (Bokmål, Norwegia)",
  "Nepali": "Nepali",
  "Dutch": "Belanda",
  "Flemish": "Flemish",
  "Norwegian (Nynorsk)": "Norwegia (Nynorsk)",
  "Navajo": "Navajo",
  "Turkish (Ottoman)": "Turki (Ottoman)",
  "Punjabi": "Punjabi",
  "Persian (Old)": "Persia (Kuno)",
  "Polish": "Polandia",
  "Pashto": "Pashto",
  "Portuguese": "Portugis",
  "Portuguese (Brazil)": "Portugis (Brasil)",
  "Portuguese (Portugal)": "Portugis (Portugal)",
  "Quechua": "Quechua",
  "Romanian": "Romania",
  "Russian": "Rusia",
  "Kinyarwanda": "Kinyarwanda",
  "Sanskrit": "Sanskerta",
  "Sami (Northern)": "Sami (Utara)",
  "Sinhala": "Sinhala",
  "Slovak": "Slovak",
  "Slovak (Slovakia)": "Slovak (Slovakia)",
  "Slovenian": "Slovenia",
  "Slovenian (Slovenia)": "Slovenia (Slovenia)",
  "Sami (Southern)": "Sami (Selatan)",
  "Sami (Northern)": "Sami (Utara)",
  "Sami (Lule)": "Sami (Lule)",
  "Shona": "Shona",
  "Serbian": "Serbia",
  "Serbian (Latin)": "Serbia (Latin)",
  "Swedish": "Swedia",
  "Swedish (Sweden)": "Swedia (Swedia)",
  "Swahili": "Swahili",
  "Swahili (Kenya)": "Swahili (Kenya)",
  "Swahili (Tanzania)": "Swahili (Tanzania)",
  "Syriac (Classical)": "Suriah (Klasik)",
  "Tamil": "Tamil",
  "Telugu": "Telugu",
  "Tajik": "Tajik",
  "Thai": "Thai",
  "Thai (Thailand)": "Thai (Thailand)",
  "Turkmen": "Turkmen",
  "Tagalog": "Tagalog",
  "Turkish": "Turki",
  "Turkish (Turkey)": "Turki (Turki)",
  "Tatar": "Tatar",
  "Uyghur": "Uyghur",
  "Ukrainian": "Ukraina",
  "Urdu": "Urdu",
  "Uzbek": "Uzbek",
  "Vietnamese": "Vietnam",
  "Wolof": "Wolof",
  "Xhosa": "Xhosa",
  "Yiddish": "Yiddish",
  "Yoruba": "Yoruba",
  "Maya (Yucatec)": "Maya (Yucatec)",
  "Chinese": "Tionghoa",
  "Chinese (Simplified)": "Tionghoa (Sederhana)",
  "Chinese (Simplified)": "Tionghoa (Sederhana)",
  "Chinese (Traditional)": "Tionghoa (Tradisional)",
  "Chinese (Hong Kong)": "Tionghoa (Hong Kong)",
  "Chinese (Singapore)": "Tionghoa (Singapura)",
  "Chinese (Traditional)": "Tionghoa (Taiwan)",
  "Zulu": "Zulu",
  "Zulu": "Zulu (Afrika Selatan)"
});