tinymce.addI18n('is', {
  "-Language Not Set-": "-Tungumál ekki stillt-",
  "Choose from list": "Veldu af lista",
  "Choose languages": "Veldu tungumál",
  "Choose up to six languages": "Veldu allt að sex tungumál",
  "Configure languages": "Stilla tungumál",
  "Current language:": "Núverandi tungumál:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Sláðu inn gildann tungumálakóða án bila. Eða ýttu á hætta við.",
  "Enter manually": "Sláðu inn handvirkt",
  "Enter new lang code (e.g., \"en-US\"):": "Sláðu inn nýjan tungumálakóða (t.d., \"en-US\"):",
  "Indicate current language": "Tilgreina núverandi tungumál",
  "Manually enter language {{number}}:": "Sláðu handvirkt inn tungumál {{number}}:",
  "New Language:": "Nýtt tungumál:",
  "None": "Ekkert",
  "Other - Enter manually": "Annað - Sláðu inn handvirkt",
  "Really remove all language markup from the document?": "Viltu virkilega fjarlægja allar tungumálamerkingar úr skjalinu?",
  "Remove All lang markup": "Fjarlægja allar tungumálamerkingar",
  "Remove Language Markup": "Fjarlægja tungumálamerkingar",
  "Remove current lang value": "Fjarlægja núverandi tungumálagildi",
  "Reveal lang markup": "Sýna tungumálamerkingar",
  "Select language {{number}}:": "Veldu tungumál {{number}}:",
  "Select the document's default language.": "Veldu sjálfgefið tungumál skjalsins.",
  "Set default document language": "Stilla sjálfgefið tungumál skjals",
  "Set text language": "Stilla tungumál texta",
  "Afrikaans": "afríkanska",
  "Afrikaans": "afríkanska (Suður-Afríka)",
  "Akan": "akan",
  "Amharic": "amharíska",
  "Arabic": "arabíska",
  "Arabic (Egypt)": "arabíska (Egyptaland)",
  "Arabic (Morocco)": "arabíska (Marokkó)",
  "Arabic (Saudi Arabia)": "arabíska (Sádi-Arabía)",
  "Azerbaijani": "aserska",
  "Belarusian": "hvítrússneska",
  "Bulgarian": "búlgarska",
  "Bulgarian (Bulgaria)": "búlgarska (Búlgaría)",
  "Bhojpuri": "bojpúrí",
  "Bambara": "bambara",
  "Bangla": "bengalska",
  "Tibetan": "tíbeska",
  "Bosnian": "bosníska",
  "Catalan": "katalónska",
  "Coptic": "koptíska",
  "Cree": "krí",
  "Czech": "tékkneska",
  "Church Slavic": "kirkjuslavneska",
  "Welsh": "velska",
  "Danish": "danska",
  "German": "þýska",
  "German (Austria)": "þýska (Austurríki)",
  "German (Switzerland)": "þýska (Sviss)",
  "German (Germany)": "þýska (Þýskaland)",
  "Divehi": "dívehí",
  "Greek": "gríska",
  "English": "enska",
  "English (Australia)": "enska (Ástralía)",
  "English (Canada)": "enska (Kanada)",
  "English (United Kingdom)": "enska (Bretland)",
  "English (Ireland)": "enska (Írland)",
  "English (India)": "enska (Indland)",
  "English (Trinidad)": "enska (Trínidad)",
  "English (United States)": "enska (Bandaríkin)",
  "English (South Africa)": "enska (Suður-Afríka)",
  "Esperanto": "esperantó",
  "Spanish": "spænska",
  "Spanish (Argentina)": "spænska (Argentína)",
  "Spanish (Chile)": "spænska (Síle)",
  "Spanish (Colombia)": "spænska (Kólumbía)",
  "Spanish (Costa Rica)": "spænska (Kosta Ríka)",
  "Spanish (Spain)": "spænska (Spánn)",
  "Spanish (Mexico)": "spænska (Mexíkó)",
  "Spanish (Peru)": "spænska (Perú)",
  "Estonian": "eistneska",
  "Basque": "baskneska",
  "Persian": "persneska",
  "Dari": "darí",
  "Persian (Iran)": "persneska (Íran)",
  "Fula": "fúla",
  "Finnish": "finnska",
  "Finnish (Finland)": "finnska (Finnland)",
  "Filipino": "filippseyska",
  "French": "franska",
  "French (Belgium)": "franska (Belgía)",
  "French (Canada)": "franska (Kanada)",
  "French (Switzerland)": "franska (Sviss)",
  "Irish": "írska",
  "Galician": "galisíska",
  "Greek (Ancient)": "gríska (forn)",
  "Hausa": "hása",
  "Hebrew": "hebreska",
  "Hebrew (Israel)": "hebreska (Ísrael)",
  "Hindi": "hindí",
  "Croatian": "króatíska",
  "Croatian (Croatia)": "króatíska (Króatía)",
  "Haitian Creole": "haítíska",
  "Hungarian": "ungverska",
  "Hungarian (Hungary)": "ungverska (Ungverjaland)",
  "Armenian": "armenska",
  "Indonesian": "indónesíska",
  "Igbo": "ígbó",
  "Icelandic": "íslenska",
  "Italian": "ítalska",
  "Italian (Italy)": "ítalska (Ítalía)",
  "Inuktitut": "inúktitút",
  "Japanese": "japanska",
  "Japanese (Japan)": "japanska (Japan)",
  "Georgian": "georgíska",
  "Kabyle": "kabíle",
  "Kazakh": "kasakska",
  "Khmer": "kmer",
  "Kannada": "kannada",
  "Korean": "kóreska",
  "Korean (Korea)": "kóreska (Kórea)",
  "Latin": "latína",
  "Lakota": "lakóta",
  "Lao": "laó",
  "Lithuanian": "litháíska",
  "Latvian": "lettneska",
  "Māori": "maorí",
  "Mongolian": "mongólska",
  "Marathi": "maratí",
  "Malay": "malaíska",
  "Maltese": "maltneska",
  "Burmese": "búrmneska",
  "Norwegian (Bokmål)": "norska (bókmál)",
  "Norwegian (Bokmål, Norway)": "norska (bókmál, Noregur)",
  "Nepali": "nepalska",
  "Dutch": "hollenska",
  "Flemish": "flæmska",
  "Norwegian (Nynorsk)": "norska (nýnorska)",
  "Navajo": "navahó",
  "Turkish (Ottoman)": "tyrkneska (ottóman)",
  "Punjabi": "púnjabí",
  "Persian (Old)": "persneska (forn)",
  "Polish": "pólska",
  "Pashto": "pastú",
  "Portuguese": "portúgalska",
  "Portuguese (Brazil)": "portúgalska (Brasilía)",
  "Portuguese (Portugal)": "portúgalska (Portúgal)",
  "Quechua": "kvesjúa",
  "Romanian": "rúmenska",
  "Russian": "rússneska",
  "Kinyarwanda": "kínjarvanda",
  "Sanskrit": "sanskrít",
  "Sami (Northern)": "samíska (norður)",
  "Sinhala": "singalíska",
  "Slovak": "slóvakíska",
  "Slovak (Slovakia)": "slóvakíska (Slóvakía)",
  "Slovenian": "slóvenska",
  "Slovenian (Slovenia)": "slóvenska (Slóvenía)",
  "Sami (Southern)": "samíska (suður)",
  "Sami (Northern)": "samíska (norður)",
  "Sami (Lule)": "samíska (lúle)",
  "Shona": "shona",
  "Serbian": "serbneska",
  "Serbian (Latin)": "serbneska (latnesk)",
  "Swedish": "sænska",
  "Swedish (Sweden)": "sænska (Svíþjóð)",
  "Swahili": "svahílí",
  "Swahili (Kenya)": "svahílí (Kenía)",
  "Swahili (Tanzania)": "svahílí (Tansanía)",
  "Syriac (Classical)": "sýrlenska (klassísk)",
  "Tamil": "tamílska",
  "Telugu": "telúgú",
  "Tajik": "tadsjikska",
  "Thai": "taílenska",
  "Thai (Thailand)": "taílenska (Taíland)",
  "Turkmen": "túrkmenska",
  "Tagalog": "tagalog",
  "Turkish": "tyrkneska",
  "Turkish (Turkey)": "tyrkneska (Tyrkland)",
  "Tatar": "tatarska",
  "Uyghur": "úígúr",
  "Ukrainian": "úkraínska",
  "Urdu": "úrdú",
  "Uzbek": "úsbekska",
  "Vietnamese": "víetnamska",
  "Wolof": "wolof",
  "Xhosa": "sósa",
  "Yiddish": "jiddíska",
  "Yoruba": "jórúba",
  "Maya (Yucatec)": "majamál (júkatesk)",
  "Chinese": "kínverska",
  "Chinese (Simplified)": "kínverska (einfölduð)",
  "Chinese (Simplified)": "kínverska (einfölduð)",
  "Chinese (Traditional)": "kínverska (hefðbundin)",
  "Chinese (Hong Kong)": "kínverska (Hong Kong)",
  "Chinese (Singapore)": "kínverska (Singapúr)",
  "Chinese (Traditional)": "kínverska (hefðbundin)",
  "Zulu": "súlú",
  "Zulu": "súlú (Suður-Afríka)"
});