tinymce.addI18n('it', {
  "-Language Not Set-": "-Lingua non impostata-",
  "Choose from list": "Scegli dalla lista",
  "Choose languages": "Scegli lingue",
  "Choose up to six languages": "Scegli fino a sei lingue",
  "Configure languages": "Configura lingue",
  "Current language:": "Lingua corrente:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Inserisci un codice lingua valido senza spazi. Oppure premi annulla.",
  "Enter manually": "Inserisci manualmente",
  "Enter new lang code (e.g., \"en-US\"):": "Inserisci nuovo codice lingua (es. \"en-US\"):",
  "Indicate current language": "Indica lingua corrente",
  "Manually enter language {{number}}:": "Inserisci manualmente lingua {{number}}:",
  "New Language:": "Nuova lingua:",
  "None": "Nessuno",
  "Other - Enter manually": "Altro - Inserisci manualmente",
  "Really remove all language markup from the document?": "Rimuovere davvero tutto il markup lingua dal documento?",
  "Remove All lang markup": "Rimuovi tutto il markup lingua",
  "Remove Language Markup": "Rimuovi markup lingua",
  "Remove current lang value": "Rimuovi valore lingua corrente",
  "Reveal lang markup": "Rivela markup lingua",
  "Select language {{number}}:": "Seleziona lingua {{number}}:",
  "Select the document's default language.": "Seleziona la lingua predefinita del documento.",
  "Set default document language": "Imposta lingua predefinita del documento",
  "Set text language": "Imposta lingua del testo",
  "Afrikaans": "afrikaans",
  "Afrikaans": "afrikaans (Sudafrica)",
  "Akan": "akan",
  "Amharic": "amarico",
  "Arabic": "arabo",
  "Arabic (Egypt)": "arabo (Egitto)",
  "Arabic (Morocco)": "arabo (Marocco)",
  "Arabic (Saudi Arabia)": "arabo (Arabia Saudita)",
  "Azerbaijani": "azerbaigiano",
  "Belarusian": "bielorusso",
  "Bulgarian": "bulgaro",
  "Bulgarian (Bulgaria)": "bulgaro (Bulgaria)",
  "Bhojpuri": "bhojpuri",
  "Bambara": "bambara",
  "Bangla": "bengalese",
  "Tibetan": "tibetano",
  "Bosnian": "bosniaco",
  "Catalan": "catalano",
  "Coptic": "copto",
  "Cree": "cree",
  "Czech": "ceco",
  "Church Slavic": "slavo ecclesiastico",
  "Welsh": "gallese",
  "Danish": "danese",
  "German": "tedesco",
  "German (Austria)": "tedesco (Austria)",
  "German (Switzerland)": "tedesco (Svizzera)",
  "German (Germany)": "tedesco (Germania)",
  "Divehi": "divehi",
  "Greek": "greco",
  "English": "inglese",
  "English (Australia)": "inglese (Australia)",
  "English (Canada)": "inglese (Canada)",
  "English (United Kingdom)": "inglese (Regno Unito)",
  "English (Ireland)": "inglese (Irlanda)",
  "English (India)": "inglese (India)",
  "English (Trinidad)": "inglese (Trinidad)",
  "English (United States)": "inglese (Stati Uniti)",
  "English (South Africa)": "inglese (Sudafrica)",
  "Esperanto": "esperanto",
  "Spanish": "spagnolo",
  "Spanish (Argentina)": "spagnolo (Argentina)",
  "Spanish (Chile)": "spagnolo (Cile)",
  "Spanish (Colombia)": "spagnolo (Colombia)",
  "Spanish (Costa Rica)": "spagnolo (Costa Rica)",
  "Spanish (Spain)": "spagnolo (Spagna)",
  "Spanish (Mexico)": "spagnolo (Messico)",
  "Spanish (Peru)": "spagnolo (Perù)",
  "Estonian": "estone",
  "Basque": "basco",
  "Persian": "persiano",
  "Dari": "dari",
  "Persian (Iran)": "persiano (Iran)",
  "Fula": "fulah",
  "Finnish": "finlandese",
  "Finnish (Finland)": "finlandese (Finlandia)",
  "Filipino": "filippino",
  "French": "francese",
  "French (Belgium)": "francese (Belgio)",
  "French (Canada)": "francese (Canada)",
  "French (Switzerland)": "francese (Svizzera)",
  "Irish": "irlandese",
  "Galician": "galiziano",
  "Greek (Ancient)": "greco antico",
  "Hausa": "hausa",
  "Hebrew": "ebraico",
  "Hebrew (Israel)": "ebraico (Israele)",
  "Hindi": "hindi",
  "Croatian": "croato",
  "Croatian (Croatia)": "croato (Croazia)",
  "Haitian Creole": "creolo haitiano",
  "Hungarian": "ungherese",
  "Hungarian (Hungary)": "ungherese (Ungheria)",
  "Armenian": "armeno",
  "Indonesian": "indonesiano",
  "Igbo": "igbo",
  "Icelandic": "islandese",
  "Italian": "italiano",
  "Italian (Italy)": "italiano (Italia)",
  "Inuktitut": "inuktitut",
  "Japanese": "giapponese",
  "Japanese (Japan)": "giapponese (Giappone)",
  "Georgian": "georgiano",
  "Kabyle": "cabilo",
  "Kazakh": "kazako",
  "Khmer": "khmer",
  "Kannada": "kannada",
  "Korean": "coreano",
  "Korean (Korea)": "coreano (Corea del Sud)",
  "Latin": "latino",
  "Lakota": "lakota",
  "Lao": "lao",
  "Lithuanian": "lituano",
  "Latvian": "lettone",
  "Māori": "maori",
  "Mongolian": "mongolo",
  "Marathi": "marathi",
  "Malay": "malese",
  "Maltese": "maltese",
  "Burmese": "birmano",
  "Norwegian (Bokmål)": "norvegese (bokmål)",
  "Norwegian (Bokmål, Norway)": "norvegese (bokmål, Norvegia)",
  "Nepali": "nepalese",
  "Dutch": "olandese",
  "Flemish": "fiammingo",
  "Norwegian (Nynorsk)": "norvegese (nynorsk)",
  "Navajo": "navajo",
  "Turkish (Ottoman)": "turco ottomano",
  "Punjabi": "punjabi",
  "Persian (Old)": "persiano antico",
  "Polish": "polacco",
  "Pashto": "pashto",
  "Portuguese": "portoghese",
  "Portuguese (Brazil)": "portoghese (Brasile)",
  "Portuguese (Portugal)": "portoghese (Portogallo)",
  "Quechua": "quechua",
  "Romanian": "rumeno",
  "Russian": "russo",
  "Kinyarwanda": "kinyarwanda",
  "Sanskrit": "sanscrito",
  "Sami (Northern)": "sami settentrionale",
  "Sinhala": "singalese",
  "Slovak": "slovacco",
  "Slovak (Slovakia)": "slovacco (Slovacchia)",
  "Slovenian": "sloveno",
  "Slovenian (Slovenia)": "sloveno (Slovenia)",
  "Sami (Southern)": "sami meridionale",
  "Sami (Northern)": "sami settentrionale",
  "Sami (Lule)": "sami di Lule",
  "Shona": "shona",
  "Serbian": "serbo",
  "Serbian (Latin)": "serbo (latino)",
  "Swedish": "svedese",
  "Swedish (Sweden)": "svedese (Svezia)",
  "Swahili": "swahili",
  "Swahili (Kenya)": "swahili (Kenya)",
  "Swahili (Tanzania)": "swahili (Tanzania)",
  "Syriac (Classical)": "siriaco classico",
  "Tamil": "tamil",
  "Telugu": "telugu",
  "Tajik": "tagico",
  "Thai": "thailandese",
  "Thai (Thailand)": "thailandese (Thailandia)",
  "Turkmen": "turcomanno",
  "Tagalog": "tagalog",
  "Turkish": "turco",
  "Turkish (Turkey)": "turco (Turchia)",
  "Tatar": "tataro",
  "Uyghur": "uiguro",
  "Ukrainian": "ucraino",
  "Urdu": "urdu",
  "Uzbek": "uzbeco",
  "Vietnamese": "vietnamita",
  "Wolof": "wolof",
  "Xhosa": "xhosa",
  "Yiddish": "yiddish",
  "Yoruba": "yoruba",
  "Maya (Yucatec)": "maya yucateco",
  "Chinese": "cinese",
  "Chinese (Simplified)": "cinese (semplificato)",
  "Chinese (Simplified)": "cinese (semplificato)",
  "Chinese (Traditional)": "cinese (tradizionale)",
  "Chinese (Hong Kong)": "cinese (Hong Kong)",
  "Chinese (Singapore)": "cinese (Singapore)",
  "Chinese (Traditional)": "cinese (tradizionale)",
  "Zulu": "zulu",
  "Zulu": "zulu (Sudafrica)"
});