tinymce.addI18n('ko_KR', {
  "-Language Not Set-": "-언어가 설정되지 않음-",
  "Choose from list": "목록에서 선택",
  "Choose languages": "언어 선택",
  "Choose up to six languages": "최대 6개 언어 선택",
  "Configure languages": "언어 구성",
  "Current language:": "현재 언어:",
  "Enter a valid language code with no spaces. Or, press cancel.": "공백 없이 유효한 언어 코드를 입력하거나 취소를 누르세요.",
  "Enter manually": "수동 입력",
  "Enter new lang code (e.g., \"en-US\"):": "새 언어 코드를 입력하세요 (예: \"en-US\"):",
  "Indicate current language": "현재 언어 표시",
  "Manually enter language {{number}}:": "언어 {{number}} 수동 입력:",
  "New Language:": "새 언어:",
  "None": "없음",
  "Other - Enter manually": "기타 - 수동 입력",
  "Really remove all language markup from the document?": "문서에서 모든 언어 마크업을 제거하시겠습니까?",
  "Remove All lang markup": "모든 언어 마크업 제거",
  "Remove Language Markup": "언어 마크업 제거",
  "Remove current lang value": "현재 언어 값 제거",
  "Reveal lang markup": "언어 마크업 표시",
  "Select language {{number}}:": "언어 {{number}} 선택:",
  "Select the document's default language.": "문서의 기본 언어를 선택하세요.",
  "Set default document language": "기본 문서 언어 설정",
  "Set text language": "텍스트 언어 설정",
  "Afrikaans": "아프리칸스어",
  "Afrikaans": "아프리칸스어 (남아프리카)",
  "Akan": "아칸어",
  "Amharic": "암하라어",
  "Arabic": "아랍어",
  "Arabic (Egypt)": "아랍어 (이집트)",
  "Arabic (Morocco)": "아랍어 (모로코)",
  "Arabic (Saudi Arabia)": "아랍어 (사우디아라비아)",
  "Azerbaijani": "아제르바이잔어",
  "Belarusian": "벨라루스어",
  "Bulgarian": "불가리아어",
  "Bulgarian (Bulgaria)": "불가리아어 (불가리아)",
  "Bhojpuri": "보즈푸리어",
  "Bambara": "밤바라어",
  "Bangla": "벵골어",
  "Tibetan": "티베트어",
  "Bosnian": "보스니아어",
  "Catalan": "카탈로니아어",
  "Coptic": "콥트어",
  "Cree": "크리어",
  "Czech": "체코어",
  "Church Slavic": "교회 슬라브어",
  "Welsh": "웨일스어",
  "Danish": "덴마크어",
  "German": "독일어",
  "German (Austria)": "독일어 (오스트리아)",
  "German (Switzerland)": "독일어 (스위스)",
  "German (Germany)": "독일어 (독일)",
  "Divehi": "디베히어",
  "Greek": "그리스어",
  "English": "영어",
  "English (Australia)": "영어 (호주)",
  "English (Canada)": "영어 (캐나다)",
  "English (United Kingdom)": "영어 (영국)",
  "English (Ireland)": "영어 (아일랜드)",
  "English (India)": "영어 (인도)",
  "English (Trinidad)": "영어 (트리니다드)",
  "English (United States)": "영어 (미국)",
  "English (South Africa)": "영어 (남아프리카)",
  "Esperanto": "에스페란토어",
  "Spanish": "스페인어",
  "Spanish (Argentina)": "스페인어 (아르헨티나)",
  "Spanish (Chile)": "스페인어 (칠레)",
  "Spanish (Colombia)": "스페인어 (콜롬비아)",
  "Spanish (Costa Rica)": "스페인어 (코스타리카)",
  "Spanish (Spain)": "스페인어 (스페인)",
  "Spanish (Mexico)": "스페인어 (멕시코)",
  "Spanish (Peru)": "스페인어 (페루)",
  "Estonian": "에스토니아어",
  "Basque": "바스크어",
  "Persian": "페르시아어",
  "Dari": "다리어",
  "Persian (Iran)": "페르시아어 (이란)",
  "Fula": "풀라어",
  "Finnish": "핀란드어",
  "Finnish (Finland)": "핀란드어 (핀란드)",
  "Filipino": "필리핀어",
  "French": "프랑스어",
  "French (Belgium)": "프랑스어 (벨기에)",
  "French (Canada)": "프랑스어 (캐나다)",
  "French (Switzerland)": "프랑스어 (스위스)",
  "Irish": "아일랜드어",
  "Galician": "갈리시아어",
  "Greek (Ancient)": "고대 그리스어",
  "Hausa": "하우사어",
  "Hebrew": "히브리어",
  "Hebrew (Israel)": "히브리어 (이스라엘)",
  "Hindi": "힌디어",
  "Croatian": "크로아티아어",
  "Croatian (Croatia)": "크로아티아어 (크로아티아)",
  "Haitian Creole": "아이티 크리올어",
  "Hungarian": "헝가리어",
  "Hungarian (Hungary)": "헝가리어 (헝가리)",
  "Armenian": "아르메니아어",
  "Indonesian": "인도네시아어",
  "Igbo": "이그보어",
  "Icelandic": "아이슬란드어",
  "Italian": "이탈리아어",
  "Italian (Italy)": "이탈리아어 (이탈리아)",
  "Inuktitut": "이누이트어",
  "Japanese": "일본어",
  "Japanese (Japan)": "일본어 (일본)",
  "Georgian": "조지아어",
  "Kabyle": "카빌어",
  "Kazakh": "카자흐어",
  "Khmer": "크메르어",
  "Kannada": "칸나다어",
  "Korean": "한국어",
  "Korean (Korea)": "한국어 (한국)",
  "Latin": "라틴어",
  "Lakota": "라코타어",
  "Lao": "라오어",
  "Lithuanian": "리투아니아어",
  "Latvian": "라트비아어",
  "Māori": "마오리어",
  "Mongolian": "몽골어",
  "Marathi": "마라티어",
  "Malay": "말레이어",
  "Maltese": "몰타어",
  "Burmese": "미얀마어",
  "Norwegian (Bokmål)": "노르웨이어 (보크말)",
  "Norwegian (Bokmål, Norway)": "노르웨이어 (보크말, 노르웨이)",
  "Nepali": "네팔어",
  "Dutch": "네덜란드어",
  "Flemish": "플라망어",
  "Norwegian (Nynorsk)": "노르웨이어 (뉘노르스크)",
  "Navajo": "나바호어",
  "Turkish (Ottoman)": "오스만 터키어",
  "Punjabi": "펀자브어",
  "Persian (Old)": "고대 페르시아어",
  "Polish": "폴란드어",
  "Pashto": "파슈토어",
  "Portuguese": "포르투갈어",
  "Portuguese (Brazil)": "포르투갈어 (브라질)",
  "Portuguese (Portugal)": "포르투갈어 (포르투갈)",
  "Quechua": "케추아어",
  "Romanian": "루마니아어",
  "Russian": "러시아어",
  "Kinyarwanda": "키냐르완다어",
  "Sanskrit": "산스크리트어",
  "Sami (Northern)": "북부 사미어",
  "Sinhala": "싱할라어",
  "Slovak": "슬로바키아어",
  "Slovak (Slovakia)": "슬로바키아어 (슬로바키아)",
  "Slovenian": "슬로베니아어",
  "Slovenian (Slovenia)": "슬로베니아어 (슬로베니아)",
  "Sami (Southern)": "남부 사미어",
  "Sami (Northern)": "북부 사미어",
  "Sami (Lule)": "룰레 사미어",
  "Shona": "쇼나어",
  "Serbian": "세르비아어",
  "Serbian (Latin)": "세르비아어 (라틴 문자)",
  "Swedish": "스웨덴어",
  "Swedish (Sweden)": "스웨덴어 (스웨덴)",
  "Swahili": "스와힐리어",
  "Swahili (Kenya)": "스와힐리어 (케냐)",
  "Swahili (Tanzania)": "스와힐리어 (탄자니아)",
  "Syriac (Classical)": "고전 시리아어",
  "Tamil": "타밀어",
  "Telugu": "텔루구어",
  "Tajik": "타지크어",
  "Thai": "태국어",
  "Thai (Thailand)": "태국어 (태국)",
  "Turkmen": "투르크멘어",
  "Tagalog": "타갈로그어",
  "Turkish": "터키어",
  "Turkish (Turkey)": "터키어 (터키)",
  "Tatar": "타타르어",
  "Uyghur": "위구르어",
  "Ukrainian": "우크라이나어",
  "Urdu": "우르두어",
  "Uzbek": "우즈베크어",
  "Vietnamese": "베트남어",
  "Wolof": "월로프어",
  "Xhosa": "코사어",
  "Yiddish": "이디시어",
  "Yoruba": "요루바어",
  "Maya (Yucatec)": "유카텍 마야어",
  "Chinese": "중국어",
  "Chinese (Simplified)": "중국어 (간체)",
  "Chinese (Simplified)": "중국어 (간체)",
  "Chinese (Traditional)": "중국어 (번체)",
  "Chinese (Hong Kong)": "중국어 (홍콩)",
  "Chinese (Singapore)": "중국어 (싱가포르)",
  "Chinese (Traditional)": "중국어 (번체)",
  "Zulu": "줄루어",
  "Zulu": "줄루어 (남아프리카)"
});