tinymce.addI18n('mi', {
  "-Language Not Set-": "-Kāore he Reo i Whakatakoto-",
  "Choose from list": "Kōwhiri i te raina",
  "Choose languages": "Kōwhiri ngā reo",
  "Choose up to six languages": "Kōwhiri hā ki a ono reo",
  "Configure languages": "Whiriwhiri ngā reo",
  "Current language:": "Reo o nāianei:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Whakaurunga waehere reo whaimana kore mokowā rānei. Rānei, pēhi whakakore.",
  "Enter manually": "Whakaurunga ā-ringaringa",
  "Enter new lang code (e.g., \"en-US\"):": "Whakaurunga waehere reo hōu (hei tauira, \"en-US\"):",
  "Indicate current language": "Tohu te reo o nāianei",
  "Manually enter language {{number}}:": "Whakaurunga ā-ringaringa reo {{number}}:",
  "New Language:": "Reo Hōu:",
  "None": "Kāore",
  "Other - Enter manually": "Kē atu - Whakaurunga ā-ringaringa",
  "Really remove all language markup from the document?": "He pono koe kī te tango katoa ngā tohu reo i te pukapuka?",
  "Remove All lang markup": "Tango katoa ngā tohu reo",
  "Remove Language Markup": "Tango Tohu Reo",
  "Remove current lang value": "Tango uara reo o nāianei",
  "Reveal lang markup": "Whakaatu tohu reo",
  "Select language {{number}}:": "Kōwhiri reo {{number}}:",
  "Select the document's default language.": "Kōwhiri te reo taunoa o te pukapuka.",
  "Set default document language": "Whakatakoto reo taunoa o te pukapuka",
  "Set text language": "Whakatakoto reo kuputuhi",
  "Afrikaans": "Awherikāna",
  "Afrikaans": "Awherikāna (Āwherika-ki-te-Tonga)",
  "Akan": "Ākana",
  "Amharic": "Amahereka",
  "Arabic": "Ārapi",
  "Arabic (Egypt)": "Ārapi (Ihipa)",
  "Arabic (Morocco)": "Ārapi (Moroko)",
  "Arabic (Saudi Arabia)": "Ārapi (Hauti Arepia)",
  "Azerbaijani": "Atepaihānia",
  "Belarusian": "Perarūhiana",
  "Bulgarian": "Purukāriana",
  "Bulgarian (Bulgaria)": "Purukāriana (Purukāria)",
  "Bhojpuri": "Pōhipuri",
  "Bambara": "Pāpara",
  "Bangla": "Pākara",
  "Tibetan": "Tipete",
  "Bosnian": "Pōngiana",
  "Catalan": "Katarana",
  "Coptic": "Kopitika",
  "Cree": "Kırī",
  "Czech": "Tieke",
  "Church Slavic": "Pūkāriana Tawhito",
  "Welsh": "Werehi",
  "Danish": "Teina",
  "German": "Tiamana",
  "German (Austria)": "Tiamana (Ōtelia)",
  "German (Switzerland)": "Tiamana (Huiterangi)",
  "German (Germany)": "Tiamana (Tiamani)",
  "Divehi": "Tīwhehi",
  "Greek": "Kariki",
  "English": "Ingarihi",
  "English (Australia)": "Ingarihi (Ahitereiriana)",
  "English (Canada)": "Ingarihi (Kānata)",
  "English (United Kingdom)": "Ingarihi (Kīngitanga Kotahi)",
  "English (Ireland)": "Ingarihi (Airangi)",
  "English (India)": "Ingarihi (Inia)",
  "English (Trinidad)": "Ingarihi (Tirinaki)",
  "English (United States)": "Ingarihi (Hononga-o-Amerika)",
  "English (South Africa)": "Ingarihi (Āwherika-ki-te-Tonga)",
  "Esperanto": "Eheperāto",
  "Spanish": "Pāniora",
  "Spanish (Argentina)": "Pāniora (Āketina)",
  "Spanish (Chile)": "Pāniora (Tire)",
  "Spanish (Colombia)": "Pāniora (Koromopia)",
  "Spanish (Costa Rica)": "Pāniora (Koha Rika)",
  "Spanish (Spain)": "Pāniora (Pēni)",
  "Spanish (Mexico)": "Pāniora (Mehikana)",
  "Spanish (Peru)": "Pāniora (Perū)",
  "Estonian": "Etōniana",
  "Basque": "Pākihi",
  "Persian": "Pāhiana",
  "Dari": "Tāri",
  "Persian (Iran)": "Pāhiana (Īrāna)",
  "Fula": "Whūra",
  "Finnish": "Whinirānia",
  "Finnish (Finland)": "Whinirānia (Whinirāni)",
  "Filipino": "Piripīno",
  "French": "Wīwī",
  "French (Belgium)": "Wīwī (Pehiamu)",
  "French (Canada)": "Wīwī (Kānata)",
  "French (Switzerland)": "Wīwī (Huiterangi)",
  "Irish": "Airihi",
  "Galician": "Karīhia",
  "Greek (Ancient)": "Kariki Tawhito",
  "Hausa": "Hauha",
  "Hebrew": "Hīperu",
  "Hebrew (Israel)": "Hīperu (Iharaira)",
  "Hindi": "Hīni",
  "Croatian": "Koroātiana",
  "Croatian (Croatia)": "Koroātiana (Koroātia)",
  "Haitian Creole": "Kereō Haiti",
  "Hungarian": "Hanekari",
  "Hungarian (Hungary)": "Hanekari (Hanekāria)",
  "Armenian": "Āmeniana",
  "Indonesian": "Initonīhiana",
  "Igbo": "Ikapo",
  "Icelandic": "Tiorangi",
  "Italian": "Itāriana",
  "Italian (Italy)": "Itāriana (Itāria)",
  "Inuktitut": "Inukitetūta",
  "Japanese": "Hapanihi",
  "Japanese (Japan)": "Hapanihi (Hapani)",
  "Georgian": "Hōriana",
  "Kabyle": "Kapāiro",
  "Kazakh": "Kahāka",
  "Khmer": "Kimēra",
  "Kannada": "Kanara",
  "Korean": "Kōreana",
  "Korean (Korea)": "Kōreana (Kōrea)",
  "Latin": "Rātini",
  "Lakota": "Rakōta",
  "Lao": "Rao",
  "Lithuanian": "Rituānia",
  "Latvian": "Rāwhia",
  "Māori": "Māori",
  "Mongolian": "Mongōria",
  "Marathi": "Marati",
  "Malay": "Marei",
  "Maltese": "Mārata",
  "Burmese": "Pēmīhi",
  "Norwegian (Bokmål)": "Nōwei (Pakamō)",
  "Norwegian (Bokmål, Norway)": "Nōwei (Pakamō, Nōwei)",
  "Nepali": "Nepari",
  "Dutch": "Tati",
  "Flemish": "Tati (Pehiamu)",
  "Norwegian (Nynorsk)": "Nōwei (Nīnōka)",
  "Navajo": "Nawahō",
  "Turkish (Ottoman)": "Tākei (Otomana)",
  "Punjabi": "Punutapi",
  "Persian (Old)": "Pāhiana Tawhito",
  "Polish": "Pōrihi",
  "Pashto": "Pāhitō",
  "Portuguese": "Pōtukīhi",
  "Portuguese (Brazil)": "Pōtukīhi (Parahi)",
  "Portuguese (Portugal)": "Pōtukīhi (Pōtukāra)",
  "Quechua": "Kētua",
  "Romanian": "Romeinia",
  "Russian": "Ruhiana",
  "Kinyarwanda": "Kiniawāna",
  "Sanskrit": "Hanahiti",
  "Sami (Northern)": "Hami (Raki)",
  "Sinhala": "Hinihāra",
  "Slovak": "Horowākia",
  "Slovak (Slovakia)": "Horowākia (Horowākia)",
  "Slovenian": "Horowinia",
  "Slovenian (Slovenia)": "Horowinia (Horowinia)",
  "Sami (Southern)": "Hami (Tonga)",
  "Sami (Northern)": "Hami (Raki)",
  "Sami (Lule)": "Hami (Lule)",
  "Shona": "Hōna",
  "Serbian": "Hirupia",
  "Serbian (Latin)": "Hirupia (Rātini)",
  "Swedish": "Huitene",
  "Swedish (Sweden)": "Huitene (Huitene)",
  "Swahili": "Wāhīri",
  "Swahili (Kenya)": "Wāhīri (Kenia)",
  "Swahili (Tanzania)": "Wāhīri (Tanahania)",
  "Syriac (Classical)": "Hiriaka Tawhito",
  "Tamil": "Tamira",
  "Telugu": "Teruku",
  "Tajik": "Tāhiki",
  "Thai": "Tai",
  "Thai (Thailand)": "Tai (Tairana)",
  "Turkmen": "Tākamana",
  "Tagalog": "Takaroka",
  "Turkish": "Tākei",
  "Turkish (Turkey)": "Tākei (Tākei)",
  "Tatar": "Tatā",
  "Uyghur": "Wīkura",
  "Ukrainian": "Ukareinga",
  "Urdu": "Ūrutu",
  "Uzbek": "Ūpeke",
  "Vietnamese": "Whitināmu",
  "Wolof": "Warawhe",
  "Xhosa": "Tōha",
  "Yiddish": "Irihi",
  "Yoruba": "Ōrūpa",
  "Maya (Yucatec)": "Maya (Yucatec)",
  "Chinese": "Hainamana",
  "Chinese (Simplified)": "Hainamana (Haina)",
  "Chinese (Simplified)": "Hainamana (Māmā)",
  "Chinese (Traditional)": "Hainamana (Tukuiho)",
  "Chinese (Hong Kong)": "Hainamana (Hong Kong)",
  "Chinese (Singapore)": "Hainamana (Hingapoa)",
  "Chinese (Traditional)": "Hainamana (Taiwan)",
  "Zulu": "Tūru",
  "Zulu": "Tūru (Āwherika-ki-te-Tonga)"
});