tinymce.addI18n('nl', {
  "-Language Not Set-": "-Taal niet ingesteld-",
  "Choose from list": "Kiezen uit lijst",
  "Choose languages": "Talen kiezen",
  "Choose up to six languages": "Kies maximaal zes talen",
  "Configure languages": "Talen configureren",
  "Current language:": "Huidige taal:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Voer een geldige taalcode in zonder spaties. Of druk op annuleren.",
  "Enter manually": "Handmatig invoeren",
  "Enter new lang code (e.g., \"en-US\"):": "Voer nieuwe taalcode in (bijv. \"en-US\"):",
  "Indicate current language": "Huidige taal aangeven",
  "Manually enter language {{number}}:": "Voer taal {{number}} handmatig in:",
  "New Language:": "Nieuwe taal:",
  "None": "Geen",
  "Other - Enter manually": "Anders - Handmatig invoeren",
  "Really remove all language markup from the document?": "Wilt u werkelijk alle taalmarkering uit het document verwijderen?",
  "Remove All lang markup": "Alle taalmarkering verwijderen",
  "Remove Language Markup": "Taalmarkering verwijderen",
  "Remove current lang value": "Huidige taalwaarde verwijderen",
  "Reveal lang markup": "Taalmarkering tonen",
  "Select language {{number}}:": "Selecteer taal {{number}}:",
  "Select the document's default language.": "Selecteer de standaardtaal van het document.",
  "Set default document language": "Standaard documenttaal instellen",
  "Set text language": "Teksttaal instellen",
  "Afrikaans": "Afrikaans",
  "Afrikaans": "Afrikaans (Zuid-Afrika)",
  "Akan": "Akan",
  "Amharic": "Amhaars",
  "Arabic": "Arabisch",
  "Arabic (Egypt)": "Arabisch (Egypte)",
  "Arabic (Morocco)": "Arabisch (Marokko)",
  "Arabic (Saudi Arabia)": "Arabisch (Saoedi-Arabië)",
  "Azerbaijani": "Azerbeidzjaans",
  "Belarusian": "Belarussisch",
  "Bulgarian": "Bulgaars",
  "Bulgarian (Bulgaria)": "Bulgaars (Bulgarije)",
  "Bhojpuri": "Bhojpuri",
  "Bambara": "Bambara",
  "Bangla": "Bengaals",
  "Tibetan": "Tibetaans",
  "Bosnian": "Bosnisch",
  "Catalan": "Catalaans",
  "Coptic": "Koptisch",
  "Cree": "Cree",
  "Czech": "Tsjechisch",
  "Church Slavic": "Kerkslavisch",
  "Welsh": "Welsh",
  "Danish": "Deens",
  "German": "Duits",
  "German (Austria)": "Duits (Oostenrijk)",
  "German (Switzerland)": "Duits (Zwitserland)",
  "German (Germany)": "Duits (Duitsland)",
  "Divehi": "Divehi",
  "Greek": "Grieks",
  "English": "Engels",
  "English (Australia)": "Engels (Australië)",
  "English (Canada)": "Engels (Canada)",
  "English (United Kingdom)": "Engels (Verenigd Koninkrijk)",
  "English (Ireland)": "Engels (Ierland)",
  "English (India)": "Engels (India)",
  "English (Trinidad)": "Engels (Trinidad)",
  "English (United States)": "Engels (Verenigde Staten)",
  "English (South Africa)": "Engels (Zuid-Afrika)",
  "Esperanto": "Esperanto",
  "Spanish": "Spaans",
  "Spanish (Argentina)": "Spaans (Argentinië)",
  "Spanish (Chile)": "Spaans (Chili)",
  "Spanish (Colombia)": "Spaans (Colombia)",
  "Spanish (Costa Rica)": "Spaans (Costa Rica)",
  "Spanish (Spain)": "Spaans (Spanje)",
  "Spanish (Mexico)": "Spaans (Mexico)",
  "Spanish (Peru)": "Spaans (Peru)",
  "Estonian": "Estisch",
  "Basque": "Baskisch",
  "Persian": "Perzisch",
  "Dari": "Dari",
  "Persian (Iran)": "Perzisch (Iran)",
  "Fula": "Fulah",
  "Finnish": "Fins",
  "Finnish (Finland)": "Fins (Finland)",
  "Filipino": "Filipijns",
  "French": "Frans",
  "French (Belgium)": "Frans (België)",
  "French (Canada)": "Frans (Canada)",
  "French (Switzerland)": "Frans (Zwitserland)",
  "Irish": "Iers",
  "Galician": "Galicisch",
  "Greek (Ancient)": "Oudgrieks",
  "Hausa": "Hausa",
  "Hebrew": "Hebreeuws",
  "Hebrew (Israel)": "Hebreeuws (Israël)",
  "Hindi": "Hindi",
  "Croatian": "Kroatisch",
  "Croatian (Croatia)": "Kroatisch (Kroatië)",
  "Haitian Creole": "Haïtiaans Creools",
  "Hungarian": "Hongaars",
  "Hungarian (Hungary)": "Hongaars (Hongarije)",
  "Armenian": "Armeens",
  "Indonesian": "Indonesisch",
  "Igbo": "Igbo",
  "Icelandic": "IJslands",
  "Italian": "Italiaans",
  "Italian (Italy)": "Italiaans (Italië)",
  "Inuktitut": "Inuktitut",
  "Japanese": "Japans",
  "Japanese (Japan)": "Japans (Japan)",
  "Georgian": "Georgisch",
  "Kabyle": "Kabylisch",
  "Kazakh": "Kazachs",
  "Khmer": "Khmer",
  "Kannada": "Kannada",
  "Korean": "Koreaans",
  "Korean (Korea)": "Koreaans (Korea)",
  "Latin": "Latijn",
  "Lakota": "Lakota",
  "Lao": "Laotiaans",
  "Lithuanian": "Litouws",
  "Latvian": "Lets",
  "Māori": "Maori",
  "Mongolian": "Mongools",
  "Marathi": "Marathi",
  "Malay": "Maleis",
  "Maltese": "Maltees",
  "Burmese": "Birmaans",
  "Norwegian (Bokmål)": "Noors (Bokmål)",
  "Norwegian (Bokmål, Norway)": "Noors (Bokmål, Noorwegen)",
  "Nepali": "Nepalees",
  "Dutch": "Nederlands",
  "Flemish": "Vlaams",
  "Norwegian (Nynorsk)": "Noors (Nynorsk)",
  "Navajo": "Navajo",
  "Turkish (Ottoman)": "Ottomaans-Turks",
  "Punjabi": "Punjabi",
  "Persian (Old)": "Oudperzisch",
  "Polish": "Pools",
  "Pashto": "Pasjtoe",
  "Portuguese": "Portugees",
  "Portuguese (Brazil)": "Portugees (Brazilië)",
  "Portuguese (Portugal)": "Portugees (Portugal)",
  "Quechua": "Quechua",
  "Romanian": "Roemeens",
  "Russian": "Russisch",
  "Kinyarwanda": "Kinyarwanda",
  "Sanskrit": "Sanskriet",
  "Sami (Northern)": "Noord-Samisch",
  "Sinhala": "Singalees",
  "Slovak": "Slowaaks",
  "Slovak (Slovakia)": "Slowaaks (Slowakije)",
  "Slovenian": "Sloveens",
  "Slovenian (Slovenia)": "Sloveens (Slovenië)",
  "Sami (Southern)": "Zuid-Samisch",
  "Sami (Northern)": "Noord-Samisch",
  "Sami (Lule)": "Lule-Samisch",
  "Shona": "Shona",
  "Serbian": "Servisch",
  "Serbian (Latin)": "Servisch (Latijns)",
  "Swedish": "Zweeds",
  "Swedish (Sweden)": "Zweeds (Zweden)",
  "Swahili": "Swahili",
  "Swahili (Kenya)": "Swahili (Kenia)",
  "Swahili (Tanzania)": "Swahili (Tanzania)",
  "Syriac (Classical)": "Klassiek Syrisch",
  "Tamil": "Tamil",
  "Telugu": "Telugu",
  "Tajik": "Tadzjieks",
  "Thai": "Thai",
  "Thai (Thailand)": "Thai (Thailand)",
  "Turkmen": "Turkmeens",
  "Tagalog": "Tagalog",
  "Turkish": "Turks",
  "Turkish (Turkey)": "Turks (Turkije)",
  "Tatar": "Tataars",
  "Uyghur": "Oeigoers",
  "Ukrainian": "Oekraïens",
  "Urdu": "Urdu",
  "Uzbek": "Oezbeeks",
  "Vietnamese": "Vietnamees",
  "Wolof": "Wolof",
  "Xhosa": "Xhosa",
  "Yiddish": "Jiddisch",
  "Yoruba": "Yoruba",
  "Maya (Yucatec)": "Yucateeks Maya",
  "Chinese": "Chinees",
  "Chinese (Simplified)": "Chinees (China)",
  "Chinese (Simplified)": "Chinees (vereenvoudigd)",
  "Chinese (Traditional)": "Chinees (traditioneel)",
  "Chinese (Hong Kong)": "Chinees (Hong Kong)",
  "Chinese (Singapore)": "Chinees (Singapore)",
  "Chinese (Traditional)": "Chinees (Taiwan)",
  "Zulu": "Zoeloe",
  "Zulu": "Zoeloe (Zuid-Afrika)"
});