tinymce.addI18n('nn', {
  "-Language Not Set-": "-Språk ikkje sett-",
  "Choose from list": "Vel frå liste",
  "Choose languages": "Vel språk",
  "Choose up to six languages": "Vel opptil seks språk",
  "Configure languages": "Set opp språk",
  "Current language:": "Gjeldande språk:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Skriv inn ein gyldig språkkode utan mellomrom. Eller trykk avbryt.",
  "Enter manually": "Skriv inn manuelt",
  "Enter new lang code (e.g., \"en-US\"):": "Skriv inn ny språkkode (t.d. \"en-US\"):",
  "Indicate current language": "Vis gjeldande språk",
  "Manually enter language {{number}}:": "Skriv inn språk {{number}} manuelt:",
  "New Language:": "Nytt språk:",
  "None": "Ingen",
  "Other - Enter manually": "Anna - Skriv inn manuelt",
  "Really remove all language markup from the document?": "Vil du verkeleg fjerne all språkmerking frå dokumentet?",
  "Remove All lang markup": "Fjern all språkmerking",
  "Remove Language Markup": "Fjern språkmerking",
  "Remove current lang value": "Fjern gjeldande språkverdi",
  "Reveal lang markup": "Vis språkmerking",
  "Select language {{number}}:": "Vel språk {{number}}:",
  "Select the document's default language.": "Vel standardspråket til dokumentet.",
  "Set default document language": "Set standard dokumentspråk",
  "Set text language": "Set tekstspråk",
  "Afrikaans": "afrikaans",
  "Afrikaans": "afrikaans (Sør-Afrika)",
  "Akan": "akan",
  "Amharic": "amharisk",
  "Arabic": "arabisk",
  "Arabic (Egypt)": "arabisk (Egypt)",
  "Arabic (Morocco)": "arabisk (Marokko)",
  "Arabic (Saudi Arabia)": "arabisk (Saudi-Arabia)",
  "Azerbaijani": "aserbajdsjansk",
  "Belarusian": "belarusisk",
  "Bulgarian": "bulgarsk",
  "Bulgarian (Bulgaria)": "bulgarsk (Bulgaria)",
  "Bhojpuri": "bhojpuri",
  "Bambara": "bambara",
  "Bangla": "bengali",
  "Tibetan": "tibetansk",
  "Bosnian": "bosnisk",
  "Catalan": "katalansk",
  "Coptic": "koptisk",
  "Cree": "cree",
  "Czech": "tsjekkisk",
  "Church Slavic": "kyrkjeslavisk",
  "Welsh": "walisisk",
  "Danish": "dansk",
  "German": "tysk",
  "German (Austria)": "tysk (Austerrike)",
  "German (Switzerland)": "tysk (Sveits)",
  "German (Germany)": "tysk (Tyskland)",
  "Divehi": "divehi",
  "Greek": "gresk",
  "English": "engelsk",
  "English (Australia)": "engelsk (Australia)",
  "English (Canada)": "engelsk (Canada)",
  "English (United Kingdom)": "engelsk (Storbritannia)",
  "English (Ireland)": "engelsk (Irland)",
  "English (India)": "engelsk (India)",
  "English (Trinidad)": "engelsk (Trinidad)",
  "English (United States)": "engelsk (USA)",
  "English (South Africa)": "engelsk (Sør-Afrika)",
  "Esperanto": "esperanto",
  "Spanish": "spansk",
  "Spanish (Argentina)": "spansk (Argentina)",
  "Spanish (Chile)": "spansk (Chile)",
  "Spanish (Colombia)": "spansk (Colombia)",
  "Spanish (Costa Rica)": "spansk (Costa Rica)",
  "Spanish (Spain)": "spansk (Spania)",
  "Spanish (Mexico)": "spansk (Mexico)",
  "Spanish (Peru)": "spansk (Peru)",
  "Estonian": "estisk",
  "Basque": "baskisk",
  "Persian": "persisk",
  "Dari": "dari",
  "Persian (Iran)": "persisk (Iran)",
  "Fula": "fulfulde",
  "Finnish": "finsk",
  "Finnish (Finland)": "finsk (Finland)",
  "Filipino": "filipino",
  "French": "fransk",
  "French (Belgium)": "fransk (Belgia)",
  "French (Canada)": "fransk (Canada)",
  "French (Switzerland)": "fransk (Sveits)",
  "Irish": "irsk",
  "Galician": "galisisk",
  "Greek (Ancient)": "gammalgresk",
  "Hausa": "hausa",
  "Hebrew": "hebraisk",
  "Hebrew (Israel)": "hebraisk (Israel)",
  "Hindi": "hindi",
  "Croatian": "kroatisk",
  "Croatian (Croatia)": "kroatisk (Kroatia)",
  "Haitian Creole": "haitisk kreol",
  "Hungarian": "ungarsk",
  "Hungarian (Hungary)": "ungarsk (Ungarn)",
  "Armenian": "armensk",
  "Indonesian": "indonesisk",
  "Igbo": "ibo",
  "Icelandic": "islandsk",
  "Italian": "italiensk",
  "Italian (Italy)": "italiensk (Italia)",
  "Inuktitut": "inuktitut",
  "Japanese": "japansk",
  "Japanese (Japan)": "japansk (Japan)",
  "Georgian": "georgisk",
  "Kabyle": "kabylsk",
  "Kazakh": "kasakhisk",
  "Khmer": "khmer",
  "Kannada": "kannada",
  "Korean": "koreansk",
  "Korean (Korea)": "koreansk (Sør-Korea)",
  "Latin": "latin",
  "Lakota": "lakota",
  "Lao": "laotisk",
  "Lithuanian": "litauisk",
  "Latvian": "latvisk",
  "Māori": "maori",
  "Mongolian": "mongolsk",
  "Marathi": "marathi",
  "Malay": "malayisk",
  "Maltese": "maltesisk",
  "Burmese": "burmesisk",
  "Norwegian (Bokmål)": "norsk bokmål",
  "Norwegian (Bokmål, Norway)": "norsk bokmål (Noreg)",
  "Nepali": "nepali",
  "Dutch": "nederlandsk",
  "Flemish": "flamsk",
  "Norwegian (Nynorsk)": "norsk nynorsk",
  "Navajo": "navajo",
  "Turkish (Ottoman)": "ottomansk tyrkisk",
  "Punjabi": "panjabi",
  "Persian (Old)": "gammalpersisk",
  "Polish": "polsk",
  "Pashto": "pashto",
  "Portuguese": "portugisisk",
  "Portuguese (Brazil)": "portugisisk (Brasil)",
  "Portuguese (Portugal)": "portugisisk (Portugal)",
  "Quechua": "quechua",
  "Romanian": "rumensk",
  "Russian": "russisk",
  "Kinyarwanda": "kinyarwanda",
  "Sanskrit": "sanskrit",
  "Sami (Northern)": "nordsamisk",
  "Sinhala": "singalesisk",
  "Slovak": "slovakisk",
  "Slovak (Slovakia)": "slovakisk (Slovakia)",
  "Slovenian": "slovensk",
  "Slovenian (Slovenia)": "slovensk (Slovenia)",
  "Sami (Southern)": "sørsamisk",
  "Sami (Northern)": "nordsamisk",
  "Sami (Lule)": "lulesamisk",
  "Shona": "shona",
  "Serbian": "serbisk",
  "Serbian (Latin)": "serbisk (latin)",
  "Swedish": "svensk",
  "Swedish (Sweden)": "svensk (Sverige)",
  "Swahili": "swahili",
  "Swahili (Kenya)": "swahili (Kenya)",
  "Swahili (Tanzania)": "swahili (Tanzania)",
  "Syriac (Classical)": "klassisk syrisk",
  "Tamil": "tamil",
  "Telugu": "telugu",
  "Tajik": "tadsjikisk",
  "Thai": "thai",
  "Thai (Thailand)": "thai (Thailand)",
  "Turkmen": "turkmensk",
  "Tagalog": "tagalog",
  "Turkish": "tyrkisk",
  "Turkish (Turkey)": "tyrkisk (Tyrkia)",
  "Tatar": "tatarisk",
  "Uyghur": "uigurisk",
  "Ukrainian": "ukrainsk",
  "Urdu": "urdu",
  "Uzbek": "usbekisk",
  "Vietnamese": "vietnamesisk",
  "Wolof": "wolof",
  "Xhosa": "xhosa",
  "Yiddish": "jiddisk",
  "Yoruba": "joruba",
  "Maya (Yucatec)": "yukatekisk maya",
  "Chinese": "kinesisk",
  "Chinese (Simplified)": "kinesisk (forenkla)",
  "Chinese (Simplified)": "kinesisk (forenkla)",
  "Chinese (Traditional)": "kinesisk (tradisjonell)",
  "Chinese (Hong Kong)": "kinesisk (Hong Kong)",
  "Chinese (Singapore)": "kinesisk (Singapore)",
  "Chinese (Traditional)": "kinesisk (tradisjonell, Taiwan)",
  "Zulu": "zulu",
  "Zulu": "zulu (Sør-Afrika)"
});