tinymce.addI18n('pl', {
  "-Language Not Set-": "-Język nie ustawiony-",
  "Choose from list": "Wybierz z listy",
  "Choose languages": "Wybierz języki",
  "Choose up to six languages": "Wybierz do sześciu języków",
  "Configure languages": "Konfiguruj języki",
  "Current language:": "Bieżący język:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Wprowadź prawidłowy kod języka bez spacji. Lub naciśnij anuluj.",
  "Enter manually": "Wprowadź ręcznie",
  "Enter new lang code (e.g., \"en-US\"):": "Wprowadź nowy kod języka (np. \"en-US\"):",
  "Indicate current language": "Wskaż bieżący język",
  "Manually enter language {{number}}:": "Wprowadź ręcznie język {{number}}:",
  "New Language:": "Nowy język:",
  "None": "Brak",
  "Other - Enter manually": "Inny - Wprowadź ręcznie",
  "Really remove all language markup from the document?": "Czy na pewno usunąć wszystkie znaczniki języka z dokumentu?",
  "Remove All lang markup": "Usuń wszystkie znaczniki języka",
  "Remove Language Markup": "Usuń znaczniki języka",
  "Remove current lang value": "Usuń bieżącą wartość języka",
  "Reveal lang markup": "Pokaż znaczniki języka",
  "Select language {{number}}:": "Wybierz język {{number}}:",
  "Select the document's default language.": "Wybierz domyślny język dokumentu.",
  "Set default document language": "Ustaw domyślny język dokumentu",
  "Set text language": "Ustaw język tekstu",
  "Afrikaans": "afrikaans",
  "Afrikaans": "afrikaans (Afryka Południowa)",
  "Akan": "akan",
  "Amharic": "amharski",
  "Arabic": "arabski",
  "Arabic (Egypt)": "arabski (Egipt)",
  "Arabic (Morocco)": "arabski (Maroko)",
  "Arabic (Saudi Arabia)": "arabski (Arabia Saudyjska)",
  "Azerbaijani": "azerbejdżański",
  "Belarusian": "białoruski",
  "Bulgarian": "bułgarski",
  "Bulgarian (Bulgaria)": "bułgarski (Bułgaria)",
  "Bhojpuri": "bhodżpuri",
  "Bambara": "bambara",
  "Bangla": "bengalski",
  "Tibetan": "tybetański",
  "Bosnian": "bośniacki",
  "Catalan": "kataloński",
  "Coptic": "koptyjski",
  "Cree": "kri",
  "Czech": "czeski",
  "Church Slavic": "cerkiewnosłowiański",
  "Welsh": "walijski",
  "Danish": "duński",
  "German": "niemiecki",
  "German (Austria)": "niemiecki (Austria)",
  "German (Switzerland)": "niemiecki (Szwajcaria)",
  "German (Germany)": "niemiecki (Niemcy)",
  "Divehi": "malediwski",
  "Greek": "grecki",
  "English": "angielski",
  "English (Australia)": "angielski (Australia)",
  "English (Canada)": "angielski (Kanada)",
  "English (United Kingdom)": "angielski (Wielka Brytania)",
  "English (Ireland)": "angielski (Irlandia)",
  "English (India)": "angielski (Indie)",
  "English (Trinidad)": "angielski (Trynidad)",
  "English (United States)": "angielski (Stany Zjednoczone)",
  "English (South Africa)": "angielski (Afryka Południowa)",
  "Esperanto": "esperanto",
  "Spanish": "hiszpański",
  "Spanish (Argentina)": "hiszpański (Argentyna)",
  "Spanish (Chile)": "hiszpański (Chile)",
  "Spanish (Colombia)": "hiszpański (Kolumbia)",
  "Spanish (Costa Rica)": "hiszpański (Kostaryka)",
  "Spanish (Spain)": "hiszpański (Hiszpania)",
  "Spanish (Mexico)": "hiszpański (Meksyk)",
  "Spanish (Peru)": "hiszpański (Peru)",
  "Estonian": "estoński",
  "Basque": "baskijski",
  "Persian": "perski",
  "Dari": "dari",
  "Persian (Iran)": "perski (Iran)",
  "Fula": "fulani",
  "Finnish": "fiński",
  "Finnish (Finland)": "fiński (Finlandia)",
  "Filipino": "filipiński",
  "French": "francuski",
  "French (Belgium)": "francuski (Belgia)",
  "French (Canada)": "francuski (Kanada)",
  "French (Switzerland)": "francuski (Szwajcaria)",
  "Irish": "irlandzki",
  "Galician": "galicyjski",
  "Greek (Ancient)": "grecki (starożytny)",
  "Hausa": "hausa",
  "Hebrew": "hebrajski",
  "Hebrew (Israel)": "hebrajski (Izrael)",
  "Hindi": "hindi",
  "Croatian": "chorwacki",
  "Croatian (Croatia)": "chorwacki (Chorwacja)",
  "Haitian Creole": "kreolski haitański",
  "Hungarian": "węgierski",
  "Hungarian (Hungary)": "węgierski (Węgry)",
  "Armenian": "ormiański",
  "Indonesian": "indonezyjski",
  "Igbo": "igbo",
  "Icelandic": "islandzki",
  "Italian": "włoski",
  "Italian (Italy)": "włoski (Włochy)",
  "Inuktitut": "inuktitut",
  "Japanese": "japoński",
  "Japanese (Japan)": "japoński (Japonia)",
  "Georgian": "gruziński",
  "Kabyle": "kabylski",
  "Kazakh": "kazachski",
  "Khmer": "khmerski",
  "Kannada": "kannada",
  "Korean": "koreański",
  "Korean (Korea)": "koreański (Korea)",
  "Latin": "łaciński",
  "Lakota": "lakota",
  "Lao": "laotański",
  "Lithuanian": "litewski",
  "Latvian": "łotewski",
  "Māori": "maoryjski",
  "Mongolian": "mongolski",
  "Marathi": "marathi",
  "Malay": "malajski",
  "Maltese": "maltański",
  "Burmese": "birmański",
  "Norwegian (Bokmål)": "norweski (bokmål)",
  "Norwegian (Bokmål, Norway)": "norweski (bokmål, Norwegia)",
  "Nepali": "nepalski",
  "Dutch": "niderlandzki",
  "Flemish": "flamandzki",
  "Norwegian (Nynorsk)": "norweski (nynorsk)",
  "Navajo": "nawaho",
  "Turkish (Ottoman)": "turecki (osmański)",
  "Punjabi": "pendżabski",
  "Persian (Old)": "perski (starożytny)",
  "Polish": "polski",
  "Pashto": "paszto",
  "Portuguese": "portugalski",
  "Portuguese (Brazil)": "portugalski (Brazylia)",
  "Portuguese (Portugal)": "portugalski (Portugalia)",
  "Quechua": "keczua",
  "Romanian": "rumuński",
  "Russian": "rosyjski",
  "Kinyarwanda": "kinya-ruanda",
  "Sanskrit": "sanskryt",
  "Sami (Northern)": "lapoński (północny)",
  "Sinhala": "syngaleski",
  "Slovak": "słowacki",
  "Slovak (Slovakia)": "słowacki (Słowacja)",
  "Slovenian": "słoweński",
  "Slovenian (Slovenia)": "słoweński (Słowenia)",
  "Sami (Southern)": "lapoński (południowy)",
  "Sami (Northern)": "lapoński (północny)",
  "Sami (Lule)": "lapoński (lule)",
  "Shona": "shona",
  "Serbian": "serbski",
  "Serbian (Latin)": "serbski (łaciński)",
  "Swedish": "szwedzki",
  "Swedish (Sweden)": "szwedzki (Szwecja)",
  "Swahili": "suahili",
  "Swahili (Kenya)": "suahili (Kenia)",
  "Swahili (Tanzania)": "suahili (Tanzania)",
  "Syriac (Classical)": "syriacki (klasyczny)",
  "Tamil": "tamilski",
  "Telugu": "telugu",
  "Tajik": "tadżycki",
  "Thai": "tajski",
  "Thai (Thailand)": "tajski (Tajlandia)",
  "Turkmen": "turkmeński",
  "Tagalog": "tagalski",
  "Turkish": "turecki",
  "Turkish (Turkey)": "turecki (Turcja)",
  "Tatar": "tatarski",
  "Uyghur": "ujgurski",
  "Ukrainian": "ukraiński",
  "Urdu": "urdu",
  "Uzbek": "uzbecki",
  "Vietnamese": "wietnamski",
  "Wolof": "wolof",
  "Xhosa": "khosa",
  "Yiddish": "jidysz",
  "Yoruba": "joruba",
  "Maya (Yucatec)": "maja (jukateński)",
  "Chinese": "chiński",
  "Chinese (Simplified)": "chiński (uproszczony)",
  "Chinese (Simplified)": "chiński (uproszczony)",
  "Chinese (Traditional)": "chiński (tradycyjny)",
  "Chinese (Hong Kong)": "chiński (Hongkong)",
  "Chinese (Singapore)": "chiński (Singapur)",
  "Chinese (Traditional)": "chiński (Tajwan)",
  "Zulu": "zulu",
  "Zulu": "zulu (Afryka Południowa)"
});