tinymce.addI18n('pt_PT', {
  "-Language Not Set-": "-Idioma Não Definido-",
  "Choose from list": "Escolher da lista",
  "Choose languages": "Escolher idiomas",
  "Choose up to six languages": "Escolha até seis idiomas",
  "Configure languages": "Configurar idiomas",
  "Current language:": "Idioma actual:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Introduza um código de idioma válido sem espaços. Ou prima cancelar.",
  "Enter manually": "Introduzir manualmente",
  "Enter new lang code (e.g., \"en-US\"):": "Introduza o novo código de idioma (ex. \"pt-PT\"):",
  "Indicate current language": "Indicar idioma actual",
  "Manually enter language {{number}}:": "Introduzir manualmente o idioma {{number}}:",
  "New Language:": "Novo Idioma:",
  "None": "Nenhum",
  "Other - Enter manually": "Outro - Introduzir manualmente",
  "Really remove all language markup from the document?": "Deseja realmente remover toda a marcação de idioma do documento?",
  "Remove All lang markup": "Remover toda a marcação de idioma",
  "Remove Language Markup": "Remover Marcação de Idioma",
  "Remove current lang value": "Remover valor do idioma actual",
  "Reveal lang markup": "Revelar marcação de idioma",
  "Select language {{number}}:": "Seleccionar idioma {{number}}:",
  "Select the document's default language.": "Seleccione o idioma predefinido do documento.",
  "Set default document language": "Definir idioma predefinido do documento",
  "Set text language": "Definir idioma do texto",
  "Afrikaans": "africanês",
  "Afrikaans": "africanês (África do Sul)",
  "Akan": "akan",
  "Amharic": "amárico",
  "Arabic": "árabe",
  "Arabic (Egypt)": "árabe (Egipto)",
  "Arabic (Morocco)": "árabe (Marrocos)",
  "Arabic (Saudi Arabia)": "árabe (Arábia Saudita)",
  "Azerbaijani": "azerbaijano",
  "Belarusian": "bielorrusso",
  "Bulgarian": "búlgaro",
  "Bulgarian (Bulgaria)": "búlgaro (Bulgária)",
  "Bhojpuri": "bhojpuri",
  "Bambara": "bambara",
  "Bangla": "bengalês",
  "Tibetan": "tibetano",
  "Bosnian": "bósnio",
  "Catalan": "catalão",
  "Coptic": "copta",
  "Cree": "cree",
  "Czech": "checo",
  "Church Slavic": "eslavo eclesiástico",
  "Welsh": "galês",
  "Danish": "dinamarquês",
  "German": "alemão",
  "German (Austria)": "alemão (Áustria)",
  "German (Switzerland)": "alemão (Suíça)",
  "German (Germany)": "alemão (Alemanha)",
  "Divehi": "divehi",
  "Greek": "grego",
  "English": "inglês",
  "English (Australia)": "inglês (Austrália)",
  "English (Canada)": "inglês (Canadá)",
  "English (United Kingdom)": "inglês (Reino Unido)",
  "English (Ireland)": "inglês (Irlanda)",
  "English (India)": "inglês (Índia)",
  "English (Trinidad)": "inglês (Trindade)",
  "English (United States)": "inglês (Estados Unidos)",
  "English (South Africa)": "inglês (África do Sul)",
  "Esperanto": "esperanto",
  "Spanish": "espanhol",
  "Spanish (Argentina)": "espanhol (Argentina)",
  "Spanish (Chile)": "espanhol (Chile)",
  "Spanish (Colombia)": "espanhol (Colômbia)",
  "Spanish (Costa Rica)": "espanhol (Costa Rica)",
  "Spanish (Spain)": "espanhol (Espanha)",
  "Spanish (Mexico)": "espanhol (México)",
  "Spanish (Peru)": "espanhol (Peru)",
  "Estonian": "estónio",
  "Basque": "basco",
  "Persian": "persa",
  "Dari": "dari",
  "Persian (Iran)": "persa (Irão)",
  "Fula": "fula",
  "Finnish": "finlandês",
  "Finnish (Finland)": "finlandês (Finlândia)",
  "Filipino": "filipino",
  "French": "francês",
  "French (Belgium)": "francês (Bélgica)",
  "French (Canada)": "francês (Canadá)",
  "French (Switzerland)": "francês (Suíça)",
  "Irish": "irlandês",
  "Galician": "galego",
  "Greek (Ancient)": "grego (clássico)",
  "Hausa": "haúça",
  "Hebrew": "hebraico",
  "Hebrew (Israel)": "hebraico (Israel)",
  "Hindi": "hindi",
  "Croatian": "croata",
  "Croatian (Croatia)": "croata (Croácia)",
  "Haitian Creole": "crioulo haitiano",
  "Hungarian": "húngaro",
  "Hungarian (Hungary)": "húngaro (Hungria)",
  "Armenian": "arménio",
  "Indonesian": "indonésio",
  "Igbo": "igbo",
  "Icelandic": "islandês",
  "Italian": "italiano",
  "Italian (Italy)": "italiano (Itália)",
  "Inuktitut": "inuktitut",
  "Japanese": "japonês",
  "Japanese (Japan)": "japonês (Japão)",
  "Georgian": "georgiano",
  "Kabyle": "kabyle",
  "Kazakh": "cazaque",
  "Khmer": "khmer",
  "Kannada": "canarim",
  "Korean": "coreano",
  "Korean (Korea)": "coreano (Coreia do Sul)",
  "Latin": "latim",
  "Lakota": "lacota",
  "Lao": "laosiano",
  "Lithuanian": "lituano",
  "Latvian": "letão",
  "Māori": "maori",
  "Mongolian": "mongol",
  "Marathi": "marata",
  "Malay": "malaio",
  "Maltese": "maltês",
  "Burmese": "birmanês",
  "Norwegian (Bokmål)": "norueguês (bokmål)",
  "Norwegian (Bokmål, Norway)": "norueguês (bokmål, Noruega)",
  "Nepali": "nepalês",
  "Dutch": "neerlandês",
  "Flemish": "neerlandês (Bélgica)",
  "Norwegian (Nynorsk)": "norueguês (nynorsk)",
  "Navajo": "navajo",
  "Turkish (Ottoman)": "turco (otomano)",
  "Punjabi": "panjabi",
  "Persian (Old)": "persa (antigo)",
  "Polish": "polaco",
  "Pashto": "pastó",
  "Portuguese": "português",
  "Portuguese (Brazil)": "português (Brasil)",
  "Portuguese (Portugal)": "português (Portugal)",
  "Quechua": "quíchua",
  "Romanian": "romeno",
  "Russian": "russo",
  "Kinyarwanda": "quiniaruanda",
  "Sanskrit": "sânscrito",
  "Sami (Northern)": "sami (setentrional)",
  "Sinhala": "cingalês",
  "Slovak": "eslovaco",
  "Slovak (Slovakia)": "eslovaco (Eslováquia)",
  "Slovenian": "esloveno",
  "Slovenian (Slovenia)": "esloveno (Eslovénia)",
  "Sami (Southern)": "sami (meridional)",
  "Sami (Northern)": "sami (setentrional)",
  "Sami (Lule)": "sami (lule)",
  "Shona": "shona",
  "Serbian": "sérvio",
  "Serbian (Latin)": "sérvio (latim)",
  "Swedish": "sueco",
  "Swedish (Sweden)": "sueco (Suécia)",
  "Swahili": "suaíli",
  "Swahili (Kenya)": "suaíli (Quénia)",
  "Swahili (Tanzania)": "suaíli (Tanzânia)",
  "Syriac (Classical)": "siríaco (clássico)",
  "Tamil": "tâmil",
  "Telugu": "telugu",
  "Tajik": "tajique",
  "Thai": "tailandês",
  "Thai (Thailand)": "tailandês (Tailândia)",
  "Turkmen": "turcomano",
  "Tagalog": "tagalo",
  "Turkish": "turco",
  "Turkish (Turkey)": "turco (Turquia)",
  "Tatar": "tatar",
  "Uyghur": "uigur",
  "Ukrainian": "ucraniano",
  "Urdu": "urdu",
  "Uzbek": "usbeque",
  "Vietnamese": "vietnamita",
  "Wolof": "uólofe",
  "Xhosa": "xosa",
  "Yiddish": "iídiche",
  "Yoruba": "ioruba",
  "Maya (Yucatec)": "maia (iucateco)",
  "Chinese": "chinês",
  "Chinese (Simplified)": "chinês (simplificado)",
  "Chinese (Simplified)": "chinês (simplificado)",
  "Chinese (Traditional)": "chinês (tradicional)",
  "Chinese (Hong Kong)": "chinês (Hong Kong)",
  "Chinese (Singapore)": "chinês (Singapura)",
  "Chinese (Traditional)": "chinês (tradicional, Taiwan)",
  "Zulu": "zulu",
  "Zulu": "zulu (África do Sul)"
});