tinymce.addI18n('ro', {
  "-Language Not Set-": "-Limba nu este setată-",
  "Choose from list": "Alege din listă",
  "Choose languages": "Alege limbile",
  "Choose up to six languages": "Alege până la șase limbi",
  "Configure languages": "Configurează limbile",
  "Current language:": "Limba curentă:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Introdu un cod de limbă valid fără spații. Sau apasă anulează.",
  "Enter manually": "Introdu manual",
  "Enter new lang code (e.g., \"en-US\"):": "Introdu codul noii limbi (ex. \"ro-RO\"):",
  "Indicate current language": "Indică limba curentă",
  "Manually enter language {{number}}:": "Introdu manual limba {{number}}:",
  "New Language:": "Limbă nouă:",
  "None": "Niciuna",
  "Other - Enter manually": "Altă limbă - Introdu manual",
  "Really remove all language markup from the document?": "Chiar vrei să elimini tot marcajul de limbă din document?",
  "Remove All lang markup": "Elimină tot marcajul de limbă",
  "Remove Language Markup": "Elimină marcajul de limbă",
  "Remove current lang value": "Elimină valoarea limbii curente",
  "Reveal lang markup": "Afișează marcajul de limbă",
  "Select language {{number}}:": "Selectează limba {{number}}:",
  "Select the document's default language.": "Selectează limba implicită a documentului.",
  "Set default document language": "Setează limba implicită a documentului",
  "Set text language": "Setează limba textului",
  "Afrikaans": "afrikaans",
  "Afrikaans": "afrikaans (Africa de Sud)",
  "Akan": "akan",
  "Amharic": "amharică",
  "Arabic": "arabă",
  "Arabic (Egypt)": "arabă (Egipt)",
  "Arabic (Morocco)": "arabă (Maroc)",
  "Arabic (Saudi Arabia)": "arabă (Arabia Saudită)",
  "Azerbaijani": "azeră",
  "Belarusian": "belarusă",
  "Bulgarian": "bulgară",
  "Bulgarian (Bulgaria)": "bulgară (Bulgaria)",
  "Bhojpuri": "bhojpuri",
  "Bambara": "bambara",
  "Bangla": "bengaleză",
  "Tibetan": "tibetană",
  "Bosnian": "bosniacă",
  "Catalan": "catalană",
  "Coptic": "coptă",
  "Cree": "cree",
  "Czech": "cehă",
  "Church Slavic": "slavonă",
  "Welsh": "galeză",
  "Danish": "daneză",
  "German": "germană",
  "German (Austria)": "germană (Austria)",
  "German (Switzerland)": "germană (Elveția)",
  "German (Germany)": "germană (Germania)",
  "Divehi": "divehi",
  "Greek": "greacă",
  "English": "engleză",
  "English (Australia)": "engleză (Australia)",
  "English (Canada)": "engleză (Canada)",
  "English (United Kingdom)": "engleză (Regatul Unit)",
  "English (Ireland)": "engleză (Irlanda)",
  "English (India)": "engleză (India)",
  "English (Trinidad)": "engleză (Trinidad)",
  "English (United States)": "engleză (Statele Unite)",
  "English (South Africa)": "engleză (Africa de Sud)",
  "Esperanto": "esperanto",
  "Spanish": "spaniolă",
  "Spanish (Argentina)": "spaniolă (Argentina)",
  "Spanish (Chile)": "spaniolă (Chile)",
  "Spanish (Colombia)": "spaniolă (Columbia)",
  "Spanish (Costa Rica)": "spaniolă (Costa Rica)",
  "Spanish (Spain)": "spaniolă (Spania)",
  "Spanish (Mexico)": "spaniolă (Mexic)",
  "Spanish (Peru)": "spaniolă (Peru)",
  "Estonian": "estonă",
  "Basque": "bască",
  "Persian": "persană",
  "Dari": "dari",
  "Persian (Iran)": "persană (Iran)",
  "Fula": "fulah",
  "Finnish": "finlandeză",
  "Finnish (Finland)": "finlandeză (Finlanda)",
  "Filipino": "filipineză",
  "French": "franceză",
  "French (Belgium)": "franceză (Belgia)",
  "French (Canada)": "franceză (Canada)",
  "French (Switzerland)": "franceză (Elveția)",
  "Irish": "irlandeză",
  "Galician": "galiciană",
  "Greek (Ancient)": "greacă (veche)",
  "Hausa": "hausa",
  "Hebrew": "ebraică",
  "Hebrew (Israel)": "ebraică (Israel)",
  "Hindi": "hindi",
  "Croatian": "croată",
  "Croatian (Croatia)": "croată (Croația)",
  "Haitian Creole": "haitiană",
  "Hungarian": "maghiară",
  "Hungarian (Hungary)": "maghiară (Ungaria)",
  "Armenian": "armeană",
  "Indonesian": "indoneziană",
  "Igbo": "igbo",
  "Icelandic": "islandeză",
  "Italian": "italiană",
  "Italian (Italy)": "italiană (Italia)",
  "Inuktitut": "inuktitut",
  "Japanese": "japoneză",
  "Japanese (Japan)": "japoneză (Japonia)",
  "Georgian": "georgiană",
  "Kabyle": "kabyle",
  "Kazakh": "kazahă",
  "Khmer": "khmeră",
  "Kannada": "kannada",
  "Korean": "coreeană",
  "Korean (Korea)": "coreeană (Coreea de Sud)",
  "Latin": "latină",
  "Lakota": "lakota",
  "Lao": "laoțiană",
  "Lithuanian": "lituaniană",
  "Latvian": "letonă",
  "Māori": "maori",
  "Mongolian": "mongolă",
  "Marathi": "marathi",
  "Malay": "malaeză",
  "Maltese": "malteză",
  "Burmese": "birmană",
  "Norwegian (Bokmål)": "norvegiană (bokmål)",
  "Norwegian (Bokmål, Norway)": "norvegiană bokmål (Norvegia)",
  "Nepali": "nepaleză",
  "Dutch": "neerlandeză",
  "Flemish": "flamandă",
  "Norwegian (Nynorsk)": "norvegiană (nynorsk)",
  "Navajo": "navajo",
  "Turkish (Ottoman)": "turcă (otomană)",
  "Punjabi": "punjabi",
  "Persian (Old)": "persană (veche)",
  "Polish": "poloneză",
  "Pashto": "paștună",
  "Portuguese": "portugheză",
  "Portuguese (Brazil)": "portugheză (Brazilia)",
  "Portuguese (Portugal)": "portugheză (Portugalia)",
  "Quechua": "quechua",
  "Romanian": "română",
  "Russian": "rusă",
  "Kinyarwanda": "kinyarwanda",
  "Sanskrit": "sanscrită",
  "Sami (Northern)": "sami (nord)",
  "Sinhala": "singhaleză",
  "Slovak": "slovacă",
  "Slovak (Slovakia)": "slovacă (Slovacia)",
  "Slovenian": "slovenă",
  "Slovenian (Slovenia)": "slovenă (Slovenia)",
  "Sami (Southern)": "sami (sud)",
  "Sami (Northern)": "sami (nord)",
  "Sami (Lule)": "sami (lule)",
  "Shona": "shona",
  "Serbian": "sârbă",
  "Serbian (Latin)": "sârbă (latină)",
  "Swedish": "suedeză",
  "Swedish (Sweden)": "suedeză (Suedia)",
  "Swahili": "swahili",
  "Swahili (Kenya)": "swahili (Kenya)",
  "Swahili (Tanzania)": "swahili (Tanzania)",
  "Syriac (Classical)": "siriacă (clasică)",
  "Tamil": "tamilă",
  "Telugu": "telugu",
  "Tajik": "tadjică",
  "Thai": "thailandeză",
  "Thai (Thailand)": "thailandeză (Thailanda)",
  "Turkmen": "turkmenă",
  "Tagalog": "tagalog",
  "Turkish": "turcă",
  "Turkish (Turkey)": "turcă (Turcia)",
  "Tatar": "tătară",
  "Uyghur": "uigură",
  "Ukrainian": "ucraineană",
  "Urdu": "urdu",
  "Uzbek": "uzbecă",
  "Vietnamese": "vietnameză",
  "Wolof": "wolof",
  "Xhosa": "xhosa",
  "Yiddish": "idiș",
  "Yoruba": "yoruba",
  "Maya (Yucatec)": "maya (yucatecă)",
  "Chinese": "chineză",
  "Chinese (Simplified)": "chineză (simplificată)",
  "Chinese (Simplified)": "chineză (simplificată)",
  "Chinese (Traditional)": "chineză (tradițională)",
  "Chinese (Hong Kong)": "chineză (Hong Kong)",
  "Chinese (Singapore)": "chineză (Singapore)",
  "Chinese (Traditional)": "chineză (tradițională)",
  "Zulu": "zulu",
  "Zulu": "zulu (Africa de Sud)"
});