tinymce.addI18n('ru', {
  "-Language Not Set-": "-Язык не установлен-",
  "Choose from list": "Выбрать из списка",
  "Choose languages": "Выбрать языки",
  "Choose up to six languages": "Выберите до шести языков",
  "Configure languages": "Настроить языки",
  "Current language:": "Текущий язык:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Введите правильный код языка без пробелов. Или нажмите отмену.",
  "Enter manually": "Ввести вручную",
  "Enter new lang code (e.g., \"en-US\"):": "Введите новый код языка (напр. \"ru-RU\"):",
  "Indicate current language": "Указать текущий язык",
  "Manually enter language {{number}}:": "Ввести язык {{number}} вручную:",
  "New Language:": "Новый язык:",
  "None": "Нет",
  "Other - Enter manually": "Другой - Ввести вручную",
  "Really remove all language markup from the document?": "Действительно удалить всю языковую разметку из документа?",
  "Remove All lang markup": "Удалить всю языковую разметку",
  "Remove Language Markup": "Удалить языковую разметку",
  "Remove current lang value": "Удалить текущее значение языка",
  "Reveal lang markup": "Показать языковую разметку",
  "Select language {{number}}:": "Выбрать язык {{number}}:",
  "Select the document's default language.": "Выберите язык документа по умолчанию.",
  "Set default document language": "Установить язык документа по умолчанию",
  "Set text language": "Установить язык текста",
  "Afrikaans": "африкаанс",
  "Afrikaans": "африкаанс (ЮАР)",
  "Akan": "акан",
  "Amharic": "амхарский",
  "Arabic": "арабский",
  "Arabic (Egypt)": "арабский (Египет)",
  "Arabic (Morocco)": "арабский (Марокко)",
  "Arabic (Saudi Arabia)": "арабский (Саудовская Аравия)",
  "Azerbaijani": "азербайджанский",
  "Belarusian": "белорусский",
  "Bulgarian": "болгарский",
  "Bulgarian (Bulgaria)": "болгарский (Болгария)",
  "Bhojpuri": "бходжпури",
  "Bambara": "бамбара",
  "Bangla": "бенгальский",
  "Tibetan": "тибетский",
  "Bosnian": "боснийский",
  "Catalan": "каталанский",
  "Coptic": "коптский",
  "Cree": "кри",
  "Czech": "чешский",
  "Church Slavic": "церковнославянский",
  "Welsh": "валлийский",
  "Danish": "датский",
  "German": "немецкий",
  "German (Austria)": "немецкий (Австрия)",
  "German (Switzerland)": "немецкий (Швейцария)",
  "German (Germany)": "немецкий (Германия)",
  "Divehi": "мальдивский",
  "Greek": "греческий",
  "English": "английский",
  "English (Australia)": "английский (Австралия)",
  "English (Canada)": "английский (Канада)",
  "English (United Kingdom)": "английский (Великобритания)",
  "English (Ireland)": "английский (Ирландия)",
  "English (India)": "английский (Индия)",
  "English (Trinidad)": "английский (Тринидад)",
  "English (United States)": "английский (США)",
  "English (South Africa)": "английский (ЮАР)",
  "Esperanto": "эсперанто",
  "Spanish": "испанский",
  "Spanish (Argentina)": "испанский (Аргентина)",
  "Spanish (Chile)": "испанский (Чили)",
  "Spanish (Colombia)": "испанский (Колумбия)",
  "Spanish (Costa Rica)": "испанский (Коста-Рика)",
  "Spanish (Spain)": "испанский (Испания)",
  "Spanish (Mexico)": "испанский (Мексика)",
  "Spanish (Peru)": "испанский (Перу)",
  "Estonian": "эстонский",
  "Basque": "баскский",
  "Persian": "персидский",
  "Dari": "дари",
  "Persian (Iran)": "персидский (Иран)",
  "Fula": "фулах",
  "Finnish": "финский",
  "Finnish (Finland)": "финский (Финляндия)",
  "Filipino": "филиппинский",
  "French": "французский",
  "French (Belgium)": "французский (Бельгия)",
  "French (Canada)": "французский (Канада)",
  "French (Switzerland)": "французский (Швейцария)",
  "Irish": "ирландский",
  "Galician": "галисийский",
  "Greek (Ancient)": "древнегреческий",
  "Hausa": "хауса",
  "Hebrew": "иврит",
  "Hebrew (Israel)": "иврит (Израиль)",
  "Hindi": "хинди",
  "Croatian": "хорватский",
  "Croatian (Croatia)": "хорватский (Хорватия)",
  "Haitian Creole": "гаитянский креольский",
  "Hungarian": "венгерский",
  "Hungarian (Hungary)": "венгерский (Венгрия)",
  "Armenian": "армянский",
  "Indonesian": "индонезийский",
  "Igbo": "игбо",
  "Icelandic": "исландский",
  "Italian": "итальянский",
  "Italian (Italy)": "итальянский (Италия)",
  "Inuktitut": "инуктитут",
  "Japanese": "японский",
  "Japanese (Japan)": "японский (Япония)",
  "Georgian": "грузинский",
  "Kabyle": "кабильский",
  "Kazakh": "казахский",
  "Khmer": "кхмерский",
  "Kannada": "каннада",
  "Korean": "корейский",
  "Korean (Korea)": "корейский (Корея)",
  "Latin": "латинский",
  "Lakota": "лакота",
  "Lao": "лаосский",
  "Lithuanian": "литовский",
  "Latvian": "латышский",
  "Māori": "маори",
  "Mongolian": "монгольский",
  "Marathi": "маратхи",
  "Malay": "малайский",
  "Maltese": "мальтийский",
  "Burmese": "бирманский",
  "Norwegian (Bokmål)": "норвежский (букмол)",
  "Norwegian (Bokmål, Norway)": "норвежский (букмол, Норвегия)",
  "Nepali": "непальский",
  "Dutch": "нидерландский",
  "Flemish": "фламандский",
  "Norwegian (Nynorsk)": "норвежский (нюнорск)",
  "Navajo": "навахо",
  "Turkish (Ottoman)": "турецкий (османский)",
  "Punjabi": "панджаби",
  "Persian (Old)": "древнеперсидский",
  "Polish": "польский",
  "Pashto": "пушту",
  "Portuguese": "португальский",
  "Portuguese (Brazil)": "португальский (Бразилия)",
  "Portuguese (Portugal)": "португальский (Португалия)",
  "Quechua": "кечуа",
  "Romanian": "румынский",
  "Russian": "русский",
  "Kinyarwanda": "киньяруанда",
  "Sanskrit": "санскрит",
  "Sami (Northern)": "саамский (северный)",
  "Sinhala": "сингальский",
  "Slovak": "словацкий",
  "Slovak (Slovakia)": "словацкий (Словакия)",
  "Slovenian": "словенский",
  "Slovenian (Slovenia)": "словенский (Словения)",
  "Sami (Southern)": "саамский (южный)",
  "Sami (Northern)": "саамский (северный)",
  "Sami (Lule)": "саамский (луле)",
  "Shona": "шона",
  "Serbian": "сербский",
  "Serbian (Latin)": "сербский (латиница)",
  "Swedish": "шведский",
  "Swedish (Sweden)": "шведский (Швеция)",
  "Swahili": "суахили",
  "Swahili (Kenya)": "суахили (Кения)",
  "Swahili (Tanzania)": "суахили (Танзания)",
  "Syriac (Classical)": "сирийский (классический)",
  "Tamil": "тамильский",
  "Telugu": "телугу",
  "Tajik": "таджикский",
  "Thai": "тайский",
  "Thai (Thailand)": "тайский (Таиланд)",
  "Turkmen": "туркменский",
  "Tagalog": "тагалог",
  "Turkish": "турецкий",
  "Turkish (Turkey)": "турецкий (Турция)",
  "Tatar": "татарский",
  "Uyghur": "уйгурский",
  "Ukrainian": "украинский",
  "Urdu": "урду",
  "Uzbek": "узбекский",
  "Vietnamese": "вьетнамский",
  "Wolof": "волоф",
  "Xhosa": "коса",
  "Yiddish": "идиш",
  "Yoruba": "йоруба",
  "Maya (Yucatec)": "майя (юкатекский)",
  "Chinese": "китайский",
  "Chinese (Simplified)": "китайский (упрощенный)",
  "Chinese (Simplified)": "китайский (упрощенный)",
  "Chinese (Traditional)": "китайский (традиционный)",
  "Chinese (Hong Kong)": "китайский (Гонконг)",
  "Chinese (Singapore)": "китайский (Сингапур)",
  "Chinese (Traditional)": "китайский (традиционный)",
  "Zulu": "зулу",
  "Zulu": "зулу (ЮАР)"
});