tinymce.addI18n('sv', {
  "-Language Not Set-": "-Språk inte angivet-",
  "Choose from list": "Välj från lista",
  "Choose languages": "Välj språk",
  "Choose up to six languages": "Välj upp till sex språk",
  "Configure languages": "Konfigurera språk",
  "Current language:": "Aktuellt språk:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Ange en giltig språkkod utan mellanslag. Eller tryck avbryt.",
  "Enter manually": "Ange manuellt",
  "Enter new lang code (e.g., \"en-US\"):": "Ange ny språkkod (t.ex. \"sv-SE\"):",
  "Indicate current language": "Ange aktuellt språk",
  "Manually enter language {{number}}:": "Ange språk {{number}} manuellt:",
  "New Language:": "Nytt språk:",
  "None": "Ingen",
  "Other - Enter manually": "Annat - Ange manuellt",
  "Really remove all language markup from the document?": "Vill du verkligen ta bort all språkmarkering från dokumentet?",
  "Remove All lang markup": "Ta bort all språkmarkering",
  "Remove Language Markup": "Ta bort språkmarkering",
  "Remove current lang value": "Ta bort aktuellt språkvärde",
  "Reveal lang markup": "Visa språkmarkering",
  "Select language {{number}}:": "Välj språk {{number}}:",
  "Select the document's default language.": "Välj dokumentets standardspråk.",
  "Set default document language": "Ange standardspråk för dokument",
  "Set text language": "Ange textspråk",
  "Afrikaans": "afrikaans",
  "Afrikaans": "afrikaans (Sydafrika)",
  "Akan": "akan",
  "Amharic": "amhariska",
  "Arabic": "arabiska",
  "Arabic (Egypt)": "arabiska (Egypten)",
  "Arabic (Morocco)": "arabiska (Marocko)",
  "Arabic (Saudi Arabia)": "arabiska (Saudiarabien)",
  "Azerbaijani": "azerbajdzjanska",
  "Belarusian": "belarusiska",
  "Bulgarian": "bulgariska",
  "Bulgarian (Bulgaria)": "bulgariska (Bulgarien)",
  "Bhojpuri": "bhojpuri",
  "Bambara": "bambara",
  "Bangla": "bengali",
  "Tibetan": "tibetanska",
  "Bosnian": "bosniska",
  "Catalan": "katalanska",
  "Coptic": "koptiska",
  "Cree": "cree",
  "Czech": "tjeckiska",
  "Church Slavic": "kyrkslaviska",
  "Welsh": "walesiska",
  "Danish": "danska",
  "German": "tyska",
  "German (Austria)": "tyska (Österrike)",
  "German (Switzerland)": "tyska (Schweiz)",
  "German (Germany)": "tyska (Tyskland)",
  "Divehi": "divehi",
  "Greek": "grekiska",
  "English": "engelska",
  "English (Australia)": "engelska (Australien)",
  "English (Canada)": "engelska (Kanada)",
  "English (United Kingdom)": "engelska (Storbritannien)",
  "English (Ireland)": "engelska (Irland)",
  "English (India)": "engelska (Indien)",
  "English (Trinidad)": "engelska (Trinidad)",
  "English (United States)": "engelska (USA)",
  "English (South Africa)": "engelska (Sydafrika)",
  "Esperanto": "esperanto",
  "Spanish": "spanska",
  "Spanish (Argentina)": "spanska (Argentina)",
  "Spanish (Chile)": "spanska (Chile)",
  "Spanish (Colombia)": "spanska (Colombia)",
  "Spanish (Costa Rica)": "spanska (Costa Rica)",
  "Spanish (Spain)": "spanska (Spanien)",
  "Spanish (Mexico)": "spanska (Mexiko)",
  "Spanish (Peru)": "spanska (Peru)",
  "Estonian": "estniska",
  "Basque": "baskiska",
  "Persian": "persiska",
  "Dari": "dari",
  "Persian (Iran)": "persiska (Iran)",
  "Fula": "fulani",
  "Finnish": "finska",
  "Finnish (Finland)": "finska (Finland)",
  "Filipino": "filippinska",
  "French": "franska",
  "French (Belgium)": "franska (Belgien)",
  "French (Canada)": "franska (Kanada)",
  "French (Switzerland)": "franska (Schweiz)",
  "Irish": "iriska",
  "Galician": "galiciska",
  "Greek (Ancient)": "forngrekiska",
  "Hausa": "hausa",
  "Hebrew": "hebreiska",
  "Hebrew (Israel)": "hebreiska (Israel)",
  "Hindi": "hindi",
  "Croatian": "kroatiska",
  "Croatian (Croatia)": "kroatiska (Kroatien)",
  "Haitian Creole": "haitisk kreol",
  "Hungarian": "ungerska",
  "Hungarian (Hungary)": "ungerska (Ungern)",
  "Armenian": "armeniska",
  "Indonesian": "indonesiska",
  "Igbo": "igbo",
  "Icelandic": "isländska",
  "Italian": "italienska",
  "Italian (Italy)": "italienska (Italien)",
  "Inuktitut": "inuktitut",
  "Japanese": "japanska",
  "Japanese (Japan)": "japanska (Japan)",
  "Georgian": "georgiska",
  "Kabyle": "kabyliska",
  "Kazakh": "kazakiska",
  "Khmer": "kambodjanska",
  "Kannada": "kannada",
  "Korean": "koreanska",
  "Korean (Korea)": "koreanska (Sydkorea)",
  "Latin": "latin",
  "Lakota": "lakota",
  "Lao": "laotiska",
  "Lithuanian": "litauiska",
  "Latvian": "lettiska",
  "Māori": "maori",
  "Mongolian": "mongoliska",
  "Marathi": "marathi",
  "Malay": "malajiska",
  "Maltese": "maltesiska",
  "Burmese": "burmesiska",
  "Norwegian (Bokmål)": "norska (bokmål)",
  "Norwegian (Bokmål, Norway)": "norska (bokmål, Norge)",
  "Nepali": "nepalesiska",
  "Dutch": "nederländska",
  "Flemish": "flamländska",
  "Norwegian (Nynorsk)": "norska (nynorska)",
  "Navajo": "navaho",
  "Turkish (Ottoman)": "turkiska (ottomanska)",
  "Punjabi": "punjabi",
  "Persian (Old)": "persiska (fornpersiska)",
  "Polish": "polska",
  "Pashto": "afghanska",
  "Portuguese": "portugisiska",
  "Portuguese (Brazil)": "portugisiska (Brasilien)",
  "Portuguese (Portugal)": "portugisiska (Portugal)",
  "Quechua": "quechua",
  "Romanian": "rumänska",
  "Russian": "ryska",
  "Kinyarwanda": "kinjarwanda",
  "Sanskrit": "sanskrit",
  "Sami (Northern)": "samiska (nordsamiska)",
  "Sinhala": "singalesiska",
  "Slovak": "slovakiska",
  "Slovak (Slovakia)": "slovakiska (Slovakien)",
  "Slovenian": "slovenska",
  "Slovenian (Slovenia)": "slovenska (Slovenien)",
  "Sami (Southern)": "samiska (sydsamiska)",
  "Sami (Northern)": "samiska (nordsamiska)",
  "Sami (Lule)": "samiska (lulesamiska)",
  "Shona": "shona",
  "Serbian": "serbiska",
  "Serbian (Latin)": "serbiska (latinsk)",
  "Swedish": "svenska",
  "Swedish (Sweden)": "svenska (Sverige)",
  "Swahili": "swahili",
  "Swahili (Kenya)": "swahili (Kenya)",
  "Swahili (Tanzania)": "swahili (Tanzania)",
  "Syriac (Classical)": "syriska (klassisk)",
  "Tamil": "tamil",
  "Telugu": "telugu",
  "Tajik": "tadzjikiska",
  "Thai": "thailändska",
  "Thai (Thailand)": "thailändska (Thailand)",
  "Turkmen": "turkmeniska",
  "Tagalog": "tagalog",
  "Turkish": "turkiska",
  "Turkish (Turkey)": "turkiska (Turkiet)",
  "Tatar": "tatariska",
  "Uyghur": "uiguriska",
  "Ukrainian": "ukrainska",
  "Urdu": "urdu",
  "Uzbek": "uzbekiska",
  "Vietnamese": "vietnamesiska",
  "Wolof": "wolof",
  "Xhosa": "xhosa",
  "Yiddish": "jiddisch",
  "Yoruba": "yoruba",
  "Maya (Yucatec)": "maya (yukatekisk)",
  "Chinese": "kinesiska",
  "Chinese (Simplified)": "kinesiska (förenklad)",
  "Chinese (Simplified)": "kinesiska (förenklad)",
  "Chinese (Traditional)": "kinesiska (traditionell)",
  "Chinese (Hong Kong)": "kinesiska (Hongkong)",
  "Chinese (Singapore)": "kinesiska (Singapore)",
  "Chinese (Traditional)": "kinesiska (traditionell)",
  "Zulu": "zulu",
  "Zulu": "zulu (Sydafrika)"
});