tinymce.addI18n('th_TH', {
  "-Language Not Set-": "-ไม่ได้ตั้งค่าภาษา-",
  "Choose from list": "เลือกจากรายการ",
  "Choose languages": "เลือกภาษา",
  "Choose up to six languages": "เลือกได้สูงสุดหกภาษา",
  "Configure languages": "กำหนดค่าภาษา",
  "Current language:": "ภาษาปัจจุบัน:",
  "Enter a valid language code with no spaces. Or, press cancel.": "ป้อนรหัสภาษาที่ถูกต้องโดยไม่มีช่องว่าง หรือกดยกเลิก",
  "Enter manually": "ป้อนด้วยตนเอง",
  "Enter new lang code (e.g., \"en-US\"):": "ป้อนรหัสภาษาใหม่ (เช่น \"th-TH\"):",
  "Indicate current language": "แสดงภาษาปัจจุบัน",
  "Manually enter language {{number}}:": "ป้อนภาษา {{number}} ด้วยตนเอง:",
  "New Language:": "ภาษาใหม่:",
  "None": "ไม่มี",
  "Other - Enter manually": "อื่น ๆ - ป้อนด้วยตนเอง",
  "Really remove all language markup from the document?": "ต้องการลบเครื่องหมายภาษาทั้งหมดออกจากเอกสารจริงหรือไม่?",
  "Remove All lang markup": "ลบเครื่องหมายภาษาทั้งหมด",
  "Remove Language Markup": "ลบเครื่องหมายภาษา",
  "Remove current lang value": "ลบค่าภาษาปัจจุบัน",
  "Reveal lang markup": "แสดงเครื่องหมายภาษา",
  "Select language {{number}}:": "เลือกภาษา {{number}}:",
  "Select the document's default language.": "เลือกภาษาเริ่มต้นของเอกสาร",
  "Set default document language": "ตั้งค่าภาษาเริ่มต้นของเอกสาร",
  "Set text language": "ตั้งค่าภาษาข้อความ",
  "Afrikaans": "แอฟริกานส์",
  "Afrikaans": "แอฟริกานส์ (แอฟริกาใต้)",
  "Akan": "อาคาน",
  "Amharic": "อัมฮารา",
  "Arabic": "อาหรับ",
  "Arabic (Egypt)": "อาหรับ (อียิปต์)",
  "Arabic (Morocco)": "อาหรับ (โมร็อกโก)",
  "Arabic (Saudi Arabia)": "อาหรับ (ซาอุดีอาระเบีย)",
  "Azerbaijani": "อาเซอร์ไบจาน",
  "Belarusian": "เบลารุส",
  "Bulgarian": "บัลแกเรีย",
  "Bulgarian (Bulgaria)": "บัลแกเรีย (บัลแกเรีย)",
  "Bhojpuri": "โภชปุรี",
  "Bambara": "บัมบารา",
  "Bangla": "บังกลา",
  "Tibetan": "ทิเบต",
  "Bosnian": "บอสเนีย",
  "Catalan": "คาตาลัน",
  "Coptic": "คอปติก",
  "Cree": "ครี",
  "Czech": "เช็ก",
  "Church Slavic": "เชอร์ชสลาวิก",
  "Welsh": "เวลส์",
  "Danish": "เดนมาร์ก",
  "German": "เยอรมัน",
  "German (Austria)": "เยอรมัน (ออสเตรีย)",
  "German (Switzerland)": "เยอรมัน (สวิตเซอร์แลนด์)",
  "German (Germany)": "เยอรมัน (เยอรมนี)",
  "Divehi": "ธิเวหิ",
  "Greek": "กรีก",
  "English": "อังกฤษ",
  "English (Australia)": "อังกฤษ (ออสเตรเลีย)",
  "English (Canada)": "อังกฤษ (แคนาดา)",
  "English (United Kingdom)": "อังกฤษ (สหราชอาณาจักร)",
  "English (Ireland)": "อังกฤษ (ไอร์แลนด์)",
  "English (India)": "อังกฤษ (อินเดีย)",
  "English (Trinidad)": "อังกฤษ (ตรินิแดด)",
  "English (United States)": "อังกฤษ (สหรัฐอเมริกา)",
  "English (South Africa)": "อังกฤษ (แอฟริกาใต้)",
  "Esperanto": "เอสเปรันโต",
  "Spanish": "สเปน",
  "Spanish (Argentina)": "สเปน (อาร์เจนตินา)",
  "Spanish (Chile)": "สเปน (ชิลี)",
  "Spanish (Colombia)": "สเปน (โคลอมเบีย)",
  "Spanish (Costa Rica)": "สเปน (คอสตาริกา)",
  "Spanish (Spain)": "สเปน (สเปน)",
  "Spanish (Mexico)": "สเปน (เม็กซิโก)",
  "Spanish (Peru)": "สเปน (เปรู)",
  "Estonian": "เอสโตเนีย",
  "Basque": "บาสก์",
  "Persian": "เปอร์เซีย",
  "Dari": "ดารี",
  "Persian (Iran)": "เปอร์เซีย (อิหร่าน)",
  "Fula": "ฟูลาห์",
  "Finnish": "ฟินแลนด์",
  "Finnish (Finland)": "ฟินแลนด์ (ฟินแลนด์)",
  "Filipino": "ฟิลิปปินส์",
  "French": "ฝรั่งเศส",
  "French (Belgium)": "ฝรั่งเศส (เบลเยียม)",
  "French (Canada)": "ฝรั่งเศส (แคนาดา)",
  "French (Switzerland)": "ฝรั่งเศส (สวิตเซอร์แลนด์)",
  "Irish": "ไอริช",
  "Galician": "กาลิเซีย",
  "Greek (Ancient)": "กรีก (โบราณ)",
  "Hausa": "เฮาซา",
  "Hebrew": "ฮิบรู",
  "Hebrew (Israel)": "ฮิบรู (อิสราเอล)",
  "Hindi": "ฮินดี",
  "Croatian": "โครเอเชีย",
  "Croatian (Croatia)": "โครเอเชีย (โครเอเชีย)",
  "Haitian Creole": "เฮติครีโอล",
  "Hungarian": "ฮังการี",
  "Hungarian (Hungary)": "ฮังการี (ฮังการี)",
  "Armenian": "อาร์เมเนีย",
  "Indonesian": "อินโดนีเซีย",
  "Igbo": "อิกโบ",
  "Icelandic": "ไอซ์แลนด์",
  "Italian": "อิตาลี",
  "Italian (Italy)": "อิตาลี (อิตาลี)",
  "Inuktitut": "อินุกติตุต",
  "Japanese": "ญี่ปุ่น",
  "Japanese (Japan)": "ญี่ปุ่น (ญี่ปุ่น)",
  "Georgian": "จอร์เจีย",
  "Kabyle": "กาไบล",
  "Kazakh": "คาซัค",
  "Khmer": "เขมร",
  "Kannada": "กันนาดา",
  "Korean": "เกาหลี",
  "Korean (Korea)": "เกาหลี (เกาหลีใต้)",
  "Latin": "ละติน",
  "Lakota": "ลาโกตา",
  "Lao": "ลาว",
  "Lithuanian": "ลิทัวเนีย",
  "Latvian": "ลัตเวีย",
  "Māori": "เมารี",
  "Mongolian": "มองโกเลีย",
  "Marathi": "มราฐี",
  "Malay": "มาเลย์",
  "Maltese": "มอลตา",
  "Burmese": "พม่า",
  "Norwegian (Bokmål)": "นอร์เวย์ (บุคมอล)",
  "Norwegian (Bokmål, Norway)": "นอร์เวย์ (บุคมอล, นอร์เวย์)",
  "Nepali": "เนปาล",
  "Dutch": "ดัตช์",
  "Flemish": "เฟลมิช",
  "Norwegian (Nynorsk)": "นอร์เวย์ (นีนอสก์)",
  "Navajo": "นาวาโฮ",
  "Turkish (Ottoman)": "ตุรกี (ออตโตมัน)",
  "Punjabi": "ปัญจาบ",
  "Persian (Old)": "เปอร์เซีย (โบราณ)",
  "Polish": "โปแลนด์",
  "Pashto": "พัชโต",
  "Portuguese": "โปรตุเกส",
  "Portuguese (Brazil)": "โปรตุเกส (บราซิล)",
  "Portuguese (Portugal)": "โปรตุเกส (โปรตุเกส)",
  "Quechua": "เคชวา",
  "Romanian": "โรมาเนีย",
  "Russian": "รัสเซีย",
  "Kinyarwanda": "กินยารวันดา",
  "Sanskrit": "สันสกฤต",
  "Sami (Northern)": "ซามิ (เหนือ)",
  "Sinhala": "สิงหล",
  "Slovak": "สโลวัก",
  "Slovak (Slovakia)": "สโลวัก (สโลวาเกีย)",
  "Slovenian": "สโลวีเนีย",
  "Slovenian (Slovenia)": "สโลวีเนีย (สโลวีเนีย)",
  "Sami (Southern)": "ซามิ (ใต้)",
  "Sami (Northern)": "ซามิ (เหนือ)",
  "Sami (Lule)": "ซามิ (ลูเล)",
  "Shona": "โชนา",
  "Serbian": "เซอร์เบีย",
  "Serbian (Latin)": "เซอร์เบีย (ตัวอักษรละติน)",
  "Swedish": "สวีเดน",
  "Swedish (Sweden)": "สวีเดน (สวีเดน)",
  "Swahili": "สวาฮีลี",
  "Swahili (Kenya)": "สวาฮีลี (เคนยา)",
  "Swahili (Tanzania)": "สวาฮีลี (แทนซาเนีย)",
  "Syriac (Classical)": "ซีเรีย (คลาสสิก)",
  "Tamil": "ทมิฬ",
  "Telugu": "เตลูกู",
  "Tajik": "ทาจิก",
  "Thai": "ไทย",
  "Thai (Thailand)": "ไทย (ไทย)",
  "Turkmen": "เติร์กเมน",
  "Tagalog": "ตากาล็อก",
  "Turkish": "ตุรกี",
  "Turkish (Turkey)": "ตุรกี (ตุรกี)",
  "Tatar": "ตาตาร์",
  "Uyghur": "อุยกูร์",
  "Ukrainian": "ยูเครน",
  "Urdu": "อูรดู",
  "Uzbek": "อุซเบก",
  "Vietnamese": "เวียดนาม",
  "Wolof": "โวลอฟ",
  "Xhosa": "คะห์โอซา",
  "Yiddish": "ยิดดิช",
  "Yoruba": "โยรูบา",
  "Maya (Yucatec)": "มายา (ยูคาเตก)",
  "Chinese": "จีน",
  "Chinese (Simplified)": "จีน (ตัวย่อ)",
  "Chinese (Simplified)": "จีน (ตัวย่อ)",
  "Chinese (Traditional)": "จีน (ตัวเต็ม)",
  "Chinese (Hong Kong)": "จีน (ฮ่องกง)",
  "Chinese (Singapore)": "จีน (สิงคโปร์)",
  "Chinese (Traditional)": "จีน (ตัวเต็ม)",
  "Zulu": "ซูลู",
  "Zulu": "ซูลู (แอฟริกาใต้)"
});