tinymce.addI18n('tr', {
  "-Language Not Set-": "-Dil Ayarlanmadı-",
  "Choose from list": "Listeden seç",
  "Choose languages": "Dilleri seç",
  "Choose up to six languages": "En fazla altı dil seçin",
  "Configure languages": "Dilleri yapılandır",
  "Current language:": "Geçerli dil:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Boşluk içermeyen geçerli bir dil kodu girin. Veya iptal'e basın.",
  "Enter manually": "El ile gir",
  "Enter new lang code (e.g., \"en-US\"):": "Yeni dil kodunu girin (örn. \"tr-TR\"):",
  "Indicate current language": "Geçerli dili belirt",
  "Manually enter language {{number}}:": "{{number}}. dili el ile girin:",
  "New Language:": "Yeni Dil:",
  "None": "Hiçbiri",
  "Other - Enter manually": "Diğer - El ile gir",
  "Really remove all language markup from the document?": "Belgeden tüm dil işaretlemesi gerçekten kaldırılsın mı?",
  "Remove All lang markup": "Tüm dil işaretlemesini kaldır",
  "Remove Language Markup": "Dil İşaretlemesini Kaldır",
  "Remove current lang value": "Geçerli dil değerini kaldır",
  "Reveal lang markup": "Dil işaretlemesini göster",
  "Select language {{number}}:": "{{number}}. dili seçin:",
  "Select the document's default language.": "Belgenin varsayılan dilini seçin.",
  "Set default document language": "Varsayılan belge dilini ayarla",
  "Set text language": "Metin dilini ayarla",
  "Afrikaans": "Afrikaanca",
  "Afrikaans": "Afrikaanca (Güney Afrika)",
  "Akan": "Akan",
  "Amharic": "Amharca",
  "Arabic": "Arapça",
  "Arabic (Egypt)": "Arapça (Mısır)",
  "Arabic (Morocco)": "Arapça (Fas)",
  "Arabic (Saudi Arabia)": "Arapça (Suudi Arabistan)",
  "Azerbaijani": "Azerbaycan dili",
  "Belarusian": "Belarusça",
  "Bulgarian": "Bulgarca",
  "Bulgarian (Bulgaria)": "Bulgarca (Bulgaristan)",
  "Bhojpuri": "Bhojpuri",
  "Bambara": "Bambara",
  "Bangla": "Bengalce",
  "Tibetan": "Tibetçe",
  "Bosnian": "Boşnakça",
  "Catalan": "Katalanca",
  "Coptic": "Kıptice",
  "Cree": "Krice",
  "Czech": "Çekçe",
  "Church Slavic": "Kilise Slavcası",
  "Welsh": "Galce",
  "Danish": "Danca",
  "German": "Almanca",
  "German (Austria)": "Almanca (Avusturya)",
  "German (Switzerland)": "Almanca (İsviçre)",
  "German (Germany)": "Almanca (Almanya)",
  "Divehi": "Divehi dili",
  "Greek": "Yunanca",
  "English": "İngilizce",
  "English (Australia)": "İngilizce (Avustralya)",
  "English (Canada)": "İngilizce (Kanada)",
  "English (United Kingdom)": "İngilizce (Birleşik Krallık)",
  "English (Ireland)": "İngilizce (İrlanda)",
  "English (India)": "İngilizce (Hindistan)",
  "English (Trinidad)": "İngilizce (Trinidad)",
  "English (United States)": "İngilizce (Amerika Birleşik Devletleri)",
  "English (South Africa)": "İngilizce (Güney Afrika)",
  "Esperanto": "Esperanto",
  "Spanish": "İspanyolca",
  "Spanish (Argentina)": "İspanyolca (Arjantin)",
  "Spanish (Chile)": "İspanyolca (Şili)",
  "Spanish (Colombia)": "İspanyolca (Kolombiya)",
  "Spanish (Costa Rica)": "İspanyolca (Kosta Rika)",
  "Spanish (Spain)": "İspanyolca (İspanya)",
  "Spanish (Mexico)": "İspanyolca (Meksika)",
  "Spanish (Peru)": "İspanyolca (Peru)",
  "Estonian": "Estonca",
  "Basque": "Baskça",
  "Persian": "Farsça",
  "Dari": "Darice",
  "Persian (Iran)": "Farsça (İran)",
  "Fula": "Fula dili",
  "Finnish": "Fince",
  "Finnish (Finland)": "Fince (Finlandiya)",
  "Filipino": "Filipince",
  "French": "Fransızca",
  "French (Belgium)": "Fransızca (Belçika)",
  "French (Canada)": "Fransızca (Kanada)",
  "French (Switzerland)": "Fransızca (İsviçre)",
  "Irish": "İrlandaca",
  "Galician": "Galiçyaca",
  "Greek (Ancient)": "Yunanca (Antik)",
  "Hausa": "Hausa dili",
  "Hebrew": "İbranice",
  "Hebrew (Israel)": "İbranice (İsrail)",
  "Hindi": "Hintçe",
  "Croatian": "Hırvatça",
  "Croatian (Croatia)": "Hırvatça (Hırvatistan)",
  "Haitian Creole": "Haiti Kreyolu",
  "Hungarian": "Macarca",
  "Hungarian (Hungary)": "Macarca (Macaristan)",
  "Armenian": "Ermenice",
  "Indonesian": "Endonezce",
  "Igbo": "İbo dili",
  "Icelandic": "İzlandaca",
  "Italian": "İtalyanca",
  "Italian (Italy)": "İtalyanca (İtalya)",
  "Inuktitut": "İnuktitut dili",
  "Japanese": "Japonca",
  "Japanese (Japan)": "Japonca (Japonya)",
  "Georgian": "Gürcüce",
  "Kabyle": "Kabiliyece",
  "Kazakh": "Kazakça",
  "Khmer": "Khmer dili",
  "Kannada": "Kannada dili",
  "Korean": "Korece",
  "Korean (Korea)": "Korece (Kore)",
  "Latin": "Latince",
  "Lakota": "Lakotaca",
  "Lao": "Lao dili",
  "Lithuanian": "Litvanca",
  "Latvian": "Letonca",
  "Māori": "Māori dili",
  "Mongolian": "Moğolca",
  "Marathi": "Marathi dili",
  "Malay": "Malayca",
  "Maltese": "Maltaca",
  "Burmese": "Birman dili",
  "Norwegian (Bokmål)": "Norveççe (Bokmål)",
  "Norwegian (Bokmål, Norway)": "Norveççe (Bokmål, Norveç)",
  "Nepali": "Nepalce",
  "Dutch": "Felemenkçe",
  "Flemish": "Flamanca",
  "Norwegian (Nynorsk)": "Norveççe (Nynorsk)",
  "Navajo": "Navaho dili",
  "Turkish (Ottoman)": "Türkçe (Osmanlı)",
  "Punjabi": "Pencapça",
  "Persian (Old)": "Farsça (Eski)",
  "Polish": "Lehçe",
  "Pashto": "Peştuca",
  "Portuguese": "Portekizce",
  "Portuguese (Brazil)": "Portekizce (Brezilya)",
  "Portuguese (Portugal)": "Portekizce (Portekiz)",
  "Quechua": "Keçuva dili",
  "Romanian": "Rumence",
  "Russian": "Rusça",
  "Kinyarwanda": "Kinyarwanda",
  "Sanskrit": "Sanskrit",
  "Sami (Northern)": "Sami (Kuzey)",
  "Sinhala": "Sinhali dili",
  "Slovak": "Slovakça",
  "Slovak (Slovakia)": "Slovakça (Slovakya)",
  "Slovenian": "Slovence",
  "Slovenian (Slovenia)": "Slovence (Slovenya)",
  "Sami (Southern)": "Sami (Güney)",
  "Sami (Northern)": "Sami (Kuzey)",
  "Sami (Lule)": "Sami (Lule)",
  "Shona": "Şona dili",
  "Serbian": "Sırpça",
  "Serbian (Latin)": "Sırpça (Latin)",
  "Swedish": "İsveççe",
  "Swedish (Sweden)": "İsveççe (İsveç)",
  "Swahili": "Svahili dili",
  "Swahili (Kenya)": "Svahili dili (Kenya)",
  "Swahili (Tanzania)": "Svahili dili (Tanzanya)",
  "Syriac (Classical)": "Süryanice (Klasik)",
  "Tamil": "Tamilce",
  "Telugu": "Telugu dili",
  "Tajik": "Tacikçe",
  "Thai": "Tayca",
  "Thai (Thailand)": "Tayca (Tayland)",
  "Turkmen": "Türkmence",
  "Tagalog": "Tagalogca",
  "Turkish": "Türkçe",
  "Turkish (Turkey)": "Türkçe (Türkiye)",
  "Tatar": "Tatarca",
  "Uyghur": "Uygurca",
  "Ukrainian": "Ukraynaca",
  "Urdu": "Urduca",
  "Uzbek": "Özbekçe",
  "Vietnamese": "Vietnamca",
  "Wolof": "Volofça",
  "Xhosa": "Zosa dili",
  "Yiddish": "Yidiş",
  "Yoruba": "Yorubaca",
  "Maya (Yucatec)": "Maya (Yukatek)",
  "Chinese": "Çince",
  "Chinese (Simplified)": "Çince (Basitleştirilmiş)",
  "Chinese (Simplified)": "Çince (Basitleştirilmiş)",
  "Chinese (Traditional)": "Çince (Geleneksel)",
  "Chinese (Hong Kong)": "Çince (Hong Kong)",
  "Chinese (Singapore)": "Çince (Singapur)",
  "Chinese (Traditional)": "Çince (Geleneksel)",
  "Zulu": "Zuluca",
  "Zulu": "Zuluca (Güney Afrika)"
});