tinymce.addI18n('zh', {
  "-Language Not Set-": "-未设置语言-",
  "Choose from list": "从列表中选择",
  "Choose languages": "选择语言",
  "Choose up to six languages": "最多选择六种语言",
  "Configure languages": "配置语言",
  "Current language:": "当前语言：",
  "Enter a valid language code with no spaces. Or, press cancel.": "请输入有效的语言代码，不能包含空格。或者按取消。",
  "Enter manually": "手动输入",
  "Enter new lang code (e.g., \"en-US\"):": "输入新的语言代码（例如：\"zh\"）：",
  "Indicate current language": "指示当前语言",
  "Manually enter language {{number}}:": "手动输入语言{{number}}：",
  "New Language:": "新语言：",
  "None": "无",
  "Other - Enter manually": "其他 - 手动输入",
  "Really remove all language markup from the document?": "确定要从文档中移除所有语言标记吗？",
  "Remove All lang markup": "移除所有语言标记",
  "Remove Language Markup": "移除语言标记",
  "Remove current lang value": "移除当前语言值",
  "Reveal lang markup": "显示语言标记",
  "Select language {{number}}:": "选择语言{{number}}：",
  "Select the document's default language.": "选择文档的默认语言。",
  "Set default document language": "设置默认文档语言",
  "Set text language": "设置文本语言",
  "Afrikaans": "南非荷兰语",
  "Afrikaans": "南非荷兰语（南非）",
  "Akan": "阿肯语",
  "Amharic": "阿姆哈拉语",
  "Arabic": "阿拉伯语",
  "Arabic (Egypt)": "阿拉伯语（埃及）",
  "Arabic (Morocco)": "阿拉伯语（摩洛哥）",
  "Arabic (Saudi Arabia)": "阿拉伯语（沙特阿拉伯）",
  "Azerbaijani": "阿塞拜疆语",
  "Belarusian": "白俄罗斯语",
  "Bulgarian": "保加利亚语",
  "Bulgarian (Bulgaria)": "保加利亚语（保加利亚）",
  "Bhojpuri": "博杰普尔语",
  "Bambara": "班巴拉语",
  "Bangla": "孟加拉语",
  "Tibetan": "藏语",
  "Bosnian": "波斯尼亚语",
  "Catalan": "加泰罗尼亚语",
  "Coptic": "科普特语",
  "Cree": "克里语",
  "Czech": "捷克语",
  "Church Slavic": "教会斯拉夫语",
  "Welsh": "威尔士语",
  "Danish": "丹麦语",
  "German": "德语",
  "German (Austria)": "德语（奥地利）",
  "German (Switzerland)": "德语（瑞士）",
  "German (Germany)": "德语（德国）",
  "Divehi": "迪维希语",
  "Greek": "希腊语",
  "English": "英语",
  "English (Australia)": "英语（澳大利亚）",
  "English (Canada)": "英语（加拿大）",
  "English (United Kingdom)": "英语（英国）",
  "English (Ireland)": "英语（爱尔兰）",
  "English (India)": "英语（印度）",
  "English (Trinidad)": "英语（特立尼达）",
  "English (United States)": "英语（美国）",
  "English (South Africa)": "英语（南非）",
  "Esperanto": "世界语",
  "Spanish": "西班牙语",
  "Spanish (Argentina)": "西班牙语（阿根廷）",
  "Spanish (Chile)": "西班牙语（智利）",
  "Spanish (Colombia)": "西班牙语（哥伦比亚）",
  "Spanish (Costa Rica)": "西班牙语（哥斯达黎加）",
  "Spanish (Spain)": "西班牙语（西班牙）",
  "Spanish (Mexico)": "西班牙语（墨西哥）",
  "Spanish (Peru)": "西班牙语（秘鲁）",
  "Estonian": "爱沙尼亚语",
  "Basque": "巴斯克语",
  "Persian": "波斯语",
  "Dari": "达里语",
  "Persian (Iran)": "波斯语（伊朗）",
  "Fula": "富拉语",
  "Finnish": "芬兰语",
  "Finnish (Finland)": "芬兰语（芬兰）",
  "Filipino": "菲律宾语",
  "French": "法语",
  "French (Belgium)": "法语（比利时）",
  "French (Canada)": "法语（加拿大）",
  "French (Switzerland)": "法语（瑞士）",
  "Irish": "爱尔兰语",
  "Galician": "加利西亚语",
  "Greek (Ancient)": "希腊语（古代）",
  "Hausa": "豪萨语",
  "Hebrew": "希伯来语",
  "Hebrew (Israel)": "希伯来语（以色列）",
  "Hindi": "印地语",
  "Croatian": "克罗地亚语",
  "Croatian (Croatia)": "克罗地亚语（克罗地亚）",
  "Haitian Creole": "海地克里奥尔语",
  "Hungarian": "匈牙利语",
  "Hungarian (Hungary)": "匈牙利语（匈牙利）",
  "Armenian": "亚美尼亚语",
  "Indonesian": "印度尼西亚语",
  "Igbo": "伊博语",
  "Icelandic": "冰岛语",
  "Italian": "意大利语",
  "Italian (Italy)": "意大利语（意大利）",
  "Inuktitut": "因纽特语",
  "Japanese": "日语",
  "Japanese (Japan)": "日语（日本）",
  "Georgian": "格鲁吉亚语",
  "Kabyle": "卡拜尔语",
  "Kazakh": "哈萨克语",
  "Khmer": "高棉语",
  "Kannada": "卡纳达语",
  "Korean": "韩语",
  "Korean (Korea)": "韩语（韩国）",
  "Latin": "拉丁语",
  "Lakota": "拉科塔语",
  "Lao": "老挝语",
  "Lithuanian": "立陶宛语",
  "Latvian": "拉脱维亚语",
  "Māori": "毛利语",
  "Mongolian": "蒙古语",
  "Marathi": "马拉地语",
  "Malay": "马来语",
  "Maltese": "马耳他语",
  "Burmese": "缅甸语",
  "Norwegian (Bokmål)": "挪威语（博克马尔）",
  "Norwegian (Bokmål, Norway)": "挪威语（博克马尔，挪威）",
  "Nepali": "尼泊尔语",
  "Dutch": "荷兰语",
  "Flemish": "佛兰德语",
  "Norwegian (Nynorsk)": "挪威语（新挪威语）",
  "Navajo": "纳瓦霍语",
  "Turkish (Ottoman)": "土耳其语（奥斯曼）",
  "Punjabi": "旁遮普语",
  "Persian (Old)": "波斯语（古代）",
  "Polish": "波兰语",
  "Pashto": "普什图语",
  "Portuguese": "葡萄牙语",
  "Portuguese (Brazil)": "葡萄牙语（巴西）",
  "Portuguese (Portugal)": "葡萄牙语（葡萄牙）",
  "Quechua": "克丘亚语",
  "Romanian": "罗马尼亚语",
  "Russian": "俄语",
  "Kinyarwanda": "卢旺达语",
  "Sanskrit": "梵语",
  "Sami (Northern)": "萨米语（北部）",
  "Sinhala": "僧伽罗语",
  "Slovak": "斯洛伐克语",
  "Slovak (Slovakia)": "斯洛伐克语（斯洛伐克）",
  "Slovenian": "斯洛文尼亚语",
  "Slovenian (Slovenia)": "斯洛文尼亚语（斯洛文尼亚）",
  "Sami (Southern)": "萨米语（南部）",
  "Sami (Northern)": "萨米语（北部）",
  "Sami (Lule)": "萨米语（吕勒）",
  "Shona": "绍纳语",
  "Serbian": "塞尔维亚语",
  "Serbian (Latin)": "塞尔维亚语（拉丁文）",
  "Swedish": "瑞典语",
  "Swedish (Sweden)": "瑞典语（瑞典）",
  "Swahili": "斯瓦希里语",
  "Swahili (Kenya)": "斯瓦希里语（肯尼亚）",
  "Swahili (Tanzania)": "斯瓦希里语（坦桑尼亚）",
  "Syriac (Classical)": "叙利亚语（古典）",
  "Tamil": "泰米尔语",
  "Telugu": "泰卢固语",
  "Tajik": "塔吉克语",
  "Thai": "泰语",
  "Thai (Thailand)": "泰语（泰国）",
  "Turkmen": "土库曼语",
  "Tagalog": "他加禄语",
  "Turkish": "土耳其语",
  "Turkish (Turkey)": "土耳其语（土耳其）",
  "Tatar": "鞑靼语",
  "Uyghur": "维吾尔语",
  "Ukrainian": "乌克兰语",
  "Urdu": "乌尔都语",
  "Uzbek": "乌兹别克语",
  "Vietnamese": "越南语",
  "Wolof": "沃洛夫语",
  "Xhosa": "科萨语",
  "Yiddish": "意第绪语",
  "Yoruba": "约鲁巴语",
  "Maya (Yucatec)": "玛雅语（尤卡坦）",
  "Chinese": "中文",
  "Chinese (Simplified)": "中文（简体）",
  "Chinese (Simplified)": "中文（简体）",
  "Chinese (Traditional)": "中文（繁体）",
  "Chinese (Hong Kong)": "中文（香港）",
  "Chinese (Singapore)": "中文（新加坡）",
  "Chinese (Traditional)": "中文（繁体）",
  "Zulu": "祖鲁语",
  "Zulu": "祖鲁语（南非）"
});