tinymce.addI18n('ar', {
  "Current language:": "اللغة الحالية:",
  "Set text language": "تعيين لغة النص",
  "-Language Not Set-": "-لم يتم تعيين اللغة-",
  "Choose languages": "اختيار اللغات",
  "Remove Language Markup": "إزالة ترميز اللغة",
  "Remove current lang value": "إزالة قيمة اللغة الحالية",
  "Remove All lang markup": "إزالة جميع ترميز اللغة",
  "Configure languages": "تكوين اللغات",
  "Set default document language": "تعيين لغة المستند الافتراضية",
  "Reveal lang markup": "إظهار ترميز اللغة",
  "Indicate current language": "تحديد اللغة الحالية",
  "Select the document's default language.": "اختر اللغة الافتراضية للمستند.",
  "Choose from list": "اختر من القائمة",
  "Enter manually": "إدخال يدوي",
  "None": "لا شيء",
  "Other - Enter manually": "أخرى - إدخال يدوي",
  "Current language:": "اللغة الحالية:",
  "New Language:": "لغة جديدة:",
  'Enter new lang code (e.g., "en-US"):': 'أدخل رمز اللغة الجديد (مثل "en-US"):',
  "Choose up to six languages": "اختر حتى ست لغات",
  "Select language {{number}}:": "اختر اللغة {{number}}:",
  "Manually enter language {{number}}:": "أدخل اللغة {{number}} يدوياً:",
  "Really remove all language markup from the document?": "هل تريد حقاً إزالة جميع ترميز اللغة من المستند؟",
  "Enter a valid language code with no spaces. Or, press cancel.": "أدخل رمز لغة صالح بدون مسافات. أو اضغط إلغاء.",
  "langName.af": 'الأفريكانية',
  "langName.ak": 'الأكان',
  "langName.ar": 'العربية',
  "langName.az": 'الأذربيجانية',
  "langName.bg": 'البلغارية',
  "langName.bho": 'البهوجبورية',
  "langName.bm": 'البامبارا',
  "langName.bn": 'البنغالية',
  "langName.bo": 'التبتية',
  "langName.bs": 'البوسنية',
  "langName.ca": 'الكتالانية؛ الفالنسية',
  "langName.cs": 'التشيكية',
  "langName.cu": 'البلغارية القديمة',
  "langName.da": 'الدنماركية',
  "langName.de": 'الألمانية',
  "langName.el": 'اليونانية',
  "langName.en": 'الإنجليزية',
  "langName.en-au": 'الإنجليزية (أستراليا)',
  "langName.en-gb": 'الإنجليزية (المملكة المتحدة)',
  "langName.en-in": 'الإنجليزية (الهند)',
  "langName.en-ie": 'الإنجليزية (أيرلندا)',
  "langName.en-tt": 'الإنجليزية (ترينيداد)',
  "langName.en-us": 'الإنجليزية (الولايات المتحدة)',
  "langName.en-za": 'الإنجليزية (جنوب أفريقيا)',
  "langName.es": 'الإسبانية',
  "langName.es-ar": 'الإسبانية (الأرجنتين)',
  "langName.es-cl": 'الإسبانية (تشيلي)',
  "langName.es-co": 'الإسبانية (كولومبيا)',
  "langName.es-mx": 'الإسبانية (المكسيك)',
  "langName.es-pe": 'الإسبانية (بيرو)',
  "langName.et": 'الإستونية',
  "langName.eu": 'الباسكية',
  "langName.fa": 'الفارسية',
  "langName.fi": 'الفنلندية',
  "langName.fr": 'الفرنسية',
  "langName.fr-ca": 'الفرنسية (الكندية)',
  "langName.gl": 'الجاليكية (إسبانيا)',
  "langName.he": 'العبرية',
  "langName.hi": 'الهندية',
  "langName.hr": 'الكرواتية',
  "langName.hu": 'المجرية',
  "langName.id": 'الإندونيسية',
  "langName.it": 'الإيطالية',
  "langName.ja": 'اليابانية',
  "langName.kk": 'الكازاخية',
  "langName.kn": 'الكانادا',
  "langName.ko": 'الكورية',
  "langName.la": 'اللاتينية',
  "langName.lkt": 'اللاكوتا',
  "langName.mn": 'المنغولية',
  "langName.mr": 'الماراثية',
  "langName.nb": 'النرويجية بوكمال',
  "langName.nl": 'الهولندية',
  "langName.nl-be": 'الهولندية (بلجيكا)',
  "langName.nn": 'النرويجية نينورسك',
  "langName.pl": 'البولندية',
  "langName.ps": 'الباشتو',
  "langName.pt": 'البرتغالية الدولية',
  "langName.pt-br": 'البرتغالية البرازيلية',
  "langName.qu": 'الكيتشوا',
  "langName.ro": 'الرومانية',
  "langName.ru": 'الروسية',
  "langName.sa": 'السنسكريتية',
  "langName.sk-sk": 'السلوفاكية',
  "langName.sl": 'السلوفينية',
  "langName.sma": 'السامي الجنوبي',
  "langName.sme": 'السامي الشمالي',
  "langName.smj": 'سامي لوله',
  "langName.sr": 'الصربية',
  "langName.sv": 'السويدية',
  "langName.sw": 'السواحيلية',
  "langName.ta": 'التاميلية',
  "langName.te": 'التيلوغو',
  "langName.tg": 'الطاجيكية',
  "langName.th": 'التايلاندية',
  "langName.tr": 'التركية',
  "langName.ug": 'الأويغورية',
  "langName.uk": 'الأوكرانية',
  "langName.ur": 'الأردو',
  "langName.uz": 'الأوزبكية',
  "langName.vi": 'الفيتنامية',
  "langName.wo": 'الولوف',
  "langName.yi": 'اليديشية',
  "langName.yo": 'اليوروبا',
  "langName.yua": 'يوكاتيك مايا',
  "langName.zh": 'الصينية',
  "langName.zh-cn": 'الصينية (الصين)',
  "langName.zh-hk": 'الصينية (هونغ كونغ)',
  "langName.zh-tw": 'الصينية (تايوان)',
  "langName.zh-hans": 'الصينية المبسطة',
  "langName.zh-hant": 'الصينية التقليدية',
  "langName.zu": 'الزولو'
});