tinymce.addI18n('ar', {
  "-Language Not Set-": "-لم يتم تعيين اللغة-",
  "Choose from list": "اختر من القائمة",
  "Choose languages": "اختيار اللغات",
  "Choose up to six languages": "اختر حتى ست لغات",
  "Configure languages": "تكوين اللغات",
  "Current language:": "اللغة الحالية:",
  "Enter a valid language code with no spaces. Or, press cancel.": "أدخل رمز لغة صالح بدون مسافات. أو اضغط إلغاء.",
  "Enter manually": "إدخال يدوي",
  "Enter new lang code (e.g., \"en-US\"):": "أدخل رمز اللغة الجديد (مثل \"en-US\"):",
  "Indicate current language": "تحديد اللغة الحالية",
  "Manually enter language {{number}}:": "أدخل اللغة {{number}} يدوياً:",
  "New Language:": "لغة جديدة:",
  "None": "لا شيء",
  "Other - Enter manually": "أخرى - إدخال يدوي",
  "Really remove all language markup from the document?": "هل تريد حقاً إزالة جميع ترميز اللغة من المستند؟",
  "Remove All lang markup": "إزالة جميع ترميز اللغة",
  "Remove Language Markup": "إزالة ترميز اللغة",
  "Remove current lang value": "إزالة قيمة اللغة الحالية",
  "Reveal lang markup": "إظهار ترميز اللغة",
  "Select language {{number}}:": "اختر اللغة {{number}}:",
  "Select the document's default language.": "اختر اللغة الافتراضية للمستند.",
  "Set default document language": "تعيين لغة المستند الافتراضية",
  "Set text language": "تعيين لغة النص",
  "langName.af": "الأفريقانية",
  "langName.af-za": "الأفريقانية",
  "langName.ak": "الأكانية",
  "langName.am": "الأمهرية",
  "langName.ar": "العربية",
  "langName.ar-eg": "العربية (مصر)",
  "langName.ar-ma": "العربية (المغرب)",
  "langName.ar-sa": "العربية",
  "langName.az": "الأذربيجانية",
  "langName.be": "البيلاروسية",
  "langName.bg": "البلغارية",
  "langName.bg-bg": "البلغارية",
  "langName.bho": "البهوجبورية",
  "langName.bm": "البامبارا",
  "langName.bn": "البنغالية",
  "langName.bo": "التبتية",
  "langName.bs": "البوسنية",
  "langName.ca": "الكتالانية",
  "langName.cop": "القبطية",
  "langName.cr": "الكرى",
  "langName.cs": "التشيكية",
  "langName.cu": "سلافية كنسية",
  "langName.cy": "الويلزية",
  "langName.da": "الدانمركية",
  "langName.de": "الألمانية",
  "langName.de-at": "الألمانية النمساوية",
  "langName.de-ch": "الألمانية (سويسرا)",
  "langName.de-de": "الألمانية",
  "langName.dv": "المالديفية",
  "langName.el": "اليونانية",
  "langName.en": "الإنجليزية",
  "langName.en-au": "الإنجليزية (أستراليا)",
  "langName.en-ca": "الإنجليزية (كندا)",
  "langName.en-gb": "الإنجليزية (المملكة المتحدة)",
  "langName.en-ie": "الإنجليزية (أيرلندا)",
  "langName.en-in": "الإنجليزية (الهند)",
  "langName.en-tt": "الإنجليزية (ترينيداد)",
  "langName.en-us": "الإنجليزية",
  "langName.en-za": "الإنجليزية (جنوب أفريقيا)",
  "langName.eo": "الإسبرانتو",
  "langName.es": "الإسبانية",
  "langName.es-ar": "الإسبانية (الأرجنتين)",
  "langName.es-cl": "الإسبانية (تشيلي)",
  "langName.es-co": "الإسبانية (كولومبيا)",
  "langName.es-cr": "الإسبانية (كوستاريكا)",
  "langName.es-es": "الإسبانية الأوروبية",
  "langName.es-mx": "الإسبانية المكسيكية",
  "langName.es-pe": "الإسبانية (بيرو)",
  "langName.et": "الإستونية",
  "langName.eu": "الباسكية",
  "langName.fa": "الفارسية",
  "langName.fa-af": "الدارية",
  "langName.fa-ir": "الفارسية",
  "langName.ff": "الفولانية",
  "langName.fi": "الفنلندية",
  "langName.fi-fi": "الفنلندية",
  "langName.fil": "الفلبينية",
  "langName.fr": "الفرنسية",
  "langName.fr-be": "الفرنسية (بلجيكا)",
  "langName.fr-ca": "الفرنسية (الكندية)",
  "langName.fr-ch": "الفرنسية (سويسرا)",
  "langName.ga": "الأيرلندية",
  "langName.gl": "الجاليكية",
  "langName.grc": "اليونانية القديمة",
  "langName.ha": "الهوسا",
  "langName.he": "العبرية",
  "langName.he-il": "العبرية",
  "langName.hi": "الهندية",
  "langName.hr": "الكرواتية",
  "langName.hr-hr": "الكرواتية",
  "langName.ht": "الكريولية الهايتية",
  "langName.hu": "الهنغارية",
  "langName.hu-hu": "الهنغارية",
  "langName.hy": "الأرمنية",
  "langName.id": "الإندونيسية",
  "langName.ig": "الإيجبو",
  "langName.is": "الأيسلندية",
  "langName.it": "الإيطالية",
  "langName.it-it": "الإيطالية",
  "langName.iu": "الإينكتيتت",
  "langName.ja": "اليابانية",
  "langName.ja-jp": "اليابانية",
  "langName.ka": "الجورجية",
  "langName.kab": "القبيلية",
  "langName.kk": "الكازاخستانية",
  "langName.km": "الخميرية",
  "langName.kn": "الكانادا",
  "langName.ko": "الكورية",
  "langName.ko-kr": "الكورية",
  "langName.la": "اللاتينية",
  "langName.lkt": "لاكوتا",
  "langName.lo": "اللاوية",
  "langName.lt": "الليتوانية",
  "langName.lv": "اللاتفية",
  "langName.mi": "الماورية",
  "langName.mn": "المنغولية",
  "langName.mr": "الماراثية",
  "langName.ms": "الماليزية",
  "langName.mt": "المالطية",
  "langName.my": "البورمية",
  "langName.nb": "النرويجية بوكمال",
  "langName.nb-no": "النرويجية بوكمال",
  "langName.ne": "النيبالية",
  "langName.nl": "الهولندية",
  "langName.nl-be": "الهولندية (بلجيكا)",
  "langName.nn": "النرويجية نينورسك",
  "langName.nv": "النافاجو",
  "langName.ota": "التركية العثمانية",
  "langName.pa": "البنجابية",
  "langName.peo": "الفارسية القديمة",
  "langName.pl": "البولندية",
  "langName.ps": "البشتو",
  "langName.pt": "البرتغالية",
  "langName.pt-br": "البرتغالية البرازيلية",
  "langName.pt-pt": "البرتغالية الأوروبية",
  "langName.qu": "كيشوا",
  "langName.ro": "الرومانية",
  "langName.ru": "الروسية",
  "langName.rw": "الكينيارواندا",
  "langName.sa": "السنسكريتية",
  "langName.se": "سامي الشمالية",
  "langName.si": "السنهالية",
  "langName.sk-sk": "السلوفاكية",
  "langName.sl": "السلوفانية",
  "langName.sl-si": "السلوفانية",
  "langName.sma": "السامي الجنوبي",
  "langName.sme": "السامي الشمالي",
  "langName.smj": "اللول سامي",
  "langName.sn": "الشونا",
  "langName.sr": "الصربية",
  "langName.sr-latn": "الصربية (لاتينية)",
  "langName.sv": "السويدية",
  "langName.sv-se": "السويدية",
  "langName.sw": "السواحلية",
  "langName.sw-ke": "السواحلية",
  "langName.sw-tz": "السواحلية",
  "langName.syc": "سريانية تقليدية",
  "langName.ta": "التاميلية",
  "langName.te": "التيلوغوية",
  "langName.tg": "الطاجيكية",
  "langName.th": "التايلاندية",
  "langName.th-th": "التايلاندية",
  "langName.tk": "التركمانية",
  "langName.tl": "التاغالوغية",
  "langName.tr": "التركية",
  "langName.tr-tr": "التركية",
  "langName.tt": "التترية",
  "langName.ug": "الأويغورية",
  "langName.uk": "الأوكرانية",
  "langName.ur": "الأوردية",
  "langName.uz": "الأوزبكية",
  "langName.vi": "الفيتنامية",
  "langName.wo": "الولوفية",
  "langName.xh": "الخوسا",
  "langName.yi": "اليديشية",
  "langName.yo": "اليوروبا",
  "langName.yua": "يوكاتيك مايا",
  "langName.zh": "الصينية",
  "langName.zh-cn": "الصينية المبسطة",
  "langName.zh-hans": "الصينية المبسطة",
  "langName.zh-hant": "الصينية التقليدية",
  "langName.zh-hk": "الصينية (هونغ كونغ)",
  "langName.zh-sg": "الصينية (سنغافورة)",
  "langName.zh-tw": "الصينية التقليدية",
  "langName.zu": "الزولو",
  "langName.zu-za": "الزولو"
});