tinymce.addI18n("ar_SA", {
  "Current language:": "اللغة الحالية:",
  "Set text language": "تحديد لغة النص",
  "-Language Not Set-": "-لم يتم تحديد اللغة-",
  "Choose languages": "اختيار اللغات",
  "Remove Language Markup": "إزالة تمييز اللغة",
  "Remove current lang value": "إزالة قيمة اللغة الحالية",
  "Remove All lang markup": "إزالة جميع تمييزات اللغة",
  "Configure languages": "إعداد اللغات",
  "Set default document language": "تحديد اللغة الافتراضية للمستند",
  "Reveal lang markup": "إظهار تمييز اللغة",
  "Indicate current language": "تحديد اللغة الحالية",
  "Select the document's default language.": "قم بتحديد اللغة الافتراضية للمستند.",
  "Choose from list": "اختيار من القائمة",
  "Enter manually": "إدخال يدوي",
  "None": "لا شيء",
  "Other - Enter manually": "أخرى - إدخال يدوي",
  "New Language:": "لغة جديدة:",
  "Enter new lang code (e.g., \"en-US\"):": "أدخل رمز اللغة الجديد (مثال: \"ar-SA\"):",
  "Choose up to six languages": "اختيار حتى ست لغات",
  "Select language {{number}}:": "اختيار اللغة {{number}}:",
  "Manually enter language {{number}}:": "إدخال اللغة {{number}} يدوياً:",
  "Really remove all language markup from the document?": "هل تريد حقاً إزالة جميع تمييزات اللغة من المستند؟",
  "Enter a valid language code with no spaces. Or, press cancel.": "أدخل رمز لغة صحيح بدون مسافات. أو اضغط إلغاء.",
  "langName.af": "الأفريقانية",
  "langName.ak": "الأكانية",
  "langName.ar": "العربية",
  "langName.az": "الأذربيجانية",
  "langName.bg": "البلغارية",
  "langName.bho": "البوجبورية",
  "langName.bm": "البامبارا",
  "langName.bn": "البنغالية",
  "langName.bo": "التبتية",
  "langName.bs": "البوسنية",
  "langName.ca": "الكتالونية؛ الفالنسية",
  "langName.cs": "التشيكية",
  "langName.cu": "البلغارية القديمة",
  "langName.da": "الدنماركية",
  "langName.de": "الألمانية",
  "langName.el": "اليونانية",
  "langName.en": "الإنجليزية",
  "langName.en-au": "الإنجليزية (أستراليا)",
  "langName.en-gb": "الإنجليزية (بريطانيا)",
  "langName.en-in": "الإنجليزية (الهند)",
  "langName.en-ie": "الإنجليزية (أيرلندا)",
  "langName.en-tt": "الإنجليزية (ترينيداد)",
  "langName.en-us": "الإنجليزية (الولايات المتحدة)",
  "langName.en-za": "الإنجليزية (جنوب أفريقيا)",
  "langName.es": "الإسبانية",
  "langName.es-ar": "الإسبانية (الأرجنتين)",
  "langName.es-cl": "الإسبانية (تشيلي)",
  "langName.es-co": "الإسبانية (كولومبيا)",
  "langName.es-mx": "الإسبانية (المكسيك)",
  "langName.es-pe": "الإسبانية (بيرو)",
  "langName.et": "الإستونية",
  "langName.eu": "الباسكية",
  "langName.fa": "الفارسية",
  "langName.fi": "الفنلندية",
  "langName.fr": "الفرنسية",
  "langName.fr-ca": "الفرنسية (كندا)",
  "langName.gl": "الجاليسية (إسبانيا)",
  "langName.he": "العبرية",
  "langName.hi": "الهندية",
  "langName.hr": "الكرواتية",
  "langName.hu": "المجرية",
  "langName.id": "الإندونيسية",
  "langName.it": "الإيطالية",
  "langName.ja": "اليابانية",
  "langName.kk": "الكازاخية",
  "langName.kn": "الكنادية",
  "langName.ko": "الكورية",
  "langName.la": "اللاتينية",
  "langName.lkt": "اللاكوتا",
  "langName.mn": "المنغولية",
  "langName.mr": "الماراثية",
  "langName.nb": "النرويجية بوكمال",
  "langName.nl": "الهولندية",
  "langName.nl-be": "الهولندية (بلجيكا)",
  "langName.nn": "النرويجية نينورسك",
  "langName.pl": "البولندية",
  "langName.ps": "البشتوية",
  "langName.pt": "البرتغالية الدولية",
  "langName.pt-br": "البرتغالية (البرازيل)",
  "langName.qu": "الكيتشوا",
  "langName.ro": "الرومانية",
  "langName.ru": "الروسية",
  "langName.sa": "السنسكريتية",
  "langName.sk-sk": "السلوفاكية",
  "langName.sl": "السلوفينية",
  "langName.sma": "السامية الجنوبية",
  "langName.sme": "السامية الشمالية",
  "langName.smj": "سامية لولي",
  "langName.sr": "الصربية",
  "langName.sv": "السويدية",
  "langName.sw": "السواحيلية",
  "langName.ta": "التاميلية",
  "langName.te": "التيلوغوية",
  "langName.tg": "الطاجيكية",
  "langName.th": "التايلندية",
  "langName.tr": "التركية",
  "langName.ug": "الأويغورية",
  "langName.uk": "الأوكرانية",
  "langName.ur": "الأردية",
  "langName.uz": "الأوزبكية",
  "langName.vi": "الفيتنامية",
  "langName.wo": "الولوفية",
  "langName.yi": "اليديشية",
  "langName.yo": "اليوروبا",
  "langName.yua": "مايا يوكاتيك",
  "langName.zh": "الصينية",
  "langName.zh-cn": "الصينية (الصين)",
  "langName.zh-hk": "الصينية (هونغ كونغ)",
  "langName.zh-tw": "الصينية (تايوان)",
  "langName.zh-hans": "الصينية المبسطة",
  "langName.zh-hant": "الصينية التقليدية",
  "langName.zu": "الزولوية"
});