tinymce.addI18n('bg', {
  "-Language Not Set-": "-Езикът не е зададен-",
  "Choose from list": "Избиране от списък",
  "Choose languages": "Избиране на езици",
  "Choose up to six languages": "Изберете до шест езика",
  "Configure languages": "Конфигуриране на езици",
  "Current language:": "Текущ език:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Въведете валиден код за език без интервали. Или натиснете отказ.",
  "Enter manually": "Въвеждане ръчно",
  "Enter new lang code (e.g., \"en-US\"):": "Въведете нов код за език (напр. \"bg-BG\"):",
  "Indicate current language": "Указване на текущия език",
  "Manually enter language {{number}}:": "Ръчно въвеждане на език {{number}}:",
  "New Language:": "Нов език:",
  "None": "Няма",
  "Other - Enter manually": "Друго - Въвеждане ръчно",
  "Really remove all language markup from the document?": "Наистина ли да премахна цялото езиково маркиране от документа?",
  "Remove All lang markup": "Премахване на цялото езиково маркиране",
  "Remove Language Markup": "Премахване на езиковото маркиране",
  "Remove current lang value": "Премахване на текущата стойност за език",
  "Reveal lang markup": "Показване на езиковото маркиране",
  "Select language {{number}}:": "Избиране на език {{number}}:",
  "Select the document's default language.": "Изберете езика по подразбиране на документа.",
  "Set default document language": "Задаване на език по подразбиране на документа",
  "Set text language": "Задаване на език на текста",
  "langName.af": "африканс",
  "langName.af-za": "африканс (Южна Африка)",
  "langName.ak": "акан",
  "langName.am": "амхарски",
  "langName.ar": "арабски",
  "langName.ar-eg": "арабски (Египет)",
  "langName.ar-ma": "арабски (Мароко)",
  "langName.ar-sa": "арабски (Саудитска Арабия)",
  "langName.az": "азербайджански",
  "langName.be": "беларуски",
  "langName.bg": "български",
  "langName.bg-bg": "български (България)",
  "langName.bho": "боджпури",
  "langName.bm": "бамбара",
  "langName.bn": "бенгалски",
  "langName.bo": "тибетски",
  "langName.bs": "босненски",
  "langName.ca": "каталонски",
  "langName.cop": "коптски",
  "langName.cr": "крии",
  "langName.cs": "чешки",
  "langName.cu": "църковнославянски",
  "langName.cy": "уелски",
  "langName.da": "датски",
  "langName.de": "немски",
  "langName.de-at": "немски (Австрия)",
  "langName.de-ch": "немски (Швейцария)",
  "langName.de-de": "немски (Германия)",
  "langName.dv": "дивехи",
  "langName.el": "гръцки",
  "langName.en": "английски",
  "langName.en-au": "английски (Австралия)",
  "langName.en-ca": "английски (Канада)",
  "langName.en-gb": "английски (Обединено кралство)",
  "langName.en-ie": "английски (Ирландия)",
  "langName.en-in": "английски (Индия)",
  "langName.en-tt": "английски (Тринидад)",
  "langName.en-us": "английски (Съединени щати)",
  "langName.en-za": "английски (Южна Африка)",
  "langName.eo": "есперанто",
  "langName.es": "испански",
  "langName.es-ar": "испански (Аржентина)",
  "langName.es-cl": "испански (Чили)",
  "langName.es-co": "испански (Колумбия)",
  "langName.es-cr": "испански (Коста Рика)",
  "langName.es-es": "испански (Испания)",
  "langName.es-mx": "испански (Мексико)",
  "langName.es-pe": "испански (Перу)",
  "langName.et": "естонски",
  "langName.eu": "баски",
  "langName.fa": "персийски",
  "langName.fa-af": "дари",
  "langName.fa-ir": "персийски (Иран)",
  "langName.ff": "фула",
  "langName.fi": "фински",
  "langName.fi-fi": "фински (Финландия)",
  "langName.fil": "филипински",
  "langName.fr": "френски",
  "langName.fr-be": "френски (Белгия)",
  "langName.fr-ca": "френски (Канада)",
  "langName.fr-ch": "френски (Швейцария)",
  "langName.ga": "ирландски",
  "langName.gl": "галисийски",
  "langName.grc": "древногръцки",
  "langName.ha": "хауса",
  "langName.he": "иврит",
  "langName.he-il": "иврит (Израел)",
  "langName.hi": "хинди",
  "langName.hr": "хърватски",
  "langName.hr-hr": "хърватски (Хърватия)",
  "langName.ht": "хаитянски креолски",
  "langName.hu": "унгарски",
  "langName.hu-hu": "унгарски (Унгария)",
  "langName.hy": "арменски",
  "langName.id": "индонезийски",
  "langName.ig": "игбо",
  "langName.is": "исландски",
  "langName.it": "италиански",
  "langName.it-it": "италиански (Италия)",
  "langName.iu": "инуктитут",
  "langName.ja": "японски",
  "langName.ja-jp": "японски (Япония)",
  "langName.ka": "грузински",
  "langName.kab": "кабилски",
  "langName.kk": "казахски",
  "langName.km": "кхмерски",
  "langName.kn": "каннада",
  "langName.ko": "корейски",
  "langName.ko-kr": "корейски (Корея)",
  "langName.la": "латински",
  "langName.lkt": "лакота",
  "langName.lo": "лаоски",
  "langName.lt": "литовски",
  "langName.lv": "латвийски",
  "langName.mi": "маорски",
  "langName.mn": "монголски",
  "langName.mr": "марати",
  "langName.ms": "малайски",
  "langName.mt": "малтийски",
  "langName.my": "бирмански",
  "langName.nb": "норвежки (букмол)",
  "langName.nb-no": "норвежки (букмол, Норвегия)",
  "langName.ne": "непалски",
  "langName.nl": "нидерландски",
  "langName.nl-be": "фламандски",
  "langName.nn": "норвежки (нюношк)",
  "langName.nv": "навахо",
  "langName.ota": "турски (отомански)",
  "langName.pa": "пенджабски",
  "langName.peo": "персийски (старо)",
  "langName.pl": "полски",
  "langName.ps": "пущу",
  "langName.pt": "португалски",
  "langName.pt-br": "португалски (Бразилия)",
  "langName.pt-pt": "португалски (Португалия)",
  "langName.qu": "кечуа",
  "langName.ro": "румънски",
  "langName.ru": "руски",
  "langName.rw": "киняруанда",
  "langName.sa": "санскрит",
  "langName.se": "саамски (северен)",
  "langName.si": "синхалски",
  "langName.sk": "словашки",
  "langName.sk-sk": "словашки (Словакия)",
  "langName.sl": "словенски",
  "langName.sl-si": "словенски (Словения)",
  "langName.sma": "саамски (южен)",
  "langName.sme": "саамски (северен)",
  "langName.smj": "саамски (луле)",
  "langName.sn": "шона",
  "langName.sr": "сръбски",
  "langName.sr-latn": "сръбски (латиница)",
  "langName.sv": "шведски",
  "langName.sv-se": "шведски (Швеция)",
  "langName.sw": "суахили",
  "langName.sw-ke": "суахили (Кения)",
  "langName.sw-tz": "суахили (Танзания)",
  "langName.syc": "сирийски (класически)",
  "langName.ta": "тамилски",
  "langName.te": "телугу",
  "langName.tg": "таджикски",
  "langName.th": "тайски",
  "langName.th-th": "тайски (Тайланд)",
  "langName.tk": "туркменски",
  "langName.tl": "тагалог",
  "langName.tr": "турски",
  "langName.tr-tr": "турски (Турция)",
  "langName.tt": "татарски",
  "langName.ug": "уйгурски",
  "langName.uk": "украински",
  "langName.ur": "урду",
  "langName.uz": "узбекски",
  "langName.vi": "виетнамски",
  "langName.wo": "волоф",
  "langName.xh": "кхоса",
  "langName.yi": "идиш",
  "langName.yo": "йоруба",
  "langName.yua": "мая (юкатекски)",
  "langName.zh": "китайски",
  "langName.zh-cn": "китайски (опростен)",
  "langName.zh-hans": "китайски (опростен)",
  "langName.zh-hant": "китайски (традиционен)",
  "langName.zh-hk": "китайски (Хонконг)",
  "langName.zh-sg": "китайски (Сингапур)",
  "langName.zh-tw": "китайски (традиционен)",
  "langName.zu": "зулуски",
  "langName.zu-za": "зулуски (Южна Африка)"
});