tinymce.addI18n('bg', {
  "-Language Not Set-": "-Езикът не е зададен-",
  "Choose from list": "Избиране от списък",
  "Choose languages": "Избиране на езици",
  "Choose up to six languages": "Изберете до шест езика",
  "Configure languages": "Конфигуриране на езици",
  "Current language:": "Текущ език:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Въведете валиден код за език без интервали. Или натиснете отказ.",
  "Enter manually": "Въвеждане ръчно",
  "Enter new lang code (e.g., \"en-US\"):": "Въведете нов код за език (напр. \"bg-BG\"):",
  "Indicate current language": "Указване на текущия език",
  "Manually enter language {{number}}:": "Ръчно въвеждане на език {{number}}:",
  "New Language:": "Нов език:",
  "None": "Няма",
  "Other - Enter manually": "Друго - Въвеждане ръчно",
  "Really remove all language markup from the document?": "Наистина ли да премахна цялото езиково маркиране от документа?",
  "Remove All lang markup": "Премахване на цялото езиково маркиране",
  "Remove Language Markup": "Премахване на езиковото маркиране",
  "Remove current lang value": "Премахване на текущата стойност за език",
  "Reveal lang markup": "Показване на езиковото маркиране",
  "Select language {{number}}:": "Избиране на език {{number}}:",
  "Select the document's default language.": "Изберете езика по подразбиране на документа.",
  "Set default document language": "Задаване на език по подразбиране на документа",
  "Set text language": "Задаване на език на текста",
  "langName.af": "африканс",
  "langName.af-za": "африканс",
  "langName.ak": "акан",
  "langName.am": "амхарски",
  "langName.ar": "арабски",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "арабски",
  "langName.az": "азербайджански",
  "langName.be": "беларуски",
  "langName.bg": "български",
  "langName.bg-bg": "български",
  "langName.bho": "боджпури",
  "langName.bm": "бамбара",
  "langName.bn": "бенгалски",
  "langName.bo": "тибетски",
  "langName.bs": "босненски",
  "langName.ca": "каталонски",
  "langName.cop": "коптски",
  "langName.cr": "крии",
  "langName.cs": "чешки",
  "langName.cu": "църковнославянски",
  "langName.cy": "уелски",
  "langName.da": "датски",
  "langName.de": "немски",
  "langName.de-at": "",
  "langName.de-ch": "",
  "langName.de-de": "немски",
  "langName.dv": "дивехи",
  "langName.el": "гръцки",
  "langName.en": "английски",
  "langName.en-au": "австралийски английски",
  "langName.en-ca": "канадски английски",
  "langName.en-gb": "британски английски",
  "langName.en-ie": "Английски (Ирландия)",
  "langName.en-in": "Английски (Индия)",
  "langName.en-tt": "Английски (Тринидад)",
  "langName.en-us": "американски английски",
  "langName.en-za": "Английски (Южна Африка)",
  "langName.eo": "есперанто",
  "langName.es": "испански",
  "langName.es-ar": "Испански (Аржентина)",
  "langName.es-cl": "Испански (Чили)",
  "langName.es-co": "Испански (Колумбия)",
  "langName.es-cr": "",
  "langName.es-es": "испански",
  "langName.es-mx": "Испански (Мексико)",
  "langName.es-pe": "Испански (Перу)",
  "langName.et": "естонски",
  "langName.eu": "баски",
  "langName.fa": "персийски",
  "langName.fa-af": "дари",
  "langName.fa-ir": "персийски",
  "langName.ff": "фула",
  "langName.fi": "фински",
  "langName.fi-fi": "фински",
  "langName.fil": "филипински",
  "langName.fr": "френски",
  "langName.fr-be": "",
  "langName.fr-ca": "Френски (Канада)",
  "langName.fr-ch": "",
  "langName.ga": "ирландски",
  "langName.gl": "галисийски",
  "langName.grc": "древногръцки",
  "langName.ha": "хауса",
  "langName.he": "иврит",
  "langName.he-il": "иврит",
  "langName.hi": "хинди",
  "langName.hr": "хърватски",
  "langName.hr-hr": "хърватски",
  "langName.ht": "хаитянски креолски",
  "langName.hu": "унгарски",
  "langName.hu-hu": "унгарски",
  "langName.hy": "арменски",
  "langName.id": "индонезийски",
  "langName.ig": "игбо",
  "langName.is": "исландски",
  "langName.it": "италиански",
  "langName.it-it": "италиански",
  "langName.iu": "инуктитут",
  "langName.ja": "японски",
  "langName.ja-jp": "японски",
  "langName.ka": "грузински",
  "langName.kab": "кабилски",
  "langName.kk": "казахски",
  "langName.km": "кхмерски",
  "langName.kn": "каннада",
  "langName.ko": "корейски",
  "langName.ko-kr": "корейски",
  "langName.la": "латински",
  "langName.lkt": "лакота",
  "langName.lo": "лаоски",
  "langName.lt": "литовски",
  "langName.lv": "латвийски",
  "langName.mi": "маорски",
  "langName.mn": "монголски",
  "langName.mr": "марати",
  "langName.ms": "малайски",
  "langName.mt": "малтийски",
  "langName.my": "бирмански",
  "langName.nb": "норвежки (букмол)",
  "langName.nb-no": "норвежки (букмол)",
  "langName.ne": "непалски",
  "langName.nl": "нидерландски",
  "langName.nl-be": "фламандски",
  "langName.nn": "норвежки (нюношк)",
  "langName.nv": "навахо",
  "langName.ota": "отомански турски",
  "langName.pa": "пенджабски",
  "langName.peo": "староперсийски",
  "langName.pl": "полски",
  "langName.ps": "пущу",
  "langName.pt": "португалски",
  "langName.pt-br": "португалски",
  "langName.pt-pt": "португалски",
  "langName.qu": "кечуа",
  "langName.ro": "румънски",
  "langName.ru": "руски",
  "langName.rw": "киняруанда",
  "langName.sa": "санскрит",
  "langName.se": "северносаамски",
  "langName.si": "синхалски",
  "langName.sk-sk": "словашки",
  "langName.sl": "словенски",
  "langName.sl-si": "словенски",
  "langName.sma": "южносаамски",
  "langName.sme": "Северен саами",
  "langName.smj": "луле-саамски",
  "langName.sn": "шона",
  "langName.sr": "сръбски",
  "langName.sr-latn": "",
  "langName.sv": "шведски",
  "langName.sv-se": "шведски",
  "langName.sw": "суахили",
  "langName.sw-ke": "суахили",
  "langName.sw-tz": "суахили",
  "langName.syc": "класически сирийски",
  "langName.ta": "тамилски",
  "langName.te": "телугу",
  "langName.tg": "таджикски",
  "langName.th": "тайски",
  "langName.th-th": "тайски",
  "langName.tk": "туркменски",
  "langName.tl": "тагалог",
  "langName.tr": "турски",
  "langName.tr-tr": "турски",
  "langName.tt": "татарски",
  "langName.ug": "уйгурски",
  "langName.uk": "украински",
  "langName.ur": "урду",
  "langName.uz": "узбекски",
  "langName.vi": "виетнамски",
  "langName.wo": "волоф",
  "langName.xh": "кхоса",
  "langName.yi": "идиш",
  "langName.yo": "йоруба",
  "langName.yua": "Юкатекски мая",
  "langName.zh": "китайски",
  "langName.zh-cn": "китайски (опростен)",
  "langName.zh-hans": "китайски (опростен)",
  "langName.zh-hant": "китайски (традиционен)",
  "langName.zh-hk": "Китайски (Хонконг)",
  "langName.zh-sg": "",
  "langName.zh-tw": "китайски (традиционен)",
  "langName.zu": "зулуски",
  "langName.zu-za": "зулуски"
});