tinymce.addI18n("bg_BG", {
  "Current language:": "Текущ език:",
  "Set text language": "Задаване на език на текста",
  "-Language Not Set-": "-Езикът не е зададен-",
  "Choose languages": "Избиране на езици",
  "Remove Language Markup": "Премахване на езиковото маркиране",
  "Remove current lang value": "Премахване на текущата стойност за език",
  "Remove All lang markup": "Премахване на цялото езиково маркиране",
  "Configure languages": "Конфигуриране на езици",
  "Set default document language": "Задаване на език по подразбиране на документа",
  "Reveal lang markup": "Показване на езиковото маркиране",
  "Indicate current language": "Указване на текущия език",
  "Select the document's default language.": "Изберете езика по подразбиране на документа.",
  "Choose from list": "Избиране от списък",
  "Enter manually": "Въвеждане ръчно",
  "None": "Няма",
  "Other - Enter manually": "Друго - Въвеждане ръчно",
  "New Language:": "Нов език:",
  "Enter new lang code (e.g., \"en-US\"):": "Въведете нов код за език (напр. \"bg-BG\"):",
  "Choose up to six languages": "Изберете до шест езика",
  "Select language {{number}}:": "Избиране на език {{number}}:",
  "Manually enter language {{number}}:": "Ръчно въвеждане на език {{number}}:",
  "Really remove all language markup from the document?": "Наистина ли да премахна цялото езиково маркиране от документа?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Въведете валиден код за език без интервали. Или натиснете отказ.",
  "langName.af": "Африканс",
  "langName.ak": "Акан",
  "langName.ar": "Арабски",
  "langName.az": "Азербайджански",
  "langName.bg": "Български",
  "langName.bho": "Бходжпури",
  "langName.bm": "Бамбара",
  "langName.bn": "Бенгалски",
  "langName.bo": "Тибетски",
  "langName.bs": "Босненски",
  "langName.ca": "Каталунски; Валенсийски",
  "langName.cs": "Чешки",
  "langName.cu": "Старобългарски",
  "langName.da": "Датски",
  "langName.de": "Немски",
  "langName.el": "Гръцки",
  "langName.en": "Английски",
  "langName.en-au": "Английски (Австралия)",
  "langName.en-gb": "Английски (Великобритания)",
  "langName.en-in": "Английски (Индия)",
  "langName.en-ie": "Английски (Ирландия)",
  "langName.en-tt": "Английски (Тринидад)",
  "langName.en-us": "Английски (САЩ)",
  "langName.en-za": "Английски (Южна Африка)",
  "langName.es": "Испански",
  "langName.es-ar": "Испански (Аржентина)",
  "langName.es-cl": "Испански (Чили)",
  "langName.es-co": "Испански (Колумбия)",
  "langName.es-mx": "Испански (Мексико)",
  "langName.es-pe": "Испански (Перу)",
  "langName.et": "Естонски",
  "langName.eu": "Баски",
  "langName.fa": "Персийски",
  "langName.fi": "Фински",
  "langName.fr": "Френски",
  "langName.fr-ca": "Френски (Канада)",
  "langName.gl": "Галисийски (Испания)",
  "langName.he": "Иврит",
  "langName.hi": "Хинди",
  "langName.hr": "Хърватски",
  "langName.hu": "Унгарски",
  "langName.id": "Индонезийски",
  "langName.it": "Италиански",
  "langName.ja": "Японски",
  "langName.kk": "Казахски",
  "langName.kn": "Канада",
  "langName.ko": "Корейски",
  "langName.la": "Латински",
  "langName.lkt": "Лакота",
  "langName.mn": "Монголски",
  "langName.mr": "Марати",
  "langName.nb": "Норвежки Букмол",
  "langName.nl": "Холандски",
  "langName.nl-be": "Холандски (Белгия)",
  "langName.nn": "Норвежки Нюношк",
  "langName.pl": "Полски",
  "langName.ps": "Пащо",
  "langName.pt": "Португалски, международен",
  "langName.pt-br": "Португалски (Бразилия)",
  "langName.qu": "Кечуа",
  "langName.ro": "Румънски",
  "langName.ru": "Руски",
  "langName.sa": "Санскрит",
  "langName.sk-sk": "Словашки",
  "langName.sl": "Словенски",
  "langName.sma": "Южен саами",
  "langName.sme": "Северен саами",
  "langName.smj": "Луле саами",
  "langName.sr": "Сръбски",
  "langName.sv": "Шведски",
  "langName.sw": "Суахили",
  "langName.ta": "Тамилски",
  "langName.te": "Телугу",
  "langName.tg": "Таджикски",
  "langName.th": "Тайландски",
  "langName.tr": "Турски",
  "langName.ug": "Уйгурски",
  "langName.uk": "Украински",
  "langName.ur": "Урду",
  "langName.uz": "Узбекски",
  "langName.vi": "Виетнамски",
  "langName.wo": "Волоф",
  "langName.yi": "Идиш",
  "langName.yo": "Йоруба",
  "langName.yua": "Юкатекски мая",
  "langName.zh": "Китайски",
  "langName.zh-cn": "Китайски (Китай)",
  "langName.zh-hk": "Китайски (Хонконг)",
  "langName.zh-tw": "Китайски (Тайван)",
  "langName.zh-hans": "Китайски, опростен",
  "langName.zh-hant": "Китайски, традиционен",
  "langName.zu": "Зулу"
});