tinymce.addI18n('bg_BG', {
  "-Language Not Set-": "-Езикът не е зададен-",
  "Choose from list": "Избиране от списък",
  "Choose languages": "Избиране на езици",
  "Choose up to six languages": "Изберете до шест езика",
  "Configure languages": "Конфигуриране на езици",
  "Current language:": "Текущ език:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Въведете валиден код за език без интервали. Или натиснете отказ.",
  "Enter manually": "Въвеждане ръчно",
  "Enter new lang code (e.g., \"en-US\"):": "Въведете нов код за език (напр. \"bg-BG\"):",
  "Indicate current language": "Указване на текущия език",
  "Manually enter language {{number}}:": "Ръчно въвеждане на език {{number}}:",
  "New Language:": "Нов език:",
  "None": "Няма",
  "Other - Enter manually": "Друго - Въвеждане ръчно",
  "Really remove all language markup from the document?": "Наистина ли да премахна цялото езиково маркиране от документа?",
  "Remove All lang markup": "Премахване на цялото езиково маркиране",
  "Remove Language Markup": "Премахване на езиковото маркиране",
  "Remove current lang value": "Премахване на текущата стойност за език",
  "Reveal lang markup": "Показване на езиковото маркиране",
  "Select language {{number}}:": "Избиране на език {{number}}:",
  "Select the document's default language.": "Изберете езика по подразбиране на документа.",
  "Set default document language": "Задаване на език по подразбиране на документа",
  "Set text language": "Задаване на език на текста",
  "Afrikaans": "африканс",
  "Afrikaans": "африканс (Южна Африка)",
  "Akan": "акан",
  "Amharic": "амхарски",
  "Arabic": "арабски",
  "Arabic (Egypt)": "арабски (Египет)",
  "Arabic (Morocco)": "арабски (Мароко)",
  "Arabic (Saudi Arabia)": "арабски (Саудитска Арабия)",
  "Azerbaijani": "азербайджански",
  "Belarusian": "беларуски",
  "Bulgarian": "български",
  "Bulgarian (Bulgaria)": "български (България)",
  "Bhojpuri": "боджпури",
  "Bambara": "бамбара",
  "Bangla": "бенгалски",
  "Tibetan": "тибетски",
  "Bosnian": "босненски",
  "Catalan": "каталонски",
  "Coptic": "коптски",
  "Cree": "крии",
  "Czech": "чешки",
  "Church Slavic": "църковнославянски",
  "Welsh": "уелски",
  "Danish": "датски",
  "German": "немски",
  "German (Austria)": "немски (Австрия)",
  "German (Switzerland)": "немски (Швейцария)",
  "German (Germany)": "немски (Германия)",
  "Divehi": "дивехи",
  "Greek": "гръцки",
  "English": "английски",
  "English (Australia)": "английски (Австралия)",
  "English (Canada)": "английски (Канада)",
  "English (United Kingdom)": "английски (Обединено кралство)",
  "English (Ireland)": "английски (Ирландия)",
  "English (India)": "английски (Индия)",
  "English (Trinidad)": "английски (Тринидад)",
  "English (United States)": "английски (Съединени щати)",
  "English (South Africa)": "английски (Южна Африка)",
  "Esperanto": "есперанто",
  "Spanish": "испански",
  "Spanish (Argentina)": "испански (Аржентина)",
  "Spanish (Chile)": "испански (Чили)",
  "Spanish (Colombia)": "испански (Колумбия)",
  "Spanish (Costa Rica)": "испански (Коста Рика)",
  "Spanish (Spain)": "испански (Испания)",
  "Spanish (Mexico)": "испански (Мексико)",
  "Spanish (Peru)": "испански (Перу)",
  "Estonian": "естонски",
  "Basque": "баски",
  "Persian": "персийски",
  "Dari": "дари",
  "Persian (Iran)": "персийски (Иран)",
  "Fula": "фула",
  "Finnish": "фински",
  "Finnish (Finland)": "фински (Финландия)",
  "Filipino": "филипински",
  "French": "френски",
  "French (Belgium)": "френски (Белгия)",
  "French (Canada)": "френски (Канада)",
  "French (Switzerland)": "френски (Швейцария)",
  "Irish": "ирландски",
  "Galician": "галисийски",
  "Greek (Ancient)": "древногръцки",
  "Hausa": "хауса",
  "Hebrew": "иврит",
  "Hebrew (Israel)": "иврит (Израел)",
  "Hindi": "хинди",
  "Croatian": "хърватски",
  "Croatian (Croatia)": "хърватски (Хърватия)",
  "Haitian Creole": "хаитянски креолски",
  "Hungarian": "унгарски",
  "Hungarian (Hungary)": "унгарски (Унгария)",
  "Armenian": "арменски",
  "Indonesian": "индонезийски",
  "Igbo": "игбо",
  "Icelandic": "исландски",
  "Italian": "италиански",
  "Italian (Italy)": "италиански (Италия)",
  "Inuktitut": "инуктитут",
  "Japanese": "японски",
  "Japanese (Japan)": "японски (Япония)",
  "Georgian": "грузински",
  "Kabyle": "кабилски",
  "Kazakh": "казахски",
  "Khmer": "кхмерски",
  "Kannada": "каннада",
  "Korean": "корейски",
  "Korean (Korea)": "корейски (Корея)",
  "Latin": "латински",
  "Lakota": "лакота",
  "Lao": "лаоски",
  "Lithuanian": "литовски",
  "Latvian": "латвийски",
  "Māori": "маорски",
  "Mongolian": "монголски",
  "Marathi": "марати",
  "Malay": "малайски",
  "Maltese": "малтийски",
  "Burmese": "бирмански",
  "Norwegian (Bokmål)": "норвежки (букмол)",
  "Norwegian (Bokmål, Norway)": "норвежки (букмол, Норвегия)",
  "Nepali": "непалски",
  "Dutch": "нидерландски",
  "Flemish": "фламандски",
  "Norwegian (Nynorsk)": "норвежки (нюношк)",
  "Navajo": "навахо",
  "Turkish (Ottoman)": "турски (отомански)",
  "Punjabi": "пенджабски",
  "Persian (Old)": "персийски (старо)",
  "Polish": "полски",
  "Pashto": "пущу",
  "Portuguese": "португалски",
  "Portuguese (Brazil)": "португалски (Бразилия)",
  "Portuguese (Portugal)": "португалски (Португалия)",
  "Quechua": "кечуа",
  "Romanian": "румънски",
  "Russian": "руски",
  "Kinyarwanda": "киняруанда",
  "Sanskrit": "санскрит",
  "Sami (Northern)": "саамски (северен)",
  "Sinhala": "синхалски",
  "Slovak": "словашки",
  "Slovak (Slovakia)": "словашки (Словакия)",
  "Slovenian": "словенски",
  "Slovenian (Slovenia)": "словенски (Словения)",
  "Sami (Southern)": "саамски (южен)",
  "Sami (Northern)": "саамски (северен)",
  "Sami (Lule)": "саамски (луле)",
  "Shona": "шона",
  "Serbian": "сръбски",
  "Serbian (Latin)": "сръбски (латиница)",
  "Swedish": "шведски",
  "Swedish (Sweden)": "шведски (Швеция)",
  "Swahili": "суахили",
  "Swahili (Kenya)": "суахили (Кения)",
  "Swahili (Tanzania)": "суахили (Танзания)",
  "Syriac (Classical)": "сирийски (класически)",
  "Tamil": "тамилски",
  "Telugu": "телугу",
  "Tajik": "таджикски",
  "Thai": "тайски",
  "Thai (Thailand)": "тайски (Тайланд)",
  "Turkmen": "туркменски",
  "Tagalog": "тагалог",
  "Turkish": "турски",
  "Turkish (Turkey)": "турски (Турция)",
  "Tatar": "татарски",
  "Uyghur": "уйгурски",
  "Ukrainian": "украински",
  "Urdu": "урду",
  "Uzbek": "узбекски",
  "Vietnamese": "виетнамски",
  "Wolof": "волоф",
  "Xhosa": "кхоса",
  "Yiddish": "идиш",
  "Yoruba": "йоруба",
  "Maya (Yucatec)": "мая (юкатекски)",
  "Chinese": "китайски",
  "Chinese (Simplified)": "китайски (опростен)",
  "Chinese (Simplified)": "китайски (опростен)",
  "Chinese (Traditional)": "китайски (традиционен)",
  "Chinese (Hong Kong)": "китайски (Хонконг)",
  "Chinese (Singapore)": "китайски (Сингапур)",
  "Chinese (Traditional)": "китайски (традиционен)",
  "Zulu": "зулуски",
  "Zulu": "зулуски (Южна Африка)"
});