tinymce.addI18n("cs", {
  "-Language Not Set-": "-Jazyk není nastaven-",
  "Choose from list": "Vybrat ze seznamu",
  "Choose languages": "Vybrat jazyky",
  "Choose up to six languages": "Vyberte až šest jazyků",
  "Configure languages": "Konfigurovat jazyky",
  "Current language:": "Aktuální jazyk:",
  "Enter a valid language code with no spaces. Or, press cancel.":
    "Zadejte platný kód jazyka bez mezer. Nebo stiskněte zrušit.",
  "Enter manually": "Zadat ručně",
  'Enter new lang code (e.g., "en-US"):':
    'Zadejte nový kód jazyka (např. "cs-CZ"):',
  "Indicate current language": "Označit aktuální jazyk",
  "Manually enter language {{number}}:": "Ručně zadat jazyk {{number}}:",
  "New Language:": "Nový jazyk:",
  None: "Žádný",
  "Other - Enter manually": "Jiný - Zadat ručně",
  "Really remove all language markup from the document?":
    "Opravdu odstranit všechny jazykové značky z dokumentu?",
  "Remove All lang markup": "Odstranit všechny jazykové značky",
  "Remove Language Markup": "Odstranit jazykové značky",
  "Remove current lang value": "Odstranit aktuální hodnotu jazyka",
  "Reveal lang markup": "Zobrazit jazykové značky",
  "Select language {{number}}:": "Vybrat jazyk {{number}}:",
  "Select the document's default language.": "Vyberte výchozí jazyk dokumentu.",
  "Set default document language": "Nastavit výchozí jazyk dokumentu",
  "Set text language": "Nastavit jazyk textu",
  "langName.af": "afrikánština",
  "langName.af-za": "afrikánština",
  "langName.ak": "akanština",
  "langName.am": "amharština",
  "langName.ar": "arabština",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "arabština",
  "langName.az": "ázerbájdžánština",
  "langName.be": "běloruština",
  "langName.bg": "bulharština",
  "langName.bg-bg": "bulharština",
  "langName.bho": "bhódžpurština",
  "langName.bm": "bambarština",
  "langName.bn": "bengálština",
  "langName.bo": "tibetština",
  "langName.bs": "bosenština",
  "langName.ca": "katalánština",
  "langName.cop": "koptština",
  "langName.cr": "kríjština",
  "langName.cs": "čeština",
  "langName.cu": "staroslověnština",
  "langName.cy": "velština",
  "langName.da": "dánština",
  "langName.de": "němčina",
  "langName.de-at": "",
  "langName.de-ch": "němčina standardní (Švýcarsko)",
  "langName.de-de": "němčina",
  "langName.dv": "maledivština",
  "langName.el": "řečtina",
  "langName.en": "angličtina",
  "langName.en-au": "Angličtina (Austrálie)",
  "langName.en-ca": "",
  "langName.en-gb": "angličtina (Velká Británie)",
  "langName.en-ie": "Angličtina (Irsko)",
  "langName.en-in": "Angličtina (Indie)",
  "langName.en-tt": "Angličtina (Trinidad)",
  "langName.en-us": "angličtina (USA)",
  "langName.en-za": "Angličtina (Jižní Afrika)",
  "langName.eo": "esperanto",
  "langName.es": "španělština",
  "langName.es-ar": "Španělština (Argentina)",
  "langName.es-cl": "Španělština (Chile)",
  "langName.es-co": "Španělština (Kolumbie)",
  "langName.es-cr": "",
  "langName.es-es": "španělština (Evropa)",
  "langName.es-mx": "Španělština (Mexiko)",
  "langName.es-pe": "Španělština (Peru)",
  "langName.et": "estonština",
  "langName.eu": "baskičtina",
  "langName.fa": "perština",
  "langName.fa-af": "darí",
  "langName.fa-ir": "perština",
  "langName.ff": "fulbština",
  "langName.fi": "finština",
  "langName.fi-fi": "finština",
  "langName.fil": "filipínština",
  "langName.fr": "francouzština",
  "langName.fr-be": "",
  "langName.fr-ca": "Francouzština (Kanada)",
  "langName.fr-ch": "",
  "langName.ga": "irština",
  "langName.gl": "galicijština",
  "langName.grc": "starořečtina",
  "langName.ha": "hauština",
  "langName.he": "hebrejština",
  "langName.he-il": "hebrejština",
  "langName.hi": "hindština",
  "langName.hr": "chorvatština",
  "langName.hr-hr": "chorvatština",
  "langName.ht": "haitština",
  "langName.hu": "maďarština",
  "langName.hu-hu": "maďarština",
  "langName.hy": "arménština",
  "langName.id": "indonéština",
  "langName.ig": "igboština",
  "langName.is": "islandština",
  "langName.it": "italština",
  "langName.it-it": "italština",
  "langName.iu": "inuktitutština",
  "langName.ja": "japonština",
  "langName.ja-jp": "japonština",
  "langName.ka": "gruzínština",
  "langName.kab": "kabylština",
  "langName.kk": "kazaština",
  "langName.km": "khmérština",
  "langName.kn": "kannadština",
  "langName.ko": "korejština",
  "langName.ko-kr": "korejština",
  "langName.la": "latina",
  "langName.lkt": "lakotština",
  "langName.lo": "laoština",
  "langName.lt": "litevština",
  "langName.lv": "lotyština",
  "langName.mi": "maorština",
  "langName.mn": "mongolština",
  "langName.mr": "maráthština",
  "langName.ms": "malajština",
  "langName.mt": "maltština",
  "langName.my": "barmština",
  "langName.nb": "norština (bokmål)",
  "langName.nb-no": "norština (bokmål)",
  "langName.ne": "nepálština",
  "langName.nl": "nizozemština",
  "langName.nl-be": "vlámština",
  "langName.nn": "norština (nynorsk)",
  "langName.nv": "navažština",
  "langName.ota": "turečtina (osmanská)",
  "langName.pa": "paňdžábština",
  "langName.peo": "staroperština",
  "langName.pl": "polština",
  "langName.ps": "paštština",
  "langName.pt": "portugalština",
  "langName.pt-br": "portugalština",
  "langName.pt-pt": "portugalština (Evropa)",
  "langName.qu": "kečuánština",
  "langName.ro": "rumunština",
  "langName.ru": "ruština",
  "langName.rw": "kiňarwandština",
  "langName.sa": "sanskrt",
  "langName.se": "sámština (severní)",
  "langName.si": "sinhálština",
  "langName.sk-sk": "slovenština",
  "langName.sl": "slovinština",
  "langName.sl-si": "slovinština",
  "langName.sma": "sámština (jižní)",
  "langName.sme": "Severní sámština",
  "langName.smj": "sámština (lulejská)",
  "langName.sn": "šonština",
  "langName.sr": "srbština",
  "langName.sr-latn": "",
  "langName.sv": "švédština",
  "langName.sv-se": "švédština",
  "langName.sw": "svahilština",
  "langName.sw-ke": "svahilština",
  "langName.sw-tz": "svahilština",
  "langName.syc": "syrština (klasická)",
  "langName.ta": "tamilština",
  "langName.te": "telugština",
  "langName.tg": "tádžičtina",
  "langName.th": "thajština",
  "langName.th-th": "thajština",
  "langName.tk": "turkmenština",
  "langName.tl": "tagalog",
  "langName.tr": "turečtina",
  "langName.tr-tr": "turečtina",
  "langName.tt": "tatarština",
  "langName.ug": "ujgurština",
  "langName.uk": "ukrajinština",
  "langName.ur": "urdština",
  "langName.uz": "uzbečtina",
  "langName.vi": "vietnamština",
  "langName.wo": "wolofština",
  "langName.xh": "xhoština",
  "langName.yi": "jidiš",
  "langName.yo": "jorubština",
  "langName.yua": "Yukatéčtina maya",
  "langName.zh": "čínština",
  "langName.zh-cn": "čínština (zjednodušená)",
  "langName.zh-hans": "čínština (zjednodušená)",
  "langName.zh-hant": "Čínština, tradiční",
  "langName.zh-hk": "Čínština (Hongkong)",
  "langName.zh-sg": "",
  "langName.zh-tw": "Čínština (Tchaj-wan)",
  "langName.zu": "zuluština",
  "langName.zu-za": "zuluština",
});
