tinymce.addI18n("cs", {
  "Current language:": "Aktuální jazyk:",
  "Set text language": "Nastavit jazyk textu",
  "-Language Not Set-": "-Jazyk není nastaven-",
  "Choose languages": "Vybrat jazyky",
  "Remove Language Markup": "Odstranit jazykové značky",
  "Remove current lang value": "Odstranit aktuální hodnotu jazyka",
  "Remove All lang markup": "Odstranit všechny jazykové značky",
  "Configure languages": "Konfigurovat jazyky",
  "Set default document language": "Nastavit výchozí jazyk dokumentu",
  "Reveal lang markup": "Zobrazit jazykové značky",
  "Indicate current language": "Označit aktuální jazyk",
  "Select the document's default language.": "Vyberte výchozí jazyk dokumentu.",
  "Choose from list": "Vybrat ze seznamu",
  "Enter manually": "Zadat ručně",
  "None": "Žádný",
  "Other - Enter manually": "Jiný - Zadat ručně",
  "New Language:": "Nový jazyk:",
  "Enter new lang code (e.g., \"en-US\"):": "Zadejte nový kód jazyka (např. \"cs-CZ\"):",
  "Choose up to six languages": "Vyberte až šest jazyků",
  "Select language {{number}}:": "Vybrat jazyk {{number}}:",
  "Manually enter language {{number}}:": "Ručně zadat jazyk {{number}}:",
  "Really remove all language markup from the document?": "Opravdu odstranit všechny jazykové značky z dokumentu?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Zadejte platný kód jazyka bez mezer. Nebo stiskněte zrušit.",
  "langName.af": "Afrikánština",
  "langName.ak": "Akanština",
  "langName.ar": "Arabština",
  "langName.az": "Ázerbájdžánština",
  "langName.bg": "Bulharština",
  "langName.bho": "Bhódžpurština",
  "langName.bm": "Bambarština",
  "langName.bn": "Bengálština",
  "langName.bo": "Tibetština",
  "langName.bs": "Bosenština",
  "langName.ca": "Katalánština; Valencijština",
  "langName.cs": "Čeština",
  "langName.cu": "Staroslověnština",
  "langName.da": "Dánština",
  "langName.de": "Němčina",
  "langName.el": "Řečtina",
  "langName.en": "Angličtina",
  "langName.en-au": "Angličtina (Austrálie)",
  "langName.en-gb": "Angličtina (Velká Británie)",
  "langName.en-in": "Angličtina (Indie)",
  "langName.en-ie": "Angličtina (Irsko)",
  "langName.en-tt": "Angličtina (Trinidad)",
  "langName.en-us": "Angličtina (USA)",
  "langName.en-za": "Angličtina (Jižní Afrika)",
  "langName.es": "Španělština",
  "langName.es-ar": "Španělština (Argentina)",
  "langName.es-cl": "Španělština (Chile)",
  "langName.es-co": "Španělština (Kolumbie)",
  "langName.es-mx": "Španělština (Mexiko)",
  "langName.es-pe": "Španělština (Peru)",
  "langName.et": "Estonština",
  "langName.eu": "Baskičtina",
  "langName.fa": "Perština",
  "langName.fi": "Finština",
  "langName.fr": "Francouzština",
  "langName.fr-ca": "Francouzština (Kanada)",
  "langName.gl": "Galicijština (Španělsko)",
  "langName.he": "Hebrejština",
  "langName.hi": "Hindština",
  "langName.hr": "Chorvatština",
  "langName.hu": "Maďarština",
  "langName.id": "Indonéština",
  "langName.it": "Italština",
  "langName.ja": "Japonština",
  "langName.kk": "Kazaština",
  "langName.kn": "Kannadština",
  "langName.ko": "Korejština",
  "langName.la": "Latina",
  "langName.lkt": "Lakotština",
  "langName.mn": "Mongolština",
  "langName.mr": "Maráthština",
  "langName.nb": "Norština Bokmål",
  "langName.nl": "Nizozemština",
  "langName.nl-be": "Nizozemština (Belgie)",
  "langName.nn": "Norština Nynorsk",
  "langName.pl": "Polština",
  "langName.ps": "Paštština",
  "langName.pt": "Portugalština, mezinárodní",
  "langName.pt-br": "Portugalština (Brazílie)",
  "langName.qu": "Kečuánština",
  "langName.ro": "Rumunština",
  "langName.ru": "Ruština",
  "langName.sa": "Sanskrt",
  "langName.sk-sk": "Slovenština",
  "langName.sl": "Slovinština",
  "langName.sma": "Jižní sámština",
  "langName.sme": "Severní sámština",
  "langName.smj": "Lule sámština",
  "langName.sr": "Srbština",
  "langName.sv": "Švédština",
  "langName.sw": "Svahilština",
  "langName.ta": "Tamilština",
  "langName.te": "Telugština",
  "langName.tg": "Tádžičtina",
  "langName.th": "Thajština",
  "langName.tr": "Turečtina",
  "langName.ug": "Ujgurština",
  "langName.uk": "Ukrajinština",
  "langName.ur": "Urdština",
  "langName.uz": "Uzbečtina",
  "langName.vi": "Vietnamština",
  "langName.wo": "Wolofština",
  "langName.yi": "Jidiš",
  "langName.yo": "Jorubština",
  "langName.yua": "Yukatéčtina maya",
  "langName.zh": "Čínština",
  "langName.zh-cn": "Čínština (Čína)",
  "langName.zh-hk": "Čínština (Hongkong)",
  "langName.zh-tw": "Čínština (Tchaj-wan)",
  "langName.zh-hans": "Čínština, zjednodušená",
  "langName.zh-hant": "Čínština, tradiční",
  "langName.zu": "Zuluština"
});