tinymce.addI18n("cs", {
  "-Language Not Set-": "-Jazyk není nastaven-",
  "Choose from list": "Vybrat ze seznamu",
  "Choose languages": "Vybrat jazyky",
  "Choose up to six languages": "Vyberte až šest jazyků",
  "Configure languages": "Konfigurovat jazyky",
  "Current language:": "Aktuální jazyk:",
  "Enter a valid language code with no spaces. Or, press cancel.":"Zadejte platný kód jazyka bez mezer. Nebo stiskněte zrušit.",
  "Enter manually": "Zadat ručně",
  'Enter new lang code (e.g., "en-US"):': 'Zadejte nový kód jazyka (např. "cs-CZ"):',
  "Indicate current language": "Označit aktuální jazyk",
  "Manually enter language {{number}}:": "Ručně zadat jazyk {{number}}:",
  "New Language:": "Nový jazyk:",
  "None": "Žádný",
  "Other - Enter manually": "Jiný - Zadat ručně",
  "Really remove all language markup from the document?": "Opravdu odstranit všechny jazykové značky z dokumentu?",
  "Remove All lang markup": "Odstranit všechny jazykové značky",
  "Remove Language Markup": "Odstranit jazykové značky",
  "Remove current lang value": "Odstranit aktuální hodnotu jazyka",
  "Reveal lang markup": "Zobrazit jazykové značky",
  "Select language {{number}}:": "Vybrat jazyk {{number}}:",
  "Select the document's default language.": "Vyberte výchozí jazyk dokumentu.",
  "Set default document language": "Nastavit výchozí jazyk dokumentu",
  "Set text language": "Nastavit jazyk textu",
  "langName.af": "afrikánština",
  "langName.af-za": "afrikánština",
  "langName.ak": "akanština",
  "langName.am": "amharština",
  "langName.ar": "arabština",
  "langName.ar-eg": "arabština (Egypt)",
  "langName.ar-ma": "arabština (Maroko)",
  "langName.ar-sa": "arabština (Saúdská Arábie)",
  "langName.az": "ázerbájdžánština",
  "langName.be": "běloruština",
  "langName.bg": "bulharština",
  "langName.bg-bg": "bulharština",
  "langName.bho": "bhódžpurština",
  "langName.bm": "bambarština",
  "langName.bn": "bengálština",
  "langName.bo": "tibetština",
  "langName.bs": "bosenština",
  "langName.ca": "katalánština",
  "langName.cop": "koptština",
  "langName.cr": "kríjština",
  "langName.cs": "čeština",
  "langName.cu": "staroslověnština",
  "langName.cy": "velština",
  "langName.da": "dánština",
  "langName.de": "němčina",
  "langName.de-at": "němčina (Rakousko)",
  "langName.de-ch": "němčina (Švýcarsko)",
  "langName.de-de": "němčina (Německo)",
  "langName.dv": "maledivština",
  "langName.el": "řečtina",
  "langName.en": "angličtina",
  "langName.en-au": "angličtina (Austrálie)",
  "langName.en-ca": "angličtina (Kanada)",
  "langName.en-gb": "angličtina (Velká Británie)",
  "langName.en-ie": "angličtina (Irsko)",
  "langName.en-in": "angličtina (Indie)",
  "langName.en-tt": "angličtina (Trinidad)",
  "langName.en-us": "angličtina (USA)",
  "langName.en-za": "angličtina (Jižní Afrika)",
  "langName.eo": "esperanto",
  "langName.es": "španělština",
  "langName.es-ar": "španělština (Argentina)",
  "langName.es-cl": "španělština (Chile)",
  "langName.es-co": "španělština (Kolumbie)",
  "langName.es-cr": "španělština (Kostarika)",
  "langName.es-es": "španělština (Španělsko)",
  "langName.es-mx": "španělština (Mexiko)",
  "langName.es-pe": "španělština (Peru)",
  "langName.et": "estonština",
  "langName.eu": "baskičtina",
  "langName.fa": "perština",
  "langName.fa-af": "darí",
  "langName.fa-ir": "perština (Írán)",
  "langName.ff": "fulbština",
  "langName.fi": "finština",
  "langName.fi-fi": "finština",
  "langName.fil": "filipínština",
  "langName.fr": "francouzština",
  "langName.fr-be": "francouzština (Belgie)",
  "langName.fr-ca": "francouzština (Kanada)",
  "langName.fr-ch": "francouzština (Švýcarsko)",
  "langName.ga": "irština",
  "langName.gl": "galicijština",
  "langName.grc": "starořečtina",
  "langName.ha": "hauština",
  "langName.he": "hebrejština",
  "langName.he-il": "hebrejština",
  "langName.hi": "hindština",
  "langName.hr": "chorvatština",
  "langName.hr-hr": "chorvatština",
  "langName.ht": "haitština",
  "langName.hu": "maďarština",
  "langName.hu-hu": "maďarština",
  "langName.hy": "arménština",
  "langName.id": "indonéština",
  "langName.ig": "igboština",
  "langName.is": "islandština",
  "langName.it": "italština",
  "langName.it-it": "italština",
  "langName.iu": "inuktitutština",
  "langName.ja": "japonština",
  "langName.ja-jp": "japonština",
  "langName.ka": "gruzínština",
  "langName.kab": "kabylština",
  "langName.kk": "kazaština",
  "langName.km": "khmérština",
  "langName.kn": "kannadština",
  "langName.ko": "korejština",
  "langName.ko-kr": "korejština",
  "langName.la": "latina",
  "langName.lkt": "lakotština",
  "langName.lo": "laoština",
  "langName.lt": "litevština",
  "langName.lv": "lotyština",
  "langName.mi": "maorština",
  "langName.mn": "mongolština",
  "langName.mr": "maráthština",
  "langName.ms": "malajština",
  "langName.mt": "maltština",
  "langName.my": "barmština",
  "langName.nb": "norština (bokmål)",
  "langName.nb-no": "norština (bokmål)",
  "langName.ne": "nepálština",
  "langName.nl": "nizozemština",
  "langName.nl-be": "vlámština",
  "langName.nn": "norština (nynorsk)",
  "langName.nv": "navažština",
  "langName.ota": "turečtina (osmanská)",
  "langName.pa": "paňdžábština",
  "langName.peo": "staroperština",
  "langName.pl": "polština",
  "langName.ps": "paštština",
  "langName.pt": "portugalština",
  "langName.pt-br": "portugalština (Brazílie)",
  "langName.pt-pt": "portugalština (Portugalsko)",
  "langName.qu": "kečuánština",
  "langName.ro": "rumunština",
  "langName.ru": "ruština",
  "langName.rw": "kiňarwandština",
  "langName.sa": "sanskrt",
  "langName.se": "sámština (severní)",
  "langName.si": "sinhálština",
  "langName.sk-sk": "slovenština",
  "langName.sl": "slovinština",
  "langName.sl-si": "slovinština",
  "langName.sma": "sámština (jižní)",
  "langName.sme": "sámština (severní)",
  "langName.smj": "sámština (lulejská)",
  "langName.sn": "šonština",
  "langName.sr": "srbština",
  "langName.sr-latn": "srbština (latinka)",
  "langName.sv": "švédština",
  "langName.sv-se": "švédština",
  "langName.sw": "svahilština",
  "langName.sw-ke": "svahilština (Keňa)",
  "langName.sw-tz": "svahilština (Tanzanie)",
  "langName.syc": "syrština (klasická)",
  "langName.ta": "tamilština",
  "langName.te": "telugština",
  "langName.tg": "tádžičtina",
  "langName.th": "thajština",
  "langName.th-th": "thajština",
  "langName.tk": "turkmenština",
  "langName.tl": "tagalog",
  "langName.tr": "turečtina",
  "langName.tr-tr": "turečtina",
  "langName.tt": "tatarština",
  "langName.ug": "ujgurština",
  "langName.uk": "ukrajinština",
  "langName.ur": "urdština",
  "langName.uz": "uzbečtina",
  "langName.vi": "vietnamština",
  "langName.wo": "wolofština",
  "langName.xh": "xhoština",
  "langName.yi": "jidiš",
  "langName.yo": "jorubština",
  "langName.yua": "mayština (yukatéčtina)",
  "langName.zh": "čínština",
  "langName.zh-cn": "čínština (zjednodušená)",
  "langName.zh-hans": "čínština (zjednodušená)",
  "langName.zh-hant": "čínština (tradiční)",
  "langName.zh-hk": "čínština (Hongkong)",
  "langName.zh-sg": "čínština (Singapur)",
  "langName.zh-tw": "čínština (Tchaj-wan)",
  "langName.zu": "zuluština",
  "langName.zu-za": "zuluština",
});