tinymce.addI18n('cy', {
  "-Language Not Set-": "-Iaith heb ei gosod-",
  "Choose from list": "Dewis o'r rhestr",
  "Choose languages": "Dewis ieithoedd",
  "Choose up to six languages": "Dewis hyd at chwe iaith",
  "Configure languages": "Ffurfweddu ieithoedd",
  "Current language:": "Iaith bresennol:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Rhoi cod iaith dilys heb fylchau. Neu, pwyswch canslo.",
  "Enter manually": "Rhoi i mewn â llaw",
  "Enter new lang code (e.g., \"en-US\"):": "Rhoi cod iaith newydd (e.e., \"cy-GB\"):",
  "Indicate current language": "Nodi'r iaith bresennol",
  "Manually enter language {{number}}:": "Rhoi iaith {{number}} i mewn â llaw:",
  "New Language:": "Iaith newydd:",
  "None": "Dim",
  "Other - Enter manually": "Arall - Rhoi i mewn â llaw",
  "Really remove all language markup from the document?": "Wir dynnu'r holl farcio iaith o'r ddogfen?",
  "Remove All lang markup": "Tynnu'r holl farcio iaith",
  "Remove Language Markup": "Tynnu marcio iaith",
  "Remove current lang value": "Tynnu gwerth iaith bresennol",
  "Reveal lang markup": "Datgelu marcio iaith",
  "Select language {{number}}:": "Dewis iaith {{number}}:",
  "Select the document's default language.": "Dewis iaith rhagosodedig y ddogfen.",
  "Set default document language": "Gosod iaith rhagosodedig y ddogfen",
  "Set text language": "Gosod iaith y testun",
  "langName.af": "affricaneg",
  "langName.af-za": "affricaneg",
  "langName.ak": "acaneg",
  "langName.am": "amhareg",
  "langName.ar": "arabeg",
  "langName.ar-eg": "arabeg (Aifft)",
  "langName.ar-ma": "arabeg (Moroco)",
  "langName.ar-sa": "arabeg (Saudi Arabia)",
  "langName.az": "aserbaijaneg",
  "langName.be": "belarwseg",
  "langName.bg": "bwlgareg",
  "langName.bg-bg": "bwlgareg",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambareg",
  "langName.bn": "bengaleg",
  "langName.bo": "tibeteg",
  "langName.bs": "bosnieg",
  "langName.ca": "catalaneg",
  "langName.cop": "copteg",
  "langName.cr": "cri",
  "langName.cs": "tsieceg",
  "langName.cu": "hen slafoneg",
  "langName.cy": "cymraeg",
  "langName.da": "daneg",
  "langName.de": "almaeneg",
  "langName.de-at": "almaeneg Awstria",
  "langName.de-ch": "almaeneg safonol y Swistir",
  "langName.de-de": "almaeneg (Almaen)",
  "langName.dv": "difehi",
  "langName.el": "groeg",
  "langName.en": "saesneg",
  "langName.en-au": "saesneg Awstralia",
  "langName.en-ca": "saesneg Canada",
  "langName.en-gb": "saesneg Prydain",
  "langName.en-ie": "saesneg (Iwerddon)",
  "langName.en-in": "saesneg (India)",
  "langName.en-tt": "saesneg (Trinidad)",
  "langName.en-us": "saesneg America",
  "langName.en-za": "saesneg (De Affrica)",
  "langName.eo": "esperanto",
  "langName.es": "sbaeneg",
  "langName.es-ar": "sbaeneg (Ariannin)",
  "langName.es-cl": "sbaeneg (Chile)",
  "langName.es-co": "sbaeneg (Colombia)",
  "langName.es-cr": "sbaeneg (Costa Rica)",
  "langName.es-es": "sbaeneg Ewrop",
  "langName.es-mx": "sbaeneg Mecsico",
  "langName.es-pe": "sbaeneg (Periw)",
  "langName.et": "estoneg",
  "langName.eu": "basgeg",
  "langName.fa": "perseg",
  "langName.fa-af": "dari",
  "langName.fa-ir": "perseg (Iran)",
  "langName.ff": "ffwla",
  "langName.fi": "ffinneg",
  "langName.fi-fi": "ffinneg",
  "langName.fil": "ffilipineg",
  "langName.fr": "ffrangeg",
  "langName.fr-be": "ffrangeg (Gwlad Belg)",
  "langName.fr-ca": "ffrangeg Canada",
  "langName.fr-ch": "ffrangeg y Swistir",
  "langName.ga": "gwyddeleg",
  "langName.gl": "galisieg",
  "langName.grc": "hen roeg",
  "langName.ha": "hawsa",
  "langName.he": "hebraeg",
  "langName.he-il": "hebraeg",
  "langName.hi": "hindi",
  "langName.hr": "croateg",
  "langName.hr-hr": "croateg",
  "langName.ht": "creol Haiti",
  "langName.hu": "hwngareg",
  "langName.hu-hu": "hwngareg",
  "langName.hy": "armeneg",
  "langName.id": "indoneseg",
  "langName.ig": "igbo",
  "langName.is": "islandeg",
  "langName.it": "eidaleg",
  "langName.it-it": "eidaleg",
  "langName.iu": "inwctitwt",
  "langName.ja": "japaneeg",
  "langName.ja-jp": "japaneeg",
  "langName.ka": "georgeg",
  "langName.kab": "cabileg",
  "langName.kk": "casacheg",
  "langName.km": "chmereg",
  "langName.kn": "kannada",
  "langName.ko": "coreeg",
  "langName.ko-kr": "coreeg",
  "langName.la": "lladin",
  "langName.lkt": "lakota",
  "langName.lo": "laoeg",
  "langName.lt": "lithwaneg",
  "langName.lv": "latfieg",
  "langName.mi": "māori",
  "langName.mn": "mongoleg",
  "langName.mr": "marathi",
  "langName.ms": "maleieg",
  "langName.mt": "malteg",
  "langName.my": "byrmaneg",
  "langName.nb": "norwyeg bokmål",
  "langName.nb-no": "norwyeg bokmål",
  "langName.ne": "nepaleg",
  "langName.nl": "iseldireg",
  "langName.nl-be": "fflemeg",
  "langName.nn": "norwyeg nynorsk",
  "langName.nv": "nafaho",
  "langName.ota": "tyrceg otoman",
  "langName.pa": "pwnjabeg",
  "langName.peo": "hen bersieg",
  "langName.pl": "pwyleg",
  "langName.ps": "pashto",
  "langName.pt": "portiwgaleg",
  "langName.pt-br": "portiwgaleg Brasil",
  "langName.pt-pt": "portiwgaleg Ewrop",
  "langName.qu": "quechua",
  "langName.ro": "rwmaneg",
  "langName.ru": "rwseg",
  "langName.rw": "ciniarŵandeg",
  "langName.sa": "sansgrit",
  "langName.se": "sami gogleddol",
  "langName.si": "sinhaleg",
  "langName.sk-sk": "slofaceg",
  "langName.sl": "slofeneg",
  "langName.sl-si": "slofeneg",
  "langName.sma": "sami deheuol",
  "langName.sme": "sami gogleddol",
  "langName.smj": "sami lwle",
  "langName.sn": "shona",
  "langName.sr": "serbeg",
  "langName.sr-latn": "serbeg (lladin)",
  "langName.sv": "swedeg",
  "langName.sv-se": "swedeg",
  "langName.sw": "swahili",
  "langName.sw-ke": "swahili (Kenya)",
  "langName.sw-tz": "swahili (Tanzania)",
  "langName.syc": "hen syrieg",
  "langName.ta": "tamileg",
  "langName.te": "telugu",
  "langName.tg": "tajiceg",
  "langName.th": "thai",
  "langName.th-th": "thai",
  "langName.tk": "tyrcmeneg",
  "langName.tl": "tagalog",
  "langName.tr": "tyrceg",
  "langName.tr-tr": "tyrceg",
  "langName.tt": "tatareg",
  "langName.ug": "uighur",
  "langName.uk": "wcreineg",
  "langName.ur": "wrdw",
  "langName.uz": "wsbeceg",
  "langName.vi": "fietnameg",
  "langName.wo": "woloff",
  "langName.xh": "xhosa",
  "langName.yi": "iddew-almaeneg",
  "langName.yo": "iorwba",
  "langName.yua": "maya yucatec",
  "langName.zh": "tsieinëeg",
  "langName.zh-cn": "tsieinëeg symledig",
  "langName.zh-hans": "tsieinëeg symledig",
  "langName.zh-hant": "tsieinëeg traddodiadol",
  "langName.zh-hk": "tsieineg (Hong Kong)",
  "langName.zh-sg": "tsieinëeg (Singapore)",
  "langName.zh-tw": "tsieinëeg traddodiadol",
  "langName.zu": "swlw",
  "langName.zu-za": "swlw"
});