tinymce.addI18n('cy', {
  "-Language Not Set-": "-Iaith heb ei gosod-",
  "Choose from list": "Dewis o'r rhestr",
  "Choose languages": "Dewis ieithoedd",
  "Choose up to six languages": "Dewis hyd at chwe iaith",
  "Configure languages": "Ffurfweddu ieithoedd",
  "Current language:": "Iaith bresennol:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Rhoi cod iaith dilys heb fylchau. Neu, pwyswch canslo.",
  "Enter manually": "Rhoi i mewn â llaw",
  "Enter new lang code (e.g., \"en-US\"):": "Rhoi cod iaith newydd (e.e., \"cy-GB\"):",
  "Indicate current language": "Nodi'r iaith bresennol",
  "Manually enter language {{number}}:": "Rhoi iaith {{number}} i mewn â llaw:",
  "New Language:": "Iaith newydd:",
  "None": "Dim",
  "Other - Enter manually": "Arall - Rhoi i mewn â llaw",
  "Really remove all language markup from the document?": "Wir dynnu'r holl farcio iaith o'r ddogfen?",
  "Remove All lang markup": "Tynnu'r holl farcio iaith",
  "Remove Language Markup": "Tynnu marcio iaith",
  "Remove current lang value": "Tynnu gwerth iaith bresennol",
  "Reveal lang markup": "Datgelu marcio iaith",
  "Select language {{number}}:": "Dewis iaith {{number}}:",
  "Select the document's default language.": "Dewis iaith rhagosodedig y ddogfen.",
  "Set default document language": "Gosod iaith rhagosodedig y ddogfen",
  "Set text language": "Gosod iaith y testun",
  "langName.af": "Affricaneg",
  "langName.af-za": "Affricaneg",
  "langName.ak": "Acaneg",
  "langName.am": "Amhareg",
  "langName.ar": "Arabeg",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "Arabeg",
  "langName.az": "Aserbaijaneg",
  "langName.be": "Belarwseg",
  "langName.bg": "Bwlgareg",
  "langName.bg-bg": "Bwlgareg",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambareg",
  "langName.bn": "Bengaleg",
  "langName.bo": "Tibeteg",
  "langName.bs": "Bosnieg",
  "langName.ca": "Catalaneg",
  "langName.cop": "Copteg",
  "langName.cr": "Cri",
  "langName.cs": "Tsieceg",
  "langName.cu": "Hen Slafoneg",
  "langName.cy": "Cymraeg",
  "langName.da": "Daneg",
  "langName.de": "Almaeneg",
  "langName.de-at": "Almaeneg Awstria",
  "langName.de-ch": "Almaeneg Safonol y Swistir",
  "langName.de-de": "Almaeneg",
  "langName.dv": "Difehi",
  "langName.el": "Groeg",
  "langName.en": "Saesneg",
  "langName.en-au": "Saesneg Awstralia",
  "langName.en-ca": "Saesneg Canada",
  "langName.en-gb": "Saesneg Prydain",
  "langName.en-ie": "Saesneg (Iwerddon)",
  "langName.en-in": "Saesneg (India)",
  "langName.en-tt": "Saesneg (Trinidad)",
  "langName.en-us": "Saesneg America",
  "langName.en-za": "Saesneg (De Affrica)",
  "langName.eo": "Esperanto",
  "langName.es": "Sbaeneg",
  "langName.es-ar": "Sbaeneg (Ariannin)",
  "langName.es-cl": "Sbaeneg (Chile)",
  "langName.es-co": "Sbaeneg (Colombia)",
  "langName.es-cr": "",
  "langName.es-es": "Sbaeneg Ewrop",
  "langName.es-mx": "Sbaeneg Mecsico",
  "langName.es-pe": "Sbaeneg (Periw)",
  "langName.et": "Estoneg",
  "langName.eu": "Basgeg",
  "langName.fa": "Perseg",
  "langName.fa-af": "Dari",
  "langName.fa-ir": "Perseg",
  "langName.ff": "Ffwla",
  "langName.fi": "Ffinneg",
  "langName.fi-fi": "Ffinneg",
  "langName.fil": "Ffilipineg",
  "langName.fr": "Ffrangeg",
  "langName.fr-be": "",
  "langName.fr-ca": "Ffrangeg Canada",
  "langName.fr-ch": "Ffrangeg y Swistir",
  "langName.ga": "Gwyddeleg",
  "langName.gl": "Galisieg",
  "langName.grc": "Hen Roeg",
  "langName.ha": "Hawsa",
  "langName.he": "Hebraeg",
  "langName.he-il": "Hebraeg",
  "langName.hi": "Hindi",
  "langName.hr": "Croateg",
  "langName.hr-hr": "Croateg",
  "langName.ht": "Creol Haiti",
  "langName.hu": "Hwngareg",
  "langName.hu-hu": "Hwngareg",
  "langName.hy": "Armeneg",
  "langName.id": "Indoneseg",
  "langName.ig": "Igbo",
  "langName.is": "Islandeg",
  "langName.it": "Eidaleg",
  "langName.it-it": "Eidaleg",
  "langName.iu": "Inwctitwt",
  "langName.ja": "Japaneeg",
  "langName.ja-jp": "Japaneeg",
  "langName.ka": "Georgeg",
  "langName.kab": "Cabileg",
  "langName.kk": "Casacheg",
  "langName.km": "Chmereg",
  "langName.kn": "Kannada",
  "langName.ko": "Coreeg",
  "langName.ko-kr": "Coreeg",
  "langName.la": "Lladin",
  "langName.lkt": "Lakota",
  "langName.lo": "Laoeg",
  "langName.lt": "Lithwaneg",
  "langName.lv": "Latfieg",
  "langName.mi": "Māori",
  "langName.mn": "Mongoleg",
  "langName.mr": "Marathi",
  "langName.ms": "Maleieg",
  "langName.mt": "Malteg",
  "langName.my": "Byrmaneg",
  "langName.nb": "Norwyeg Bokmål",
  "langName.nb-no": "Norwyeg Bokmål",
  "langName.ne": "Nepaleg",
  "langName.nl": "Iseldireg",
  "langName.nl-be": "Fflemeg",
  "langName.nn": "Norwyeg Nynorsk",
  "langName.nv": "Nafaho",
  "langName.ota": "Tyrceg Otoman",
  "langName.pa": "Pwnjabeg",
  "langName.peo": "Hen Bersieg",
  "langName.pl": "Pwyleg",
  "langName.ps": "Pashto",
  "langName.pt": "Portiwgaleg",
  "langName.pt-br": "Portiwgaleg Brasil",
  "langName.pt-pt": "Portiwgaleg Ewrop",
  "langName.qu": "Quechua",
  "langName.ro": "Rwmaneg",
  "langName.ru": "Rwseg",
  "langName.rw": "Ciniarŵandeg",
  "langName.sa": "Sansgrit",
  "langName.se": "Sami Gogleddol",
  "langName.si": "Sinhaleg",
  "langName.sk-sk": "Slofaceg",
  "langName.sl": "Slofeneg",
  "langName.sl-si": "Slofeneg",
  "langName.sma": "Sami Deheuol",
  "langName.sme": "Sami Gogleddol",
  "langName.smj": "Sami Lwle",
  "langName.sn": "Shona",
  "langName.sr": "Serbeg",
  "langName.sr-latn": "",
  "langName.sv": "Swedeg",
  "langName.sv-se": "Swedeg",
  "langName.sw": "Swahili",
  "langName.sw-ke": "Swahili",
  "langName.sw-tz": "Swahili",
  "langName.syc": "Hen Syrieg",
  "langName.ta": "Tamileg",
  "langName.te": "Telugu",
  "langName.tg": "Tajiceg",
  "langName.th": "Thai",
  "langName.th-th": "Thai",
  "langName.tk": "Tyrcmeneg",
  "langName.tl": "Tagalog",
  "langName.tr": "Tyrceg",
  "langName.tr-tr": "Tyrceg",
  "langName.tt": "Tatareg",
  "langName.ug": "Uighur",
  "langName.uk": "Wcreineg",
  "langName.ur": "Wrdw",
  "langName.uz": "Wsbeceg",
  "langName.vi": "Fietnameg",
  "langName.wo": "Woloff",
  "langName.xh": "Xhosa",
  "langName.yi": "Iddew-Almaeneg",
  "langName.yo": "Iorwba",
  "langName.yua": "Maya Yucatec",
  "langName.zh": "Tsieinëeg",
  "langName.zh-cn": "Tsieinëeg Symledig",
  "langName.zh-hans": "Tsieinëeg Symledig",
  "langName.zh-hant": "Tsieinëeg Traddodiadol",
  "langName.zh-hk": "Tsieineg (Hong Kong)",
  "langName.zh-sg": "",
  "langName.zh-tw": "Tsieinëeg Traddodiadol",
  "langName.zu": "Swlw",
  "langName.zu-za": "Swlw"
});