tinymce.addI18n('da_x_k12', {
  "-Language Not Set-": "-Intet sprog valgt-",
  "Choose from list": "Vælg fra liste",
  "Choose languages": "Vælg sprog",
  "Choose up to six languages": "Vælg op til seks sprog",
  "Configure languages": "Indstil sprog",
  "Current language:": "Nuværende sprog:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Skriv en gyldig sprogkode uden mellemrum. Eller tryk annuller.",
  "Enter manually": "Skriv selv",
  "Enter new lang code (e.g., \"en-US\"):": "Skriv ny sprogkode (f.eks. \"da-DK\"):",
  "Indicate current language": "Vis nuværende sprog",
  "Manually enter language {{number}}:": "Skriv sprog {{number}} selv:",
  "New Language:": "Nyt sprog:",
  "None": "Ingen",
  "Other - Enter manually": "Andet - Skriv selv",
  "Really remove all language markup from the document?": "Vil du virkelig fjerne al sprogmærkning fra dokumentet?",
  "Remove All lang markup": "Fjern al sprogmærkning",
  "Remove Language Markup": "Fjern sprogmærkning",
  "Remove current lang value": "Fjern nuværende sprog",
  "Reveal lang markup": "Vis sprogmærkning",
  "Select language {{number}}:": "Vælg sprog {{number}}:",
  "Select the document's default language.": "Vælg dokumentets standardsprog.",
  "Set default document language": "Vælg standardsprog for dokumentet",
  "Set text language": "Vælg sprog for tekst",
  "langName.af": "afrikaans",
  "langName.af-za": "afrikaans (Sydafrika)",
  "langName.ak": "akan",
  "langName.am": "amharisk",
  "langName.ar": "arabisk",
  "langName.ar-eg": "arabisk (Egypten)",
  "langName.ar-ma": "arabisk (Marokko)",
  "langName.ar-sa": "arabisk (Saudi-Arabien)",
  "langName.az": "aserbajdsjansk",
  "langName.be": "belarusisk",
  "langName.bg": "bulgarsk",
  "langName.bg-bg": "bulgarsk (Bulgarien)",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengali",
  "langName.bo": "tibetansk",
  "langName.bs": "bosnisk",
  "langName.ca": "catalansk",
  "langName.cop": "koptisk",
  "langName.cr": "cree",
  "langName.cs": "tjekkisk",
  "langName.cu": "kirkeslavisk",
  "langName.cy": "walisisk",
  "langName.da": "dansk",
  "langName.de": "tysk",
  "langName.de-at": "tysk (Østrig)",
  "langName.de-ch": "tysk (Schweiz)",
  "langName.de-de": "tysk (Tyskland)",
  "langName.dv": "divehi",
  "langName.el": "græsk",
  "langName.en": "engelsk",
  "langName.en-au": "engelsk (Australien)",
  "langName.en-ca": "engelsk (Canada)",
  "langName.en-gb": "engelsk (Storbritannien)",
  "langName.en-ie": "engelsk (Irland)",
  "langName.en-in": "engelsk (Indien)",
  "langName.en-tt": "engelsk (Trinidad)",
  "langName.en-us": "engelsk (USA)",
  "langName.en-za": "engelsk (Sydafrika)",
  "langName.eo": "esperanto",
  "langName.es": "spansk",
  "langName.es-ar": "spansk (Argentina)",
  "langName.es-cl": "spansk (Chile)",
  "langName.es-co": "spansk (Colombia)",
  "langName.es-cr": "spansk (Costa Rica)",
  "langName.es-es": "spansk (Spanien)",
  "langName.es-mx": "spansk (Mexico)",
  "langName.es-pe": "spansk (Peru)",
  "langName.et": "estisk",
  "langName.eu": "baskisk",
  "langName.fa": "persisk",
  "langName.fa-af": "dari",
  "langName.fa-ir": "persisk (Iran)",
  "langName.ff": "fulah",
  "langName.fi": "finsk",
  "langName.fi-fi": "finsk (Finland)",
  "langName.fil": "filippinsk",
  "langName.fr": "fransk",
  "langName.fr-be": "fransk (Belgien)",
  "langName.fr-ca": "fransk (Canada)",
  "langName.fr-ch": "fransk (Schweiz)",
  "langName.ga": "irsk",
  "langName.gl": "galicisk",
  "langName.grc": "græsk (oldtids)",
  "langName.ha": "hausa",
  "langName.he": "hebraisk",
  "langName.he-il": "hebraisk (Israel)",
  "langName.hi": "hindi",
  "langName.hr": "kroatisk",
  "langName.hr-hr": "kroatisk (Kroatien)",
  "langName.ht": "haitisk",
  "langName.hu": "ungarsk",
  "langName.hu-hu": "ungarsk (Ungarn)",
  "langName.hy": "armensk",
  "langName.id": "indonesisk",
  "langName.ig": "igbo",
  "langName.is": "islandsk",
  "langName.it": "italiensk",
  "langName.it-it": "italiensk (Italien)",
  "langName.iu": "inuktitut",
  "langName.ja": "japansk",
  "langName.ja-jp": "japansk (Japan)",
  "langName.ka": "georgisk",
  "langName.kab": "kabylsk",
  "langName.kk": "kasakhisk",
  "langName.km": "khmer",
  "langName.kn": "kannada",
  "langName.ko": "koreansk",
  "langName.ko-kr": "koreansk (Korea)",
  "langName.la": "latin",
  "langName.lkt": "lakota",
  "langName.lo": "lao",
  "langName.lt": "litauisk",
  "langName.lv": "lettisk",
  "langName.mi": "maori",
  "langName.mn": "mongolsk",
  "langName.mr": "marathi",
  "langName.ms": "malajisk",
  "langName.mt": "maltesisk",
  "langName.my": "burmesisk",
  "langName.nb": "norsk (bokmål)",
  "langName.nb-no": "norsk (bokmål, Norge)",
  "langName.ne": "nepalesisk",
  "langName.nl": "nederlandsk",
  "langName.nl-be": "flamsk",
  "langName.nn": "norsk (nynorsk)",
  "langName.nv": "navajo",
  "langName.ota": "tyrkisk (osmannisk)",
  "langName.pa": "punjabi",
  "langName.peo": "persisk (oldtids)",
  "langName.pl": "polsk",
  "langName.ps": "pashto",
  "langName.pt": "portugisisk",
  "langName.pt-br": "portugisisk (Brasilien)",
  "langName.pt-pt": "portugisisk (Portugal)",
  "langName.qu": "quechua",
  "langName.ro": "rumænsk",
  "langName.ru": "russisk",
  "langName.rw": "kinyarwanda",
  "langName.sa": "sanskrit",
  "langName.se": "samisk (nord)",
  "langName.si": "singalesisk",
  "langName.sk": "slovakisk",
  "langName.sk-sk": "slovakisk (Slovakiet)",
  "langName.sl": "slovensk",
  "langName.sl-si": "slovensk (Slovenien)",
  "langName.sma": "samisk (syd)",
  "langName.sme": "samisk (nord)",
  "langName.smj": "samisk (lule)",
  "langName.sn": "shona",
  "langName.sr": "serbisk",
  "langName.sr-latn": "serbisk (latin)",
  "langName.sv": "svensk",
  "langName.sv-se": "svensk (Sverige)",
  "langName.sw": "swahili",
  "langName.sw-ke": "swahili (Kenya)",
  "langName.sw-tz": "swahili (Tanzania)",
  "langName.syc": "syrisk (klassisk)",
  "langName.ta": "tamil",
  "langName.te": "telugu",
  "langName.tg": "tadsjikisk",
  "langName.th": "thai",
  "langName.th-th": "thai (Thailand)",
  "langName.tk": "turkmensk",
  "langName.tl": "tagalog",
  "langName.tr": "tyrkisk",
  "langName.tr-tr": "tyrkisk (Tyrkiet)",
  "langName.tt": "tatarisk",
  "langName.ug": "uygurisk",
  "langName.uk": "ukrainsk",
  "langName.ur": "urdu",
  "langName.uz": "usbekisk",
  "langName.vi": "vietnamesisk",
  "langName.wo": "wolof",
  "langName.xh": "xhosa",
  "langName.yi": "jiddisch",
  "langName.yo": "yoruba",
  "langName.yua": "maya (yucatec)",
  "langName.zh": "kinesisk",
  "langName.zh-cn": "kinesisk (forenklet)",
  "langName.zh-hans": "kinesisk (forenklet)",
  "langName.zh-hant": "kinesisk (traditionelt)",
  "langName.zh-hk": "kinesisk (Hong Kong)",
  "langName.zh-sg": "kinesisk (Singapore)",
  "langName.zh-tw": "kinesisk (traditionelt)",
  "langName.zu": "zulu",
  "langName.zu-za": "zulu (Sydafrika)"
});