tinymce.addI18n("da_x_k12", {
  "Current language:": "Nuværende sprog:",
  "Set text language": "Vælg sprog for tekst",
  "-Language Not Set-": "-Intet sprog valgt-",
  "Choose languages": "Vælg sprog",
  "Remove Language Markup": "Fjern sprogmærkning",
  "Remove current lang value": "Fjern nuværende sprog",
  "Remove All lang markup": "Fjern al sprogmærkning",
  "Configure languages": "Indstil sprog",
  "Set default document language": "Vælg standardsprog for dokumentet",
  "Reveal lang markup": "Vis sprogmærkning",
  "Indicate current language": "Vis nuværende sprog",
  "Select the document's default language.": "Vælg dokumentets standardsprog.",
  "Choose from list": "Vælg fra liste",
  "Enter manually": "Skriv selv",
  "None": "Ingen",
  "Other - Enter manually": "Andet - Skriv selv",
  "New Language:": "Nyt sprog:",
  "Enter new lang code (e.g., \"en-US\"):": "Skriv ny sprogkode (f.eks. \"da-DK\"):",
  "Choose up to six languages": "Vælg op til seks sprog",
  "Select language {{number}}:": "Vælg sprog {{number}}:",
  "Manually enter language {{number}}:": "Skriv sprog {{number}} selv:",
  "Really remove all language markup from the document?": "Vil du virkelig fjerne al sprogmærkning fra dokumentet?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Skriv en gyldig sprogkode uden mellemrum. Eller tryk annuller.",
  "langName.af": "Afrikaans",
  "langName.ak": "Akan",
  "langName.ar": "Arabisk",
  "langName.az": "Aserbajdsjansk",
  "langName.bg": "Bulgarsk",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengali",
  "langName.bo": "Tibetansk",
  "langName.bs": "Bosnisk",
  "langName.ca": "Catalansk",
  "langName.cs": "Tjekkisk",
  "langName.cu": "Gammelbulgarsk",
  "langName.da": "Dansk",
  "langName.de": "Tysk",
  "langName.el": "Græsk",
  "langName.en": "Engelsk",
  "langName.en-au": "Engelsk (Australien)",
  "langName.en-gb": "Engelsk (England)",
  "langName.en-in": "Engelsk (Indien)",
  "langName.en-ie": "Engelsk (Irland)",
  "langName.en-tt": "Engelsk (Trinidad)",
  "langName.en-us": "Engelsk (USA)",
  "langName.en-za": "Engelsk (Sydafrika)",
  "langName.es": "Spansk",
  "langName.es-ar": "Spansk (Argentina)",
  "langName.es-cl": "Spansk (Chile)",
  "langName.es-co": "Spansk (Colombia)",
  "langName.es-mx": "Spansk (Mexico)",
  "langName.es-pe": "Spansk (Peru)",
  "langName.et": "Estisk",
  "langName.eu": "Baskisk",
  "langName.fa": "Persisk",
  "langName.fi": "Finsk",
  "langName.fr": "Fransk",
  "langName.fr-ca": "Fransk (Canada)",
  "langName.gl": "Galicisk",
  "langName.he": "Hebraisk",
  "langName.hi": "Hindi",
  "langName.hr": "Kroatisk",
  "langName.hu": "Ungarsk",
  "langName.id": "Indonesisk",
  "langName.it": "Italiensk",
  "langName.ja": "Japansk",
  "langName.kk": "Kasakhisk",
  "langName.kn": "Kannada",
  "langName.ko": "Koreansk",
  "langName.la": "Latin",
  "langName.lkt": "Lakota",
  "langName.mn": "Mongolsk",
  "langName.mr": "Marathi",
  "langName.nb": "Norsk bokmål",
  "langName.nl": "Hollandsk",
  "langName.nl-be": "Hollandsk (Belgien)",
  "langName.nn": "Norsk nynorsk",
  "langName.pl": "Polsk",
  "langName.ps": "Pashto",
  "langName.pt": "Portugisisk",
  "langName.pt-br": "Portugisisk (Brasilien)",
  "langName.qu": "Quechua",
  "langName.ro": "Rumænsk",
  "langName.ru": "Russisk",
  "langName.sa": "Sanskrit",
  "langName.sk-sk": "Slovakisk",
  "langName.sl": "Slovensk",
  "langName.sma": "Sydsapisk",
  "langName.sme": "Nordsapisk",
  "langName.smj": "Lule-sapisk",
  "langName.sr": "Serbisk",
  "langName.sv": "Svensk",
  "langName.sw": "Swahili",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tadsjikisk",
  "langName.th": "Thai",
  "langName.tr": "Tyrkisk",
  "langName.ug": "Uygurisk",
  "langName.uk": "Ukrainsk",
  "langName.ur": "Urdu",
  "langName.uz": "Usbekisk",
  "langName.vi": "Vietnamesisk",
  "langName.wo": "Wolof",
  "langName.yi": "Jiddisch",
  "langName.yo": "Yoruba",
  "langName.yua": "Yucatec Maya",
  "langName.zh": "Kinesisk",
  "langName.zh-cn": "Kinesisk (Kina)",
  "langName.zh-hk": "Kinesisk (Hongkong)",
  "langName.zh-tw": "Kinesisk (Taiwan)",
  "langName.zh-hans": "Kinesisk (forenklet)",
  "langName.zh-hant": "Kinesisk (traditionelt)",
  "langName.zu": "Zulu"
});