tinymce.addI18n('el', {
  "Current language:": "Τρέχουσα γλώσσα:",
  "Set text language": "Ορισμός γλώσσας κειμένου",
  "-Language Not Set-": "-Γλώσσα δεν έχει οριστεί-",
  "Choose languages": "Επιλογή γλωσσών",
  "Remove Language Markup": "Αφαίρεση σήμανσης γλώσσας",
  "Remove current lang value": "Αφαίρεση τρέχουσας τιμής γλώσσας",
  "Remove All lang markup": "Αφαίρεση όλης της σήμανσης γλώσσας",
  "Configure languages": "Διαμόρφωση γλωσσών",
  "Set default document language": "Ορισμός προεπιλεγμένης γλώσσας εγγράφου",
  "Reveal lang markup": "Εμφάνιση σήμανσης γλώσσας",
  "Indicate current language": "Ένδειξη τρέχουσας γλώσσας",
  "Select the document's default language.": "Επιλέξτε την προεπιλεγμένη γλώσσα του εγγράφου.",
  "Choose from list": "Επιλογή από λίστα",
  "Enter manually": "Εισαγωγή χειροκίνητα",
  "None": "Κανένα",
  "Other - Enter manually": "Άλλο - Εισαγωγή χειροκίνητα",
  "New Language:": "Νέα γλώσσα:",
  "Enter new lang code (e.g., \"en-US\"):": "Εισάγετε νέο κωδικό γλώσσας (π.χ., \"el-GR\"):",
  "Choose up to six languages": "Επιλέξτε έως έξι γλώσσες",
  "Select language {{number}}:": "Επιλέξτε γλώσσα {{number}}:",
  "Manually enter language {{number}}:": "Εισάγετε χειροκίνητα γλώσσα {{number}}:",
  "Really remove all language markup from the document?": "Πραγματικά να αφαιρεθεί όλη η σήμανση γλώσσας από το έγγραφο;",
  "Enter a valid language code with no spaces. Or, press cancel.": "Εισάγετε έναν έγκυρο κωδικό γλώσσας χωρίς κενά. Ή πατήστε ακύρωση.",
  "langName.af": "Αφρικάανς",
  "langName.ak": "Ακάν",
  "langName.ar": "Αραβικά",
  "langName.az": "Αζερμπαϊτζανικά",
  "langName.bg": "Βουλγαρικά",
  "langName.bho": "Μποτζπούρι",
  "langName.bm": "Μπαμπάρα",
  "langName.bn": "Βεγγαλικά",
  "langName.bo": "Θιβετιανά",
  "langName.bs": "Βοσνιακά",
  "langName.ca": "Καταλανικά· Βαλενθιανά",
  "langName.cs": "Τσεχικά",
  "langName.cu": "Παλαιά Βουλγαρικά",
  "langName.da": "Δανικά",
  "langName.de": "Γερμανικά",
  "langName.el": "Ελληνικά",
  "langName.en": "Αγγλικά",
  "langName.en-au": "Αγγλικά (Αυστραλία)",
  "langName.en-gb": "Αγγλικά (Ηνωμένο Βασίλειο)",
  "langName.en-in": "Αγγλικά (Ινδία)",
  "langName.en-ie": "Αγγλικά (Ιρλανδία)",
  "langName.en-tt": "Αγγλικά (Τρινιντάντ)",
  "langName.en-us": "Αγγλικά (Ηνωμένες Πολιτείες)",
  "langName.en-za": "Αγγλικά (Νότια Αφρική)",
  "langName.es": "Ισπανικά",
  "langName.es-ar": "Ισπανικά (Αργεντινή)",
  "langName.es-cl": "Ισπανικά (Χιλή)",
  "langName.es-co": "Ισπανικά (Κολομβία)",
  "langName.es-mx": "Ισπανικά (Μεξικό)",
  "langName.es-pe": "Ισπανικά (Περού)",
  "langName.et": "Εσθονικά",
  "langName.eu": "Βασκικά",
  "langName.fa": "Περσικά",
  "langName.fi": "Φινλανδικά",
  "langName.fr": "Γαλλικά",
  "langName.fr-ca": "Γαλλικά (Καναδά)",
  "langName.gl": "Γαλικιανά (Ισπανία)",
  "langName.he": "Εβραϊκά",
  "langName.hi": "Χίντι",
  "langName.hr": "Κροατικά",
  "langName.hu": "Ουγγρικά",
  "langName.id": "Ινδονησιακά",
  "langName.it": "Ιταλικά",
  "langName.ja": "Ιαπωνικά",
  "langName.kk": "Καζαχικά",
  "langName.kn": "Κανάντα",
  "langName.ko": "Κορεατικά",
  "langName.la": "Λατινικά",
  "langName.lkt": "Λακότα",
  "langName.mn": "Μογγολικά",
  "langName.mr": "Μαράθι",
  "langName.nb": "Νορβηγικά Μποκμάλ",
  "langName.nl": "Ολλανδικά",
  "langName.nl-be": "Ολλανδικά (Βέλγιο)",
  "langName.nn": "Νορβηγικά Νινόρσκ",
  "langName.pl": "Πολωνικά",
  "langName.ps": "Πάστο",
  "langName.pt": "Πορτογαλικά, Διεθνή",
  "langName.pt-br": "Πορτογαλικά, Βραζιλία",
  "langName.qu": "Κέτσουα",
  "langName.ro": "Ρουμανικά",
  "langName.ru": "Ρωσικά",
  "langName.sa": "Σανσκριτικά",
  "langName.sk-sk": "Σλοβακικά",
  "langName.sl": "Σλοβενικά",
  "langName.sma": "Νότια Σάμι",
  "langName.sme": "Βόρεια Σάμι",
  "langName.smj": "Λούλε Σάμι",
  "langName.sr": "Σερβικά",
  "langName.sv": "Σουηδικά",
  "langName.sw": "Σουαχίλι",
  "langName.ta": "Ταμίλ",
  "langName.te": "Τελούγκου",
  "langName.tg": "Τατζικικά",
  "langName.th": "Ταϊλανδικά",
  "langName.tr": "Τουρκικά",
  "langName.ug": "Ουιγκούρ",
  "langName.uk": "Ουκρανικά",
  "langName.ur": "Ουρντού",
  "langName.uz": "Ουζμπεκικά",
  "langName.vi": "Βιετναμικά",
  "langName.wo": "Γουόλοφ",
  "langName.yi": "Γίντις",
  "langName.yo": "Γιορούμπα",
  "langName.yua": "Μάγια Γιουκατέκ",
  "langName.zh": "Κινεζικά",
  "langName.zh-cn": "Κινεζικά (Κίνα)",
  "langName.zh-hk": "Κινεζικά (Χονγκ Κονγκ)",
  "langName.zh-tw": "Κινεζικά (Ταϊβάν)",
  "langName.zh-hans": "Κινεζικά, Απλοποιημένα",
  "langName.zh-hant": "Κινεζικά, Παραδοσιακά",
  "langName.zu": "Ζουλού"
});