tinymce.addI18n('el', {
  "-Language Not Set-": "-Γλώσσα δεν έχει οριστεί-",
  "Choose from list": "Επιλογή από λίστα",
  "Choose languages": "Επιλογή γλωσσών",
  "Choose up to six languages": "Επιλέξτε έως έξι γλώσσες",
  "Configure languages": "Διαμόρφωση γλωσσών",
  "Current language:": "Τρέχουσα γλώσσα:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Εισάγετε έναν έγκυρο κωδικό γλώσσας χωρίς κενά. Ή πατήστε ακύρωση.",
  "Enter manually": "Εισαγωγή χειροκίνητα",
  "Enter new lang code (e.g., \"en-US\"):": "Εισάγετε νέο κωδικό γλώσσας (π.χ., \"el-GR\"):",
  "Indicate current language": "Ένδειξη τρέχουσας γλώσσας",
  "Manually enter language {{number}}:": "Εισάγετε χειροκίνητα γλώσσα {{number}}:",
  "New Language:": "Νέα γλώσσα:",
  "None": "Κανένα",
  "Other - Enter manually": "Άλλο - Εισαγωγή χειροκίνητα",
  "Really remove all language markup from the document?": "Πραγματικά να αφαιρεθεί όλη η σήμανση γλώσσας από το έγγραφο;",
  "Remove All lang markup": "Αφαίρεση όλης της σήμανσης γλώσσας",
  "Remove Language Markup": "Αφαίρεση σήμανσης γλώσσας",
  "Remove current lang value": "Αφαίρεση τρέχουσας τιμής γλώσσας",
  "Reveal lang markup": "Εμφάνιση σήμανσης γλώσσας",
  "Select language {{number}}:": "Επιλέξτε γλώσσα {{number}}:",
  "Select the document's default language.": "Επιλέξτε την προεπιλεγμένη γλώσσα του εγγράφου.",
  "Set default document language": "Ορισμός προεπιλεγμένης γλώσσας εγγράφου",
  "Set text language": "Ορισμός γλώσσας κειμένου",
  "langName.af": "Αφρικάανς",
  "langName.af-za": "Αφρικάανς",
  "langName.ak": "Ακάν",
  "langName.am": "Αμχαρικά",
  "langName.ar": "Αραβικά",
  "langName.ar-eg": "Αραβικά (Αίγυπτος)",
  "langName.ar-ma": "Αραβικά (Μαρόκο)",
  "langName.ar-sa": "Αραβικά (Σαουδική Αραβία)",
  "langName.az": "Αζερμπαϊτζανικά",
  "langName.be": "Λευκορωσικά",
  "langName.bg": "Βουλγαρικά",
  "langName.bg-bg": "Βουλγαρικά",
  "langName.bho": "Μπότζπουρι",
  "langName.bm": "Μπαμπάρα",
  "langName.bn": "Βεγγαλικά",
  "langName.bo": "Θιβετιανά",
  "langName.bs": "Βοσνιακά",
  "langName.ca": "Καταλανικά",
  "langName.cop": "Κοπτικά",
  "langName.cr": "Κρι",
  "langName.cs": "Τσεχικά",
  "langName.cu": "Εκκλησιαστικά Σλαβικά",
  "langName.cy": "Ουαλικά",
  "langName.da": "Δανικά",
  "langName.de": "Γερμανικά",
  "langName.de-at": "Γερμανικά Αυστρίας",
  "langName.de-ch": "Υψηλά Γερμανικά Ελβετίας",
  "langName.de-de": "Γερμανικά (Γερμανία)",
  "langName.dv": "Ντιβέχι",
  "langName.el": "Ελληνικά",
  "langName.en": "Αγγλικά",
  "langName.en-au": "Αγγλικά Αυστραλίας",
  "langName.en-ca": "Αγγλικά Καναδά",
  "langName.en-gb": "Αγγλικά Βρετανίας",
  "langName.en-ie": "Αγγλικά (Ιρλανδία)",
  "langName.en-in": "Αγγλικά (Ινδία)",
  "langName.en-tt": "Αγγλικά (Τρινιντάντ)",
  "langName.en-us": "Αγγλικά Αμερικής",
  "langName.en-za": "Αγγλικά (Νότια Αφρική)",
  "langName.eo": "Εσπεράντο",
  "langName.es": "Ισπανικά",
  "langName.es-ar": "Ισπανικά (Αργεντινή)",
  "langName.es-cl": "Ισπανικά (Χιλή)",
  "langName.es-co": "Ισπανικά (Κολομβία)",
  "langName.es-cr": "Ισπανικά (Κόστα Ρίκα)",
  "langName.es-es": "Ισπανικά Ευρώπης",
  "langName.es-mx": "Ισπανικά Μεξικού",
  "langName.es-pe": "Ισπανικά (Περού)",
  "langName.et": "Εσθονικά",
  "langName.eu": "Βασκικά",
  "langName.fa": "Περσικά",
  "langName.fa-af": "Νταρί",
  "langName.fa-ir": "Περσικά (Ιράν)",
  "langName.ff": "Φουλά",
  "langName.fi": "Φινλανδικά",
  "langName.fi-fi": "Φινλανδικά",
  "langName.fil": "Φιλιππινικά",
  "langName.fr": "Γαλλικά",
  "langName.fr-be": "Γαλλικά (Βέλγιο)",
  "langName.fr-ca": "Γαλλικά Καναδά",
  "langName.fr-ch": "Γαλλικά Ελβετίας",
  "langName.ga": "Ιρλανδικά",
  "langName.gl": "Γαλικιανά",
  "langName.grc": "Αρχαία Ελληνικά",
  "langName.ha": "Χάουσα",
  "langName.he": "Εβραϊκά",
  "langName.he-il": "Εβραϊκά",
  "langName.hi": "Χίντι",
  "langName.hr": "Κροατικά",
  "langName.hr-hr": "Κροατικά",
  "langName.ht": "Αϊτιανά",
  "langName.hu": "Ουγγρικά",
  "langName.hu-hu": "Ουγγρικά",
  "langName.hy": "Αρμενικά",
  "langName.id": "Ινδονησιακά",
  "langName.ig": "Ίγκμπο",
  "langName.is": "Ισλανδικά",
  "langName.it": "Ιταλικά",
  "langName.it-it": "Ιταλικά",
  "langName.iu": "Ινούκτιτουτ",
  "langName.ja": "Ιαπωνικά",
  "langName.ja-jp": "Ιαπωνικά",
  "langName.ka": "Γεωργιανά",
  "langName.kab": "Καμπίλε",
  "langName.kk": "Καζακικά",
  "langName.km": "Χμερ",
  "langName.kn": "Κανάντα",
  "langName.ko": "Κορεατικά",
  "langName.ko-kr": "Κορεατικά",
  "langName.la": "Λατινικά",
  "langName.lkt": "Λακότα",
  "langName.lo": "Λαοτινά",
  "langName.lt": "Λιθουανικά",
  "langName.lv": "Λετονικά",
  "langName.mi": "Μαορί",
  "langName.mn": "Μογγολικά",
  "langName.mr": "Μαραθικά",
  "langName.ms": "Μαλαισιανά",
  "langName.mt": "Μαλτεζικά",
  "langName.my": "Βιρμανικά",
  "langName.nb": "Νορβηγικά Μποκμάλ",
  "langName.nb-no": "Νορβηγικά Μποκμάλ",
  "langName.ne": "Νεπαλικά",
  "langName.nl": "Ολλανδικά",
  "langName.nl-be": "Φλαμανδικά",
  "langName.nn": "Νορβηγικά Νινόρσκ",
  "langName.nv": "Νάβαχο",
  "langName.ota": "Οθωμανικά Τουρκικά",
  "langName.pa": "Παντζαπικά",
  "langName.peo": "Αρχαία Περσικά",
  "langName.pl": "Πολωνικά",
  "langName.ps": "Πάστο",
  "langName.pt": "Πορτογαλικά",
  "langName.pt-br": "Πορτογαλικά Βραζιλίας",
  "langName.pt-pt": "Πορτογαλικά Ευρώπης",
  "langName.qu": "Κέτσουα",
  "langName.ro": "Ρουμανικά",
  "langName.ru": "Ρωσικά",
  "langName.rw": "Κινιαρουάντα",
  "langName.sa": "Σανσκριτικά",
  "langName.se": "Βόρεια Σάμι",
  "langName.si": "Σινχαλεζικά",
  "langName.sk-sk": "Σλοβακικά",
  "langName.sl": "Σλοβενικά",
  "langName.sl-si": "Σλοβενικά",
  "langName.sma": "Νότια Σάμι",
  "langName.sme": "Βόρεια Σάμι",
  "langName.smj": "Λούλε Σάμι",
  "langName.sn": "Σόνα",
  "langName.sr": "Σερβικά",
  "langName.sr-latn": "Σερβικά (Λατινικό)",
  "langName.sv": "Σουηδικά",
  "langName.sv-se": "Σουηδικά",
  "langName.sw": "Σουαχίλι",
  "langName.sw-ke": "Σουαχίλι (Κένυα)",
  "langName.sw-tz": "Σουαχίλι (Τανζανία)",
  "langName.syc": "Κλασικά Συριακά",
  "langName.ta": "Ταμιλικά",
  "langName.te": "Τελούγκου",
  "langName.tg": "Τατζικικά",
  "langName.th": "Ταϊλανδικά",
  "langName.th-th": "Ταϊλανδικά",
  "langName.tk": "Τουρκμενικά",
  "langName.tl": "Τάγκαλογκ",
  "langName.tr": "Τουρκικά",
  "langName.tr-tr": "Τουρκικά",
  "langName.tt": "Ταταρικά",
  "langName.ug": "Ουιγουρικά",
  "langName.uk": "Ουκρανικά",
  "langName.ur": "Ούρντου",
  "langName.uz": "Ουζμπεκικά",
  "langName.vi": "Βιετναμικά",
  "langName.wo": "Γουόλοφ",
  "langName.xh": "Κόσα",
  "langName.yi": "Γίντις",
  "langName.yo": "Γιορούμπα",
  "langName.yua": "Μάγια Γιουκατέκ",
  "langName.zh": "Κινεζικά",
  "langName.zh-cn": "Απλοποιημένα Κινεζικά",
  "langName.zh-hans": "Απλοποιημένα Κινεζικά",
  "langName.zh-hant": "Παραδοσιακά Κινεζικά",
  "langName.zh-hk": "Κινεζικά (Χονγκ Κονγκ)",
  "langName.zh-sg": "Κινεζικά (Σιγκαπούρη)",
  "langName.zh-tw": "Παραδοσιακά Κινεζικά",
  "langName.zu": "Ζουλού",
  "langName.zu-za": "Ζουλού"
});