tinymce.addI18n('en_AU', {
  "-Language Not Set-": "-Language Not Set-",
  "Choose from list": "Choose from list",
  "Choose languages": "Choose languages",
  "Choose up to six languages": "Choose up to six languages",
  "Configure languages": "Configure languages",
  "Current language:": "Current language:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Enter a valid language code with no spaces. Or, press cancel.",
  "Enter manually": "Enter manually",
  "Enter new lang code (e.g., \"en-US\"):": "Enter new lang code (e.g., \"en-AU\"):",
  "Indicate current language": "Indicate current language",
  "Manually enter language {{number}}:": "Manually enter language {{number}}:",
  "New Language:": "New Language:",
  "None": "None",
  "Other - Enter manually": "Other - Enter manually",
  "Really remove all language markup from the document?": "Really remove all language markup from the document?",
  "Remove All lang markup": "Remove All lang markup",
  "Remove Language Markup": "Remove Language Markup",
  "Remove current lang value": "Remove current lang value",
  "Reveal lang markup": "Reveal lang markup",
  "Select language {{number}}:": "Select language {{number}}:",
  "Select the document's default language.": "Select the document's default language.",
  "Set default document language": "Set default document language",
  "Set text language": "Set text language",
  "langName.af": "Afrikaans",
  "langName.af-za": "Afrikaans",
  "langName.ak": "Akan",
  "langName.am": "Amharic",
  "langName.ar": "Arabic",
  "langName.ar-eg": "Arabic (Egypt)",
  "langName.ar-ma": "Arabic (Morocco)",
  "langName.ar-sa": "Arabic (Saudi Arabia)",
  "langName.az": "Azerbaijani",
  "langName.be": "Belarusian",
  "langName.bg": "Bulgarian",
  "langName.bg-bg": "Bulgarian (Bulgaria)",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bangla",
  "langName.bo": "Tibetan",
  "langName.bs": "Bosnian",
  "langName.ca": "Catalan",
  "langName.cop": "Coptic",
  "langName.cr": "Cree",
  "langName.cs": "Czech",
  "langName.cu": "Church Slavic",
  "langName.cy": "Welsh",
  "langName.da": "Danish",
  "langName.de": "German",
  "langName.de-at": "German (Austria)",
  "langName.de-ch": "German (Switzerland)",
  "langName.de-de": "German (Germany)",
  "langName.dv": "Divehi",
  "langName.el": "Greek",
  "langName.en": "English",
  "langName.en-au": "English (Australia)",
  "langName.en-ca": "English (Canada)",
  "langName.en-gb": "English (United Kingdom)",
  "langName.en-ie": "English (Ireland)",
  "langName.en-in": "English (India)",
  "langName.en-tt": "English (Trinidad)",
  "langName.en-us": "English (United States)",
  "langName.en-za": "English (South Africa)",
  "langName.eo": "Esperanto",
  "langName.es": "Spanish",
  "langName.es-ar": "Spanish (Argentina)",
  "langName.es-cl": "Spanish (Chile)",
  "langName.es-co": "Spanish (Colombia)",
  "langName.es-cr": "Spanish (Costa Rica)",
  "langName.es-es": "Spanish (Spain)",
  "langName.es-mx": "Spanish (Mexico)",
  "langName.es-pe": "Spanish (Peru)",
  "langName.et": "Estonian",
  "langName.eu": "Basque",
  "langName.fa": "Persian",
  "langName.fa-af": "Dari",
  "langName.fa-ir": "Persian (Iran)",
  "langName.ff": "Fula",
  "langName.fi": "Finnish",
  "langName.fi-fi": "Finnish (Finland)",
  "langName.fil": "Filipino",
  "langName.fr": "French",
  "langName.fr-be": "French (Belgium)",
  "langName.fr-ca": "French (Canada)",
  "langName.fr-ch": "French (Switzerland)",
  "langName.ga": "Irish",
  "langName.gl": "Galician",
  "langName.grc": "Greek (Ancient)",
  "langName.ha": "Hausa",
  "langName.he": "Hebrew",
  "langName.he-il": "Hebrew (Israel)",
  "langName.hi": "Hindi",
  "langName.hr": "Croatian",
  "langName.hr-hr": "Croatian (Croatia)",
  "langName.ht": "Haitian Creole",
  "langName.hu": "Hungarian",
  "langName.hu-hu": "Hungarian (Hungary)",
  "langName.hy": "Armenian",
  "langName.id": "Indonesian",
  "langName.ig": "Igbo",
  "langName.is": "Icelandic",
  "langName.it": "Italian",
  "langName.it-it": "Italian (Italy)",
  "langName.iu": "Inuktitut",
  "langName.ja": "Japanese",
  "langName.ja-jp": "Japanese (Japan)",
  "langName.ka": "Georgian",
  "langName.kab": "Kabyle",
  "langName.kk": "Kazakh",
  "langName.km": "Khmer",
  "langName.kn": "Kannada",
  "langName.ko": "Korean",
  "langName.ko-kr": "Korean (Korea)",
  "langName.la": "Latin",
  "langName.lkt": "Lakota",
  "langName.lo": "Lao",
  "langName.lt": "Lithuanian",
  "langName.lv": "Latvian",
  "langName.mi": "Māori",
  "langName.mn": "Mongolian",
  "langName.mr": "Marathi",
  "langName.ms": "Malay",
  "langName.mt": "Maltese",
  "langName.my": "Burmese",
  "langName.nb": "Norwegian (Bokmål)",
  "langName.nb-no": "Norwegian (Bokmål, Norway)",
  "langName.ne": "Nepali",
  "langName.nl": "Dutch",
  "langName.nl-be": "Flemish",
  "langName.nn": "Norwegian (Nynorsk)",
  "langName.nv": "Navajo",
  "langName.ota": "Turkish (Ottoman)",
  "langName.pa": "Punjabi",
  "langName.peo": "Persian (Old)",
  "langName.pl": "Polish",
  "langName.ps": "Pashto",
  "langName.pt": "Portuguese",
  "langName.pt-br": "Portuguese (Brazil)",
  "langName.pt-pt": "Portuguese (Portugal)",
  "langName.qu": "Quechua",
  "langName.ro": "Romanian",
  "langName.ru": "Russian",
  "langName.rw": "Kinyarwanda",
  "langName.sa": "Sanskrit",
  "langName.se": "Sami (Northern)",
  "langName.si": "Sinhala",
  "langName.sk-sk": "Slovak (Slovakia)",
  "langName.sl": "Slovenian",
  "langName.sl-si": "Slovenian (Slovenia)",
  "langName.sma": "Sami (Southern)",
  "langName.sme": "Sami (Northern)",
  "langName.smj": "Sami (Lule)",
  "langName.sn": "Shona",
  "langName.sr": "Serbian",
  "langName.sr-latn": "Serbian (Latin)",
  "langName.sv": "Swedish",
  "langName.sv-se": "Swedish (Sweden)",
  "langName.sw": "Swahili",
  "langName.sw-ke": "Swahili (Kenya)",
  "langName.sw-tz": "Swahili (Tanzania)",
  "langName.syc": "Syriac (Classical)",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tajik",
  "langName.th": "Thai",
  "langName.th-th": "Thai (Thailand)",
  "langName.tk": "Turkmen",
  "langName.tl": "Tagalog",
  "langName.tr": "Turkish",
  "langName.tr-tr": "Turkish (Turkey)",
  "langName.tt": "Tatar",
  "langName.ug": "Uyghur",
  "langName.uk": "Ukrainian",
  "langName.ur": "Urdu",
  "langName.uz": "Uzbek",
  "langName.vi": "Vietnamese",
  "langName.wo": "Wolof",
  "langName.xh": "Xhosa",
  "langName.yi": "Yiddish",
  "langName.yo": "Yoruba",
  "langName.yua": "Maya (Yucatec)",
  "langName.zh": "Chinese",
  "langName.zh-cn": "Chinese (Simplified)",
  "langName.zh-hans": "Chinese (Simplified)",
  "langName.zh-hant": "Chinese (Traditional)",
  "langName.zh-hk": "Chinese (Hong Kong)",
  "langName.zh-sg": "Chinese (Singapore)",
  "langName.zh-tw": "Chinese (Traditional)",
  "langName.zu": "Zulu",
  "langName.zu-za": "Zulu"
});