tinymce.addI18n('en_CA', {
  "Current language:": "Current language:",
  "Set text language": "Set text language",
  "-Language Not Set-": "-Language Not Set-",
  "Choose languages": "Choose languages",
  "Remove Language Markup": "Remove Language Markup",
  "Remove current lang value": "Remove current lang value",
  "Remove All lang markup": "Remove All lang markup",
  "Configure languages": "Configure languages",
  "Set default document language": "Set default document language",
  "Reveal lang markup": "Reveal lang markup",
  "Indicate current language": "Indicate current language",
  "Select the document's default language.": "Select the document's default language.",
  "Choose from list": "Choose from list",
  "Enter manually": "Enter manually",
  "None": "None",
  "Other - Enter manually": "Other - Enter manually",
  "New Language:": "New Language:",
  "Enter new lang code (e.g., \"en-US\"):": "Enter new lang code (e.g., \"en-CA\"):",
  "Choose up to six languages": "Choose up to six languages",
  "Select language {{number}}:": "Select language {{number}}:",
  "Manually enter language {{number}}:": "Manually enter language {{number}}:",
  "Really remove all language markup from the document?": "Really remove all language markup from the document?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Enter a valid language code with no spaces. Or, press cancel.",
  "langName.af": "Afrikaans",
  "langName.ak": "Akan",
  "langName.ar": "Arabic",
  "langName.az": "Azerbaijani",
  "langName.bg": "Bulgarian",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengali",
  "langName.bo": "Tibetan",
  "langName.bs": "Bosnian",
  "langName.ca": "Catalan; Valencian",
  "langName.cs": "Czech",
  "langName.cu": "Bulgarian, Old",
  "langName.da": "Danish",
  "langName.de": "German",
  "langName.el": "Greek",
  "langName.en": "English",
  "langName.en-au": "English (Australia)",
  "langName.en-gb": "English (United Kingdom)",
  "langName.en-in": "English (Indian)",
  "langName.en-ie": "English (Ireland)",
  "langName.en-tt": "English (Trinidad)",
  "langName.en-us": "English (United States)",
  "langName.en-za": "English (South Africa)",
  "langName.es": "Spanish",
  "langName.es-ar": "Spanish (Argentina)",
  "langName.es-cl": "Spanish (Chile)",
  "langName.es-co": "Spanish (Colombia)",
  "langName.es-mx": "Spanish (Mexico)",
  "langName.es-pe": "Spanish (Peru)",
  "langName.et": "Estonian",
  "langName.eu": "Basque",
  "langName.fa": "Persian",
  "langName.fi": "Finnish",
  "langName.fr": "French",
  "langName.fr-ca": "French (Canadian)",
  "langName.gl": "Galician (Spain)",
  "langName.he": "Hebrew",
  "langName.hi": "Hindi",
  "langName.hr": "Croatian",
  "langName.hu": "Hungarian",
  "langName.id": "Indonesian",
  "langName.it": "Italian",
  "langName.ja": "Japanese",
  "langName.kk": "Kazakh",
  "langName.kn": "Kannada",
  "langName.ko": "Korean",
  "langName.la": "Latin",
  "langName.lkt": "Lakota",
  "langName.mn": "Mongolian",
  "langName.mr": "Marathi",
  "langName.nb": "Norwegian Bokmål",
  "langName.nl": "Dutch",
  "langName.nl-be": "Dutch (Belgium)",
  "langName.nn": "Norwegian Nynorsk",
  "langName.pl": "Polish",
  "langName.ps": "Pashto",
  "langName.pt": "Portuguese, International",
  "langName.pt-br": "Portuguese, Brazil",
  "langName.qu": "Quechua",
  "langName.ro": "Romanian",
  "langName.ru": "Russian",
  "langName.sa": "Sanskrit",
  "langName.sk-sk": "Slovak",
  "langName.sl": "Slovenian",
  "langName.sma": "Southern Sami",
  "langName.sme": "Northern Sami",
  "langName.smj": "Lule Sami",
  "langName.sr": "Serbian",
  "langName.sv": "Swedish",
  "langName.sw": "Swahili",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tajik",
  "langName.th": "Thai",
  "langName.tr": "Turkish",
  "langName.ug": "Uyghur",
  "langName.uk": "Ukrainian",
  "langName.ur": "Urdu",
  "langName.uz": "Uzbek",
  "langName.vi": "Vietnamese",
  "langName.wo": "Wolof",
  "langName.yi": "Yiddish",
  "langName.yo": "Yoruba",
  "langName.yua": "Yucatec Maya",
  "langName.zh": "Chinese",
  "langName.zh-cn": "Chinese (China)",
  "langName.zh-hk": "Chinese (Hong Kong)",
  "langName.zh-tw": "Chinese (Taiwan)",
  "langName.zh-hans": "Chinese, Simplified",
  "langName.zh-hant": "Chinese, Traditional",
  "langName.zu": "Zulu"
});