tinymce.addI18n('en_US', {
  "-Language Not Set-": "-Language Not Set-",
  "Choose from list": "Choose from list",
  "Choose languages": "Choose languages",
  "Choose up to six languages": "Choose up to six languages",
  "Configure languages": "Configure languages",
  "Current language:": "Current language:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Enter a valid language code with no spaces. Or, press cancel.",
  "Enter manually": "Enter manually",
  "Enter new lang code (e.g., \"en-US\"):": "Enter new lang code (e.g., \"en-US\"):",
  "Indicate current language": "Indicate current language",
  "Manually enter language {{number}}:": "Manually enter language {{number}}:",
  "New Language:": "New Language:",
  "None": "None",
  "Other - Enter manually": "Other - Enter manually",
  "Really remove all language markup from the document?": "Really remove all language markup from the document?",
  "Remove All lang markup": "Remove All lang markup",
  "Remove Language Markup": "Remove Language Markup",
  "Remove current lang value": "Remove current lang value",
  "Reveal lang markup": "Reveal lang markup",
  "Select language {{number}}:": "Select language {{number}}:",
  "Select the document's default language.": "Select the document's default language.",
  "Set default document language": "Set default document language",
  "Set text language": "Set text language",
  "langName.af": "Afrikaans",
  "langName.af-za": "Afrikaans",
  "langName.ak": "Akan",
  "langName.am": "Amharic",
  "langName.ar": "Arabic",
  "langName.ar-eg": "Egyptian Arabic",
  "langName.ar-ma": "Moroccan Arabic",
  "langName.ar-sa": "Arabic",
  "langName.az": "Azerbaijani",
  "langName.be": "Belarusian",
  "langName.bg": "Bulgarian",
  "langName.bg-bg": "Bulgarian",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bangla",
  "langName.bo": "Tibetan",
  "langName.bs": "Bosnian",
  "langName.ca": "Catalan",
  "langName.cop": "Coptic",
  "langName.cr": "Cree",
  "langName.cs": "Czech",
  "langName.cu": "Church Slavic",
  "langName.cy": "Welsh",
  "langName.da": "Danish",
  "langName.de": "German",
  "langName.de-at": "Austrian German",
  "langName.de-ch": "Swiss High German",
  "langName.de-de": "German",
  "langName.dv": "Divehi",
  "langName.el": "Greek",
  "langName.en": "English",
  "langName.en-au": "Australian English",
  "langName.en-ca": "Canadian English",
  "langName.en-gb": "British English",
  "langName.en-ie": "English (Ireland)",
  "langName.en-in": "English (Indian)",
  "langName.en-tt": "English (Trinidad)",
  "langName.en-us": "American English",
  "langName.en-za": "English (South Africa)",
  "langName.eo": "Esperanto",
  "langName.es": "Spanish",
  "langName.es-ar": "Spanish (Argentinia)",
  "langName.es-cl": "Spanish (Chile)",
  "langName.es-co": "Spanish (Columbia)",
  "langName.es-cr": "Spanish (Costa Rica)",
  "langName.es-es": "European Spanish",
  "langName.es-mx": "Mexican Spanish",
  "langName.es-pe": "Spanish (Peru)",
  "langName.et": "Estonian",
  "langName.eu": "Basque",
  "langName.fa": "Persian",
  "langName.fa-af": "Dari",
  "langName.fa-ir": "Persian",
  "langName.ff": "Fula",
  "langName.fi": "Finnish",
  "langName.fi-fi": "Finnish",
  "langName.fil": "Filipino",
  "langName.fr": "French",
  "langName.fr-be": "Belgian French",
  "langName.fr-ca": "Canadian French",
  "langName.fr-ch": "Swiss French",
  "langName.ga": "Irish",
  "langName.gl": "Galician",
  "langName.grc": "Ancient Greek",
  "langName.ha": "Hausa",
  "langName.he": "Hebrew",
  "langName.he-il": "Hebrew",
  "langName.hi": "Hindi",
  "langName.hr": "Croatian",
  "langName.hr-hr": "Croatian",
  "langName.ht": "Haitian Creole",
  "langName.hu": "Hungarian",
  "langName.hu-hu": "Hungarian",
  "langName.hy": "Armenian",
  "langName.id": "Indonesian",
  "langName.ig": "Igbo",
  "langName.is": "Icelandic",
  "langName.it": "Italian",
  "langName.it-it": "Italian",
  "langName.iu": "Inuktitut",
  "langName.ja": "Japanese",
  "langName.ja-jp": "Japanese",
  "langName.ka": "Georgian",
  "langName.kab": "Kabyle",
  "langName.kk": "Kazakh",
  "langName.km": "Khmer",
  "langName.kn": "Kannada",
  "langName.ko": "Korean",
  "langName.ko-kr": "Korean",
  "langName.la": "Latin",
  "langName.lkt": "Lakota",
  "langName.lo": "Lao",
  "langName.lt": "Lithuanian",
  "langName.lv": "Latvian",
  "langName.mi": "Māori",
  "langName.mn": "Mongolian",
  "langName.mr": "Marathi",
  "langName.ms": "Malay",
  "langName.mt": "Maltese",
  "langName.my": "Burmese",
  "langName.nb": "Norwegian Bokmål",
  "langName.nb-no": "Norwegian Bokmål",
  "langName.ne": "Nepali",
  "langName.nl": "Dutch",
  "langName.nl-be": "Flemish",
  "langName.nn": "Norwegian Nynorsk",
  "langName.nv": "Navajo",
  "langName.ota": "Ottoman Turkish",
  "langName.pa": "Punjabi",
  "langName.peo": "Old Persian",
  "langName.pl": "Polish",
  "langName.ps": "Pashto",
  "langName.pt": "Portuguese",
  "langName.pt-br": "Brazilian Portuguese",
  "langName.pt-pt": "European Portuguese",
  "langName.qu": "Quechua",
  "langName.ro": "Romanian",
  "langName.ru": "Russian",
  "langName.rw": "Kinyarwanda",
  "langName.sa": "Sanskrit",
  "langName.se": "Northern Sami",
  "langName.si": "Sinhala",
  "langName.sk-sk": "Slovak",
  "langName.sl": "Slovenian",
  "langName.sl-si": "Slovenian",
  "langName.sma": "Southern Sami",
  "langName.sme": "Northern Sami",
  "langName.smj": "Lule Sami",
  "langName.sn": "Shona",
  "langName.sr": "Serbian",
  "langName.sr-latn": "Serbian (Latin)",
  "langName.sv": "Swedish",
  "langName.sv-se": "Swedish",
  "langName.sw": "Swahili",
  "langName.sw-ke": "Swahili",
  "langName.sw-tz": "Swahili",
  "langName.syc": "Classical Syriac",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tajik",
  "langName.th": "Thai",
  "langName.th-th": "Thai",
  "langName.tk": "Turkmen",
  "langName.tl": "Tagalog",
  "langName.tr": "Turkish",
  "langName.tr-tr": "Turkish",
  "langName.tt": "Tatar",
  "langName.ug": "Uyghur",
  "langName.uk": "Ukrainian",
  "langName.ur": "Urdu",
  "langName.uz": "Uzbek",
  "langName.vi": "Vietnamese",
  "langName.wo": "Wolof",
  "langName.xh": "Xhosa",
  "langName.yi": "Yiddish",
  "langName.yo": "Yoruba",
  "langName.yua": "Yucatec Maya",
  "langName.zh": "Chinese",
  "langName.zh-cn": "Simplified Chinese",
  "langName.zh-hans": "Simplified Chinese",
  "langName.zh-hant": "Traditional Chinese",
  "langName.zh-hk": "Chinese (Hong Kong)",
  "langName.zh-sg": "Chinese (Singapore)",
  "langName.zh-tw": "Traditional Chinese",
  "langName.zu": "Zulu",
  "langName.zu-za": "Zulu"
});