tinymce.addI18n('es', {
  "-Language Not Set-": "-Idioma No Establecido-",
  "Choose from list": "Elegir de la lista",
  "Choose languages": "Elegir idiomas",
  "Choose up to six languages": "Elegir hasta seis idiomas",
  "Configure languages": "Configurar idiomas",
  "Current language:": "Idioma actual:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Introducir un código de idioma válido sin espacios. O presionar cancelar.",
  "Enter manually": "Introducir manualmente",
  "Enter new lang code (e.g., \"en-US\"):": "Introducir nuevo código de idioma (ej., \"es-ES\"):",
  "Indicate current language": "Indicar idioma actual",
  "Manually enter language {{number}}:": "Introducir idioma {{number}} manualmente:",
  "New Language:": "Nuevo Idioma:",
  "None": "Ninguno",
  "Other - Enter manually": "Otro - Introducir manualmente",
  "Really remove all language markup from the document?": "¿Realmente eliminar todo el marcado de idioma del documento?",
  "Remove All lang markup": "Eliminar todo el marcado de idioma",
  "Remove Language Markup": "Eliminar Marcado de Idioma",
  "Remove current lang value": "Eliminar valor de idioma actual",
  "Reveal lang markup": "Mostrar marcado de idioma",
  "Select language {{number}}:": "Seleccionar idioma {{number}}:",
  "Select the document's default language.": "Seleccionar el idioma predeterminado del documento.",
  "Set default document language": "Establecer idioma predeterminado del documento",
  "Set text language": "Establecer idioma del texto",
  "Afrikaans": "afrikáans",
  "Afrikaans": "afrikáans (Sudáfrica)",
  "Akan": "akan",
  "Amharic": "amárico",
  "Arabic": "árabe",
  "Arabic (Egypt)": "árabe (Egipto)",
  "Arabic (Morocco)": "árabe (Marruecos)",
  "Arabic (Saudi Arabia)": "árabe (Arabia Saudí)",
  "Azerbaijani": "azerbaiyano",
  "Belarusian": "bielorruso",
  "Bulgarian": "búlgaro",
  "Bulgarian (Bulgaria)": "búlgaro (Bulgaria)",
  "Bhojpuri": "bhoyapurí",
  "Bambara": "bambara",
  "Bangla": "bengalí",
  "Tibetan": "tibetano",
  "Bosnian": "bosnio",
  "Catalan": "catalán",
  "Coptic": "copto",
  "Cree": "cree",
  "Czech": "checo",
  "Church Slavic": "eslavo eclesiástico",
  "Welsh": "galés",
  "Danish": "danés",
  "German": "alemán",
  "German (Austria)": "alemán (Austria)",
  "German (Switzerland)": "alemán (Suiza)",
  "German (Germany)": "alemán (Alemania)",
  "Divehi": "divehi",
  "Greek": "griego",
  "English": "inglés",
  "English (Australia)": "inglés (Australia)",
  "English (Canada)": "inglés (Canadá)",
  "English (United Kingdom)": "inglés (Reino Unido)",
  "English (Ireland)": "inglés (Irlanda)",
  "English (India)": "inglés (India)",
  "English (Trinidad)": "inglés (Trinidad)",
  "English (United States)": "inglés (Estados Unidos)",
  "English (South Africa)": "inglés (Sudáfrica)",
  "Esperanto": "esperanto",
  "Spanish": "español",
  "Spanish (Argentina)": "español (Argentina)",
  "Spanish (Chile)": "español (Chile)",
  "Spanish (Colombia)": "español (Colombia)",
  "Spanish (Costa Rica)": "español (Costa Rica)",
  "Spanish (Spain)": "español (España)",
  "Spanish (Mexico)": "español (México)",
  "Spanish (Peru)": "español (Perú)",
  "Estonian": "estonio",
  "Basque": "euskera",
  "Persian": "persa",
  "Dari": "darí",
  "Persian (Iran)": "persa (Irán)",
  "Fula": "fula",
  "Finnish": "finés",
  "Finnish (Finland)": "finés (Finlandia)",
  "Filipino": "filipino",
  "French": "francés",
  "French (Belgium)": "francés (Bélgica)",
  "French (Canada)": "francés (Canadá)",
  "French (Switzerland)": "francés (Suiza)",
  "Irish": "irlandés",
  "Galician": "gallego",
  "Greek (Ancient)": "griego antiguo",
  "Hausa": "hausa",
  "Hebrew": "hebreo",
  "Hebrew (Israel)": "hebreo (Israel)",
  "Hindi": "hindi",
  "Croatian": "croata",
  "Croatian (Croatia)": "croata (Croacia)",
  "Haitian Creole": "criollo haitiano",
  "Hungarian": "húngaro",
  "Hungarian (Hungary)": "húngaro (Hungría)",
  "Armenian": "armenio",
  "Indonesian": "indonesio",
  "Igbo": "igbo",
  "Icelandic": "islandés",
  "Italian": "italiano",
  "Italian (Italy)": "italiano (Italia)",
  "Inuktitut": "inuktitut",
  "Japanese": "japonés",
  "Japanese (Japan)": "japonés (Japón)",
  "Georgian": "georgiano",
  "Kabyle": "cabileño",
  "Kazakh": "kazajo",
  "Khmer": "jemer",
  "Kannada": "canarés",
  "Korean": "coreano",
  "Korean (Korea)": "coreano (Corea)",
  "Latin": "latín",
  "Lakota": "lakota",
  "Lao": "lao",
  "Lithuanian": "lituano",
  "Latvian": "letón",
  "Māori": "maorí",
  "Mongolian": "mongol",
  "Marathi": "maratí",
  "Malay": "malayo",
  "Maltese": "maltés",
  "Burmese": "birmano",
  "Norwegian (Bokmål)": "noruego (bokmål)",
  "Norwegian (Bokmål, Norway)": "noruego (bokmål, Noruega)",
  "Nepali": "nepalí",
  "Dutch": "neerlandés",
  "Flemish": "flamenco",
  "Norwegian (Nynorsk)": "noruego (nynorsk)",
  "Navajo": "navajo",
  "Turkish (Ottoman)": "turco otomano",
  "Punjabi": "punyabí",
  "Persian (Old)": "persa antiguo",
  "Polish": "polaco",
  "Pashto": "pastún",
  "Portuguese": "portugués",
  "Portuguese (Brazil)": "portugués (Brasil)",
  "Portuguese (Portugal)": "portugués (Portugal)",
  "Quechua": "quechua",
  "Romanian": "rumano",
  "Russian": "ruso",
  "Kinyarwanda": "kinyarwanda",
  "Sanskrit": "sánscrito",
  "Sami (Northern)": "sami septentrional",
  "Sinhala": "cingalés",
  "Slovak": "eslovaco",
  "Slovak (Slovakia)": "eslovaco (Eslovaquia)",
  "Slovenian": "esloveno",
  "Slovenian (Slovenia)": "esloveno (Eslovenia)",
  "Sami (Southern)": "sami meridional",
  "Sami (Northern)": "sami septentrional",
  "Sami (Lule)": "sami lule",
  "Shona": "shona",
  "Serbian": "serbio",
  "Serbian (Latin)": "serbio (latino)",
  "Swedish": "sueco",
  "Swedish (Sweden)": "sueco (Suecia)",
  "Swahili": "suajili",
  "Swahili (Kenya)": "suajili (Kenia)",
  "Swahili (Tanzania)": "suajili (Tanzania)",
  "Syriac (Classical)": "siríaco clásico",
  "Tamil": "tamil",
  "Telugu": "telugu",
  "Tajik": "tayiko",
  "Thai": "tailandés",
  "Thai (Thailand)": "tailandés (Tailandia)",
  "Turkmen": "turcomano",
  "Tagalog": "tagalo",
  "Turkish": "turco",
  "Turkish (Turkey)": "turco (Turquía)",
  "Tatar": "tártaro",
  "Uyghur": "uigur",
  "Ukrainian": "ucraniano",
  "Urdu": "urdu",
  "Uzbek": "uzbeko",
  "Vietnamese": "vietnamita",
  "Wolof": "wólof",
  "Xhosa": "xhosa",
  "Yiddish": "yidis",
  "Yoruba": "yoruba",
  "Maya (Yucatec)": "maya yucateco",
  "Chinese": "chino",
  "Chinese (Simplified)": "chino (simplificado)",
  "Chinese (Simplified)": "chino (simplificado)",
  "Chinese (Traditional)": "chino (tradicional)",
  "Chinese (Hong Kong)": "chino (Hong Kong)",
  "Chinese (Singapore)": "chino (Singapur)",
  "Chinese (Traditional)": "chino (tradicional)",
  "Zulu": "zulú",
  "Zulu": "zulú (Sudáfrica)"
});