tinymce.addI18n("es_CR", {
  "Current language:": "Idioma actual:",
  "Set text language": "Establecer idioma del texto",
  "-Language Not Set-": "-Idioma No Establecido-",
  "Choose languages": "Elegir idiomas",
  "Remove Language Markup": "Eliminar Marcado de Idioma",
  "Remove current lang value": "Eliminar valor de idioma actual",
  "Remove All lang markup": "Eliminar todo el marcado de idioma",
  "Configure languages": "Configurar idiomas",
  "Set default document language": "Establecer idioma predeterminado del documento",
  "Reveal lang markup": "Mostrar marcado de idioma",
  "Indicate current language": "Indicar idioma actual",
  "Select the document's default language.": "Seleccionar el idioma predeterminado del documento.",
  "Choose from list": "Elegir de la lista",
  "Enter manually": "Ingresar manualmente",
  "None": "Ninguno",
  "Other - Enter manually": "Otro - Ingresar manualmente",
  "New Language:": "Nuevo Idioma:",
  "Enter new lang code (e.g., \"en-US\"):": "Ingresar nuevo código de idioma (ej., \"es-CR\"):",
  "Choose up to six languages": "Elegir hasta seis idiomas",
  "Select language {{number}}:": "Seleccionar idioma {{number}}:",
  "Manually enter language {{number}}:": "Ingresar idioma {{number}} manualmente:",
  "Really remove all language markup from the document?": "¿Realmente eliminar todo el marcado de idioma del documento?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Ingresar un código de idioma válido sin espacios. O presionar cancelar.",
  "langName.af": "Afrikáans",
  "langName.ak": "Akan",
  "langName.ar": "Árabe",
  "langName.az": "Azerbaiyano",
  "langName.bg": "Búlgaro",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengalí",
  "langName.bo": "Tibetano",
  "langName.bs": "Bosnio",
  "langName.ca": "Catalán; Valenciano",
  "langName.cs": "Checo",
  "langName.cu": "Búlgaro Antiguo",
  "langName.da": "Danés",
  "langName.de": "Alemán",
  "langName.el": "Griego",
  "langName.en": "Inglés",
  "langName.en-au": "Inglés (Australia)",
  "langName.en-gb": "Inglés (Reino Unido)",
  "langName.en-in": "Inglés (India)",
  "langName.en-ie": "Inglés (Irlanda)",
  "langName.en-tt": "Inglés (Trinidad)",
  "langName.en-us": "Inglés (Estados Unidos)",
  "langName.en-za": "Inglés (Sudáfrica)",
  "langName.es": "Español",
  "langName.es-ar": "Español (Argentina)",
  "langName.es-cl": "Español (Chile)",
  "langName.es-co": "Español (Colombia)",
  "langName.es-mx": "Español (México)",
  "langName.es-pe": "Español (Perú)",
  "langName.et": "Estonio",
  "langName.eu": "Euskera",
  "langName.fa": "Persa",
  "langName.fi": "Finlandés",
  "langName.fr": "Francés",
  "langName.fr-ca": "Francés (Canadá)",
  "langName.gl": "Gallego (España)",
  "langName.he": "Hebreo",
  "langName.hi": "Hindi",
  "langName.hr": "Croata",
  "langName.hu": "Húngaro",
  "langName.id": "Indonesio",
  "langName.it": "Italiano",
  "langName.ja": "Japonés",
  "langName.kk": "Kazajo",
  "langName.kn": "Kannada",
  "langName.ko": "Coreano",
  "langName.la": "Latín",
  "langName.lkt": "Lakota",
  "langName.mn": "Mongol",
  "langName.mr": "Marathi",
  "langName.nb": "Noruego Bokmål",
  "langName.nl": "Holandés",
  "langName.nl-be": "Holandés (Bélgica)",
  "langName.nn": "Noruego Nynorsk",
  "langName.pl": "Polaco",
  "langName.ps": "Pashto",
  "langName.pt": "Portugués Internacional",
  "langName.pt-br": "Portugués (Brasil)",
  "langName.qu": "Quechua",
  "langName.ro": "Rumano",
  "langName.ru": "Ruso",
  "langName.sa": "Sánscrito",
  "langName.sk-sk": "Eslovaco",
  "langName.sl": "Esloveno",
  "langName.sma": "Sami Meridional",
  "langName.sme": "Sami Septentrional",
  "langName.smj": "Sami Lule",
  "langName.sr": "Serbio",
  "langName.sv": "Sueco",
  "langName.sw": "Suajili",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tayiko",
  "langName.th": "Tailandés",
  "langName.tr": "Turco",
  "langName.ug": "Uigur",
  "langName.uk": "Ucraniano",
  "langName.ur": "Urdu",
  "langName.uz": "Uzbeko",
  "langName.vi": "Vietnamita",
  "langName.wo": "Wolof",
  "langName.yi": "Yídish",
  "langName.yo": "Yoruba",
  "langName.yua": "Maya Yucateco",
  "langName.zh": "Chino",
  "langName.zh-cn": "Chino (China)",
  "langName.zh-hk": "Chino (Hong Kong)",
  "langName.zh-tw": "Chino (Taiwán)",
  "langName.zh-hans": "Chino Simplificado",
  "langName.zh-hant": "Chino Tradicional",
  "langName.zu": "Zulú"
});