tinymce.addI18n('es_ES', {
  "-Language Not Set-": "-Idioma No Establecido-",
  "Choose from list": "Elegir de la lista",
  "Choose languages": "Elegir idiomas",
  "Choose up to six languages": "Elegir hasta seis idiomas",
  "Configure languages": "Configurar idiomas",
  "Current language:": "Idioma actual:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Introducir un código de idioma válido sin espacios. O presionar cancelar.",
  "Enter manually": "Introducir manualmente",
  "Enter new lang code (e.g., \"en-US\"):": "Introducir nuevo código de idioma (ej., \"es-ES\"):",
  "Indicate current language": "Indicar idioma actual",
  "Manually enter language {{number}}:": "Introducir idioma {{number}} manualmente:",
  "New Language:": "Nuevo Idioma:",
  "None": "Ninguno",
  "Other - Enter manually": "Otro - Introducir manualmente",
  "Really remove all language markup from the document?": "¿Realmente eliminar todo el marcado de idioma del documento?",
  "Remove All lang markup": "Eliminar todo el marcado de idioma",
  "Remove Language Markup": "Eliminar Marcado de Idioma",
  "Remove current lang value": "Eliminar valor de idioma actual",
  "Reveal lang markup": "Mostrar marcado de idioma",
  "Select language {{number}}:": "Seleccionar idioma {{number}}:",
  "Select the document's default language.": "Seleccionar el idioma predeterminado del documento.",
  "Set default document language": "Establecer idioma predeterminado del documento",
  "Set text language": "Establecer idioma del texto",
  "langName.af": "afrikáans",
  "langName.af-za": "afrikáans",
  "langName.ak": "akan",
  "langName.am": "amárico",
  "langName.ar": "árabe",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "árabe",
  "langName.az": "azerbaiyano",
  "langName.be": "bielorruso",
  "langName.bg": "búlgaro",
  "langName.bg-bg": "búlgaro",
  "langName.bho": "bhoyapurí",
  "langName.bm": "bambara",
  "langName.bn": "bengalí",
  "langName.bo": "tibetano",
  "langName.bs": "bosnio",
  "langName.ca": "catalán",
  "langName.cop": "copto",
  "langName.cr": "cree",
  "langName.cs": "checo",
  "langName.cu": "eslavo eclesiástico",
  "langName.cy": "galés",
  "langName.da": "danés",
  "langName.de": "alemán",
  "langName.de-at": "alemán austríaco",
  "langName.de-ch": "alto alemán suizo",
  "langName.de-de": "alemán",
  "langName.dv": "divehi",
  "langName.el": "griego",
  "langName.en": "inglés",
  "langName.en-au": "inglés australiano",
  "langName.en-ca": "inglés canadiense",
  "langName.en-gb": "inglés británico",
  "langName.en-ie": "Inglés (Irlanda)",
  "langName.en-in": "Inglés (India)",
  "langName.en-tt": "Inglés (Trinidad)",
  "langName.en-us": "inglés estadounidense",
  "langName.en-za": "Inglés (Sudáfrica)",
  "langName.eo": "esperanto",
  "langName.es": "español",
  "langName.es-ar": "Español (Argentina)",
  "langName.es-cl": "Español (Chile)",
  "langName.es-co": "Español (Colombia)",
  "langName.es-cr": "",
  "langName.es-es": "español de España",
  "langName.es-mx": "español de México",
  "langName.es-pe": "Español (Perú)",
  "langName.et": "estonio",
  "langName.eu": "euskera",
  "langName.fa": "persa",
  "langName.fa-af": "darí",
  "langName.fa-ir": "persa",
  "langName.ff": "fula",
  "langName.fi": "finés",
  "langName.fi-fi": "finés",
  "langName.fil": "filipino",
  "langName.fr": "francés",
  "langName.fr-be": "",
  "langName.fr-ca": "francés canadiense",
  "langName.fr-ch": "francés suizo",
  "langName.ga": "irlandés",
  "langName.gl": "gallego",
  "langName.grc": "griego antiguo",
  "langName.ha": "hausa",
  "langName.he": "hebreo",
  "langName.he-il": "hebreo",
  "langName.hi": "hindi",
  "langName.hr": "croata",
  "langName.hr-hr": "croata",
  "langName.ht": "criollo haitiano",
  "langName.hu": "húngaro",
  "langName.hu-hu": "húngaro",
  "langName.hy": "armenio",
  "langName.id": "indonesio",
  "langName.ig": "igbo",
  "langName.is": "islandés",
  "langName.it": "italiano",
  "langName.it-it": "italiano",
  "langName.iu": "inuktitut",
  "langName.ja": "japonés",
  "langName.ja-jp": "japonés",
  "langName.ka": "georgiano",
  "langName.kab": "cabileño",
  "langName.kk": "kazajo",
  "langName.km": "jemer",
  "langName.kn": "canarés",
  "langName.ko": "coreano",
  "langName.ko-kr": "coreano",
  "langName.la": "latín",
  "langName.lkt": "lakota",
  "langName.lo": "lao",
  "langName.lt": "lituano",
  "langName.lv": "letón",
  "langName.mi": "maorí",
  "langName.mn": "mongol",
  "langName.mr": "maratí",
  "langName.ms": "malayo",
  "langName.mt": "maltés",
  "langName.my": "birmano",
  "langName.nb": "noruego bokmal",
  "langName.nb-no": "noruego bokmal",
  "langName.ne": "nepalí",
  "langName.nl": "neerlandés",
  "langName.nl-be": "flamenco",
  "langName.nn": "noruego nynorsk",
  "langName.nv": "navajo",
  "langName.ota": "turco otomano",
  "langName.pa": "punyabí",
  "langName.peo": "persa antiguo",
  "langName.pl": "polaco",
  "langName.ps": "pastún",
  "langName.pt": "portugués",
  "langName.pt-br": "portugués de Brasil",
  "langName.pt-pt": "portugués de Portugal",
  "langName.qu": "quechua",
  "langName.ro": "rumano",
  "langName.ru": "ruso",
  "langName.rw": "kinyarwanda",
  "langName.sa": "sánscrito",
  "langName.se": "sami septentrional",
  "langName.si": "cingalés",
  "langName.sk-sk": "eslovaco",
  "langName.sl": "esloveno",
  "langName.sl-si": "esloveno",
  "langName.sma": "sami meridional",
  "langName.sme": "Sami Septentrional",
  "langName.smj": "sami lule",
  "langName.sn": "shona",
  "langName.sr": "serbio",
  "langName.sr-latn": "",
  "langName.sv": "sueco",
  "langName.sv-se": "sueco",
  "langName.sw": "suajili",
  "langName.sw-ke": "suajili",
  "langName.sw-tz": "suajili",
  "langName.syc": "siríaco clásico",
  "langName.ta": "tamil",
  "langName.te": "telugu",
  "langName.tg": "tayiko",
  "langName.th": "tailandés",
  "langName.th-th": "tailandés",
  "langName.tk": "turcomano",
  "langName.tl": "tagalo",
  "langName.tr": "turco",
  "langName.tr-tr": "turco",
  "langName.tt": "tártaro",
  "langName.ug": "uigur",
  "langName.uk": "ucraniano",
  "langName.ur": "urdu",
  "langName.uz": "uzbeko",
  "langName.vi": "vietnamita",
  "langName.wo": "wólof",
  "langName.xh": "xhosa",
  "langName.yi": "yidis",
  "langName.yo": "yoruba",
  "langName.yua": "Maya Yucateco",
  "langName.zh": "chino",
  "langName.zh-cn": "chino simplificado",
  "langName.zh-hans": "chino simplificado",
  "langName.zh-hant": "chino tradicional",
  "langName.zh-hk": "Chino (Hong Kong)",
  "langName.zh-sg": "",
  "langName.zh-tw": "chino tradicional",
  "langName.zu": "zulú",
  "langName.zu-za": "zulú"
});