tinymce.addI18n('fa_AF', {
  "-Language Not Set-": "-زبان تعین نشده-",
  "Choose from list": "انتخاب از فهرست",
  "Choose languages": "انتخاب زبان‌ها",
  "Choose up to six languages": "حداکثر شش زبان انتخاب کنید",
  "Configure languages": "تنظیم زبان‌ها",
  "Current language:": "زبان فعلی:",
  "Enter a valid language code with no spaces. Or, press cancel.": "کد زبان معتبر بدون فاصله وارد کنید. یا لغو را فشار دهید.",
  "Enter manually": "وارد کردن دستی",
  "Enter new lang code (e.g., \"en-US\"):": "کد زبان جدید را وارد کنید (مثال: \"fa-AF\"):",
  "Indicate current language": "نشان دادن زبان فعلی",
  "Manually enter language {{number}}:": "وارد کردن دستی زبان {{number}}:",
  "New Language:": "زبان جدید:",
  "None": "هیچ",
  "Other - Enter manually": "سایر - وارد کردن دستی",
  "Really remove all language markup from the document?": "واقعاً تمام نشانه‌گذاری زبان از سند حذف شود؟",
  "Remove All lang markup": "حذف تمام نشانه‌گذاری زبان",
  "Remove Language Markup": "حذف نشانه‌گذاری زبان",
  "Remove current lang value": "حذف مقدار زبان فعلی",
  "Reveal lang markup": "نمایش نشانه‌گذاری زبان",
  "Select language {{number}}:": "انتخاب زبان {{number}}:",
  "Select the document's default language.": "زبان پیش‌فرض سند را انتخاب کنید.",
  "Set default document language": "تعین زبان پیش‌فرض سند",
  "Set text language": "تعین زبان متن",
  "langName.af": "آفریکانس",
  "langName.af-za": "آفریکانس (آفریقای جنوبی)",
  "langName.ak": "آکان",
  "langName.am": "امهری",
  "langName.ar": "عربی",
  "langName.ar-eg": "عربی (مصر)",
  "langName.ar-ma": "عربی (مراکش)",
  "langName.ar-sa": "عربی (عربستان سعودی)",
  "langName.az": "آذربایجانی",
  "langName.be": "بلاروسی",
  "langName.bg": "بلغاری",
  "langName.bg-bg": "بلغاری (بلغارستان)",
  "langName.bho": "بوجپوری",
  "langName.bm": "بامبارایی",
  "langName.bn": "بنگالی",
  "langName.bo": "تبتی",
  "langName.bs": "بوسنیایی",
  "langName.ca": "کاتالان",
  "langName.cop": "قبطی",
  "langName.cr": "کری",
  "langName.cs": "چکی",
  "langName.cu": "اسلاوی کلیسایی",
  "langName.cy": "ولزی",
  "langName.da": "دانمارکی",
  "langName.de": "آلمانی",
  "langName.de-at": "آلمانی (اتریش)",
  "langName.de-ch": "آلمانی (سوئیس)",
  "langName.de-de": "آلمانی (آلمان)",
  "langName.dv": "دیوهی",
  "langName.el": "یونانی",
  "langName.en": "انگلیسی",
  "langName.en-au": "انگلیسی (استرالیا)",
  "langName.en-ca": "انگلیسی (کانادا)",
  "langName.en-gb": "انگلیسی (پادشاهی متحده)",
  "langName.en-ie": "انگلیسی (ایرلند)",
  "langName.en-in": "انگلیسی (هند)",
  "langName.en-tt": "انگلیسی (ترینیداد)",
  "langName.en-us": "انگلیسی (ایالات متحده آمریکا)",
  "langName.en-za": "انگلیسی (آفریقای جنوبی)",
  "langName.eo": "اسپرانتو",
  "langName.es": "اسپانیایی",
  "langName.es-ar": "اسپانیایی (آرژانتین)",
  "langName.es-cl": "اسپانیایی (شیلی)",
  "langName.es-co": "اسپانیایی (کلمبیا)",
  "langName.es-cr": "اسپانیایی (کاستاریکا)",
  "langName.es-es": "اسپانیایی (اسپانیا)",
  "langName.es-mx": "اسپانیایی (مکزیک)",
  "langName.es-pe": "اسپانیایی (پرو)",
  "langName.et": "استونیایی",
  "langName.eu": "باسکی",
  "langName.fa": "فارسی",
  "langName.fa-af": "دری",
  "langName.fa-ir": "فارسی (ایران)",
  "langName.ff": "فولانی",
  "langName.fi": "فنلندی",
  "langName.fi-fi": "فنلندی (فنلاند)",
  "langName.fil": "فیلیپینی",
  "langName.fr": "فرانسوی",
  "langName.fr-be": "فرانسوی (بلژیک)",
  "langName.fr-ca": "فرانسوی (کانادا)",
  "langName.fr-ch": "فرانسوی (سوئیس)",
  "langName.ga": "ایرلندی",
  "langName.gl": "گالیسیایی",
  "langName.grc": "یونانی (کهن)",
  "langName.ha": "هوسایی",
  "langName.he": "عبری",
  "langName.he-il": "عبری (اسرائیل)",
  "langName.hi": "هندی",
  "langName.hr": "کرواتی",
  "langName.hr-hr": "کرواتی (کرواسی)",
  "langName.ht": "کریول هائیتی",
  "langName.hu": "مجاری",
  "langName.hu-hu": "مجاری (مجارستان)",
  "langName.hy": "ارمنی",
  "langName.id": "اندونزیایی",
  "langName.ig": "ایgبو",
  "langName.is": "ایسلندی",
  "langName.it": "ایتالیایی",
  "langName.it-it": "ایتالیایی (ایتالیا)",
  "langName.iu": "اینوکتیتوت",
  "langName.ja": "ژاپنی",
  "langName.ja-jp": "ژاپنی (ژاپن)",
  "langName.ka": "گرجی",
  "langName.kab": "قبایلی",
  "langName.kk": "قزاقی",
  "langName.km": "خمری",
  "langName.kn": "کانارا",
  "langName.ko": "کره‌ای",
  "langName.ko-kr": "کره‌ای (کره)",
  "langName.la": "لاتین",
  "langName.lkt": "لاکوتا",
  "langName.lo": "لائوسی",
  "langName.lt": "لیتوانیایی",
  "langName.lv": "لتونیایی",
  "langName.mi": "مائوری",
  "langName.mn": "مغولی",
  "langName.mr": "مراتی",
  "langName.ms": "مالایی",
  "langName.mt": "مالتی",
  "langName.my": "برمه‌ای",
  "langName.nb": "نروژی (بوک‌مُل)",
  "langName.nb-no": "نروژی (بوک‌مُل، نروژ)",
  "langName.ne": "نپالی",
  "langName.nl": "هلندی",
  "langName.nl-be": "فلمنگی",
  "langName.nn": "نروژی (نی‌نُشک)",
  "langName.nv": "ناواهو",
  "langName.ota": "ترکی (عثمانی)",
  "langName.pa": "پنجابی",
  "langName.peo": "فارسی (باستان)",
  "langName.pl": "لهستانی",
  "langName.ps": "پشتو",
  "langName.pt": "پرتغالی",
  "langName.pt-br": "پرتغالی (برزیل)",
  "langName.pt-pt": "پرتغالی (پرتغال)",
  "langName.qu": "کچوایی",
  "langName.ro": "رومانیایی",
  "langName.ru": "روسی",
  "langName.rw": "کینیارواندا",
  "langName.sa": "سانسکریت",
  "langName.se": "سامی (شمالی)",
  "langName.si": "سینهالی",
  "langName.sk": "اسلواکی",
  "langName.sk-sk": "اسلواکی (اسلواکی)",
  "langName.sl": "اسلوونیایی",
  "langName.sl-si": "اسلوونیایی (اسلوونی)",
  "langName.sma": "سامی (جنوبی)",
  "langName.sme": "سامی (شمالی)",
  "langName.smj": "سامی (لوله)",
  "langName.sn": "شونا",
  "langName.sr": "صربی",
  "langName.sr-latn": "صربی (لاتین)",
  "langName.sv": "سوئدی",
  "langName.sv-se": "سوئدی (سوئد)",
  "langName.sw": "سواحیلی",
  "langName.sw-ke": "سواحیلی (کنیا)",
  "langName.sw-tz": "سواحیلی (تانزانیا)",
  "langName.syc": "سریانی (کلاسیک)",
  "langName.ta": "تامیلی",
  "langName.te": "تلوگو",
  "langName.tg": "تاجیکی",
  "langName.th": "تایلندی",
  "langName.th-th": "تایلندی (تایلند)",
  "langName.tk": "ترکمنی",
  "langName.tl": "تاگالوگ",
  "langName.tr": "ترکی",
  "langName.tr-tr": "ترکی (ترکیه)",
  "langName.tt": "تاتاری",
  "langName.ug": "اویغوری",
  "langName.uk": "اوکراینی",
  "langName.ur": "اردو",
  "langName.uz": "ازبکی",
  "langName.vi": "ویتنامی",
  "langName.wo": "ولوف",
  "langName.xh": "خوسا",
  "langName.yi": "یدی",
  "langName.yo": "یوروبا",
  "langName.yua": "مایا (یوکاتک)",
  "langName.zh": "چینی",
  "langName.zh-cn": "چینی (ساده‌شده)",
  "langName.zh-hans": "چینی (ساده‌شده)",
  "langName.zh-hant": "چینی (سنتی)",
  "langName.zh-hk": "چینی (هنگ کنگ)",
  "langName.zh-sg": "چینی (سنگاپور)",
  "langName.zh-tw": "چینی (تایوان)",
  "langName.zu": "زولو",
  "langName.zu-za": "زولو (آفریقای جنوبی)"
});