tinymce.addI18n('fa_IR', {
  "-Language Not Set-": "-زبان تنظیم نشده-",
  "Choose from list": "انتخاب از فهرست",
  "Choose languages": "انتخاب زبان‌ها",
  "Choose up to six languages": "حداکثر شش زبان انتخاب کنید",
  "Configure languages": "پیکربندی زبان‌ها",
  "Current language:": "زبان فعلی:",
  "Enter a valid language code with no spaces. Or, press cancel.": "کد زبان معتبر بدون فاصله وارد کنید. یا لغو را فشار دهید.",
  "Enter manually": "وارد کردن دستی",
  "Enter new lang code (e.g., \"en-US\"):": "کد زبان جدید را وارد کنید (مثال: \"fa-IR\"):",
  "Indicate current language": "نشان دادن زبان فعلی",
  "Manually enter language {{number}}:": "وارد کردن دستی زبان {{number}}:",
  "New Language:": "زبان جدید:",
  "None": "هیچ",
  "Other - Enter manually": "سایر - وارد کردن دستی",
  "Really remove all language markup from the document?": "واقعاً تمام نشانه‌گذاری زبان از سند حذف شود؟",
  "Remove All lang markup": "حذف تمام نشانه‌گذاری زبان",
  "Remove Language Markup": "حذف نشانه‌گذاری زبان",
  "Remove current lang value": "حذف مقدار زبان فعلی",
  "Reveal lang markup": "نمایش نشانه‌گذاری زبان",
  "Select language {{number}}:": "انتخاب زبان {{number}}:",
  "Select the document's default language.": "زبان پیش‌فرض سند را انتخاب کنید.",
  "Set default document language": "تنظیم زبان پیش‌فرض سند",
  "Set text language": "تنظیم زبان متن",
  "langName.af": "آفریکانس",
  "langName.af-za": "آفریکانس",
  "langName.ak": "آکان",
  "langName.am": "امهری",
  "langName.ar": "عربی",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "عربی",
  "langName.az": "ترکی آذربایجانی",
  "langName.be": "بلاروسی",
  "langName.bg": "بلغاری",
  "langName.bg-bg": "بلغاری",
  "langName.bho": "بوجپوری",
  "langName.bm": "بامبارایی",
  "langName.bn": "بنگالی",
  "langName.bo": "تبتی",
  "langName.bs": "بوسنیایی",
  "langName.ca": "کاتالان",
  "langName.cop": "قبطی",
  "langName.cr": "کریایی",
  "langName.cs": "چکی",
  "langName.cu": "اسلاوی کلیسایی",
  "langName.cy": "ولزی",
  "langName.da": "دانمارکی",
  "langName.de": "آلمانی",
  "langName.de-at": "آلمانی اتریش",
  "langName.de-ch": "آلمانی معیار سوئیس",
  "langName.de-de": "آلمانی",
  "langName.dv": "دیوهی",
  "langName.el": "یونانی",
  "langName.en": "انگلیسی",
  "langName.en-au": "انگلیسی استرالیا",
  "langName.en-ca": "انگلیسی کانادا",
  "langName.en-gb": "انگلیسی بریتانیا",
  "langName.en-ie": "انگلیسی (ایرلند)",
  "langName.en-in": "انگلیسی (هند)",
  "langName.en-tt": "انگلیسی (ترینیداد)",
  "langName.en-us": "انگلیسی آمریکا",
  "langName.en-za": "انگلیسی (آفریقای جنوبی)",
  "langName.eo": "اسپرانتو",
  "langName.es": "اسپانیایی",
  "langName.es-ar": "اسپانیایی (آرژانتین)",
  "langName.es-cl": "اسپانیایی (شیلی)",
  "langName.es-co": "اسپانیایی (کلمبیا)",
  "langName.es-cr": "",
  "langName.es-es": "اسپانیایی اروپا",
  "langName.es-mx": "اسپانیایی مکزیک",
  "langName.es-pe": "اسپانیایی (پرو)",
  "langName.et": "استونیایی",
  "langName.eu": "باسکی",
  "langName.fa": "فارسی",
  "langName.fa-af": "دری",
  "langName.fa-ir": "فارسی",
  "langName.ff": "فولانی",
  "langName.fi": "فنلاندی",
  "langName.fi-fi": "فنلاندی",
  "langName.fil": "فیلیپینی",
  "langName.fr": "فرانسوی",
  "langName.fr-be": "",
  "langName.fr-ca": "فرانسوی کانادا",
  "langName.fr-ch": "فرانسوی سوئیس",
  "langName.ga": "ایرلندی",
  "langName.gl": "گالیسیایی",
  "langName.grc": "یونانی کهن",
  "langName.ha": "هوسایی",
  "langName.he": "عبری",
  "langName.he-il": "عبری",
  "langName.hi": "هندی",
  "langName.hr": "کروات",
  "langName.hr-hr": "کروات",
  "langName.ht": "هائیتیایی",
  "langName.hu": "مجاری",
  "langName.hu-hu": "مجاری",
  "langName.hy": "ارمنی",
  "langName.id": "اندونزیایی",
  "langName.ig": "ایگبویی",
  "langName.is": "ایسلندی",
  "langName.it": "ایتالیایی",
  "langName.it-it": "ایتالیایی",
  "langName.iu": "اینوکتیتوت",
  "langName.ja": "ژاپنی",
  "langName.ja-jp": "ژاپنی",
  "langName.ka": "گرجی",
  "langName.kab": "قبایلی",
  "langName.kk": "قزاقی",
  "langName.km": "خمری",
  "langName.kn": "کانارا",
  "langName.ko": "کره‌ای",
  "langName.ko-kr": "کره‌ای",
  "langName.la": "لاتین",
  "langName.lkt": "لاکوتا",
  "langName.lo": "لائوسی",
  "langName.lt": "لیتوانیایی",
  "langName.lv": "لتونیایی",
  "langName.mi": "مائوری",
  "langName.mn": "مغولی",
  "langName.mr": "مراتی",
  "langName.ms": "مالایی",
  "langName.mt": "مالتی",
  "langName.my": "برمه‌ای",
  "langName.nb": "نروژی بوک‌مُل",
  "langName.nb-no": "نروژی بوک‌مُل",
  "langName.ne": "نپالی",
  "langName.nl": "هلندی",
  "langName.nl-be": "فلمنگی",
  "langName.nn": "نروژی نی‌نُشک",
  "langName.nv": "ناواهویی",
  "langName.ota": "ترکی عثمانی",
  "langName.pa": "پنجابی",
  "langName.peo": "فارسی باستان",
  "langName.pl": "لهستانی",
  "langName.ps": "پشتو",
  "langName.pt": "پرتغالی",
  "langName.pt-br": "پرتغالی برزیل",
  "langName.pt-pt": "پرتغالی اروپا",
  "langName.qu": "کچوایی",
  "langName.ro": "رومانیایی",
  "langName.ru": "روسی",
  "langName.rw": "کینیارواندایی",
  "langName.sa": "سانسکریت",
  "langName.se": "سامی شمالی",
  "langName.si": "سینهالی",
  "langName.sk-sk": "اسلواکی",
  "langName.sl": "اسلوونیایی",
  "langName.sl-si": "اسلوونیایی",
  "langName.sma": "سامی جنوبی",
  "langName.sme": "سامی شمالی",
  "langName.smj": "لوله سامی",
  "langName.sn": "شونایی",
  "langName.sr": "صربی",
  "langName.sr-latn": "",
  "langName.sv": "سوئدی",
  "langName.sv-se": "سوئدی",
  "langName.sw": "سواحیلی",
  "langName.sw-ke": "سواحیلی",
  "langName.sw-tz": "سواحیلی",
  "langName.syc": "سریانی کلاسیک",
  "langName.ta": "تامیلی",
  "langName.te": "تلوگویی",
  "langName.tg": "تاجیکی",
  "langName.th": "تایلندی",
  "langName.th-th": "تایلندی",
  "langName.tk": "ترکمنی",
  "langName.tl": "تاگالوگی",
  "langName.tr": "ترکی استانبولی",
  "langName.tr-tr": "ترکی استانبولی",
  "langName.tt": "تاتاری",
  "langName.ug": "اویغوری",
  "langName.uk": "اوکراینی",
  "langName.ur": "اردو",
  "langName.uz": "ازبکی",
  "langName.vi": "ویتنامی",
  "langName.wo": "ولوفی",
  "langName.xh": "خوسایی",
  "langName.yi": "یدی",
  "langName.yo": "یوروبایی",
  "langName.yua": "مایای یوکاتک",
  "langName.zh": "چینی",
  "langName.zh-cn": "چینی ساده‌شده",
  "langName.zh-hans": "چینی ساده‌شده",
  "langName.zh-hant": "چینی سنتی",
  "langName.zh-hk": "چینی (هنگ کنگ)",
  "langName.zh-sg": "",
  "langName.zh-tw": "چینی سنتی",
  "langName.zu": "زولویی",
  "langName.zu-za": "زولویی"
});