tinymce.addI18n("fa_IR", {
  "Current language:": "زبان فعلی:",
  "Set text language": "تنظیم زبان متن",
  "-Language Not Set-": "-زبان تنظیم نشده-",
  "Choose languages": "انتخاب زبان‌ها",
  "Remove Language Markup": "حذف نشانه‌گذاری زبان",
  "Remove current lang value": "حذف مقدار زبان فعلی",
  "Remove All lang markup": "حذف تمام نشانه‌گذاری زبان",
  "Configure languages": "پیکربندی زبان‌ها",
  "Set default document language": "تنظیم زبان پیش‌فرض سند",
  "Reveal lang markup": "نمایش نشانه‌گذاری زبان",
  "Indicate current language": "نشان دادن زبان فعلی",
  "Select the document's default language.": "زبان پیش‌فرض سند را انتخاب کنید.",
  "Choose from list": "انتخاب از فهرست",
  "Enter manually": "وارد کردن دستی",
  "None": "هیچ",
  "Other - Enter manually": "سایر - وارد کردن دستی",
  "New Language:": "زبان جدید:",
  "Enter new lang code (e.g., \"en-US\"):": "کد زبان جدید را وارد کنید (مثال: \"fa-IR\"):",
  "Choose up to six languages": "حداکثر شش زبان انتخاب کنید",
  "Select language {{number}}:": "انتخاب زبان {{number}}:",
  "Manually enter language {{number}}:": "وارد کردن دستی زبان {{number}}:",
  "Really remove all language markup from the document?": "واقعاً تمام نشانه‌گذاری زبان از سند حذف شود؟",
  "Enter a valid language code with no spaces. Or, press cancel.": "کد زبان معتبر بدون فاصله وارد کنید. یا لغو را فشار دهید.",
  "langName.af": "آفریکانس",
  "langName.ak": "آکان",
  "langName.ar": "عربی",
  "langName.az": "آذربایجانی",
  "langName.bg": "بلغاری",
  "langName.bho": "بوجپوری",
  "langName.bm": "بامبارا",
  "langName.bn": "بنگالی",
  "langName.bo": "تبتی",
  "langName.bs": "بوسنیایی",
  "langName.ca": "کاتالان؛ والنسیایی",
  "langName.cs": "چکی",
  "langName.cu": "بلغاری باستان",
  "langName.da": "دانمارکی",
  "langName.de": "آلمانی",
  "langName.el": "یونانی",
  "langName.en": "انگلیسی",
  "langName.en-au": "انگلیسی (استرالیا)",
  "langName.en-gb": "انگلیسی (انگلستان)",
  "langName.en-in": "انگلیسی (هند)",
  "langName.en-ie": "انگلیسی (ایرلند)",
  "langName.en-tt": "انگلیسی (ترینیداد)",
  "langName.en-us": "انگلیسی (ایالات متحده)",
  "langName.en-za": "انگلیسی (آفریقای جنوبی)",
  "langName.es": "اسپانیایی",
  "langName.es-ar": "اسپانیایی (آرژانتین)",
  "langName.es-cl": "اسپانیایی (شیلی)",
  "langName.es-co": "اسپانیایی (کلمبیا)",
  "langName.es-mx": "اسپانیایی (مکزیک)",
  "langName.es-pe": "اسپانیایی (پرو)",
  "langName.et": "استونیایی",
  "langName.eu": "باسکی",
  "langName.fa": "فارسی",
  "langName.fi": "فنلاندی",
  "langName.fr": "فرانسوی",
  "langName.fr-ca": "فرانسوی (کانادا)",
  "langName.gl": "گالیسیایی (اسپانیا)",
  "langName.he": "عبری",
  "langName.hi": "هندی",
  "langName.hr": "کرواتی",
  "langName.hu": "مجاری",
  "langName.id": "اندونزیایی",
  "langName.it": "ایتالیایی",
  "langName.ja": "ژاپنی",
  "langName.kk": "قزاقی",
  "langName.kn": "کانادا",
  "langName.ko": "کره‌ای",
  "langName.la": "لاتین",
  "langName.lkt": "لاکوتا",
  "langName.mn": "مغولی",
  "langName.mr": "مراتی",
  "langName.nb": "نروژی بوک‌مول",
  "langName.nl": "هلندی",
  "langName.nl-be": "هلندی (بلژیک)",
  "langName.nn": "نروژی نی‌نورشک",
  "langName.pl": "لهستانی",
  "langName.ps": "پشتو",
  "langName.pt": "پرتغالی، بین‌المللی",
  "langName.pt-br": "پرتغالی (برزیل)",
  "langName.qu": "کچوا",
  "langName.ro": "رومانیایی",
  "langName.ru": "روسی",
  "langName.sa": "سانسکریت",
  "langName.sk-sk": "اسلواکی",
  "langName.sl": "اسلوونیایی",
  "langName.sma": "سامی جنوبی",
  "langName.sme": "سامی شمالی",
  "langName.smj": "سامی لوله",
  "langName.sr": "صربی",
  "langName.sv": "سوئدی",
  "langName.sw": "سواحیلی",
  "langName.ta": "تامیل",
  "langName.te": "تلوگو",
  "langName.tg": "تاجیکی",
  "langName.th": "تایلندی",
  "langName.tr": "ترکی",
  "langName.ug": "اویغوری",
  "langName.uk": "اوکراینی",
  "langName.ur": "اردو",
  "langName.uz": "ازبکی",
  "langName.vi": "ویتنامی",
  "langName.wo": "ولوف",
  "langName.yi": "یدیش",
  "langName.yo": "یوروبا",
  "langName.yua": "مایای یوکاتک",
  "langName.zh": "چینی",
  "langName.zh-cn": "چینی (چین)",
  "langName.zh-hk": "چینی (هنگ کنگ)",
  "langName.zh-tw": "چینی (تایوان)",
  "langName.zh-hans": "چینی، ساده‌شده",
  "langName.zh-hant": "چینی، سنتی",
  "langName.zu": "زولو"
});