tinymce.addI18n('fa_IR', {
  "-Language Not Set-": "-زبان تنظیم نشده-",
  "Choose from list": "انتخاب از فهرست",
  "Choose languages": "انتخاب زبان‌ها",
  "Choose up to six languages": "حداکثر شش زبان انتخاب کنید",
  "Configure languages": "پیکربندی زبان‌ها",
  "Current language:": "زبان فعلی:",
  "Enter a valid language code with no spaces. Or, press cancel.": "کد زبان معتبر بدون فاصله وارد کنید. یا لغو را فشار دهید.",
  "Enter manually": "وارد کردن دستی",
  "Enter new lang code (e.g., \"en-US\"):": "کد زبان جدید را وارد کنید (مثال: \"fa-IR\"):",
  "Indicate current language": "نشان دادن زبان فعلی",
  "Manually enter language {{number}}:": "وارد کردن دستی زبان {{number}}:",
  "New Language:": "زبان جدید:",
  "None": "هیچ",
  "Other - Enter manually": "سایر - وارد کردن دستی",
  "Really remove all language markup from the document?": "واقعاً تمام نشانه‌گذاری زبان از سند حذف شود؟",
  "Remove All lang markup": "حذف تمام نشانه‌گذاری زبان",
  "Remove Language Markup": "حذف نشانه‌گذاری زبان",
  "Remove current lang value": "حذف مقدار زبان فعلی",
  "Reveal lang markup": "نمایش نشانه‌گذاری زبان",
  "Select language {{number}}:": "انتخاب زبان {{number}}:",
  "Select the document's default language.": "زبان پیش‌فرض سند را انتخاب کنید.",
  "Set default document language": "تنظیم زبان پیش‌فرض سند",
  "Set text language": "تنظیم زبان متن",
  "Afrikaans": "آفریکانس",
  "Afrikaans": "آفریکانس (آفریقای جنوبی)",
  "Akan": "آکان",
  "Amharic": "امهری",
  "Arabic": "عربی",
  "Arabic (Egypt)": "عربی (مصر)",
  "Arabic (Morocco)": "عربی (مراکش)",
  "Arabic (Saudi Arabia)": "عربی (عربستان سعودی)",
  "Azerbaijani": "آذربایجانی",
  "Belarusian": "بلاروسی",
  "Bulgarian": "بلغاری",
  "Bulgarian (Bulgaria)": "بلغاری (بلغارستان)",
  "Bhojpuri": "بوجپوری",
  "Bambara": "بامبارایی",
  "Bangla": "بنگالی",
  "Tibetan": "تبتی",
  "Bosnian": "بوسنیایی",
  "Catalan": "کاتالان",
  "Coptic": "قبطی",
  "Cree": "کری",
  "Czech": "چکی",
  "Church Slavic": "اسلاوی کلیسایی",
  "Welsh": "ولزی",
  "Danish": "دانمارکی",
  "German": "آلمانی",
  "German (Austria)": "آلمانی (اتریش)",
  "German (Switzerland)": "آلمانی (سوئیس)",
  "German (Germany)": "آلمانی (آلمان)",
  "Divehi": "دیوهی",
  "Greek": "یونانی",
  "English": "انگلیسی",
  "English (Australia)": "انگلیسی (استرالیا)",
  "English (Canada)": "انگلیسی (کانادا)",
  "English (United Kingdom)": "انگلیسی (پادشاهی متحده)",
  "English (Ireland)": "انگلیسی (ایرلند)",
  "English (India)": "انگلیسی (هند)",
  "English (Trinidad)": "انگلیسی (ترینیداد)",
  "English (United States)": "انگلیسی (ایالات متحده آمریکا)",
  "English (South Africa)": "انگلیسی (آفریقای جنوبی)",
  "Esperanto": "اسپرانتو",
  "Spanish": "اسپانیایی",
  "Spanish (Argentina)": "اسپانیایی (آرژانتین)",
  "Spanish (Chile)": "اسپانیایی (شیلی)",
  "Spanish (Colombia)": "اسپانیایی (کلمبیا)",
  "Spanish (Costa Rica)": "اسپانیایی (کاستاریکا)",
  "Spanish (Spain)": "اسپانیایی (اسپانیا)",
  "Spanish (Mexico)": "اسپانیایی (مکزیک)",
  "Spanish (Peru)": "اسپانیایی (پرو)",
  "Estonian": "استونیایی",
  "Basque": "باسکی",
  "Persian": "فارسی",
  "Dari": "دری",
  "Persian (Iran)": "فارسی (ایران)",
  "Fula": "فولانی",
  "Finnish": "فنلاندی",
  "Finnish (Finland)": "فنلاندی (فنلاند)",
  "Filipino": "فیلیپینی",
  "French": "فرانسوی",
  "French (Belgium)": "فرانسوی (بلژیک)",
  "French (Canada)": "فرانسوی (کانادا)",
  "French (Switzerland)": "فرانسوی (سوئیس)",
  "Irish": "ایرلندی",
  "Galician": "گالیسیایی",
  "Greek (Ancient)": "یونانی (کهن)",
  "Hausa": "هوسایی",
  "Hebrew": "عبری",
  "Hebrew (Israel)": "عبری (اسرائیل)",
  "Hindi": "هندی",
  "Croatian": "کرواتی",
  "Croatian (Croatia)": "کرواتی (کرواسی)",
  "Haitian Creole": "کریول هائیتی",
  "Hungarian": "مجاری",
  "Hungarian (Hungary)": "مجاری (مجارستان)",
  "Armenian": "ارمنی",
  "Indonesian": "اندونزیایی",
  "Igbo": "ایگبو",
  "Icelandic": "ایسلندی",
  "Italian": "ایتالیایی",
  "Italian (Italy)": "ایتالیایی (ایتالیا)",
  "Inuktitut": "اینوکتیتوت",
  "Japanese": "ژاپنی",
  "Japanese (Japan)": "ژاپنی (ژاپن)",
  "Georgian": "گرجی",
  "Kabyle": "قبایلی",
  "Kazakh": "قزاقی",
  "Khmer": "خمری",
  "Kannada": "کانارا",
  "Korean": "کره‌ای",
  "Korean (Korea)": "کره‌ای (کره)",
  "Latin": "لاتین",
  "Lakota": "لاکوتا",
  "Lao": "لائوسی",
  "Lithuanian": "لیتوانیایی",
  "Latvian": "لتونیایی",
  "Māori": "مائوری",
  "Mongolian": "مغولی",
  "Marathi": "مراتی",
  "Malay": "مالایی",
  "Maltese": "مالتی",
  "Burmese": "برمه‌ای",
  "Norwegian (Bokmål)": "نروژی (بوک‌مُل)",
  "Norwegian (Bokmål, Norway)": "نروژی (بوک‌مُل، نروژ)",
  "Nepali": "نپالی",
  "Dutch": "هلندی",
  "Flemish": "فلمنگی",
  "Norwegian (Nynorsk)": "نروژی (نی‌نُشک)",
  "Navajo": "ناواهو",
  "Turkish (Ottoman)": "ترکی (عثمانی)",
  "Punjabi": "پنجابی",
  "Persian (Old)": "فارسی (باستان)",
  "Polish": "لهستانی",
  "Pashto": "پشتو",
  "Portuguese": "پرتغالی",
  "Portuguese (Brazil)": "پرتغالی (برزیل)",
  "Portuguese (Portugal)": "پرتغالی (پرتغال)",
  "Quechua": "کچوایی",
  "Romanian": "رومانیایی",
  "Russian": "روسی",
  "Kinyarwanda": "کینیارواندا",
  "Sanskrit": "سانسکریت",
  "Sami (Northern)": "سامی (شمالی)",
  "Sinhala": "سینهالی",
  "Slovak": "اسلواکی",
  "Slovak (Slovakia)": "اسلواکی (اسلواکی)",
  "Slovenian": "اسلوونیایی",
  "Slovenian (Slovenia)": "اسلوونیایی (اسلوونی)",
  "Sami (Southern)": "سامی (جنوبی)",
  "Sami (Northern)": "سامی (شمالی)",
  "Sami (Lule)": "سامی (لوله)",
  "Shona": "شونا",
  "Serbian": "صربی",
  "Serbian (Latin)": "صربی (لاتین)",
  "Swedish": "سوئدی",
  "Swedish (Sweden)": "سوئدی (سوئد)",
  "Swahili": "سواحیلی",
  "Swahili (Kenya)": "سواحیلی (کنیا)",
  "Swahili (Tanzania)": "سواحیلی (تانزانیا)",
  "Syriac (Classical)": "سریانی (کلاسیک)",
  "Tamil": "تامیلی",
  "Telugu": "تلوگو",
  "Tajik": "تاجیکی",
  "Thai": "تایلندی",
  "Thai (Thailand)": "تایلندی (تایلند)",
  "Turkmen": "ترکمنی",
  "Tagalog": "تاگالوگ",
  "Turkish": "ترکی",
  "Turkish (Turkey)": "ترکی (ترکیه)",
  "Tatar": "تاتاری",
  "Uyghur": "اویغوری",
  "Ukrainian": "اوکراینی",
  "Urdu": "اردو",
  "Uzbek": "ازبکی",
  "Vietnamese": "ویتنامی",
  "Wolof": "ولوف",
  "Xhosa": "خوسا",
  "Yiddish": "یدی",
  "Yoruba": "یوروبا",
  "Maya (Yucatec)": "مایا (یوکاتک)",
  "Chinese": "چینی",
  "Chinese (Simplified)": "چینی (ساده‌شده)",
  "Chinese (Simplified)": "چینی (ساده‌شده)",
  "Chinese (Traditional)": "چینی (سنتی)",
  "Chinese (Hong Kong)": "چینی (هنگ کنگ)",
  "Chinese (Singapore)": "چینی (سنگاپور)",
  "Chinese (Traditional)": "چینی (تایوان)",
  "Zulu": "زولو",
  "Zulu": "زولو (آفریقای جنوبی)"
});