tinymce.addI18n("fi_FI", {
  "Current language:": "Nykyinen kieli:",
  "Set text language": "Aseta tekstin kieli",
  "-Language Not Set-": "-Kieltä ei asetettu-",
  "Choose languages": "Valitse kielet",
  "Remove Language Markup": "Poista kielimerkinnät",
  "Remove current lang value": "Poista nykyinen kieliarvo",
  "Remove All lang markup": "Poista kaikki kielimerkinnät",
  "Configure languages": "Määritä kielet",
  "Set default document language": "Aseta dokumentin oletuskieli",
  "Reveal lang markup": "Näytä kielimerkinnät",
  "Indicate current language": "Ilmoita nykyinen kieli",
  "Select the document's default language.": "Valitse dokumentin oletuskieli.",
  "Choose from list": "Valitse listasta",
  "Enter manually": "Syötä käsin",
  "None": "Ei mitään",
  "Other - Enter manually": "Muu - Syötä käsin",
  "New Language:": "Uusi kieli:",
  "Enter new lang code (e.g., \"en-US\"):": "Syötä uusi kielikoodi (esim. \"fi-FI\"):",
  "Choose up to six languages": "Valitse enintään kuusi kieltä",
  "Select language {{number}}:": "Valitse kieli {{number}}:",
  "Manually enter language {{number}}:": "Syötä kieli {{number}} käsin:",
  "Really remove all language markup from the document?": "Poistetaanko todella kaikki kielimerkinnät dokumentista?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Syötä kelvollinen kielikoodi ilman välilyöntejä. Tai paina peruuta.",
  "langName.af": "Afrikaans",
  "langName.ak": "Akan",
  "langName.ar": "Arabia",
  "langName.az": "Azeri",
  "langName.bg": "Bulgaria",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengali",
  "langName.bo": "Tiibet",
  "langName.bs": "Bosnia",
  "langName.ca": "Katalaani; Valencian",
  "langName.cs": "Tsekki",
  "langName.cu": "Muinaisbulgaria",
  "langName.da": "Tanska",
  "langName.de": "Saksa",
  "langName.el": "Kreikka",
  "langName.en": "Englanti",
  "langName.en-au": "Englanti (Australia)",
  "langName.en-gb": "Englanti (Iso-Britannia)",
  "langName.en-in": "Englanti (Intia)",
  "langName.en-ie": "Englanti (Irlanti)",
  "langName.en-tt": "Englanti (Trinidad)",
  "langName.en-us": "Englanti (Yhdysvallat)",
  "langName.en-za": "Englanti (Etelä-Afrikka)",
  "langName.es": "Espanja",
  "langName.es-ar": "Espanja (Argentiina)",
  "langName.es-cl": "Espanja (Chile)",
  "langName.es-co": "Espanja (Kolumbia)",
  "langName.es-mx": "Espanja (Meksiko)",
  "langName.es-pe": "Espanja (Peru)",
  "langName.et": "Viro",
  "langName.eu": "Baski",
  "langName.fa": "Persia",
  "langName.fi": "Suomi",
  "langName.fr": "Ranska",
  "langName.fr-ca": "Ranska (Kanada)",
  "langName.gl": "Galicia (Espanja)",
  "langName.he": "Heprea",
  "langName.hi": "Hindi",
  "langName.hr": "Kroatia",
  "langName.hu": "Unkari",
  "langName.id": "Indonesia",
  "langName.it": "Italia",
  "langName.ja": "Japani",
  "langName.kk": "Kazakki",
  "langName.kn": "Kannada",
  "langName.ko": "Korea",
  "langName.la": "Latina",
  "langName.lkt": "Lakota",
  "langName.mn": "Mongoli",
  "langName.mr": "Marathi",
  "langName.nb": "Norja Bokmål",
  "langName.nl": "Hollanti",
  "langName.nl-be": "Hollanti (Belgia)",
  "langName.nn": "Norja Nynorsk",
  "langName.pl": "Puola",
  "langName.ps": "Paštu",
  "langName.pt": "Portugali, kansainvälinen",
  "langName.pt-br": "Portugali (Brasilia)",
  "langName.qu": "Ketšua",
  "langName.ro": "Romania",
  "langName.ru": "Venäjä",
  "langName.sa": "Sanskrit",
  "langName.sk-sk": "Slovakia",
  "langName.sl": "Slovenia",
  "langName.sma": "Eteläsaame",
  "langName.sme": "Pohjoissaame",
  "langName.smj": "Luulajansaame",
  "langName.sr": "Serbia",
  "langName.sv": "Ruotsi",
  "langName.sw": "Swahili",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tadžikki",
  "langName.th": "Thai",
  "langName.tr": "Turkki",
  "langName.ug": "Uiguuri",
  "langName.uk": "Ukraina",
  "langName.ur": "Urdu",
  "langName.uz": "Uzbekki",
  "langName.vi": "Vietnam",
  "langName.wo": "Wolof",
  "langName.yi": "Jiddiš",
  "langName.yo": "Joruba",
  "langName.yua": "Jukateekin maya",
  "langName.zh": "Kiina",
  "langName.zh-cn": "Kiina (Kiina)",
  "langName.zh-hk": "Kiina (Hongkong)",
  "langName.zh-tw": "Kiina (Taiwan)",
  "langName.zh-hans": "Kiina, yksinkertaistettu",
  "langName.zh-hant": "Kiina, perinteinen",
  "langName.zu": "Zulu"
});