tinymce.addI18n('fi_FI', {
  "-Language Not Set-": "-Kieltä ei asetettu-",
  "Choose from list": "Valitse listasta",
  "Choose languages": "Valitse kielet",
  "Choose up to six languages": "Valitse enintään kuusi kieltä",
  "Configure languages": "Määritä kielet",
  "Current language:": "Nykyinen kieli:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Syötä kelvollinen kielikoodi ilman välilyöntejä. Tai paina peruuta.",
  "Enter manually": "Syötä käsin",
  "Enter new lang code (e.g., \"en-US\"):": "Syötä uusi kielikoodi (esim. \"fi-FI\"):",
  "Indicate current language": "Ilmoita nykyinen kieli",
  "Manually enter language {{number}}:": "Syötä kieli {{number}} käsin:",
  "New Language:": "Uusi kieli:",
  "None": "Ei mitään",
  "Other - Enter manually": "Muu - Syötä käsin",
  "Really remove all language markup from the document?": "Poistetaanko todella kaikki kielimerkinnät dokumentista?",
  "Remove All lang markup": "Poista kaikki kielimerkinnät",
  "Remove Language Markup": "Poista kielimerkinnät",
  "Remove current lang value": "Poista nykyinen kieliarvo",
  "Reveal lang markup": "Näytä kielimerkinnät",
  "Select language {{number}}:": "Valitse kieli {{number}}:",
  "Select the document's default language.": "Valitse dokumentin oletuskieli.",
  "Set default document language": "Aseta dokumentin oletuskieli",
  "Set text language": "Aseta tekstin kieli",
  "langName.af": "afrikaans",
  "langName.af-za": "afrikaans (Etelä-Afrikka)",
  "langName.ak": "akan",
  "langName.am": "amhara",
  "langName.ar": "arabia",
  "langName.ar-eg": "arabia (Egypti)",
  "langName.ar-ma": "arabia (Marokko)",
  "langName.ar-sa": "arabia (Saudi-Arabia)",
  "langName.az": "azeri",
  "langName.be": "valkovenäjä",
  "langName.bg": "bulgaria",
  "langName.bg-bg": "bulgaria (Bulgaria)",
  "langName.bho": "bhodžpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengali",
  "langName.bo": "tiibet",
  "langName.bs": "bosnia",
  "langName.ca": "katalaani",
  "langName.cop": "kopti",
  "langName.cr": "cree",
  "langName.cs": "tšekki",
  "langName.cu": "kirkkoslaavi",
  "langName.cy": "kymri",
  "langName.da": "tanska",
  "langName.de": "saksa",
  "langName.de-at": "saksa (Itävalta)",
  "langName.de-ch": "saksa (Sveitsi)",
  "langName.de-de": "saksa (Saksa)",
  "langName.dv": "divehi",
  "langName.el": "kreikka",
  "langName.en": "englanti",
  "langName.en-au": "englanti (Australia)",
  "langName.en-ca": "englanti (Kanada)",
  "langName.en-gb": "englanti (Iso-Britannia)",
  "langName.en-ie": "englanti (Irlanti)",
  "langName.en-in": "englanti (Intia)",
  "langName.en-tt": "englanti (Trinidad)",
  "langName.en-us": "englanti (Yhdysvallat)",
  "langName.en-za": "englanti (Etelä-Afrikka)",
  "langName.eo": "esperanto",
  "langName.es": "espanja",
  "langName.es-ar": "espanja (Argentiina)",
  "langName.es-cl": "espanja (Chile)",
  "langName.es-co": "espanja (Kolumbia)",
  "langName.es-cr": "espanja (Costa Rica)",
  "langName.es-es": "espanja (Espanja)",
  "langName.es-mx": "espanja (Meksiko)",
  "langName.es-pe": "espanja (Peru)",
  "langName.et": "viro",
  "langName.eu": "baski",
  "langName.fa": "persia",
  "langName.fa-af": "dari",
  "langName.fa-ir": "persia (Iran)",
  "langName.ff": "fulani",
  "langName.fi": "suomi",
  "langName.fi-fi": "suomi (Suomi)",
  "langName.fil": "filipino",
  "langName.fr": "ranska",
  "langName.fr-be": "ranska (Belgia)",
  "langName.fr-ca": "ranska (Kanada)",
  "langName.fr-ch": "ranska (Sveitsi)",
  "langName.ga": "iiri",
  "langName.gl": "galicia",
  "langName.grc": "kreikka (muinainen)",
  "langName.ha": "hausa",
  "langName.he": "heprea",
  "langName.he-il": "heprea (Israel)",
  "langName.hi": "hindi",
  "langName.hr": "kroatia",
  "langName.hr-hr": "kroatia (Kroatia)",
  "langName.ht": "haiti",
  "langName.hu": "unkari",
  "langName.hu-hu": "unkari (Unkari)",
  "langName.hy": "armenia",
  "langName.id": "indonesia",
  "langName.ig": "igbo",
  "langName.is": "islanti",
  "langName.it": "italia",
  "langName.it-it": "italia (Italia)",
  "langName.iu": "inuktitut",
  "langName.ja": "japani",
  "langName.ja-jp": "japani (Japani)",
  "langName.ka": "georgia",
  "langName.kab": "kabyyli",
  "langName.kk": "kazakki",
  "langName.km": "khmer",
  "langName.kn": "kannada",
  "langName.ko": "korea",
  "langName.ko-kr": "korea (Korea)",
  "langName.la": "latina",
  "langName.lkt": "lakota",
  "langName.lo": "lao",
  "langName.lt": "liettua",
  "langName.lv": "latvia",
  "langName.mi": "maori",
  "langName.mn": "mongoli",
  "langName.mr": "marathi",
  "langName.ms": "malaiji",
  "langName.mt": "malta",
  "langName.my": "burma",
  "langName.nb": "norja (bokmål)",
  "langName.nb-no": "norja (bokmål, Norja)",
  "langName.ne": "nepali",
  "langName.nl": "hollanti",
  "langName.nl-be": "flaami",
  "langName.nn": "norja (nynorsk)",
  "langName.nv": "navajo",
  "langName.ota": "turkki (osmani)",
  "langName.pa": "pandžabi",
  "langName.peo": "persia (muinainen)",
  "langName.pl": "puola",
  "langName.ps": "paštu",
  "langName.pt": "portugali",
  "langName.pt-br": "portugali (Brasilia)",
  "langName.pt-pt": "portugali (Portugali)",
  "langName.qu": "ketšua",
  "langName.ro": "romania",
  "langName.ru": "venäjä",
  "langName.rw": "ruanda",
  "langName.sa": "sanskrit",
  "langName.se": "saame (pohjoinen)",
  "langName.si": "sinhala",
  "langName.sk": "slovakki",
  "langName.sk-sk": "slovakki (Slovakia)",
  "langName.sl": "sloveeni",
  "langName.sl-si": "sloveeni (Slovenia)",
  "langName.sma": "saame (eteläinen)",
  "langName.sme": "saame (pohjoinen)",
  "langName.smj": "saame (luulaja)",
  "langName.sn": "šona",
  "langName.sr": "serbia",
  "langName.sr-latn": "serbia (latinalainen)",
  "langName.sv": "ruotsi",
  "langName.sv-se": "ruotsi (Ruotsi)",
  "langName.sw": "swahili",
  "langName.sw-ke": "swahili (Kenia)",
  "langName.sw-tz": "swahili (Tansania)",
  "langName.syc": "syyria (muinainen)",
  "langName.ta": "tamili",
  "langName.te": "telugu",
  "langName.tg": "tadžikki",
  "langName.th": "thai",
  "langName.th-th": "thai (Thaimaa)",
  "langName.tk": "turkmeeni",
  "langName.tl": "tagalog",
  "langName.tr": "turkki",
  "langName.tr-tr": "turkki (Turkki)",
  "langName.tt": "tataari",
  "langName.ug": "uiguuri",
  "langName.uk": "ukraina",
  "langName.ur": "urdu",
  "langName.uz": "uzbekki",
  "langName.vi": "vietnam",
  "langName.wo": "wolof",
  "langName.xh": "xhosa",
  "langName.yi": "jiddiš",
  "langName.yo": "joruba",
  "langName.yua": "maya (jukateekin)",
  "langName.zh": "kiina",
  "langName.zh-cn": "kiina (yksinkertaistettu)",
  "langName.zh-hans": "kiina (yksinkertaistettu)",
  "langName.zh-hant": "kiina (perinteinen)",
  "langName.zh-hk": "kiina (Hongkong)",
  "langName.zh-sg": "kiina (Singapore)",
  "langName.zh-tw": "kiina (perinteinen)",
  "langName.zu": "zulu",
  "langName.zu-za": "zulu (Etelä-Afrikka)"
});