tinymce.addI18n('fr', {
  "-Language Not Set-": "-Langue Non Définie-",
  "Choose from list": "Choisir dans la liste",
  "Choose languages": "Choisir les langues",
  "Choose up to six languages": "Choisir jusqu'à six langues",
  "Configure languages": "Configurer les langues",
  "Current language:": "Langue actuelle :",
  "Enter a valid language code with no spaces. Or, press cancel.": "Saisir un code de langue valide sans espaces. Ou appuyer sur annuler.",
  "Enter manually": "Saisir manuellement",
  "Enter new lang code (e.g., \"en-US\"):": "Saisir le nouveau code de langue (ex. \"fr-FR\") :",
  "Indicate current language": "Indiquer la langue actuelle",
  "Manually enter language {{number}}:": "Saisir manuellement la langue {{number}} :",
  "New Language:": "Nouvelle Langue :",
  "None": "Aucun",
  "Other - Enter manually": "Autre - Saisir manuellement",
  "Really remove all language markup from the document?": "Vraiment supprimer tout le balisage de langue du document ?",
  "Remove All lang markup": "Supprimer tout le balisage de langue",
  "Remove Language Markup": "Supprimer le Balisage de Langue",
  "Remove current lang value": "Supprimer la valeur de langue actuelle",
  "Reveal lang markup": "Révéler le balisage de langue",
  "Select language {{number}}:": "Sélectionner la langue {{number}} :",
  "Select the document's default language.": "Sélectionner la langue par défaut du document.",
  "Set default document language": "Définir la langue par défaut du document",
  "Set text language": "Définir la langue du texte",
  "langName.af": "afrikaans",
  "langName.af-za": "afrikaans (Afrique du Sud)",
  "langName.ak": "akan",
  "langName.am": "amharique",
  "langName.ar": "arabe",
  "langName.ar-eg": "arabe (Égypte)",
  "langName.ar-ma": "arabe (Maroc)",
  "langName.ar-sa": "arabe (Arabie Saoudite)",
  "langName.az": "azerbaïdjanais",
  "langName.be": "biélorusse",
  "langName.bg": "bulgare",
  "langName.bg-bg": "bulgare (Bulgarie)",
  "langName.bho": "bhodjpouri",
  "langName.bm": "bambara",
  "langName.bn": "bengali",
  "langName.bo": "tibétain",
  "langName.bs": "bosniaque",
  "langName.ca": "catalan",
  "langName.cop": "copte",
  "langName.cr": "cree",
  "langName.cs": "tchèque",
  "langName.cu": "slavon d'église",
  "langName.cy": "gallois",
  "langName.da": "danois",
  "langName.de": "allemand",
  "langName.de-at": "allemand (Autriche)",
  "langName.de-ch": "allemand (Suisse)",
  "langName.de-de": "allemand (Allemagne)",
  "langName.dv": "maldivien",
  "langName.el": "grec",
  "langName.en": "anglais",
  "langName.en-au": "anglais (Australie)",
  "langName.en-ca": "anglais (Canada)",
  "langName.en-gb": "anglais (Royaume-Uni)",
  "langName.en-ie": "anglais (Irlande)",
  "langName.en-in": "anglais (Inde)",
  "langName.en-tt": "anglais (Trinité)",
  "langName.en-us": "anglais (États-Unis)",
  "langName.en-za": "anglais (Afrique du Sud)",
  "langName.eo": "espéranto",
  "langName.es": "espagnol",
  "langName.es-ar": "espagnol (Argentine)",
  "langName.es-cl": "espagnol (Chili)",
  "langName.es-co": "espagnol (Colombie)",
  "langName.es-cr": "espagnol (Costa Rica)",
  "langName.es-es": "espagnol (Espagne)",
  "langName.es-mx": "espagnol (Mexique)",
  "langName.es-pe": "espagnol (Pérou)",
  "langName.et": "estonien",
  "langName.eu": "basque",
  "langName.fa": "persan",
  "langName.fa-af": "dari",
  "langName.fa-ir": "persan (Iran)",
  "langName.ff": "peul",
  "langName.fi": "finnois",
  "langName.fi-fi": "finnois (Finlande)",
  "langName.fil": "filipino",
  "langName.fr": "français",
  "langName.fr-be": "français (Belgique)",
  "langName.fr-ca": "français (Canada)",
  "langName.fr-ch": "français (Suisse)",
  "langName.ga": "irlandais",
  "langName.gl": "galicien",
  "langName.grc": "grec ancien",
  "langName.ha": "haoussa",
  "langName.he": "hébreu",
  "langName.he-il": "hébreu (Israël)",
  "langName.hi": "hindi",
  "langName.hr": "croate",
  "langName.hr-hr": "croate (Croatie)",
  "langName.ht": "créole haïtien",
  "langName.hu": "hongrois",
  "langName.hu-hu": "hongrois (Hongrie)",
  "langName.hy": "arménien",
  "langName.id": "indonésien",
  "langName.ig": "igbo",
  "langName.is": "islandais",
  "langName.it": "italien",
  "langName.it-it": "italien (Italie)",
  "langName.iu": "inuktitut",
  "langName.ja": "japonais",
  "langName.ja-jp": "japonais (Japon)",
  "langName.ka": "géorgien",
  "langName.kab": "kabyle",
  "langName.kk": "kazakh",
  "langName.km": "khmer",
  "langName.kn": "kannada",
  "langName.ko": "coréen",
  "langName.ko-kr": "coréen (Corée)",
  "langName.la": "latin",
  "langName.lkt": "lakota",
  "langName.lo": "lao",
  "langName.lt": "lituanien",
  "langName.lv": "letton",
  "langName.mi": "maori",
  "langName.mn": "mongol",
  "langName.mr": "marathi",
  "langName.ms": "malais",
  "langName.mt": "maltais",
  "langName.my": "birman",
  "langName.nb": "norvégien (bokmål)",
  "langName.nb-no": "norvégien (bokmål, Norvège)",
  "langName.ne": "népalais",
  "langName.nl": "néerlandais",
  "langName.nl-be": "flamand",
  "langName.nn": "norvégien (nynorsk)",
  "langName.nv": "navajo",
  "langName.ota": "turc ottoman",
  "langName.pa": "pendjabi",
  "langName.peo": "persan ancien",
  "langName.pl": "polonais",
  "langName.ps": "pachto",
  "langName.pt": "portugais",
  "langName.pt-br": "portugais (Brésil)",
  "langName.pt-pt": "portugais (Portugal)",
  "langName.qu": "quechua",
  "langName.ro": "roumain",
  "langName.ru": "russe",
  "langName.rw": "kinyarwanda",
  "langName.sa": "sanskrit",
  "langName.se": "same du Nord",
  "langName.si": "cingalais",
  "langName.sk": "slovaque",
  "langName.sk-sk": "slovaque (Slovaquie)",
  "langName.sl": "slovène",
  "langName.sl-si": "slovène (Slovénie)",
  "langName.sma": "same du Sud",
  "langName.sme": "same du Nord",
  "langName.smj": "same de Lule",
  "langName.sn": "shona",
  "langName.sr": "serbe",
  "langName.sr-latn": "serbe (latin)",
  "langName.sv": "suédois",
  "langName.sv-se": "suédois (Suède)",
  "langName.sw": "swahili",
  "langName.sw-ke": "swahili (Kenya)",
  "langName.sw-tz": "swahili (Tanzanie)",
  "langName.syc": "syriaque classique",
  "langName.ta": "tamoul",
  "langName.te": "télougou",
  "langName.tg": "tadjik",
  "langName.th": "thaï",
  "langName.th-th": "thaï (Thaïlande)",
  "langName.tk": "turkmène",
  "langName.tl": "tagalog",
  "langName.tr": "turc",
  "langName.tr-tr": "turc (Turquie)",
  "langName.tt": "tatar",
  "langName.ug": "ouïghour",
  "langName.uk": "ukrainien",
  "langName.ur": "ourdou",
  "langName.uz": "ouzbek",
  "langName.vi": "vietnamien",
  "langName.wo": "wolof",
  "langName.xh": "xhosa",
  "langName.yi": "yiddish",
  "langName.yo": "yoruba",
  "langName.yua": "maya du Yucatan",
  "langName.zh": "chinois",
  "langName.zh-cn": "chinois (simplifié)",
  "langName.zh-hans": "chinois (simplifié)",
  "langName.zh-hant": "chinois (traditionnel)",
  "langName.zh-hk": "chinois (Hong Kong)",
  "langName.zh-sg": "chinois (Singapour)",
  "langName.zh-tw": "chinois (traditionnel)",
  "langName.zu": "zoulou",
  "langName.zu-za": "zoulou (Afrique du Sud)"
});