tinymce.addI18n("fr_FR", {
  "Current language:": "Langue actuelle :",
  "Set text language": "Définir la langue du texte",
  "-Language Not Set-": "-Langue non définie-",
  "Choose languages": "Choisir les langues",
  "Remove Language Markup": "Supprimer le balisage de langue",
  "Remove current lang value": "Supprimer la valeur de langue actuelle",
  "Remove All lang markup": "Supprimer tout le balisage de langue",
  "Configure languages": "Configurer les langues",
  "Set default document language": "Définir la langue par défaut du document",
  "Reveal lang markup": "Révéler le balisage de langue",
  "Indicate current language": "Indiquer la langue actuelle",
  "Select the document's default language.": "Sélectionnez la langue par défaut du document.",
  "Choose from list": "Choisir dans la liste",
  "Enter manually": "Saisir manuellement",
  "None": "Aucune",
  "Other - Enter manually": "Autre - Saisir manuellement",
  "New Language:": "Nouvelle langue :",
  "Enter new lang code (e.g., \"en-US\"):": "Saisir le nouveau code de langue (ex. « fr-FR ») :",
  "Choose up to six languages": "Choisir jusqu'à six langues",
  "Select language {{number}}:": "Sélectionner la langue {{number}} :",
  "Manually enter language {{number}}:": "Saisir manuellement la langue {{number}} :",
  "Really remove all language markup from the document?": "Voulez-vous vraiment supprimer tout le balisage de langue du document ?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Saisir un code de langue valide sans espaces. Ou appuyer sur annuler.",
  "langName.af": "Afrikaans",
  "langName.ak": "Akan",
  "langName.ar": "Arabe",
  "langName.az": "Azéri",
  "langName.bg": "Bulgare",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengali",
  "langName.bo": "Tibétain",
  "langName.bs": "Bosniaque",
  "langName.ca": "Catalan ; Valencien",
  "langName.cs": "Tchèque",
  "langName.cu": "Vieux bulgare",
  "langName.da": "Danois",
  "langName.de": "Allemand",
  "langName.el": "Grec",
  "langName.en": "Anglais",
  "langName.en-au": "Anglais (Australie)",
  "langName.en-gb": "Anglais (Royaume-Uni)",
  "langName.en-in": "Anglais (Inde)",
  "langName.en-ie": "Anglais (Irlande)",
  "langName.en-tt": "Anglais (Trinité)",
  "langName.en-us": "Anglais (États-Unis)",
  "langName.en-za": "Anglais (Afrique du Sud)",
  "langName.es": "Espagnol",
  "langName.es-ar": "Espagnol (Argentine)",
  "langName.es-cl": "Espagnol (Chili)",
  "langName.es-co": "Espagnol (Colombie)",
  "langName.es-mx": "Espagnol (Mexique)",
  "langName.es-pe": "Espagnol (Pérou)",
  "langName.et": "Estonien",
  "langName.eu": "Basque",
  "langName.fa": "Persan",
  "langName.fi": "Finnois",
  "langName.fr": "Français",
  "langName.fr-ca": "Français (Canada)",
  "langName.gl": "Galicien (Espagne)",
  "langName.he": "Hébreu",
  "langName.hi": "Hindi",
  "langName.hr": "Croate",
  "langName.hu": "Hongrois",
  "langName.id": "Indonésien",
  "langName.it": "Italien",
  "langName.ja": "Japonais",
  "langName.kk": "Kazakh",
  "langName.kn": "Kannada",
  "langName.ko": "Coréen",
  "langName.la": "Latin",
  "langName.lkt": "Lakota",
  "langName.mn": "Mongol",
  "langName.mr": "Marathi",
  "langName.nb": "Norvégien bokmål",
  "langName.nl": "Néerlandais",
  "langName.nl-be": "Néerlandais (Belgique)",
  "langName.nn": "Norvégien nynorsk",
  "langName.pl": "Polonais",
  "langName.ps": "Pachto",
  "langName.pt": "Portugais international",
  "langName.pt-br": "Portugais (Brésil)",
  "langName.qu": "Quechua",
  "langName.ro": "Roumain",
  "langName.ru": "Russe",
  "langName.sa": "Sanskrit",
  "langName.sk-sk": "Slovaque",
  "langName.sl": "Slovène",
  "langName.sma": "Same du Sud",
  "langName.sme": "Same du Nord",
  "langName.smj": "Same de Lule",
  "langName.sr": "Serbe",
  "langName.sv": "Suédois",
  "langName.sw": "Swahili",
  "langName.ta": "Tamoul",
  "langName.te": "Télougou",
  "langName.tg": "Tadjik",
  "langName.th": "Thaï",
  "langName.tr": "Turc",
  "langName.ug": "Ouïghour",
  "langName.uk": "Ukrainien",
  "langName.ur": "Ourdou",
  "langName.uz": "Ouzbek",
  "langName.vi": "Vietnamien",
  "langName.wo": "Wolof",
  "langName.yi": "Yiddish",
  "langName.yo": "Yoruba",
  "langName.yua": "Maya yucatèque",
  "langName.zh": "Chinois",
  "langName.zh-cn": "Chinois (Chine)",
  "langName.zh-hk": "Chinois (Hong Kong)",
  "langName.zh-tw": "Chinois (Taïwan)",
  "langName.zh-hans": "Chinois simplifié",
  "langName.zh-hant": "Chinois traditionnel",
  "langName.zu": "Zoulou"
});