tinymce.addI18n("ga", {
  "Current language:": "Teanga reatha:",
  "Set text language": "Socraigh teanga téacs",
  "-Language Not Set-": "-Teanga gan Socrú-",
  "Choose languages": "Roghnaigh teangacha",
  "Remove Language Markup": "Bain Marcáil Teanga",
  "Remove current lang value": "Bain luach teanga reatha",
  "Remove All lang markup": "Bain gach marcáil teanga",
  "Configure languages": "Cumraigh teangacha",
  "Set default document language": "Socraigh teanga réamhshocraithe cáipéise",
  "Reveal lang markup": "Nocht marcáil teanga",
  "Indicate current language": "Taispeáin teanga reatha",
  "Select the document's default language.": "Roghnaigh teanga réamhshocraithe na cáipéise.",
  "Choose from list": "Roghnaigh ó liosta",
  "Enter manually": "Iontráil de láimh",
  "None": "Faic",
  "Other - Enter manually": "Eile - Iontráil de láimh",
  "New Language:": "Teanga Nua:",
  "Enter new lang code (e.g., \"en-US\"):": "Iontráil cód teanga nua (m.sh., \"en-US\"):",
  "Choose up to six languages": "Roghnaigh suas le sé theanga",
  "Select language {{number}}:": "Roghnaigh teanga {{number}}:",
  "Manually enter language {{number}}:": "Iontráil teanga {{number}} de láimh:",
  "Really remove all language markup from the document?": "Bain gach marcáil teanga ón gcáipéis i ndáiríre?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Iontráil cód teanga bailí gan spásanna. Nó, brúigh cealaigh.",
  "langName.af": "Afracáinis",
  "langName.ak": "Acáinis",
  "langName.ar": "Araibis",
  "langName.az": "Asarbaiseáinis",
  "langName.bg": "Bulgáiris",
  "langName.bho": "Bhójpúiris",
  "langName.bm": "Bambairis",
  "langName.bn": "Beangáilis",
  "langName.bo": "Tibéidis",
  "langName.bs": "Boisnis",
  "langName.ca": "Catalóinis; Vaileinsis",
  "langName.cs": "Seicis",
  "langName.cu": "Bulgáiris Ársa",
  "langName.da": "Danmhairgis",
  "langName.de": "Gearmáinis",
  "langName.el": "Gréigis",
  "langName.en": "Béarla",
  "langName.en-au": "Béarla (an Astráil)",
  "langName.en-gb": "Béarla (an Ríocht Aontaithe)",
  "langName.en-in": "Béarla (Indiach)",
  "langName.en-ie": "Béarla (Éire)",
  "langName.en-tt": "Béarla (Oileán na Tríonóide)",
  "langName.en-us": "Béarla (Stáit Aontaithe)",
  "langName.en-za": "Béarla (an Afraic Theas)",
  "langName.es": "Spáinnis",
  "langName.es-ar": "Spáinnis (an Airgintín)",
  "langName.es-cl": "Spáinnis (an tSile)",
  "langName.es-co": "Spáinnis (an Cholóim)",
  "langName.es-mx": "Spáinnis (Meicsiceo)",
  "langName.es-pe": "Spáinnis (Peiriú)",
  "langName.et": "Eastóinis",
  "langName.eu": "Bascais",
  "langName.fa": "Peirsis",
  "langName.fi": "Fionlainnis",
  "langName.fr": "Fraincis",
  "langName.fr-ca": "Fraincis (Ceanada)",
  "langName.gl": "Gailísis (an Spáinn)",
  "langName.he": "Eabhrais",
  "langName.hi": "Hiondúis",
  "langName.hr": "Cróitis",
  "langName.hu": "Ungáiris",
  "langName.id": "Indinéisis",
  "langName.it": "Iodáilis",
  "langName.ja": "Seapáinis",
  "langName.kk": "Casachstáinis",
  "langName.kn": "Cannadais",
  "langName.ko": "Cóiréis",
  "langName.la": "Laidin",
  "langName.lkt": "Lacótais",
  "langName.mn": "Mongóilis",
  "langName.mr": "Maraitis",
  "langName.nb": "Ioruais Bokmål",
  "langName.nl": "Ollainnis",
  "langName.nl-be": "Ollainnis (an Bheilg)",
  "langName.nn": "Ioruais Nynorsk",
  "langName.pl": "Polainnis",
  "langName.ps": "Paistis",
  "langName.pt": "Portaingéilis, Idirnáisiúnta",
  "langName.pt-br": "Portaingéilis, Brasaíl",
  "langName.qu": "Ceatsuais",
  "langName.ro": "Rómáinis",
  "langName.ru": "Rúisis",
  "langName.sa": "Sanscrait",
  "langName.sk-sk": "Slóvaicis",
  "langName.sl": "Slóivéinis",
  "langName.sma": "Samáis Theas",
  "langName.sme": "Samáis Tuaidh",
  "langName.smj": "Samáis Lule",
  "langName.sr": "Seirbis",
  "langName.sv": "Sualainnis",
  "langName.sw": "Svahílis",
  "langName.ta": "Tamailis",
  "langName.te": "Teileagúis",
  "langName.tg": "Táidsícis",
  "langName.th": "Téalainnis",
  "langName.tr": "Tuircis",
  "langName.ug": "Uighiúiris",
  "langName.uk": "Úcráinis",
  "langName.ur": "Urdúis",
  "langName.uz": "Úisbéicis",
  "langName.vi": "Vítneaimis",
  "langName.wo": "Volaifis",
  "langName.yi": "Giúdais",
  "langName.yo": "Iarúibis",
  "langName.yua": "Maidhis Iúcatáin",
  "langName.zh": "Sínis",
  "langName.zh-cn": "Sínis (an tSín)",
  "langName.zh-hk": "Sínis (Hong Cong)",
  "langName.zh-tw": "Sínis (an Téaváin)",
  "langName.zh-hans": "Sínis, Simplithe",
  "langName.zh-hant": "Sínis, Traidisiúnta",
  "langName.zu": "Súlúis"
});