tinymce.addI18n('ga', {
  "-Language Not Set-": "-Teanga gan Socrú-",
  "Choose from list": "Roghnaigh ó liosta",
  "Choose languages": "Roghnaigh teangacha",
  "Choose up to six languages": "Roghnaigh suas le sé theanga",
  "Configure languages": "Cumraigh teangacha",
  "Current language:": "Teanga reatha:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Iontráil cód teanga bailí gan spásanna. Nó, brúigh cealaigh.",
  "Enter manually": "Iontráil de láimh",
  "Enter new lang code (e.g., \"en-US\"):": "Iontráil cód teanga nua (m.sh., \"en-US\"):",
  "Indicate current language": "Taispeáin teanga reatha",
  "Manually enter language {{number}}:": "Iontráil teanga {{number}} de láimh:",
  "New Language:": "Teanga Nua:",
  "None": "Faic",
  "Other - Enter manually": "Eile - Iontráil de láimh",
  "Really remove all language markup from the document?": "Bain gach marcáil teanga ón gcáipéis i ndáiríre?",
  "Remove All lang markup": "Bain gach marcáil teanga",
  "Remove Language Markup": "Bain Marcáil Teanga",
  "Remove current lang value": "Bain luach teanga reatha",
  "Reveal lang markup": "Nocht marcáil teanga",
  "Select language {{number}}:": "Roghnaigh teanga {{number}}:",
  "Select the document's default language.": "Roghnaigh teanga réamhshocraithe na cáipéise.",
  "Set default document language": "Socraigh teanga réamhshocraithe cáipéise",
  "Set text language": "Socraigh teanga téacs",
  "langName.af": "Afracáinis",
  "langName.af-za": "Afracáinis",
  "langName.ak": "Acáinis",
  "langName.am": "Amáiris",
  "langName.ar": "Araibis",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "Araibis",
  "langName.az": "Asarbaiseáinis",
  "langName.be": "Bealarúisis",
  "langName.bg": "Bulgáiris",
  "langName.bg-bg": "Bulgáiris",
  "langName.bho": "Vóispiris",
  "langName.bm": "Bambairis",
  "langName.bn": "Beangáilis",
  "langName.bo": "Tibéidis",
  "langName.bs": "Boisnis",
  "langName.ca": "Catalóinis",
  "langName.cop": "Coptais",
  "langName.cr": "Craís",
  "langName.cs": "Seicis",
  "langName.cu": "Slavais na hEaglaise",
  "langName.cy": "Breatnais",
  "langName.da": "Danmhairgis",
  "langName.de": "Gearmáinis",
  "langName.de-at": "Gearmáinis na hOstaire",
  "langName.de-ch": "Ard-Ghearmáinis Eilvéiseach",
  "langName.de-de": "Gearmáinis",
  "langName.dv": "Divéihis",
  "langName.el": "Gréigis",
  "langName.en": "Béarla",
  "langName.en-au": "Béarla na hAstráile",
  "langName.en-ca": "Béarla Cheanada",
  "langName.en-gb": "Béarla na Breataine",
  "langName.en-ie": "Béarla (Éire)",
  "langName.en-in": "Béarla (Indiach)",
  "langName.en-tt": "Béarla (Oileán na Tríonóide)",
  "langName.en-us": "Béarla Mheiriceá",
  "langName.en-za": "Béarla (an Afraic Theas)",
  "langName.eo": "Esperanto",
  "langName.es": "Spáinnis",
  "langName.es-ar": "Spáinnis (an Airgintín)",
  "langName.es-cl": "Spáinnis (an tSile)",
  "langName.es-co": "Spáinnis (an Cholóim)",
  "langName.es-cr": "",
  "langName.es-es": "Spáinnis Eorpach",
  "langName.es-mx": "Spáinnis Mheicsiceach",
  "langName.es-pe": "Spáinnis (Peiriú)",
  "langName.et": "Eastóinis",
  "langName.eu": "Bascais",
  "langName.fa": "Peirsis",
  "langName.fa-af": "Dairis",
  "langName.fa-ir": "Peirsis",
  "langName.ff": "Fuláinis",
  "langName.fi": "Fionlainnis",
  "langName.fi-fi": "Fionlainnis",
  "langName.fil": "Filipínis",
  "langName.fr": "Fraincis",
  "langName.fr-be": "",
  "langName.fr-ca": "Fraincis Cheanada",
  "langName.fr-ch": "Fraincis na hEilvéise",
  "langName.ga": "Gaeilge",
  "langName.gl": "Gailísis",
  "langName.grc": "Sean-Ghréigis",
  "langName.ha": "Hásais",
  "langName.he": "Eabhrais",
  "langName.he-il": "Eabhrais",
  "langName.hi": "Hiondúis",
  "langName.hr": "Cróitis",
  "langName.hr-hr": "Cróitis",
  "langName.ht": "Críol Háítí",
  "langName.hu": "Ungáiris",
  "langName.hu-hu": "Ungáiris",
  "langName.hy": "Airméinis",
  "langName.id": "Indinéisis",
  "langName.ig": "Íogbóis",
  "langName.is": "Íoslainnis",
  "langName.it": "Iodáilis",
  "langName.it-it": "Iodáilis",
  "langName.iu": "Ionúitis",
  "langName.ja": "Seapáinis",
  "langName.ja-jp": "Seapáinis",
  "langName.ka": "Seoirsis",
  "langName.kab": "Caibílis",
  "langName.kk": "Casaicis",
  "langName.km": "Ciméiris",
  "langName.kn": "Cannadais",
  "langName.ko": "Cóiréis",
  "langName.ko-kr": "Cóiréis",
  "langName.la": "Laidin",
  "langName.lkt": "Lacótais",
  "langName.lo": "Laoisis",
  "langName.lt": "Liotuáinis",
  "langName.lv": "Laitvis",
  "langName.mi": "Maorais",
  "langName.mn": "Mongóilis",
  "langName.mr": "Maraitis",
  "langName.ms": "Malaeis",
  "langName.mt": "Máltais",
  "langName.my": "Burmais",
  "langName.nb": "Bocmál",
  "langName.nb-no": "Bocmál",
  "langName.ne": "Neipeailis",
  "langName.nl": "Ollainnis",
  "langName.nl-be": "Pléimeannais",
  "langName.nn": "Nua-Ioruais",
  "langName.nv": "Navachóis",
  "langName.ota": "",
  "langName.pa": "Puinseáibis",
  "langName.peo": "Sean-Pheirsis",
  "langName.pl": "Polainnis",
  "langName.ps": "Paistis",
  "langName.pt": "Portaingéilis",
  "langName.pt-br": "Portaingéilis Bhrasaíleach",
  "langName.pt-pt": "Portaingéilis Ibéarach",
  "langName.qu": "Ceatsuais",
  "langName.ro": "Rómáinis",
  "langName.ru": "Rúisis",
  "langName.rw": "Ciniaruaindis",
  "langName.sa": "Sanscrait",
  "langName.se": "Sáimis an Tuaiscirt",
  "langName.si": "Siolóinis",
  "langName.sk-sk": "Slóvaicis",
  "langName.sl": "Slóivéinis",
  "langName.sl-si": "Slóivéinis",
  "langName.sma": "Sáimis Theas",
  "langName.sme": "Samáis Tuaidh",
  "langName.smj": "Sáimis Lule",
  "langName.sn": "Seoinis",
  "langName.sr": "Seirbis",
  "langName.sr-latn": "",
  "langName.sv": "Sualainnis",
  "langName.sv-se": "Sualainnis",
  "langName.sw": "Svahaílis",
  "langName.sw-ke": "Svahaílis",
  "langName.sw-tz": "Svahaílis",
  "langName.syc": "",
  "langName.ta": "Tamailis",
  "langName.te": "Teileagúis",
  "langName.tg": "Taidsícis",
  "langName.th": "Téalainnis",
  "langName.th-th": "Téalainnis",
  "langName.tk": "Tuircméinis",
  "langName.tl": "Tagálaigis",
  "langName.tr": "Tuircis",
  "langName.tr-tr": "Tuircis",
  "langName.tt": "Tatairis",
  "langName.ug": "Uigiúiris",
  "langName.uk": "Úcráinis",
  "langName.ur": "Urdúis",
  "langName.uz": "Úisbéiceastáinis",
  "langName.vi": "Vítneaimis",
  "langName.wo": "Volaifis",
  "langName.xh": "Cóisis",
  "langName.yi": "Giúdais",
  "langName.yo": "Iarúibis",
  "langName.yua": "Maidhis Iúcatáin",
  "langName.zh": "Sínis",
  "langName.zh-cn": "Sínis Shimplithe",
  "langName.zh-hans": "Sínis Shimplithe",
  "langName.zh-hant": "Sínis Thraidisiúnta",
  "langName.zh-hk": "Sínis (Hong Cong)",
  "langName.zh-sg": "",
  "langName.zh-tw": "Sínis Thraidisiúnta",
  "langName.zu": "Súlúis",
  "langName.zu-za": "Súlúis"
});