tinymce.addI18n("he", {
  "Current language:": "שפה נוכחית:",
  "Set text language": "קבע שפת טקסט",
  "-Language Not Set-": "-שפה לא נקבעה-",
  "Choose languages": "בחר שפות",
  "Remove Language Markup": "הסר סימון שפה",
  "Remove current lang value": "הסר ערך שפה נוכחי",
  "Remove All lang markup": "הסר את כל סימוני השפה",
  "Configure languages": "הגדר שפות",
  "Set default document language": "קבע שפת ברירת מחדל למסמך",
  "Reveal lang markup": "חשף סימון שפה",
  "Indicate current language": "ציין שפה נוכחית",
  "Select the document's default language.": "בחר את שפת ברירת המחדל של המסמך.",
  "Choose from list": "בחר מרשימה",
  "Enter manually": "הזן ידנית",
  "None": "ללא",
  "Other - Enter manually": "אחר - הזן ידנית",
  "New Language:": "שפה חדשה:",
  "Enter new lang code (e.g., \"en-US\"):": "הזן קוד שפה חדש (למשל, \"en-US\"):",
  "Choose up to six languages": "בחר עד שש שפות",
  "Select language {{number}}:": "בחר שפה {{number}}:",
  "Manually enter language {{number}}:": "הזן ידנית שפה {{number}}:",
  "Really remove all language markup from the document?": "האם באמת להסיר את כל סימוני השפה מהמסמך?",
  "Enter a valid language code with no spaces. Or, press cancel.": "הזן קוד שפה תקין ללא רווחים. או לחץ ביטול.",
  "langName.af": "אפריקאנס",
  "langName.ak": "אקאן",
  "langName.ar": "ערבית",
  "langName.az": "אזרבייג'נית",
  "langName.bg": "בולגרית",
  "langName.bho": "בהוג'פורי",
  "langName.bm": "במברה",
  "langName.bn": "בנגלית",
  "langName.bo": "טיבטית",
  "langName.bs": "בוסנית",
  "langName.ca": "קטלנית; ולנסיאנית",
  "langName.cs": "צ'כית",
  "langName.cu": "בולגרית עתיקה",
  "langName.da": "דנית",
  "langName.de": "גרמנית",
  "langName.el": "יוונית",
  "langName.en": "אנגלית",
  "langName.en-au": "אנגלית (אוסטרליה)",
  "langName.en-gb": "אנגלית (בריטניה)",
  "langName.en-in": "אנגלית (הודו)",
  "langName.en-ie": "אנגלית (אירלנד)",
  "langName.en-tt": "אנגלית (טרינידד)",
  "langName.en-us": "אנגלית (ארצות הברית)",
  "langName.en-za": "אנגלית (דרום אפריקה)",
  "langName.es": "ספרדית",
  "langName.es-ar": "ספרדית (ארגנטינה)",
  "langName.es-cl": "ספרדית (צ'ילה)",
  "langName.es-co": "ספרדית (קולומביה)",
  "langName.es-mx": "ספרדית (מקסיקו)",
  "langName.es-pe": "ספרדית (פרו)",
  "langName.et": "אסטונית",
  "langName.eu": "בסקית",
  "langName.fa": "פרסית",
  "langName.fi": "פינית",
  "langName.fr": "צרפתית",
  "langName.fr-ca": "צרפתית (קנדה)",
  "langName.gl": "גלית (ספרד)",
  "langName.he": "עברית",
  "langName.hi": "הינדי",
  "langName.hr": "קרואטית",
  "langName.hu": "הונגרית",
  "langName.id": "אינדונזית",
  "langName.it": "איטלקית",
  "langName.ja": "יפנית",
  "langName.kk": "קזחית",
  "langName.kn": "קנאדה",
  "langName.ko": "קוריאנית",
  "langName.la": "לטינית",
  "langName.lkt": "לקוטה",
  "langName.mn": "מונגולית",
  "langName.mr": "מרטהי",
  "langName.nb": "נורווגית בוקמול",
  "langName.nl": "הולנדית",
  "langName.nl-be": "הולנדית (בלגיה)",
  "langName.nn": "נורווגית נינורסק",
  "langName.pl": "פולנית",
  "langName.ps": "פשטו",
  "langName.pt": "פורטוגזית, בינלאומית",
  "langName.pt-br": "פורטוגזית, ברזיל",
  "langName.qu": "קצ'ואה",
  "langName.ro": "רומנית",
  "langName.ru": "רוסית",
  "langName.sa": "סנסקריט",
  "langName.sk-sk": "סלובקית",
  "langName.sl": "סלובנית",
  "langName.sma": "סמי דרומית",
  "langName.sme": "סמי צפונית",
  "langName.smj": "סמי לולה",
  "langName.sr": "סרבית",
  "langName.sv": "שוודית",
  "langName.sw": "סווהילי",
  "langName.ta": "טמילית",
  "langName.te": "טלוגו",
  "langName.tg": "טג'יקית",
  "langName.th": "תאילנדית",
  "langName.tr": "טורקית",
  "langName.ug": "אויגורית",
  "langName.uk": "אוקראינית",
  "langName.ur": "אורדו",
  "langName.uz": "אוזבקית",
  "langName.vi": "וייטנאמית",
  "langName.wo": "וולוף",
  "langName.yi": "יידיש",
  "langName.yo": "יורובה",
  "langName.yua": "מאיה יוקטנית",
  "langName.zh": "סינית",
  "langName.zh-cn": "סינית (סין)",
  "langName.zh-hk": "סינית (הונג קונג)",
  "langName.zh-tw": "סינית (טייוואן)",
  "langName.zh-hans": "סינית, מפושטת",
  "langName.zh-hant": "סינית, מסורתית",
  "langName.zu": "זולו"
});