tinymce.addI18n('he_IL', {
  "-Language Not Set-": "-שפה לא נקבעה-",
  "Choose from list": "בחר מרשימה",
  "Choose languages": "בחר שפות",
  "Choose up to six languages": "בחר עד שש שפות",
  "Configure languages": "הגדר שפות",
  "Current language:": "שפה נוכחית:",
  "Enter a valid language code with no spaces. Or, press cancel.": "הזן קוד שפה תקין ללא רווחים. או לחץ ביטול.",
  "Enter manually": "הזן ידנית",
  "Enter new lang code (e.g., \"en-US\"):": "הזן קוד שפה חדש (למשל, \"en-US\"):",
  "Indicate current language": "ציין שפה נוכחית",
  "Manually enter language {{number}}:": "הזן ידנית שפה {{number}}:",
  "New Language:": "שפה חדשה:",
  "None": "ללא",
  "Other - Enter manually": "אחר - הזן ידנית",
  "Really remove all language markup from the document?": "האם באמת להסיר את כל סימוני השפה מהמסמך?",
  "Remove All lang markup": "הסר את כל סימוני השפה",
  "Remove Language Markup": "הסר סימון שפה",
  "Remove current lang value": "הסר ערך שפה נוכחי",
  "Reveal lang markup": "חשף סימון שפה",
  "Select language {{number}}:": "בחר שפה {{number}}:",
  "Select the document's default language.": "בחר את שפת ברירת המחדל של המסמך.",
  "Set default document language": "קבע שפת ברירת מחדל למסמך",
  "Set text language": "קבע שפת טקסט",
  "langName.af": "אפריקאנס",
  "langName.af-za": "אפריקאנס",
  "langName.ak": "אקאן",
  "langName.am": "אמהרית",
  "langName.ar": "ערבית",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "ערבית",
  "langName.az": "אזרית",
  "langName.be": "בלארוסית",
  "langName.bg": "בולגרית",
  "langName.bg-bg": "בולגרית",
  "langName.bho": "בוג׳פורי",
  "langName.bm": "במבארה",
  "langName.bn": "בנגלית",
  "langName.bo": "טיבטית",
  "langName.bs": "בוסנית",
  "langName.ca": "קטלאנית",
  "langName.cop": "קופטית",
  "langName.cr": "קרי",
  "langName.cs": "צ׳כית",
  "langName.cu": "סלאבית כנסייתית עתיקה",
  "langName.cy": "וולשית",
  "langName.da": "דנית",
  "langName.de": "גרמנית",
  "langName.de-at": "",
  "langName.de-ch": "",
  "langName.de-de": "גרמנית",
  "langName.dv": "דיבהי",
  "langName.el": "יוונית",
  "langName.en": "אנגלית",
  "langName.en-au": "אנגלית (אוסטרליה)",
  "langName.en-ca": "",
  "langName.en-gb": "אנגלית (בריטניה)",
  "langName.en-ie": "אנגלית (אירלנד)",
  "langName.en-in": "אנגלית (הודו)",
  "langName.en-tt": "אנגלית (טרינידד)",
  "langName.en-us": "אנגלית",
  "langName.en-za": "אנגלית (דרום אפריקה)",
  "langName.eo": "אספרנטו",
  "langName.es": "ספרדית",
  "langName.es-ar": "ספרדית (ארגנטינה)",
  "langName.es-cl": "ספרדית (צ'ילה)",
  "langName.es-co": "ספרדית (קולומביה)",
  "langName.es-cr": "",
  "langName.es-es": "ספרדית",
  "langName.es-mx": "ספרדית (מקסיקו)",
  "langName.es-pe": "ספרדית (פרו)",
  "langName.et": "אסטונית",
  "langName.eu": "בסקית",
  "langName.fa": "פרסית",
  "langName.fa-af": "דארי",
  "langName.fa-ir": "פרסית",
  "langName.ff": "פולה",
  "langName.fi": "פינית",
  "langName.fi-fi": "פינית",
  "langName.fil": "פיליפינית",
  "langName.fr": "צרפתית",
  "langName.fr-be": "",
  "langName.fr-ca": "צרפתית (קנדה)",
  "langName.fr-ch": "",
  "langName.ga": "אירית",
  "langName.gl": "גליציאנית",
  "langName.grc": "יוונית עתיקה",
  "langName.ha": "האוסה",
  "langName.he": "עברית",
  "langName.he-il": "עברית",
  "langName.hi": "הינדי",
  "langName.hr": "קרואטית",
  "langName.hr-hr": "קרואטית",
  "langName.ht": "קריאולית (האיטי)",
  "langName.hu": "הונגרית",
  "langName.hu-hu": "הונגרית",
  "langName.hy": "ארמנית",
  "langName.id": "אינדונזית",
  "langName.ig": "איגבו",
  "langName.is": "איסלנדית",
  "langName.it": "איטלקית",
  "langName.it-it": "איטלקית",
  "langName.iu": "אינוקטיטוט",
  "langName.ja": "יפנית",
  "langName.ja-jp": "יפנית",
  "langName.ka": "גאורגית",
  "langName.kab": "קבילה",
  "langName.kk": "קזחית",
  "langName.km": "חמרית",
  "langName.kn": "קנאדה",
  "langName.ko": "קוריאנית",
  "langName.ko-kr": "קוריאנית",
  "langName.la": "לטינית",
  "langName.lkt": "לקוטה",
  "langName.lo": "לאו",
  "langName.lt": "ליטאית",
  "langName.lv": "לטבית",
  "langName.mi": "מאורית",
  "langName.mn": "מונגולית",
  "langName.mr": "מראטהית",
  "langName.ms": "מלאית",
  "langName.mt": "מלטית",
  "langName.my": "בורמזית",
  "langName.nb": "נורווגית ספרותית",
  "langName.nb-no": "נורווגית ספרותית",
  "langName.ne": "נפאלית",
  "langName.nl": "הולנדית",
  "langName.nl-be": "הולנדית (פלמית)",
  "langName.nn": "נורווגית חדשה",
  "langName.nv": "נאוואחו",
  "langName.ota": "טורקית עות׳מנית",
  "langName.pa": "פנג׳אבי",
  "langName.peo": "פרסית עתיקה",
  "langName.pl": "פולנית",
  "langName.ps": "פאשטו",
  "langName.pt": "פורטוגזית",
  "langName.pt-br": "פורטוגזית",
  "langName.pt-pt": "פורטוגזית",
  "langName.qu": "קצ׳ואה",
  "langName.ro": "רומנית",
  "langName.ru": "רוסית",
  "langName.rw": "קנירואנדית",
  "langName.sa": "סנסקריט",
  "langName.se": "סמי צפונית",
  "langName.si": "סינהלה",
  "langName.sk-sk": "סלובקית",
  "langName.sl": "סלובנית",
  "langName.sl-si": "סלובנית",
  "langName.sma": "סאמי דרומית",
  "langName.sme": "סמי צפונית",
  "langName.smj": "לולה סאמי",
  "langName.sn": "שונה",
  "langName.sr": "סרבית",
  "langName.sr-latn": "",
  "langName.sv": "שוודית",
  "langName.sv-se": "שוודית",
  "langName.sw": "סווהילי",
  "langName.sw-ke": "סווהילי",
  "langName.sw-tz": "סווהילי",
  "langName.syc": "סירית קלאסית",
  "langName.ta": "טמילית",
  "langName.te": "טלוגו",
  "langName.tg": "טג׳יקית",
  "langName.th": "תאית",
  "langName.th-th": "תאית",
  "langName.tk": "טורקמנית",
  "langName.tl": "טאגאלוג",
  "langName.tr": "טורקית",
  "langName.tr-tr": "טורקית",
  "langName.tt": "טטרית",
  "langName.ug": "אויגורית",
  "langName.uk": "אוקראינית",
  "langName.ur": "אורדו",
  "langName.uz": "אוזבקית",
  "langName.vi": "וייטנאמית",
  "langName.wo": "וולוף",
  "langName.xh": "קוסה",
  "langName.yi": "יידיש",
  "langName.yo": "יורובה",
  "langName.yua": "מאיה יוקטנית",
  "langName.zh": "סינית",
  "langName.zh-cn": "סינית פשוטה",
  "langName.zh-hans": "סינית פשוטה",
  "langName.zh-hant": "סינית מסורתית",
  "langName.zh-hk": "סינית (הונג קונג)",
  "langName.zh-sg": "",
  "langName.zh-tw": "סינית מסורתית",
  "langName.zu": "זולו",
  "langName.zu-za": "זולו"
});