tinymce.addI18n("hi", {
  "Current language:": "वर्तमान भाषा:",
  "Set text language": "टेक्स्ट भाषा सेट करें",
  "-Language Not Set-": "-भाषा निर्धारित नहीं-",
  "Choose languages": "भाषाएँ चुनें",
  "Remove Language Markup": "भाषा मार्कअप हटाएं",
  "Remove current lang value": "वर्तमान भाषा मान हटाएं",
  "Remove All lang markup": "सभी भाषा मार्कअप हटाएं",
  "Configure languages": "भाषाएँ कॉन्फ़िगर करें",
  "Set default document language": "डिफ़ॉल्ट दस्तावेज़ भाषा सेट करें",
  "Reveal lang markup": "भाषा मार्कअप दिखाएं",
  "Indicate current language": "वर्तमान भाषा इंगित करें",
  "Select the document's default language.": "दस्तावेज़ की डिफ़ॉल्ट भाषा चुनें।",
  "Choose from list": "सूची से चुनें",
  "Enter manually": "मैन्युअल रूप से दर्ज करें",
  "None": "कोई नहीं",
  "Other - Enter manually": "अन्य - मैन्युअल रूप से दर्ज करें",
  "New Language:": "नई भाषा:",
  "Enter new lang code (e.g., \"en-US\"):": "नया भाषा कोड दर्ज करें (जैसे, \"en-US\"):",
  "Choose up to six languages": "छह तक भाषाएँ चुनें",
  "Select language {{number}}:": "भाषा {{number}} चुनें:",
  "Manually enter language {{number}}:": "भाषा {{number}} मैन्युअल रूप से दर्ज करें:",
  "Really remove all language markup from the document?": "वास्तव में दस्तावेज़ से सभी भाषा मार्कअप हटाना है?",
  "Enter a valid language code with no spaces. Or, press cancel.": "बिना स्पेस के एक वैध भाषा कोड दर्ज करें। या रद्द करें दबाएं।",
  "langName.af": "अफ्रीकांस",
  "langName.ak": "अकान",
  "langName.ar": "अरबी",
  "langName.az": "अज़रबैजानी",
  "langName.bg": "बल्गेरियाई",
  "langName.bho": "भोजपुरी",
  "langName.bm": "बम्बारा",
  "langName.bn": "बंगाली",
  "langName.bo": "तिब्बती",
  "langName.bs": "बोस्नियाई",
  "langName.ca": "कैटलन; वैलेंसियन",
  "langName.cs": "चेक",
  "langName.cu": "पुराना बल्गेरियाई",
  "langName.da": "डेनिश",
  "langName.de": "जर्मन",
  "langName.el": "ग्रीक",
  "langName.en": "अंग्रेजी",
  "langName.en-au": "अंग्रेजी (ऑस्ट्रेलिया)",
  "langName.en-gb": "अंग्रेजी (यूनाइटेड किंगडम)",
  "langName.en-in": "अंग्रेजी (भारत)",
  "langName.en-ie": "अंग्रेजी (आयरलैंड)",
  "langName.en-tt": "अंग्रेजी (त्रिनिदाद)",
  "langName.en-us": "अंग्रेजी (संयुक्त राज्य)",
  "langName.en-za": "अंग्रेजी (दक्षिण अफ्रीका)",
  "langName.es": "स्पेनिश",
  "langName.es-ar": "स्पेनिश (अर्जेंटीना)",
  "langName.es-cl": "स्पेनिश (चिली)",
  "langName.es-co": "स्पेनिश (कोलंबिया)",
  "langName.es-mx": "स्पेनिश (मैक्सिको)",
  "langName.es-pe": "स्पेनिश (पेरू)",
  "langName.et": "एस्टोनियाई",
  "langName.eu": "बास्क",
  "langName.fa": "फारसी",
  "langName.fi": "फिनिश",
  "langName.fr": "फ्रेंच",
  "langName.fr-ca": "फ्रेंच (कैनेडा)",
  "langName.gl": "गैलिशियन (स्पेन)",
  "langName.he": "हिब्रू",
  "langName.hi": "हिंदी",
  "langName.hr": "क्रोएशियाई",
  "langName.hu": "हंगेरियन",
  "langName.id": "इंडोनेशियाई",
  "langName.it": "इतालवी",
  "langName.ja": "जापानी",
  "langName.kk": "कज़ाख",
  "langName.kn": "कन्नड़",
  "langName.ko": "कोरियाई",
  "langName.la": "लैटिन",
  "langName.lkt": "लकोटा",
  "langName.mn": "मंगोलियाई",
  "langName.mr": "मराठी",
  "langName.nb": "नॉर्वेजियन बोकमाल",
  "langName.nl": "डच",
  "langName.nl-be": "डच (बेल्जियम)",
  "langName.nn": "नॉर्वेजियन नाइनॉर्स्क",
  "langName.pl": "पोलिश",
  "langName.ps": "पश्तो",
  "langName.pt": "पुर्तगाली, अंतर्राष्ट्रीय",
  "langName.pt-br": "पुर्तगाली, ब्राजील",
  "langName.qu": "क्वेचुआ",
  "langName.ro": "रोमानियाई",
  "langName.ru": "रूसी",
  "langName.sa": "संस्कृत",
  "langName.sk-sk": "स्लोवाक",
  "langName.sl": "स्लोवेनियाई",
  "langName.sma": "दक्षिणी सामी",
  "langName.sme": "उत्तरी सामी",
  "langName.smj": "लूले सामी",
  "langName.sr": "सर्बियाई",
  "langName.sv": "स्वीडिश",
  "langName.sw": "स्वाहिली",
  "langName.ta": "तमिल",
  "langName.te": "तेलुगु",
  "langName.tg": "ताजिक",
  "langName.th": "थाई",
  "langName.tr": "तुर्की",
  "langName.ug": "उइगुर",
  "langName.uk": "यूक्रेनियाई",
  "langName.ur": "उर्दू",
  "langName.uz": "उज़्बेक",
  "langName.vi": "वियतनामी",
  "langName.wo": "वोलोफ",
  "langName.yi": "यिडिश",
  "langName.yo": "योरुबा",
  "langName.yua": "युकाटेक माया",
  "langName.zh": "चीनी",
  "langName.zh-cn": "चीनी (चीन)",
  "langName.zh-hk": "चीनी (हांग कांग)",
  "langName.zh-tw": "चीनी (ताइवान)",
  "langName.zh-hans": "चीनी, सरलीकृत",
  "langName.zh-hant": "चीनी, पारंपरिक",
  "langName.zu": "जुलु"
});