tinymce.addI18n('hi', {
  "-Language Not Set-": "-भाषा निर्धारित नहीं-",
  "Choose from list": "सूची से चुनें",
  "Choose languages": "भाषाएँ चुनें",
  "Choose up to six languages": "छह तक भाषाएँ चुनें",
  "Configure languages": "भाषाएँ कॉन्फ़िगर करें",
  "Current language:": "वर्तमान भाषा:",
  "Enter a valid language code with no spaces. Or, press cancel.": "बिना स्पेस के एक वैध भाषा कोड दर्ज करें। या रद्द करें दबाएं।",
  "Enter manually": "मैन्युअल रूप से दर्ज करें",
  "Enter new lang code (e.g., \"en-US\"):": "नया भाषा कोड दर्ज करें (जैसे, \"en-US\"):",
  "Indicate current language": "वर्तमान भाषा इंगित करें",
  "Manually enter language {{number}}:": "भाषा {{number}} मैन्युअल रूप से दर्ज करें:",
  "New Language:": "नई भाषा:",
  "None": "कोई नहीं",
  "Other - Enter manually": "अन्य - मैन्युअल रूप से दर्ज करें",
  "Really remove all language markup from the document?": "वास्तव में दस्तावेज़ से सभी भाषा मार्कअप हटाना है?",
  "Remove All lang markup": "सभी भाषा मार्कअप हटाएं",
  "Remove Language Markup": "भाषा मार्कअप हटाएं",
  "Remove current lang value": "वर्तमान भाषा मान हटाएं",
  "Reveal lang markup": "भाषा मार्कअप दिखाएं",
  "Select language {{number}}:": "भाषा {{number}} चुनें:",
  "Select the document's default language.": "दस्तावेज़ की डिफ़ॉल्ट भाषा चुनें।",
  "Set default document language": "डिफ़ॉल्ट दस्तावेज़ भाषा सेट करें",
  "Set text language": "टेक्स्ट भाषा सेट करें",
  "langName.af": "अफ़्रीकी",
  "langName.af-za": "अफ़्रीकी",
  "langName.ak": "अकन",
  "langName.am": "अम्हेरी",
  "langName.ar": "अरबी",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "अरबी",
  "langName.az": "अज़रबैजानी",
  "langName.be": "बेलारूसी",
  "langName.bg": "बुल्गारियाई",
  "langName.bg-bg": "बुल्गारियाई",
  "langName.bho": "भोजपुरी",
  "langName.bm": "बाम्बारा",
  "langName.bn": "बंगाली",
  "langName.bo": "तिब्बती",
  "langName.bs": "बोस्नियाई",
  "langName.ca": "कातालान",
  "langName.cop": "कॉप्टिक",
  "langName.cr": "क्री",
  "langName.cs": "चेक",
  "langName.cu": "चर्च साल्विक",
  "langName.cy": "वेल्श",
  "langName.da": "डेनिश",
  "langName.de": "जर्मन",
  "langName.de-at": "ऑस्ट्रियाई जर्मन",
  "langName.de-ch": "स्विस उच्च जर्मन",
  "langName.de-de": "जर्मन",
  "langName.dv": "दिवेही",
  "langName.el": "यूनानी",
  "langName.en": "अंग्रेज़ी",
  "langName.en-au": "ऑस्ट्रेलियाई अंग्रेज़ी",
  "langName.en-ca": "कनाडाई अंग्रेज़ी",
  "langName.en-gb": "ब्रिटिश अंग्रेज़ी",
  "langName.en-ie": "अंग्रेजी (आयरलैंड)",
  "langName.en-in": "अंग्रेजी (भारत)",
  "langName.en-tt": "अंग्रेजी (त्रिनिदाद)",
  "langName.en-us": "अमेरिकी अंग्रेज़ी",
  "langName.en-za": "अंग्रेजी (दक्षिण अफ्रीका)",
  "langName.eo": "एस्पेरेंतो",
  "langName.es": "स्पेनिश",
  "langName.es-ar": "स्पेनिश (अर्जेंटीना)",
  "langName.es-cl": "स्पेनिश (चिली)",
  "langName.es-co": "स्पेनिश (कोलंबिया)",
  "langName.es-cr": "",
  "langName.es-es": "यूरोपीय स्पेनिश",
  "langName.es-mx": "मैक्सिकन स्पेनिश",
  "langName.es-pe": "स्पेनिश (पेरू)",
  "langName.et": "एस्टोनियाई",
  "langName.eu": "बास्क",
  "langName.fa": "फ़ारसी",
  "langName.fa-af": "दारी",
  "langName.fa-ir": "फ़ारसी",
  "langName.ff": "फुलाह",
  "langName.fi": "फ़िनिश",
  "langName.fi-fi": "फ़िनिश",
  "langName.fil": "फ़िलिपीनो",
  "langName.fr": "फ़्रेंच",
  "langName.fr-be": "",
  "langName.fr-ca": "कनाडाई फ़्रेंच",
  "langName.fr-ch": "स्विस फ़्रेंच",
  "langName.ga": "आयरिश",
  "langName.gl": "गैलिशियन",
  "langName.grc": "प्राचीन यूनानी",
  "langName.ha": "हौसा",
  "langName.he": "हिब्रू",
  "langName.he-il": "हिब्रू",
  "langName.hi": "हिन्दी",
  "langName.hr": "क्रोएशियाई",
  "langName.hr-hr": "क्रोएशियाई",
  "langName.ht": "हैतियाई",
  "langName.hu": "हंगेरियाई",
  "langName.hu-hu": "हंगेरियाई",
  "langName.hy": "आर्मेनियाई",
  "langName.id": "इंडोनेशियाई",
  "langName.ig": "ईग्बो",
  "langName.is": "आइसलैंडिक",
  "langName.it": "इतालवी",
  "langName.it-it": "इतालवी",
  "langName.iu": "इनुक्टिटुट",
  "langName.ja": "जापानी",
  "langName.ja-jp": "जापानी",
  "langName.ka": "जॉर्जियाई",
  "langName.kab": "कबाइल",
  "langName.kk": "कज़ाख़",
  "langName.km": "खमेर",
  "langName.kn": "कन्नड़",
  "langName.ko": "कोरियाई",
  "langName.ko-kr": "कोरियाई",
  "langName.la": "लैटिन",
  "langName.lkt": "लैकोटा",
  "langName.lo": "लाओ",
  "langName.lt": "लिथुआनियाई",
  "langName.lv": "लातवियाई",
  "langName.mi": "माओरी",
  "langName.mn": "मंगोलियाई",
  "langName.mr": "मराठी",
  "langName.ms": "मलय",
  "langName.mt": "माल्टीज़",
  "langName.my": "बर्मीज़",
  "langName.nb": "नॉर्वेजियाई बोकमाल",
  "langName.nb-no": "नॉर्वेजियाई बोकमाल",
  "langName.ne": "नेपाली",
  "langName.nl": "डच",
  "langName.nl-be": "फ़्लेमिश",
  "langName.nn": "नॉर्वेजियाई नॉयनॉर्स्क",
  "langName.nv": "नवाहो",
  "langName.ota": "ओटोमान तुर्किश",
  "langName.pa": "पंजाबी",
  "langName.peo": "पुरानी फारसी",
  "langName.pl": "पोलिश",
  "langName.ps": "पश्तो",
  "langName.pt": "पुर्तगाली",
  "langName.pt-br": "ब्राज़ीली पुर्तगाली",
  "langName.pt-pt": "यूरोपीय पुर्तगाली",
  "langName.qu": "क्वेचुआ",
  "langName.ro": "रोमानियाई",
  "langName.ru": "रूसी",
  "langName.rw": "किन्यारवांडा",
  "langName.sa": "संस्कृत",
  "langName.se": "नॉर्दन सामी",
  "langName.si": "सिंहली",
  "langName.sk-sk": "स्लोवाक",
  "langName.sl": "स्लोवेनियाई",
  "langName.sl-si": "स्लोवेनियाई",
  "langName.sma": "दक्षिणी सामी",
  "langName.sme": "उत्तरी सामी",
  "langName.smj": "ल्युल सामी",
  "langName.sn": "शोणा",
  "langName.sr": "सर्बियाई",
  "langName.sr-latn": "",
  "langName.sv": "स्वीडिश",
  "langName.sv-se": "स्वीडिश",
  "langName.sw": "स्वाहिली",
  "langName.sw-ke": "स्वाहिली",
  "langName.sw-tz": "स्वाहिली",
  "langName.syc": "क्लासिकल सिरिएक",
  "langName.ta": "तमिल",
  "langName.te": "तेलुगू",
  "langName.tg": "ताजिक",
  "langName.th": "थाई",
  "langName.th-th": "थाई",
  "langName.tk": "तुर्कमेन",
  "langName.tl": "टैगलॉग",
  "langName.tr": "तुर्की",
  "langName.tr-tr": "तुर्की",
  "langName.tt": "तातार",
  "langName.ug": "उइगर",
  "langName.uk": "यूक्रेनियाई",
  "langName.ur": "उर्दू",
  "langName.uz": "उज़्बेक",
  "langName.vi": "वियतनामी",
  "langName.wo": "वोलोफ़",
  "langName.xh": "ख़ोसा",
  "langName.yi": "यहूदी",
  "langName.yo": "योरूबा",
  "langName.yua": "युकाटेक माया",
  "langName.zh": "चीनी",
  "langName.zh-cn": "सरलीकृत चीनी",
  "langName.zh-hans": "सरलीकृत चीनी",
  "langName.zh-hant": "पारंपरिक चीनी",
  "langName.zh-hk": "चीनी (हांग कांग)",
  "langName.zh-sg": "",
  "langName.zh-tw": "पारंपरिक चीनी",
  "langName.zu": "ज़ुलू",
  "langName.zu-za": "ज़ुलू"
});