tinymce.addI18n('hi', {
  "-Language Not Set-": "-भाषा निर्धारित नहीं-",
  "Choose from list": "सूची से चुनें",
  "Choose languages": "भाषाएँ चुनें",
  "Choose up to six languages": "छह तक भाषाएँ चुनें",
  "Configure languages": "भाषाएँ कॉन्फ़िगर करें",
  "Current language:": "वर्तमान भाषा:",
  "Enter a valid language code with no spaces. Or, press cancel.": "बिना स्पेस के एक वैध भाषा कोड दर्ज करें। या रद्द करें दबाएं।",
  "Enter manually": "मैन्युअल रूप से दर्ज करें",
  "Enter new lang code (e.g., \"en-US\"):": "नया भाषा कोड दर्ज करें (जैसे, \"hi-IN\"):",
  "Indicate current language": "वर्तमान भाषा इंगित करें",
  "Manually enter language {{number}}:": "भाषा {{number}} मैन्युअल रूप से दर्ज करें:",
  "New Language:": "नई भाषा:",
  "None": "कोई नहीं",
  "Other - Enter manually": "अन्य - मैन्युअल रूप से दर्ज करें",
  "Really remove all language markup from the document?": "वास्तव में दस्तावेज़ से सभी भाषा मार्कअप हटाना है?",
  "Remove All lang markup": "सभी भाषा मार्कअप हटाएं",
  "Remove Language Markup": "भाषा मार्कअप हटाएं",
  "Remove current lang value": "वर्तमान भाषा मान हटाएं",
  "Reveal lang markup": "भाषा मार्कअप दिखाएं",
  "Select language {{number}}:": "भाषा {{number}} चुनें:",
  "Select the document's default language.": "दस्तावेज़ की डिफ़ॉल्ट भाषा चुनें।",
  "Set default document language": "डिफ़ॉल्ट दस्तावेज़ भाषा सेट करें",
  "Set text language": "टेक्स्ट भाषा सेट करें",
  "langName.af": "अफ़्रीकी",
  "langName.af-za": "अफ़्रीकी (दक्षिण अफ्रीका)",
  "langName.ak": "अकन",
  "langName.am": "अम्हेरी",
  "langName.ar": "अरबी",
  "langName.ar-eg": "अरबी (मिस्र)",
  "langName.ar-ma": "अरबी (मोरक्को)",
  "langName.ar-sa": "अरबी (सऊदी अरब)",
  "langName.az": "अज़रबैजानी",
  "langName.be": "बेलारूसी",
  "langName.bg": "बुल्गारियाई",
  "langName.bg-bg": "बुल्गारियाई (बुल्गारिया)",
  "langName.bho": "भोजपुरी",
  "langName.bm": "बाम्बारा",
  "langName.bn": "बंगाली",
  "langName.bo": "तिब्बती",
  "langName.bs": "बोस्नियाई",
  "langName.ca": "कातालान",
  "langName.cop": "कॉप्टिक",
  "langName.cr": "क्री",
  "langName.cs": "चेक",
  "langName.cu": "चर्च स्लाविक",
  "langName.cy": "वेल्श",
  "langName.da": "डेनिश",
  "langName.de": "जर्मन",
  "langName.de-at": "जर्मन (ऑस्ट्रिया)",
  "langName.de-ch": "जर्मन (स्विट्जरलैंड)",
  "langName.de-de": "जर्मन (जर्मनी)",
  "langName.dv": "दिवेही",
  "langName.el": "यूनानी",
  "langName.en": "अंग्रेज़ी",
  "langName.en-au": "अंग्रेज़ी (ऑस्ट्रेलिया)",
  "langName.en-ca": "अंग्रेज़ी (कनाडा)",
  "langName.en-gb": "अंग्रेज़ी (ब्रिटेन)",
  "langName.en-ie": "अंग्रेज़ी (आयरलैंड)",
  "langName.en-in": "अंग्रेज़ी (भारत)",
  "langName.en-tt": "अंग्रेज़ी (त्रिनिदाद)",
  "langName.en-us": "अंग्रेज़ी (संयुक्त राज्य)",
  "langName.en-za": "अंग्रेज़ी (दक्षिण अफ्रीका)",
  "langName.eo": "एस्पेरेंतो",
  "langName.es": "स्पेनिश",
  "langName.es-ar": "स्पेनिश (अर्जेंटीना)",
  "langName.es-cl": "स्पेनिश (चिली)",
  "langName.es-co": "स्पेनिश (कोलंबिया)",
  "langName.es-cr": "स्पेनिश (कोस्टा रिका)",
  "langName.es-es": "स्पेनिश (स्पेन)",
  "langName.es-mx": "स्पेनिश (मेक्सिको)",
  "langName.es-pe": "स्पेनिश (पेरू)",
  "langName.et": "एस्टोनियाई",
  "langName.eu": "बास्क",
  "langName.fa": "फ़ारसी",
  "langName.fa-af": "दारी",
  "langName.fa-ir": "फ़ारसी (ईरान)",
  "langName.ff": "फुलाह",
  "langName.fi": "फ़िनिश",
  "langName.fi-fi": "फ़िनिश (फिनलैंड)",
  "langName.fil": "फ़िलिपीनो",
  "langName.fr": "फ़्रेंच",
  "langName.fr-be": "फ़्रेंच (बेल्जियम)",
  "langName.fr-ca": "फ़्रेंच (कनाडा)",
  "langName.fr-ch": "फ़्रेंच (स्विट्जरलैंड)",
  "langName.ga": "आयरिश",
  "langName.gl": "गैलिशियन",
  "langName.grc": "यूनानी (प्राचीन)",
  "langName.ha": "हौसा",
  "langName.he": "हिब्रू",
  "langName.he-il": "हिब्रू (इस्राएल)",
  "langName.hi": "हिन्दी",
  "langName.hr": "क्रोएशियाई",
  "langName.hr-hr": "क्रोएशियाई (क्रोएशिया)",
  "langName.ht": "हैतियाई क्रिओल",
  "langName.hu": "हंगेरियाई",
  "langName.hu-hu": "हंगेरियाई (हंगरी)",
  "langName.hy": "आर्मेनियाई",
  "langName.id": "इंडोनेशियाई",
  "langName.ig": "ईग्बो",
  "langName.is": "आइसलैंडिक",
  "langName.it": "इतालवी",
  "langName.it-it": "इतालवी (इटली)",
  "langName.iu": "इनुक्टिटुट",
  "langName.ja": "जापानी",
  "langName.ja-jp": "जापानी (जापान)",
  "langName.ka": "जॉर्जियाई",
  "langName.kab": "कबाइल",
  "langName.kk": "कज़ाख़",
  "langName.km": "खमेर",
  "langName.kn": "कन्नड़",
  "langName.ko": "कोरियाई",
  "langName.ko-kr": "कोरियाई (दक्षिण कोरिया)",
  "langName.la": "लैटिन",
  "langName.lkt": "लैकोटा",
  "langName.lo": "लाओ",
  "langName.lt": "लिथुआनियाई",
  "langName.lv": "लातवियाई",
  "langName.mi": "माओरी",
  "langName.mn": "मंगोलियाई",
  "langName.mr": "मराठी",
  "langName.ms": "मलय",
  "langName.mt": "माल्टीज़",
  "langName.my": "बर्मीज़",
  "langName.nb": "नॉर्वेजियाई (बोकमाल)",
  "langName.nb-no": "नॉर्वेजियाई (बोकमाल, नॉर्वे)",
  "langName.ne": "नेपाली",
  "langName.nl": "डच",
  "langName.nl-be": "डच (बेल्जियम)",
  "langName.nn": "नॉर्वेजियाई (न्यूनॉर्स्क)",
  "langName.nv": "नवाहो",
  "langName.ota": "तुर्की (ओटोमान)",
  "langName.pa": "पंजाबी",
  "langName.peo": "फ़ारसी (पुरानी)",
  "langName.pl": "पोलिश",
  "langName.ps": "पश्तो",
  "langName.pt": "पुर्तगाली",
  "langName.pt-br": "पुर्तगाली (ब्राज़ील)",
  "langName.pt-pt": "पुर्तगाली (पुर्तगाल)",
  "langName.qu": "क्वेचुआ",
  "langName.ro": "रोमानियाई",
  "langName.ru": "रूसी",
  "langName.rw": "किन्यारवांडा",
  "langName.sa": "संस्कृत",
  "langName.se": "सामी (उत्तरी)",
  "langName.si": "सिंहली",
  "langName.sk": "स्लोवाक",
  "langName.sk-sk": "स्लोवाक (स्लोवाकिया)",
  "langName.sl": "स्लोवेनियाई",
  "langName.sl-si": "स्लोवेनियाई (स्लोवेनिया)",
  "langName.sma": "सामी (दक्षिणी)",
  "langName.sme": "सामी (उत्तरी)",
  "langName.smj": "सामी (ल्युल)",
  "langName.sn": "शोणा",
  "langName.sr": "सर्बियाई",
  "langName.sr-latn": "सर्बियाई (लैटिन)",
  "langName.sv": "स्वीडिश",
  "langName.sv-se": "स्वीडिश (स्वीडन)",
  "langName.sw": "स्वाहिली",
  "langName.sw-ke": "स्वाहिली (केन्या)",
  "langName.sw-tz": "स्वाहिली (तंजानिया)",
  "langName.syc": "सिरिएक (शास्त्रीय)",
  "langName.ta": "तमिल",
  "langName.te": "तेलुगू",
  "langName.tg": "ताजिक",
  "langName.th": "थाई",
  "langName.th-th": "थाई (थाईलैंड)",
  "langName.tk": "तुर्कमेन",
  "langName.tl": "टैगलॉग",
  "langName.tr": "तुर्की",
  "langName.tr-tr": "तुर्की (तुर्की)",
  "langName.tt": "तातार",
  "langName.ug": "उइगर",
  "langName.uk": "यूक्रेनियाई",
  "langName.ur": "उर्दू",
  "langName.uz": "उज़्बेक",
  "langName.vi": "वियतनामी",
  "langName.wo": "वोलोफ़",
  "langName.xh": "ख़ोसा",
  "langName.yi": "यिडिश",
  "langName.yo": "योरूबा",
  "langName.yua": "माया (युकाटेक)",
  "langName.zh": "चीनी",
  "langName.zh-cn": "चीनी (सरलीकृत)",
  "langName.zh-hans": "चीनी (सरलीकृत)",
  "langName.zh-hant": "चीनी (पारंपरिक)",
  "langName.zh-hk": "चीनी (हांग कांग)",
  "langName.zh-sg": "चीनी (सिंगापुर)",
  "langName.zh-tw": "चीनी (पारंपरिक, ताइवान)",
  "langName.zu": "ज़ुलू",
  "langName.zu-za": "ज़ुलू (दक्षिण अफ्रीका)"
});