tinymce.addI18n('hr_HR', {
  "-Language Not Set-": "-Jezik nije postavljen-",
  "Choose from list": "Odaberite s popisa",
  "Choose languages": "Odaberite jezike",
  "Choose up to six languages": "Odaberite do šest jezika",
  "Configure languages": "Konfiguriraj jezike",
  "Current language:": "Trenutni jezik:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Unesite valjani kod jezika bez razmaka. Ili pritisnite odustani.",
  "Enter manually": "Unesite ručno",
  "Enter new lang code (e.g., \"en-US\"):": "Unesite novi kod jezika (npr. \"en-US\"):",
  "Indicate current language": "Označi trenutni jezik",
  "Manually enter language {{number}}:": "Ručno unesite jezik {{number}}:",
  "New Language:": "Novi jezik:",
  "None": "Nijedan",
  "Other - Enter manually": "Ostalo - Unesite ručno",
  "Really remove all language markup from the document?": "Stvarno ukloniti sve označavanje jezika iz dokumenta?",
  "Remove All lang markup": "Ukloni sve oznake jezika",
  "Remove Language Markup": "Ukloni označavanje jezika",
  "Remove current lang value": "Ukloni trenutnu vrijednost jezika",
  "Reveal lang markup": "Prikaži označavanje jezika",
  "Select language {{number}}:": "Odaberite jezik {{number}}:",
  "Select the document's default language.": "Odaberite zadani jezik dokumenta.",
  "Set default document language": "Postavi zadani jezik dokumenta",
  "Set text language": "Postavi jezik teksta",
  "langName.af": "afrikaans",
  "langName.af-za": "afrikaans",
  "langName.ak": "akanski",
  "langName.am": "amharski",
  "langName.ar": "arapski",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "arapski",
  "langName.az": "azerbajdžanski",
  "langName.be": "bjeloruski",
  "langName.bg": "bugarski",
  "langName.bg-bg": "bugarski",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bangla",
  "langName.bo": "tibetski",
  "langName.bs": "bosanski",
  "langName.ca": "katalonski",
  "langName.cop": "koptski",
  "langName.cr": "cree",
  "langName.cs": "češki",
  "langName.cu": "crkvenoslavenski",
  "langName.cy": "velški",
  "langName.da": "danski",
  "langName.de": "njemački",
  "langName.de-at": "austrijski njemački",
  "langName.de-ch": "gornjonjemački (švicarski)",
  "langName.de-de": "njemački",
  "langName.dv": "divehi",
  "langName.el": "grčki",
  "langName.en": "engleski",
  "langName.en-au": "australski engleski",
  "langName.en-ca": "kanadski engleski",
  "langName.en-gb": "britanski engleski",
  "langName.en-ie": "engleski (Irska)",
  "langName.en-in": "engleski (Indija)",
  "langName.en-tt": "engleski (Trinidad)",
  "langName.en-us": "američki engleski",
  "langName.en-za": "engleski (Južna Afrika)",
  "langName.eo": "esperanto",
  "langName.es": "španjolski",
  "langName.es-ar": "španjolski (Argentina)",
  "langName.es-cl": "španjolski (Čile)",
  "langName.es-co": "španjolski (Kolumbija)",
  "langName.es-cr": "",
  "langName.es-es": "europski španjolski",
  "langName.es-mx": "meksički španjolski",
  "langName.es-pe": "španjolski (Peru)",
  "langName.et": "estonski",
  "langName.eu": "baskijski",
  "langName.fa": "perzijski",
  "langName.fa-af": "dari",
  "langName.fa-ir": "perzijski",
  "langName.ff": "fula",
  "langName.fi": "finski",
  "langName.fi-fi": "finski",
  "langName.fil": "filipinski",
  "langName.fr": "francuski",
  "langName.fr-be": "",
  "langName.fr-ca": "kanadski francuski",
  "langName.fr-ch": "švicarski francuski",
  "langName.ga": "irski",
  "langName.gl": "galicijski",
  "langName.grc": "starogrčki",
  "langName.ha": "hausa",
  "langName.he": "hebrejski",
  "langName.he-il": "hebrejski",
  "langName.hi": "hindski",
  "langName.hr": "hrvatski",
  "langName.hr-hr": "hrvatski",
  "langName.ht": "haićanski kreolski",
  "langName.hu": "mađarski",
  "langName.hu-hu": "mađarski",
  "langName.hy": "armenski",
  "langName.id": "indonezijski",
  "langName.ig": "igbo",
  "langName.is": "islandski",
  "langName.it": "talijanski",
  "langName.it-it": "talijanski",
  "langName.iu": "inuktitut",
  "langName.ja": "japanski",
  "langName.ja-jp": "japanski",
  "langName.ka": "gruzijski",
  "langName.kab": "kabilski",
  "langName.kk": "kazaški",
  "langName.km": "kmerski",
  "langName.kn": "karnatački",
  "langName.ko": "korejski",
  "langName.ko-kr": "korejski",
  "langName.la": "latinski",
  "langName.lkt": "lakota",
  "langName.lo": "laoski",
  "langName.lt": "litavski",
  "langName.lv": "latvijski",
  "langName.mi": "maorski",
  "langName.mn": "mongolski",
  "langName.mr": "marathski",
  "langName.ms": "malajski",
  "langName.mt": "malteški",
  "langName.my": "burmanski",
  "langName.nb": "norveški bokmål",
  "langName.nb-no": "norveški bokmål",
  "langName.ne": "nepalski",
  "langName.nl": "nizozemski",
  "langName.nl-be": "flamanski",
  "langName.nn": "norveški nynorsk",
  "langName.nv": "navajo",
  "langName.ota": "turski - otomanski",
  "langName.pa": "pandžapski",
  "langName.peo": "staroperzijski",
  "langName.pl": "poljski",
  "langName.ps": "paštunski",
  "langName.pt": "portugalski",
  "langName.pt-br": "brazilski portugalski",
  "langName.pt-pt": "europski portugalski",
  "langName.qu": "kečuanski",
  "langName.ro": "rumunjski",
  "langName.ru": "ruski",
  "langName.rw": "kinyarwanda",
  "langName.sa": "sanskrtski",
  "langName.se": "sjeverni sami",
  "langName.si": "sinhaleški",
  "langName.sk-sk": "slovački",
  "langName.sl": "slovenski",
  "langName.sl-si": "slovenski",
  "langName.sma": "južni sami",
  "langName.sme": "sjeverni sami",
  "langName.smj": "lule sami",
  "langName.sn": "shona",
  "langName.sr": "srpski",
  "langName.sr-latn": "",
  "langName.sv": "švedski",
  "langName.sv-se": "švedski",
  "langName.sw": "svahili",
  "langName.sw-ke": "svahili",
  "langName.sw-tz": "svahili",
  "langName.syc": "klasični sirski",
  "langName.ta": "tamilski",
  "langName.te": "teluški",
  "langName.tg": "tadžički",
  "langName.th": "tajlandski",
  "langName.th-th": "tajlandski",
  "langName.tk": "turkmenski",
  "langName.tl": "tagalog",
  "langName.tr": "turski",
  "langName.tr-tr": "turski",
  "langName.tt": "tatarski",
  "langName.ug": "ujgurski",
  "langName.uk": "ukrajinski",
  "langName.ur": "urdski",
  "langName.uz": "uzbečki",
  "langName.vi": "vijetnamski",
  "langName.wo": "volof",
  "langName.xh": "xhosa",
  "langName.yi": "jidiš",
  "langName.yo": "jorupski",
  "langName.yua": "jukateški maja",
  "langName.zh": "kineski",
  "langName.zh-cn": "kineski (pojednostavljeni)",
  "langName.zh-hans": "kineski (pojednostavljeni)",
  "langName.zh-hant": "kineski (tradicionalni)",
  "langName.zh-hk": "kineski (Hong Kong)",
  "langName.zh-sg": "",
  "langName.zh-tw": "kineski (tradicionalni)",
  "langName.zu": "zulu",
  "langName.zu-za": "zulu"
});