tinymce.addI18n("hr_HR", {
  "Current language:": "Trenutni jezik:",
  "Set text language": "Postavi jezik teksta",
  "-Language Not Set-": "-Jezik nije postavljen-",
  "Choose languages": "Odaberite jezike",
  "Remove Language Markup": "Ukloni označavanje jezika",
  "Remove current lang value": "Ukloni trenutnu vrijednost jezika",
  "Remove All lang markup": "Ukloni sve oznake jezika",
  "Configure languages": "Konfiguriraj jezike",
  "Set default document language": "Postavi zadani jezik dokumenta",
  "Reveal lang markup": "Prikaži označavanje jezika",
  "Indicate current language": "Označi trenutni jezik",
  "Select the document's default language.": "Odaberite zadani jezik dokumenta.",
  "Choose from list": "Odaberite s popisa",
  "Enter manually": "Unesite ručno",
  "None": "Nijedan",
  "Other - Enter manually": "Ostalo - Unesite ručno",
  "New Language:": "Novi jezik:",
  "Enter new lang code (e.g., \"en-US\"):": "Unesite novi kod jezika (npr. \"en-US\"):",
  "Choose up to six languages": "Odaberite do šest jezika",
  "Select language {{number}}:": "Odaberite jezik {{number}}:",
  "Manually enter language {{number}}:": "Ručno unesite jezik {{number}}:",
  "Really remove all language markup from the document?": "Stvarno ukloniti sve označavanje jezika iz dokumenta?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Unesite valjani kod jezika bez razmaka. Ili pritisnite odustani.",
  "langName.af": "afrikaans",
  "langName.ak": "akan",
  "langName.ar": "arapski",
  "langName.az": "azerbajdžanski",
  "langName.bg": "bugarski",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengalski",
  "langName.bo": "tibetanski",
  "langName.bs": "bosanski",
  "langName.ca": "katalonski; valencijski",
  "langName.cs": "češki",
  "langName.cu": "staroslavenski",
  "langName.da": "danski",
  "langName.de": "njemački",
  "langName.el": "grčki",
  "langName.en": "engleski",
  "langName.en-au": "engleski (Australija)",
  "langName.en-gb": "engleski (Ujedinjeno Kraljevstvo)",
  "langName.en-in": "engleski (Indija)",
  "langName.en-ie": "engleski (Irska)",
  "langName.en-tt": "engleski (Trinidad)",
  "langName.en-us": "engleski (Sjedinjene Države)",
  "langName.en-za": "engleski (Južna Afrika)",
  "langName.es": "španjolski",
  "langName.es-ar": "španjolski (Argentina)",
  "langName.es-cl": "španjolski (Čile)",
  "langName.es-co": "španjolski (Kolumbija)",
  "langName.es-mx": "španjolski (Meksiko)",
  "langName.es-pe": "španjolski (Peru)",
  "langName.et": "estonski",
  "langName.eu": "baskijski",
  "langName.fa": "perzijski",
  "langName.fi": "finski",
  "langName.fr": "francuski",
  "langName.fr-ca": "francuski (Kanada)",
  "langName.gl": "galicijski (Španjolska)",
  "langName.he": "hebrejski",
  "langName.hi": "hindski",
  "langName.hr": "hrvatski",
  "langName.hu": "mađarski",
  "langName.id": "indonezijski",
  "langName.it": "talijanski",
  "langName.ja": "japanski",
  "langName.kk": "kazaški",
  "langName.kn": "kannada",
  "langName.ko": "korejski",
  "langName.la": "latinski",
  "langName.lkt": "lakota",
  "langName.mn": "mongolski",
  "langName.mr": "marathi",
  "langName.nb": "norveški bokmål",
  "langName.nl": "nizozemski",
  "langName.nl-be": "nizozemski (Belgija)",
  "langName.nn": "norveški nynorsk",
  "langName.pl": "poljski",
  "langName.ps": "paštunski",
  "langName.pt": "portugalski, međunarodni",
  "langName.pt-br": "portugalski, Brazil",
  "langName.qu": "kečua",
  "langName.ro": "rumunjski",
  "langName.ru": "ruski",
  "langName.sa": "sanskrt",
  "langName.sk-sk": "slovački",
  "langName.sl": "slovenski",
  "langName.sma": "južni sami",
  "langName.sme": "sjeverni sami",
  "langName.smj": "lule sami",
  "langName.sr": "srpski",
  "langName.sv": "švedski",
  "langName.sw": "svahili",
  "langName.ta": "tamilski",
  "langName.te": "telugu",
  "langName.tg": "tadžički",
  "langName.th": "tajlandski",
  "langName.tr": "turski",
  "langName.ug": "ujgurski",
  "langName.uk": "ukrajinski",
  "langName.ur": "urdu",
  "langName.uz": "uzbečki",
  "langName.vi": "vijetnamski",
  "langName.wo": "volof",
  "langName.yi": "jidiš",
  "langName.yo": "joruba",
  "langName.yua": "jukateški maja",
  "langName.zh": "kineski",
  "langName.zh-cn": "kineski (Kina)",
  "langName.zh-hk": "kineski (Hong Kong)",
  "langName.zh-tw": "kineski (Tajvan)",
  "langName.zh-hans": "kineski, pojednostavljen",
  "langName.zh-hant": "kineski, tradicionalan",
  "langName.zu": "zulu"
});