tinymce.addI18n('ht', {
  "-Language Not Set-": "-Lang la pa chwazi-",
  "Choose from list": "Chwazi nan lis la",
  "Choose languages": "Chwazi lang yo",
  "Choose up to six languages": "Chwazi jiska sis lang",
  "Configure languages": "Konfigire lang yo",
  "Current language:": "Lang kounye a:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Antre yon kòd lang ki valab san espas. Oswa, peze sou anile.",
  "Enter manually": "Antre ak men ou",
  "Enter new lang code (e.g., \"en-US\"):": "Antre nouvo kòd lang lan (egzanp, \"en-US\"):",
  "Indicate current language": "Endike lang kounye a",
  "Manually enter language {{number}}:": "Antre ak men ou lang {{number}}:",
  "New Language:": "Nouvo Lang:",
  "None": "Anyen",
  "Other - Enter manually": "Lòt bagay - Antre ak men ou",
  "Really remove all language markup from the document?": "Ou kwè ou vle retire tout mak lang yo nan dokiman an?",
  "Remove All lang markup": "Retire tout mak lang yo",
  "Remove Language Markup": "Retire mak lang yo",
  "Remove current lang value": "Retire valè lang kounye a",
  "Reveal lang markup": "Montre mak lang yo",
  "Select language {{number}}:": "Chwazi lang {{number}}:",
  "Select the document's default language.": "Chwazi lang dokiman an pa defo a.",
  "Set default document language": "Chwazi lang dokiman an pa defo",
  "Set text language": "Chwazi lang tèks la",
  "langName.af": "afrikaans",
  "langName.af-za": "afrikaans",
  "langName.ak": "akan",
  "langName.am": "amharique",
  "langName.ar": "arabe",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "arabe",
  "langName.az": "azerbaïdjanais",
  "langName.be": "biélorusse",
  "langName.bg": "bulgare",
  "langName.bg-bg": "bulgare",
  "langName.bho": "bhodjpouri",
  "langName.bm": "bambara",
  "langName.bn": "bengali",
  "langName.bo": "tibétain",
  "langName.bs": "bosniaque",
  "langName.ca": "catalan",
  "langName.cop": "copte",
  "langName.cr": "cree",
  "langName.cs": "tchèque",
  "langName.cu": "slavon d’église",
  "langName.cy": "gallois",
  "langName.da": "danois",
  "langName.de": "allemand",
  "langName.de-at": "allemand autrichien",
  "langName.de-ch": "allemand suisse",
  "langName.de-de": "allemand",
  "langName.dv": "maldivien",
  "langName.el": "grec",
  "langName.en": "anglais",
  "langName.en-au": "anglais australien",
  "langName.en-ca": "anglais canadien",
  "langName.en-gb": "anglais britannique",
  "langName.en-ie": "angle (Iland)",
  "langName.en-in": "angle (Enn)",
  "langName.en-tt": "angle (Trinidad)",
  "langName.en-us": "anglais américain",
  "langName.en-za": "angle (Afrik disid)",
  "langName.eo": "espéranto",
  "langName.es": "espagnol",
  "langName.es-ar": "panyòl (Ajantin)",
  "langName.es-cl": "panyòl (Chili)",
  "langName.es-co": "panyòl (Kolonbi)",
  "langName.es-cr": "",
  "langName.es-es": "espagnol d’Espagne",
  "langName.es-mx": "espagnol du Mexique",
  "langName.es-pe": "panyòl (Perou)",
  "langName.et": "estonien",
  "langName.eu": "basque",
  "langName.fa": "persan",
  "langName.fa-af": "dari",
  "langName.fa-ir": "persan",
  "langName.ff": "peul",
  "langName.fi": "finnois",
  "langName.fi-fi": "finnois",
  "langName.fil": "filipino",
  "langName.fr": "français",
  "langName.fr-be": "",
  "langName.fr-ca": "français canadien",
  "langName.fr-ch": "français suisse",
  "langName.ga": "irlandais",
  "langName.gl": "galicien",
  "langName.grc": "grec ancien",
  "langName.ha": "haoussa",
  "langName.he": "hébreu",
  "langName.he-il": "hébreu",
  "langName.hi": "hindi",
  "langName.hr": "croate",
  "langName.hr-hr": "croate",
  "langName.ht": "Kreyòl Ayisyen",
  "langName.hu": "hongrois",
  "langName.hu-hu": "hongrois",
  "langName.hy": "arménien",
  "langName.id": "indonésien",
  "langName.ig": "igbo",
  "langName.is": "islandais",
  "langName.it": "italien",
  "langName.it-it": "italien",
  "langName.iu": "inuktitut",
  "langName.ja": "japonais",
  "langName.ja-jp": "japonais",
  "langName.ka": "géorgien",
  "langName.kab": "kabyle",
  "langName.kk": "kazakh",
  "langName.km": "khmer",
  "langName.kn": "kannada",
  "langName.ko": "coréen",
  "langName.ko-kr": "coréen",
  "langName.la": "latin",
  "langName.lkt": "lakota",
  "langName.lo": "lao",
  "langName.lt": "lituanien",
  "langName.lv": "letton",
  "langName.mi": "maori",
  "langName.mn": "mongol",
  "langName.mr": "marathi",
  "langName.ms": "malais",
  "langName.mt": "maltais",
  "langName.my": "birman",
  "langName.nb": "norvégien bokmål",
  "langName.nb-no": "norvégien bokmål",
  "langName.ne": "népalais",
  "langName.nl": "néerlandais",
  "langName.nl-be": "flamand",
  "langName.nn": "norvégien nynorsk",
  "langName.nv": "navajo",
  "langName.ota": "turc ottoman",
  "langName.pa": "pendjabi",
  "langName.peo": "persan ancien",
  "langName.pl": "polonais",
  "langName.ps": "pachto",
  "langName.pt": "portugais",
  "langName.pt-br": "portugais brésilien",
  "langName.pt-pt": "portugais européen",
  "langName.qu": "quechua",
  "langName.ro": "roumain",
  "langName.ru": "russe",
  "langName.rw": "kinyarwanda",
  "langName.sa": "sanskrit",
  "langName.se": "same du Nord",
  "langName.si": "cingalais",
  "langName.sk-sk": "slovaque",
  "langName.sl": "slovène",
  "langName.sl-si": "slovène",
  "langName.sma": "same du Sud",
  "langName.sme": "sami dinò",
  "langName.smj": "same de Lule",
  "langName.sn": "shona",
  "langName.sr": "serbe",
  "langName.sr-latn": "",
  "langName.sv": "suédois",
  "langName.sv-se": "suédois",
  "langName.sw": "swahili",
  "langName.sw-ke": "swahili",
  "langName.sw-tz": "swahili",
  "langName.syc": "syriaque classique",
  "langName.ta": "tamoul",
  "langName.te": "télougou",
  "langName.tg": "tadjik",
  "langName.th": "thaï",
  "langName.th-th": "thaï",
  "langName.tk": "turkmène",
  "langName.tl": "tagalog",
  "langName.tr": "turc",
  "langName.tr-tr": "turc",
  "langName.tt": "tatar",
  "langName.ug": "ouïghour",
  "langName.uk": "ukrainien",
  "langName.ur": "ourdou",
  "langName.uz": "ouzbek",
  "langName.vi": "vietnamien",
  "langName.wo": "wolof",
  "langName.xh": "xhosa",
  "langName.yi": "yiddish",
  "langName.yo": "yoruba",
  "langName.yua": "maya youkatan",
  "langName.zh": "chinois",
  "langName.zh-cn": "chinois simplifié",
  "langName.zh-hans": "chinois simplifié",
  "langName.zh-hant": "chinois traditionnel",
  "langName.zh-hk": "chinwa (Hong Kong)",
  "langName.zh-sg": "",
  "langName.zh-tw": "chinois traditionnel",
  "langName.zu": "zoulou",
  "langName.zu-za": "zoulou"
});