tinymce.addI18n('ht', {
  "-Language Not Set-": "-Lang la pa chwazi-",
  "Choose from list": "Chwazi nan lis la",
  "Choose languages": "Chwazi lang yo",
  "Choose up to six languages": "Chwazi jiska sis lang",
  "Configure languages": "Konfigire lang yo",
  "Current language:": "Lang kounye a:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Antre yon kòd lang ki valab san espas. Oswa, peze sou anile.",
  "Enter manually": "Antre ak men ou",
  "Enter new lang code (e.g., \"en-US\"):": "Antre nouvo kòd lang lan (egzanp, \"en-US\"):",
  "Indicate current language": "Endike lang kounye a",
  "Manually enter language {{number}}:": "Antre ak men ou lang {{number}}:",
  "New Language:": "Nouvo Lang:",
  "None": "Anyen",
  "Other - Enter manually": "Lòt bagay - Antre ak men ou",
  "Really remove all language markup from the document?": "Ou kwè ou vle retire tout mak lang yo nan dokiman an?",
  "Remove All lang markup": "Retire tout mak lang yo",
  "Remove Language Markup": "Retire mak lang yo",
  "Remove current lang value": "Retire valè lang kounye a",
  "Reveal lang markup": "Montre mak lang yo",
  "Select language {{number}}:": "Chwazi lang {{number}}:",
  "Select the document's default language.": "Chwazi lang dokiman an pa defo a.",
  "Set default document language": "Chwazi lang dokiman an pa defo",
  "Set text language": "Chwazi lang tèks la",
  "langName.af": "afrikaans",
  "langName.af-za": "afrikaans (Afrik disid)",
  "langName.ak": "akan",
  "langName.am": "amharik",
  "langName.ar": "arab",
  "langName.ar-eg": "arab (Ejip)",
  "langName.ar-ma": "arab (Maròk)",
  "langName.ar-sa": "arab (Arabi Sawoudit)",
  "langName.az": "azerbaïdjanè",
  "langName.be": "byeloris",
  "langName.bg": "bilgar",
  "langName.bg-bg": "bilgar (Bilgari)",
  "langName.bho": "bhodjpouri",
  "langName.bm": "bambara",
  "langName.bn": "bengali",
  "langName.bo": "tibetè",
  "langName.bs": "bosniak",
  "langName.ca": "katalan",
  "langName.cop": "kòpt",
  "langName.cr": "kri",
  "langName.cs": "tchèk",
  "langName.cu": "slavon legliz",
  "langName.cy": "galwa",
  "langName.da": "danwa",
  "langName.de": "almè",
  "langName.de-at": "almè (Otrich)",
  "langName.de-ch": "almè (Swis)",
  "langName.de-de": "almè (Almay)",
  "langName.dv": "divehi",
  "langName.el": "grèk",
  "langName.en": "angle",
  "langName.en-au": "angle (Ostrali)",
  "langName.en-ca": "angle (Kanada)",
  "langName.en-gb": "angle (Wayòm Ini)",
  "langName.en-ie": "angle (Iland)",
  "langName.en-in": "angle (Enn)",
  "langName.en-tt": "angle (Trinidad)",
  "langName.en-us": "angle (Etazini)",
  "langName.en-za": "angle (Afrik disid)",
  "langName.eo": "esperanto",
  "langName.es": "panyòl",
  "langName.es-ar": "panyòl (Ajantin)",
  "langName.es-cl": "panyòl (Chili)",
  "langName.es-co": "panyòl (Kolonbi)",
  "langName.es-cr": "panyòl (Kosta Rika)",
  "langName.es-es": "panyòl (Pany)",
  "langName.es-mx": "panyòl (Meksik)",
  "langName.es-pe": "panyòl (Perou)",
  "langName.et": "estonyen",
  "langName.eu": "bask",
  "langName.fa": "pèsan",
  "langName.fa-af": "dari",
  "langName.fa-ir": "pèsan (Iran)",
  "langName.ff": "pèl",
  "langName.fi": "finwa",
  "langName.fi-fi": "finwa (Finland)",
  "langName.fil": "filipino",
  "langName.fr": "franse",
  "langName.fr-be": "franse (Bèljik)",
  "langName.fr-ca": "franse (Kanada)",
  "langName.fr-ch": "franse (Swis)",
  "langName.ga": "ilandè",
  "langName.gl": "galisyen",
  "langName.grc": "grèk (ansyen)",
  "langName.ha": "haoussa",
  "langName.he": "ebrè",
  "langName.he-il": "ebrè (Izrayèl)",
  "langName.hi": "hindi",
  "langName.hr": "kwoyat",
  "langName.hr-hr": "kwoyat (Kwoyasi)",
  "langName.ht": "kreyòl ayisyen",
  "langName.hu": "hongrwa",
  "langName.hu-hu": "hongrwa (Ongri)",
  "langName.hy": "amenyen",
  "langName.id": "endonezyen",
  "langName.ig": "igbo",
  "langName.is": "islandè",
  "langName.it": "italyen",
  "langName.it-it": "italyen (Itali)",
  "langName.iu": "inuktitut",
  "langName.ja": "japonè",
  "langName.ja-jp": "japonè (Japon)",
  "langName.ka": "jewojyen",
  "langName.kab": "kabil",
  "langName.kk": "kazak",
  "langName.km": "kmè",
  "langName.kn": "kannada",
  "langName.ko": "koreyen",
  "langName.ko-kr": "koreyen (Kore)",
  "langName.la": "latin",
  "langName.lkt": "lakota",
  "langName.lo": "lao",
  "langName.lt": "lityenyen",
  "langName.lv": "leton",
  "langName.mi": "maori",
  "langName.mn": "mongolyen",
  "langName.mr": "marathi",
  "langName.ms": "malè",
  "langName.mt": "maltè",
  "langName.my": "biman",
  "langName.nb": "nòvejyen (Bokmål)",
  "langName.nb-no": "nòvejyen (Bokmål, Nòvèj)",
  "langName.ne": "nepalè",
  "langName.nl": "ollandè",
  "langName.nl-be": "flamè",
  "langName.nn": "nòvejyen (Nynorsk)",
  "langName.nv": "navajo",
  "langName.ota": "tik (otomàn)",
  "langName.pa": "pendjabi",
  "langName.peo": "pèsan (ansyen)",
  "langName.pl": "polonè",
  "langName.ps": "pachto",
  "langName.pt": "pòtigè",
  "langName.pt-br": "pòtigè (Brezil)",
  "langName.pt-pt": "pòtigè (Pòtigal)",
  "langName.qu": "ketchwa",
  "langName.ro": "woumen",
  "langName.ru": "ris",
  "langName.rw": "kinyarwanda",
  "langName.sa": "sanskrit",
  "langName.se": "sami (kote nò)",
  "langName.si": "sinhala",
  "langName.sk": "slovak",
  "langName.sk-sk": "slovak (Slovaki)",
  "langName.sl": "slovenyen",
  "langName.sl-si": "slovenyen (Sloveni)",
  "langName.sma": "sami (kote sid)",
  "langName.sme": "sami (kote nò)",
  "langName.smj": "sami (Lule)",
  "langName.sn": "shona",
  "langName.sr": "sèb",
  "langName.sr-latn": "sèb (Latin)",
  "langName.sv": "swedwa",
  "langName.sv-se": "swedwa (Swèd)",
  "langName.sw": "swahili",
  "langName.sw-ke": "swahili (Kenya)",
  "langName.sw-tz": "swahili (Tanzani)",
  "langName.syc": "siryen (klasik)",
  "langName.ta": "tamil",
  "langName.te": "telougu",
  "langName.tg": "tadjik",
  "langName.th": "tay",
  "langName.th-th": "tay (Taylann)",
  "langName.tk": "tikmen",
  "langName.tl": "tagalog",
  "langName.tr": "tik",
  "langName.tr-tr": "tik (Tiki)",
  "langName.tt": "tata",
  "langName.ug": "ouyghour",
  "langName.uk": "ikrenyen",
  "langName.ur": "ourdou",
  "langName.uz": "ouzbèk",
  "langName.vi": "vyetnamyen",
  "langName.wo": "wolof",
  "langName.xh": "xhosa",
  "langName.yi": "yidich",
  "langName.yo": "yoruba",
  "langName.yua": "maya (Youkatan)",
  "langName.zh": "chinwa",
  "langName.zh-cn": "chinwa (senplif)",
  "langName.zh-hans": "chinwa (senplif)",
  "langName.zh-hant": "chinwa (tradisyonèl)",
  "langName.zh-hk": "chinwa (Hong Kong)",
  "langName.zh-sg": "chinwa (Singapou)",
  "langName.zh-tw": "chinwa (tradisyonèl)",
  "langName.zu": "zoulou",
  "langName.zu-za": "zoulou (Afrik disid)"
});