tinymce.addI18n("ht", {
  "Current language:": "Lang kounye a:",
  "Set text language": "Chwazi lang tèks la",
  "-Language Not Set-": "-Lang la pa chwazi-",
  "Choose languages": "Chwazi lang yo",
  "Remove Language Markup": "Retire mak lang yo",
  "Remove current lang value": "Retire valè lang kounye a",
  "Remove All lang markup": "Retire tout mak lang yo",
  "Configure languages": "Konfigire lang yo",
  "Set default document language": "Chwazi lang dokiman an pa defo",
  "Reveal lang markup": "Montre mak lang yo",
  "Indicate current language": "Endike lang kounye a",
  "Select the document's default language.": "Chwazi lang dokiman an pa defo a.",
  "Choose from list": "Chwazi nan lis la",
  "Enter manually": "Antre ak men ou",
  "None": "Anyen",
  "Other - Enter manually": "Lòt bagay - Antre ak men ou",
  "New Language:": "Nouvo Lang:",
  "Enter new lang code (e.g., \"en-US\"):": "Antre nouvo kòd lang lan (egzanp, \"en-US\"):",
  "Choose up to six languages": "Chwazi jiska sis lang",
  "Select language {{number}}:": "Chwazi lang {{number}}:",
  "Manually enter language {{number}}:": "Antre ak men ou lang {{number}}:",
  "Really remove all language markup from the document?": "Ou kwè ou vle retire tout mak lang yo nan dokiman an?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Antre yon kòd lang ki valab san espas. Oswa, peze sou anile.",
  "langName.af": "afriken",
  "langName.ak": "akan",
  "langName.ar": "arab",
  "langName.az": "azerbayjan",
  "langName.bg": "bilgè",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengali",
  "langName.bo": "tibetèn",
  "langName.bs": "bosnyen",
  "langName.ca": "katalan; valansyen",
  "langName.cs": "tchèk",
  "langName.cu": "bilgè ansyen",
  "langName.da": "danwa",
  "langName.de": "almèn",
  "langName.el": "grèk",
  "langName.en": "angle",
  "langName.en-au": "angle (Ostrali)",
  "langName.en-gb": "angle (Wayòm Ini)",
  "langName.en-in": "angle (Enn)",
  "langName.en-ie": "angle (Iland)",
  "langName.en-tt": "angle (Trinidad)",
  "langName.en-us": "angle (Etazini)",
  "langName.en-za": "angle (Afrik disid)",
  "langName.es": "panyòl",
  "langName.es-ar": "panyòl (Ajantin)",
  "langName.es-cl": "panyòl (Chili)",
  "langName.es-co": "panyòl (Kolonbi)",
  "langName.es-mx": "panyòl (Meksik)",
  "langName.es-pe": "panyòl (Perou)",
  "langName.et": "estonyen",
  "langName.eu": "bask",
  "langName.fa": "pèsan",
  "langName.fi": "fenlandez",
  "langName.fr": "fransè",
  "langName.fr-ca": "fransè (Kanada)",
  "langName.gl": "galisyen (Panyòl)",
  "langName.he": "ebre",
  "langName.hi": "indi",
  "langName.hr": "kwoasyen",
  "langName.hu": "ongwa",
  "langName.id": "endonezyen",
  "langName.it": "italyen",
  "langName.ja": "japonè",
  "langName.kk": "kazak",
  "langName.kn": "kannada",
  "langName.ko": "koreyen",
  "langName.la": "latin",
  "langName.lkt": "lakota",
  "langName.mn": "mongòl",
  "langName.mr": "marati",
  "langName.nb": "nòvejyen bokmål",
  "langName.nl": "olandez",
  "langName.nl-be": "olandez (Bèljik)",
  "langName.nn": "nòvejyen nynorsk",
  "langName.pl": "polonè",
  "langName.ps": "pachto",
  "langName.pt": "pòtigè, entènasyonal",
  "langName.pt-br": "pòtigè, Brezil",
  "langName.qu": "ketchwa",
  "langName.ro": "woumen",
  "langName.ru": "ris",
  "langName.sa": "sanskri",
  "langName.sk-sk": "slovak",
  "langName.sl": "slovenyen",
  "langName.sma": "sami disid",
  "langName.sme": "sami dinò",
  "langName.smj": "sami lule",
  "langName.sr": "sèb",
  "langName.sv": "syèdwa",
  "langName.sw": "swayili",
  "langName.ta": "tamil",
  "langName.te": "telougou",
  "langName.tg": "tajik",
  "langName.th": "tay",
  "langName.tr": "tik",
  "langName.ug": "ouygou",
  "langName.uk": "ikrenyen",
  "langName.ur": "oudou",
  "langName.uz": "ouzbèk",
  "langName.vi": "vyetnamyen",
  "langName.wo": "wolof",
  "langName.yi": "yidich",
  "langName.yo": "yorouba",
  "langName.yua": "maya youkatan",
  "langName.zh": "chinwa",
  "langName.zh-cn": "chinwa (Lachin)",
  "langName.zh-hk": "chinwa (Hong Kong)",
  "langName.zh-tw": "chinwa (Taywan)",
  "langName.zh-hans": "chinwa, senplè",
  "langName.zh-hant": "chinwa, tradisyonèl",
  "langName.zu": "zoulou"
});