tinymce.addI18n("hu", {
  "Current language:": "Jelenlegi nyelv:",
  "Set text language": "Szöveg nyelvének beállítása",
  "-Language Not Set-": "-Nyelv nincs beállítva-",
  "Choose languages": "Nyelvek kiválasztása",
  "Remove Language Markup": "Nyelvi jelölés eltávolítása",
  "Remove current lang value": "Jelenlegi nyelvi érték eltávolítása",
  "Remove All lang markup": "Minden nyelvi jelölés eltávolítása",
  "Configure languages": "Nyelvek konfigurálása",
  "Set default document language": "Alapértelmezett dokumentumnyelv beállítása",
  "Reveal lang markup": "Nyelvi jelölés megjelenítése",
  "Indicate current language": "Jelenlegi nyelv jelzése",
  "Select the document's default language.": "Válassza ki a dokumentum alapértelmezett nyelvét.",
  "Choose from list": "Kiválasztás listából",
  "Enter manually": "Kézi bevitel",
  "None": "Nincs",
  "Other - Enter manually": "Egyéb - Kézi bevitel",
  "New Language:": "Új nyelv:",
  "Enter new lang code (e.g., \"en-US\"):": "Adja meg az új nyelvkódot (pl. \"en-US\"):",
  "Choose up to six languages": "Válasszon ki legfeljebb hat nyelvet",
  "Select language {{number}}:": "Válassza ki a(z) {{number}}. nyelvet:",
  "Manually enter language {{number}}:": "Adja meg kézzel a(z) {{number}}. nyelvet:",
  "Really remove all language markup from the document?": "Valóban eltávolítja az összes nyelvi jelölést a dokumentumból?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Adjon meg egy érvényes nyelvkódot szóközök nélkül. Vagy nyomja meg a mégsem gombot.",
  "langName.af": "afrikaans",
  "langName.ak": "akan",
  "langName.ar": "arab",
  "langName.az": "azerbajdzsáni",
  "langName.bg": "bolgár",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengáli",
  "langName.bo": "tibeti",
  "langName.bs": "bosnyák",
  "langName.ca": "katalán; valencia",
  "langName.cs": "cseh",
  "langName.cu": "óbolgár",
  "langName.da": "dán",
  "langName.de": "német",
  "langName.el": "görög",
  "langName.en": "angol",
  "langName.en-au": "angol (Ausztrália)",
  "langName.en-gb": "angol (Egyesült Királyság)",
  "langName.en-in": "angol (India)",
  "langName.en-ie": "angol (Írország)",
  "langName.en-tt": "angol (Trinidad)",
  "langName.en-us": "angol (Egyesült Államok)",
  "langName.en-za": "angol (Dél-Afrika)",
  "langName.es": "spanyol",
  "langName.es-ar": "spanyol (Argentína)",
  "langName.es-cl": "spanyol (Chile)",
  "langName.es-co": "spanyol (Kolumbia)",
  "langName.es-mx": "spanyol (Mexikó)",
  "langName.es-pe": "spanyol (Peru)",
  "langName.et": "észt",
  "langName.eu": "baszk",
  "langName.fa": "perzsa",
  "langName.fi": "finn",
  "langName.fr": "francia",
  "langName.fr-ca": "francia (Kanada)",
  "langName.gl": "galíciai (Spanyolország)",
  "langName.he": "héber",
  "langName.hi": "hindi",
  "langName.hr": "horvát",
  "langName.hu": "magyar",
  "langName.id": "indonéz",
  "langName.it": "olasz",
  "langName.ja": "japán",
  "langName.kk": "kazah",
  "langName.kn": "kannada",
  "langName.ko": "koreai",
  "langName.la": "latin",
  "langName.lkt": "lakota",
  "langName.mn": "mongol",
  "langName.mr": "marathi",
  "langName.nb": "norvég bokmål",
  "langName.nl": "holland",
  "langName.nl-be": "holland (Belgium)",
  "langName.nn": "norvég nynorsk",
  "langName.pl": "lengyel",
  "langName.ps": "pastu",
  "langName.pt": "portugál, nemzetközi",
  "langName.pt-br": "portugál, brazíliai",
  "langName.qu": "kecsua",
  "langName.ro": "román",
  "langName.ru": "orosz",
  "langName.sa": "szanszkrit",
  "langName.sk-sk": "szlovák",
  "langName.sl": "szlovén",
  "langName.sma": "déli számi",
  "langName.sme": "északi számi",
  "langName.smj": "lule számi",
  "langName.sr": "szerb",
  "langName.sv": "svéd",
  "langName.sw": "szuahéli",
  "langName.ta": "tamil",
  "langName.te": "telugu",
  "langName.tg": "tadzsik",
  "langName.th": "thai",
  "langName.tr": "török",
  "langName.ug": "ujgur",
  "langName.uk": "ukrán",
  "langName.ur": "urdu",
  "langName.uz": "üzbég",
  "langName.vi": "vietnámi",
  "langName.wo": "volof",
  "langName.yi": "jiddis",
  "langName.yo": "joruba",
  "langName.yua": "jukatan maja",
  "langName.zh": "kínai",
  "langName.zh-cn": "kínai (Kína)",
  "langName.zh-hk": "kínai (Hongkong)",
  "langName.zh-tw": "kínai (Tajvan)",
  "langName.zh-hans": "kínai, egyszerűsített",
  "langName.zh-hant": "kínai, hagyományos",
  "langName.zu": "zulu"
});