tinymce.addI18n('hu_HU', {
  "-Language Not Set-": "-Nyelv nincs beállítva-",
  "Choose from list": "Kiválasztás listából",
  "Choose languages": "Nyelvek kiválasztása",
  "Choose up to six languages": "Válasszon ki legfeljebb hat nyelvet",
  "Configure languages": "Nyelvek konfigurálása",
  "Current language:": "Jelenlegi nyelv:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Adjon meg egy érvényes nyelvkódot szóközök nélkül. Vagy nyomja meg a mégsem gombot.",
  "Enter manually": "Kézi bevitel",
  "Enter new lang code (e.g., \"en-US\"):": "Adja meg az új nyelvkódot (pl. \"en-US\"):",
  "Indicate current language": "Jelenlegi nyelv jelzése",
  "Manually enter language {{number}}:": "Adja meg kézzel a(z) {{number}}. nyelvet:",
  "New Language:": "Új nyelv:",
  "None": "Nincs",
  "Other - Enter manually": "Egyéb - Kézi bevitel",
  "Really remove all language markup from the document?": "Valóban eltávolítja az összes nyelvi jelölést a dokumentumból?",
  "Remove All lang markup": "Minden nyelvi jelölés eltávolítása",
  "Remove Language Markup": "Nyelvi jelölés eltávolítása",
  "Remove current lang value": "Jelenlegi nyelvi érték eltávolítása",
  "Reveal lang markup": "Nyelvi jelölés megjelenítése",
  "Select language {{number}}:": "Válassza ki a(z) {{number}}. nyelvet:",
  "Select the document's default language.": "Válassza ki a dokumentum alapértelmezett nyelvét.",
  "Set default document language": "Alapértelmezett dokumentumnyelv beállítása",
  "Set text language": "Szöveg nyelvének beállítása",
  "langName.af": "afrikaans",
  "langName.af-za": "afrikaans",
  "langName.ak": "akan",
  "langName.am": "amhara",
  "langName.ar": "arab",
  "langName.ar-eg": "egyiptomi arab",
  "langName.ar-ma": "marokkói arab",
  "langName.ar-sa": "arab",
  "langName.az": "azerbajdzsáni",
  "langName.be": "belarusz",
  "langName.bg": "bolgár",
  "langName.bg-bg": "bolgár",
  "langName.bho": "bodzspuri",
  "langName.bm": "bambara",
  "langName.bn": "bangla",
  "langName.bo": "tibeti",
  "langName.bs": "bosnyák",
  "langName.ca": "katalán",
  "langName.cop": "kopt",
  "langName.cr": "krí",
  "langName.cs": "cseh",
  "langName.cu": "egyházi szláv",
  "langName.cy": "walesi",
  "langName.da": "dán",
  "langName.de": "német",
  "langName.de-at": "osztrák német",
  "langName.de-ch": "svájci felnémet",
  "langName.de-de": "német",
  "langName.dv": "divehi",
  "langName.el": "görög",
  "langName.en": "angol",
  "langName.en-au": "ausztrál angol",
  "langName.en-ca": "kanadai angol",
  "langName.en-gb": "brit angol",
  "langName.en-ie": "angol (Írország)",
  "langName.en-in": "angol (India)",
  "langName.en-tt": "angol (Trinidad)",
  "langName.en-us": "amerikai angol",
  "langName.en-za": "angol (Dél-Afrika)",
  "langName.eo": "eszperantó",
  "langName.es": "spanyol",
  "langName.es-ar": "spanyol (Argentína)",
  "langName.es-cl": "spanyol (Chile)",
  "langName.es-co": "spanyol (Kolumbia)",
  "langName.es-cr": "spanyol (Costa Rica)",
  "langName.es-es": "európai spanyol",
  "langName.es-mx": "spanyol (mexikói)",
  "langName.es-pe": "spanyol (Peru)",
  "langName.et": "észt",
  "langName.eu": "baszk",
  "langName.fa": "perzsa",
  "langName.fa-af": "dari",
  "langName.fa-ir": "perzsa",
  "langName.ff": "fulani",
  "langName.fi": "finn",
  "langName.fi-fi": "finn",
  "langName.fil": "filippínó",
  "langName.fr": "francia",
  "langName.fr-be": "belga francia",
  "langName.fr-ca": "kanadai francia",
  "langName.fr-ch": "svájci francia",
  "langName.ga": "ír",
  "langName.gl": "gallego",
  "langName.grc": "ógörög",
  "langName.ha": "hausza",
  "langName.he": "héber",
  "langName.he-il": "héber",
  "langName.hi": "hindi",
  "langName.hr": "horvát",
  "langName.hr-hr": "horvát",
  "langName.ht": "haiti kreol",
  "langName.hu": "magyar",
  "langName.hu-hu": "magyar",
  "langName.hy": "örmény",
  "langName.id": "indonéz",
  "langName.ig": "igbó",
  "langName.is": "izlandi",
  "langName.it": "olasz",
  "langName.it-it": "olasz",
  "langName.iu": "inuktitut",
  "langName.ja": "japán",
  "langName.ja-jp": "japán",
  "langName.ka": "grúz",
  "langName.kab": "kabije",
  "langName.kk": "kazah",
  "langName.km": "khmer",
  "langName.kn": "kannada",
  "langName.ko": "koreai",
  "langName.ko-kr": "koreai",
  "langName.la": "latin",
  "langName.lkt": "lakota",
  "langName.lo": "lao",
  "langName.lt": "litván",
  "langName.lv": "lett",
  "langName.mi": "maori",
  "langName.mn": "mongol",
  "langName.mr": "maráthi",
  "langName.ms": "maláj",
  "langName.mt": "máltai",
  "langName.my": "burmai",
  "langName.nb": "norvég (bokmål)",
  "langName.nb-no": "norvég (bokmål)",
  "langName.ne": "nepáli",
  "langName.nl": "holland",
  "langName.nl-be": "flamand",
  "langName.nn": "norvég (nynorsk)",
  "langName.nv": "navahó",
  "langName.ota": "oszmán-török",
  "langName.pa": "pandzsábi",
  "langName.peo": "óperzsa",
  "langName.pl": "lengyel",
  "langName.ps": "pastu",
  "langName.pt": "portugál",
  "langName.pt-br": "brazíliai portugál",
  "langName.pt-pt": "európai portugál",
  "langName.qu": "kecsua",
  "langName.ro": "román",
  "langName.ru": "orosz",
  "langName.rw": "kinyarvanda",
  "langName.sa": "szanszkrit",
  "langName.se": "északi számi",
  "langName.si": "szingaléz",
  "langName.sk-sk": "szlovák",
  "langName.sl": "szlovén",
  "langName.sl-si": "szlovén",
  "langName.sma": "déli számi",
  "langName.sme": "északi számi",
  "langName.smj": "lulei számi",
  "langName.sn": "sona",
  "langName.sr": "szerb",
  "langName.sr-latn": "szerb (latin)",
  "langName.sv": "svéd",
  "langName.sv-se": "svéd",
  "langName.sw": "szuahéli",
  "langName.sw-ke": "szuahéli",
  "langName.sw-tz": "szuahéli",
  "langName.syc": "klasszikus szír",
  "langName.ta": "tamil",
  "langName.te": "telugu",
  "langName.tg": "tadzsik",
  "langName.th": "thai",
  "langName.th-th": "thai",
  "langName.tk": "türkmén",
  "langName.tl": "tagalog",
  "langName.tr": "török",
  "langName.tr-tr": "török",
  "langName.tt": "tatár",
  "langName.ug": "ujgur",
  "langName.uk": "ukrán",
  "langName.ur": "urdu",
  "langName.uz": "üzbég",
  "langName.vi": "vietnámi",
  "langName.wo": "volof",
  "langName.xh": "xhosza",
  "langName.yi": "jiddis",
  "langName.yo": "joruba",
  "langName.yua": "jukatan maja",
  "langName.zh": "kínai",
  "langName.zh-cn": "egyszerűsített kínai",
  "langName.zh-hans": "egyszerűsített kínai",
  "langName.zh-hant": "hagyományos kínai",
  "langName.zh-hk": "kínai (Hongkong)",
  "langName.zh-sg": "kínai (Szingapúr)",
  "langName.zh-tw": "hagyományos kínai",
  "langName.zu": "zulu",
  "langName.zu-za": "zulu"
});