tinymce.addI18n('hy', {
  "-Language Not Set-": "-Լեզուն չի սահմանված-",
  "Choose from list": "Ընտրել ցանկից",
  "Choose languages": "Ընտրել լեզուներ",
  "Choose up to six languages": "Ընտրել մինչև վեց լեզու",
  "Configure languages": "Կարգավորել լեզուները",
  "Current language:": "Ներկայիս լեզու․",
  "Enter a valid language code with no spaces. Or, press cancel.": "Մուտքագրել վավեր լեզվի կոդ առանց բացատների։ Կամ սեղմել չեղարկել։",
  "Enter manually": "Մուտքագրել ձեռքով",
  "Enter new lang code (e.g., \"en-US\"):": "Մուտքագրել նոր լեզվի կոդը (օր․՝ \"en-US\")․",
  "Indicate current language": "Ցույց տալ ներկայիս լեզուն",
  "Manually enter language {{number}}:": "Ձեռքով մուտքագրել {{number}} լեզուն․",
  "New Language:": "Նոր լեզու․",
  "None": "Ոչինչ",
  "Other - Enter manually": "Այլ - Մուտքագրել ձեռքով",
  "Really remove all language markup from the document?": "Իսկապե՞ս հեռացնել բոլոր լեզվական նշանակումները փաստաթղթից։",
  "Remove All lang markup": "Հեռացնել բոլոր լեզվական նշանակումները",
  "Remove Language Markup": "Հեռացնել լեզվական նշանակումը",
  "Remove current lang value": "Հեռացնել ներկայիս լեզվի արժեքը",
  "Reveal lang markup": "Ցույց տալ լեզվական նշանակումը",
  "Select language {{number}}:": "Ընտրել {{number}} լեզուն․",
  "Select the document's default language.": "Ընտրել փաստաթղթի լռելյայն լեզուն։",
  "Set default document language": "Սահմանել փաստաթղթի լռելյայն լեզուն",
  "Set text language": "Սահմանել տեքստի լեզուն",
  "langName.af": "աֆրիկաանս",
  "langName.af-za": "աֆրիկաանս",
  "langName.ak": "աքան",
  "langName.am": "ամհարերեն",
  "langName.ar": "արաբերեն",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "արաբերեն",
  "langName.az": "ադրբեջաներեն",
  "langName.be": "բելառուսերեն",
  "langName.bg": "բուլղարերեն",
  "langName.bg-bg": "բուլղարերեն",
  "langName.bho": "բհոպուրի",
  "langName.bm": "բամբարա",
  "langName.bn": "բենգալերեն",
  "langName.bo": "տիբեթերեն",
  "langName.bs": "բոսնիերեն",
  "langName.ca": "կատալաներեն",
  "langName.cop": "ղպտերեն",
  "langName.cr": "",
  "langName.cs": "չեխերեն",
  "langName.cu": "սլավոներեն, եկեղեցական",
  "langName.cy": "ուելսերեն",
  "langName.da": "դանիերեն",
  "langName.de": "գերմաներեն",
  "langName.de-at": "ավստրիական գերմաներեն",
  "langName.de-ch": "շվեյցարական վերին գերմաներեն",
  "langName.de-de": "գերմաներեն",
  "langName.dv": "դիվեհի",
  "langName.el": "հունարեն",
  "langName.en": "անգլերեն",
  "langName.en-au": "ավստրալիական անգլերեն",
  "langName.en-ca": "կանադական անգլերեն",
  "langName.en-gb": "բրիտանական անգլերեն",
  "langName.en-ie": "անգլերեն (Իռլանդիա)",
  "langName.en-in": "անգլերեն (Հնդկաստան)",
  "langName.en-tt": "անգլերեն (Տրինիդադ)",
  "langName.en-us": "ամերիկյան անգլերեն",
  "langName.en-za": "անգլերեն (Հարավային Աֆրիկա)",
  "langName.eo": "էսպերանտո",
  "langName.es": "իսպաներեն",
  "langName.es-ar": "իսպաներեն (Արգենտինա)",
  "langName.es-cl": "իսպաներեն (Չիլի)",
  "langName.es-co": "իսպաներեն (Կոլումբիա)",
  "langName.es-cr": "",
  "langName.es-es": "եվրոպական իսպաներեն",
  "langName.es-mx": "մեքսիկական իսպաներեն",
  "langName.es-pe": "իսպաներեն (Պերու)",
  "langName.et": "էստոներեն",
  "langName.eu": "բասկերեն",
  "langName.fa": "պարսկերեն",
  "langName.fa-af": "դարի",
  "langName.fa-ir": "պարսկերեն",
  "langName.ff": "ֆուլահ",
  "langName.fi": "ֆիններեն",
  "langName.fi-fi": "ֆիններեն",
  "langName.fil": "ֆիլիպիներեն",
  "langName.fr": "ֆրանսերեն",
  "langName.fr-be": "",
  "langName.fr-ca": "կանադական ֆրանսերեն",
  "langName.fr-ch": "շվեյցարական ֆրանսերեն",
  "langName.ga": "իռլանդերեն",
  "langName.gl": "գալիսերեն",
  "langName.grc": "հին հունարեն",
  "langName.ha": "հաուսա",
  "langName.he": "եբրայերեն",
  "langName.he-il": "եբրայերեն",
  "langName.hi": "հինդի",
  "langName.hr": "խորվաթերեն",
  "langName.hr-hr": "խորվաթերեն",
  "langName.ht": "խառնակերտ հայիթերեն",
  "langName.hu": "հունգարերեն",
  "langName.hu-hu": "հունգարերեն",
  "langName.hy": "հայերեն",
  "langName.id": "ինդոնեզերեն",
  "langName.ig": "իգբո",
  "langName.is": "իսլանդերեն",
  "langName.it": "իտալերեն",
  "langName.it-it": "իտալերեն",
  "langName.iu": "ինուկտիտուտ",
  "langName.ja": "ճապոներեն",
  "langName.ja-jp": "ճապոներեն",
  "langName.ka": "վրացերեն",
  "langName.kab": "կաբիլերեն",
  "langName.kk": "ղազախերեն",
  "langName.km": "քմերերեն",
  "langName.kn": "կաննադա",
  "langName.ko": "կորեերեն",
  "langName.ko-kr": "կորեերեն",
  "langName.la": "լատիներեն",
  "langName.lkt": "լակոտա",
  "langName.lo": "լաոսերեն",
  "langName.lt": "լիտվերեն",
  "langName.lv": "լատվիերեն",
  "langName.mi": "մաորի",
  "langName.mn": "մոնղոլերեն",
  "langName.mr": "մարաթի",
  "langName.ms": "մալայերեն",
  "langName.mt": "մալթայերեն",
  "langName.my": "բիրմայերեն",
  "langName.nb": "գրքային նորվեգերեն",
  "langName.nb-no": "գրքային նորվեգերեն",
  "langName.ne": "նեպալերեն",
  "langName.nl": "հոլանդերեն",
  "langName.nl-be": "ֆլամանդերեն",
  "langName.nn": "նոր նորվեգերեն",
  "langName.nv": "նավախո",
  "langName.ota": "օսմաներեն",
  "langName.pa": "փենջաբերեն",
  "langName.peo": "հին պարսկերեն",
  "langName.pl": "լեհերեն",
  "langName.ps": "փուշթու",
  "langName.pt": "պորտուգալերեն",
  "langName.pt-br": "բրազիլական պորտուգալերեն",
  "langName.pt-pt": "եվրոպական պորտուգալերեն",
  "langName.qu": "կեչուա",
  "langName.ro": "ռումիներեն",
  "langName.ru": "ռուսերեն",
  "langName.rw": "կինյառուանդա",
  "langName.sa": "սանսկրիտ",
  "langName.se": "հյուսիսային սաամի",
  "langName.si": "սինհալերեն",
  "langName.sk-sk": "սլովակերեն",
  "langName.sl": "սլովեներեն",
  "langName.sl-si": "սլովեներեն",
  "langName.sma": "հարավային սաամի",
  "langName.sme": "հյուսիսային սամի",
  "langName.smj": "լուլե սաամի",
  "langName.sn": "շոնա",
  "langName.sr": "սերբերեն",
  "langName.sr-latn": "",
  "langName.sv": "շվեդերեն",
  "langName.sv-se": "շվեդերեն",
  "langName.sw": "սուահիլի",
  "langName.sw-ke": "սուահիլի",
  "langName.sw-tz": "սուահիլի",
  "langName.syc": "",
  "langName.ta": "թամիլերեն",
  "langName.te": "թելուգու",
  "langName.tg": "տաջիկերեն",
  "langName.th": "թայերեն",
  "langName.th-th": "թայերեն",
  "langName.tk": "թուրքմեներեն",
  "langName.tl": "տագալերեն",
  "langName.tr": "թուրքերեն",
  "langName.tr-tr": "թուրքերեն",
  "langName.tt": "թաթարերեն",
  "langName.ug": "ույղուրերեն",
  "langName.uk": "ուկրաիներեն",
  "langName.ur": "ուրդու",
  "langName.uz": "ուզբեկերեն",
  "langName.vi": "վիետնամերեն",
  "langName.wo": "վոլոֆ",
  "langName.xh": "քոսա",
  "langName.yi": "իդիշ",
  "langName.yo": "յորուբա",
  "langName.yua": "յուկատեկ մայա",
  "langName.zh": "չինարեն",
  "langName.zh-cn": "պարզեցված չինարեն",
  "langName.zh-hans": "պարզեցված չինարեն",
  "langName.zh-hant": "ավանդական չինարեն",
  "langName.zh-hk": "չիներեն (Հոնկոնգ)",
  "langName.zh-sg": "",
  "langName.zh-tw": "ավանդական չինարեն",
  "langName.zu": "զուլուերեն",
  "langName.zu-za": "զուլուերեն"
});