tinymce.addI18n("hy", {
  "Current language:": "Ներկայիս լեզու․",
  "Set text language": "Սահմանել տեքստի լեզուն",
  "-Language Not Set-": "-Լեզուն չի սահմանված-",
  "Choose languages": "Ընտրել լեզուներ",
  "Remove Language Markup": "Հեռացնել լեզվական նշանակումը",
  "Remove current lang value": "Հեռացնել ներկայիս լեզվի արժեքը",
  "Remove All lang markup": "Հեռացնել բոլոր լեզվական նշանակումները",
  "Configure languages": "Կարգավորել լեզուները",
  "Set default document language": "Սահմանել փաստաթղթի լռելյայն լեզուն",
  "Reveal lang markup": "Ցույց տալ լեզվական նշանակումը",
  "Indicate current language": "Ցույց տալ ներկայիս լեզուն",
  "Select the document's default language.": "Ընտրել փաստաթղթի լռելյայն լեզուն։",
  "Choose from list": "Ընտրել ցանկից",
  "Enter manually": "Մուտքագրել ձեռքով",
  "None": "Ոչինչ",
  "Other - Enter manually": "Այլ - Մուտքագրել ձեռքով",
  "New Language:": "Նոր լեզու․",
  "Enter new lang code (e.g., \"en-US\"):": "Մուտքագրել նոր լեզվի կոդը (օր․՝ \"en-US\")․",
  "Choose up to six languages": "Ընտրել մինչև վեց լեզու",
  "Select language {{number}}:": "Ընտրել {{number}} լեզուն․",
  "Manually enter language {{number}}:": "Ձեռքով մուտքագրել {{number}} լեզուն․",
  "Really remove all language markup from the document?": "Իսկապե՞ս հեռացնել բոլոր լեզվական նշանակումները փաստաթղթից։",
  "Enter a valid language code with no spaces. Or, press cancel.": "Մուտքագրել վավեր լեզվի կոդ առանց բացատների։ Կամ սեղմել չեղարկել։",
  "langName.af": "աֆրիկաանս",
  "langName.ak": "ական",
  "langName.ar": "արաբերեն",
  "langName.az": "ադրբեջաներեն",
  "langName.bg": "բուլղարերեն",
  "langName.bho": "բհոջպուրի",
  "langName.bm": "բամբարա",
  "langName.bn": "բենգալերեն",
  "langName.bo": "տիբեթերեն",
  "langName.bs": "բոսնիերեն",
  "langName.ca": "կատալաներեն; վալենսիերեն",
  "langName.cs": "չեխերեն",
  "langName.cu": "հին բուլղարերեն",
  "langName.da": "դանիերեն",
  "langName.de": "գերմաներեն",
  "langName.el": "հունարեն",
  "langName.en": "անգլերեն",
  "langName.en-au": "անգլերեն (Ավստրալիա)",
  "langName.en-gb": "անգլերեն (Մեծ Բրիտանիա)",
  "langName.en-in": "անգլերեն (Հնդկաստան)",
  "langName.en-ie": "անգլերեն (Իռլանդիա)",
  "langName.en-tt": "անգլերեն (Տրինիդադ)",
  "langName.en-us": "անգլերեն (ԱՄՆ)",
  "langName.en-za": "անգլերեն (Հարավային Աֆրիկա)",
  "langName.es": "իսպաներեն",
  "langName.es-ar": "իսպաներեն (Արգենտինա)",
  "langName.es-cl": "իսպաներեն (Չիլի)",
  "langName.es-co": "իսպաներեն (Կոլումբիա)",
  "langName.es-mx": "իսպաներեն (Մեքսիկա)",
  "langName.es-pe": "իսպաներեն (Պերու)",
  "langName.et": "էստոներեն",
  "langName.eu": "բասկերեն",
  "langName.fa": "պարսկերեն",
  "langName.fi": "ֆիներեն",
  "langName.fr": "ֆրանսերեն",
  "langName.fr-ca": "ֆրանսերեն (Կանադա)",
  "langName.gl": "գալիսիերեն (Իսպանիա)",
  "langName.he": "եբրայերեն",
  "langName.hi": "հինդի",
  "langName.hr": "խորվաթերեն",
  "langName.hu": "հունգարերեն",
  "langName.id": "ինդոնեզիերեն",
  "langName.it": "իտալերեն",
  "langName.ja": "ճապոներեն",
  "langName.kk": "ղազախերեն",
  "langName.kn": "կանադա",
  "langName.ko": "կորեերեն",
  "langName.la": "լատիներեն",
  "langName.lkt": "լակոտա",
  "langName.mn": "մոնղոլերեն",
  "langName.mr": "մարաթի",
  "langName.nb": "նորվեգերեն բոկմալ",
  "langName.nl": "հոլանդերեն",
  "langName.nl-be": "հոլանդերեն (Բելգիա)",
  "langName.nn": "նորվեգերեն նյունոշք",
  "langName.pl": "լեհերեն",
  "langName.ps": "փաշտո",
  "langName.pt": "պորտուգալերեն, միջազգային",
  "langName.pt-br": "պորտուգալերեն, Բրազիլիա",
  "langName.qu": "կեչուա",
  "langName.ro": "ռումիներեն",
  "langName.ru": "ռուսերեն",
  "langName.sa": "սանսկրիտ",
  "langName.sk-sk": "սլովակերեն",
  "langName.sl": "սլովեներեն",
  "langName.sma": "հարավային սամի",
  "langName.sme": "հյուսիսային սամի",
  "langName.smj": "լուլե սամի",
  "langName.sr": "սերբերեն",
  "langName.sv": "շվեդերեն",
  "langName.sw": "սվահիլի",
  "langName.ta": "տամիլերեն",
  "langName.te": "տելուգու",
  "langName.tg": "տաջիկերեն",
  "langName.th": "թայերեն",
  "langName.tr": "թուրքերեն",
  "langName.ug": "ույղուրերեն",
  "langName.uk": "ուկրաիներեն",
  "langName.ur": "ուրդու",
  "langName.uz": "ուզբեկերեն",
  "langName.vi": "վիետնամերեն",
  "langName.wo": "վոլոֆ",
  "langName.yi": "իդիշ",
  "langName.yo": "յորուբա",
  "langName.yua": "յուկատեկ մայա",
  "langName.zh": "չիներեն",
  "langName.zh-cn": "չիներեն (Չինաստան)",
  "langName.zh-hk": "չիներեն (Հոնկոնգ)",
  "langName.zh-tw": "չիներեն (Թայվան)",
  "langName.zh-hans": "չիներեն, պարզեցված",
  "langName.zh-hant": "չիներեն, ավանդական",
  "langName.zu": "զուլու"
});