tinymce.addI18n("id", {
  "Current language:": "Bahasa saat ini:",
  "Set text language": "Atur bahasa teks",
  "-Language Not Set-": "-Bahasa Tidak Diatur-",
  "Choose languages": "Pilih bahasa",
  "Remove Language Markup": "Hapus Markup Bahasa",
  "Remove current lang value": "Hapus nilai bahasa saat ini",
  "Remove All lang markup": "Hapus semua markup bahasa",
  "Configure languages": "Konfigurasi bahasa",
  "Set default document language": "Atur bahasa dokumen default",
  "Reveal lang markup": "Tampilkan markup bahasa",
  "Indicate current language": "Tunjukkan bahasa saat ini",
  "Select the document's default language.": "Pilih bahasa default dokumen.",
  "Choose from list": "Pilih dari daftar",
  "Enter manually": "Masukkan secara manual",
  "None": "Tidak ada",
  "Other - Enter manually": "Lainnya - Masukkan secara manual",
  "New Language:": "Bahasa Baru:",
  "Enter new lang code (e.g., \"en-US\"):": "Masukkan kode bahasa baru (contoh, \"en-US\"):",
  "Choose up to six languages": "Pilih hingga enam bahasa",
  "Select language {{number}}:": "Pilih bahasa {{number}}:",
  "Manually enter language {{number}}:": "Masukkan secara manual bahasa {{number}}:",
  "Really remove all language markup from the document?": "Benar-benar hapus semua markup bahasa dari dokumen?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Masukkan kode bahasa yang valid tanpa spasi. Atau tekan batal.",
  "langName.af": "Afrikaans",
  "langName.ak": "Akan",
  "langName.ar": "Arab",
  "langName.az": "Azerbaijan",
  "langName.bg": "Bulgaria",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengali",
  "langName.bo": "Tibet",
  "langName.bs": "Bosnia",
  "langName.ca": "Katalan; Valencia",
  "langName.cs": "Ceko",
  "langName.cu": "Bulgaria Kuno",
  "langName.da": "Denmark",
  "langName.de": "Jerman",
  "langName.el": "Yunani",
  "langName.en": "Inggris",
  "langName.en-au": "Inggris (Australia)",
  "langName.en-gb": "Inggris (Inggris Raya)",
  "langName.en-in": "Inggris (India)",
  "langName.en-ie": "Inggris (Irlandia)",
  "langName.en-tt": "Inggris (Trinidad)",
  "langName.en-us": "Inggris (Amerika Serikat)",
  "langName.en-za": "Inggris (Afrika Selatan)",
  "langName.es": "Spanyol",
  "langName.es-ar": "Spanyol (Argentina)",
  "langName.es-cl": "Spanyol (Chili)",
  "langName.es-co": "Spanyol (Kolombia)",
  "langName.es-mx": "Spanyol (Meksiko)",
  "langName.es-pe": "Spanyol (Peru)",
  "langName.et": "Estonia",
  "langName.eu": "Basque",
  "langName.fa": "Persia",
  "langName.fi": "Finlandia",
  "langName.fr": "Prancis",
  "langName.fr-ca": "Prancis (Kanada)",
  "langName.gl": "Galisia (Spanyol)",
  "langName.he": "Ibrani",
  "langName.hi": "Hindi",
  "langName.hr": "Kroasia",
  "langName.hu": "Hungaria",
  "langName.id": "Indonesia",
  "langName.it": "Italia",
  "langName.ja": "Jepang",
  "langName.kk": "Kazakh",
  "langName.kn": "Kannada",
  "langName.ko": "Korea",
  "langName.la": "Latin",
  "langName.lkt": "Lakota",
  "langName.mn": "Mongolia",
  "langName.mr": "Marathi",
  "langName.nb": "Norwegia Bokmål",
  "langName.nl": "Belanda",
  "langName.nl-be": "Belanda (Belgia)",
  "langName.nn": "Norwegia Nynorsk",
  "langName.pl": "Polandia",
  "langName.ps": "Pashto",
  "langName.pt": "Portugis, Internasional",
  "langName.pt-br": "Portugis, Brasil",
  "langName.qu": "Quechua",
  "langName.ro": "Rumania",
  "langName.ru": "Rusia",
  "langName.sa": "Sanskerta",
  "langName.sk-sk": "Slovakia",
  "langName.sl": "Slovenia",
  "langName.sma": "Sami Selatan",
  "langName.sme": "Sami Utara",
  "langName.smj": "Sami Lule",
  "langName.sr": "Serbia",
  "langName.sv": "Swedia",
  "langName.sw": "Swahili",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tajik",
  "langName.th": "Thailand",
  "langName.tr": "Turki",
  "langName.ug": "Uyghur",
  "langName.uk": "Ukraina",
  "langName.ur": "Urdu",
  "langName.uz": "Uzbek",
  "langName.vi": "Vietnam",
  "langName.wo": "Wolof",
  "langName.yi": "Yiddish",
  "langName.yo": "Yoruba",
  "langName.yua": "Maya Yukatan",
  "langName.zh": "Cina",
  "langName.zh-cn": "Cina (Tiongkok)",
  "langName.zh-hk": "Cina (Hong Kong)",
  "langName.zh-tw": "Cina (Taiwan)",
  "langName.zh-hans": "Cina, Disederhanakan",
  "langName.zh-hant": "Cina, Tradisional",
  "langName.zu": "Zulu"
});