tinymce.addI18n('id', {
  "-Language Not Set-": "-Bahasa Tidak Diatur-",
  "Choose from list": "Pilih dari daftar",
  "Choose languages": "Pilih bahasa",
  "Choose up to six languages": "Pilih hingga enam bahasa",
  "Configure languages": "Konfigurasi bahasa",
  "Current language:": "Bahasa saat ini:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Masukkan kode bahasa yang valid tanpa spasi. Atau tekan batal.",
  "Enter manually": "Masukkan secara manual",
  "Enter new lang code (e.g., \"en-US\"):": "Masukkan kode bahasa baru (contoh, \"en-US\"):",
  "Indicate current language": "Tunjukkan bahasa saat ini",
  "Manually enter language {{number}}:": "Masukkan secara manual bahasa {{number}}:",
  "New Language:": "Bahasa Baru:",
  "None": "Tidak ada",
  "Other - Enter manually": "Lainnya - Masukkan secara manual",
  "Really remove all language markup from the document?": "Benar-benar hapus semua markup bahasa dari dokumen?",
  "Remove All lang markup": "Hapus semua markup bahasa",
  "Remove Language Markup": "Hapus Markup Bahasa",
  "Remove current lang value": "Hapus nilai bahasa saat ini",
  "Reveal lang markup": "Tampilkan markup bahasa",
  "Select language {{number}}:": "Pilih bahasa {{number}}:",
  "Select the document's default language.": "Pilih bahasa default dokumen.",
  "Set default document language": "Atur bahasa dokumen default",
  "Set text language": "Atur bahasa teks",
  "langName.af": "Afrikaans",
  "langName.af-za": "Afrikaans",
  "langName.ak": "Akan",
  "langName.am": "Amharik",
  "langName.ar": "Arab",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "Arab",
  "langName.az": "Azerbaijani",
  "langName.be": "Belarusia",
  "langName.bg": "Bulgaria",
  "langName.bg-bg": "Bulgaria",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengali",
  "langName.bo": "Tibet",
  "langName.bs": "Bosnia",
  "langName.ca": "Katalan",
  "langName.cop": "Koptik",
  "langName.cr": "Kree",
  "langName.cs": "Ceko",
  "langName.cu": "Bahasa Gereja Slavonia",
  "langName.cy": "Welsh",
  "langName.da": "Dansk",
  "langName.de": "Jerman",
  "langName.de-at": "",
  "langName.de-ch": "Jerman Tinggi (Swiss)",
  "langName.de-de": "Jerman",
  "langName.dv": "Divehi",
  "langName.el": "Yunani",
  "langName.en": "Inggris",
  "langName.en-au": "Inggris (Australia)",
  "langName.en-ca": "",
  "langName.en-gb": "Inggris (Britania)",
  "langName.en-ie": "Inggris (Irlandia)",
  "langName.en-in": "Inggris (India)",
  "langName.en-tt": "Inggris (Trinidad)",
  "langName.en-us": "Inggris",
  "langName.en-za": "Inggris (Afrika Selatan)",
  "langName.eo": "Esperanto",
  "langName.es": "Spanyol",
  "langName.es-ar": "Spanyol (Argentina)",
  "langName.es-cl": "Spanyol (Chili)",
  "langName.es-co": "Spanyol (Kolombia)",
  "langName.es-cr": "",
  "langName.es-es": "Spanyol (Eropa)",
  "langName.es-mx": "Spanyol (Meksiko)",
  "langName.es-pe": "Spanyol (Peru)",
  "langName.et": "Estonia",
  "langName.eu": "Basque",
  "langName.fa": "Persia",
  "langName.fa-af": "Persia Dari",
  "langName.fa-ir": "Persia",
  "langName.ff": "Fula",
  "langName.fi": "Suomi",
  "langName.fi-fi": "Suomi",
  "langName.fil": "Filipino",
  "langName.fr": "Prancis",
  "langName.fr-be": "",
  "langName.fr-ca": "Prancis (Kanada)",
  "langName.fr-ch": "",
  "langName.ga": "Irlandia",
  "langName.gl": "Galisia",
  "langName.grc": "Yunani Kuno",
  "langName.ha": "Hausa",
  "langName.he": "Ibrani",
  "langName.he-il": "Ibrani",
  "langName.hi": "Hindi",
  "langName.hr": "Kroasia",
  "langName.hr-hr": "Kroasia",
  "langName.ht": "Kreol Haiti",
  "langName.hu": "Hungaria",
  "langName.hu-hu": "Hungaria",
  "langName.hy": "Armenia",
  "langName.id": "Indonesia",
  "langName.ig": "Igbo",
  "langName.is": "Islandia",
  "langName.it": "Italia",
  "langName.it-it": "Italia",
  "langName.iu": "Inuktitut",
  "langName.ja": "Jepang",
  "langName.ja-jp": "Jepang",
  "langName.ka": "Georgia",
  "langName.kab": "Kabyle",
  "langName.kk": "Kazakh",
  "langName.km": "Khmer",
  "langName.kn": "Kannada",
  "langName.ko": "Korea",
  "langName.ko-kr": "Korea",
  "langName.la": "Latin",
  "langName.lkt": "Lakota",
  "langName.lo": "Lao",
  "langName.lt": "Lituania",
  "langName.lv": "Latvia",
  "langName.mi": "Maori",
  "langName.mn": "Mongolia",
  "langName.mr": "Marathi",
  "langName.ms": "Melayu",
  "langName.mt": "Malta",
  "langName.my": "Burma",
  "langName.nb": "Bokmål Norwegia",
  "langName.nb-no": "Bokmål Norwegia",
  "langName.ne": "Nepali",
  "langName.nl": "Belanda",
  "langName.nl-be": "Belanda (Belgia)",
  "langName.nn": "Nynorsk Norwegia",
  "langName.nv": "Navajo",
  "langName.ota": "Turki Osmani",
  "langName.pa": "Punjabi",
  "langName.peo": "Persia Kuno",
  "langName.pl": "Polski",
  "langName.ps": "Pashto",
  "langName.pt": "Portugis",
  "langName.pt-br": "Portugis",
  "langName.pt-pt": "Portugis (Eropa)",
  "langName.qu": "Quechua",
  "langName.ro": "Rumania",
  "langName.ru": "Rusia",
  "langName.rw": "Kinyarwanda",
  "langName.sa": "Sanskerta",
  "langName.se": "Sami Utara",
  "langName.si": "Sinhala",
  "langName.sk-sk": "Slovak",
  "langName.sl": "Slovenia",
  "langName.sl-si": "Slovenia",
  "langName.sma": "Sami Selatan",
  "langName.sme": "Sami Utara",
  "langName.smj": "Lule Sami",
  "langName.sn": "Shona",
  "langName.sr": "Serbia",
  "langName.sr-latn": "",
  "langName.sv": "Swedia",
  "langName.sv-se": "Swedia",
  "langName.sw": "Swahili",
  "langName.sw-ke": "Swahili",
  "langName.sw-tz": "Swahili",
  "langName.syc": "Suriah Klasik",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tajik",
  "langName.th": "Thai",
  "langName.th-th": "Thai",
  "langName.tk": "Turkmen",
  "langName.tl": "Tagalog",
  "langName.tr": "Turki",
  "langName.tr-tr": "Turki",
  "langName.tt": "Tatar",
  "langName.ug": "Uyghur",
  "langName.uk": "Ukraina",
  "langName.ur": "Urdu",
  "langName.uz": "Uzbek",
  "langName.vi": "Vietnam",
  "langName.wo": "Wolof",
  "langName.xh": "Xhosa",
  "langName.yi": "Yiddish",
  "langName.yo": "Yoruba",
  "langName.yua": "Maya Yukatan",
  "langName.zh": "Tionghoa",
  "langName.zh-cn": "Cina (Tiongkok)",
  "langName.zh-hans": "Cina, Disederhanakan",
  "langName.zh-hant": "Cina, Tradisional",
  "langName.zh-hk": "Cina (Hong Kong)",
  "langName.zh-sg": "",
  "langName.zh-tw": "Cina (Taiwan)",
  "langName.zu": "Zulu",
  "langName.zu-za": "Zulu"
});