tinymce.addI18n('id', {
  "-Language Not Set-": "-Bahasa Tidak Diatur-",
  "Choose from list": "Pilih dari daftar",
  "Choose languages": "Pilih bahasa",
  "Choose up to six languages": "Pilih hingga enam bahasa",
  "Configure languages": "Konfigurasi bahasa",
  "Current language:": "Bahasa saat ini:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Masukkan kode bahasa yang valid tanpa spasi. Atau tekan batal.",
  "Enter manually": "Masukkan secara manual",
  "Enter new lang code (e.g., \"en-US\"):": "Masukkan kode bahasa baru (contoh, \"id-ID\"):",
  "Indicate current language": "Tunjukkan bahasa saat ini",
  "Manually enter language {{number}}:": "Masukkan secara manual bahasa {{number}}:",
  "New Language:": "Bahasa Baru:",
  "None": "Tidak ada",
  "Other - Enter manually": "Lainnya - Masukkan secara manual",
  "Really remove all language markup from the document?": "Benar-benar hapus semua markup bahasa dari dokumen?",
  "Remove All lang markup": "Hapus semua markup bahasa",
  "Remove Language Markup": "Hapus Markup Bahasa",
  "Remove current lang value": "Hapus nilai bahasa saat ini",
  "Reveal lang markup": "Tampilkan markup bahasa",
  "Select language {{number}}:": "Pilih bahasa {{number}}:",
  "Select the document's default language.": "Pilih bahasa default dokumen.",
  "Set default document language": "Atur bahasa dokumen default",
  "Set text language": "Atur bahasa teks",
  "langName.af": "Afrikaans",
  "langName.af-za": "Afrikaans (Afrika Selatan)",
  "langName.ak": "Akan",
  "langName.am": "Amharik",
  "langName.ar": "Arab",
  "langName.ar-eg": "Arab (Mesir)",
  "langName.ar-ma": "Arab (Maroko)",
  "langName.ar-sa": "Arab (Arab Saudi)",
  "langName.az": "Azerbaijan",
  "langName.be": "Belarus",
  "langName.bg": "Bulgaria",
  "langName.bg-bg": "Bulgaria (Bulgaria)",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengali",
  "langName.bo": "Tibet",
  "langName.bs": "Bosnia",
  "langName.ca": "Katalan",
  "langName.cop": "Koptik",
  "langName.cr": "Kree",
  "langName.cs": "Ceko",
  "langName.cu": "Slavonia Gereja",
  "langName.cy": "Welsh",
  "langName.da": "Denmark",
  "langName.de": "Jerman",
  "langName.de-at": "Jerman (Austria)",
  "langName.de-ch": "Jerman (Swiss)",
  "langName.de-de": "Jerman (Jerman)",
  "langName.dv": "Divehi",
  "langName.el": "Yunani",
  "langName.en": "Inggris",
  "langName.en-au": "Inggris (Australia)",
  "langName.en-ca": "Inggris (Kanada)",
  "langName.en-gb": "Inggris (Britania Raya)",
  "langName.en-ie": "Inggris (Irlandia)",
  "langName.en-in": "Inggris (India)",
  "langName.en-tt": "Inggris (Trinidad)",
  "langName.en-us": "Inggris (Amerika Serikat)",
  "langName.en-za": "Inggris (Afrika Selatan)",
  "langName.eo": "Esperanto",
  "langName.es": "Spanyol",
  "langName.es-ar": "Spanyol (Argentina)",
  "langName.es-cl": "Spanyol (Chili)",
  "langName.es-co": "Spanyol (Kolombia)",
  "langName.es-cr": "Spanyol (Kosta Rika)",
  "langName.es-es": "Spanyol (Spanyol)",
  "langName.es-mx": "Spanyol (Meksiko)",
  "langName.es-pe": "Spanyol (Peru)",
  "langName.et": "Estonia",
  "langName.eu": "Basque",
  "langName.fa": "Persia",
  "langName.fa-af": "Dari",
  "langName.fa-ir": "Persia (Iran)",
  "langName.ff": "Fula",
  "langName.fi": "Finlandia",
  "langName.fi-fi": "Finlandia (Finlandia)",
  "langName.fil": "Filipino",
  "langName.fr": "Prancis",
  "langName.fr-be": "Prancis (Belgia)",
  "langName.fr-ca": "Prancis (Kanada)",
  "langName.fr-ch": "Prancis (Swiss)",
  "langName.ga": "Irlandia",
  "langName.gl": "Galisia",
  "langName.grc": "Yunani (Kuno)",
  "langName.ha": "Hausa",
  "langName.he": "Ibrani",
  "langName.he-il": "Ibrani (Israel)",
  "langName.hi": "Hindi",
  "langName.hr": "Kroasia",
  "langName.hr-hr": "Kroasia (Kroasia)",
  "langName.ht": "Kreol Haiti",
  "langName.hu": "Hungaria",
  "langName.hu-hu": "Hungaria (Hungaria)",
  "langName.hy": "Armenia",
  "langName.id": "Indonesia",
  "langName.ig": "Igbo",
  "langName.is": "Islandia",
  "langName.it": "Italia",
  "langName.it-it": "Italia (Italia)",
  "langName.iu": "Inuktitut",
  "langName.ja": "Jepang",
  "langName.ja-jp": "Jepang (Jepang)",
  "langName.ka": "Georgia",
  "langName.kab": "Kabyle",
  "langName.kk": "Kazakh",
  "langName.km": "Khmer",
  "langName.kn": "Kannada",
  "langName.ko": "Korea",
  "langName.ko-kr": "Korea (Korea)",
  "langName.la": "Latin",
  "langName.lkt": "Lakota",
  "langName.lo": "Lao",
  "langName.lt": "Lithuania",
  "langName.lv": "Latvia",
  "langName.mi": "Māori",
  "langName.mn": "Mongolia",
  "langName.mr": "Marathi",
  "langName.ms": "Melayu",
  "langName.mt": "Malta",
  "langName.my": "Burma",
  "langName.nb": "Norwegia (Bokmål)",
  "langName.nb-no": "Norwegia (Bokmål, Norwegia)",
  "langName.ne": "Nepali",
  "langName.nl": "Belanda",
  "langName.nl-be": "Flemish",
  "langName.nn": "Norwegia (Nynorsk)",
  "langName.nv": "Navajo",
  "langName.ota": "Turki (Ottoman)",
  "langName.pa": "Punjabi",
  "langName.peo": "Persia (Kuno)",
  "langName.pl": "Polandia",
  "langName.ps": "Pashto",
  "langName.pt": "Portugis",
  "langName.pt-br": "Portugis (Brasil)",
  "langName.pt-pt": "Portugis (Portugal)",
  "langName.qu": "Quechua",
  "langName.ro": "Romania",
  "langName.ru": "Rusia",
  "langName.rw": "Kinyarwanda",
  "langName.sa": "Sanskerta",
  "langName.se": "Sami (Utara)",
  "langName.si": "Sinhala",
  "langName.sk": "Slovak",
  "langName.sk-sk": "Slovak (Slovakia)",
  "langName.sl": "Slovenia",
  "langName.sl-si": "Slovenia (Slovenia)",
  "langName.sma": "Sami (Selatan)",
  "langName.sme": "Sami (Utara)",
  "langName.smj": "Sami (Lule)",
  "langName.sn": "Shona",
  "langName.sr": "Serbia",
  "langName.sr-latn": "Serbia (Latin)",
  "langName.sv": "Swedia",
  "langName.sv-se": "Swedia (Swedia)",
  "langName.sw": "Swahili",
  "langName.sw-ke": "Swahili (Kenya)",
  "langName.sw-tz": "Swahili (Tanzania)",
  "langName.syc": "Suriah (Klasik)",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tajik",
  "langName.th": "Thai",
  "langName.th-th": "Thai (Thailand)",
  "langName.tk": "Turkmen",
  "langName.tl": "Tagalog",
  "langName.tr": "Turki",
  "langName.tr-tr": "Turki (Turki)",
  "langName.tt": "Tatar",
  "langName.ug": "Uyghur",
  "langName.uk": "Ukraina",
  "langName.ur": "Urdu",
  "langName.uz": "Uzbek",
  "langName.vi": "Vietnam",
  "langName.wo": "Wolof",
  "langName.xh": "Xhosa",
  "langName.yi": "Yiddish",
  "langName.yo": "Yoruba",
  "langName.yua": "Maya (Yucatec)",
  "langName.zh": "Tionghoa",
  "langName.zh-cn": "Tionghoa (Sederhana)",
  "langName.zh-hans": "Tionghoa (Sederhana)",
  "langName.zh-hant": "Tionghoa (Tradisional)",
  "langName.zh-hk": "Tionghoa (Hong Kong)",
  "langName.zh-sg": "Tionghoa (Singapura)",
  "langName.zh-tw": "Tionghoa (Taiwan)",
  "langName.zu": "Zulu",
  "langName.zu-za": "Zulu (Afrika Selatan)"
});