tinymce.addI18n("is", {
  "Current language:": "Núverandi tungumál:",
  "Set text language": "Stilla tungumál texta",
  "-Language Not Set-": "-Tungumál ekki stillt-",
  "Choose languages": "Veldu tungumál",
  "Remove Language Markup": "Fjarlægja tungumálamerkingar",
  "Remove current lang value": "Fjarlægja núverandi tungumálagildi",
  "Remove All lang markup": "Fjarlægja allar tungumálamerkingar",
  "Configure languages": "Stilla tungumál",
  "Set default document language": "Stilla sjálfgefið tungumál skjals",
  "Reveal lang markup": "Sýna tungumálamerkingar",
  "Indicate current language": "Tilgreina núverandi tungumál",
  "Select the document's default language.": "Veldu sjálfgefið tungumál skjalsins.",
  "Choose from list": "Veldu af lista",
  "Enter manually": "Sláðu inn handvirkt",
  "None": "Ekkert",
  "Other - Enter manually": "Annað - Sláðu inn handvirkt",
  "New Language:": "Nýtt tungumál:",
  "Enter new lang code (e.g., \"en-US\"):": "Sláðu inn nýjan tungumálakóða (t.d., \"en-US\"):",
  "Choose up to six languages": "Veldu allt að sex tungumál",
  "Select language {{number}}:": "Veldu tungumál {{number}}:",
  "Manually enter language {{number}}:": "Sláðu handvirkt inn tungumál {{number}}:",
  "Really remove all language markup from the document?": "Viltu virkilega fjarlægja allar tungumálamerkingar úr skjalinu?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Sláðu inn gildann tungumálakóða án bila. Eða ýttu á hætta við.",
  "langName.af": "afríkanska",
  "langName.ak": "akan",
  "langName.ar": "arabíska",
  "langName.az": "aserbaídjanska",
  "langName.bg": "búlgarska",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengalska",
  "langName.bo": "tíbeska",
  "langName.bs": "bosníska",
  "langName.ca": "katalónska; valensíska",
  "langName.cs": "tékkneska",
  "langName.cu": "fornbúlgarska",
  "langName.da": "danska",
  "langName.de": "þýska",
  "langName.el": "gríska",
  "langName.en": "enska",
  "langName.en-au": "enska (Ástralía)",
  "langName.en-gb": "enska (Bretland)",
  "langName.en-in": "enska (Indland)",
  "langName.en-ie": "enska (Írland)",
  "langName.en-tt": "enska (Trínidad)",
  "langName.en-us": "enska (Bandaríkin)",
  "langName.en-za": "enska (Suður-Afríka)",
  "langName.es": "spænska",
  "langName.es-ar": "spænska (Argentína)",
  "langName.es-cl": "spænska (Síle)",
  "langName.es-co": "spænska (Kólumbía)",
  "langName.es-mx": "spænska (Mexíkó)",
  "langName.es-pe": "spænska (Perú)",
  "langName.et": "eistneska",
  "langName.eu": "baskneska",
  "langName.fa": "persneska",
  "langName.fi": "finnska",
  "langName.fr": "franska",
  "langName.fr-ca": "franska (Kanada)",
  "langName.gl": "galisíska (Spánn)",
  "langName.he": "hebreska",
  "langName.hi": "hindí",
  "langName.hr": "króatíska",
  "langName.hu": "ungverska",
  "langName.id": "indónesíska",
  "langName.it": "ítalska",
  "langName.ja": "japanska",
  "langName.kk": "kasakska",
  "langName.kn": "kannada",
  "langName.ko": "kóreska",
  "langName.la": "latína",
  "langName.lkt": "lakóta",
  "langName.mn": "mongólska",
  "langName.mr": "maratí",
  "langName.nb": "norska bokmál",
  "langName.nl": "hollenska",
  "langName.nl-be": "hollenska (Belgía)",
  "langName.nn": "norska nynorsk",
  "langName.pl": "pólska",
  "langName.ps": "pastó",
  "langName.pt": "portúgalska, alþjóðleg",
  "langName.pt-br": "portúgalska, Brasilía",
  "langName.qu": "kvesjúa",
  "langName.ro": "rúmenska",
  "langName.ru": "rússneska",
  "langName.sa": "sanskrít",
  "langName.sk-sk": "slóvakíska",
  "langName.sl": "slóvenska",
  "langName.sma": "suður-samíska",
  "langName.sme": "norður-samíska",
  "langName.smj": "lúle-samíska",
  "langName.sr": "serbneska",
  "langName.sv": "sænska",
  "langName.sw": "svahílí",
  "langName.ta": "tamílska",
  "langName.te": "telúgú",
  "langName.tg": "tadsíkska",
  "langName.th": "taílenska",
  "langName.tr": "tyrkneska",
  "langName.ug": "úígúrska",
  "langName.uk": "úkraínska",
  "langName.ur": "úrdú",
  "langName.uz": "úsbekska",
  "langName.vi": "víetnamska",
  "langName.wo": "volof",
  "langName.yi": "jiddíska",
  "langName.yo": "jórúba",
  "langName.yua": "júkatesk maja",
  "langName.zh": "kínverska",
  "langName.zh-cn": "kínverska (Kína)",
  "langName.zh-hk": "kínverska (Hong Kong)",
  "langName.zh-tw": "kínverska (Taívan)",
  "langName.zh-hans": "kínverska, einfölduð",
  "langName.zh-hant": "kínverska, hefðbundin",
  "langName.zu": "súlú"
});