tinymce.addI18n('is', {
  "-Language Not Set-": "-Tungumál ekki stillt-",
  "Choose from list": "Veldu af lista",
  "Choose languages": "Veldu tungumál",
  "Choose up to six languages": "Veldu allt að sex tungumál",
  "Configure languages": "Stilla tungumál",
  "Current language:": "Núverandi tungumál:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Sláðu inn gildann tungumálakóða án bila. Eða ýttu á hætta við.",
  "Enter manually": "Sláðu inn handvirkt",
  "Enter new lang code (e.g., \"en-US\"):": "Sláðu inn nýjan tungumálakóða (t.d., \"en-US\"):",
  "Indicate current language": "Tilgreina núverandi tungumál",
  "Manually enter language {{number}}:": "Sláðu handvirkt inn tungumál {{number}}:",
  "New Language:": "Nýtt tungumál:",
  "None": "Ekkert",
  "Other - Enter manually": "Annað - Sláðu inn handvirkt",
  "Really remove all language markup from the document?": "Viltu virkilega fjarlægja allar tungumálamerkingar úr skjalinu?",
  "Remove All lang markup": "Fjarlægja allar tungumálamerkingar",
  "Remove Language Markup": "Fjarlægja tungumálamerkingar",
  "Remove current lang value": "Fjarlægja núverandi tungumálagildi",
  "Reveal lang markup": "Sýna tungumálamerkingar",
  "Select language {{number}}:": "Veldu tungumál {{number}}:",
  "Select the document's default language.": "Veldu sjálfgefið tungumál skjalsins.",
  "Set default document language": "Stilla sjálfgefið tungumál skjals",
  "Set text language": "Stilla tungumál texta",
  "langName.af": "afríkanska",
  "langName.af-za": "afríkanska",
  "langName.ak": "akan",
  "langName.am": "amharíska",
  "langName.ar": "arabíska",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "arabíska",
  "langName.az": "aserska",
  "langName.be": "hvítrússneska",
  "langName.bg": "búlgarska",
  "langName.bg-bg": "búlgarska",
  "langName.bho": "bojpúrí",
  "langName.bm": "bambara",
  "langName.bn": "bengalska",
  "langName.bo": "tíbeska",
  "langName.bs": "bosníska",
  "langName.ca": "katalónska",
  "langName.cop": "koptíska",
  "langName.cr": "krí",
  "langName.cs": "tékkneska",
  "langName.cu": "kirkjuslavneska",
  "langName.cy": "velska",
  "langName.da": "danska",
  "langName.de": "þýska",
  "langName.de-at": "austurrísk þýska",
  "langName.de-ch": "svissnesk háþýska",
  "langName.de-de": "þýska",
  "langName.dv": "dívehí",
  "langName.el": "gríska",
  "langName.en": "enska",
  "langName.en-au": "áströlsk enska",
  "langName.en-ca": "kanadísk enska",
  "langName.en-gb": "bresk enska",
  "langName.en-ie": "enska (Írland)",
  "langName.en-in": "enska (Indland)",
  "langName.en-tt": "enska (Trínidad)",
  "langName.en-us": "bandarísk enska",
  "langName.en-za": "enska (Suður-Afríka)",
  "langName.eo": "esperantó",
  "langName.es": "spænska",
  "langName.es-ar": "spænska (Argentína)",
  "langName.es-cl": "spænska (Síle)",
  "langName.es-co": "spænska (Kólumbía)",
  "langName.es-cr": "",
  "langName.es-es": "evrópsk spænska",
  "langName.es-mx": "mexíkósk spænska",
  "langName.es-pe": "spænska (Perú)",
  "langName.et": "eistneska",
  "langName.eu": "baskneska",
  "langName.fa": "persneska",
  "langName.fa-af": "darí",
  "langName.fa-ir": "persneska",
  "langName.ff": "fúla",
  "langName.fi": "finnska",
  "langName.fi-fi": "finnska",
  "langName.fil": "filippseyska",
  "langName.fr": "franska",
  "langName.fr-be": "",
  "langName.fr-ca": "kanadísk franska",
  "langName.fr-ch": "svissnesk franska",
  "langName.ga": "írska",
  "langName.gl": "galisíska",
  "langName.grc": "forngríska",
  "langName.ha": "hása",
  "langName.he": "hebreska",
  "langName.he-il": "hebreska",
  "langName.hi": "hindí",
  "langName.hr": "króatíska",
  "langName.hr-hr": "króatíska",
  "langName.ht": "haítíska",
  "langName.hu": "ungverska",
  "langName.hu-hu": "ungverska",
  "langName.hy": "armenska",
  "langName.id": "indónesíska",
  "langName.ig": "ígbó",
  "langName.is": "íslenska",
  "langName.it": "ítalska",
  "langName.it-it": "ítalska",
  "langName.iu": "inúktitút",
  "langName.ja": "japanska",
  "langName.ja-jp": "japanska",
  "langName.ka": "georgíska",
  "langName.kab": "kabíle",
  "langName.kk": "kasakska",
  "langName.km": "kmer",
  "langName.kn": "kannada",
  "langName.ko": "kóreska",
  "langName.ko-kr": "kóreska",
  "langName.la": "latína",
  "langName.lkt": "lakóta",
  "langName.lo": "laó",
  "langName.lt": "litháíska",
  "langName.lv": "lettneska",
  "langName.mi": "maorí",
  "langName.mn": "mongólska",
  "langName.mr": "maratí",
  "langName.ms": "malaíska",
  "langName.mt": "maltneska",
  "langName.my": "búrmneska",
  "langName.nb": "norskt bókmál",
  "langName.nb-no": "norskt bókmál",
  "langName.ne": "nepalska",
  "langName.nl": "hollenska",
  "langName.nl-be": "flæmska",
  "langName.nn": "nýnorska",
  "langName.nv": "navahó",
  "langName.ota": "tyrkneska, ottóman",
  "langName.pa": "púnjabí",
  "langName.peo": "fornpersneska",
  "langName.pl": "pólska",
  "langName.ps": "pastú",
  "langName.pt": "portúgalska",
  "langName.pt-br": "brasílísk portúgalska",
  "langName.pt-pt": "evrópsk portúgalska",
  "langName.qu": "kvesjúa",
  "langName.ro": "rúmenska",
  "langName.ru": "rússneska",
  "langName.rw": "kínjarvanda",
  "langName.sa": "sanskrít",
  "langName.se": "norðursamíska",
  "langName.si": "singalíska",
  "langName.sk-sk": "slóvakíska",
  "langName.sl": "slóvenska",
  "langName.sl-si": "slóvenska",
  "langName.sma": "suðursamíska",
  "langName.sme": "norður-samíska",
  "langName.smj": "lúlesamíska",
  "langName.sn": "shona",
  "langName.sr": "serbneska",
  "langName.sr-latn": "",
  "langName.sv": "sænska",
  "langName.sv-se": "sænska",
  "langName.sw": "svahílí",
  "langName.sw-ke": "svahílí",
  "langName.sw-tz": "svahílí",
  "langName.syc": "klassísk sýrlenska",
  "langName.ta": "tamílska",
  "langName.te": "telúgú",
  "langName.tg": "tadsjikska",
  "langName.th": "taílenska",
  "langName.th-th": "taílenska",
  "langName.tk": "túrkmenska",
  "langName.tl": "tagalog",
  "langName.tr": "tyrkneska",
  "langName.tr-tr": "tyrkneska",
  "langName.tt": "tatarska",
  "langName.ug": "úígúr",
  "langName.uk": "úkraínska",
  "langName.ur": "úrdú",
  "langName.uz": "úsbekska",
  "langName.vi": "víetnamska",
  "langName.wo": "volof",
  "langName.xh": "sósa",
  "langName.yi": "jiddíska",
  "langName.yo": "jórúba",
  "langName.yua": "júkatesk maja",
  "langName.zh": "kínverska",
  "langName.zh-cn": "kínverska (einfölduð)",
  "langName.zh-hans": "kínverska (einfölduð)",
  "langName.zh-hant": "kínverska (hefðbundin)",
  "langName.zh-hk": "kínverska (Hong Kong)",
  "langName.zh-sg": "",
  "langName.zh-tw": "kínverska (hefðbundin)",
  "langName.zu": "súlú",
  "langName.zu-za": "súlú"
});