tinymce.addI18n('is', {
  "-Language Not Set-": "-Tungumál ekki stillt-",
  "Choose from list": "Veldu af lista",
  "Choose languages": "Veldu tungumál",
  "Choose up to six languages": "Veldu allt að sex tungumál",
  "Configure languages": "Stilla tungumál",
  "Current language:": "Núverandi tungumál:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Sláðu inn gildann tungumálakóða án bila. Eða ýttu á hætta við.",
  "Enter manually": "Sláðu inn handvirkt",
  "Enter new lang code (e.g., \"en-US\"):": "Sláðu inn nýjan tungumálakóða (t.d., \"en-US\"):",
  "Indicate current language": "Tilgreina núverandi tungumál",
  "Manually enter language {{number}}:": "Sláðu handvirkt inn tungumál {{number}}:",
  "New Language:": "Nýtt tungumál:",
  "None": "Ekkert",
  "Other - Enter manually": "Annað - Sláðu inn handvirkt",
  "Really remove all language markup from the document?": "Viltu virkilega fjarlægja allar tungumálamerkingar úr skjalinu?",
  "Remove All lang markup": "Fjarlægja allar tungumálamerkingar",
  "Remove Language Markup": "Fjarlægja tungumálamerkingar",
  "Remove current lang value": "Fjarlægja núverandi tungumálagildi",
  "Reveal lang markup": "Sýna tungumálamerkingar",
  "Select language {{number}}:": "Veldu tungumál {{number}}:",
  "Select the document's default language.": "Veldu sjálfgefið tungumál skjalsins.",
  "Set default document language": "Stilla sjálfgefið tungumál skjals",
  "Set text language": "Stilla tungumál texta",
  "langName.af": "afríkanska",
  "langName.af-za": "afríkanska (Suður-Afríka)",
  "langName.ak": "akan",
  "langName.am": "amharíska",
  "langName.ar": "arabíska",
  "langName.ar-eg": "arabíska (Egyptaland)",
  "langName.ar-ma": "arabíska (Marokkó)",
  "langName.ar-sa": "arabíska (Sádi-Arabía)",
  "langName.az": "aserska",
  "langName.be": "hvítrússneska",
  "langName.bg": "búlgarska",
  "langName.bg-bg": "búlgarska (Búlgaría)",
  "langName.bho": "bojpúrí",
  "langName.bm": "bambara",
  "langName.bn": "bengalska",
  "langName.bo": "tíbeska",
  "langName.bs": "bosníska",
  "langName.ca": "katalónska",
  "langName.cop": "koptíska",
  "langName.cr": "krí",
  "langName.cs": "tékkneska",
  "langName.cu": "kirkjuslavneska",
  "langName.cy": "velska",
  "langName.da": "danska",
  "langName.de": "þýska",
  "langName.de-at": "þýska (Austurríki)",
  "langName.de-ch": "þýska (Sviss)",
  "langName.de-de": "þýska (Þýskaland)",
  "langName.dv": "dívehí",
  "langName.el": "gríska",
  "langName.en": "enska",
  "langName.en-au": "enska (Ástralía)",
  "langName.en-ca": "enska (Kanada)",
  "langName.en-gb": "enska (Bretland)",
  "langName.en-ie": "enska (Írland)",
  "langName.en-in": "enska (Indland)",
  "langName.en-tt": "enska (Trínidad)",
  "langName.en-us": "enska (Bandaríkin)",
  "langName.en-za": "enska (Suður-Afríka)",
  "langName.eo": "esperantó",
  "langName.es": "spænska",
  "langName.es-ar": "spænska (Argentína)",
  "langName.es-cl": "spænska (Síle)",
  "langName.es-co": "spænska (Kólumbía)",
  "langName.es-cr": "spænska (Kosta Ríka)",
  "langName.es-es": "spænska (Spánn)",
  "langName.es-mx": "spænska (Mexíkó)",
  "langName.es-pe": "spænska (Perú)",
  "langName.et": "eistneska",
  "langName.eu": "baskneska",
  "langName.fa": "persneska",
  "langName.fa-af": "darí",
  "langName.fa-ir": "persneska (Íran)",
  "langName.ff": "fúla",
  "langName.fi": "finnska",
  "langName.fi-fi": "finnska (Finnland)",
  "langName.fil": "filippseyska",
  "langName.fr": "franska",
  "langName.fr-be": "franska (Belgía)",
  "langName.fr-ca": "franska (Kanada)",
  "langName.fr-ch": "franska (Sviss)",
  "langName.ga": "írska",
  "langName.gl": "galisíska",
  "langName.grc": "gríska (forn)",
  "langName.ha": "hása",
  "langName.he": "hebreska",
  "langName.he-il": "hebreska (Ísrael)",
  "langName.hi": "hindí",
  "langName.hr": "króatíska",
  "langName.hr-hr": "króatíska (Króatía)",
  "langName.ht": "haítíska",
  "langName.hu": "ungverska",
  "langName.hu-hu": "ungverska (Ungverjaland)",
  "langName.hy": "armenska",
  "langName.id": "indónesíska",
  "langName.ig": "ígbó",
  "langName.is": "íslenska",
  "langName.it": "ítalska",
  "langName.it-it": "ítalska (Ítalía)",
  "langName.iu": "inúktitút",
  "langName.ja": "japanska",
  "langName.ja-jp": "japanska (Japan)",
  "langName.ka": "georgíska",
  "langName.kab": "kabíle",
  "langName.kk": "kasakska",
  "langName.km": "kmer",
  "langName.kn": "kannada",
  "langName.ko": "kóreska",
  "langName.ko-kr": "kóreska (Kórea)",
  "langName.la": "latína",
  "langName.lkt": "lakóta",
  "langName.lo": "laó",
  "langName.lt": "litháíska",
  "langName.lv": "lettneska",
  "langName.mi": "maorí",
  "langName.mn": "mongólska",
  "langName.mr": "maratí",
  "langName.ms": "malaíska",
  "langName.mt": "maltneska",
  "langName.my": "búrmneska",
  "langName.nb": "norska (bókmál)",
  "langName.nb-no": "norska (bókmál, Noregur)",
  "langName.ne": "nepalska",
  "langName.nl": "hollenska",
  "langName.nl-be": "flæmska",
  "langName.nn": "norska (nýnorska)",
  "langName.nv": "navahó",
  "langName.ota": "tyrkneska (ottóman)",
  "langName.pa": "púnjabí",
  "langName.peo": "persneska (forn)",
  "langName.pl": "pólska",
  "langName.ps": "pastú",
  "langName.pt": "portúgalska",
  "langName.pt-br": "portúgalska (Brasilía)",
  "langName.pt-pt": "portúgalska (Portúgal)",
  "langName.qu": "kvesjúa",
  "langName.ro": "rúmenska",
  "langName.ru": "rússneska",
  "langName.rw": "kínjarvanda",
  "langName.sa": "sanskrít",
  "langName.se": "samíska (norður)",
  "langName.si": "singalíska",
  "langName.sk": "slóvakíska",
  "langName.sk-sk": "slóvakíska (Slóvakía)",
  "langName.sl": "slóvenska",
  "langName.sl-si": "slóvenska (Slóvenía)",
  "langName.sma": "samíska (suður)",
  "langName.sme": "samíska (norður)",
  "langName.smj": "samíska (lúle)",
  "langName.sn": "shona",
  "langName.sr": "serbneska",
  "langName.sr-latn": "serbneska (latnesk)",
  "langName.sv": "sænska",
  "langName.sv-se": "sænska (Svíþjóð)",
  "langName.sw": "svahílí",
  "langName.sw-ke": "svahílí (Kenía)",
  "langName.sw-tz": "svahílí (Tansanía)",
  "langName.syc": "sýrlenska (klassísk)",
  "langName.ta": "tamílska",
  "langName.te": "telúgú",
  "langName.tg": "tadsjikska",
  "langName.th": "taílenska",
  "langName.th-th": "taílenska (Taíland)",
  "langName.tk": "túrkmenska",
  "langName.tl": "tagalog",
  "langName.tr": "tyrkneska",
  "langName.tr-tr": "tyrkneska (Tyrkland)",
  "langName.tt": "tatarska",
  "langName.ug": "úígúr",
  "langName.uk": "úkraínska",
  "langName.ur": "úrdú",
  "langName.uz": "úsbekska",
  "langName.vi": "víetnamska",
  "langName.wo": "wolof",
  "langName.xh": "sósa",
  "langName.yi": "jiddíska",
  "langName.yo": "jórúba",
  "langName.yua": "majamál (júkatesk)",
  "langName.zh": "kínverska",
  "langName.zh-cn": "kínverska (einfölduð)",
  "langName.zh-hans": "kínverska (einfölduð)",
  "langName.zh-hant": "kínverska (hefðbundin)",
  "langName.zh-hk": "kínverska (Hong Kong)",
  "langName.zh-sg": "kínverska (Singapúr)",
  "langName.zh-tw": "kínverska (hefðbundin)",
  "langName.zu": "súlú",
  "langName.zu-za": "súlú (Suður-Afríka)"
});