tinymce.addI18n('it', {
  "Current language:": "Lingua corrente:",
  "Set text language": "Imposta lingua del testo",
  "-Language Not Set-": "-Lingua non impostata-",
  "Choose languages": "Scegli lingue",
  "Remove Language Markup": "Rimuovi markup lingua",
  "Remove current lang value": "Rimuovi valore lingua corrente",
  "Remove All lang markup": "Rimuovi tutto il markup lingua",
  "Configure languages": "Configura lingue",
  "Set default document language": "Imposta lingua predefinita del documento",
  "Reveal lang markup": "Rivela markup lingua",
  "Indicate current language": "Indica lingua corrente",
  "Select the document's default language.": "Seleziona la lingua predefinita del documento.",
  "Choose from list": "Scegli dalla lista",
  "Enter manually": "Inserisci manualmente",
  "None": "Nessuno",
  "Other - Enter manually": "Altro - Inserisci manualmente",
  "New Language:": "Nuova lingua:",
  "Enter new lang code (e.g., \"en-US\"):": "Inserisci nuovo codice lingua (es. \"en-US\"):",
  "Choose up to six languages": "Scegli fino a sei lingue",
  "Select language {{number}}:": "Seleziona lingua {{number}}:",
  "Manually enter language {{number}}:": "Inserisci manualmente lingua {{number}}:",
  "Really remove all language markup from the document?": "Rimuovere davvero tutto il markup lingua dal documento?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Inserisci un codice lingua valido senza spazi. Oppure premi annulla.",
  "langName.af": "Afrikaans",
  "langName.ak": "Akan",
  "langName.ar": "Arabo",
  "langName.az": "Azero",
  "langName.bg": "Bulgaro",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengalese",
  "langName.bo": "Tibetano",
  "langName.bs": "Bosniaco",
  "langName.ca": "Catalano; Valenciano",
  "langName.cs": "Ceco",
  "langName.cu": "Bulgaro antico",
  "langName.da": "Danese",
  "langName.de": "Tedesco",
  "langName.el": "Greco",
  "langName.en": "Inglese",
  "langName.en-au": "Inglese (Australia)",
  "langName.en-gb": "Inglese (Regno Unito)",
  "langName.en-in": "Inglese (India)",
  "langName.en-ie": "Inglese (Irlanda)",
  "langName.en-tt": "Inglese (Trinidad)",
  "langName.en-us": "Inglese (Stati Uniti)",
  "langName.en-za": "Inglese (Sudafrica)",
  "langName.es": "Spagnolo",
  "langName.es-ar": "Spagnolo (Argentina)",
  "langName.es-cl": "Spagnolo (Cile)",
  "langName.es-co": "Spagnolo (Colombia)",
  "langName.es-mx": "Spagnolo (Messico)",
  "langName.es-pe": "Spagnolo (Perù)",
  "langName.et": "Estone",
  "langName.eu": "Basco",
  "langName.fa": "Persiano",
  "langName.fi": "Finlandese",
  "langName.fr": "Francese",
  "langName.fr-ca": "Francese (Canada)",
  "langName.gl": "Galiziano (Spagna)",
  "langName.he": "Ebraico",
  "langName.hi": "Hindi",
  "langName.hr": "Croato",
  "langName.hu": "Ungherese",
  "langName.id": "Indonesiano",
  "langName.it": "Italiano",
  "langName.ja": "Giapponese",
  "langName.kk": "Kazako",
  "langName.kn": "Kannada",
  "langName.ko": "Coreano",
  "langName.la": "Latino",
  "langName.lkt": "Lakota",
  "langName.mn": "Mongolo",
  "langName.mr": "Marathi",
  "langName.nb": "Norvegese bokmål",
  "langName.nl": "Olandese",
  "langName.nl-be": "Olandese (Belgio)",
  "langName.nn": "Norvegese nynorsk",
  "langName.pl": "Polacco",
  "langName.ps": "Pashto",
  "langName.pt": "Portoghese internazionale",
  "langName.pt-br": "Portoghese brasiliano",
  "langName.qu": "Quechua",
  "langName.ro": "Rumeno",
  "langName.ru": "Russo",
  "langName.sa": "Sanscrito",
  "langName.sk-sk": "Slovacco",
  "langName.sl": "Sloveno",
  "langName.sma": "Sami meridionale",
  "langName.sme": "Sami settentrionale",
  "langName.smj": "Sami di Lule",
  "langName.sr": "Serbo",
  "langName.sv": "Svedese",
  "langName.sw": "Swahili",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tagico",
  "langName.th": "Tailandese",
  "langName.tr": "Turco",
  "langName.ug": "Uiguro",
  "langName.uk": "Ucraino",
  "langName.ur": "Urdu",
  "langName.uz": "Uzbeko",
  "langName.vi": "Vietnamita",
  "langName.wo": "Wolof",
  "langName.yi": "Yiddish",
  "langName.yo": "Yoruba",
  "langName.yua": "Maya yucateco",
  "langName.zh": "Cinese",
  "langName.zh-cn": "Cinese (Cina)",
  "langName.zh-hk": "Cinese (Hong Kong)",
  "langName.zh-tw": "Cinese (Taiwan)",
  "langName.zh-hans": "Cinese semplificato",
  "langName.zh-hant": "Cinese tradizionale",
  "langName.zu": "Zulu"
});