tinymce.addI18n('it', {
  "-Language Not Set-": "-Lingua non impostata-",
  "Choose from list": "Scegli dalla lista",
  "Choose languages": "Scegli lingue",
  "Choose up to six languages": "Scegli fino a sei lingue",
  "Configure languages": "Configura lingue",
  "Current language:": "Lingua corrente:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Inserisci un codice lingua valido senza spazi. Oppure premi annulla.",
  "Enter manually": "Inserisci manualmente",
  "Enter new lang code (e.g., \"en-US\"):": "Inserisci nuovo codice lingua (es. \"en-US\"):",
  "Indicate current language": "Indica lingua corrente",
  "Manually enter language {{number}}:": "Inserisci manualmente lingua {{number}}:",
  "New Language:": "Nuova lingua:",
  "None": "Nessuno",
  "Other - Enter manually": "Altro - Inserisci manualmente",
  "Really remove all language markup from the document?": "Rimuovere davvero tutto il markup lingua dal documento?",
  "Remove All lang markup": "Rimuovi tutto il markup lingua",
  "Remove Language Markup": "Rimuovi markup lingua",
  "Remove current lang value": "Rimuovi valore lingua corrente",
  "Reveal lang markup": "Rivela markup lingua",
  "Select language {{number}}:": "Seleziona lingua {{number}}:",
  "Select the document's default language.": "Seleziona la lingua predefinita del documento.",
  "Set default document language": "Imposta lingua predefinita del documento",
  "Set text language": "Imposta lingua del testo",
  "langName.af": "afrikaans",
  "langName.af-za": "afrikaans",
  "langName.ak": "akan",
  "langName.am": "amarico",
  "langName.ar": "arabo",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "arabo",
  "langName.az": "azerbaigiano",
  "langName.be": "bielorusso",
  "langName.bg": "bulgaro",
  "langName.bg-bg": "bulgaro",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengalese",
  "langName.bo": "tibetano",
  "langName.bs": "bosniaco",
  "langName.ca": "catalano",
  "langName.cop": "copto",
  "langName.cr": "cree",
  "langName.cs": "ceco",
  "langName.cu": "slavo ecclesiastico",
  "langName.cy": "gallese",
  "langName.da": "danese",
  "langName.de": "tedesco",
  "langName.de-at": "tedesco austriaco",
  "langName.de-ch": "alto tedesco svizzero",
  "langName.de-de": "tedesco",
  "langName.dv": "divehi",
  "langName.el": "greco",
  "langName.en": "inglese",
  "langName.en-au": "inglese australiano",
  "langName.en-ca": "inglese canadese",
  "langName.en-gb": "inglese britannico",
  "langName.en-ie": "Inglese (Irlanda)",
  "langName.en-in": "Inglese (India)",
  "langName.en-tt": "Inglese (Trinidad)",
  "langName.en-us": "inglese americano",
  "langName.en-za": "Inglese (Sudafrica)",
  "langName.eo": "esperanto",
  "langName.es": "spagnolo",
  "langName.es-ar": "Spagnolo (Argentina)",
  "langName.es-cl": "Spagnolo (Cile)",
  "langName.es-co": "Spagnolo (Colombia)",
  "langName.es-cr": "",
  "langName.es-es": "spagnolo europeo",
  "langName.es-mx": "spagnolo messicano",
  "langName.es-pe": "Spagnolo (Perù)",
  "langName.et": "estone",
  "langName.eu": "basco",
  "langName.fa": "persiano",
  "langName.fa-af": "dari",
  "langName.fa-ir": "persiano",
  "langName.ff": "fulah",
  "langName.fi": "finlandese",
  "langName.fi-fi": "finlandese",
  "langName.fil": "filippino",
  "langName.fr": "francese",
  "langName.fr-be": "",
  "langName.fr-ca": "francese canadese",
  "langName.fr-ch": "francese svizzero",
  "langName.ga": "irlandese",
  "langName.gl": "galiziano",
  "langName.grc": "greco antico",
  "langName.ha": "hausa",
  "langName.he": "ebraico",
  "langName.he-il": "ebraico",
  "langName.hi": "hindi",
  "langName.hr": "croato",
  "langName.hr-hr": "croato",
  "langName.ht": "creolo haitiano",
  "langName.hu": "ungherese",
  "langName.hu-hu": "ungherese",
  "langName.hy": "armeno",
  "langName.id": "indonesiano",
  "langName.ig": "igbo",
  "langName.is": "islandese",
  "langName.it": "italiano",
  "langName.it-it": "italiano",
  "langName.iu": "inuktitut",
  "langName.ja": "giapponese",
  "langName.ja-jp": "giapponese",
  "langName.ka": "georgiano",
  "langName.kab": "cabilo",
  "langName.kk": "kazako",
  "langName.km": "khmer",
  "langName.kn": "kannada",
  "langName.ko": "coreano",
  "langName.ko-kr": "coreano",
  "langName.la": "latino",
  "langName.lkt": "lakota",
  "langName.lo": "lao",
  "langName.lt": "lituano",
  "langName.lv": "lettone",
  "langName.mi": "maori",
  "langName.mn": "mongolo",
  "langName.mr": "marathi",
  "langName.ms": "malese",
  "langName.mt": "maltese",
  "langName.my": "birmano",
  "langName.nb": "norvegese bokmål",
  "langName.nb-no": "norvegese bokmål",
  "langName.ne": "nepalese",
  "langName.nl": "olandese",
  "langName.nl-be": "fiammingo",
  "langName.nn": "norvegese nynorsk",
  "langName.nv": "navajo",
  "langName.ota": "turco ottomano",
  "langName.pa": "punjabi",
  "langName.peo": "persiano antico",
  "langName.pl": "polacco",
  "langName.ps": "pashto",
  "langName.pt": "portoghese",
  "langName.pt-br": "portoghese brasiliano",
  "langName.pt-pt": "portoghese europeo",
  "langName.qu": "quechua",
  "langName.ro": "rumeno",
  "langName.ru": "russo",
  "langName.rw": "kinyarwanda",
  "langName.sa": "sanscrito",
  "langName.se": "sami del nord",
  "langName.si": "singalese",
  "langName.sk-sk": "slovacco",
  "langName.sl": "sloveno",
  "langName.sl-si": "sloveno",
  "langName.sma": "sami del sud",
  "langName.sme": "Sami settentrionale",
  "langName.smj": "sami di Lule",
  "langName.sn": "shona",
  "langName.sr": "serbo",
  "langName.sr-latn": "",
  "langName.sv": "svedese",
  "langName.sv-se": "svedese",
  "langName.sw": "swahili",
  "langName.sw-ke": "swahili",
  "langName.sw-tz": "swahili",
  "langName.syc": "siriaco classico",
  "langName.ta": "tamil",
  "langName.te": "telugu",
  "langName.tg": "tagico",
  "langName.th": "thailandese",
  "langName.th-th": "thailandese",
  "langName.tk": "turcomanno",
  "langName.tl": "tagalog",
  "langName.tr": "turco",
  "langName.tr-tr": "turco",
  "langName.tt": "tataro",
  "langName.ug": "uiguro",
  "langName.uk": "ucraino",
  "langName.ur": "urdu",
  "langName.uz": "uzbeco",
  "langName.vi": "vietnamita",
  "langName.wo": "wolof",
  "langName.xh": "xhosa",
  "langName.yi": "yiddish",
  "langName.yo": "yoruba",
  "langName.yua": "Maya yucateco",
  "langName.zh": "cinese",
  "langName.zh-cn": "cinese semplificato",
  "langName.zh-hans": "cinese semplificato",
  "langName.zh-hant": "cinese tradizionale",
  "langName.zh-hk": "Cinese (Hong Kong)",
  "langName.zh-sg": "",
  "langName.zh-tw": "cinese tradizionale",
  "langName.zu": "zulu",
  "langName.zu-za": "zulu"
});