tinymce.addI18n('ja', {
  "-Language Not Set-": "-言語が設定されていません-",
  "Choose from list": "リストから選択",
  "Choose languages": "言語を選択",
  "Choose up to six languages": "最大6つの言語を選択",
  "Configure languages": "言語を設定",
  "Current language:": "現在の言語：",
  "Enter a valid language code with no spaces. Or, press cancel.": "スペースなしの有効な言語コードを入力してください。またはキャンセルを押してください。",
  "Enter manually": "手動入力",
  "Enter new lang code (e.g., \"en-US\"):": "新しい言語コードを入力（例：\"en-US\"）：",
  "Indicate current language": "現在の言語を表示",
  "Manually enter language {{number}}:": "言語{{number}}を手動入力：",
  "New Language:": "新しい言語：",
  "None": "なし",
  "Other - Enter manually": "その他 - 手動入力",
  "Really remove all language markup from the document?": "文書からすべての言語マークアップを削除しますか？",
  "Remove All lang markup": "すべての言語マークアップを削除",
  "Remove Language Markup": "言語マークアップを削除",
  "Remove current lang value": "現在の言語値を削除",
  "Reveal lang markup": "言語マークアップを表示",
  "Select language {{number}}:": "言語{{number}}を選択：",
  "Select the document's default language.": "文書のデフォルト言語を選択してください。",
  "Set default document language": "デフォルトの文書言語を設定",
  "Set text language": "テキストの言語を設定",
  "Afrikaans": "アフリカーンス語",
  "Afrikaans": "アフリカーンス語（南アフリカ）",
  "Akan": "アカン語",
  "Amharic": "アムハラ語",
  "Arabic": "アラビア語",
  "Arabic (Egypt)": "アラビア語（エジプト）",
  "Arabic (Morocco)": "アラビア語（モロッコ）",
  "Arabic (Saudi Arabia)": "アラビア語（サウジアラビア）",
  "Azerbaijani": "アゼルバイジャン語",
  "Belarusian": "ベラルーシ語",
  "Bulgarian": "ブルガリア語",
  "Bulgarian (Bulgaria)": "ブルガリア語（ブルガリア）",
  "Bhojpuri": "ボージュプリー語",
  "Bambara": "バンバラ語",
  "Bangla": "ベンガル語",
  "Tibetan": "チベット語",
  "Bosnian": "ボスニア語",
  "Catalan": "カタロニア語",
  "Coptic": "コプト語",
  "Cree": "クリー語",
  "Czech": "チェコ語",
  "Church Slavic": "教会スラブ語",
  "Welsh": "ウェールズ語",
  "Danish": "デンマーク語",
  "German": "ドイツ語",
  "German (Austria)": "ドイツ語（オーストリア）",
  "German (Switzerland)": "ドイツ語（スイス）",
  "German (Germany)": "ドイツ語（ドイツ）",
  "Divehi": "ディベヒ語",
  "Greek": "ギリシャ語",
  "English": "英語",
  "English (Australia)": "英語（オーストラリア）",
  "English (Canada)": "英語（カナダ）",
  "English (United Kingdom)": "英語（イギリス）",
  "English (Ireland)": "英語（アイルランド）",
  "English (India)": "英語（インド）",
  "English (Trinidad)": "英語（トリニダード）",
  "English (United States)": "英語（アメリカ）",
  "English (South Africa)": "英語（南アフリカ）",
  "Esperanto": "エスペラント語",
  "Spanish": "スペイン語",
  "Spanish (Argentina)": "スペイン語（アルゼンチン）",
  "Spanish (Chile)": "スペイン語（チリ）",
  "Spanish (Colombia)": "スペイン語（コロンビア）",
  "Spanish (Costa Rica)": "スペイン語（コスタリカ）",
  "Spanish (Spain)": "スペイン語（スペイン）",
  "Spanish (Mexico)": "スペイン語（メキシコ）",
  "Spanish (Peru)": "スペイン語（ペルー）",
  "Estonian": "エストニア語",
  "Basque": "バスク語",
  "Persian": "ペルシア語",
  "Dari": "ダリー語",
  "Persian (Iran)": "ペルシア語（イラン）",
  "Fula": "フラ語",
  "Finnish": "フィンランド語",
  "Finnish (Finland)": "フィンランド語（フィンランド）",
  "Filipino": "フィリピノ語",
  "French": "フランス語",
  "French (Belgium)": "フランス語（ベルギー）",
  "French (Canada)": "フランス語（カナダ）",
  "French (Switzerland)": "フランス語（スイス）",
  "Irish": "アイルランド語",
  "Galician": "ガリシア語",
  "Greek (Ancient)": "古代ギリシャ語",
  "Hausa": "ハウサ語",
  "Hebrew": "ヘブライ語",
  "Hebrew (Israel)": "ヘブライ語（イスラエル）",
  "Hindi": "ヒンディー語",
  "Croatian": "クロアチア語",
  "Croatian (Croatia)": "クロアチア語（クロアチア）",
  "Haitian Creole": "ハイチ・クレオール語",
  "Hungarian": "ハンガリー語",
  "Hungarian (Hungary)": "ハンガリー語（ハンガリー）",
  "Armenian": "アルメニア語",
  "Indonesian": "インドネシア語",
  "Igbo": "イボ語",
  "Icelandic": "アイスランド語",
  "Italian": "イタリア語",
  "Italian (Italy)": "イタリア語（イタリア）",
  "Inuktitut": "イヌクティトット語",
  "Japanese": "日本語",
  "Japanese (Japan)": "日本語（日本）",
  "Georgian": "ジョージア語",
  "Kabyle": "カビル語",
  "Kazakh": "カザフ語",
  "Khmer": "クメール語",
  "Kannada": "カンナダ語",
  "Korean": "韓国語",
  "Korean (Korea)": "韓国語（韓国）",
  "Latin": "ラテン語",
  "Lakota": "ラコタ語",
  "Lao": "ラオ語",
  "Lithuanian": "リトアニア語",
  "Latvian": "ラトビア語",
  "Māori": "マオリ語",
  "Mongolian": "モンゴル語",
  "Marathi": "マラーティー語",
  "Malay": "マレー語",
  "Maltese": "マルタ語",
  "Burmese": "ミャンマー語",
  "Norwegian (Bokmål)": "ノルウェー語（ブークモール）",
  "Norwegian (Bokmål, Norway)": "ノルウェー語（ブークモール、ノルウェー）",
  "Nepali": "ネパール語",
  "Dutch": "オランダ語",
  "Flemish": "フラマン語",
  "Norwegian (Nynorsk)": "ノルウェー語（ニーノシュク）",
  "Navajo": "ナバホ語",
  "Turkish (Ottoman)": "オスマントルコ語",
  "Punjabi": "パンジャブ語",
  "Persian (Old)": "古代ペルシア語",
  "Polish": "ポーランド語",
  "Pashto": "パシュトゥー語",
  "Portuguese": "ポルトガル語",
  "Portuguese (Brazil)": "ポルトガル語（ブラジル）",
  "Portuguese (Portugal)": "ポルトガル語（ポルトガル）",
  "Quechua": "ケチュア語",
  "Romanian": "ルーマニア語",
  "Russian": "ロシア語",
  "Kinyarwanda": "キニアルワンダ語",
  "Sanskrit": "サンスクリット語",
  "Sami (Northern)": "北サーミ語",
  "Sinhala": "シンハラ語",
  "Slovak": "スロバキア語",
  "Slovak (Slovakia)": "スロバキア語（スロバキア）",
  "Slovenian": "スロベニア語",
  "Slovenian (Slovenia)": "スロベニア語（スロベニア）",
  "Sami (Southern)": "南サーミ語",
  "Sami (Northern)": "北サーミ語",
  "Sami (Lule)": "ルレ・サーミ語",
  "Shona": "ショナ語",
  "Serbian": "セルビア語",
  "Serbian (Latin)": "セルビア語（ラテン文字）",
  "Swedish": "スウェーデン語",
  "Swedish (Sweden)": "スウェーデン語（スウェーデン）",
  "Swahili": "スワヒリ語",
  "Swahili (Kenya)": "スワヒリ語（ケニア）",
  "Swahili (Tanzania)": "スワヒリ語（タンザニア）",
  "Syriac (Classical)": "古典シリア語",
  "Tamil": "タミル語",
  "Telugu": "テルグ語",
  "Tajik": "タジク語",
  "Thai": "タイ語",
  "Thai (Thailand)": "タイ語（タイ）",
  "Turkmen": "トルクメン語",
  "Tagalog": "タガログ語",
  "Turkish": "トルコ語",
  "Turkish (Turkey)": "トルコ語（トルコ）",
  "Tatar": "タタール語",
  "Uyghur": "ウイグル語",
  "Ukrainian": "ウクライナ語",
  "Urdu": "ウルドゥー語",
  "Uzbek": "ウズベク語",
  "Vietnamese": "ベトナム語",
  "Wolof": "ウォロフ語",
  "Xhosa": "コサ語",
  "Yiddish": "イディッシュ語",
  "Yoruba": "ヨルバ語",
  "Maya (Yucatec)": "ユカテコ・マヤ語",
  "Chinese": "中国語",
  "Chinese (Simplified)": "中国語（簡体字）",
  "Chinese (Simplified)": "中国語（簡体字）",
  "Chinese (Traditional)": "中国語（繁体字）",
  "Chinese (Hong Kong)": "中国語（香港）",
  "Chinese (Singapore)": "中国語（シンガポール）",
  "Chinese (Traditional)": "中国語（繁体字）",
  "Zulu": "ズールー語",
  "Zulu": "ズールー語（南アフリカ）"
});