tinymce.addI18n('ja', {
  "Current language:": "現在の言語：",
  "Set text language": "テキストの言語を設定",
  "-Language Not Set-": "-言語が設定されていません-",
  "Choose languages": "言語を選択",
  "Remove Language Markup": "言語マークアップを削除",
  "Remove current lang value": "現在の言語値を削除",
  "Remove All lang markup": "すべての言語マークアップを削除",
  "Configure languages": "言語を設定",
  "Set default document language": "デフォルトの文書言語を設定",
  "Reveal lang markup": "言語マークアップを表示",
  "Indicate current language": "現在の言語を表示",
  "Select the document's default language.": "文書のデフォルト言語を選択してください。",
  "Choose from list": "リストから選択",
  "Enter manually": "手動入力",
  "None": "なし",
  "Other - Enter manually": "その他 - 手動入力",
  "Current language:": "現在の言語：",
  "New Language:": "新しい言語：",
  'Enter new lang code (e.g., "en-US"):': '新しい言語コードを入力（例："en-US"）：',
  "Choose up to six languages": "最大6つの言語を選択",
  "Select language {{number}}:": "言語{{number}}を選択：",
  "Manually enter language {{number}}:": "言語{{number}}を手動入力：",
  "Really remove all language markup from the document?": "文書からすべての言語マークアップを削除しますか？",
  "Enter a valid language code with no spaces. Or, press cancel.": "スペースなしの有効な言語コードを入力してください。またはキャンセルを押してください。",
  "langName.af": 'アフリカーンス語',
  "langName.ak": 'アカン語',
  "langName.ar": 'アラビア語',
  "langName.az": 'アゼルバイジャン語',
  "langName.bg": 'ブルガリア語',
  "langName.bho": 'ボージプリー語',
  "langName.bm": 'バンバラ語',
  "langName.bn": 'ベンガル語',
  "langName.bo": 'チベット語',
  "langName.bs": 'ボスニア語',
  "langName.ca": 'カタルーニャ語・バレンシア語',
  "langName.cs": 'チェコ語',
  "langName.cu": '古代ブルガリア語',
  "langName.da": 'デンマーク語',
  "langName.de": 'ドイツ語',
  "langName.el": 'ギリシャ語',
  "langName.en": '英語',
  "langName.en-au": '英語（オーストラリア）',
  "langName.en-gb": '英語（イギリス）',
  "langName.en-in": '英語（インド）',
  "langName.en-ie": '英語（アイルランド）',
  "langName.en-tt": '英語（トリニダード）',
  "langName.en-us": '英語（アメリカ）',
  "langName.en-za": '英語（南アフリカ）',
  "langName.es": 'スペイン語',
  "langName.es-ar": 'スペイン語（アルゼンチン）',
  "langName.es-cl": 'スペイン語（チリ）',
  "langName.es-co": 'スペイン語（コロンビア）',
  "langName.es-mx": 'スペイン語（メキシコ）',
  "langName.es-pe": 'スペイン語（ペルー）',
  "langName.et": 'エストニア語',
  "langName.eu": 'バスク語',
  "langName.fa": 'ペルシア語',
  "langName.fi": 'フィンランド語',
  "langName.fr": 'フランス語',
  "langName.fr-ca": 'フランス語（カナダ）',
  "langName.gl": 'ガリシア語（スペイン）',
  "langName.he": 'ヘブライ語',
  "langName.hi": 'ヒンディー語',
  "langName.hr": 'クロアチア語',
  "langName.hu": 'ハンガリー語',
  "langName.id": 'インドネシア語',
  "langName.it": 'イタリア語',
  "langName.ja": '日本語',
  "langName.kk": 'カザフ語',
  "langName.kn": 'カンナダ語',
  "langName.ko": '韓国語',
  "langName.la": 'ラテン語',
  "langName.lkt": 'ラコタ語',
  "langName.mn": 'モンゴル語',
  "langName.mr": 'マラーティー語',
  "langName.nb": 'ノルウェー語（ブークモール）',
  "langName.nl": 'オランダ語',
  "langName.nl-be": 'オランダ語（ベルギー）',
  "langName.nn": 'ノルウェー語（ニーノシュク）',
  "langName.pl": 'ポーランド語',
  "langName.ps": 'パシュトー語',
  "langName.pt": 'ポルトガル語（国際）',
  "langName.pt-br": 'ポルトガル語（ブラジル）',
  "langName.qu": 'ケチュア語',
  "langName.ro": 'ルーマニア語',
  "langName.ru": 'ロシア語',
  "langName.sa": 'サンスクリット語',
  "langName.sk-sk": 'スロバキア語',
  "langName.sl": 'スロベニア語',
  "langName.sma": '南サーミ語',
  "langName.sme": '北サーミ語',
  "langName.smj": 'ルレサーミ語',
  "langName.sr": 'セルビア語',
  "langName.sv": 'スウェーデン語',
  "langName.sw": 'スワヒリ語',
  "langName.ta": 'タミル語',
  "langName.te": 'テルグ語',
  "langName.tg": 'タジク語',
  "langName.th": 'タイ語',
  "langName.tr": 'トルコ語',
  "langName.ug": 'ウイグル語',
  "langName.uk": 'ウクライナ語',
  "langName.ur": 'ウルドゥー語',
  "langName.uz": 'ウズベク語',
  "langName.vi": 'ベトナム語',
  "langName.wo": 'ウォロフ語',
  "langName.yi": 'イディッシュ語',
  "langName.yo": 'ヨルバ語',
  "langName.yua": 'ユカテコ・マヤ語',
  "langName.zh": '中国語',
  "langName.zh-cn": '中国語（中国）',
  "langName.zh-hk": '中国語（香港）',
  "langName.zh-tw": '中国語（台湾）',
  "langName.zh-hans": '中国語（簡体字）',
  "langName.zh-hant": '中国語（繁体字）',
  "langName.zu": 'ズールー語'
});