tinymce.addI18n('ja', {
  "-Language Not Set-": "-言語が設定されていません-",
  "Choose from list": "リストから選択",
  "Choose languages": "言語を選択",
  "Choose up to six languages": "最大6つの言語を選択",
  "Configure languages": "言語を設定",
  "Current language:": "現在の言語：",
  "Enter a valid language code with no spaces. Or, press cancel.": "スペースなしの有効な言語コードを入力してください。またはキャンセルを押してください。",
  "Enter manually": "手動入力",
  "Enter new lang code (e.g., \"en-US\"):": "新しい言語コードを入力（例：\"en-US\"）：",
  "Indicate current language": "現在の言語を表示",
  "Manually enter language {{number}}:": "言語{{number}}を手動入力：",
  "New Language:": "新しい言語：",
  "None": "なし",
  "Other - Enter manually": "その他 - 手動入力",
  "Really remove all language markup from the document?": "文書からすべての言語マークアップを削除しますか？",
  "Remove All lang markup": "すべての言語マークアップを削除",
  "Remove Language Markup": "言語マークアップを削除",
  "Remove current lang value": "現在の言語値を削除",
  "Reveal lang markup": "言語マークアップを表示",
  "Select language {{number}}:": "言語{{number}}を選択：",
  "Select the document's default language.": "文書のデフォルト言語を選択してください。",
  "Set default document language": "デフォルトの文書言語を設定",
  "Set text language": "テキストの言語を設定",
  "langName.af": "アフリカーンス語",
  "langName.af-za": "アフリカーンス語（南アフリカ）",
  "langName.ak": "アカン語",
  "langName.am": "アムハラ語",
  "langName.ar": "アラビア語",
  "langName.ar-eg": "アラビア語（エジプト）",
  "langName.ar-ma": "アラビア語（モロッコ）",
  "langName.ar-sa": "アラビア語（サウジアラビア）",
  "langName.az": "アゼルバイジャン語",
  "langName.be": "ベラルーシ語",
  "langName.bg": "ブルガリア語",
  "langName.bg-bg": "ブルガリア語（ブルガリア）",
  "langName.bho": "ボージュプリー語",
  "langName.bm": "バンバラ語",
  "langName.bn": "ベンガル語",
  "langName.bo": "チベット語",
  "langName.bs": "ボスニア語",
  "langName.ca": "カタロニア語",
  "langName.cop": "コプト語",
  "langName.cr": "クリー語",
  "langName.cs": "チェコ語",
  "langName.cu": "教会スラブ語",
  "langName.cy": "ウェールズ語",
  "langName.da": "デンマーク語",
  "langName.de": "ドイツ語",
  "langName.de-at": "ドイツ語（オーストリア）",
  "langName.de-ch": "ドイツ語（スイス）",
  "langName.de-de": "ドイツ語（ドイツ）",
  "langName.dv": "ディベヒ語",
  "langName.el": "ギリシャ語",
  "langName.en": "英語",
  "langName.en-au": "英語（オーストラリア）",
  "langName.en-ca": "英語（カナダ）",
  "langName.en-gb": "英語（イギリス）",
  "langName.en-ie": "英語（アイルランド）",
  "langName.en-in": "英語（インド）",
  "langName.en-tt": "英語（トリニダード）",
  "langName.en-us": "英語（アメリカ）",
  "langName.en-za": "英語（南アフリカ）",
  "langName.eo": "エスペラント語",
  "langName.es": "スペイン語",
  "langName.es-ar": "スペイン語（アルゼンチン）",
  "langName.es-cl": "スペイン語（チリ）",
  "langName.es-co": "スペイン語（コロンビア）",
  "langName.es-cr": "スペイン語（コスタリカ）",
  "langName.es-es": "スペイン語（スペイン）",
  "langName.es-mx": "スペイン語（メキシコ）",
  "langName.es-pe": "スペイン語（ペルー）",
  "langName.et": "エストニア語",
  "langName.eu": "バスク語",
  "langName.fa": "ペルシア語",
  "langName.fa-af": "ダリー語",
  "langName.fa-ir": "ペルシア語（イラン）",
  "langName.ff": "フラ語",
  "langName.fi": "フィンランド語",
  "langName.fi-fi": "フィンランド語（フィンランド）",
  "langName.fil": "フィリピノ語",
  "langName.fr": "フランス語",
  "langName.fr-be": "フランス語（ベルギー）",
  "langName.fr-ca": "フランス語（カナダ）",
  "langName.fr-ch": "フランス語（スイス）",
  "langName.ga": "アイルランド語",
  "langName.gl": "ガリシア語",
  "langName.grc": "古代ギリシャ語",
  "langName.ha": "ハウサ語",
  "langName.he": "ヘブライ語",
  "langName.he-il": "ヘブライ語（イスラエル）",
  "langName.hi": "ヒンディー語",
  "langName.hr": "クロアチア語",
  "langName.hr-hr": "クロアチア語（クロアチア）",
  "langName.ht": "ハイチ・クレオール語",
  "langName.hu": "ハンガリー語",
  "langName.hu-hu": "ハンガリー語（ハンガリー）",
  "langName.hy": "アルメニア語",
  "langName.id": "インドネシア語",
  "langName.ig": "イボ語",
  "langName.is": "アイスランド語",
  "langName.it": "イタリア語",
  "langName.it-it": "イタリア語（イタリア）",
  "langName.iu": "イヌクティトット語",
  "langName.ja": "日本語",
  "langName.ja-jp": "日本語（日本）",
  "langName.ka": "ジョージア語",
  "langName.kab": "カビル語",
  "langName.kk": "カザフ語",
  "langName.km": "クメール語",
  "langName.kn": "カンナダ語",
  "langName.ko": "韓国語",
  "langName.ko-kr": "韓国語（韓国）",
  "langName.la": "ラテン語",
  "langName.lkt": "ラコタ語",
  "langName.lo": "ラオ語",
  "langName.lt": "リトアニア語",
  "langName.lv": "ラトビア語",
  "langName.mi": "マオリ語",
  "langName.mn": "モンゴル語",
  "langName.mr": "マラーティー語",
  "langName.ms": "マレー語",
  "langName.mt": "マルタ語",
  "langName.my": "ミャンマー語",
  "langName.nb": "ノルウェー語（ブークモール）",
  "langName.nb-no": "ノルウェー語（ブークモール、ノルウェー）",
  "langName.ne": "ネパール語",
  "langName.nl": "オランダ語",
  "langName.nl-be": "フラマン語",
  "langName.nn": "ノルウェー語（ニーノシュク）",
  "langName.nv": "ナバホ語",
  "langName.ota": "オスマントルコ語",
  "langName.pa": "パンジャブ語",
  "langName.peo": "古代ペルシア語",
  "langName.pl": "ポーランド語",
  "langName.ps": "パシュトゥー語",
  "langName.pt": "ポルトガル語",
  "langName.pt-br": "ポルトガル語（ブラジル）",
  "langName.pt-pt": "ポルトガル語（ポルトガル）",
  "langName.qu": "ケチュア語",
  "langName.ro": "ルーマニア語",
  "langName.ru": "ロシア語",
  "langName.rw": "キニアルワンダ語",
  "langName.sa": "サンスクリット語",
  "langName.se": "北サーミ語",
  "langName.si": "シンハラ語",
  "langName.sk": "スロバキア語",
  "langName.sk-sk": "スロバキア語（スロバキア）",
  "langName.sl": "スロベニア語",
  "langName.sl-si": "スロベニア語（スロベニア）",
  "langName.sma": "南サーミ語",
  "langName.sme": "北サーミ語",
  "langName.smj": "ルレ・サーミ語",
  "langName.sn": "ショナ語",
  "langName.sr": "セルビア語",
  "langName.sr-latn": "セルビア語（ラテン文字）",
  "langName.sv": "スウェーデン語",
  "langName.sv-se": "スウェーデン語（スウェーデン）",
  "langName.sw": "スワヒリ語",
  "langName.sw-ke": "スワヒリ語（ケニア）",
  "langName.sw-tz": "スワヒリ語（タンザニア）",
  "langName.syc": "古典シリア語",
  "langName.ta": "タミル語",
  "langName.te": "テルグ語",
  "langName.tg": "タジク語",
  "langName.th": "タイ語",
  "langName.th-th": "タイ語（タイ）",
  "langName.tk": "トルクメン語",
  "langName.tl": "タガログ語",
  "langName.tr": "トルコ語",
  "langName.tr-tr": "トルコ語（トルコ）",
  "langName.tt": "タタール語",
  "langName.ug": "ウイグル語",
  "langName.uk": "ウクライナ語",
  "langName.ur": "ウルドゥー語",
  "langName.uz": "ウズベク語",
  "langName.vi": "ベトナム語",
  "langName.wo": "ウォロフ語",
  "langName.xh": "コサ語",
  "langName.yi": "イディッシュ語",
  "langName.yo": "ヨルバ語",
  "langName.yua": "ユカテコ・マヤ語",
  "langName.zh": "中国語",
  "langName.zh-cn": "中国語（簡体字）",
  "langName.zh-hans": "中国語（簡体字）",
  "langName.zh-hant": "中国語（繁体字）",
  "langName.zh-hk": "中国語（香港）",
  "langName.zh-sg": "中国語（シンガポール）",
  "langName.zh-tw": "中国語（繁体字）",
  "langName.zu": "ズールー語",
  "langName.zu-za": "ズールー語（南アフリカ）"
});