tinymce.addI18n('ko', {
  "Current language:": "현재 언어:",
  "Set text language": "텍스트 언어 설정",
  "-Language Not Set-": "-언어가 설정되지 않음-",
  "Choose languages": "언어 선택",
  "Remove Language Markup": "언어 마크업 제거",
  "Remove current lang value": "현재 언어 값 제거",
  "Remove All lang markup": "모든 언어 마크업 제거",
  "Configure languages": "언어 구성",
  "Set default document language": "기본 문서 언어 설정",
  "Reveal lang markup": "언어 마크업 표시",
  "Indicate current language": "현재 언어 표시",
  "Select the document's default language.": "문서의 기본 언어를 선택하세요.",
  "Choose from list": "목록에서 선택",
  "Enter manually": "수동 입력",
  "None": "없음",
  "Other - Enter manually": "기타 - 수동 입력",
  "Current language:": "현재 언어:",
  "New Language:": "새 언어:",
  'Enter new lang code (e.g., "en-US"):': '새 언어 코드를 입력하세요 (예: "en-US"):',
  "Choose up to six languages": "최대 6개 언어 선택",
  "Select language {{number}}:": "언어 {{number}} 선택:",
  "Manually enter language {{number}}:": "언어 {{number}} 수동 입력:",
  "Really remove all language markup from the document?": "문서에서 모든 언어 마크업을 제거하시겠습니까?",
  "Enter a valid language code with no spaces. Or, press cancel.": "공백 없이 유효한 언어 코드를 입력하거나 취소를 누르세요.",
  "langName.af": '아프리칸스어',
  "langName.ak": '아칸어',
  "langName.ar": '아랍어',
  "langName.az": '아제르바이잔어',
  "langName.bg": '불가리아어',
  "langName.bho": '보즈푸리어',
  "langName.bm": '밤바라어',
  "langName.bn": '벵골어',
  "langName.bo": '티베트어',
  "langName.bs": '보스니아어',
  "langName.ca": '카탈루냐어; 발렌시아어',
  "langName.cs": '체코어',
  "langName.cu": '고대 불가리아어',
  "langName.da": '덴마크어',
  "langName.de": '독일어',
  "langName.el": '그리스어',
  "langName.en": '영어',
  "langName.en-au": '영어(호주)',
  "langName.en-gb": '영어(영국)',
  "langName.en-in": '영어(인도)',
  "langName.en-ie": '영어(아일랜드)',
  "langName.en-tt": '영어(트리니다드)',
  "langName.en-us": '영어(미국)',
  "langName.en-za": '영어(남아프리카)',
  "langName.es": '스페인어',
  "langName.es-ar": '스페인어(아르헨티나)',
  "langName.es-cl": '스페인어(칠레)',
  "langName.es-co": '스페인어(콜롬비아)',
  "langName.es-mx": '스페인어(멕시코)',
  "langName.es-pe": '스페인어(페루)',
  "langName.et": '에스토니아어',
  "langName.eu": '바스크어',
  "langName.fa": '페르시아어',
  "langName.fi": '핀란드어',
  "langName.fr": '프랑스어',
  "langName.fr-ca": '프랑스어(캐나다)',
  "langName.gl": '갈리시아어(스페인)',
  "langName.he": '히브리어',
  "langName.hi": '힌디어',
  "langName.hr": '크로아티아어',
  "langName.hu": '헝가리어',
  "langName.id": '인도네시아어',
  "langName.it": '이탈리아어',
  "langName.ja": '일본어',
  "langName.kk": '카자흐어',
  "langName.kn": '칸나다어',
  "langName.ko": '한국어',
  "langName.la": '라틴어',
  "langName.lkt": '라코타어',
  "langName.mn": '몽골어',
  "langName.mr": '마라티어',
  "langName.nb": '노르웨이어 보크몰',
  "langName.nl": '네덜란드어',
  "langName.nl-be": '네덜란드어(벨기에)',
  "langName.nn": '노르웨이어 뉘노르스크',
  "langName.pl": '폴란드어',
  "langName.ps": '파슈토어',
  "langName.pt": '포르투갈어(국제)',
  "langName.pt-br": '포르투갈어(브라질)',
  "langName.qu": '케추아어',
  "langName.ro": '루마니아어',
  "langName.ru": '러시아어',
  "langName.sa": '산스크리트어',
  "langName.sk-sk": '슬로바키아어',
  "langName.sl": '슬로베니아어',
  "langName.sma": '남부 사미어',
  "langName.sme": '북부 사미어',
  "langName.smj": '룰레 사미어',
  "langName.sr": '세르비아어',
  "langName.sv": '스웨덴어',
  "langName.sw": '스와힐리어',
  "langName.ta": '타밀어',
  "langName.te": '텔루구어',
  "langName.tg": '타지크어',
  "langName.th": '태국어',
  "langName.tr": '터키어',
  "langName.ug": '위구르어',
  "langName.uk": '우크라이나어',
  "langName.ur": '우르두어',
  "langName.uz": '우즈베크어',
  "langName.vi": '베트남어',
  "langName.wo": '월로프어',
  "langName.yi": '이디시어',
  "langName.yo": '요루바어',
  "langName.yua": '유카텍 마야어',
  "langName.zh": '중국어',
  "langName.zh-cn": '중국어(중국)',
  "langName.zh-hk": '중국어(홍콩)',
  "langName.zh-tw": '중국어(대만)',
  "langName.zh-hans": '중국어(간체)',
  "langName.zh-hant": '중국어(번체)',
  "langName.zu": '줄루어'
});