tinymce.addI18n('ko', {
  "-Language Not Set-": "-언어가 설정되지 않음-",
  "Choose from list": "목록에서 선택",
  "Choose languages": "언어 선택",
  "Choose up to six languages": "최대 6개 언어 선택",
  "Configure languages": "언어 구성",
  "Current language:": "현재 언어:",
  "Enter a valid language code with no spaces. Or, press cancel.": "공백 없이 유효한 언어 코드를 입력하거나 취소를 누르세요.",
  "Enter manually": "수동 입력",
  "Enter new lang code (e.g., \"en-US\"):": "새 언어 코드를 입력하세요 (예: \"en-US\"):",
  "Indicate current language": "현재 언어 표시",
  "Manually enter language {{number}}:": "언어 {{number}} 수동 입력:",
  "New Language:": "새 언어:",
  "None": "없음",
  "Other - Enter manually": "기타 - 수동 입력",
  "Really remove all language markup from the document?": "문서에서 모든 언어 마크업을 제거하시겠습니까?",
  "Remove All lang markup": "모든 언어 마크업 제거",
  "Remove Language Markup": "언어 마크업 제거",
  "Remove current lang value": "현재 언어 값 제거",
  "Reveal lang markup": "언어 마크업 표시",
  "Select language {{number}}:": "언어 {{number}} 선택:",
  "Select the document's default language.": "문서의 기본 언어를 선택하세요.",
  "Set default document language": "기본 문서 언어 설정",
  "Set text language": "텍스트 언어 설정",
  "langName.af": "아프리칸스어",
  "langName.af-za": "아프리칸스어",
  "langName.ak": "아칸어",
  "langName.am": "암하라어",
  "langName.ar": "아랍어",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "아랍어",
  "langName.az": "아제르바이잔어",
  "langName.be": "벨라루스어",
  "langName.bg": "불가리아어",
  "langName.bg-bg": "불가리아어",
  "langName.bho": "호즈푸리어",
  "langName.bm": "밤바라어",
  "langName.bn": "벵골어",
  "langName.bo": "티베트어",
  "langName.bs": "보스니아어",
  "langName.ca": "카탈로니아어",
  "langName.cop": "콥트어",
  "langName.cr": "크리어",
  "langName.cs": "체코어",
  "langName.cu": "교회 슬라브어",
  "langName.cy": "웨일스어",
  "langName.da": "덴마크어",
  "langName.de": "독일어",
  "langName.de-at": "",
  "langName.de-ch": "고지 독일어(스위스)",
  "langName.de-de": "독일어",
  "langName.dv": "디베히어",
  "langName.el": "그리스어",
  "langName.en": "영어",
  "langName.en-au": "영어(호주)",
  "langName.en-ca": "",
  "langName.en-gb": "영어(영국)",
  "langName.en-ie": "영어(아일랜드)",
  "langName.en-in": "영어(인도)",
  "langName.en-tt": "영어(트리니다드)",
  "langName.en-us": "영어",
  "langName.en-za": "영어(남아프리카)",
  "langName.eo": "에스페란토어",
  "langName.es": "스페인어",
  "langName.es-ar": "스페인어(아르헨티나)",
  "langName.es-cl": "스페인어(칠레)",
  "langName.es-co": "스페인어(콜롬비아)",
  "langName.es-cr": "",
  "langName.es-es": "스페인어(유럽)",
  "langName.es-mx": "스페인어(멕시코)",
  "langName.es-pe": "스페인어(페루)",
  "langName.et": "에스토니아어",
  "langName.eu": "바스크어",
  "langName.fa": "페르시아어",
  "langName.fa-af": "다리어",
  "langName.fa-ir": "페르시아어",
  "langName.ff": "풀라어",
  "langName.fi": "핀란드어",
  "langName.fi-fi": "핀란드어",
  "langName.fil": "필리핀어",
  "langName.fr": "프랑스어",
  "langName.fr-be": "",
  "langName.fr-ca": "프랑스어(캐나다)",
  "langName.fr-ch": "",
  "langName.ga": "아일랜드어",
  "langName.gl": "갈리시아어",
  "langName.grc": "고대 그리스어",
  "langName.ha": "하우사어",
  "langName.he": "히브리어",
  "langName.he-il": "히브리어",
  "langName.hi": "힌디어",
  "langName.hr": "크로아티아어",
  "langName.hr-hr": "크로아티아어",
  "langName.ht": "아이티어",
  "langName.hu": "헝가리어",
  "langName.hu-hu": "헝가리어",
  "langName.hy": "아르메니아어",
  "langName.id": "인도네시아어",
  "langName.ig": "이그보어",
  "langName.is": "아이슬란드어",
  "langName.it": "이탈리아어",
  "langName.it-it": "이탈리아어",
  "langName.iu": "이눅티투트어",
  "langName.ja": "일본어",
  "langName.ja-jp": "일본어",
  "langName.ka": "조지아어",
  "langName.kab": "커바일어",
  "langName.kk": "카자흐어",
  "langName.km": "크메르어",
  "langName.kn": "칸나다어",
  "langName.ko": "한국어",
  "langName.ko-kr": "한국어",
  "langName.la": "라틴어",
  "langName.lkt": "라코타어",
  "langName.lo": "라오어",
  "langName.lt": "리투아니아어",
  "langName.lv": "라트비아어",
  "langName.mi": "마오리어",
  "langName.mn": "몽골어",
  "langName.mr": "마라티어",
  "langName.ms": "말레이어",
  "langName.mt": "몰타어",
  "langName.my": "버마어",
  "langName.nb": "노르웨이어(보크말)",
  "langName.nb-no": "노르웨이어(보크말)",
  "langName.ne": "네팔어",
  "langName.nl": "네덜란드어",
  "langName.nl-be": "플라망어",
  "langName.nn": "노르웨이어(니노르스크)",
  "langName.nv": "나바호어",
  "langName.ota": "오스만 터키어",
  "langName.pa": "펀잡어",
  "langName.peo": "고대 페르시아어",
  "langName.pl": "폴란드어",
  "langName.ps": "파슈토어",
  "langName.pt": "포르투갈어",
  "langName.pt-br": "포르투갈어",
  "langName.pt-pt": "포르투갈어(유럽)",
  "langName.qu": "케추아어",
  "langName.ro": "루마니아어",
  "langName.ru": "러시아어",
  "langName.rw": "르완다어",
  "langName.sa": "산스크리트어",
  "langName.se": "북부 사미어",
  "langName.si": "싱할라어",
  "langName.sk-sk": "슬로바키아어",
  "langName.sl": "슬로베니아어",
  "langName.sl-si": "슬로베니아어",
  "langName.sma": "남부 사미어",
  "langName.sme": "북부 사미어",
  "langName.smj": "룰레 사미어",
  "langName.sn": "쇼나어",
  "langName.sr": "세르비아어",
  "langName.sr-latn": "",
  "langName.sv": "스웨덴어",
  "langName.sv-se": "스웨덴어",
  "langName.sw": "스와힐리어",
  "langName.sw-ke": "스와힐리어",
  "langName.sw-tz": "스와힐리어",
  "langName.syc": "고전 시리아어",
  "langName.ta": "타밀어",
  "langName.te": "텔루구어",
  "langName.tg": "타지크어",
  "langName.th": "태국어",
  "langName.th-th": "태국어",
  "langName.tk": "투르크멘어",
  "langName.tl": "타갈로그어",
  "langName.tr": "튀르키예어",
  "langName.tr-tr": "튀르키예어",
  "langName.tt": "타타르어",
  "langName.ug": "위구르어",
  "langName.uk": "우크라이나어",
  "langName.ur": "우르두어",
  "langName.uz": "우즈베크어",
  "langName.vi": "베트남어",
  "langName.wo": "월로프어",
  "langName.xh": "코사어",
  "langName.yi": "이디시어",
  "langName.yo": "요루바어",
  "langName.yua": "유카텍 마야어",
  "langName.zh": "중국어",
  "langName.zh-cn": "중국어(중국)",
  "langName.zh-hans": "중국어(간체)",
  "langName.zh-hant": "중국어(번체)",
  "langName.zh-hk": "중국어(홍콩)",
  "langName.zh-sg": "",
  "langName.zh-tw": "중국어(대만)",
  "langName.zu": "줄루어",
  "langName.zu-za": "줄루어"
});