tinymce.addI18n("mi", {
  "Current language:": "Reo o nāianei:",
  "Set text language": "Whakatakoto reo kuputuhi",
  "-Language Not Set-": "-Kāore he Reo i Whakatakoto-",
  "Choose languages": "Kōwhiri ngā reo",
  "Remove Language Markup": "Tango Tohu Reo",
  "Remove current lang value": "Tango uara reo o nāianei",
  "Remove All lang markup": "Tango katoa ngā tohu reo",
  "Configure languages": "Whiriwhiri ngā reo",
  "Set default document language": "Whakatakoto reo taunoa o te pukapuka",
  "Reveal lang markup": "Whakaatu tohu reo",
  "Indicate current language": "Tohu te reo o nāianei",
  "Select the document's default language.": "Kōwhiri te reo taunoa o te pukapuka.",
  "Choose from list": "Kōwhiri i te raina",
  "Enter manually": "Whakaurunga ā-ringaringa",
  "None": "Kāore",
  "Other - Enter manually": "Kē atu - Whakaurunga ā-ringaringa",
  "New Language:": "Reo Hōu:",
  "Enter new lang code (e.g., \"en-US\"):": "Whakaurunga waehere reo hōu (hei tauira, \"en-US\"):",
  "Choose up to six languages": "Kōwhiri hā ki a ono reo",
  "Select language {{number}}:": "Kōwhiri reo {{number}}:",
  "Manually enter language {{number}}:": "Whakaurunga ā-ringaringa reo {{number}}:",
  "Really remove all language markup from the document?": "He pono koe kī te tango katoa ngā tohu reo i te pukapuka?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Whakaurunga waehere reo whaimana kore mokowā rānei. Rānei, pēhi whakakore.",
  "langName.af": "Afrikaans",
  "langName.ak": "Akan",
  "langName.ar": "Ārapi",
  "langName.az": "Azerbaijani",
  "langName.bg": "Pūkāriana",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Penekāri",
  "langName.bo": "Tipetana",
  "langName.bs": "Posōniana",
  "langName.ca": "Katarāna; Wareniana",
  "langName.cs": "Tīeke",
  "langName.cu": "Pūkāriana Tawhito",
  "langName.da": "Taina",
  "langName.de": "Tiamana",
  "langName.el": "Kirīki",
  "langName.en": "Pākehā",
  "langName.en-au": "Pākehā (Ahitereiriana)",
  "langName.en-gb": "Pākehā (Kīngitanga Kotahi)",
  "langName.en-in": "Pākehā (Inia)",
  "langName.en-ie": "Pākehā (Airangi)",
  "langName.en-tt": "Pākehā (Tirinaki)",
  "langName.en-us": "Pākehā (Hononga-o-Amerika)",
  "langName.en-za": "Pākehā (Āwherika-ki-te-Tonga)",
  "langName.es": "Paniora",
  "langName.es-ar": "Paniora (Āketina)",
  "langName.es-cl": "Paniora (Tire)",
  "langName.es-co": "Paniora (Koromopia)",
  "langName.es-mx": "Paniora (Mēhiko)",
  "langName.es-pe": "Paniora (Perū)",
  "langName.et": "Etoniana",
  "langName.eu": "Pākeke",
  "langName.fa": "Pēhiana",
  "langName.fi": "Wīnirana",
  "langName.fr": "Wīwī",
  "langName.fr-ca": "Wīwī (Kānata)",
  "langName.gl": "Karīhiana (Peina)",
  "langName.he": "Hīperu",
  "langName.hi": "Hinī",
  "langName.hr": "Koroātiana",
  "langName.hu": "Hanekāriana",
  "langName.id": "Initonīhiana",
  "langName.it": "Ītariana",
  "langName.ja": "Hapanihi",
  "langName.kk": "Kāhaki",
  "langName.kn": "Kannada",
  "langName.ko": "Kōriana",
  "langName.la": "Rātina",
  "langName.lkt": "Lakota",
  "langName.mn": "Monokōriana",
  "langName.mr": "Marathi",
  "langName.nb": "Nōwei Bokmål",
  "langName.nl": "Tati",
  "langName.nl-be": "Tati (Pereīhiama)",
  "langName.nn": "Nōwei Nynorsk",
  "langName.pl": "Pōrana",
  "langName.ps": "Pashto",
  "langName.pt": "Pōtikī, Taiao",
  "langName.pt-br": "Pōtikī, Parahi",
  "langName.qu": "Quechua",
  "langName.ro": "Rōmana",
  "langName.ru": "Rūhia",
  "langName.sa": "Hanahikiri",
  "langName.sk-sk": "Horowākiana",
  "langName.sl": "Horowēniana",
  "langName.sma": "Sami Tonga",
  "langName.sme": "Sami Raki",
  "langName.smj": "Sami Lule",
  "langName.sr": "Hāpiana",
  "langName.sv": "Huitene",
  "langName.sw": "Swahili",
  "langName.ta": "Tamira",
  "langName.te": "Telugu",
  "langName.tg": "Tajik",
  "langName.th": "Tai",
  "langName.tr": "Tūkī",
  "langName.ug": "Uyghur",
  "langName.uk": "Ukareina",
  "langName.ur": "Urdu",
  "langName.uz": "Uzbek",
  "langName.vi": "Ūetināmi",
  "langName.wo": "Wolof",
  "langName.yi": "Yiddish",
  "langName.yo": "Yoruba",
  "langName.yua": "Maya Yucatec",
  "langName.zh": "Haina",
  "langName.zh-cn": "Haina (Haina)",
  "langName.zh-hk": "Haina (Hong Kong)",
  "langName.zh-tw": "Haina (Taiwan)",
  "langName.zh-hans": "Haina, māmā",
  "langName.zh-hant": "Haina, tawhito",
  "langName.zu": "Zulu"
});