tinymce.addI18n('mi', {
  "-Language Not Set-": "-Kāore he Reo i Whakatakoto-",
  "Choose from list": "Kōwhiri i te raina",
  "Choose languages": "Kōwhiri ngā reo",
  "Choose up to six languages": "Kōwhiri hā ki a ono reo",
  "Configure languages": "Whiriwhiri ngā reo",
  "Current language:": "Reo o nāianei:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Whakaurunga waehere reo whaimana kore mokowā rānei. Rānei, pēhi whakakore.",
  "Enter manually": "Whakaurunga ā-ringaringa",
  "Enter new lang code (e.g., \"en-US\"):": "Whakaurunga waehere reo hōu (hei tauira, \"en-US\"):",
  "Indicate current language": "Tohu te reo o nāianei",
  "Manually enter language {{number}}:": "Whakaurunga ā-ringaringa reo {{number}}:",
  "New Language:": "Reo Hōu:",
  "None": "Kāore",
  "Other - Enter manually": "Kē atu - Whakaurunga ā-ringaringa",
  "Really remove all language markup from the document?": "He pono koe kī te tango katoa ngā tohu reo i te pukapuka?",
  "Remove All lang markup": "Tango katoa ngā tohu reo",
  "Remove Language Markup": "Tango Tohu Reo",
  "Remove current lang value": "Tango uara reo o nāianei",
  "Reveal lang markup": "Whakaatu tohu reo",
  "Select language {{number}}:": "Kōwhiri reo {{number}}:",
  "Select the document's default language.": "Kōwhiri te reo taunoa o te pukapuka.",
  "Set default document language": "Whakatakoto reo taunoa o te pukapuka",
  "Set text language": "Whakatakoto reo kuputuhi",
  "langName.af": "Awherikāna",
  "langName.af-za": "Awherikāna (Āwherika-ki-te-Tonga)",
  "langName.ak": "Ākana",
  "langName.am": "Amahereka",
  "langName.ar": "Ārapi",
  "langName.ar-eg": "Ārapi (Ihipa)",
  "langName.ar-ma": "Ārapi (Moroko)",
  "langName.ar-sa": "Ārapi (Hauti Arepia)",
  "langName.az": "Atepaihānia",
  "langName.be": "Perarūhiana",
  "langName.bg": "Purukāriana",
  "langName.bg-bg": "Purukāriana (Purukāria)",
  "langName.bho": "Pōhipuri",
  "langName.bm": "Pāpara",
  "langName.bn": "Pākara",
  "langName.bo": "Tipete",
  "langName.bs": "Pōngiana",
  "langName.ca": "Katarana",
  "langName.cop": "Kopitika",
  "langName.cr": "Kırī",
  "langName.cs": "Tieke",
  "langName.cu": "Pūkāriana Tawhito",
  "langName.cy": "Werehi",
  "langName.da": "Teina",
  "langName.de": "Tiamana",
  "langName.de-at": "Tiamana (Ōtelia)",
  "langName.de-ch": "Tiamana (Huiterangi)",
  "langName.de-de": "Tiamana (Tiamani)",
  "langName.dv": "Tīwhehi",
  "langName.el": "Kariki",
  "langName.en": "Ingarihi",
  "langName.en-au": "Ingarihi (Ahitereiriana)",
  "langName.en-ca": "Ingarihi (Kānata)",
  "langName.en-gb": "Ingarihi (Kīngitanga Kotahi)",
  "langName.en-ie": "Ingarihi (Airangi)",
  "langName.en-in": "Ingarihi (Inia)",
  "langName.en-tt": "Ingarihi (Tirinaki)",
  "langName.en-us": "Ingarihi (Hononga-o-Amerika)",
  "langName.en-za": "Ingarihi (Āwherika-ki-te-Tonga)",
  "langName.eo": "Eheperāto",
  "langName.es": "Pāniora",
  "langName.es-ar": "Pāniora (Āketina)",
  "langName.es-cl": "Pāniora (Tire)",
  "langName.es-co": "Pāniora (Koromopia)",
  "langName.es-cr": "Pāniora (Koha Rika)",
  "langName.es-es": "Pāniora (Pēni)",
  "langName.es-mx": "Pāniora (Mehikana)",
  "langName.es-pe": "Pāniora (Perū)",
  "langName.et": "Etōniana",
  "langName.eu": "Pākihi",
  "langName.fa": "Pāhiana",
  "langName.fa-af": "Tāri",
  "langName.fa-ir": "Pāhiana (Īrāna)",
  "langName.ff": "Whūra",
  "langName.fi": "Whinirānia",
  "langName.fi-fi": "Whinirānia (Whinirāni)",
  "langName.fil": "Piripīno",
  "langName.fr": "Wīwī",
  "langName.fr-be": "Wīwī (Pehiamu)",
  "langName.fr-ca": "Wīwī (Kānata)",
  "langName.fr-ch": "Wīwī (Huiterangi)",
  "langName.ga": "Airihi",
  "langName.gl": "Karīhia",
  "langName.grc": "Kariki Tawhito",
  "langName.ha": "Hauha",
  "langName.he": "Hīperu",
  "langName.he-il": "Hīperu (Iharaira)",
  "langName.hi": "Hīni",
  "langName.hr": "Koroātiana",
  "langName.hr-hr": "Koroātiana (Koroātia)",
  "langName.ht": "Kereō Haiti",
  "langName.hu": "Hanekari",
  "langName.hu-hu": "Hanekari (Hanekāria)",
  "langName.hy": "Āmeniana",
  "langName.id": "Initonīhiana",
  "langName.ig": "Ikapo",
  "langName.is": "Tiorangi",
  "langName.it": "Itāriana",
  "langName.it-it": "Itāriana (Itāria)",
  "langName.iu": "Inukitetūta",
  "langName.ja": "Hapanihi",
  "langName.ja-jp": "Hapanihi (Hapani)",
  "langName.ka": "Hōriana",
  "langName.kab": "Kapāiro",
  "langName.kk": "Kahāka",
  "langName.km": "Kimēra",
  "langName.kn": "Kanara",
  "langName.ko": "Kōreana",
  "langName.ko-kr": "Kōreana (Kōrea)",
  "langName.la": "Rātini",
  "langName.lkt": "Rakōta",
  "langName.lo": "Rao",
  "langName.lt": "Rituānia",
  "langName.lv": "Rāwhia",
  "langName.mi": "Māori",
  "langName.mn": "Mongōria",
  "langName.mr": "Marati",
  "langName.ms": "Marei",
  "langName.mt": "Mārata",
  "langName.my": "Pēmīhi",
  "langName.nb": "Nōwei (Pakamō)",
  "langName.nb-no": "Nōwei (Pakamō, Nōwei)",
  "langName.ne": "Nepari",
  "langName.nl": "Tati",
  "langName.nl-be": "Tati (Pehiamu)",
  "langName.nn": "Nōwei (Nīnōka)",
  "langName.nv": "Nawahō",
  "langName.ota": "Tākei (Otomana)",
  "langName.pa": "Punutapi",
  "langName.peo": "Pāhiana Tawhito",
  "langName.pl": "Pōrihi",
  "langName.ps": "Pāhitō",
  "langName.pt": "Pōtukīhi",
  "langName.pt-br": "Pōtukīhi (Parahi)",
  "langName.pt-pt": "Pōtukīhi (Pōtukāra)",
  "langName.qu": "Kētua",
  "langName.ro": "Romeinia",
  "langName.ru": "Ruhiana",
  "langName.rw": "Kiniawāna",
  "langName.sa": "Hanahiti",
  "langName.se": "Hami (Raki)",
  "langName.si": "Hinihāra",
  "langName.sk": "Horowākia",
  "langName.sk-sk": "Horowākia (Horowākia)",
  "langName.sl": "Horowinia",
  "langName.sl-si": "Horowinia (Horowinia)",
  "langName.sma": "Hami (Tonga)",
  "langName.sme": "Hami (Raki)",
  "langName.smj": "Hami (Lule)",
  "langName.sn": "Hōna",
  "langName.sr": "Hirupia",
  "langName.sr-latn": "Hirupia (Rātini)",
  "langName.sv": "Huitene",
  "langName.sv-se": "Huitene (Huitene)",
  "langName.sw": "Wāhīri",
  "langName.sw-ke": "Wāhīri (Kenia)",
  "langName.sw-tz": "Wāhīri (Tanahania)",
  "langName.syc": "Hiriaka Tawhito",
  "langName.ta": "Tamira",
  "langName.te": "Teruku",
  "langName.tg": "Tāhiki",
  "langName.th": "Tai",
  "langName.th-th": "Tai (Tairana)",
  "langName.tk": "Tākamana",
  "langName.tl": "Takaroka",
  "langName.tr": "Tākei",
  "langName.tr-tr": "Tākei (Tākei)",
  "langName.tt": "Tatā",
  "langName.ug": "Wīkura",
  "langName.uk": "Ukareinga",
  "langName.ur": "Ūrutu",
  "langName.uz": "Ūpeke",
  "langName.vi": "Whitināmu",
  "langName.wo": "Warawhe",
  "langName.xh": "Tōha",
  "langName.yi": "Irihi",
  "langName.yo": "Ōrūpa",
  "langName.yua": "Maya (Yucatec)",
  "langName.zh": "Hainamana",
  "langName.zh-cn": "Hainamana (Haina)",
  "langName.zh-hans": "Hainamana (Māmā)",
  "langName.zh-hant": "Hainamana (Tukuiho)",
  "langName.zh-hk": "Hainamana (Hong Kong)",
  "langName.zh-sg": "Hainamana (Hingapoa)",
  "langName.zh-tw": "Hainamana (Taiwan)",
  "langName.zu": "Tūru",
  "langName.zu-za": "Tūru (Āwherika-ki-te-Tonga)"
});