tinymce.addI18n("nb", {
  "Current language:": "Gjeldende språk:",
  "Set text language": "Angi tekstspråk",
  "-Language Not Set-": "-Språk ikke angitt-",
  "Choose languages": "Velg språk",
  "Remove Language Markup": "Fjern språkmarkering",
  "Remove current lang value": "Fjern gjeldende språkverdi",
  "Remove All lang markup": "Fjern all språkmarkering",
  "Configure languages": "Konfigurer språk",
  "Set default document language": "Angi standard dokumentspråk",
  "Reveal lang markup": "Vis språkmarkering",
  "Indicate current language": "Angi gjeldende språk",
  "Select the document's default language.": "Velg dokumentets standardspråk.",
  "Choose from list": "Velg fra liste",
  "Enter manually": "Skriv inn manuelt",
  "None": "Ingen",
  "Other - Enter manually": "Annet - Skriv inn manuelt",
  "New Language:": "Nytt språk:",
  "Enter new lang code (e.g., \"en-US\"):": "Skriv inn ny språkkode (f.eks. \"en-US\"):",
  "Choose up to six languages": "Velg opptil seks språk",
  "Select language {{number}}:": "Velg språk {{number}}:",
  "Manually enter language {{number}}:": "Skriv inn språk {{number}} manuelt:",
  "Really remove all language markup from the document?": "Vil du virkelig fjerne all språkmarkering fra dokumentet?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Skriv inn en gyldig språkkode uten mellomrom. Eller trykk avbryt.",
  "langName.af": "afrikaans",
  "langName.ak": "akan",
  "langName.ar": "arabisk",
  "langName.az": "aserbajdsjansk",
  "langName.bg": "bulgarsk",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengalsk",
  "langName.bo": "tibetansk",
  "langName.bs": "bosnisk",
  "langName.ca": "katalansk; valenciansk",
  "langName.cs": "tsjekkisk",
  "langName.cu": "gammelbulgarsk",
  "langName.da": "dansk",
  "langName.de": "tysk",
  "langName.el": "gresk",
  "langName.en": "engelsk",
  "langName.en-au": "engelsk (Australia)",
  "langName.en-gb": "engelsk (Storbritannia)",
  "langName.en-in": "engelsk (India)",
  "langName.en-ie": "engelsk (Irland)",
  "langName.en-tt": "engelsk (Trinidad)",
  "langName.en-us": "engelsk (USA)",
  "langName.en-za": "engelsk (Sør-Afrika)",
  "langName.es": "spansk",
  "langName.es-ar": "spansk (Argentina)",
  "langName.es-cl": "spansk (Chile)",
  "langName.es-co": "spansk (Colombia)",
  "langName.es-mx": "spansk (Mexico)",
  "langName.es-pe": "spansk (Peru)",
  "langName.et": "estisk",
  "langName.eu": "baskisk",
  "langName.fa": "persisk",
  "langName.fi": "finsk",
  "langName.fr": "fransk",
  "langName.fr-ca": "fransk (Canada)",
  "langName.gl": "galisisk (Spania)",
  "langName.he": "hebraisk",
  "langName.hi": "hindi",
  "langName.hr": "kroatisk",
  "langName.hu": "ungarsk",
  "langName.id": "indonesisk",
  "langName.it": "italiensk",
  "langName.ja": "japansk",
  "langName.kk": "kasakhisk",
  "langName.kn": "kannada",
  "langName.ko": "koreansk",
  "langName.la": "latin",
  "langName.lkt": "lakota",
  "langName.mn": "mongolsk",
  "langName.mr": "marathi",
  "langName.nb": "norsk bokmål",
  "langName.nl": "nederlandsk",
  "langName.nl-be": "nederlandsk (Belgia)",
  "langName.nn": "norsk nynorsk",
  "langName.pl": "polsk",
  "langName.ps": "pashto",
  "langName.pt": "portugisisk, internasjonal",
  "langName.pt-br": "portugisisk, Brasil",
  "langName.qu": "quechua",
  "langName.ro": "rumensk",
  "langName.ru": "russisk",
  "langName.sa": "sanskrit",
  "langName.sk-sk": "slovakisk",
  "langName.sl": "slovensk",
  "langName.sma": "sørsamisk",
  "langName.sme": "nordsamisk",
  "langName.smj": "lulesamisk",
  "langName.sr": "serbisk",
  "langName.sv": "svensk",
  "langName.sw": "swahili",
  "langName.ta": "tamilsk",
  "langName.te": "telugu",
  "langName.tg": "tadsjikisk",
  "langName.th": "thai",
  "langName.tr": "tyrkisk",
  "langName.ug": "uigurisk",
  "langName.uk": "ukrainsk",
  "langName.ur": "urdu",
  "langName.uz": "usbekisk",
  "langName.vi": "vietnamesisk",
  "langName.wo": "wolof",
  "langName.yi": "jiddisch",
  "langName.yo": "yoruba",
  "langName.yua": "yukatekisk maya",
  "langName.zh": "kinesisk",
  "langName.zh-cn": "kinesisk (Kina)",
  "langName.zh-hk": "kinesisk (Hong Kong)",
  "langName.zh-tw": "kinesisk (Taiwan)",
  "langName.zh-hans": "kinesisk, forenklet",
  "langName.zh-hant": "kinesisk, tradisjonell",
  "langName.zu": "zulu"
});