tinymce.addI18n('nb_x_k12', {
  "-Language Not Set-": "-Ingen språk valgt-",
  "Choose from list": "Velg fra liste",
  "Choose languages": "Velg språk",
  "Choose up to six languages": "Velg opptil seks språk",
  "Configure languages": "Still inn språk",
  "Current language:": "Nåværende språk:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Skriv en gyldig språkkode uten mellomrom. Eller trykk avbryt.",
  "Enter manually": "Skriv selv",
  "Enter new lang code (e.g., \"en-US\"):": "Skriv ny språkkode (f.eks. \"nb-NO\"):",
  "Indicate current language": "Vis nåværende språk",
  "Manually enter language {{number}}:": "Skriv språk {{number}} selv:",
  "New Language:": "Nytt språk:",
  "None": "Ingen",
  "Other - Enter manually": "Annet - Skriv selv",
  "Really remove all language markup from the document?": "Vil du virkelig fjerne all språkmerking fra dokumentet?",
  "Remove All lang markup": "Fjern all språkmerking",
  "Remove Language Markup": "Fjern språkmerking",
  "Remove current lang value": "Fjern nåværende språk",
  "Reveal lang markup": "Vis språkmerking",
  "Select language {{number}}:": "Velg språk {{number}}:",
  "Select the document's default language.": "Velg dokumentets standardspråk.",
  "Set default document language": "Velg standardspråk for dokumentet",
  "Set text language": "Velg språk for tekst",
  "langName.af": "afrikaans",
  "langName.af-za": "afrikaans",
  "langName.ak": "akan",
  "langName.am": "amharisk",
  "langName.ar": "arabisk",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "arabisk",
  "langName.az": "aserbajdsjansk",
  "langName.be": "belarusisk",
  "langName.bg": "bulgarsk",
  "langName.bg-bg": "bulgarsk",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengali",
  "langName.bo": "tibetansk",
  "langName.bs": "bosnisk",
  "langName.ca": "katalansk",
  "langName.cop": "koptisk",
  "langName.cr": "cree",
  "langName.cs": "tsjekkisk",
  "langName.cu": "kirkeslavisk",
  "langName.cy": "walisisk",
  "langName.da": "dansk",
  "langName.de": "tysk",
  "langName.de-at": "",
  "langName.de-ch": "",
  "langName.de-de": "tysk",
  "langName.dv": "divehi",
  "langName.el": "gresk",
  "langName.en": "engelsk",
  "langName.en-au": "Engelsk (Australia)",
  "langName.en-ca": "",
  "langName.en-gb": "Engelsk (England)",
  "langName.en-ie": "Engelsk (Irland)",
  "langName.en-in": "Engelsk (India)",
  "langName.en-tt": "Engelsk (Trinidad)",
  "langName.en-us": "engelsk",
  "langName.en-za": "Engelsk (Sør-Afrika)",
  "langName.eo": "esperanto",
  "langName.es": "spansk",
  "langName.es-ar": "Spansk (Argentina)",
  "langName.es-cl": "Spansk (Chile)",
  "langName.es-co": "Spansk (Colombia)",
  "langName.es-cr": "",
  "langName.es-es": "spansk",
  "langName.es-mx": "Spansk (Mexico)",
  "langName.es-pe": "Spansk (Peru)",
  "langName.et": "estisk",
  "langName.eu": "baskisk",
  "langName.fa": "persisk",
  "langName.fa-af": "dari",
  "langName.fa-ir": "persisk",
  "langName.ff": "fulfulde",
  "langName.fi": "finsk",
  "langName.fi-fi": "finsk",
  "langName.fil": "filipino",
  "langName.fr": "fransk",
  "langName.fr-be": "",
  "langName.fr-ca": "Fransk (Canada)",
  "langName.fr-ch": "",
  "langName.ga": "irsk",
  "langName.gl": "galisisk",
  "langName.grc": "gammelgresk",
  "langName.ha": "hausa",
  "langName.he": "hebraisk",
  "langName.he-il": "hebraisk",
  "langName.hi": "hindi",
  "langName.hr": "kroatisk",
  "langName.hr-hr": "kroatisk",
  "langName.ht": "haitisk",
  "langName.hu": "ungarsk",
  "langName.hu-hu": "ungarsk",
  "langName.hy": "armensk",
  "langName.id": "indonesisk",
  "langName.ig": "ibo",
  "langName.is": "islandsk",
  "langName.it": "italiensk",
  "langName.it-it": "italiensk",
  "langName.iu": "inuktitut",
  "langName.ja": "japansk",
  "langName.ja-jp": "japansk",
  "langName.ka": "georgisk",
  "langName.kab": "kabylsk",
  "langName.kk": "kasakhisk",
  "langName.km": "khmer",
  "langName.kn": "kannada",
  "langName.ko": "koreansk",
  "langName.ko-kr": "koreansk",
  "langName.la": "latin",
  "langName.lkt": "lakota",
  "langName.lo": "laotisk",
  "langName.lt": "litauisk",
  "langName.lv": "latvisk",
  "langName.mi": "maori",
  "langName.mn": "mongolsk",
  "langName.mr": "marathi",
  "langName.ms": "malayisk",
  "langName.mt": "maltesisk",
  "langName.my": "burmesisk",
  "langName.nb": "norsk bokmål",
  "langName.nb-no": "norsk bokmål",
  "langName.ne": "nepali",
  "langName.nl": "nederlandsk",
  "langName.nl-be": "flamsk",
  "langName.nn": "norsk nynorsk",
  "langName.nv": "navajo",
  "langName.ota": "ottomansk tyrkisk",
  "langName.pa": "panjabi",
  "langName.peo": "gammelpersisk",
  "langName.pl": "polsk",
  "langName.ps": "pashto",
  "langName.pt": "portugisisk",
  "langName.pt-br": "portugisisk",
  "langName.pt-pt": "portugisisk",
  "langName.qu": "quechua",
  "langName.ro": "rumensk",
  "langName.ru": "russisk",
  "langName.rw": "kinyarwanda",
  "langName.sa": "sanskrit",
  "langName.se": "nordsamisk",
  "langName.si": "singalesisk",
  "langName.sk-sk": "slovakisk",
  "langName.sl": "slovensk",
  "langName.sl-si": "slovensk",
  "langName.sma": "sørsamisk",
  "langName.sme": "Nordsamisk",
  "langName.smj": "lulesamisk",
  "langName.sn": "shona",
  "langName.sr": "serbisk",
  "langName.sr-latn": "",
  "langName.sv": "svensk",
  "langName.sv-se": "svensk",
  "langName.sw": "swahili",
  "langName.sw-ke": "swahili",
  "langName.sw-tz": "swahili",
  "langName.syc": "klassisk syrisk",
  "langName.ta": "tamil",
  "langName.te": "telugu",
  "langName.tg": "tadsjikisk",
  "langName.th": "thai",
  "langName.th-th": "thai",
  "langName.tk": "turkmensk",
  "langName.tl": "tagalog",
  "langName.tr": "tyrkisk",
  "langName.tr-tr": "tyrkisk",
  "langName.tt": "tatarisk",
  "langName.ug": "uigurisk",
  "langName.uk": "ukrainsk",
  "langName.ur": "urdu",
  "langName.uz": "usbekisk",
  "langName.vi": "vietnamesisk",
  "langName.wo": "wolof",
  "langName.xh": "xhosa",
  "langName.yi": "jiddisk",
  "langName.yo": "joruba",
  "langName.yua": "Yucatec Maya",
  "langName.zh": "kinesisk",
  "langName.zh-cn": "forenklet kinesisk",
  "langName.zh-hans": "forenklet kinesisk",
  "langName.zh-hant": "tradisjonell kinesisk",
  "langName.zh-hk": "Kinesisk (Hongkong)",
  "langName.zh-sg": "",
  "langName.zh-tw": "tradisjonell kinesisk",
  "langName.zu": "zulu",
  "langName.zu-za": "zulu"
});