tinymce.addI18n("nb_x_k12", {
  "Current language:": "Nåværende språk:",
  "Set text language": "Velg språk for tekst",
  "-Language Not Set-": "-Ingen språk valgt-",
  "Choose languages": "Velg språk",
  "Remove Language Markup": "Fjern språkmerking",
  "Remove current lang value": "Fjern nåværende språk",
  "Remove All lang markup": "Fjern all språkmerking",
  "Configure languages": "Still inn språk",
  "Set default document language": "Velg standardspråk for dokumentet",
  "Reveal lang markup": "Vis språkmerking",
  "Indicate current language": "Vis nåværende språk",
  "Select the document's default language.": "Velg dokumentets standardspråk.",
  "Choose from list": "Velg fra liste",
  "Enter manually": "Skriv selv",
  "None": "Ingen",
  "Other - Enter manually": "Annet - Skriv selv",
  "New Language:": "Nytt språk:",
  "Enter new lang code (e.g., \"en-US\"):": "Skriv ny språkkode (f.eks. \"nb-NO\"):",
  "Choose up to six languages": "Velg opptil seks språk",
  "Select language {{number}}:": "Velg språk {{number}}:",
  "Manually enter language {{number}}:": "Skriv språk {{number}} selv:",
  "Really remove all language markup from the document?": "Vil du virkelig fjerne all språkmerking fra dokumentet?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Skriv en gyldig språkkode uten mellomrom. Eller trykk avbryt.",
  "langName.af": "Afrikaans",
  "langName.ak": "Akan",
  "langName.ar": "Arabisk",
  "langName.az": "Aserbajdsjansk",
  "langName.bg": "Bulgarsk",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengali",
  "langName.bo": "Tibetansk",
  "langName.bs": "Bosnisk",
  "langName.ca": "Katalansk",
  "langName.cs": "Tsjekkisk",
  "langName.cu": "Gammelbulgarsk",
  "langName.da": "Dansk",
  "langName.de": "Tysk",
  "langName.el": "Gresk",
  "langName.en": "Engelsk",
  "langName.en-au": "Engelsk (Australia)",
  "langName.en-gb": "Engelsk (England)",
  "langName.en-in": "Engelsk (India)",
  "langName.en-ie": "Engelsk (Irland)",
  "langName.en-tt": "Engelsk (Trinidad)",
  "langName.en-us": "Engelsk (USA)",
  "langName.en-za": "Engelsk (Sør-Afrika)",
  "langName.es": "Spansk",
  "langName.es-ar": "Spansk (Argentina)",
  "langName.es-cl": "Spansk (Chile)",
  "langName.es-co": "Spansk (Colombia)",
  "langName.es-mx": "Spansk (Mexico)",
  "langName.es-pe": "Spansk (Peru)",
  "langName.et": "Estisk",
  "langName.eu": "Baskisk",
  "langName.fa": "Persisk",
  "langName.fi": "Finsk",
  "langName.fr": "Fransk",
  "langName.fr-ca": "Fransk (Canada)",
  "langName.gl": "Galisisk",
  "langName.he": "Hebraisk",
  "langName.hi": "Hindi",
  "langName.hr": "Kroatisk",
  "langName.hu": "Ungarsk",
  "langName.id": "Indonesisk",
  "langName.it": "Italiensk",
  "langName.ja": "Japansk",
  "langName.kk": "Kasakhisk",
  "langName.kn": "Kannada",
  "langName.ko": "Koreansk",
  "langName.la": "Latin",
  "langName.lkt": "Lakota",
  "langName.mn": "Mongolsk",
  "langName.mr": "Marathi",
  "langName.nb": "Norsk bokmål",
  "langName.nl": "Nederlandsk",
  "langName.nl-be": "Nederlandsk (Belgia)",
  "langName.nn": "Norsk nynorsk",
  "langName.pl": "Polsk",
  "langName.ps": "Pashto",
  "langName.pt": "Portugisisk",
  "langName.pt-br": "Portugisisk (Brasil)",
  "langName.qu": "Quechua",
  "langName.ro": "Rumensk",
  "langName.ru": "Russisk",
  "langName.sa": "Sanskrit",
  "langName.sk-sk": "Slovakisk",
  "langName.sl": "Slovensk",
  "langName.sma": "Sørsamisk",
  "langName.sme": "Nordsamisk",
  "langName.smj": "Lulesamisk",
  "langName.sr": "Serbisk",
  "langName.sv": "Svensk",
  "langName.sw": "Swahili",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tadsjikisk",
  "langName.th": "Thai",
  "langName.tr": "Tyrkisk",
  "langName.ug": "Uigurisk",
  "langName.uk": "Ukrainsk",
  "langName.ur": "Urdu",
  "langName.uz": "Usbekisk",
  "langName.vi": "Vietnamesisk",
  "langName.wo": "Wolof",
  "langName.yi": "Jiddisk",
  "langName.yo": "Yoruba",
  "langName.yua": "Yucatec Maya",
  "langName.zh": "Kinesisk",
  "langName.zh-cn": "Kinesisk (Kina)",
  "langName.zh-hk": "Kinesisk (Hongkong)",
  "langName.zh-tw": "Kinesisk (Taiwan)",
  "langName.zh-hans": "Kinesisk (forenklet)",
  "langName.zh-hant": "Kinesisk (tradisjonell)",
  "langName.zu": "Zulu"
});