tinymce.addI18n('nl', {
  "-Language Not Set-": "-Taal niet ingesteld-",
  "Choose from list": "Kiezen uit lijst",
  "Choose languages": "Talen kiezen",
  "Choose up to six languages": "Kies maximaal zes talen",
  "Configure languages": "Talen configureren",
  "Current language:": "Huidige taal:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Voer een geldige taalcode in zonder spaties. Of druk op annuleren.",
  "Enter manually": "Handmatig invoeren",
  "Enter new lang code (e.g., \"en-US\"):": "Voer nieuwe taalcode in (bijv. \"en-US\"):",
  "Indicate current language": "Huidige taal aangeven",
  "Manually enter language {{number}}:": "Voer taal {{number}} handmatig in:",
  "New Language:": "Nieuwe taal:",
  "None": "Geen",
  "Other - Enter manually": "Anders - Handmatig invoeren",
  "Really remove all language markup from the document?": "Wilt u werkelijk alle taalmarkering uit het document verwijderen?",
  "Remove All lang markup": "Alle taalmarkering verwijderen",
  "Remove Language Markup": "Taalmarkering verwijderen",
  "Remove current lang value": "Huidige taalwaarde verwijderen",
  "Reveal lang markup": "Taalmarkering tonen",
  "Select language {{number}}:": "Selecteer taal {{number}}:",
  "Select the document's default language.": "Selecteer de standaardtaal van het document.",
  "Set default document language": "Standaard documenttaal instellen",
  "Set text language": "Teksttaal instellen",
  "langName.af": "Afrikaans",
  "langName.af-za": "Afrikaans",
  "langName.ak": "Akan",
  "langName.am": "Amhaars",
  "langName.ar": "Arabisch",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "Arabisch",
  "langName.az": "Azerbeidzjaans",
  "langName.be": "Belarussisch",
  "langName.bg": "Bulgaars",
  "langName.bg-bg": "Bulgaars",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengaals",
  "langName.bo": "Tibetaans",
  "langName.bs": "Bosnisch",
  "langName.ca": "Catalaans",
  "langName.cop": "Koptisch",
  "langName.cr": "Cree",
  "langName.cs": "Tsjechisch",
  "langName.cu": "Kerkslavisch",
  "langName.cy": "Welsh",
  "langName.da": "Deens",
  "langName.de": "Duits",
  "langName.de-at": "",
  "langName.de-ch": "",
  "langName.de-de": "Duits",
  "langName.dv": "Divehi",
  "langName.el": "Grieks",
  "langName.en": "Engels",
  "langName.en-au": "Engels (Australië)",
  "langName.en-ca": "",
  "langName.en-gb": "Engels (Verenigd Koninkrijk)",
  "langName.en-ie": "Engels (Ierland)",
  "langName.en-in": "Engels (India)",
  "langName.en-tt": "Engels (Trinidad)",
  "langName.en-us": "Engels",
  "langName.en-za": "Engels (Zuid-Afrika)",
  "langName.eo": "Esperanto",
  "langName.es": "Spaans",
  "langName.es-ar": "Spaans (Argentinië)",
  "langName.es-cl": "Spaans (Chili)",
  "langName.es-co": "Spaans (Colombia)",
  "langName.es-cr": "",
  "langName.es-es": "Spaans",
  "langName.es-mx": "Spaans (Mexico)",
  "langName.es-pe": "Spaans (Peru)",
  "langName.et": "Estisch",
  "langName.eu": "Baskisch",
  "langName.fa": "Perzisch",
  "langName.fa-af": "Dari",
  "langName.fa-ir": "Perzisch",
  "langName.ff": "Fulah",
  "langName.fi": "Fins",
  "langName.fi-fi": "Fins",
  "langName.fil": "Filipijns",
  "langName.fr": "Frans",
  "langName.fr-be": "",
  "langName.fr-ca": "Frans (Canada)",
  "langName.fr-ch": "",
  "langName.ga": "Iers",
  "langName.gl": "Galicisch",
  "langName.grc": "Oudgrieks",
  "langName.ha": "Hausa",
  "langName.he": "Hebreeuws",
  "langName.he-il": "Hebreeuws",
  "langName.hi": "Hindi",
  "langName.hr": "Kroatisch",
  "langName.hr-hr": "Kroatisch",
  "langName.ht": "Haïtiaans Creools",
  "langName.hu": "Hongaars",
  "langName.hu-hu": "Hongaars",
  "langName.hy": "Armeens",
  "langName.id": "Indonesisch",
  "langName.ig": "Igbo",
  "langName.is": "IJslands",
  "langName.it": "Italiaans",
  "langName.it-it": "Italiaans",
  "langName.iu": "Inuktitut",
  "langName.ja": "Japans",
  "langName.ja-jp": "Japans",
  "langName.ka": "Georgisch",
  "langName.kab": "Kabylisch",
  "langName.kk": "Kazachs",
  "langName.km": "Khmer",
  "langName.kn": "Kannada",
  "langName.ko": "Koreaans",
  "langName.ko-kr": "Koreaans",
  "langName.la": "Latijn",
  "langName.lkt": "Lakota",
  "langName.lo": "Laotiaans",
  "langName.lt": "Litouws",
  "langName.lv": "Lets",
  "langName.mi": "Maori",
  "langName.mn": "Mongools",
  "langName.mr": "Marathi",
  "langName.ms": "Maleis",
  "langName.mt": "Maltees",
  "langName.my": "Birmaans",
  "langName.nb": "Noors - Bokmål",
  "langName.nb-no": "Noors - Bokmål",
  "langName.ne": "Nepalees",
  "langName.nl": "Nederlands",
  "langName.nl-be": "Vlaams",
  "langName.nn": "Noors - Nynorsk",
  "langName.nv": "Navajo",
  "langName.ota": "Ottomaans-Turks",
  "langName.pa": "Punjabi",
  "langName.peo": "Oudperzisch",
  "langName.pl": "Pools",
  "langName.ps": "Pasjtoe",
  "langName.pt": "Portugees",
  "langName.pt-br": "Portugees",
  "langName.pt-pt": "Portugees",
  "langName.qu": "Quechua",
  "langName.ro": "Roemeens",
  "langName.ru": "Russisch",
  "langName.rw": "Kinyarwanda",
  "langName.sa": "Sanskriet",
  "langName.se": "Noord-Samisch",
  "langName.si": "Singalees",
  "langName.sk-sk": "Slowaaks",
  "langName.sl": "Sloveens",
  "langName.sl-si": "Sloveens",
  "langName.sma": "Zuid-Samisch",
  "langName.sme": "Noord-Samisch",
  "langName.smj": "Lule-Samisch",
  "langName.sn": "Shona",
  "langName.sr": "Servisch",
  "langName.sr-latn": "",
  "langName.sv": "Zweeds",
  "langName.sv-se": "Zweeds",
  "langName.sw": "Swahili",
  "langName.sw-ke": "Swahili",
  "langName.sw-tz": "Swahili",
  "langName.syc": "Klassiek Syrisch",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tadzjieks",
  "langName.th": "Thai",
  "langName.th-th": "Thai",
  "langName.tk": "Turkmeens",
  "langName.tl": "Tagalog",
  "langName.tr": "Turks",
  "langName.tr-tr": "Turks",
  "langName.tt": "Tataars",
  "langName.ug": "Oeigoers",
  "langName.uk": "Oekraïens",
  "langName.ur": "Urdu",
  "langName.uz": "Oezbeeks",
  "langName.vi": "Vietnamees",
  "langName.wo": "Wolof",
  "langName.xh": "Xhosa",
  "langName.yi": "Jiddisch",
  "langName.yo": "Yoruba",
  "langName.yua": "Yucateeks Maya",
  "langName.zh": "Chinees",
  "langName.zh-cn": "Chinees (China)",
  "langName.zh-hans": "Chinees vereenvoudigd",
  "langName.zh-hant": "Chinees traditioneel",
  "langName.zh-hk": "Chinees (Hong Kong)",
  "langName.zh-sg": "",
  "langName.zh-tw": "Chinees (Taiwan)",
  "langName.zu": "Zoeloe",
  "langName.zu-za": "Zoeloe"
});