tinymce.addI18n('nl', {
  "Current language:": "Huidige taal:",
  "Set text language": "Teksttaal instellen",
  "-Language Not Set-": "-Taal niet ingesteld-",
  "Choose languages": "Talen kiezen",
  "Remove Language Markup": "Taalmarkering verwijderen",
  "Remove current lang value": "Huidige taalwaarde verwijderen",
  "Remove All lang markup": "Alle taalmarkering verwijderen",
  "Configure languages": "Talen configureren",
  "Set default document language": "Standaard documenttaal instellen",
  "Reveal lang markup": "Taalmarkering tonen",
  "Indicate current language": "Huidige taal aangeven",
  "Select the document's default language.": "Selecteer de standaardtaal van het document.",
  "Choose from list": "Kiezen uit lijst",
  "Enter manually": "Handmatig invoeren",
  "None": "Geen",
  "Other - Enter manually": "Anders - Handmatig invoeren",
  "New Language:": "Nieuwe taal:",
  "Enter new lang code (e.g., \"en-US\"):": "Voer nieuwe taalcode in (bijv. \"en-US\"):",
  "Choose up to six languages": "Kies maximaal zes talen",
  "Select language {{number}}:": "Selecteer taal {{number}}:",
  "Manually enter language {{number}}:": "Voer taal {{number}} handmatig in:",
  "Really remove all language markup from the document?": "Wilt u werkelijk alle taalmarkering uit het document verwijderen?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Voer een geldige taalcode in zonder spaties. Of druk op annuleren.",
  "langName.af": "Afrikaans",
  "langName.ak": "Akan",
  "langName.ar": "Arabisch",
  "langName.az": "Azerbeidzjaans",
  "langName.bg": "Bulgaars",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengaals",
  "langName.bo": "Tibetaans",
  "langName.bs": "Bosnisch",
  "langName.ca": "Catalaans; Valenciaans",
  "langName.cs": "Tsjechisch",
  "langName.cu": "Oudkerkslawisch",
  "langName.da": "Deens",
  "langName.de": "Duits",
  "langName.el": "Grieks",
  "langName.en": "Engels",
  "langName.en-au": "Engels (Australië)",
  "langName.en-gb": "Engels (Verenigd Koninkrijk)",
  "langName.en-in": "Engels (India)",
  "langName.en-ie": "Engels (Ierland)",
  "langName.en-tt": "Engels (Trinidad)",
  "langName.en-us": "Engels (Verenigde Staten)",
  "langName.en-za": "Engels (Zuid-Afrika)",
  "langName.es": "Spaans",
  "langName.es-ar": "Spaans (Argentinië)",
  "langName.es-cl": "Spaans (Chili)",
  "langName.es-co": "Spaans (Colombia)",
  "langName.es-mx": "Spaans (Mexico)",
  "langName.es-pe": "Spaans (Peru)",
  "langName.et": "Estisch",
  "langName.eu": "Baskisch",
  "langName.fa": "Perzisch",
  "langName.fi": "Fins",
  "langName.fr": "Frans",
  "langName.fr-ca": "Frans (Canada)",
  "langName.gl": "Galicisch (Spanje)",
  "langName.he": "Hebreeuws",
  "langName.hi": "Hindi",
  "langName.hr": "Kroatisch",
  "langName.hu": "Hongaars",
  "langName.id": "Indonesisch",
  "langName.it": "Italiaans",
  "langName.ja": "Japans",
  "langName.kk": "Kazachs",
  "langName.kn": "Kannada",
  "langName.ko": "Koreaans",
  "langName.la": "Latijn",
  "langName.lkt": "Lakota",
  "langName.mn": "Mongools",
  "langName.mr": "Marathi",
  "langName.nb": "Noors bokmål",
  "langName.nl": "Nederlands",
  "langName.nl-be": "Nederlands (België)",
  "langName.nn": "Noors nynorsk",
  "langName.pl": "Pools",
  "langName.ps": "Pasjtoe",
  "langName.pt": "Portugees internationaal",
  "langName.pt-br": "Portugees Braziliaans",
  "langName.qu": "Quechua",
  "langName.ro": "Roemeens",
  "langName.ru": "Russisch",
  "langName.sa": "Sanskriet",
  "langName.sk-sk": "Slowaaks",
  "langName.sl": "Sloveens",
  "langName.sma": "Zuid-Samisch",
  "langName.sme": "Noord-Samisch",
  "langName.smj": "Lule-Samisch",
  "langName.sr": "Servisch",
  "langName.sv": "Zweeds",
  "langName.sw": "Swahili",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tadzjieks",
  "langName.th": "Thais",
  "langName.tr": "Turks",
  "langName.ug": "Oeigoers",
  "langName.uk": "Oekraïens",
  "langName.ur": "Urdu",
  "langName.uz": "Oezbeeks",
  "langName.vi": "Vietnamees",
  "langName.wo": "Wolof",
  "langName.yi": "Jiddisch",
  "langName.yo": "Yoruba",
  "langName.yua": "Yucateeks Maya",
  "langName.zh": "Chinees",
  "langName.zh-cn": "Chinees (China)",
  "langName.zh-hk": "Chinees (Hong Kong)",
  "langName.zh-tw": "Chinees (Taiwan)",
  "langName.zh-hans": "Chinees vereenvoudigd",
  "langName.zh-hant": "Chinees traditioneel",
  "langName.zu": "Zoeloe"
});