tinymce.addI18n('nn', {
  "-Language Not Set-": "-Språk ikkje sett-",
  "Choose from list": "Vel frå liste",
  "Choose languages": "Vel språk",
  "Choose up to six languages": "Vel opptil seks språk",
  "Configure languages": "Set opp språk",
  "Current language:": "Gjeldande språk:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Skriv inn ein gyldig språkkode utan mellomrom. Eller trykk avbryt.",
  "Enter manually": "Skriv inn manuelt",
  "Enter new lang code (e.g., \"en-US\"):": "Skriv inn ny språkkode (t.d. \"en-US\"):",
  "Indicate current language": "Vis gjeldande språk",
  "Manually enter language {{number}}:": "Skriv inn språk {{number}} manuelt:",
  "New Language:": "Nytt språk:",
  "None": "Ingen",
  "Other - Enter manually": "Anna - Skriv inn manuelt",
  "Really remove all language markup from the document?": "Vil du verkeleg fjerne all språkmerking frå dokumentet?",
  "Remove All lang markup": "Fjern all språkmerking",
  "Remove Language Markup": "Fjern språkmerking",
  "Remove current lang value": "Fjern gjeldande språkverdi",
  "Reveal lang markup": "Vis språkmerking",
  "Select language {{number}}:": "Vel språk {{number}}:",
  "Select the document's default language.": "Vel standardspråket til dokumentet.",
  "Set default document language": "Set standard dokumentspråk",
  "Set text language": "Set tekstspråk",
  "langName.af": "afrikaans",
  "langName.af-za": "afrikaans (Sør-Afrika)",
  "langName.ak": "akan",
  "langName.am": "amharisk",
  "langName.ar": "arabisk",
  "langName.ar-eg": "arabisk (Egypt)",
  "langName.ar-ma": "arabisk (Marokko)",
  "langName.ar-sa": "arabisk (Saudi-Arabia)",
  "langName.az": "aserbajdsjansk",
  "langName.be": "belarusisk",
  "langName.bg": "bulgarsk",
  "langName.bg-bg": "bulgarsk (Bulgaria)",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengali",
  "langName.bo": "tibetansk",
  "langName.bs": "bosnisk",
  "langName.ca": "katalansk",
  "langName.cop": "koptisk",
  "langName.cr": "cree",
  "langName.cs": "tsjekkisk",
  "langName.cu": "kyrkjeslavisk",
  "langName.cy": "walisisk",
  "langName.da": "dansk",
  "langName.de": "tysk",
  "langName.de-at": "tysk (Austerrike)",
  "langName.de-ch": "tysk (Sveits)",
  "langName.de-de": "tysk (Tyskland)",
  "langName.dv": "divehi",
  "langName.el": "gresk",
  "langName.en": "engelsk",
  "langName.en-au": "engelsk (Australia)",
  "langName.en-ca": "engelsk (Canada)",
  "langName.en-gb": "engelsk (Storbritannia)",
  "langName.en-ie": "engelsk (Irland)",
  "langName.en-in": "engelsk (India)",
  "langName.en-tt": "engelsk (Trinidad)",
  "langName.en-us": "engelsk (USA)",
  "langName.en-za": "engelsk (Sør-Afrika)",
  "langName.eo": "esperanto",
  "langName.es": "spansk",
  "langName.es-ar": "spansk (Argentina)",
  "langName.es-cl": "spansk (Chile)",
  "langName.es-co": "spansk (Colombia)",
  "langName.es-cr": "spansk (Costa Rica)",
  "langName.es-es": "spansk (Spania)",
  "langName.es-mx": "spansk (Mexico)",
  "langName.es-pe": "spansk (Peru)",
  "langName.et": "estisk",
  "langName.eu": "baskisk",
  "langName.fa": "persisk",
  "langName.fa-af": "dari",
  "langName.fa-ir": "persisk (Iran)",
  "langName.ff": "fulfulde",
  "langName.fi": "finsk",
  "langName.fi-fi": "finsk (Finland)",
  "langName.fil": "filipino",
  "langName.fr": "fransk",
  "langName.fr-be": "fransk (Belgia)",
  "langName.fr-ca": "fransk (Canada)",
  "langName.fr-ch": "fransk (Sveits)",
  "langName.ga": "irsk",
  "langName.gl": "galisisk",
  "langName.grc": "gammalgresk",
  "langName.ha": "hausa",
  "langName.he": "hebraisk",
  "langName.he-il": "hebraisk (Israel)",
  "langName.hi": "hindi",
  "langName.hr": "kroatisk",
  "langName.hr-hr": "kroatisk (Kroatia)",
  "langName.ht": "haitisk kreol",
  "langName.hu": "ungarsk",
  "langName.hu-hu": "ungarsk (Ungarn)",
  "langName.hy": "armensk",
  "langName.id": "indonesisk",
  "langName.ig": "ibo",
  "langName.is": "islandsk",
  "langName.it": "italiensk",
  "langName.it-it": "italiensk (Italia)",
  "langName.iu": "inuktitut",
  "langName.ja": "japansk",
  "langName.ja-jp": "japansk (Japan)",
  "langName.ka": "georgisk",
  "langName.kab": "kabylsk",
  "langName.kk": "kasakhisk",
  "langName.km": "khmer",
  "langName.kn": "kannada",
  "langName.ko": "koreansk",
  "langName.ko-kr": "koreansk (Sør-Korea)",
  "langName.la": "latin",
  "langName.lkt": "lakota",
  "langName.lo": "laotisk",
  "langName.lt": "litauisk",
  "langName.lv": "latvisk",
  "langName.mi": "maori",
  "langName.mn": "mongolsk",
  "langName.mr": "marathi",
  "langName.ms": "malayisk",
  "langName.mt": "maltesisk",
  "langName.my": "burmesisk",
  "langName.nb": "norsk bokmål",
  "langName.nb-no": "norsk bokmål (Noreg)",
  "langName.ne": "nepali",
  "langName.nl": "nederlandsk",
  "langName.nl-be": "flamsk",
  "langName.nn": "norsk nynorsk",
  "langName.nv": "navajo",
  "langName.ota": "ottomansk tyrkisk",
  "langName.pa": "panjabi",
  "langName.peo": "gammalpersisk",
  "langName.pl": "polsk",
  "langName.ps": "pashto",
  "langName.pt": "portugisisk",
  "langName.pt-br": "portugisisk (Brasil)",
  "langName.pt-pt": "portugisisk (Portugal)",
  "langName.qu": "quechua",
  "langName.ro": "rumensk",
  "langName.ru": "russisk",
  "langName.rw": "kinyarwanda",
  "langName.sa": "sanskrit",
  "langName.se": "nordsamisk",
  "langName.si": "singalesisk",
  "langName.sk": "slovakisk",
  "langName.sk-sk": "slovakisk (Slovakia)",
  "langName.sl": "slovensk",
  "langName.sl-si": "slovensk (Slovenia)",
  "langName.sma": "sørsamisk",
  "langName.sme": "nordsamisk",
  "langName.smj": "lulesamisk",
  "langName.sn": "shona",
  "langName.sr": "serbisk",
  "langName.sr-latn": "serbisk (latin)",
  "langName.sv": "svensk",
  "langName.sv-se": "svensk (Sverige)",
  "langName.sw": "swahili",
  "langName.sw-ke": "swahili (Kenya)",
  "langName.sw-tz": "swahili (Tanzania)",
  "langName.syc": "klassisk syrisk",
  "langName.ta": "tamil",
  "langName.te": "telugu",
  "langName.tg": "tadsjikisk",
  "langName.th": "thai",
  "langName.th-th": "thai (Thailand)",
  "langName.tk": "turkmensk",
  "langName.tl": "tagalog",
  "langName.tr": "tyrkisk",
  "langName.tr-tr": "tyrkisk (Tyrkia)",
  "langName.tt": "tatarisk",
  "langName.ug": "uigurisk",
  "langName.uk": "ukrainsk",
  "langName.ur": "urdu",
  "langName.uz": "usbekisk",
  "langName.vi": "vietnamesisk",
  "langName.wo": "wolof",
  "langName.xh": "xhosa",
  "langName.yi": "jiddisk",
  "langName.yo": "joruba",
  "langName.yua": "yukatekisk maya",
  "langName.zh": "kinesisk",
  "langName.zh-cn": "kinesisk (forenkla)",
  "langName.zh-hans": "kinesisk (forenkla)",
  "langName.zh-hant": "kinesisk (tradisjonell)",
  "langName.zh-hk": "kinesisk (Hong Kong)",
  "langName.zh-sg": "kinesisk (Singapore)",
  "langName.zh-tw": "kinesisk (tradisjonell, Taiwan)",
  "langName.zu": "zulu",
  "langName.zu-za": "zulu (Sør-Afrika)"
});