tinymce.addI18n("pl", {
  "Current language:": "Bieżący język:",
  "Set text language": "Ustaw język tekstu",
  "-Language Not Set-": "-Język nie ustawiony-",
  "Choose languages": "Wybierz języki",
  "Remove Language Markup": "Usuń znaczniki języka",
  "Remove current lang value": "Usuń bieżącą wartość języka",
  "Remove All lang markup": "Usuń wszystkie znaczniki języka",
  "Configure languages": "Konfiguruj języki",
  "Set default document language": "Ustaw domyślny język dokumentu",
  "Reveal lang markup": "Pokaż znaczniki języka",
  "Indicate current language": "Wskaż bieżący język",
  "Select the document's default language.": "Wybierz domyślny język dokumentu.",
  "Choose from list": "Wybierz z listy",
  "Enter manually": "Wprowadź ręcznie",
  "None": "Brak",
  "Other - Enter manually": "Inny - Wprowadź ręcznie",
  "New Language:": "Nowy język:",
  "Enter new lang code (e.g., \"en-US\"):": "Wprowadź nowy kod języka (np. \"en-US\"):",
  "Choose up to six languages": "Wybierz do sześciu języków",
  "Select language {{number}}:": "Wybierz język {{number}}:",
  "Manually enter language {{number}}:": "Wprowadź ręcznie język {{number}}:",
  "Really remove all language markup from the document?": "Czy na pewno usunąć wszystkie znaczniki języka z dokumentu?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Wprowadź prawidłowy kod języka bez spacji. Lub naciśnij anuluj.",
  "langName.af": "afrikaans",
  "langName.ak": "akan",
  "langName.ar": "arabski",
  "langName.az": "azerbejdżański",
  "langName.bg": "bułgarski",
  "langName.bho": "bhodżpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengalski",
  "langName.bo": "tybetański",
  "langName.bs": "bośniacki",
  "langName.ca": "kataloński; walencki",
  "langName.cs": "czeski",
  "langName.cu": "starobułgarski",
  "langName.da": "duński",
  "langName.de": "niemiecki",
  "langName.el": "grecki",
  "langName.en": "angielski",
  "langName.en-au": "angielski (Australia)",
  "langName.en-gb": "angielski (Wielka Brytania)",
  "langName.en-in": "angielski (Indie)",
  "langName.en-ie": "angielski (Irlandia)",
  "langName.en-tt": "angielski (Trynidad)",
  "langName.en-us": "angielski (Stany Zjednoczone)",
  "langName.en-za": "angielski (Afryka Południowa)",
  "langName.es": "hiszpański",
  "langName.es-ar": "hiszpański (Argentyna)",
  "langName.es-cl": "hiszpański (Chile)",
  "langName.es-co": "hiszpański (Kolumbia)",
  "langName.es-mx": "hiszpański (Meksyk)",
  "langName.es-pe": "hiszpański (Peru)",
  "langName.et": "estoński",
  "langName.eu": "baskijski",
  "langName.fa": "perski",
  "langName.fi": "fiński",
  "langName.fr": "francuski",
  "langName.fr-ca": "francuski (Kanada)",
  "langName.gl": "galicyjski (Hiszpania)",
  "langName.he": "hebrajski",
  "langName.hi": "hindi",
  "langName.hr": "chorwacki",
  "langName.hu": "węgierski",
  "langName.id": "indonezyjski",
  "langName.it": "włoski",
  "langName.ja": "japoński",
  "langName.kk": "kazaski",
  "langName.kn": "kannada",
  "langName.ko": "koreański",
  "langName.la": "łaciński",
  "langName.lkt": "lakota",
  "langName.mn": "mongolski",
  "langName.mr": "marathi",
  "langName.nb": "norweski bokmål",
  "langName.nl": "niderlandzki",
  "langName.nl-be": "niderlandzki (Belgia)",
  "langName.nn": "norweski nynorsk",
  "langName.pl": "polski",
  "langName.ps": "paszto",
  "langName.pt": "portugalski, międzynarodowy",
  "langName.pt-br": "portugalski, Brazylia",
  "langName.qu": "keczua",
  "langName.ro": "rumuński",
  "langName.ru": "rosyjski",
  "langName.sa": "sanskryt",
  "langName.sk-sk": "słowacki",
  "langName.sl": "słoweński",
  "langName.sma": "lapoński południowy",
  "langName.sme": "lapoński północny",
  "langName.smj": "lapoński lule",
  "langName.sr": "serbski",
  "langName.sv": "szwedzki",
  "langName.sw": "suahili",
  "langName.ta": "tamilski",
  "langName.te": "telugu",
  "langName.tg": "tadżycki",
  "langName.th": "tajski",
  "langName.tr": "turecki",
  "langName.ug": "ujgurski",
  "langName.uk": "ukraiński",
  "langName.ur": "urdu",
  "langName.uz": "uzbecki",
  "langName.vi": "wietnamski",
  "langName.wo": "wolof",
  "langName.yi": "jidysz",
  "langName.yo": "joruba",
  "langName.yua": "majański yukatański",
  "langName.zh": "chiński",
  "langName.zh-cn": "chiński (Chiny)",
  "langName.zh-hk": "chiński (Hongkong)",
  "langName.zh-tw": "chiński (Tajwan)",
  "langName.zh-hans": "chiński, uproszczony",
  "langName.zh-hant": "chiński, tradycyjny",
  "langName.zu": "zulu"
});