tinymce.addI18n('pl', {
  "-Language Not Set-": "-Język nie ustawiony-",
  "Choose from list": "Wybierz z listy",
  "Choose languages": "Wybierz języki",
  "Choose up to six languages": "Wybierz do sześciu języków",
  "Configure languages": "Konfiguruj języki",
  "Current language:": "Bieżący język:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Wprowadź prawidłowy kod języka bez spacji. Lub naciśnij anuluj.",
  "Enter manually": "Wprowadź ręcznie",
  "Enter new lang code (e.g., \"en-US\"):": "Wprowadź nowy kod języka (np. \"en-US\"):",
  "Indicate current language": "Wskaż bieżący język",
  "Manually enter language {{number}}:": "Wprowadź ręcznie język {{number}}:",
  "New Language:": "Nowy język:",
  "None": "Brak",
  "Other - Enter manually": "Inny - Wprowadź ręcznie",
  "Really remove all language markup from the document?": "Czy na pewno usunąć wszystkie znaczniki języka z dokumentu?",
  "Remove All lang markup": "Usuń wszystkie znaczniki języka",
  "Remove Language Markup": "Usuń znaczniki języka",
  "Remove current lang value": "Usuń bieżącą wartość języka",
  "Reveal lang markup": "Pokaż znaczniki języka",
  "Select language {{number}}:": "Wybierz język {{number}}:",
  "Select the document's default language.": "Wybierz domyślny język dokumentu.",
  "Set default document language": "Ustaw domyślny język dokumentu",
  "Set text language": "Ustaw język tekstu",
  "langName.af": "afrikaans",
  "langName.af-za": "afrikaans (Afryka Południowa)",
  "langName.ak": "akan",
  "langName.am": "amharski",
  "langName.ar": "arabski",
  "langName.ar-eg": "arabski egipski",
  "langName.ar-ma": "arabski marokański",
  "langName.ar-sa": "arabski (Arabia Saudyjska)",
  "langName.az": "azerbejdżański",
  "langName.be": "białoruski",
  "langName.bg": "bułgarski",
  "langName.bg-bg": "bułgarski (Bułgaria)",
  "langName.bho": "bhodżpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengalski",
  "langName.bo": "tybetański",
  "langName.bs": "bośniacki",
  "langName.ca": "kataloński",
  "langName.cop": "koptyjski",
  "langName.cr": "kri",
  "langName.cs": "czeski",
  "langName.cu": "cerkiewnosłowiański",
  "langName.cy": "walijski",
  "langName.da": "duński",
  "langName.de": "niemiecki",
  "langName.de-at": "niemiecki austriacki",
  "langName.de-ch": "wysokoniemiecki szwajcarski",
  "langName.de-de": "niemiecki (Niemcy)",
  "langName.dv": "malediwski",
  "langName.el": "grecki",
  "langName.en": "angielski",
  "langName.en-au": "angielski australijski",
  "langName.en-ca": "angielski kanadyjski",
  "langName.en-gb": "angielski brytyjski",
  "langName.en-ie": "angielski (Irlandia)",
  "langName.en-in": "angielski (Indie)",
  "langName.en-tt": "angielski (Trynidad)",
  "langName.en-us": "angielski amerykański",
  "langName.en-za": "angielski (Afryka Południowa)",
  "langName.eo": "esperanto",
  "langName.es": "hiszpański",
  "langName.es-ar": "hiszpański (Argentyna)",
  "langName.es-cl": "hiszpański (Chile)",
  "langName.es-co": "hiszpański (Kolumbia)",
  "langName.es-cr": "hiszpański (Kostaryka)",
  "langName.es-es": "europejski hiszpański",
  "langName.es-mx": "meksykański hiszpański",
  "langName.es-pe": "hiszpański (Peru)",
  "langName.et": "estoński",
  "langName.eu": "baskijski",
  "langName.fa": "perski",
  "langName.fa-af": "dari",
  "langName.fa-ir": "perski (Iran)",
  "langName.ff": "fulani",
  "langName.fi": "fiński",
  "langName.fi-fi": "fiński (Finlandia)",
  "langName.fil": "filipiński",
  "langName.fr": "francuski",
  "langName.fr-be": "francuski belgijski",
  "langName.fr-ca": "francuski kanadyjski",
  "langName.fr-ch": "francuski szwajcarski",
  "langName.ga": "irlandzki",
  "langName.gl": "galicyjski",
  "langName.grc": "starogrecki",
  "langName.ha": "hausa",
  "langName.he": "hebrajski",
  "langName.he-il": "hebrajski (Izrael)",
  "langName.hi": "hindi",
  "langName.hr": "chorwacki",
  "langName.hr-hr": "chorwacki (Chorwacja)",
  "langName.ht": "kreolski haitański",
  "langName.hu": "węgierski",
  "langName.hu-hu": "węgierski (Węgry)",
  "langName.hy": "ormiański",
  "langName.id": "indonezyjski",
  "langName.ig": "igbo",
  "langName.is": "islandzki",
  "langName.it": "włoski",
  "langName.it-it": "włoski (Włochy)",
  "langName.iu": "inuktitut",
  "langName.ja": "japoński",
  "langName.ja-jp": "japoński (Japonia)",
  "langName.ka": "gruziński",
  "langName.kab": "kabylski",
  "langName.kk": "kazachski",
  "langName.km": "khmerski",
  "langName.kn": "kannada",
  "langName.ko": "koreański",
  "langName.ko-kr": "koreański (Korea Południowa)",
  "langName.la": "łaciński",
  "langName.lkt": "lakota",
  "langName.lo": "laotański",
  "langName.lt": "litewski",
  "langName.lv": "łotewski",
  "langName.mi": "maoryjski",
  "langName.mn": "mongolski",
  "langName.mr": "marathi",
  "langName.ms": "malajski",
  "langName.mt": "maltański",
  "langName.my": "birmański",
  "langName.nb": "norweski (bokmål)",
  "langName.nb-no": "norweski bokmål (Norwegia)",
  "langName.ne": "nepalski",
  "langName.nl": "niderlandzki",
  "langName.nl-be": "flamandzki",
  "langName.nn": "norweski (nynorsk)",
  "langName.nv": "nawaho",
  "langName.ota": "osmańsko-turecki",
  "langName.pa": "pendżabski",
  "langName.peo": "staroperski",
  "langName.pl": "polski",
  "langName.ps": "paszto",
  "langName.pt": "portugalski",
  "langName.pt-br": "brazylijski portugalski",
  "langName.pt-pt": "europejski portugalski",
  "langName.qu": "keczua",
  "langName.ro": "rumuński",
  "langName.ru": "rosyjski",
  "langName.rw": "kinya-ruanda",
  "langName.sa": "sanskryt",
  "langName.se": "północnolapoński",
  "langName.si": "syngaleski",
  "langName.sk-sk": "słowacki (Słowacja)",
  "langName.sl": "słoweński",
  "langName.sl-si": "słoweński (Słowenia)",
  "langName.sma": "południowolapoński",
  "langName.sme": "lapoński północny",
  "langName.smj": "lule lapoński",
  "langName.sn": "shona",
  "langName.sr": "serbski",
  "langName.sr-latn": "serbski (łaciński)",
  "langName.sv": "szwedzki",
  "langName.sv-se": "szwedzki (Szwecja)",
  "langName.sw": "suahili",
  "langName.sw-ke": "suahili (Kenia)",
  "langName.sw-tz": "suahili (Tanzania)",
  "langName.syc": "syriacki klasyczny",
  "langName.ta": "tamilski",
  "langName.te": "telugu",
  "langName.tg": "tadżycki",
  "langName.th": "tajski",
  "langName.th-th": "tajski (Tajlandia)",
  "langName.tk": "turkmeński",
  "langName.tl": "tagalski",
  "langName.tr": "turecki",
  "langName.tr-tr": "turecki (Turcja)",
  "langName.tt": "tatarski",
  "langName.ug": "ujgurski",
  "langName.uk": "ukraiński",
  "langName.ur": "urdu",
  "langName.uz": "uzbecki",
  "langName.vi": "wietnamski",
  "langName.wo": "wolof",
  "langName.xh": "khosa",
  "langName.yi": "jidysz",
  "langName.yo": "joruba",
  "langName.yua": "majański yukatański",
  "langName.zh": "chiński",
  "langName.zh-cn": "chiński uproszczony",
  "langName.zh-hans": "chiński uproszczony",
  "langName.zh-hant": "chiński tradycyjny",
  "langName.zh-hk": "chiński (Hongkong)",
  "langName.zh-sg": "chiński (Singapur)",
  "langName.zh-tw": "chiński tradycyjny (Tajwan)",
  "langName.zu": "zulu",
  "langName.zu-za": "zulu (Afryka Południowa)"
});