tinymce.addI18n('pt', {
  "Current language:": "Idioma atual:",
  "Set text language": "Definir idioma do texto",
  "-Language Not Set-": "-Idioma Não Definido-",
  "Choose languages": "Escolher idiomas",
  "Remove Language Markup": "Remover Marcação de Idioma",
  "Remove current lang value": "Remover valor de idioma atual",
  "Remove All lang markup": "Remover toda a marcação de idioma",
  "Configure languages": "Configurar idiomas",
  "Set default document language": "Definir idioma padrão do documento",
  "Reveal lang markup": "Revelar marcação de idioma",
  "Indicate current language": "Indicar idioma atual",
  "Select the document's default language.": "Seleccionar o idioma padrão do documento.",
  "Choose from list": "Escolher da lista",
  "Enter manually": "Inserir manualmente",
  "None": "Nenhum",
  "Other - Enter manually": "Outro - Inserir manualmente",
  "Current language:": "Idioma actual:",
  "New Language:": "Novo Idioma:",
  'Enter new lang code (e.g., "en-US"):': 'Inserir novo código de idioma (ex. "pt-PT"):',
  "Choose up to six languages": "Escolher até seis idiomas",
  "Select language {{number}}:": "Seleccionar idioma {{number}}:",
  "Manually enter language {{number}}:": "Inserir idioma {{number}} manualmente:",
  "Really remove all language markup from the document?": "Realmente remover toda a marcação de idioma do documento?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Inserir um código de idioma válido sem espaços. Ou pressionar cancelar.",
  "langName.af": 'Africâner',
  "langName.ak": 'Akan',
  "langName.ar": 'Árabe',
  "langName.az": 'Azerbaijano',
  "langName.bg": 'Búlgaro',
  "langName.bho": 'Bhojpuri',
  "langName.bm": 'Bambara',
  "langName.bn": 'Bengali',
  "langName.bo": 'Tibetano',
  "langName.bs": 'Bósnio',
  "langName.ca": 'Catalão; Valenciano',
  "langName.cs": 'Checo',
  "langName.cu": 'Búlgaro Antigo',
  "langName.da": 'Dinamarquês',
  "langName.de": 'Alemão',
  "langName.el": 'Grego',
  "langName.en": 'Inglês',
  "langName.en-au": 'Inglês (Austrália)',
  "langName.en-gb": 'Inglês (Reino Unido)',
  "langName.en-in": 'Inglês (Índia)',
  "langName.en-ie": 'Inglês (Irlanda)',
  "langName.en-tt": 'Inglês (Trindade)',
  "langName.en-us": 'Inglês (Estados Unidos)',
  "langName.en-za": 'Inglês (África do Sul)',
  "langName.es": 'Espanhol',
  "langName.es-ar": 'Espanhol (Argentina)',
  "langName.es-cl": 'Espanhol (Chile)',
  "langName.es-co": 'Espanhol (Colômbia)',
  "langName.es-mx": 'Espanhol (México)',
  "langName.es-pe": 'Espanhol (Peru)',
  "langName.et": 'Estónio',
  "langName.eu": 'Basco',
  "langName.fa": 'Persa',
  "langName.fi": 'Finlandês',
  "langName.fr": 'Francês',
  "langName.fr-ca": 'Francês (Canadá)',
  "langName.gl": 'Galego (Espanha)',
  "langName.he": 'Hebraico',
  "langName.hi": 'Hindi',
  "langName.hr": 'Croata',
  "langName.hu": 'Húngaro',
  "langName.id": 'Indonésio',
  "langName.it": 'Italiano',
  "langName.ja": 'Japonês',
  "langName.kk": 'Cazaque',
  "langName.kn": 'Kannada',
  "langName.ko": 'Coreano',
  "langName.la": 'Latim',
  "langName.lkt": 'Lakota',
  "langName.mn": 'Mongol',
  "langName.mr": 'Marathi',
  "langName.nb": 'Norueguês Bokmål',
  "langName.nl": 'Holandês',
  "langName.nl-be": 'Holandês (Bélgica)',
  "langName.nn": 'Norueguês Nynorsk',
  "langName.pl": 'Polaco',
  "langName.ps": 'Pachto',
  "langName.pt": 'Português Internacional',
  "langName.pt-br": 'Português (Brasil)',
  "langName.qu": 'Quechua',
  "langName.ro": 'Romeno',
  "langName.ru": 'Russo',
  "langName.sa": 'Sânscrito',
  "langName.sk-sk": 'Eslovaco',
  "langName.sl": 'Esloveno',
  "langName.sma": 'Sami do Sul',
  "langName.sme": 'Sami do Norte',
  "langName.smj": 'Sami de Lule',
  "langName.sr": 'Sérvio',
  "langName.sv": 'Sueco',
  "langName.sw": 'Suaíli',
  "langName.ta": 'Tamil',
  "langName.te": 'Telugu',
  "langName.tg": 'Tajique',
  "langName.th": 'Tailandês',
  "langName.tr": 'Turco',
  "langName.ug": 'Uigur',
  "langName.uk": 'Ucraniano',
  "langName.ur": 'Urdu',
  "langName.uz": 'Uzbeque',
  "langName.vi": 'Vietnamita',
  "langName.wo": 'Wolof',
  "langName.yi": 'Iídiche',
  "langName.yo": 'Ioruba',
  "langName.yua": 'Maia do Iucatão',
  "langName.zh": 'Chinês',
  "langName.zh-cn": 'Chinês (China)',
  "langName.zh-hk": 'Chinês (Hong Kong)',
  "langName.zh-tw": 'Chinês (Taiwan)',
  "langName.zh-hans": 'Chinês Simplificado',
  "langName.zh-hant": 'Chinês Tradicional',
  "langName.zu": 'Zulu'
});