tinymce.addI18n('pt_PT', {
  "-Language Not Set-": "-Idioma Não Definido-",
  "Choose from list": "Escolher da lista",
  "Choose languages": "Escolher idiomas",
  "Choose up to six languages": "Escolha até seis idiomas",
  "Configure languages": "Configurar idiomas",
  "Current language:": "Idioma actual:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Introduza um código de idioma válido sem espaços. Ou prima cancelar.",
  "Enter manually": "Introduzir manualmente",
  "Enter new lang code (e.g., \"en-US\"):": "Introduza o novo código de idioma (ex. \"pt-PT\"):",
  "Indicate current language": "Indicar idioma actual",
  "Manually enter language {{number}}:": "Introduzir manualmente o idioma {{number}}:",
  "New Language:": "Novo Idioma:",
  "None": "Nenhum",
  "Other - Enter manually": "Outro - Introduzir manualmente",
  "Really remove all language markup from the document?": "Deseja realmente remover toda a marcação de idioma do documento?",
  "Remove All lang markup": "Remover toda a marcação de idioma",
  "Remove Language Markup": "Remover Marcação de Idioma",
  "Remove current lang value": "Remover valor do idioma actual",
  "Reveal lang markup": "Revelar marcação de idioma",
  "Select language {{number}}:": "Seleccionar idioma {{number}}:",
  "Select the document's default language.": "Seleccione o idioma predefinido do documento.",
  "Set default document language": "Definir idioma predefinido do documento",
  "Set text language": "Definir idioma do texto",
  "langName.af": "africanês",
  "langName.af-za": "africanês (África do Sul)",
  "langName.ak": "akan",
  "langName.am": "amárico",
  "langName.ar": "árabe",
  "langName.ar-eg": "árabe (Egipto)",
  "langName.ar-ma": "árabe (Marrocos)",
  "langName.ar-sa": "árabe (Arábia Saudita)",
  "langName.az": "azerbaijano",
  "langName.be": "bielorrusso",
  "langName.bg": "búlgaro",
  "langName.bg-bg": "búlgaro (Bulgária)",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengalês",
  "langName.bo": "tibetano",
  "langName.bs": "bósnio",
  "langName.ca": "catalão",
  "langName.cop": "copta",
  "langName.cr": "cree",
  "langName.cs": "checo",
  "langName.cu": "eslavo eclesiástico",
  "langName.cy": "galês",
  "langName.da": "dinamarquês",
  "langName.de": "alemão",
  "langName.de-at": "alemão (Áustria)",
  "langName.de-ch": "alemão (Suíça)",
  "langName.de-de": "alemão (Alemanha)",
  "langName.dv": "divehi",
  "langName.el": "grego",
  "langName.en": "inglês",
  "langName.en-au": "inglês (Austrália)",
  "langName.en-ca": "inglês (Canadá)",
  "langName.en-gb": "inglês (Reino Unido)",
  "langName.en-ie": "inglês (Irlanda)",
  "langName.en-in": "inglês (Índia)",
  "langName.en-tt": "inglês (Trindade)",
  "langName.en-us": "inglês (Estados Unidos)",
  "langName.en-za": "inglês (África do Sul)",
  "langName.eo": "esperanto",
  "langName.es": "espanhol",
  "langName.es-ar": "espanhol (Argentina)",
  "langName.es-cl": "espanhol (Chile)",
  "langName.es-co": "espanhol (Colômbia)",
  "langName.es-cr": "espanhol (Costa Rica)",
  "langName.es-es": "espanhol (Espanha)",
  "langName.es-mx": "espanhol (México)",
  "langName.es-pe": "espanhol (Peru)",
  "langName.et": "estónio",
  "langName.eu": "basco",
  "langName.fa": "persa",
  "langName.fa-af": "dari",
  "langName.fa-ir": "persa (Irão)",
  "langName.ff": "fula",
  "langName.fi": "finlandês",
  "langName.fi-fi": "finlandês (Finlândia)",
  "langName.fil": "filipino",
  "langName.fr": "francês",
  "langName.fr-be": "francês (Bélgica)",
  "langName.fr-ca": "francês (Canadá)",
  "langName.fr-ch": "francês (Suíça)",
  "langName.ga": "irlandês",
  "langName.gl": "galego",
  "langName.grc": "grego (clássico)",
  "langName.ha": "haúça",
  "langName.he": "hebraico",
  "langName.he-il": "hebraico (Israel)",
  "langName.hi": "hindi",
  "langName.hr": "croata",
  "langName.hr-hr": "croata (Croácia)",
  "langName.ht": "crioulo haitiano",
  "langName.hu": "húngaro",
  "langName.hu-hu": "húngaro (Hungria)",
  "langName.hy": "arménio",
  "langName.id": "indonésio",
  "langName.ig": "igbo",
  "langName.is": "islandês",
  "langName.it": "italiano",
  "langName.it-it": "italiano (Itália)",
  "langName.iu": "inuktitut",
  "langName.ja": "japonês",
  "langName.ja-jp": "japonês (Japão)",
  "langName.ka": "georgiano",
  "langName.kab": "kabyle",
  "langName.kk": "cazaque",
  "langName.km": "khmer",
  "langName.kn": "canarim",
  "langName.ko": "coreano",
  "langName.ko-kr": "coreano (Coreia do Sul)",
  "langName.la": "latim",
  "langName.lkt": "lacota",
  "langName.lo": "laosiano",
  "langName.lt": "lituano",
  "langName.lv": "letão",
  "langName.mi": "maori",
  "langName.mn": "mongol",
  "langName.mr": "marata",
  "langName.ms": "malaio",
  "langName.mt": "maltês",
  "langName.my": "birmanês",
  "langName.nb": "norueguês (bokmål)",
  "langName.nb-no": "norueguês (bokmål, Noruega)",
  "langName.ne": "nepalês",
  "langName.nl": "neerlandês",
  "langName.nl-be": "neerlandês (Bélgica)",
  "langName.nn": "norueguês (nynorsk)",
  "langName.nv": "navajo",
  "langName.ota": "turco (otomano)",
  "langName.pa": "panjabi",
  "langName.peo": "persa (antigo)",
  "langName.pl": "polaco",
  "langName.ps": "pastó",
  "langName.pt": "português",
  "langName.pt-br": "português (Brasil)",
  "langName.pt-pt": "português (Portugal)",
  "langName.qu": "quíchua",
  "langName.ro": "romeno",
  "langName.ru": "russo",
  "langName.rw": "quiniaruanda",
  "langName.sa": "sânscrito",
  "langName.se": "sami (setentrional)",
  "langName.si": "cingalês",
  "langName.sk": "eslovaco",
  "langName.sk-sk": "eslovaco (Eslováquia)",
  "langName.sl": "esloveno",
  "langName.sl-si": "esloveno (Eslovénia)",
  "langName.sma": "sami (meridional)",
  "langName.sme": "sami (setentrional)",
  "langName.smj": "sami (lule)",
  "langName.sn": "shona",
  "langName.sr": "sérvio",
  "langName.sr-latn": "sérvio (latim)",
  "langName.sv": "sueco",
  "langName.sv-se": "sueco (Suécia)",
  "langName.sw": "suaíli",
  "langName.sw-ke": "suaíli (Quénia)",
  "langName.sw-tz": "suaíli (Tanzânia)",
  "langName.syc": "siríaco (clássico)",
  "langName.ta": "tâmil",
  "langName.te": "telugu",
  "langName.tg": "tajique",
  "langName.th": "tailandês",
  "langName.th-th": "tailandês (Tailândia)",
  "langName.tk": "turcomano",
  "langName.tl": "tagalo",
  "langName.tr": "turco",
  "langName.tr-tr": "turco (Turquia)",
  "langName.tt": "tatar",
  "langName.ug": "uigur",
  "langName.uk": "ucraniano",
  "langName.ur": "urdu",
  "langName.uz": "usbeque",
  "langName.vi": "vietnamita",
  "langName.wo": "uólofe",
  "langName.xh": "xosa",
  "langName.yi": "iídiche",
  "langName.yo": "ioruba",
  "langName.yua": "maia (iucateco)",
  "langName.zh": "chinês",
  "langName.zh-cn": "chinês (simplificado)",
  "langName.zh-hans": "chinês (simplificado)",
  "langName.zh-hant": "chinês (tradicional)",
  "langName.zh-hk": "chinês (Hong Kong)",
  "langName.zh-sg": "chinês (Singapura)",
  "langName.zh-tw": "chinês (tradicional, Taiwan)",
  "langName.zu": "zulu",
  "langName.zu-za": "zulu (África do Sul)"
});