tinymce.addI18n("ro", {
  "Current language:": "Limba curentă:",
  "Set text language": "Setează limba textului",
  "-Language Not Set-": "-Limba nu este setată-",
  "Choose languages": "Alege limbile",
  "Remove Language Markup": "Elimină marcajul de limbă",
  "Remove current lang value": "Elimină valoarea limbii curente",
  "Remove All lang markup": "Elimină tot marcajul de limbă",
  "Configure languages": "Configurează limbile",
  "Set default document language": "Setează limba implicită a documentului",
  "Reveal lang markup": "Afișează marcajul de limbă",
  "Indicate current language": "Indică limba curentă",
  "Select the document's default language.": "Selectează limba implicită a documentului.",
  "Choose from list": "Alege din listă",
  "Enter manually": "Introdu manual",
  "None": "Niciuna",
  "Other - Enter manually": "Altă limbă - Introdu manual",
  "New Language:": "Limbă nouă:",
  "Enter new lang code (e.g., \"en-US\"):": "Introdu codul noii limbi (ex. \"ro-RO\"):",
  "Choose up to six languages": "Alege până la șase limbi",
  "Select language {{number}}:": "Selectează limba {{number}}:",
  "Manually enter language {{number}}:": "Introdu manual limba {{number}}:",
  "Really remove all language markup from the document?": "Chiar vrei să elimini tot marcajul de limbă din document?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Introdu un cod de limbă valid fără spații. Sau apasă anulează.",
  "langName.af": "Afrikaans",
  "langName.ak": "Akan",
  "langName.ar": "Arabă",
  "langName.az": "Azeră",
  "langName.bg": "Bulgară",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengali",
  "langName.bo": "Tibetană",
  "langName.bs": "Bosniană",
  "langName.ca": "Catalană; Valenciană",
  "langName.cs": "Cehă",
  "langName.cu": "Bulgară veche",
  "langName.da": "Daneză",
  "langName.de": "Germană",
  "langName.el": "Greacă",
  "langName.en": "Engleză",
  "langName.en-au": "Engleză (Australia)",
  "langName.en-gb": "Engleză (Regatul Unit)",
  "langName.en-in": "Engleză (India)",
  "langName.en-ie": "Engleză (Irlanda)",
  "langName.en-tt": "Engleză (Trinidad)",
  "langName.en-us": "Engleză (Statele Unite)",
  "langName.en-za": "Engleză (Africa de Sud)",
  "langName.es": "Spaniolă",
  "langName.es-ar": "Spaniolă (Argentina)",
  "langName.es-cl": "Spaniolă (Chile)",
  "langName.es-co": "Spaniolă (Columbia)",
  "langName.es-mx": "Spaniolă (Mexic)",
  "langName.es-pe": "Spaniolă (Peru)",
  "langName.et": "Estoniană",
  "langName.eu": "Bască",
  "langName.fa": "Persană",
  "langName.fi": "Finlandeză",
  "langName.fr": "Franceză",
  "langName.fr-ca": "Franceză (Canada)",
  "langName.gl": "Galiciană (Spania)",
  "langName.he": "Ebraică",
  "langName.hi": "Hindi",
  "langName.hr": "Croată",
  "langName.hu": "Maghiară",
  "langName.id": "Indoneziană",
  "langName.it": "Italiană",
  "langName.ja": "Japoneză",
  "langName.kk": "Kazahă",
  "langName.kn": "Kannada",
  "langName.ko": "Coreeană",
  "langName.la": "Latină",
  "langName.lkt": "Lakota",
  "langName.mn": "Mongolă",
  "langName.mr": "Marathi",
  "langName.nb": "Norvegiană Bokmål",
  "langName.nl": "Olandeză",
  "langName.nl-be": "Olandeză (Belgia)",
  "langName.nn": "Norvegiană Nynorsk",
  "langName.pl": "Poloneză",
  "langName.ps": "Paștună",
  "langName.pt": "Portugheză, internațională",
  "langName.pt-br": "Portugheză (Brazilia)",
  "langName.qu": "Quechua",
  "langName.ro": "Română",
  "langName.ru": "Rusă",
  "langName.sa": "Sanscrită",
  "langName.sk-sk": "Slovacă",
  "langName.sl": "Slovenă",
  "langName.sma": "Sami de sud",
  "langName.sme": "Sami de nord",
  "langName.smj": "Sami Lule",
  "langName.sr": "Sârbă",
  "langName.sv": "Suedeză",
  "langName.sw": "Swahili",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tadjică",
  "langName.th": "Thailandeză",
  "langName.tr": "Turcă",
  "langName.ug": "Uigură",
  "langName.uk": "Ucraineană",
  "langName.ur": "Urdu",
  "langName.uz": "Uzbecă",
  "langName.vi": "Vietnameză",
  "langName.wo": "Wolof",
  "langName.yi": "Idiș",
  "langName.yo": "Yoruba",
  "langName.yua": "Maya Yucatec",
  "langName.zh": "Chineză",
  "langName.zh-cn": "Chineză (China)",
  "langName.zh-hk": "Chineză (Hong Kong)",
  "langName.zh-tw": "Chineză (Taiwan)",
  "langName.zh-hans": "Chineză simplificată",
  "langName.zh-hant": "Chineză tradițională",
  "langName.zu": "Zulu"
});