tinymce.addI18n('ro', {
  "-Language Not Set-": "-Limba nu este setată-",
  "Choose from list": "Alege din listă",
  "Choose languages": "Alege limbile",
  "Choose up to six languages": "Alege până la șase limbi",
  "Configure languages": "Configurează limbile",
  "Current language:": "Limba curentă:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Introdu un cod de limbă valid fără spații. Sau apasă anulează.",
  "Enter manually": "Introdu manual",
  "Enter new lang code (e.g., \"en-US\"):": "Introdu codul noii limbi (ex. \"ro-RO\"):",
  "Indicate current language": "Indică limba curentă",
  "Manually enter language {{number}}:": "Introdu manual limba {{number}}:",
  "New Language:": "Limbă nouă:",
  "None": "Niciuna",
  "Other - Enter manually": "Altă limbă - Introdu manual",
  "Really remove all language markup from the document?": "Chiar vrei să elimini tot marcajul de limbă din document?",
  "Remove All lang markup": "Elimină tot marcajul de limbă",
  "Remove Language Markup": "Elimină marcajul de limbă",
  "Remove current lang value": "Elimină valoarea limbii curente",
  "Reveal lang markup": "Afișează marcajul de limbă",
  "Select language {{number}}:": "Selectează limba {{number}}:",
  "Select the document's default language.": "Selectează limba implicită a documentului.",
  "Set default document language": "Setează limba implicită a documentului",
  "Set text language": "Setează limba textului",
  "langName.af": "afrikaans",
  "langName.af-za": "afrikaans (Africa de Sud)",
  "langName.ak": "akan",
  "langName.am": "amharică",
  "langName.ar": "arabă",
  "langName.ar-eg": "arabă (Egipt)",
  "langName.ar-ma": "arabă (Maroc)",
  "langName.ar-sa": "arabă (Arabia Saudită)",
  "langName.az": "azeră",
  "langName.be": "belarusă",
  "langName.bg": "bulgară",
  "langName.bg-bg": "bulgară (Bulgaria)",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengaleză",
  "langName.bo": "tibetană",
  "langName.bs": "bosniacă",
  "langName.ca": "catalană",
  "langName.cop": "coptă",
  "langName.cr": "cree",
  "langName.cs": "cehă",
  "langName.cu": "slavonă",
  "langName.cy": "galeză",
  "langName.da": "daneză",
  "langName.de": "germană",
  "langName.de-at": "germană (Austria)",
  "langName.de-ch": "germană (Elveția)",
  "langName.de-de": "germană (Germania)",
  "langName.dv": "divehi",
  "langName.el": "greacă",
  "langName.en": "engleză",
  "langName.en-au": "engleză (Australia)",
  "langName.en-ca": "engleză (Canada)",
  "langName.en-gb": "engleză (Regatul Unit)",
  "langName.en-ie": "engleză (Irlanda)",
  "langName.en-in": "engleză (India)",
  "langName.en-tt": "engleză (Trinidad)",
  "langName.en-us": "engleză (Statele Unite)",
  "langName.en-za": "engleză (Africa de Sud)",
  "langName.eo": "esperanto",
  "langName.es": "spaniolă",
  "langName.es-ar": "spaniolă (Argentina)",
  "langName.es-cl": "spaniolă (Chile)",
  "langName.es-co": "spaniolă (Columbia)",
  "langName.es-cr": "spaniolă (Costa Rica)",
  "langName.es-es": "spaniolă (Spania)",
  "langName.es-mx": "spaniolă (Mexic)",
  "langName.es-pe": "spaniolă (Peru)",
  "langName.et": "estonă",
  "langName.eu": "bască",
  "langName.fa": "persană",
  "langName.fa-af": "dari",
  "langName.fa-ir": "persană (Iran)",
  "langName.ff": "fulah",
  "langName.fi": "finlandeză",
  "langName.fi-fi": "finlandeză (Finlanda)",
  "langName.fil": "filipineză",
  "langName.fr": "franceză",
  "langName.fr-be": "franceză (Belgia)",
  "langName.fr-ca": "franceză (Canada)",
  "langName.fr-ch": "franceză (Elveția)",
  "langName.ga": "irlandeză",
  "langName.gl": "galiciană",
  "langName.grc": "greacă (veche)",
  "langName.ha": "hausa",
  "langName.he": "ebraică",
  "langName.he-il": "ebraică (Israel)",
  "langName.hi": "hindi",
  "langName.hr": "croată",
  "langName.hr-hr": "croată (Croația)",
  "langName.ht": "haitiană",
  "langName.hu": "maghiară",
  "langName.hu-hu": "maghiară (Ungaria)",
  "langName.hy": "armeană",
  "langName.id": "indoneziană",
  "langName.ig": "igbo",
  "langName.is": "islandeză",
  "langName.it": "italiană",
  "langName.it-it": "italiană (Italia)",
  "langName.iu": "inuktitut",
  "langName.ja": "japoneză",
  "langName.ja-jp": "japoneză (Japonia)",
  "langName.ka": "georgiană",
  "langName.kab": "kabyle",
  "langName.kk": "kazahă",
  "langName.km": "khmeră",
  "langName.kn": "kannada",
  "langName.ko": "coreeană",
  "langName.ko-kr": "coreeană (Coreea de Sud)",
  "langName.la": "latină",
  "langName.lkt": "lakota",
  "langName.lo": "laoțiană",
  "langName.lt": "lituaniană",
  "langName.lv": "letonă",
  "langName.mi": "maori",
  "langName.mn": "mongolă",
  "langName.mr": "marathi",
  "langName.ms": "malaeză",
  "langName.mt": "malteză",
  "langName.my": "birmană",
  "langName.nb": "norvegiană (bokmål)",
  "langName.nb-no": "norvegiană bokmål (Norvegia)",
  "langName.ne": "nepaleză",
  "langName.nl": "neerlandeză",
  "langName.nl-be": "flamandă",
  "langName.nn": "norvegiană (nynorsk)",
  "langName.nv": "navajo",
  "langName.ota": "turcă (otomană)",
  "langName.pa": "punjabi",
  "langName.peo": "persană (veche)",
  "langName.pl": "poloneză",
  "langName.ps": "paștună",
  "langName.pt": "portugheză",
  "langName.pt-br": "portugheză (Brazilia)",
  "langName.pt-pt": "portugheză (Portugalia)",
  "langName.qu": "quechua",
  "langName.ro": "română",
  "langName.ru": "rusă",
  "langName.rw": "kinyarwanda",
  "langName.sa": "sanscrită",
  "langName.se": "sami (nord)",
  "langName.si": "singhaleză",
  "langName.sk": "slovacă",
  "langName.sk-sk": "slovacă (Slovacia)",
  "langName.sl": "slovenă",
  "langName.sl-si": "slovenă (Slovenia)",
  "langName.sma": "sami (sud)",
  "langName.sme": "sami (nord)",
  "langName.smj": "sami (lule)",
  "langName.sn": "shona",
  "langName.sr": "sârbă",
  "langName.sr-latn": "sârbă (latină)",
  "langName.sv": "suedeză",
  "langName.sv-se": "suedeză (Suedia)",
  "langName.sw": "swahili",
  "langName.sw-ke": "swahili (Kenya)",
  "langName.sw-tz": "swahili (Tanzania)",
  "langName.syc": "siriacă (clasică)",
  "langName.ta": "tamilă",
  "langName.te": "telugu",
  "langName.tg": "tadjică",
  "langName.th": "thailandeză",
  "langName.th-th": "thailandeză (Thailanda)",
  "langName.tk": "turkmenă",
  "langName.tl": "tagalog",
  "langName.tr": "turcă",
  "langName.tr-tr": "turcă (Turcia)",
  "langName.tt": "tătară",
  "langName.ug": "uigură",
  "langName.uk": "ucraineană",
  "langName.ur": "urdu",
  "langName.uz": "uzbecă",
  "langName.vi": "vietnameză",
  "langName.wo": "wolof",
  "langName.xh": "xhosa",
  "langName.yi": "idiș",
  "langName.yo": "yoruba",
  "langName.yua": "maya (yucatecă)",
  "langName.zh": "chineză",
  "langName.zh-cn": "chineză (simplificată)",
  "langName.zh-hans": "chineză (simplificată)",
  "langName.zh-hant": "chineză (tradițională)",
  "langName.zh-hk": "chineză (Hong Kong)",
  "langName.zh-sg": "chineză (Singapore)",
  "langName.zh-tw": "chineză (tradițională)",
  "langName.zu": "zulu",
  "langName.zu-za": "zulu (Africa de Sud)"
});