tinymce.addI18n('ru_RU', {
  "-Language Not Set-": "-Язык не установлен-",
  "Choose from list": "Выбрать из списка",
  "Choose languages": "Выбрать языки",
  "Choose up to six languages": "Выберите до шести языков",
  "Configure languages": "Настроить языки",
  "Current language:": "Текущий язык:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Введите действительный код языка без пробелов. Или нажмите отмена.",
  "Enter manually": "Ввести вручную",
  "Enter new lang code (e.g., \"en-US\"):": "Введите новый код языка (например, \"ru-RU\"):",
  "Indicate current language": "Указать текущий язык",
  "Manually enter language {{number}}:": "Ввести язык {{number}} вручную:",
  "New Language:": "Новый язык:",
  "None": "Нет",
  "Other - Enter manually": "Другой - Ввести вручную",
  "Really remove all language markup from the document?": "Действительно удалить всю разметку языка из документа?",
  "Remove All lang markup": "Удалить всю разметку языка",
  "Remove Language Markup": "Удалить разметку языка",
  "Remove current lang value": "Удалить значение текущего языка",
  "Reveal lang markup": "Показать разметку языка",
  "Select language {{number}}:": "Выбрать язык {{number}}:",
  "Select the document's default language.": "Выберите язык документа по умолчанию.",
  "Set default document language": "Установить язык документа по умолчанию",
  "Set text language": "Установить язык текста",
  "langName.af": "африкаанс",
  "langName.af-za": "африкаанс (ЮАР)",
  "langName.ak": "акан",
  "langName.am": "амхарский",
  "langName.ar": "арабский",
  "langName.ar-eg": "арабский (Египет)",
  "langName.ar-ma": "арабский (Марокко)",
  "langName.ar-sa": "арабский (Саудовская Аравия)",
  "langName.az": "азербайджанский",
  "langName.be": "белорусский",
  "langName.bg": "болгарский",
  "langName.bg-bg": "болгарский (Болгария)",
  "langName.bho": "бходжпури",
  "langName.bm": "бамбара",
  "langName.bn": "бенгальский",
  "langName.bo": "тибетский",
  "langName.bs": "боснийский",
  "langName.ca": "каталанский",
  "langName.cop": "коптский",
  "langName.cr": "кри",
  "langName.cs": "чешский",
  "langName.cu": "церковнославянский",
  "langName.cy": "валлийский",
  "langName.da": "датский",
  "langName.de": "немецкий",
  "langName.de-at": "немецкий (Австрия)",
  "langName.de-ch": "немецкий (Швейцария)",
  "langName.de-de": "немецкий (Германия)",
  "langName.dv": "мальдивский",
  "langName.el": "греческий",
  "langName.en": "английский",
  "langName.en-au": "английский (Австралия)",
  "langName.en-ca": "английский (Канада)",
  "langName.en-gb": "английский (Великобритания)",
  "langName.en-ie": "английский (Ирландия)",
  "langName.en-in": "английский (Индия)",
  "langName.en-tt": "английский (Тринидад)",
  "langName.en-us": "английский (США)",
  "langName.en-za": "английский (ЮАР)",
  "langName.eo": "эсперанто",
  "langName.es": "испанский",
  "langName.es-ar": "испанский (Аргентина)",
  "langName.es-cl": "испанский (Чили)",
  "langName.es-co": "испанский (Колумбия)",
  "langName.es-cr": "испанский (Коста-Рика)",
  "langName.es-es": "испанский (Испания)",
  "langName.es-mx": "испанский (Мексика)",
  "langName.es-pe": "испанский (Перу)",
  "langName.et": "эстонский",
  "langName.eu": "баскский",
  "langName.fa": "персидский",
  "langName.fa-af": "дари",
  "langName.fa-ir": "персидский (Иран)",
  "langName.ff": "фулах",
  "langName.fi": "финский",
  "langName.fi-fi": "финский (Финляндия)",
  "langName.fil": "филиппинский",
  "langName.fr": "французский",
  "langName.fr-be": "французский (Бельгия)",
  "langName.fr-ca": "французский (Канада)",
  "langName.fr-ch": "французский (Швейцария)",
  "langName.ga": "ирландский",
  "langName.gl": "галисийский",
  "langName.grc": "древнегреческий",
  "langName.ha": "хауса",
  "langName.he": "иврит",
  "langName.he-il": "иврит (Израиль)",
  "langName.hi": "хинди",
  "langName.hr": "хорватский",
  "langName.hr-hr": "хорватский (Хорватия)",
  "langName.ht": "гаитянский креольский",
  "langName.hu": "венгерский",
  "langName.hu-hu": "венгерский (Венгрия)",
  "langName.hy": "армянский",
  "langName.id": "индонезийский",
  "langName.ig": "игбо",
  "langName.is": "исландский",
  "langName.it": "итальянский",
  "langName.it-it": "итальянский (Италия)",
  "langName.iu": "инуктитут",
  "langName.ja": "японский",
  "langName.ja-jp": "японский (Япония)",
  "langName.ka": "грузинский",
  "langName.kab": "кабильский",
  "langName.kk": "казахский",
  "langName.km": "кхмерский",
  "langName.kn": "каннада",
  "langName.ko": "корейский",
  "langName.ko-kr": "корейский (Корея)",
  "langName.la": "латинский",
  "langName.lkt": "лакота",
  "langName.lo": "лаосский",
  "langName.lt": "литовский",
  "langName.lv": "латышский",
  "langName.mi": "маори",
  "langName.mn": "монгольский",
  "langName.mr": "маратхи",
  "langName.ms": "малайский",
  "langName.mt": "мальтийский",
  "langName.my": "бирманский",
  "langName.nb": "норвежский (букмол)",
  "langName.nb-no": "норвежский (букмол, Норвегия)",
  "langName.ne": "непальский",
  "langName.nl": "нидерландский",
  "langName.nl-be": "фламандский",
  "langName.nn": "норвежский (нюнорск)",
  "langName.nv": "навахо",
  "langName.ota": "турецкий (османский)",
  "langName.pa": "панджаби",
  "langName.peo": "древнеперсидский",
  "langName.pl": "польский",
  "langName.ps": "пушту",
  "langName.pt": "португальский",
  "langName.pt-br": "португальский (Бразилия)",
  "langName.pt-pt": "португальский (Португалия)",
  "langName.qu": "кечуа",
  "langName.ro": "румынский",
  "langName.ru": "русский",
  "langName.rw": "киньяруанда",
  "langName.sa": "санскрит",
  "langName.se": "саамский (северный)",
  "langName.si": "сингальский",
  "langName.sk": "словацкий",
  "langName.sk-sk": "словацкий (Словакия)",
  "langName.sl": "словенский",
  "langName.sl-si": "словенский (Словения)",
  "langName.sma": "саамский (южный)",
  "langName.sme": "саамский (северный)",
  "langName.smj": "саамский (луле)",
  "langName.sn": "шона",
  "langName.sr": "сербский",
  "langName.sr-latn": "сербский (латиница)",
  "langName.sv": "шведский",
  "langName.sv-se": "шведский (Швеция)",
  "langName.sw": "суахили",
  "langName.sw-ke": "суахили (Кения)",
  "langName.sw-tz": "суахили (Танзания)",
  "langName.syc": "сирийский (классический)",
  "langName.ta": "тамильский",
  "langName.te": "телугу",
  "langName.tg": "таджикский",
  "langName.th": "тайский",
  "langName.th-th": "тайский (Таиланд)",
  "langName.tk": "туркменский",
  "langName.tl": "тагалог",
  "langName.tr": "турецкий",
  "langName.tr-tr": "турецкий (Турция)",
  "langName.tt": "татарский",
  "langName.ug": "уйгурский",
  "langName.uk": "украинский",
  "langName.ur": "урду",
  "langName.uz": "узбекский",
  "langName.vi": "вьетнамский",
  "langName.wo": "волоф",
  "langName.xh": "коса",
  "langName.yi": "идиш",
  "langName.yo": "йоруба",
  "langName.yua": "майя (юкатекский)",
  "langName.zh": "китайский",
  "langName.zh-cn": "китайский (упрощенный)",
  "langName.zh-hans": "китайский (упрощенный)",
  "langName.zh-hant": "китайский (традиционный)",
  "langName.zh-hk": "китайский (Гонконг)",
  "langName.zh-sg": "китайский (Сингапур)",
  "langName.zh-tw": "китайский (традиционный)",
  "langName.zu": "зулу",
  "langName.zu-za": "зулу (ЮАР)"
});