tinymce.addI18n("ru_RU", {
  "Current language:": "Текущий язык:",
  "Set text language": "Установить язык текста",
  "-Language Not Set-": "-Язык не установлен-",
  "Choose languages": "Выбрать языки",
  "Remove Language Markup": "Удалить разметку языка",
  "Remove current lang value": "Удалить значение текущего языка",
  "Remove All lang markup": "Удалить всю разметку языка",
  "Configure languages": "Настроить языки",
  "Set default document language": "Установить язык документа по умолчанию",
  "Reveal lang markup": "Показать разметку языка",
  "Indicate current language": "Указать текущий язык",
  "Select the document's default language.": "Выберите язык документа по умолчанию.",
  "Choose from list": "Выбрать из списка",
  "Enter manually": "Ввести вручную",
  "None": "Нет",
  "Other - Enter manually": "Другой - Ввести вручную",
  "New Language:": "Новый язык:",
  "Enter new lang code (e.g., \"en-US\"):": "Введите новый код языка (например, \"ru-RU\"):",
  "Choose up to six languages": "Выберите до шести языков",
  "Select language {{number}}:": "Выбрать язык {{number}}:",
  "Manually enter language {{number}}:": "Ввести язык {{number}} вручную:",
  "Really remove all language markup from the document?": "Действительно удалить всю разметку языка из документа?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Введите действительный код языка без пробелов. Или нажмите отмена.",
  "langName.af": "Африкаанс",
  "langName.ak": "Акан",
  "langName.ar": "Арабский",
  "langName.az": "Азербайджанский",
  "langName.bg": "Болгарский",
  "langName.bho": "Бходжпури",
  "langName.bm": "Бамбара",
  "langName.bn": "Бенгальский",
  "langName.bo": "Тибетский",
  "langName.bs": "Боснийский",
  "langName.ca": "Каталанский; Валенсийский",
  "langName.cs": "Чешский",
  "langName.cu": "Старославянский",
  "langName.da": "Датский",
  "langName.de": "Немецкий",
  "langName.el": "Греческий",
  "langName.en": "Английский",
  "langName.en-au": "Английский (Австралия)",
  "langName.en-gb": "Английский (Великобритания)",
  "langName.en-in": "Английский (Индия)",
  "langName.en-ie": "Английский (Ирландия)",
  "langName.en-tt": "Английский (Тринидад)",
  "langName.en-us": "Английский (США)",
  "langName.en-za": "Английский (ЮАР)",
  "langName.es": "Испанский",
  "langName.es-ar": "Испанский (Аргентина)",
  "langName.es-cl": "Испанский (Чили)",
  "langName.es-co": "Испанский (Колумбия)",
  "langName.es-mx": "Испанский (Мексика)",
  "langName.es-pe": "Испанский (Перу)",
  "langName.et": "Эстонский",
  "langName.eu": "Баскский",
  "langName.fa": "Персидский",
  "langName.fi": "Финский",
  "langName.fr": "Французский",
  "langName.fr-ca": "Французский (Канада)",
  "langName.gl": "Галисийский (Испания)",
  "langName.he": "Иврит",
  "langName.hi": "Хинди",
  "langName.hr": "Хорватский",
  "langName.hu": "Венгерский",
  "langName.id": "Индонезийский",
  "langName.it": "Итальянский",
  "langName.ja": "Японский",
  "langName.kk": "Казахский",
  "langName.kn": "Каннада",
  "langName.ko": "Корейский",
  "langName.la": "Латинский",
  "langName.lkt": "Лакота",
  "langName.mn": "Монгольский",
  "langName.mr": "Маратхи",
  "langName.nb": "Норвежский букмол",
  "langName.nl": "Нидерландский",
  "langName.nl-be": "Нидерландский (Бельгия)",
  "langName.nn": "Норвежский нюнорск",
  "langName.pl": "Польский",
  "langName.ps": "Пушту",
  "langName.pt": "Португальский международный",
  "langName.pt-br": "Португальский (Бразилия)",
  "langName.qu": "Кечуа",
  "langName.ro": "Румынский",
  "langName.ru": "Русский",
  "langName.sa": "Санскрит",
  "langName.sk-sk": "Словацкий",
  "langName.sl": "Словенский",
  "langName.sma": "Южносаамский",
  "langName.sme": "Северносаамский",
  "langName.smj": "Луле-саамский",
  "langName.sr": "Сербский",
  "langName.sv": "Шведский",
  "langName.sw": "Суахили",
  "langName.ta": "Тамильский",
  "langName.te": "Телугу",
  "langName.tg": "Таджикский",
  "langName.th": "Тайский",
  "langName.tr": "Турецкий",
  "langName.ug": "Уйгурский",
  "langName.uk": "Украинский",
  "langName.ur": "Урду",
  "langName.uz": "Узбекский",
  "langName.vi": "Вьетнамский",
  "langName.wo": "Волоф",
  "langName.yi": "Идиш",
  "langName.yo": "Йоруба",
  "langName.yua": "Юкатекский майя",
  "langName.zh": "Китайский",
  "langName.zh-cn": "Китайский (Китай)",
  "langName.zh-hk": "Китайский (Гонконг)",
  "langName.zh-tw": "Китайский (Тайвань)",
  "langName.zh-hans": "Китайский упрощённый",
  "langName.zh-hant": "Китайский традиционный",
  "langName.zu": "Зулусский"
});