tinymce.addI18n('sl', {
  "-Language Not Set-": "-Jezik ni nastavljen-",
  "Choose from list": "Izberi s seznama",
  "Choose languages": "Izberi jezike",
  "Choose up to six languages": "Izberi do šest jezikov",
  "Configure languages": "Konfiguriraj jezike",
  "Current language:": "Trenutni jezik:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Vnesi veljavno kodo jezika brez presledkov. Ali pritisni prekliči.",
  "Enter manually": "Vnesi ročno",
  "Enter new lang code (e.g., \"en-US\"):": "Vnesi novo kodo jezika (npr. \"en-US\"):",
  "Indicate current language": "Označi trenutni jezik",
  "Manually enter language {{number}}:": "Ročno vnesi jezik {{number}}:",
  "New Language:": "Nov jezik:",
  "None": "Brez",
  "Other - Enter manually": "Drugo - Vnesi ročno",
  "Really remove all language markup from the document?": "Res odstrani vse označevanje jezika iz dokumenta?",
  "Remove All lang markup": "Odstrani vse označevanje jezika",
  "Remove Language Markup": "Odstrani označevanje jezika",
  "Remove current lang value": "Odstrani trenutno vrednost jezika",
  "Reveal lang markup": "Prikaži označevanje jezika",
  "Select language {{number}}:": "Izberi jezik {{number}}:",
  "Select the document's default language.": "Izberi privzeti jezik dokumenta.",
  "Set default document language": "Nastavi privzeti jezik dokumenta",
  "Set text language": "Nastavi jezik besedila",
  "langName.af": "afrikanščina",
  "langName.af-za": "afrikanščina (Južna Afrika)",
  "langName.ak": "akanščina",
  "langName.am": "amharščina",
  "langName.ar": "arabščina",
  "langName.ar-eg": "egipčanska arabščina",
  "langName.ar-ma": "maroška arabščina",
  "langName.ar-sa": "arabščina (Savdska Arabija)",
  "langName.az": "azerbajdžanščina",
  "langName.be": "beloruščina",
  "langName.bg": "bolgarščina",
  "langName.bg-bg": "bolgarščina (Bolgarija)",
  "langName.bho": "bodžpuri",
  "langName.bm": "bambarščina",
  "langName.bn": "bengalščina",
  "langName.bo": "tibetanščina",
  "langName.bs": "bosanščina",
  "langName.ca": "katalonščina",
  "langName.cop": "koptščina",
  "langName.cr": "krijščina",
  "langName.cs": "češčina",
  "langName.cu": "stara cerkvena slovanščina",
  "langName.cy": "valižanščina",
  "langName.da": "danščina",
  "langName.de": "nemščina",
  "langName.de-at": "avstrijska nemščina",
  "langName.de-ch": "švicarska visoka nemščina",
  "langName.de-de": "nemščina (Nemčija)",
  "langName.dv": "diveščina",
  "langName.el": "grščina",
  "langName.en": "angleščina",
  "langName.en-au": "avstralska angleščina",
  "langName.en-ca": "kanadska angleščina",
  "langName.en-gb": "britanska angleščina",
  "langName.en-ie": "angleščina (Irska)",
  "langName.en-in": "angleščina (Indija)",
  "langName.en-tt": "angleščina (Trinidad)",
  "langName.en-us": "ameriška angleščina",
  "langName.en-za": "angleščina (Južna Afrika)",
  "langName.eo": "esperanto",
  "langName.es": "španščina",
  "langName.es-ar": "španščina (Argentina)",
  "langName.es-cl": "španščina (Čile)",
  "langName.es-co": "španščina (Kolumbija)",
  "langName.es-cr": "španščina (Kostarika)",
  "langName.es-es": "evropska španščina",
  "langName.es-mx": "mehiška španščina",
  "langName.es-pe": "španščina (Peru)",
  "langName.et": "estonščina",
  "langName.eu": "baskovščina",
  "langName.fa": "perzijščina",
  "langName.fa-af": "darijščina",
  "langName.fa-ir": "perzijščina (Iran)",
  "langName.ff": "fulščina",
  "langName.fi": "finščina",
  "langName.fi-fi": "finščina (Finska)",
  "langName.fil": "filipinščina",
  "langName.fr": "francoščina",
  "langName.fr-be": "belgijska francoščina",
  "langName.fr-ca": "kanadska francoščina",
  "langName.fr-ch": "švicarska francoščina",
  "langName.ga": "irščina",
  "langName.gl": "galicijščina",
  "langName.grc": "stara grščina",
  "langName.ha": "havščina",
  "langName.he": "hebrejščina",
  "langName.he-il": "hebrejščina (Izrael)",
  "langName.hi": "hindijščina",
  "langName.hr": "hrvaščina",
  "langName.hr-hr": "hrvaščina (Hrvaška)",
  "langName.ht": "haitijska kreolščina",
  "langName.hu": "madžarščina",
  "langName.hu-hu": "madžarščina (Madžarska)",
  "langName.hy": "armenščina",
  "langName.id": "indonezijščina",
  "langName.ig": "igboščina",
  "langName.is": "islandščina",
  "langName.it": "italijanščina",
  "langName.it-it": "italijanščina (Italija)",
  "langName.iu": "inuktitutščina",
  "langName.ja": "japonščina",
  "langName.ja-jp": "japonščina (Japonska)",
  "langName.ka": "gruzijščina",
  "langName.kab": "kabilščina",
  "langName.kk": "kazaščina",
  "langName.km": "kmerščina",
  "langName.kn": "kanareščina",
  "langName.ko": "korejščina",
  "langName.ko-kr": "korejščina (Južna Koreja)",
  "langName.la": "latinščina",
  "langName.lkt": "lakotščina",
  "langName.lo": "laoščina",
  "langName.lt": "litovščina",
  "langName.lv": "latvijščina",
  "langName.mi": "maorščina",
  "langName.mn": "mongolščina",
  "langName.mr": "maratščina",
  "langName.ms": "malajščina",
  "langName.mt": "malteščina",
  "langName.my": "burmanščina",
  "langName.nb": "knjižna norveščina",
  "langName.nb-no": "knjižna norveščina (Norveška)",
  "langName.ne": "nepalščina",
  "langName.nl": "nizozemščina",
  "langName.nl-be": "flamščina",
  "langName.nn": "novonorveščina",
  "langName.nv": "navajščina",
  "langName.ota": "otomanska turščina",
  "langName.pa": "pandžabščina",
  "langName.peo": "stara perzijščina",
  "langName.pl": "poljščina",
  "langName.ps": "paštunščina",
  "langName.pt": "portugalščina",
  "langName.pt-br": "brazilska portugalščina",
  "langName.pt-pt": "evropska portugalščina",
  "langName.qu": "kečuanščina",
  "langName.ro": "romunščina",
  "langName.ru": "ruščina",
  "langName.rw": "ruandščina",
  "langName.sa": "sanskrt",
  "langName.se": "severna samijščina",
  "langName.si": "sinhalščina",
  "langName.sk-sk": "slovaščina (Slovaška)",
  "langName.sl": "slovenščina",
  "langName.sl-si": "slovenščina (Slovenija)",
  "langName.sma": "južna samijščina",
  "langName.sme": "severna samijščina",
  "langName.smj": "luleška samijščina",
  "langName.sn": "šonščina",
  "langName.sr": "srbščina",
  "langName.sr-latn": "srbščina (latinica)",
  "langName.sv": "švedščina",
  "langName.sv-se": "švedščina (Švedska)",
  "langName.sw": "svahili",
  "langName.sw-ke": "svahili (Kenija)",
  "langName.sw-tz": "svahili (Tanzanija)",
  "langName.syc": "klasična sirščina",
  "langName.ta": "tamilščina",
  "langName.te": "telugijščina",
  "langName.tg": "tadžiščina",
  "langName.th": "tajščina",
  "langName.th-th": "tajščina (Tajska)",
  "langName.tk": "turkmenščina",
  "langName.tl": "tagalogščina",
  "langName.tr": "turščina",
  "langName.tr-tr": "turščina (Turčija)",
  "langName.tt": "tatarščina",
  "langName.ug": "ujgurščina",
  "langName.uk": "ukrajinščina",
  "langName.ur": "urdujščina",
  "langName.uz": "uzbeščina",
  "langName.vi": "vietnamščina",
  "langName.wo": "volofščina",
  "langName.xh": "koščina",
  "langName.yi": "jidiš",
  "langName.yo": "jorubščina",
  "langName.yua": "jukatanska majevščina",
  "langName.zh": "kitajščina",
  "langName.zh-cn": "poenostavljena kitajščina",
  "langName.zh-hans": "poenostavljena kitajščina",
  "langName.zh-hant": "tradicionalna kitajščina",
  "langName.zh-hk": "kitajščina (Hong Kong)",
  "langName.zh-sg": "kitajščina (Singapur)",
  "langName.zh-tw": "tradicionalna kitajščina",
  "langName.zu": "zulujščina",
  "langName.zu-za": "zulujščina (Južna Afrika)"
});