tinymce.addI18n('sl_SI', {
  "-Language Not Set-": "-Jezik ni nastavljen-",
  "Choose from list": "Izberi s seznama",
  "Choose languages": "Izberi jezike",
  "Choose up to six languages": "Izberi do šest jezikov",
  "Configure languages": "Konfiguriraj jezike",
  "Current language:": "Trenutni jezik:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Vnesi veljavno kodo jezika brez presledkov. Ali pritisni prekliči.",
  "Enter manually": "Vnesi ročno",
  "Enter new lang code (e.g., \"en-US\"):": "Vnesi novo kodo jezika (npr. \"en-US\"):",
  "Indicate current language": "Označi trenutni jezik",
  "Manually enter language {{number}}:": "Ročno vnesi jezik {{number}}:",
  "New Language:": "Nov jezik:",
  "None": "Brez",
  "Other - Enter manually": "Drugo - Vnesi ročno",
  "Really remove all language markup from the document?": "Res odstrani vse označevanje jezika iz dokumenta?",
  "Remove All lang markup": "Odstrani vse označevanje jezika",
  "Remove Language Markup": "Odstrani označevanje jezika",
  "Remove current lang value": "Odstrani trenutno vrednost jezika",
  "Reveal lang markup": "Prikaži označevanje jezika",
  "Select language {{number}}:": "Izberi jezik {{number}}:",
  "Select the document's default language.": "Izberi privzeti jezik dokumenta.",
  "Set default document language": "Nastavi privzeti jezik dokumenta",
  "Set text language": "Nastavi jezik besedila",
  "Afrikaans": "afrikanščina",
  "Afrikaans": "afrikanščina (Južna Afrika)",
  "Akan": "akanščina",
  "Amharic": "amharščina",
  "Arabic": "arabščina",
  "Arabic (Egypt)": "arabščina (Egipt)",
  "Arabic (Morocco)": "arabščina (Maroko)",
  "Arabic (Saudi Arabia)": "arabščina (Savdska Arabija)",
  "Azerbaijani": "azerbajdžanščina",
  "Belarusian": "beloruščina",
  "Bulgarian": "bolgarščina",
  "Bulgarian (Bulgaria)": "bolgarščina (Bolgarija)",
  "Bhojpuri": "bodžpuri",
  "Bambara": "bambarščina",
  "Bangla": "bengalščina",
  "Tibetan": "tibetanščina",
  "Bosnian": "bosanščina",
  "Catalan": "katalonščina",
  "Coptic": "koptščina",
  "Cree": "krijščina",
  "Czech": "češčina",
  "Church Slavic": "cerkvena slovanščina",
  "Welsh": "valižanščina",
  "Danish": "danščina",
  "German": "nemščina",
  "German (Austria)": "nemščina (Avstrija)",
  "German (Switzerland)": "nemščina (Švica)",
  "German (Germany)": "nemščina (Nemčija)",
  "Divehi": "diveščina",
  "Greek": "grščina",
  "English": "angleščina",
  "English (Australia)": "angleščina (Avstralija)",
  "English (Canada)": "angleščina (Kanada)",
  "English (United Kingdom)": "angleščina (Združeno kraljestvo)",
  "English (Ireland)": "angleščina (Irska)",
  "English (India)": "angleščina (Indija)",
  "English (Trinidad)": "angleščina (Trinidad)",
  "English (United States)": "angleščina (Združene države Amerike)",
  "English (South Africa)": "angleščina (Južna Afrika)",
  "Esperanto": "esperanto",
  "Spanish": "španščina",
  "Spanish (Argentina)": "španščina (Argentina)",
  "Spanish (Chile)": "španščina (Čile)",
  "Spanish (Colombia)": "španščina (Kolumbija)",
  "Spanish (Costa Rica)": "španščina (Kostarika)",
  "Spanish (Spain)": "španščina (Španija)",
  "Spanish (Mexico)": "španščina (Mehika)",
  "Spanish (Peru)": "španščina (Peru)",
  "Estonian": "estonščina",
  "Basque": "baskovščina",
  "Persian": "perzijščina",
  "Dari": "darijščina",
  "Persian (Iran)": "perzijščina (Iran)",
  "Fula": "fulščina",
  "Finnish": "finščina",
  "Finnish (Finland)": "finščina (Finska)",
  "Filipino": "filipinščina",
  "French": "francoščina",
  "French (Belgium)": "francoščina (Belgija)",
  "French (Canada)": "francoščina (Kanada)",
  "French (Switzerland)": "francoščina (Švica)",
  "Irish": "irščina",
  "Galician": "galicijščina",
  "Greek (Ancient)": "stara grščina",
  "Hausa": "havščina",
  "Hebrew": "hebrejščina",
  "Hebrew (Israel)": "hebrejščina (Izrael)",
  "Hindi": "hindijščina",
  "Croatian": "hrvaščina",
  "Croatian (Croatia)": "hrvaščina (Hrvaška)",
  "Haitian Creole": "haitijska kreolščina",
  "Hungarian": "madžarščina",
  "Hungarian (Hungary)": "madžarščina (Madžarska)",
  "Armenian": "armenščina",
  "Indonesian": "indonezijščina",
  "Igbo": "igboščina",
  "Icelandic": "islandščina",
  "Italian": "italijanščina",
  "Italian (Italy)": "italijanščina (Italija)",
  "Inuktitut": "inuktitutščina",
  "Japanese": "japonščina",
  "Japanese (Japan)": "japonščina (Japonska)",
  "Georgian": "gruzijščina",
  "Kabyle": "kabilščina",
  "Kazakh": "kazaščina",
  "Khmer": "kmerščina",
  "Kannada": "kanareščina",
  "Korean": "korejščina",
  "Korean (Korea)": "korejščina (Južna Koreja)",
  "Latin": "latinščina",
  "Lakota": "lakotščina",
  "Lao": "laoščina",
  "Lithuanian": "litovščina",
  "Latvian": "latvijščina",
  "Māori": "maorščina",
  "Mongolian": "mongolščina",
  "Marathi": "maratščina",
  "Malay": "malajščina",
  "Maltese": "malteščina",
  "Burmese": "burmanščina",
  "Norwegian (Bokmål)": "norveščina (bokmål)",
  "Norwegian (Bokmål, Norway)": "norveščina (bokmål, Norveška)",
  "Nepali": "nepalščina",
  "Dutch": "nizozemščina",
  "Flemish": "flamščina",
  "Norwegian (Nynorsk)": "norveščina (nynorsk)",
  "Navajo": "navajščina",
  "Turkish (Ottoman)": "turščina (otomanska)",
  "Punjabi": "pandžabščina",
  "Persian (Old)": "perzijščina (stara)",
  "Polish": "poljščina",
  "Pashto": "paštunščina",
  "Portuguese": "portugalščina",
  "Portuguese (Brazil)": "portugalščina (Brazilija)",
  "Portuguese (Portugal)": "portugalščina (Portugalska)",
  "Quechua": "kečuanščina",
  "Romanian": "romunščina",
  "Russian": "ruščina",
  "Kinyarwanda": "ruandščina",
  "Sanskrit": "sanskrt",
  "Sami (Northern)": "samijščina (severna)",
  "Sinhala": "sinhalščina",
  "Slovak": "slovaščina",
  "Slovak (Slovakia)": "slovaščina (Slovaška)",
  "Slovenian": "slovenščina",
  "Slovenian (Slovenia)": "slovenščina (Slovenija)",
  "Sami (Southern)": "samijščina (južna)",
  "Sami (Northern)": "samijščina (severna)",
  "Sami (Lule)": "samijščina (luleška)",
  "Shona": "šonščina",
  "Serbian": "srbščina",
  "Serbian (Latin)": "srbščina (latinica)",
  "Swedish": "švedščina",
  "Swedish (Sweden)": "švedščina (Švedska)",
  "Swahili": "svahili",
  "Swahili (Kenya)": "svahili (Kenija)",
  "Swahili (Tanzania)": "svahili (Tanzanija)",
  "Syriac (Classical)": "sirščina (klasična)",
  "Tamil": "tamilščina",
  "Telugu": "telugijščina",
  "Tajik": "tadžiščina",
  "Thai": "tajščina",
  "Thai (Thailand)": "tajščina (Tajska)",
  "Turkmen": "turkmenščina",
  "Tagalog": "tagalogščina",
  "Turkish": "turščina",
  "Turkish (Turkey)": "turščina (Turčija)",
  "Tatar": "tatarščina",
  "Uyghur": "ujgurščina",
  "Ukrainian": "ukrajinščina",
  "Urdu": "urdujščina",
  "Uzbek": "uzbeščina",
  "Vietnamese": "vietnamščina",
  "Wolof": "volofščina",
  "Xhosa": "koščina",
  "Yiddish": "jidiš",
  "Yoruba": "jorubščina",
  "Maya (Yucatec)": "majevščina (jukatanska)",
  "Chinese": "kitajščina",
  "Chinese (Simplified)": "kitajščina (poenostavljena)",
  "Chinese (Simplified)": "kitajščina (poenostavljena)",
  "Chinese (Traditional)": "kitajščina (tradicionalna)",
  "Chinese (Hong Kong)": "kitajščina (Hong Kong)",
  "Chinese (Singapore)": "kitajščina (Singapur)",
  "Chinese (Traditional)": "kitajščina (tradicionalna)",
  "Zulu": "zulujščina",
  "Zulu": "zulujščina (Južna Afrika)"
});