tinymce.addI18n("sl_SI", {
  "Current language:": "Trenutni jezik:",
  "Set text language": "Nastavi jezik besedila",
  "-Language Not Set-": "-Jezik ni nastavljen-",
  "Choose languages": "Izberi jezike",
  "Remove Language Markup": "Odstrani označevanje jezika",
  "Remove current lang value": "Odstrani trenutno vrednost jezika",
  "Remove All lang markup": "Odstrani vse označevanje jezika",
  "Configure languages": "Konfiguriraj jezike",
  "Set default document language": "Nastavi privzeti jezik dokumenta",
  "Reveal lang markup": "Prikaži označevanje jezika",
  "Indicate current language": "Označi trenutni jezik",
  "Select the document's default language.": "Izberi privzeti jezik dokumenta.",
  "Choose from list": "Izberi s seznama",
  "Enter manually": "Vnesi ročno",
  "None": "Brez",
  "Other - Enter manually": "Drugo - Vnesi ročno",
  "New Language:": "Nov jezik:",
  "Enter new lang code (e.g., \"en-US\"):": "Vnesi novo kodo jezika (npr. \"en-US\"):",
  "Choose up to six languages": "Izberi do šest jezikov",
  "Select language {{number}}:": "Izberi jezik {{number}}:",
  "Manually enter language {{number}}:": "Ročno vnesi jezik {{number}}:",
  "Really remove all language markup from the document?": "Res odstrani vse označevanje jezika iz dokumenta?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Vnesi veljavno kodo jezika brez presledkov. Ali pritisni prekliči.",
  "langName.af": "afrikanščina",
  "langName.ak": "akanščina",
  "langName.ar": "arabščina",
  "langName.az": "azerbajdžanščina",
  "langName.bg": "bolgarščina",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengalščina",
  "langName.bo": "tibetanščina",
  "langName.bs": "bosanščina",
  "langName.ca": "katalonščina; valencijščina",
  "langName.cs": "češčina",
  "langName.cu": "stara cerkvena slovanščina",
  "langName.da": "danščina",
  "langName.de": "nemščina",
  "langName.el": "grščina",
  "langName.en": "angleščina",
  "langName.en-au": "angleščina (Avstralija)",
  "langName.en-gb": "angleščina (Združeno kraljestvo)",
  "langName.en-in": "angleščina (Indija)",
  "langName.en-ie": "angleščina (Irska)",
  "langName.en-tt": "angleščina (Trinidad)",
  "langName.en-us": "angleščina (Združene države)",
  "langName.en-za": "angleščina (Južna Afrika)",
  "langName.es": "španščina",
  "langName.es-ar": "španščina (Argentina)",
  "langName.es-cl": "španščina (Čile)",
  "langName.es-co": "španščina (Kolumbija)",
  "langName.es-mx": "španščina (Mehika)",
  "langName.es-pe": "španščina (Peru)",
  "langName.et": "estonščina",
  "langName.eu": "baskovščina",
  "langName.fa": "perzijščina",
  "langName.fi": "finščina",
  "langName.fr": "francoščina",
  "langName.fr-ca": "francoščina (Kanada)",
  "langName.gl": "galicijščina (Španija)",
  "langName.he": "hebrejščina",
  "langName.hi": "hindujščina",
  "langName.hr": "hrvaščina",
  "langName.hu": "madžarščina",
  "langName.id": "indonezijščina",
  "langName.it": "italijanščina",
  "langName.ja": "japonščina",
  "langName.kk": "kazaščina",
  "langName.kn": "kanada",
  "langName.ko": "korejščina",
  "langName.la": "latinščina",
  "langName.lkt": "lakota",
  "langName.mn": "mongolščina",
  "langName.mr": "marati",
  "langName.nb": "norveščina bokmål",
  "langName.nl": "nizozemščina",
  "langName.nl-be": "nizozemščina (Belgija)",
  "langName.nn": "norveščina nynorsk",
  "langName.pl": "poljščina",
  "langName.ps": "paštunščina",
  "langName.pt": "portugalščina, mednarodna",
  "langName.pt-br": "portugalščina, Brazilija",
  "langName.qu": "kečuanščina",
  "langName.ro": "romunščina",
  "langName.ru": "ruščina",
  "langName.sa": "sanskrt",
  "langName.sk-sk": "slovaščina",
  "langName.sl": "slovenščina",
  "langName.sma": "južna samijščina",
  "langName.sme": "severna samijščina",
  "langName.smj": "lulska samijščina",
  "langName.sr": "srbščina",
  "langName.sv": "švedščina",
  "langName.sw": "svahili",
  "langName.ta": "tamilščina",
  "langName.te": "telugu",
  "langName.tg": "tadžiščina",
  "langName.th": "tajščina",
  "langName.tr": "turščina",
  "langName.ug": "ujgurščina",
  "langName.uk": "ukrajinščina",
  "langName.ur": "urdu",
  "langName.uz": "uzbeščina",
  "langName.vi": "vietnamščina",
  "langName.wo": "volof",
  "langName.yi": "jidiš",
  "langName.yo": "joruba",
  "langName.yua": "majevščina yukatanska",
  "langName.zh": "kitajščina",
  "langName.zh-cn": "kitajščina (Kitajska)",
  "langName.zh-hk": "kitajščina (Hong Kong)",
  "langName.zh-tw": "kitajščina (Tajvan)",
  "langName.zh-hans": "kitajščina, poenostavljena",
  "langName.zh-hant": "kitajščina, tradicionalna",
  "langName.zu": "zulujščina"
});