tinymce.addI18n("sr", {
  "Current language:": "Тренутни језик:",
  "Set text language": "Подеси језик текста",
  "-Language Not Set-": "-Језик није подешен-",
  "Choose languages": "Изабери језике",
  "Remove Language Markup": "Уклони означавање језика",
  "Remove current lang value": "Уклони вредност тренутног језика",
  "Remove All lang markup": "Уклони сво означавање језика",
  "Configure languages": "Подеси језике",
  "Set default document language": "Подеси подразумевани језик документа",
  "Reveal lang markup": "Прикажи означавање језика",
  "Indicate current language": "Означи тренутни језик",
  "Select the document's default language.": "Изаберите подразумевани језик документа.",
  "Choose from list": "Изабери са листе",
  "Enter manually": "Унеси ручно",
  "None": "Ниједан",
  "Other - Enter manually": "Остало - Унеси ручно",
  "New Language:": "Нови језик:",
  "Enter new lang code (e.g., \"en-US\"):": "Унесите нови код језика (нпр. \"sr-RS\"):",
  "Choose up to six languages": "Изаберите до шест језика",
  "Select language {{number}}:": "Изабери језик {{number}}:",
  "Manually enter language {{number}}:": "Ручно унеси језик {{number}}:",
  "Really remove all language markup from the document?": "Да ли заista желите да уклоните сво означавање језика из документа?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Унесите важећи код језика без размака. Или притисните откажи.",
  "langName.af": "Африканс",
  "langName.ak": "Акан",
  "langName.ar": "Арапски",
  "langName.az": "Азербејџански",
  "langName.bg": "Бугарски",
  "langName.bho": "Бхојпури",
  "langName.bm": "Бамбара",
  "langName.bn": "Бенгалски",
  "langName.bo": "Тибетански",
  "langName.bs": "Босански",
  "langName.ca": "Каталонски; Валенсијски",
  "langName.cs": "Чешки",
  "langName.cu": "Старословенски",
  "langName.da": "Дански",
  "langName.de": "Немачки",
  "langName.el": "Грчки",
  "langName.en": "Енглески",
  "langName.en-au": "Енглески (Аустралија)",
  "langName.en-gb": "Енглески (Велика Британија)",
  "langName.en-in": "Енглески (Индија)",
  "langName.en-ie": "Енглески (Ирска)",
  "langName.en-tt": "Енглески (Тринидад)",
  "langName.en-us": "Енглески (САД)",
  "langName.en-za": "Енглески (Јужна Африка)",
  "langName.es": "Шпански",
  "langName.es-ar": "Шпански (Аргентина)",
  "langName.es-cl": "Шпански (Чиле)",
  "langName.es-co": "Шпански (Колумбија)",
  "langName.es-mx": "Шпански (Мексико)",
  "langName.es-pe": "Шпански (Перу)",
  "langName.et": "Естонски",
  "langName.eu": "Баскијски",
  "langName.fa": "Персијски",
  "langName.fi": "Фински",
  "langName.fr": "Француски",
  "langName.fr-ca": "Француски (Канада)",
  "langName.gl": "Галицијски (Шпанија)",
  "langName.he": "Хебрејски",
  "langName.hi": "Хинди",
  "langName.hr": "Хрватски",
  "langName.hu": "Мађарски",
  "langName.id": "Индонежански",
  "langName.it": "Италијански",
  "langName.ja": "Јапански",
  "langName.kk": "Казашки",
  "langName.kn": "Канада",
  "langName.ko": "Корејски",
  "langName.la": "Латински",
  "langName.lkt": "Лакота",
  "langName.mn": "Монголски",
  "langName.mr": "Марати",
  "langName.nb": "Норвешки букмол",
  "langName.nl": "Холандски",
  "langName.nl-be": "Холандски (Белгија)",
  "langName.nn": "Норвешки нинорск",
  "langName.pl": "Пољски",
  "langName.ps": "Паштунски",
  "langName.pt": "Португалски, међународни",
  "langName.pt-br": "Португалски (Бразил)",
  "langName.qu": "Кечуа",
  "langName.ro": "Румунски",
  "langName.ru": "Руски",
  "langName.sa": "Санскрит",
  "langName.sk-sk": "Словачки",
  "langName.sl": "Словеначки",
  "langName.sma": "Јужни сами",
  "langName.sme": "Северни сами",
  "langName.smj": "Луле сами",
  "langName.sr": "Српски",
  "langName.sv": "Шведски",
  "langName.sw": "Свахили",
  "langName.ta": "Тамилски",
  "langName.te": "Телугу",
  "langName.tg": "Таџички",
  "langName.th": "Тајландски",
  "langName.tr": "Турски",
  "langName.ug": "Ујгурски",
  "langName.uk": "Украјински",
  "langName.ur": "Урду",
  "langName.uz": "Узбечки",
  "langName.vi": "Вијетнамски",
  "langName.wo": "Волоф",
  "langName.yi": "Јидиш",
  "langName.yo": "Јоруба",
  "langName.yua": "Јукатечки маја",
  "langName.zh": "Кинески",
  "langName.zh-cn": "Кинески (Кина)",
  "langName.zh-hk": "Кинески (Хонг Конг)",
  "langName.zh-tw": "Кинески (Тајван)",
  "langName.zh-hans": "Кинески, поједностављени",
  "langName.zh-hant": "Кинески, традиционални",
  "langName.zu": "Зулу"
});