tinymce.addI18n('sr', {
  "-Language Not Set-": "-Језик није подешен-",
  "Choose from list": "Изабери са листе",
  "Choose languages": "Изабери језике",
  "Choose up to six languages": "Изаберите до шест језика",
  "Configure languages": "Подеси језике",
  "Current language:": "Тренутни језик:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Унесите важећи код језика без размака. Или притисните откажи.",
  "Enter manually": "Унеси ручно",
  "Enter new lang code (e.g., \"en-US\"):": "Унесите нови код језика (нпр. \"sr-RS\"):",
  "Indicate current language": "Означи тренутни језик",
  "Manually enter language {{number}}:": "Ручно унеси језик {{number}}:",
  "New Language:": "Нови језик:",
  "None": "Ниједан",
  "Other - Enter manually": "Остало - Унеси ручно",
  "Really remove all language markup from the document?": "Да ли заиста желите да уклоните сво означавање језика из документа?",
  "Remove All lang markup": "Уклони сво означавање језика",
  "Remove Language Markup": "Уклони означавање језика",
  "Remove current lang value": "Уклони вредност тренутног језика",
  "Reveal lang markup": "Прикажи означавање језика",
  "Select language {{number}}:": "Изабери језик {{number}}:",
  "Select the document's default language.": "Изаберите подразумевани језик документа.",
  "Set default document language": "Подеси подразумевани језик документа",
  "Set text language": "Подеси језик текста",
  "langName.af": "африканс",
  "langName.af-za": "африканс (Јужна Африка)",
  "langName.ak": "акански",
  "langName.am": "амхарски",
  "langName.ar": "арапски",
  "langName.ar-eg": "арапски (Египат)",
  "langName.ar-ma": "арапски (Мароко)",
  "langName.ar-sa": "арапски (Саудијска Арабија)",
  "langName.az": "азербејџански",
  "langName.be": "белоруски",
  "langName.bg": "бугарски",
  "langName.bg-bg": "бугарски (Бугарска)",
  "langName.bho": "боџпури",
  "langName.bm": "бамбара",
  "langName.bn": "бенгалски",
  "langName.bo": "тибетански",
  "langName.bs": "босански",
  "langName.ca": "каталонски",
  "langName.cop": "коптски",
  "langName.cr": "кри",
  "langName.cs": "чешки",
  "langName.cu": "црквенословенски",
  "langName.cy": "велшки",
  "langName.da": "дански",
  "langName.de": "немачки",
  "langName.de-at": "немачки (Аустрија)",
  "langName.de-ch": "немачки (Швајцарска)",
  "langName.de-de": "немачки (Немачка)",
  "langName.dv": "малдивски",
  "langName.el": "грчки",
  "langName.en": "енглески",
  "langName.en-au": "енглески (Аустралија)",
  "langName.en-ca": "енглески (Канада)",
  "langName.en-gb": "енглески (Уједињено Краљевство)",
  "langName.en-ie": "енглески (Ирска)",
  "langName.en-in": "енглески (Индија)",
  "langName.en-tt": "енглески (Тринидад)",
  "langName.en-us": "енглески (Сједињене Државе)",
  "langName.en-za": "енглески (Јужна Африка)",
  "langName.eo": "есперанто",
  "langName.es": "шпански",
  "langName.es-ar": "шпански (Аргентина)",
  "langName.es-cl": "шпански (Чиле)",
  "langName.es-co": "шпански (Колумбија)",
  "langName.es-cr": "шпански (Костарика)",
  "langName.es-es": "шпански (Шпанија)",
  "langName.es-mx": "шпански (Мексико)",
  "langName.es-pe": "шпански (Перу)",
  "langName.et": "естонски",
  "langName.eu": "баскијски",
  "langName.fa": "персијски",
  "langName.fa-af": "дари",
  "langName.fa-ir": "персијски (Иран)",
  "langName.ff": "фула",
  "langName.fi": "фински",
  "langName.fi-fi": "фински (Финска)",
  "langName.fil": "филипински",
  "langName.fr": "француски",
  "langName.fr-be": "француски (Белгија)",
  "langName.fr-ca": "француски (Канада)",
  "langName.fr-ch": "француски (Швајцарска)",
  "langName.ga": "ирски",
  "langName.gl": "галицијски",
  "langName.grc": "старогрчки",
  "langName.ha": "хауса",
  "langName.he": "хебрејски",
  "langName.he-il": "хебрејски (Израел)",
  "langName.hi": "хинди",
  "langName.hr": "хрватски",
  "langName.hr-hr": "хрватски (Хрватска)",
  "langName.ht": "хаићански",
  "langName.hu": "мађарски",
  "langName.hu-hu": "мађарски (Мађарска)",
  "langName.hy": "јерменски",
  "langName.id": "индонежански",
  "langName.ig": "игбо",
  "langName.is": "исландски",
  "langName.it": "италијански",
  "langName.it-it": "италијански (Италија)",
  "langName.iu": "инуктитутски",
  "langName.ja": "јапански",
  "langName.ja-jp": "јапански (Јапан)",
  "langName.ka": "грузијски",
  "langName.kab": "кабиле",
  "langName.kk": "казашки",
  "langName.km": "кмерски",
  "langName.kn": "канада",
  "langName.ko": "корејски",
  "langName.ko-kr": "корејски (Јужна Кореја)",
  "langName.la": "латински",
  "langName.lkt": "лакота",
  "langName.lo": "лаоски",
  "langName.lt": "литвански",
  "langName.lv": "летонски",
  "langName.mi": "маорски",
  "langName.mn": "монголски",
  "langName.mr": "марати",
  "langName.ms": "малајски",
  "langName.mt": "малтешки",
  "langName.my": "бурмански",
  "langName.nb": "норвешки (букмол)",
  "langName.nb-no": "норвешки букмол (Норвешка)",
  "langName.ne": "непалски",
  "langName.nl": "холандски",
  "langName.nl-be": "фламански",
  "langName.nn": "норвешки (нинорск)",
  "langName.nv": "навахо",
  "langName.ota": "турски (османски)",
  "langName.pa": "пенџапски",
  "langName.peo": "персијски (стари)",
  "langName.pl": "пољски",
  "langName.ps": "паштунски",
  "langName.pt": "португалски",
  "langName.pt-br": "португалски (Бразил)",
  "langName.pt-pt": "португалски (Португалија)",
  "langName.qu": "кечуа",
  "langName.ro": "румунски",
  "langName.ru": "руски",
  "langName.rw": "кињаруанда",
  "langName.sa": "санскрит",
  "langName.se": "сами (северни)",
  "langName.si": "синхалешки",
  "langName.sk": "словачки",
  "langName.sk-sk": "словачки (Словачка)",
  "langName.sl": "словеначки",
  "langName.sl-si": "словеначки (Словенија)",
  "langName.sma": "сами (јужни)",
  "langName.sme": "сами (северни)",
  "langName.smj": "сами (луле)",
  "langName.sn": "шона",
  "langName.sr": "српски",
  "langName.sr-latn": "српски (латиница)",
  "langName.sv": "шведски",
  "langName.sv-se": "шведски (Шведска)",
  "langName.sw": "свахили",
  "langName.sw-ke": "свахили (Кенија)",
  "langName.sw-tz": "свахили (Танзанија)",
  "langName.syc": "сиријачки (класични)",
  "langName.ta": "тамилски",
  "langName.te": "телугу",
  "langName.tg": "таџички",
  "langName.th": "тајски",
  "langName.th-th": "тајски (Тајланд)",
  "langName.tk": "туркменски",
  "langName.tl": "тагалог",
  "langName.tr": "турски",
  "langName.tr-tr": "турски (Турска)",
  "langName.tt": "татарски",
  "langName.ug": "ујгурски",
  "langName.uk": "украјински",
  "langName.ur": "урду",
  "langName.uz": "узбечки",
  "langName.vi": "вијетнамски",
  "langName.wo": "волоф",
  "langName.xh": "коса",
  "langName.yi": "јидиш",
  "langName.yo": "јоруба",
  "langName.yua": "маја (јукатечки)",
  "langName.zh": "кинески",
  "langName.zh-cn": "кинески (поједностављени)",
  "langName.zh-hans": "кинески (поједностављени)",
  "langName.zh-hant": "кинески (традиционални)",
  "langName.zh-hk": "кинески (Хонг Конг)",
  "langName.zh-sg": "кинески (Сингапур)",
  "langName.zh-tw": "кинески (традиционални)",
  "langName.zu": "зулу",
  "langName.zu-za": "зулу (Јужна Африка)"
});