tinymce.addI18n("sv", {
  "Current language:": "Aktuellt språk:",
  "Set text language": "Ange textspråk",
  "-Language Not Set-": "-Språk inte angivet-",
  "Choose languages": "Välj språk",
  "Remove Language Markup": "Ta bort språkmarkering",
  "Remove current lang value": "Ta bort aktuellt språkvärde",
  "Remove All lang markup": "Ta bort all språkmarkering",
  "Configure languages": "Konfigurera språk",
  "Set default document language": "Ange standardspråk för dokument",
  "Reveal lang markup": "Visa språkmarkering",
  "Indicate current language": "Ange aktuellt språk",
  "Select the document's default language.": "Välj dokumentets standardspråk.",
  "Choose from list": "Välj från lista",
  "Enter manually": "Ange manuellt",
  "None": "Ingen",
  "Other - Enter manually": "Annat - Ange manuellt",
  "New Language:": "Nytt språk:",
  "Enter new lang code (e.g., \"en-US\"):": "Ange ny språkkod (t.ex. \"sv-SE\"):",
  "Choose up to six languages": "Välj upp till sex språk",
  "Select language {{number}}:": "Välj språk {{number}}:",
  "Manually enter language {{number}}:": "Ange språk {{number}} manuellt:",
  "Really remove all language markup from the document?": "Vill du verkligen ta bort all språkmarkering från dokumentet?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Ange en giltig språkkod utan mellanslag. Eller tryck avbryt.",
  "langName.af": "Afrikaans",
  "langName.ak": "Akan",
  "langName.ar": "Arabiska",
  "langName.az": "Azerbajdzjanska",
  "langName.bg": "Bulgariska",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengali",
  "langName.bo": "Tibetanska",
  "langName.bs": "Bosniska",
  "langName.ca": "Katalanska; Valencianska",
  "langName.cs": "Tjeckiska",
  "langName.cu": "Fornbulgariska",
  "langName.da": "Danska",
  "langName.de": "Tyska",
  "langName.el": "Grekiska",
  "langName.en": "Engelska",
  "langName.en-au": "Engelska (Australien)",
  "langName.en-gb": "Engelska (Storbritannien)",
  "langName.en-in": "Engelska (Indien)",
  "langName.en-ie": "Engelska (Irland)",
  "langName.en-tt": "Engelska (Trinidad)",
  "langName.en-us": "Engelska (USA)",
  "langName.en-za": "Engelska (Sydafrika)",
  "langName.es": "Spanska",
  "langName.es-ar": "Spanska (Argentina)",
  "langName.es-cl": "Spanska (Chile)",
  "langName.es-co": "Spanska (Colombia)",
  "langName.es-mx": "Spanska (Mexiko)",
  "langName.es-pe": "Spanska (Peru)",
  "langName.et": "Estniska",
  "langName.eu": "Baskiska",
  "langName.fa": "Persiska",
  "langName.fi": "Finska",
  "langName.fr": "Franska",
  "langName.fr-ca": "Franska (Kanada)",
  "langName.gl": "Galiciska (Spanien)",
  "langName.he": "Hebreiska",
  "langName.hi": "Hindi",
  "langName.hr": "Kroatiska",
  "langName.hu": "Ungerska",
  "langName.id": "Indonesiska",
  "langName.it": "Italienska",
  "langName.ja": "Japanska",
  "langName.kk": "Kazakiska",
  "langName.kn": "Kannada",
  "langName.ko": "Koreanska",
  "langName.la": "Latin",
  "langName.lkt": "Lakota",
  "langName.mn": "Mongoliska",
  "langName.mr": "Marathi",
  "langName.nb": "Norska Bokmål",
  "langName.nl": "Nederländska",
  "langName.nl-be": "Nederländska (Belgien)",
  "langName.nn": "Norska Nynorsk",
  "langName.pl": "Polska",
  "langName.ps": "Pashto",
  "langName.pt": "Portugisiska, internationell",
  "langName.pt-br": "Portugisiska (Brasilien)",
  "langName.qu": "Quechua",
  "langName.ro": "Rumänska",
  "langName.ru": "Ryska",
  "langName.sa": "Sanskrit",
  "langName.sk-sk": "Slovakiska",
  "langName.sl": "Slovenska",
  "langName.sma": "Sydsamiska",
  "langName.sme": "Nordsamiska",
  "langName.smj": "Lulesamiska",
  "langName.sr": "Serbiska",
  "langName.sv": "Svenska",
  "langName.sw": "Swahili",
  "langName.ta": "Tamil",
  "langName.te": "Telugu",
  "langName.tg": "Tadzjikiska",
  "langName.th": "Thailändska",
  "langName.tr": "Turkiska",
  "langName.ug": "Uiguriska",
  "langName.uk": "Ukrainska",
  "langName.ur": "Urdu",
  "langName.uz": "Uzbekiska",
  "langName.vi": "Vietnamesiska",
  "langName.wo": "Wolof",
  "langName.yi": "Jiddisch",
  "langName.yo": "Yoruba",
  "langName.yua": "Yukatekisk maya",
  "langName.zh": "Kinesiska",
  "langName.zh-cn": "Kinesiska (Kina)",
  "langName.zh-hk": "Kinesiska (Hongkong)",
  "langName.zh-tw": "Kinesiska (Taiwan)",
  "langName.zh-hans": "Kinesiska, förenklad",
  "langName.zh-hant": "Kinesiska, traditionell",
  "langName.zu": "Zulu"
});