tinymce.addI18n('sv_SE', {
  "-Language Not Set-": "-Språk inte angivet-",
  "Choose from list": "Välj från lista",
  "Choose languages": "Välj språk",
  "Choose up to six languages": "Välj upp till sex språk",
  "Configure languages": "Konfigurera språk",
  "Current language:": "Aktuellt språk:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Ange en giltig språkkod utan mellanslag. Eller tryck avbryt.",
  "Enter manually": "Ange manuellt",
  "Enter new lang code (e.g., \"en-US\"):": "Ange ny språkkod (t.ex. \"sv-SE\"):",
  "Indicate current language": "Ange aktuellt språk",
  "Manually enter language {{number}}:": "Ange språk {{number}} manuellt:",
  "New Language:": "Nytt språk:",
  "None": "Ingen",
  "Other - Enter manually": "Annat - Ange manuellt",
  "Really remove all language markup from the document?": "Vill du verkligen ta bort all språkmarkering från dokumentet?",
  "Remove All lang markup": "Ta bort all språkmarkering",
  "Remove Language Markup": "Ta bort språkmarkering",
  "Remove current lang value": "Ta bort aktuellt språkvärde",
  "Reveal lang markup": "Visa språkmarkering",
  "Select language {{number}}:": "Välj språk {{number}}:",
  "Select the document's default language.": "Välj dokumentets standardspråk.",
  "Set default document language": "Ange standardspråk för dokument",
  "Set text language": "Ange textspråk",
  "langName.af": "afrikaans",
  "langName.af-za": "afrikaans",
  "langName.ak": "akan",
  "langName.am": "amhariska",
  "langName.ar": "arabiska",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "arabiska",
  "langName.az": "azerbajdzjanska",
  "langName.be": "belarusiska",
  "langName.bg": "bulgariska",
  "langName.bg-bg": "bulgariska",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengali",
  "langName.bo": "tibetanska",
  "langName.bs": "bosniska",
  "langName.ca": "katalanska",
  "langName.cop": "koptiska",
  "langName.cr": "cree",
  "langName.cs": "tjeckiska",
  "langName.cu": "kyrkslaviska",
  "langName.cy": "walesiska",
  "langName.da": "danska",
  "langName.de": "tyska",
  "langName.de-at": "österrikisk tyska",
  "langName.de-ch": "schweizisk högtyska",
  "langName.de-de": "tyska",
  "langName.dv": "divehi",
  "langName.el": "grekiska",
  "langName.en": "engelska",
  "langName.en-au": "australisk engelska",
  "langName.en-ca": "kanadensisk engelska",
  "langName.en-gb": "brittisk engelska",
  "langName.en-ie": "Engelska (Irland)",
  "langName.en-in": "Engelska (Indien)",
  "langName.en-tt": "Engelska (Trinidad)",
  "langName.en-us": "amerikansk engelska",
  "langName.en-za": "Engelska (Sydafrika)",
  "langName.eo": "esperanto",
  "langName.es": "spanska",
  "langName.es-ar": "Spanska (Argentina)",
  "langName.es-cl": "Spanska (Chile)",
  "langName.es-co": "Spanska (Colombia)",
  "langName.es-cr": "",
  "langName.es-es": "europeisk spanska",
  "langName.es-mx": "mexikansk spanska",
  "langName.es-pe": "Spanska (Peru)",
  "langName.et": "estniska",
  "langName.eu": "baskiska",
  "langName.fa": "persiska",
  "langName.fa-af": "dari",
  "langName.fa-ir": "persiska",
  "langName.ff": "fulani",
  "langName.fi": "finska",
  "langName.fi-fi": "finska",
  "langName.fil": "filippinska",
  "langName.fr": "franska",
  "langName.fr-be": "",
  "langName.fr-ca": "kanadensisk franska",
  "langName.fr-ch": "schweizisk franska",
  "langName.ga": "iriska",
  "langName.gl": "galiciska",
  "langName.grc": "forngrekiska",
  "langName.ha": "hausa",
  "langName.he": "hebreiska",
  "langName.he-il": "hebreiska",
  "langName.hi": "hindi",
  "langName.hr": "kroatiska",
  "langName.hr-hr": "kroatiska",
  "langName.ht": "haitiska",
  "langName.hu": "ungerska",
  "langName.hu-hu": "ungerska",
  "langName.hy": "armeniska",
  "langName.id": "indonesiska",
  "langName.ig": "igbo",
  "langName.is": "isländska",
  "langName.it": "italienska",
  "langName.it-it": "italienska",
  "langName.iu": "inuktitut",
  "langName.ja": "japanska",
  "langName.ja-jp": "japanska",
  "langName.ka": "georgiska",
  "langName.kab": "kabyliska",
  "langName.kk": "kazakiska",
  "langName.km": "kambodjanska",
  "langName.kn": "kannada",
  "langName.ko": "koreanska",
  "langName.ko-kr": "koreanska",
  "langName.la": "latin",
  "langName.lkt": "lakota",
  "langName.lo": "laotiska",
  "langName.lt": "litauiska",
  "langName.lv": "lettiska",
  "langName.mi": "maori",
  "langName.mn": "mongoliska",
  "langName.mr": "marathi",
  "langName.ms": "malajiska",
  "langName.mt": "maltesiska",
  "langName.my": "burmesiska",
  "langName.nb": "norskt bokmål",
  "langName.nb-no": "norskt bokmål",
  "langName.ne": "nepalesiska",
  "langName.nl": "nederländska",
  "langName.nl-be": "flamländska",
  "langName.nn": "nynorska",
  "langName.nv": "navaho",
  "langName.ota": "ottomanska",
  "langName.pa": "punjabi",
  "langName.peo": "fornpersiska",
  "langName.pl": "polska",
  "langName.ps": "afghanska",
  "langName.pt": "portugisiska",
  "langName.pt-br": "brasiliansk portugisiska",
  "langName.pt-pt": "europeisk portugisiska",
  "langName.qu": "quechua",
  "langName.ro": "rumänska",
  "langName.ru": "ryska",
  "langName.rw": "kinjarwanda",
  "langName.sa": "sanskrit",
  "langName.se": "nordsamiska",
  "langName.si": "singalesiska",
  "langName.sk-sk": "slovakiska",
  "langName.sl": "slovenska",
  "langName.sl-si": "slovenska",
  "langName.sma": "sydsamiska",
  "langName.sme": "Nordsamiska",
  "langName.smj": "lulesamiska",
  "langName.sn": "shona",
  "langName.sr": "serbiska",
  "langName.sr-latn": "",
  "langName.sv": "svenska",
  "langName.sv-se": "svenska",
  "langName.sw": "swahili",
  "langName.sw-ke": "swahili",
  "langName.sw-tz": "swahili",
  "langName.syc": "klassisk syriska",
  "langName.ta": "tamil",
  "langName.te": "telugu",
  "langName.tg": "tadzjikiska",
  "langName.th": "thailändska",
  "langName.th-th": "thailändska",
  "langName.tk": "turkmeniska",
  "langName.tl": "tagalog",
  "langName.tr": "turkiska",
  "langName.tr-tr": "turkiska",
  "langName.tt": "tatariska",
  "langName.ug": "uiguriska",
  "langName.uk": "ukrainska",
  "langName.ur": "urdu",
  "langName.uz": "uzbekiska",
  "langName.vi": "vietnamesiska",
  "langName.wo": "wolof",
  "langName.xh": "xhosa",
  "langName.yi": "jiddisch",
  "langName.yo": "yoruba",
  "langName.yua": "Yukatekisk maya",
  "langName.zh": "kinesiska",
  "langName.zh-cn": "förenklad kinesiska",
  "langName.zh-hans": "förenklad kinesiska",
  "langName.zh-hant": "traditionell kinesiska",
  "langName.zh-hk": "Kinesiska (Hongkong)",
  "langName.zh-sg": "",
  "langName.zh-tw": "traditionell kinesiska",
  "langName.zu": "zulu",
  "langName.zu-za": "zulu"
});