tinymce.addI18n('sv_x_k12', {
  "-Language Not Set-": "-Inget språk valt-",
  "Choose from list": "Välj från lista",
  "Choose languages": "Välj språk",
  "Choose up to six languages": "Välj upp till sex språk",
  "Configure languages": "Ställ in språk",
  "Current language:": "Nuvarande språk:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Skriv en giltig språkkod utan mellanslag. Eller tryck avbryt.",
  "Enter manually": "Skriv själv",
  "Enter new lang code (e.g., \"en-US\"):": "Skriv ny språkkod (t.ex. \"sv-SE\"):",
  "Indicate current language": "Visa nuvarande språk",
  "Manually enter language {{number}}:": "Skriv språk {{number}} själv:",
  "New Language:": "Nytt språk:",
  "None": "Inget",
  "Other - Enter manually": "Annat - Skriv själv",
  "Really remove all language markup from the document?": "Vill du verkligen ta bort alla språkmarkeringar från dokumentet?",
  "Remove All lang markup": "Ta bort alla språkmarkeringar",
  "Remove Language Markup": "Ta bort språkmarkeringar",
  "Remove current lang value": "Ta bort nuvarande språk",
  "Reveal lang markup": "Visa språkmarkeringar",
  "Select language {{number}}:": "Välj språk {{number}}:",
  "Select the document's default language.": "Välj dokumentets grundspråk.",
  "Set default document language": "Välj grundspråk för dokumentet",
  "Set text language": "Välj språk för text",
  "langName.af": "afrikaans",
  "langName.af-za": "afrikaans (Sydafrika)",
  "langName.ak": "akan",
  "langName.am": "amhariska",
  "langName.ar": "arabiska",
  "langName.ar-eg": "arabiska (Egypten)",
  "langName.ar-ma": "arabiska (Marocko)",
  "langName.ar-sa": "arabiska (Saudiarabien)",
  "langName.az": "azerbajdzjanska",
  "langName.be": "belarusiska",
  "langName.bg": "bulgariska",
  "langName.bg-bg": "bulgariska (Bulgarien)",
  "langName.bho": "bhojpuri",
  "langName.bm": "bambara",
  "langName.bn": "bengali",
  "langName.bo": "tibetanska",
  "langName.bs": "bosniska",
  "langName.ca": "katalanska",
  "langName.cop": "koptiska",
  "langName.cr": "cree",
  "langName.cs": "tjeckiska",
  "langName.cu": "kyrkslaviska",
  "langName.cy": "walesiska",
  "langName.da": "danska",
  "langName.de": "tyska",
  "langName.de-at": "tyska (Österrike)",
  "langName.de-ch": "tyska (Schweiz)",
  "langName.de-de": "tyska (Tyskland)",
  "langName.dv": "divehi",
  "langName.el": "grekiska",
  "langName.en": "engelska",
  "langName.en-au": "engelska (Australien)",
  "langName.en-ca": "engelska (Kanada)",
  "langName.en-gb": "engelska (Storbritannien)",
  "langName.en-ie": "engelska (Irland)",
  "langName.en-in": "engelska (Indien)",
  "langName.en-tt": "engelska (Trinidad)",
  "langName.en-us": "engelska (USA)",
  "langName.en-za": "engelska (Sydafrika)",
  "langName.eo": "esperanto",
  "langName.es": "spanska",
  "langName.es-ar": "spanska (Argentina)",
  "langName.es-cl": "spanska (Chile)",
  "langName.es-co": "spanska (Colombia)",
  "langName.es-cr": "spanska (Costa Rica)",
  "langName.es-es": "spanska (Spanien)",
  "langName.es-mx": "spanska (Mexiko)",
  "langName.es-pe": "spanska (Peru)",
  "langName.et": "estniska",
  "langName.eu": "baskiska",
  "langName.fa": "persiska",
  "langName.fa-af": "dari",
  "langName.fa-ir": "persiska (Iran)",
  "langName.ff": "fulani",
  "langName.fi": "finska",
  "langName.fi-fi": "finska (Finland)",
  "langName.fil": "filippinska",
  "langName.fr": "franska",
  "langName.fr-be": "franska (Belgien)",
  "langName.fr-ca": "franska (Kanada)",
  "langName.fr-ch": "franska (Schweiz)",
  "langName.ga": "iriska",
  "langName.gl": "galiciska",
  "langName.grc": "forngrekiska",
  "langName.ha": "hausa",
  "langName.he": "hebreiska",
  "langName.he-il": "hebreiska (Israel)",
  "langName.hi": "hindi",
  "langName.hr": "kroatiska",
  "langName.hr-hr": "kroatiska (Kroatien)",
  "langName.ht": "haitisk kreol",
  "langName.hu": "ungerska",
  "langName.hu-hu": "ungerska (Ungern)",
  "langName.hy": "armeniska",
  "langName.id": "indonesiska",
  "langName.ig": "igbo",
  "langName.is": "isländska",
  "langName.it": "italienska",
  "langName.it-it": "italienska (Italien)",
  "langName.iu": "inuktitut",
  "langName.ja": "japanska",
  "langName.ja-jp": "japanska (Japan)",
  "langName.ka": "georgiska",
  "langName.kab": "kabyliska",
  "langName.kk": "kazakiska",
  "langName.km": "kambodjanska",
  "langName.kn": "kannada",
  "langName.ko": "koreanska",
  "langName.ko-kr": "koreanska (Sydkorea)",
  "langName.la": "latin",
  "langName.lkt": "lakota",
  "langName.lo": "laotiska",
  "langName.lt": "litauiska",
  "langName.lv": "lettiska",
  "langName.mi": "maori",
  "langName.mn": "mongoliska",
  "langName.mr": "marathi",
  "langName.ms": "malajiska",
  "langName.mt": "maltesiska",
  "langName.my": "burmesiska",
  "langName.nb": "norska (bokmål)",
  "langName.nb-no": "norska (bokmål, Norge)",
  "langName.ne": "nepalesiska",
  "langName.nl": "nederländska",
  "langName.nl-be": "flamländska",
  "langName.nn": "norska (nynorska)",
  "langName.nv": "navaho",
  "langName.ota": "turkiska (ottomanska)",
  "langName.pa": "punjabi",
  "langName.peo": "persiska (fornpersiska)",
  "langName.pl": "polska",
  "langName.ps": "afghanska",
  "langName.pt": "portugisiska",
  "langName.pt-br": "portugisiska (Brasilien)",
  "langName.pt-pt": "portugisiska (Portugal)",
  "langName.qu": "quechua",
  "langName.ro": "rumänska",
  "langName.ru": "ryska",
  "langName.rw": "kinjarwanda",
  "langName.sa": "sanskrit",
  "langName.se": "samiska (nordsamiska)",
  "langName.si": "singalesiska",
  "langName.sk": "slovakiska",
  "langName.sk-sk": "slovakiska (Slovakien)",
  "langName.sl": "slovenska",
  "langName.sl-si": "slovenska (Slovenien)",
  "langName.sma": "samiska (sydsamiska)",
  "langName.sme": "samiska (nordsamiska)",
  "langName.smj": "samiska (lulesamiska)",
  "langName.sn": "shona",
  "langName.sr": "serbiska",
  "langName.sr-latn": "serbiska (latinsk)",
  "langName.sv": "svenska",
  "langName.sv-se": "svenska (Sverige)",
  "langName.sw": "swahili",
  "langName.sw-ke": "swahili (Kenya)",
  "langName.sw-tz": "swahili (Tanzania)",
  "langName.syc": "syriska (klassisk)",
  "langName.ta": "tamil",
  "langName.te": "telugu",
  "langName.tg": "tadzjikiska",
  "langName.th": "thailändska",
  "langName.th-th": "thailändska (Thailand)",
  "langName.tk": "turkmeniska",
  "langName.tl": "tagalog",
  "langName.tr": "turkiska",
  "langName.tr-tr": "turkiska (Turkiet)",
  "langName.tt": "tatariska",
  "langName.ug": "uiguriska",
  "langName.uk": "ukrainska",
  "langName.ur": "urdu",
  "langName.uz": "uzbekiska",
  "langName.vi": "vietnamesiska",
  "langName.wo": "wolof",
  "langName.xh": "xhosa",
  "langName.yi": "jiddisch",
  "langName.yo": "yoruba",
  "langName.yua": "maya (yukatekisk)",
  "langName.zh": "kinesiska",
  "langName.zh-cn": "kinesiska (förenklad)",
  "langName.zh-hans": "kinesiska (förenklad)",
  "langName.zh-hant": "kinesiska (traditionell)",
  "langName.zh-hk": "kinesiska (Hongkong)",
  "langName.zh-sg": "kinesiska (Singapore)",
  "langName.zh-tw": "kinesiska (traditionell)",
  "langName.zu": "zulu",
  "langName.zu-za": "zulu (Sydafrika)"
});