tinymce.addI18n("th", {
  "Current language:": "ภาษาปัจจุบัน:",
  "Set text language": "ตั้งค่าภาษาข้อความ",
  "-Language Not Set-": "-ไม่ได้ตั้งค่าภาษา-",
  "Choose languages": "เลือกภาษา",
  "Remove Language Markup": "ลบเครื่องหมายภาษา",
  "Remove current lang value": "ลบค่าภาษาปัจจุบัน",
  "Remove All lang markup": "ลบเครื่องหมายภาษาทั้งหมด",
  "Configure languages": "กำหนดค่าภาษา",
  "Set default document language": "ตั้งค่าภาษาเริ่มต้นของเอกสาร",
  "Reveal lang markup": "แสดงเครื่องหมายภาษา",
  "Indicate current language": "แสดงภาษาปัจจุบัน",
  "Select the document's default language.": "เลือกภาษาเริ่มต้นของเอกสาร",
  "Choose from list": "เลือกจากรายการ",
  "Enter manually": "ป้อนด้วยตนเอง",
  "None": "ไม่มี",
  "Other - Enter manually": "อื่น ๆ - ป้อนด้วยตนเอง",
  "New Language:": "ภาษาใหม่:",
  "Enter new lang code (e.g., \"en-US\"):": "ป้อนรหัสภาษาใหม่ (เช่น \"th-TH\"):",
  "Choose up to six languages": "เลือกได้สูงสุดหกภาษา",
  "Select language {{number}}:": "เลือกภาษา {{number}}:",
  "Manually enter language {{number}}:": "ป้อนภาษา {{number}} ด้วยตนเอง:",
  "Really remove all language markup from the document?": "ต้องการลบเครื่องหมายภาษาทั้งหมดออกจากเอกสารจริงหรือไม่?",
  "Enter a valid language code with no spaces. Or, press cancel.": "ป้อนรหัสภาษาที่ถูกต้องโดยไม่มีช่องว่าง หรือกดยกเลิก",
  "langName.af": "แอฟริกาใต้",
  "langName.ak": "อาคาน",
  "langName.ar": "อาหรับ",
  "langName.az": "อาเซอร์ไบจาน",
  "langName.bg": "บัลแกเรีย",
  "langName.bho": "โภชปุรี",
  "langName.bm": "บัมบารา",
  "langName.bn": "เบงกาลี",
  "langName.bo": "ทิเบต",
  "langName.bs": "บอสเนีย",
  "langName.ca": "คาตาลัน; บาเลนเซีย",
  "langName.cs": "เช็ก",
  "langName.cu": "บัลแกเรียโบราณ",
  "langName.da": "เดนมาร์ก",
  "langName.de": "เยอรมัน",
  "langName.el": "กรีก",
  "langName.en": "อังกฤษ",
  "langName.en-au": "อังกฤษ (ออสเตรเลีย)",
  "langName.en-gb": "อังกฤษ (สหราชอาณาจักร)",
  "langName.en-in": "อังกฤษ (อินเดีย)",
  "langName.en-ie": "อังกฤษ (ไอร์แลนด์)",
  "langName.en-tt": "อังกฤษ (ตรินิแดด)",
  "langName.en-us": "อังกฤษ (สหรัฐอเมริกา)",
  "langName.en-za": "อังกฤษ (แอฟริกาใต้)",
  "langName.es": "สเปน",
  "langName.es-ar": "สเปน (อาร์เจนตินา)",
  "langName.es-cl": "สเปน (ชิลี)",
  "langName.es-co": "สเปน (โคลอมเบีย)",
  "langName.es-mx": "สเปน (เม็กซิโก)",
  "langName.es-pe": "สเปน (เปรู)",
  "langName.et": "เอสโตเนีย",
  "langName.eu": "บาสก์",
  "langName.fa": "เปอร์เซีย",
  "langName.fi": "ฟินแลนด์",
  "langName.fr": "ฝรั่งเศส",
  "langName.fr-ca": "ฝรั่งเศส (แคนาดา)",
  "langName.gl": "กาลิเซีย (สเปน)",
  "langName.he": "ฮิบรู",
  "langName.hi": "ฮินดี",
  "langName.hr": "โครเอเชีย",
  "langName.hu": "ฮังการี",
  "langName.id": "อินโดนีเซีย",
  "langName.it": "อิตาลี",
  "langName.ja": "ญี่ปุ่น",
  "langName.kk": "คาซัค",
  "langName.kn": "กันนาดา",
  "langName.ko": "เกาหลี",
  "langName.la": "ลาติน",
  "langName.lkt": "ลาโคตา",
  "langName.mn": "มองโกเลีย",
  "langName.mr": "มราฐี",
  "langName.nb": "นอร์เวย์ บุคมอล",
  "langName.nl": "ดัตช์",
  "langName.nl-be": "ดัตช์ (เบลเยียม)",
  "langName.nn": "นอร์เวย์ นี่นอสก์",
  "langName.pl": "โปแลนด์",
  "langName.ps": "ปาชตู",
  "langName.pt": "โปรตุเกส สากล",
  "langName.pt-br": "โปรตุเกส (บราซิล)",
  "langName.qu": "เคชัว",
  "langName.ro": "โรมาเนีย",
  "langName.ru": "รัสเซีย",
  "langName.sa": "สันสกฤต",
  "langName.sk-sk": "สโลวาเกีย",
  "langName.sl": "สโลวีเนีย",
  "langName.sma": "ซามิใต้",
  "langName.sme": "ซามิเหนือ",
  "langName.smj": "ซามิลูเล",
  "langName.sr": "เซอร์เบีย",
  "langName.sv": "สวีเดน",
  "langName.sw": "สวาฮิลี",
  "langName.ta": "ทมิฬ",
  "langName.te": "เตลูกู",
  "langName.tg": "ทาจิก",
  "langName.th": "ไทย",
  "langName.tr": "ตุรกี",
  "langName.ug": "อุยกูร์",
  "langName.uk": "ยูเครน",
  "langName.ur": "อูรดู",
  "langName.uz": "อุซเบก",
  "langName.vi": "เวียดนาม",
  "langName.wo": "วูลอฟ",
  "langName.yi": "ยิดดิช",
  "langName.yo": "โยรูบา",
  "langName.yua": "มายายูคาเตก",
  "langName.zh": "จีน",
  "langName.zh-cn": "จีน (จีน)",
  "langName.zh-hk": "จีน (ฮ่องกง)",
  "langName.zh-tw": "จีน (ไต้หวัน)",
  "langName.zh-hans": "จีน แบบตัวย่อ",
  "langName.zh-hant": "จีน แบบตัวเต็ม",
  "langName.zu": "ซูลู"
});