tinymce.addI18n('th', {
  "-Language Not Set-": "-ไม่ได้ตั้งค่าภาษา-",
  "Choose from list": "เลือกจากรายการ",
  "Choose languages": "เลือกภาษา",
  "Choose up to six languages": "เลือกได้สูงสุดหกภาษา",
  "Configure languages": "กำหนดค่าภาษา",
  "Current language:": "ภาษาปัจจุบัน:",
  "Enter a valid language code with no spaces. Or, press cancel.": "ป้อนรหัสภาษาที่ถูกต้องโดยไม่มีช่องว่าง หรือกดยกเลิก",
  "Enter manually": "ป้อนด้วยตนเอง",
  "Enter new lang code (e.g., \"en-US\"):": "ป้อนรหัสภาษาใหม่ (เช่น \"th-TH\"):",
  "Indicate current language": "แสดงภาษาปัจจุบัน",
  "Manually enter language {{number}}:": "ป้อนภาษา {{number}} ด้วยตนเอง:",
  "New Language:": "ภาษาใหม่:",
  "None": "ไม่มี",
  "Other - Enter manually": "อื่น ๆ - ป้อนด้วยตนเอง",
  "Really remove all language markup from the document?": "ต้องการลบเครื่องหมายภาษาทั้งหมดออกจากเอกสารจริงหรือไม่?",
  "Remove All lang markup": "ลบเครื่องหมายภาษาทั้งหมด",
  "Remove Language Markup": "ลบเครื่องหมายภาษา",
  "Remove current lang value": "ลบค่าภาษาปัจจุบัน",
  "Reveal lang markup": "แสดงเครื่องหมายภาษา",
  "Select language {{number}}:": "เลือกภาษา {{number}}:",
  "Select the document's default language.": "เลือกภาษาเริ่มต้นของเอกสาร",
  "Set default document language": "ตั้งค่าภาษาเริ่มต้นของเอกสาร",
  "Set text language": "ตั้งค่าภาษาข้อความ",
  "langName.af": "แอฟริกานส์",
  "langName.af-za": "แอฟริกานส์",
  "langName.ak": "อาคาน",
  "langName.am": "อัมฮารา",
  "langName.ar": "อาหรับ",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "อาหรับ",
  "langName.az": "อาเซอร์ไบจาน",
  "langName.be": "เบลารุส",
  "langName.bg": "บัลแกเรีย",
  "langName.bg-bg": "บัลแกเรีย",
  "langName.bho": "โภชปุรี",
  "langName.bm": "บัมบารา",
  "langName.bn": "บังกลา",
  "langName.bo": "ทิเบต",
  "langName.bs": "บอสเนีย",
  "langName.ca": "คาตาลัน",
  "langName.cop": "คอปติก",
  "langName.cr": "ครี",
  "langName.cs": "เช็ก",
  "langName.cu": "เชอร์ชสลาวิก",
  "langName.cy": "เวลส์",
  "langName.da": "เดนมาร์ก",
  "langName.de": "เยอรมัน",
  "langName.de-at": "เยอรมัน - ออสเตรีย",
  "langName.de-ch": "เยอรมันสูง (สวิส)",
  "langName.de-de": "เยอรมัน",
  "langName.dv": "ธิเวหิ",
  "langName.el": "กรีก",
  "langName.en": "อังกฤษ",
  "langName.en-au": "อังกฤษ - ออสเตรเลีย",
  "langName.en-ca": "อังกฤษ - แคนาดา",
  "langName.en-gb": "อังกฤษ - สหราชอาณาจักร",
  "langName.en-ie": "อังกฤษ (ไอร์แลนด์)",
  "langName.en-in": "อังกฤษ (อินเดีย)",
  "langName.en-tt": "อังกฤษ (ตรินิแดด)",
  "langName.en-us": "อังกฤษ - สหรัฐอเมริกา",
  "langName.en-za": "อังกฤษ (แอฟริกาใต้)",
  "langName.eo": "เอสเปรันโต",
  "langName.es": "สเปน",
  "langName.es-ar": "สเปน (อาร์เจนตินา)",
  "langName.es-cl": "สเปน (ชิลี)",
  "langName.es-co": "สเปน (โคลอมเบีย)",
  "langName.es-cr": "",
  "langName.es-es": "สเปน - ยุโรป",
  "langName.es-mx": "สเปน - เม็กซิโก",
  "langName.es-pe": "สเปน (เปรู)",
  "langName.et": "เอสโตเนีย",
  "langName.eu": "บาสก์",
  "langName.fa": "เปอร์เซีย",
  "langName.fa-af": "ดารี",
  "langName.fa-ir": "เปอร์เซีย",
  "langName.ff": "ฟูลาห์",
  "langName.fi": "ฟินแลนด์",
  "langName.fi-fi": "ฟินแลนด์",
  "langName.fil": "ฟิลิปปินส์",
  "langName.fr": "ฝรั่งเศส",
  "langName.fr-be": "",
  "langName.fr-ca": "ฝรั่งเศส - แคนาดา",
  "langName.fr-ch": "ฝรั่งเศส - สวิส",
  "langName.ga": "ไอริช",
  "langName.gl": "กาลิเซีย",
  "langName.grc": "กรีกโบราณ",
  "langName.ha": "เฮาซา",
  "langName.he": "ฮิบรู",
  "langName.he-il": "ฮิบรู",
  "langName.hi": "ฮินดี",
  "langName.hr": "โครเอเชีย",
  "langName.hr-hr": "โครเอเชีย",
  "langName.ht": "เฮติครีโอล",
  "langName.hu": "ฮังการี",
  "langName.hu-hu": "ฮังการี",
  "langName.hy": "อาร์เมเนีย",
  "langName.id": "อินโดนีเซีย",
  "langName.ig": "อิกโบ",
  "langName.is": "ไอซ์แลนด์",
  "langName.it": "อิตาลี",
  "langName.it-it": "อิตาลี",
  "langName.iu": "อินุกติตุต",
  "langName.ja": "ญี่ปุ่น",
  "langName.ja-jp": "ญี่ปุ่น",
  "langName.ka": "จอร์เจีย",
  "langName.kab": "กาไบล",
  "langName.kk": "คาซัค",
  "langName.km": "เขมร",
  "langName.kn": "กันนาดา",
  "langName.ko": "เกาหลี",
  "langName.ko-kr": "เกาหลี",
  "langName.la": "ละติน",
  "langName.lkt": "ลาโกตา",
  "langName.lo": "ลาว",
  "langName.lt": "ลิทัวเนีย",
  "langName.lv": "ลัตเวีย",
  "langName.mi": "เมารี",
  "langName.mn": "มองโกเลีย",
  "langName.mr": "มราฐี",
  "langName.ms": "มาเลย์",
  "langName.mt": "มอลตา",
  "langName.my": "พม่า",
  "langName.nb": "นอร์เวย์บุคมอล",
  "langName.nb-no": "นอร์เวย์บุคมอล",
  "langName.ne": "เนปาล",
  "langName.nl": "ดัตช์",
  "langName.nl-be": "เฟลมิช",
  "langName.nn": "นอร์เวย์นีนอสก์",
  "langName.nv": "นาวาโฮ",
  "langName.ota": "ตุรกีออตโตมัน",
  "langName.pa": "ปัญจาบ",
  "langName.peo": "เปอร์เซียโบราณ",
  "langName.pl": "โปแลนด์",
  "langName.ps": "พัชโต",
  "langName.pt": "โปรตุเกส",
  "langName.pt-br": "โปรตุเกส - บราซิล",
  "langName.pt-pt": "โปรตุเกส - ยุโรป",
  "langName.qu": "เคชวา",
  "langName.ro": "โรมาเนีย",
  "langName.ru": "รัสเซีย",
  "langName.rw": "รวันดา",
  "langName.sa": "สันสกฤต",
  "langName.se": "ซามิเหนือ",
  "langName.si": "สิงหล",
  "langName.sk-sk": "สโลวัก",
  "langName.sl": "สโลวีเนีย",
  "langName.sl-si": "สโลวีเนีย",
  "langName.sma": "ซามิใต้",
  "langName.sme": "ซามิเหนือ",
  "langName.smj": "ซามิลูเล",
  "langName.sn": "โชนา",
  "langName.sr": "เซอร์เบีย",
  "langName.sr-latn": "",
  "langName.sv": "สวีเดน",
  "langName.sv-se": "สวีเดน",
  "langName.sw": "สวาฮีลี",
  "langName.sw-ke": "สวาฮีลี",
  "langName.sw-tz": "สวาฮีลี",
  "langName.syc": "ซีเรียแบบดั้งเดิม",
  "langName.ta": "ทมิฬ",
  "langName.te": "เตลูกู",
  "langName.tg": "ทาจิก",
  "langName.th": "ไทย",
  "langName.th-th": "ไทย",
  "langName.tk": "เติร์กเมน",
  "langName.tl": "ตากาล็อก",
  "langName.tr": "ตุรกี",
  "langName.tr-tr": "ตุรกี",
  "langName.tt": "ตาตาร์",
  "langName.ug": "อุยกูร์",
  "langName.uk": "ยูเครน",
  "langName.ur": "อูรดู",
  "langName.uz": "อุซเบก",
  "langName.vi": "เวียดนาม",
  "langName.wo": "โวลอฟ",
  "langName.xh": "คะห์โอซา",
  "langName.yi": "ยิดดิช",
  "langName.yo": "โยรูบา",
  "langName.yua": "มายายูคาเตก",
  "langName.zh": "จีน",
  "langName.zh-cn": "จีนตัวย่อ",
  "langName.zh-hans": "จีนตัวย่อ",
  "langName.zh-hant": "จีนตัวเต็ม",
  "langName.zh-hk": "จีน (ฮ่องกง)",
  "langName.zh-sg": "",
  "langName.zh-tw": "จีนตัวเต็ม",
  "langName.zu": "ซูลู",
  "langName.zu-za": "ซูลู"
});