tinymce.addI18n("tr", {
  "Current language:": "Geçerli dil:",
  "Set text language": "Metin dilini ayarla",
  "-Language Not Set-": "-Dil Ayarlanmadı-",
  "Choose languages": "Dilleri seç",
  "Remove Language Markup": "Dil İşaretlemesini Kaldır",
  "Remove current lang value": "Geçerli dil değerini kaldır",
  "Remove All lang markup": "Tüm dil işaretlemesini kaldır",
  "Configure languages": "Dilleri yapılandır",
  "Set default document language": "Varsayılan belge dilini ayarla",
  "Reveal lang markup": "Dil işaretlemesini göster",
  "Indicate current language": "Geçerli dili belirt",
  "Select the document's default language.": "Belgenin varsayılan dilini seçin.",
  "Choose from list": "Listeden seç",
  "Enter manually": "El ile gir",
  "None": "Hiçbiri",
  "Other - Enter manually": "Diğer - El ile gir",
  "New Language:": "Yeni Dil:",
  "Enter new lang code (e.g., \"en-US\"):": "Yeni dil kodunu girin (örn. \"tr-TR\"):",
  "Choose up to six languages": "En fazla altı dil seçin",
  "Select language {{number}}:": "{{number}}. dili seçin:",
  "Manually enter language {{number}}:": "{{number}}. dili el ile girin:",
  "Really remove all language markup from the document?": "Belgeden tüm dil işaretlemesi gerçekten kaldırılsın mı?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Boşluk içermeyen geçerli bir dil kodu girin. Veya iptal'e basın.",
  "langName.af": "Afrikanca",
  "langName.ak": "Akan",
  "langName.ar": "Arapça",
  "langName.az": "Azerice",
  "langName.bg": "Bulgarca",
  "langName.bho": "Bhojpuri",
  "langName.bm": "Bambara",
  "langName.bn": "Bengalce",
  "langName.bo": "Tibetçe",
  "langName.bs": "Boşnakça",
  "langName.ca": "Katalanca; Valensiyaca",
  "langName.cs": "Çekçe",
  "langName.cu": "Eski Bulgarca",
  "langName.da": "Danca",
  "langName.de": "Almanca",
  "langName.el": "Yunanca",
  "langName.en": "İngilizce",
  "langName.en-au": "İngilizce (Avustralya)",
  "langName.en-gb": "İngilizce (Birleşik Krallık)",
  "langName.en-in": "İngilizce (Hindistan)",
  "langName.en-ie": "İngilizce (İrlanda)",
  "langName.en-tt": "İngilizce (Trinidad)",
  "langName.en-us": "İngilizce (Amerika Birleşik Devletleri)",
  "langName.en-za": "İngilizce (Güney Afrika)",
  "langName.es": "İspanyolca",
  "langName.es-ar": "İspanyolca (Arjantin)",
  "langName.es-cl": "İspanyolca (Şili)",
  "langName.es-co": "İspanyolca (Kolombiya)",
  "langName.es-mx": "İspanyolca (Meksika)",
  "langName.es-pe": "İspanyolca (Peru)",
  "langName.et": "Estonca",
  "langName.eu": "Baskça",
  "langName.fa": "Farsça",
  "langName.fi": "Fince",
  "langName.fr": "Fransızca",
  "langName.fr-ca": "Fransızca (Kanada)",
  "langName.gl": "Galiçyaca (İspanya)",
  "langName.he": "İbranice",
  "langName.hi": "Hintçe",
  "langName.hr": "Hırvatça",
  "langName.hu": "Macarca",
  "langName.id": "Endonezce",
  "langName.it": "İtalyanca",
  "langName.ja": "Japonca",
  "langName.kk": "Kazakça",
  "langName.kn": "Kannada",
  "langName.ko": "Korece",
  "langName.la": "Latince",
  "langName.lkt": "Lakota",
  "langName.mn": "Moğolca",
  "langName.mr": "Marathi",
  "langName.nb": "Norveççe Bokmål",
  "langName.nl": "Felemenkçe",
  "langName.nl-be": "Felemenkçe (Belçika)",
  "langName.nn": "Norveççe Nynorsk",
  "langName.pl": "Lehçe",
  "langName.ps": "Peştuca",
  "langName.pt": "Portekizce, Uluslararası",
  "langName.pt-br": "Portekizce (Brezilya)",
  "langName.qu": "Keçuva",
  "langName.ro": "Romence",
  "langName.ru": "Rusça",
  "langName.sa": "Sanskritçe",
  "langName.sk-sk": "Slovakça",
  "langName.sl": "Slovence",
  "langName.sma": "Güney Sami",
  "langName.sme": "Kuzey Sami",
  "langName.smj": "Lule Sami",
  "langName.sr": "Sırpça",
  "langName.sv": "İsveççe",
  "langName.sw": "Svahili",
  "langName.ta": "Tamilce",
  "langName.te": "Telugu",
  "langName.tg": "Tacikçe",
  "langName.th": "Tayca",
  "langName.tr": "Türkçe",
  "langName.ug": "Uygurca",
  "langName.uk": "Ukraynaca",
  "langName.ur": "Urduca",
  "langName.uz": "Özbekçe",
  "langName.vi": "Vietnamca",
  "langName.wo": "Wolof",
  "langName.yi": "Yidiş",
  "langName.yo": "Yoruba",
  "langName.yua": "Yukatek Maya",
  "langName.zh": "Çince",
  "langName.zh-cn": "Çince (Çin)",
  "langName.zh-hk": "Çince (Hong Kong)",
  "langName.zh-tw": "Çince (Tayvan)",
  "langName.zh-hans": "Çince, Basitleştirilmiş",
  "langName.zh-hant": "Çince, Geleneksel",
  "langName.zu": "Zulu"
});