tinymce.addI18n('tr_TR', {
  "-Language Not Set-": "-Dil Ayarlanmadı-",
  "Choose from list": "Listeden seç",
  "Choose languages": "Dilleri seç",
  "Choose up to six languages": "En fazla altı dil seçin",
  "Configure languages": "Dilleri yapılandır",
  "Current language:": "Geçerli dil:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Boşluk içermeyen geçerli bir dil kodu girin. Veya iptal'e basın.",
  "Enter manually": "El ile gir",
  "Enter new lang code (e.g., \"en-US\"):": "Yeni dil kodunu girin (örn. \"tr-TR\"):",
  "Indicate current language": "Geçerli dili belirt",
  "Manually enter language {{number}}:": "{{number}}. dili el ile girin:",
  "New Language:": "Yeni Dil:",
  "None": "Hiçbiri",
  "Other - Enter manually": "Diğer - El ile gir",
  "Really remove all language markup from the document?": "Belgeden tüm dil işaretlemesi gerçekten kaldırılsın mı?",
  "Remove All lang markup": "Tüm dil işaretlemesini kaldır",
  "Remove Language Markup": "Dil İşaretlemesini Kaldır",
  "Remove current lang value": "Geçerli dil değerini kaldır",
  "Reveal lang markup": "Dil işaretlemesini göster",
  "Select language {{number}}:": "{{number}}. dili seçin:",
  "Select the document's default language.": "Belgenin varsayılan dilini seçin.",
  "Set default document language": "Varsayılan belge dilini ayarla",
  "Set text language": "Metin dilini ayarla",
  "langName.af": "Afrikaanca",
  "langName.af-za": "Afrikaanca",
  "langName.ak": "Akan",
  "langName.am": "Amharca",
  "langName.ar": "Arapça",
  "langName.ar-eg": "",
  "langName.ar-ma": "",
  "langName.ar-sa": "Arapça",
  "langName.az": "Azerbaycan dili",
  "langName.be": "Belarusça",
  "langName.bg": "Bulgarca",
  "langName.bg-bg": "Bulgarca",
  "langName.bho": "Arayanice",
  "langName.bm": "Bambara",
  "langName.bn": "Bengalce",
  "langName.bo": "Tibetçe",
  "langName.bs": "Boşnakça",
  "langName.ca": "Katalanca",
  "langName.cop": "Kıptice",
  "langName.cr": "Krice",
  "langName.cs": "Çekçe",
  "langName.cu": "Kilise Slavcası",
  "langName.cy": "Galce",
  "langName.da": "Danca",
  "langName.de": "Almanca",
  "langName.de-at": "Avusturya Almancası",
  "langName.de-ch": "İsviçre Yüksek Almancası",
  "langName.de-de": "Almanca",
  "langName.dv": "Divehi dili",
  "langName.el": "Yunanca",
  "langName.en": "İngilizce",
  "langName.en-au": "Avustralya İngilizcesi",
  "langName.en-ca": "Kanada İngilizcesi",
  "langName.en-gb": "İngiliz İngilizcesi",
  "langName.en-ie": "İngilizce (İrlanda)",
  "langName.en-in": "İngilizce (Hindistan)",
  "langName.en-tt": "İngilizce (Trinidad)",
  "langName.en-us": "Amerikan İngilizcesi",
  "langName.en-za": "İngilizce (Güney Afrika)",
  "langName.eo": "Esperanto",
  "langName.es": "İspanyolca",
  "langName.es-ar": "İspanyolca (Arjantin)",
  "langName.es-cl": "İspanyolca (Şili)",
  "langName.es-co": "İspanyolca (Kolombiya)",
  "langName.es-cr": "",
  "langName.es-es": "Avrupa İspanyolcası",
  "langName.es-mx": "Meksika İspanyolcası",
  "langName.es-pe": "İspanyolca (Peru)",
  "langName.et": "Estonca",
  "langName.eu": "Baskça",
  "langName.fa": "Farsça",
  "langName.fa-af": "Darice",
  "langName.fa-ir": "Farsça",
  "langName.ff": "Fula dili",
  "langName.fi": "Fince",
  "langName.fi-fi": "Fince",
  "langName.fil": "Filipince",
  "langName.fr": "Fransızca",
  "langName.fr-be": "",
  "langName.fr-ca": "Kanada Fransızcası",
  "langName.fr-ch": "İsviçre Fransızcası",
  "langName.ga": "İrlandaca",
  "langName.gl": "Galiçyaca",
  "langName.grc": "Antik Yunanca",
  "langName.ha": "Hausa dili",
  "langName.he": "İbranice",
  "langName.he-il": "İbranice",
  "langName.hi": "Hintçe",
  "langName.hr": "Hırvatça",
  "langName.hr-hr": "Hırvatça",
  "langName.ht": "Haiti Kreyolu",
  "langName.hu": "Macarca",
  "langName.hu-hu": "Macarca",
  "langName.hy": "Ermenice",
  "langName.id": "Endonezce",
  "langName.ig": "İbo dili",
  "langName.is": "İzlandaca",
  "langName.it": "İtalyanca",
  "langName.it-it": "İtalyanca",
  "langName.iu": "İnuktitut dili",
  "langName.ja": "Japonca",
  "langName.ja-jp": "Japonca",
  "langName.ka": "Gürcüce",
  "langName.kab": "Kabiliyece",
  "langName.kk": "Kazakça",
  "langName.km": "Khmer dili",
  "langName.kn": "Kannada dili",
  "langName.ko": "Korece",
  "langName.ko-kr": "Korece",
  "langName.la": "Latince",
  "langName.lkt": "Lakotaca",
  "langName.lo": "Lao dili",
  "langName.lt": "Litvanca",
  "langName.lv": "Letonca",
  "langName.mi": "Maori dili",
  "langName.mn": "Moğolca",
  "langName.mr": "Marathi dili",
  "langName.ms": "Malayca",
  "langName.mt": "Maltaca",
  "langName.my": "Birman dili",
  "langName.nb": "Norveççe Bokmål",
  "langName.nb-no": "Norveççe Bokmål",
  "langName.ne": "Nepalce",
  "langName.nl": "Felemenkçe",
  "langName.nl-be": "Flamanca",
  "langName.nn": "Norveççe Nynorsk",
  "langName.nv": "Navaho dili",
  "langName.ota": "Osmanlı Türkçesi",
  "langName.pa": "Pencapça",
  "langName.peo": "Eski Farsça",
  "langName.pl": "Lehçe",
  "langName.ps": "Peştuca",
  "langName.pt": "Portekizce",
  "langName.pt-br": "Brezilya Portekizcesi",
  "langName.pt-pt": "Avrupa Portekizcesi",
  "langName.qu": "Keçuva dili",
  "langName.ro": "Rumence",
  "langName.ru": "Rusça",
  "langName.rw": "Kinyarwanda",
  "langName.sa": "Sanskrit",
  "langName.se": "Kuzey Laponcası",
  "langName.si": "Sinhali dili",
  "langName.sk-sk": "Slovakça",
  "langName.sl": "Slovence",
  "langName.sl-si": "Slovence",
  "langName.sma": "Güney Laponcası",
  "langName.sme": "Kuzey Sami",
  "langName.smj": "Lule Laponcası",
  "langName.sn": "Şona dili",
  "langName.sr": "Sırpça",
  "langName.sr-latn": "",
  "langName.sv": "İsveççe",
  "langName.sv-se": "İsveççe",
  "langName.sw": "Svahili dili",
  "langName.sw-ke": "Svahili dili",
  "langName.sw-tz": "Svahili dili",
  "langName.syc": "Klasik Süryanice",
  "langName.ta": "Tamilce",
  "langName.te": "Telugu dili",
  "langName.tg": "Tacikçe",
  "langName.th": "Tayca",
  "langName.th-th": "Tayca",
  "langName.tk": "Türkmence",
  "langName.tl": "Tagalogca",
  "langName.tr": "Türkçe",
  "langName.tr-tr": "Türkçe",
  "langName.tt": "Tatarca",
  "langName.ug": "Uygurca",
  "langName.uk": "Ukraynaca",
  "langName.ur": "Urduca",
  "langName.uz": "Özbekçe",
  "langName.vi": "Vietnamca",
  "langName.wo": "Volofça",
  "langName.xh": "Zosa dili",
  "langName.yi": "Yidiş",
  "langName.yo": "Yorubaca",
  "langName.yua": "Yukatek Maya",
  "langName.zh": "Çince",
  "langName.zh-cn": "Basitleştirilmiş Çince",
  "langName.zh-hans": "Basitleştirilmiş Çince",
  "langName.zh-hant": "Geleneksel Çince",
  "langName.zh-hk": "Çince (Hong Kong)",
  "langName.zh-sg": "",
  "langName.zh-tw": "Geleneksel Çince",
  "langName.zu": "Zuluca",
  "langName.zu-za": "Zuluca"
});