tinymce.addI18n('uk', {
  "Current language:": "Поточна мова:",
  "Set text language": "Встановити мову тексту",
  "-Language Not Set-": "-Мова Не Встановлена-",
  "Choose languages": "Вибрати мови",
  "Remove Language Markup": "Видалити Мовну Розмітку",
  "Remove current lang value": "Видалити поточне значення мови",
  "Remove All lang markup": "Видалити всю мовну розмітку",
  "Configure languages": "Налаштувати мови",
  "Set default document language": "Встановити мову документа за замовчуванням",
  "Reveal lang markup": "Показати мовну розмітку",
  "Indicate current language": "Вказати поточну мову",
  "Select the document's default language.": "Виберіть мову документа за замовчуванням.",
  "Choose from list": "Вибрати зі списку",
  "Enter manually": "Ввести вручну",
  "None": "Немає",
  "Other - Enter manually": "Інше - Ввести вручну",
  "New Language:": "Нова Мова:",
  "Enter new lang code (e.g., \"en-US\"):": "Введіть новий код мови (напр. \"uk-UA\"):",
  "Choose up to six languages": "Виберіть до шести мов",
  "Select language {{number}}:": "Вибрати мову {{number}}:",
  "Manually enter language {{number}}:": "Ввести мову {{number}} вручну:",
  "Really remove all language markup from the document?": "Дійсно видалити всю мовну розмітку з документа?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Введіть правильний код мови без пробілів. Або натисніть скасувати.",
  "langName.af": "Африкаанс",
  "langName.ak": "Акан",
  "langName.ar": "Арабська",
  "langName.az": "Азербайджанська",
  "langName.bg": "Болгарська",
  "langName.bho": "Бходжпурі",
  "langName.bm": "Бамбара",
  "langName.bn": "Бенгальська",
  "langName.bo": "Тибетська",
  "langName.bs": "Боснійська",
  "langName.ca": "Каталанська; Валенсійська",
  "langName.cs": "Чеська",
  "langName.cu": "Староболгарська",
  "langName.da": "Данська",
  "langName.de": "Німецька",
  "langName.el": "Грецька",
  "langName.en": "Англійська",
  "langName.en-au": "Англійська (Австралія)",
  "langName.en-gb": "Англійська (Велика Британія)",
  "langName.en-in": "Англійська (Індія)",
  "langName.en-ie": "Англійська (Ірландія)",
  "langName.en-tt": "Англійська (Тринідад)",
  "langName.en-us": "Англійська (США)",
  "langName.en-za": "Англійська (ПАР)",
  "langName.es": "Іспанська",
  "langName.es-ar": "Іспанська (Аргентина)",
  "langName.es-cl": "Іспанська (Чилі)",
  "langName.es-co": "Іспанська (Колумбія)",
  "langName.es-mx": "Іспанська (Мексика)",
  "langName.es-pe": "Іспанська (Перу)",
  "langName.et": "Естонська",
  "langName.eu": "Баскська",
  "langName.fa": "Перська",
  "langName.fi": "Фінська",
  "langName.fr": "Французька",
  "langName.fr-ca": "Французька (Канада)",
  "langName.gl": "Галісійська (Іспанія)",
  "langName.he": "Іврит",
  "langName.hi": "Хінді",
  "langName.hr": "Хорватська",
  "langName.hu": "Угорська",
  "langName.id": "Індонезійська",
  "langName.it": "Італійська",
  "langName.ja": "Японська",
  "langName.kk": "Казахська",
  "langName.kn": "Каннада",
  "langName.ko": "Корейська",
  "langName.la": "Латинська",
  "langName.lkt": "Лакота",
  "langName.mn": "Монгольська",
  "langName.mr": "Маратхі",
  "langName.nb": "Норвезька Букмол",
  "langName.nl": "Нідерландська",
  "langName.nl-be": "Нідерландська (Бельгія)",
  "langName.nn": "Норвезька Нюношк",
  "langName.pl": "Польська",
  "langName.ps": "Пушту",
  "langName.pt": "Португальська Міжнародна",
  "langName.pt-br": "Португальська (Бразилія)",
  "langName.qu": "Кечуа",
  "langName.ro": "Румунська",
  "langName.ru": "Російська",
  "langName.sa": "Санскрит",
  "langName.sk-sk": "Словацька",
  "langName.sl": "Словенська",
  "langName.sma": "Південносаамська",
  "langName.sme": "Північносаамська",
  "langName.smj": "Луле-саамська",
  "langName.sr": "Сербська",
  "langName.sv": "Шведська",
  "langName.sw": "Суахілі",
  "langName.ta": "Тамільська",
  "langName.te": "Телугу",
  "langName.tg": "Таджицька",
  "langName.th": "Тайська",
  "langName.tr": "Турецька",
  "langName.ug": "Уйгурська",
  "langName.uk": "Українська",
  "langName.ur": "Урду",
  "langName.uz": "Узбецька",
  "langName.vi": "В'єтнамська",
  "langName.wo": "Волоф",
  "langName.yi": "Їдиш",
  "langName.yo": "Йоруба",
  "langName.yua": "Юкатекська майя",
  "langName.zh": "Китайська",
  "langName.zh-cn": "Китайська (Китай)",
  "langName.zh-hk": "Китайська (Гонконг)",
  "langName.zh-tw": "Китайська (Тайвань)",
  "langName.zh-hans": "Китайська Спрощена",
  "langName.zh-hant": "Китайська Традиційна",
  "langName.zu": "Зулу"
});