tinymce.addI18n('uk', {
  "-Language Not Set-": "-Мова Не Встановлена-",
  "Choose from list": "Вибрати зі списку",
  "Choose languages": "Вибрати мови",
  "Choose up to six languages": "Виберіть до шести мов",
  "Configure languages": "Налаштувати мови",
  "Current language:": "Поточна мова:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Введіть правильний код мови без пробілів. Або натисніть скасувати.",
  "Enter manually": "Ввести вручну",
  "Enter new lang code (e.g., \"en-US\"):": "Введіть новий код мови (напр. \"uk-UA\"):",
  "Indicate current language": "Вказати поточну мову",
  "Manually enter language {{number}}:": "Ввести мову {{number}} вручну:",
  "New Language:": "Нова Мова:",
  "None": "Немає",
  "Other - Enter manually": "Інше - Ввести вручну",
  "Really remove all language markup from the document?": "Дійсно видалити всю мовну розмітку з документа?",
  "Remove All lang markup": "Видалити всю мовну розмітку",
  "Remove Language Markup": "Видалити Мовну Розмітку",
  "Remove current lang value": "Видалити поточне значення мови",
  "Reveal lang markup": "Показати мовну розмітку",
  "Select language {{number}}:": "Вибрати мову {{number}}:",
  "Select the document's default language.": "Виберіть мову документа за замовчуванням.",
  "Set default document language": "Встановити мову документа за замовчуванням",
  "Set text language": "Встановити мову тексту",
  "langName.af": "африкаанс",
  "langName.af-za": "африкаанс (ПАР)",
  "langName.ak": "акан",
  "langName.am": "амхарська",
  "langName.ar": "арабська",
  "langName.ar-eg": "арабська (Єгипет)",
  "langName.ar-ma": "арабська (Марокко)",
  "langName.ar-sa": "арабська (Саудівська Аравія)",
  "langName.az": "азербайджанська",
  "langName.be": "білоруська",
  "langName.bg": "болгарська",
  "langName.bg-bg": "болгарська (Болгарія)",
  "langName.bho": "бходжпурі",
  "langName.bm": "бамбара",
  "langName.bn": "бенгальська",
  "langName.bo": "тибетська",
  "langName.bs": "боснійська",
  "langName.ca": "каталонська",
  "langName.cop": "коптська",
  "langName.cr": "крі",
  "langName.cs": "чеська",
  "langName.cu": "церковнословʼянська",
  "langName.cy": "валлійська",
  "langName.da": "данська",
  "langName.de": "німецька",
  "langName.de-at": "німецька (Австрія)",
  "langName.de-ch": "німецька (Швейцарія)",
  "langName.de-de": "німецька (Німеччина)",
  "langName.dv": "дивехі",
  "langName.el": "грецька",
  "langName.en": "англійська",
  "langName.en-au": "англійська (Австралія)",
  "langName.en-ca": "англійська (Канада)",
  "langName.en-gb": "англійська (Велика Британія)",
  "langName.en-ie": "англійська (Ірландія)",
  "langName.en-in": "англійська (Індія)",
  "langName.en-tt": "англійська (Тринідад)",
  "langName.en-us": "англійська (США)",
  "langName.en-za": "англійська (Південна Африка)",
  "langName.eo": "есперанто",
  "langName.es": "іспанська",
  "langName.es-ar": "іспанська (Аргентина)",
  "langName.es-cl": "іспанська (Чилі)",
  "langName.es-co": "іспанська (Колумбія)",
  "langName.es-cr": "іспанська (Коста-Ріка)",
  "langName.es-es": "іспанська (Іспанія)",
  "langName.es-mx": "іспанська (Мексика)",
  "langName.es-pe": "іспанська (Перу)",
  "langName.et": "естонська",
  "langName.eu": "баскська",
  "langName.fa": "перська",
  "langName.fa-af": "дарі",
  "langName.fa-ir": "перська (Іран)",
  "langName.ff": "фула",
  "langName.fi": "фінська",
  "langName.fi-fi": "фінська (Фінляндія)",
  "langName.fil": "філіппінська",
  "langName.fr": "французька",
  "langName.fr-be": "французька (Бельгія)",
  "langName.fr-ca": "французька (Канада)",
  "langName.fr-ch": "французька (Швейцарія)",
  "langName.ga": "ірландська",
  "langName.gl": "галісійська",
  "langName.grc": "грецька (давня)",
  "langName.ha": "хауса",
  "langName.he": "іврит",
  "langName.he-il": "іврит (Ізраїль)",
  "langName.hi": "гінді",
  "langName.hr": "хорватська",
  "langName.hr-hr": "хорватська (Хорватія)",
  "langName.ht": "гаїтянська креольська",
  "langName.hu": "угорська",
  "langName.hu-hu": "угорська (Угорщина)",
  "langName.hy": "вірменська",
  "langName.id": "індонезійська",
  "langName.ig": "ігбо",
  "langName.is": "ісландська",
  "langName.it": "італійська",
  "langName.it-it": "італійська (Італія)",
  "langName.iu": "інуктитут",
  "langName.ja": "японська",
  "langName.ja-jp": "японська (Японія)",
  "langName.ka": "грузинська",
  "langName.kab": "кабільська",
  "langName.kk": "казахська",
  "langName.km": "кхмерська",
  "langName.kn": "каннада",
  "langName.ko": "корейська",
  "langName.ko-kr": "корейська (Корея)",
  "langName.la": "латинська",
  "langName.lkt": "лакота",
  "langName.lo": "лаоська",
  "langName.lt": "литовська",
  "langName.lv": "латиська",
  "langName.mi": "маорі",
  "langName.mn": "монгольська",
  "langName.mr": "маратхі",
  "langName.ms": "малайська",
  "langName.mt": "мальтійська",
  "langName.my": "бірманська",
  "langName.nb": "норвезька (букмол)",
  "langName.nb-no": "норвезька (букмол, Норвегія)",
  "langName.ne": "непальська",
  "langName.nl": "нідерландська",
  "langName.nl-be": "фламандська",
  "langName.nn": "норвезька (нюношк)",
  "langName.nv": "навахо",
  "langName.ota": "турецька (османська)",
  "langName.pa": "панджабі",
  "langName.peo": "перська (давня)",
  "langName.pl": "польська",
  "langName.ps": "пушту",
  "langName.pt": "португальська",
  "langName.pt-br": "португальська (Бразилія)",
  "langName.pt-pt": "португальська (Португалія)",
  "langName.qu": "кечуа",
  "langName.ro": "румунська",
  "langName.ru": "російська",
  "langName.rw": "кіньяруанда",
  "langName.sa": "санскрит",
  "langName.se": "саамська (північна)",
  "langName.si": "сингальська",
  "langName.sk": "словацька",
  "langName.sk-sk": "словацька (Словаччина)",
  "langName.sl": "словенська",
  "langName.sl-si": "словенська (Словенія)",
  "langName.sma": "саамська (південна)",
  "langName.sme": "саамська (північна)",
  "langName.smj": "саамська (луле)",
  "langName.sn": "шона",
  "langName.sr": "сербська",
  "langName.sr-latn": "сербська (латиниця)",
  "langName.sv": "шведська",
  "langName.sv-se": "шведська (Швеція)",
  "langName.sw": "суахілі",
  "langName.sw-ke": "суахілі (Кенія)",
  "langName.sw-tz": "суахілі (Танзанія)",
  "langName.syc": "сирійська (класична)",
  "langName.ta": "тамільська",
  "langName.te": "телугу",
  "langName.tg": "таджицька",
  "langName.th": "тайська",
  "langName.th-th": "тайська (Таїланд)",
  "langName.tk": "туркменська",
  "langName.tl": "тагальська",
  "langName.tr": "турецька",
  "langName.tr-tr": "турецька (Туреччина)",
  "langName.tt": "татарська",
  "langName.ug": "уйгурська",
  "langName.uk": "українська",
  "langName.ur": "урду",
  "langName.uz": "узбецька",
  "langName.vi": "вʼєтнамська",
  "langName.wo": "волоф",
  "langName.xh": "кхоса",
  "langName.yi": "їдиш",
  "langName.yo": "йоруба",
  "langName.yua": "майя (юкатек)",
  "langName.zh": "китайська",
  "langName.zh-cn": "китайська (спрощене письмо)",
  "langName.zh-hans": "китайська (спрощене письмо)",
  "langName.zh-hant": "китайська (традиційне письмо)",
  "langName.zh-hk": "китайська (Гонконг)",
  "langName.zh-sg": "китайська (Сінгапур)",
  "langName.zh-tw": "китайська (Тайвань)",
  "langName.zu": "зулуська",
  "langName.zu-za": "зулуська (ПАР)"
});