tinymce.addI18n('vi', {
  "-Language Not Set-": "-Chưa Đặt Ngôn Ngữ-",
  "Choose from list": "Chọn từ danh sách",
  "Choose languages": "Chọn ngôn ngữ",
  "Choose up to six languages": "Chọn tối đa sáu ngôn ngữ",
  "Configure languages": "Cấu hình ngôn ngữ",
  "Current language:": "Ngôn ngữ hiện tại:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Nhập mã ngôn ngữ hợp lệ không có khoảng trắng. Hoặc nhấn hủy.",
  "Enter manually": "Nhập thủ công",
  "Enter new lang code (e.g., \"en-US\"):": "Nhập mã ngôn ngữ mới (ví dụ: \"vi-VN\"):",
  "Indicate current language": "Chỉ ra ngôn ngữ hiện tại",
  "Manually enter language {{number}}:": "Nhập thủ công ngôn ngữ {{number}}:",
  "New Language:": "Ngôn Ngữ Mới:",
  "None": "Không có",
  "Other - Enter manually": "Khác - Nhập thủ công",
  "Really remove all language markup from the document?": "Có thực sự xóa tất cả đánh dấu ngôn ngữ khỏi tài liệu không?",
  "Remove All lang markup": "Xóa tất cả đánh dấu ngôn ngữ",
  "Remove Language Markup": "Xóa Đánh Dấu Ngôn Ngữ",
  "Remove current lang value": "Xóa giá trị ngôn ngữ hiện tại",
  "Reveal lang markup": "Hiển thị đánh dấu ngôn ngữ",
  "Select language {{number}}:": "Chọn ngôn ngữ {{number}}:",
  "Select the document's default language.": "Chọn ngôn ngữ mặc định của tài liệu.",
  "Set default document language": "Đặt ngôn ngữ mặc định của tài liệu",
  "Set text language": "Đặt ngôn ngữ văn bản",
  "langName.af": "Tiếng Afrikaans",
  "langName.af-za": "Tiếng Afrikaans",
  "langName.ak": "Tiếng Akan",
  "langName.am": "Tiếng Amharic",
  "langName.ar": "Tiếng Ả Rập",
  "langName.ar-eg": "Tiếng Ả Rập Ai Cập",
  "langName.ar-ma": "Tiếng Ả Rập Morocco",
  "langName.ar-sa": "Tiếng Ả Rập (Ả Rập Saudi)",
  "langName.az": "Tiếng Azerbaijan",
  "langName.be": "Tiếng Belarus",
  "langName.bg": "Tiếng Bulgaria",
  "langName.bg-bg": "Tiếng Bulgaria",
  "langName.bho": "Tiếng Bhojpuri",
  "langName.bm": "Tiếng Bambara",
  "langName.bn": "Tiếng Bangla",
  "langName.bo": "Tiếng Tây Tạng",
  "langName.bs": "Tiếng Bosnia",
  "langName.ca": "Tiếng Catalan",
  "langName.cop": "Tiếng Coptic",
  "langName.cr": "Tiếng Cree",
  "langName.cs": "Tiếng Séc",
  "langName.cu": "Tiếng Slavơ Nhà thờ",
  "langName.cy": "Tiếng Wales",
  "langName.da": "Tiếng Đan Mạch",
  "langName.de": "Tiếng Đức",
  "langName.de-at": "Tiếng Đức Áo",
  "langName.de-ch": "Tiếng Đức Thụy Sĩ",
  "langName.de-de": "Tiếng Đức (Đức)",
  "langName.dv": "Tiếng Divehi",
  "langName.el": "Tiếng Hy Lạp",
  "langName.en": "Tiếng Anh",
  "langName.en-au": "Tiếng Anh (Úc)",
  "langName.en-ca": "Tiếng Anh Canada",
  "langName.en-gb": "Tiếng Anh (Anh)",
  "langName.en-ie": "Tiếng Anh (Ireland)",
  "langName.en-in": "Tiếng Anh (Ấn Độ)",
  "langName.en-tt": "Tiếng Anh (Trinidad)",
  "langName.en-us": "Tiếng Anh Mỹ",
  "langName.en-za": "Tiếng Anh (Nam Phi)",
  "langName.eo": "Tiếng Quốc Tế Ngữ",
  "langName.es": "Tiếng Tây Ban Nha",
  "langName.es-ar": "Tiếng Tây Ban Nha (Argentina)",
  "langName.es-cl": "Tiếng Tây Ban Nha (Chile)",
  "langName.es-co": "Tiếng Tây Ban Nha (Colombia)",
  "langName.es-cr": "Tiếng Tây Ban Nha (Costa Rica)",
  "langName.es-es": "Tiếng Tây Ban Nha Châu Âu",
  "langName.es-mx": "Tiếng Tây Ban Nha Mexico",
  "langName.es-pe": "Tiếng Tây Ban Nha (Peru)",
  "langName.et": "Tiếng Estonia",
  "langName.eu": "Tiếng Basque",
  "langName.fa": "Tiếng Ba Tư",
  "langName.fa-af": "Tiếng Dari",
  "langName.fa-ir": "Tiếng Ba Tư (Iran)",
  "langName.ff": "Tiếng Fulah",
  "langName.fi": "Tiếng Phần Lan",
  "langName.fi-fi": "Tiếng Phần Lan",
  "langName.fil": "Tiếng Philippines",
  "langName.fr": "Tiếng Pháp",
  "langName.fr-be": "Tiếng Pháp Bỉ",
  "langName.fr-ca": "Tiếng Pháp Canada",
  "langName.fr-ch": "Tiếng Pháp Thụy Sĩ",
  "langName.ga": "Tiếng Ireland",
  "langName.gl": "Tiếng Galician",
  "langName.grc": "Tiếng Hy Lạp cổ",
  "langName.ha": "Tiếng Hausa",
  "langName.he": "Tiếng Do Thái",
  "langName.he-il": "Tiếng Do Thái",
  "langName.hi": "Tiếng Hindi",
  "langName.hr": "Tiếng Croatia",
  "langName.hr-hr": "Tiếng Croatia",
  "langName.ht": "Tiếng Creole Haiti",
  "langName.hu": "Tiếng Hungary",
  "langName.hu-hu": "Tiếng Hungary",
  "langName.hy": "Tiếng Armenia",
  "langName.id": "Tiếng Indonesia",
  "langName.ig": "Tiếng Igbo",
  "langName.is": "Tiếng Iceland",
  "langName.it": "Tiếng Italy",
  "langName.it-it": "Tiếng Italy",
  "langName.iu": "Tiếng Inuktitut",
  "langName.ja": "Tiếng Nhật",
  "langName.ja-jp": "Tiếng Nhật",
  "langName.ka": "Tiếng Georgia",
  "langName.kab": "Tiếng Kabyle",
  "langName.kk": "Tiếng Kazakh",
  "langName.km": "Tiếng Khmer",
  "langName.kn": "Tiếng Kannada",
  "langName.ko": "Tiếng Hàn",
  "langName.ko-kr": "Tiếng Hàn",
  "langName.la": "Tiếng La-tinh",
  "langName.lkt": "Tiếng Lakota",
  "langName.lo": "Tiếng Lào",
  "langName.lt": "Tiếng Litva",
  "langName.lv": "Tiếng Latvia",
  "langName.mi": "Tiếng Māori",
  "langName.mn": "Tiếng Mông Cổ",
  "langName.mr": "Tiếng Marathi",
  "langName.ms": "Tiếng Mã Lai",
  "langName.mt": "Tiếng Malta",
  "langName.my": "Tiếng Miến Điện",
  "langName.nb": "Tiếng Na Uy (Bokmål)",
  "langName.nb-no": "Tiếng Na Uy Bokmål",
  "langName.ne": "Tiếng Nepal",
  "langName.nl": "Tiếng Hà Lan",
  "langName.nl-be": "Tiếng Flemish",
  "langName.nn": "Tiếng Na Uy (Nynorsk)",
  "langName.nv": "Tiếng Navajo",
  "langName.ota": "Tiếng Thổ Nhĩ Kỳ Ottoman",
  "langName.pa": "Tiếng Punjab",
  "langName.peo": "Tiếng Ba Tư cổ",
  "langName.pl": "Tiếng Ba Lan",
  "langName.ps": "Tiếng Pashto",
  "langName.pt": "Tiếng Bồ Đào Nha",
  "langName.pt-br": "Tiếng Bồ Đào Nha Brazil",
  "langName.pt-pt": "Tiếng Bồ Đào Nha Châu Âu",
  "langName.qu": "Tiếng Quechua",
  "langName.ro": "Tiếng Romania",
  "langName.ru": "Tiếng Nga",
  "langName.rw": "Tiếng Kinyarwanda",
  "langName.sa": "Tiếng Phạn",
  "langName.se": "Tiếng Sami Miền Bắc",
  "langName.si": "Tiếng Sinhala",
  "langName.sk-sk": "Tiếng Slovak",
  "langName.sl": "Tiếng Slovenia",
  "langName.sl-si": "Tiếng Slovenia",
  "langName.sma": "Tiếng Sami Miền Nam",
  "langName.sme": "Tiếng Sami Miền Bắc",
  "langName.smj": "Tiếng Lule Sami",
  "langName.sn": "Tiếng Shona",
  "langName.sr": "Tiếng Serbia",
  "langName.sr-latn": "Tiếng Serbia (La-tinh)",
  "langName.sv": "Tiếng Thụy Điển",
  "langName.sv-se": "Tiếng Thụy Điển",
  "langName.sw": "Tiếng Swahili",
  "langName.sw-ke": "Tiếng Swahili (Kenya)",
  "langName.sw-tz": "Tiếng Swahili (Tanzania)",
  "langName.syc": "Tiếng Syriac cổ",
  "langName.ta": "Tiếng Tamil",
  "langName.te": "Tiếng Telugu",
  "langName.tg": "Tiếng Tajik",
  "langName.th": "Tiếng Thái",
  "langName.th-th": "Tiếng Thái",
  "langName.tk": "Tiếng Turkmen",
  "langName.tl": "Tiếng Tagalog",
  "langName.tr": "Tiếng Thổ Nhĩ Kỳ",
  "langName.tr-tr": "Tiếng Thổ Nhĩ Kỳ",
  "langName.tt": "Tiếng Tatar",
  "langName.ug": "Tiếng Uyghur",
  "langName.uk": "Tiếng Ukraina",
  "langName.ur": "Tiếng Urdu",
  "langName.uz": "Tiếng Uzbek",
  "langName.vi": "Tiếng Việt",
  "langName.wo": "Tiếng Wolof",
  "langName.xh": "Tiếng Xhosa",
  "langName.yi": "Tiếng Yiddish",
  "langName.yo": "Tiếng Yoruba",
  "langName.yua": "Tiếng Maya Yucatec",
  "langName.zh": "Tiếng Trung",
  "langName.zh-cn": "Tiếng Trung (Trung Quốc)",
  "langName.zh-hans": "Tiếng Trung Giản thể",
  "langName.zh-hant": "Tiếng Trung Phồn thể",
  "langName.zh-hk": "Tiếng Trung (Hồng Kông)",
  "langName.zh-sg": "Tiếng Trung (Singapore)",
  "langName.zh-tw": "Tiếng Trung (Đài Loan)",
  "langName.zu": "Tiếng Zulu",
  "langName.zu-za": "Tiếng Zulu"
});