tinymce.addI18n('vi_VN', {
  "-Language Not Set-": "-Chưa Đặt Ngôn Ngữ-",
  "Choose from list": "Chọn từ danh sách",
  "Choose languages": "Chọn ngôn ngữ",
  "Choose up to six languages": "Chọn tối đa sáu ngôn ngữ",
  "Configure languages": "Cấu hình ngôn ngữ",
  "Current language:": "Ngôn ngữ hiện tại:",
  "Enter a valid language code with no spaces. Or, press cancel.": "Nhập mã ngôn ngữ hợp lệ không có khoảng trắng. Hoặc nhấn hủy.",
  "Enter manually": "Nhập thủ công",
  "Enter new lang code (e.g., \"en-US\"):": "Nhập mã ngôn ngữ mới (ví dụ: \"vi-VN\"):",
  "Indicate current language": "Chỉ ra ngôn ngữ hiện tại",
  "Manually enter language {{number}}:": "Nhập thủ công ngôn ngữ {{number}}:",
  "New Language:": "Ngôn Ngữ Mới:",
  "None": "Không có",
  "Other - Enter manually": "Khác - Nhập thủ công",
  "Really remove all language markup from the document?": "Có thực sự xóa tất cả đánh dấu ngôn ngữ khỏi tài liệu không?",
  "Remove All lang markup": "Xóa tất cả đánh dấu ngôn ngữ",
  "Remove Language Markup": "Xóa Đánh Dấu Ngôn Ngữ",
  "Remove current lang value": "Xóa giá trị ngôn ngữ hiện tại",
  "Reveal lang markup": "Hiển thị đánh dấu ngôn ngữ",
  "Select language {{number}}:": "Chọn ngôn ngữ {{number}}:",
  "Select the document's default language.": "Chọn ngôn ngữ mặc định của tài liệu.",
  "Set default document language": "Đặt ngôn ngữ mặc định của tài liệu",
  "Set text language": "Đặt ngôn ngữ văn bản",
  "Afrikaans": "Tiếng Afrikaans",
  "Afrikaans": "Tiếng Afrikaans (Nam Phi)",
  "Akan": "Tiếng Akan",
  "Amharic": "Tiếng Amharic",
  "Arabic": "Tiếng Ả Rập",
  "Arabic (Egypt)": "Tiếng Ả Rập (Ai Cập)",
  "Arabic (Morocco)": "Tiếng Ả Rập (Morocco)",
  "Arabic (Saudi Arabia)": "Tiếng Ả Rập (Ả Rập Saudi)",
  "Azerbaijani": "Tiếng Azerbaijan",
  "Belarusian": "Tiếng Belarus",
  "Bulgarian": "Tiếng Bulgaria",
  "Bulgarian (Bulgaria)": "Tiếng Bulgaria (Bulgaria)",
  "Bhojpuri": "Tiếng Bhojpuri",
  "Bambara": "Tiếng Bambara",
  "Bangla": "Tiếng Bangla",
  "Tibetan": "Tiếng Tây Tạng",
  "Bosnian": "Tiếng Bosnia",
  "Catalan": "Tiếng Catalan",
  "Coptic": "Tiếng Coptic",
  "Cree": "Tiếng Cree",
  "Czech": "Tiếng Séc",
  "Church Slavic": "Tiếng Slavơ Nhà thờ",
  "Welsh": "Tiếng Wales",
  "Danish": "Tiếng Đan Mạch",
  "German": "Tiếng Đức",
  "German (Austria)": "Tiếng Đức (Áo)",
  "German (Switzerland)": "Tiếng Đức (Thụy Sĩ)",
  "German (Germany)": "Tiếng Đức (Đức)",
  "Divehi": "Tiếng Divehi",
  "Greek": "Tiếng Hy Lạp",
  "English": "Tiếng Anh",
  "English (Australia)": "Tiếng Anh (Úc)",
  "English (Canada)": "Tiếng Anh (Canada)",
  "English (United Kingdom)": "Tiếng Anh (Vương quốc Anh)",
  "English (Ireland)": "Tiếng Anh (Ireland)",
  "English (India)": "Tiếng Anh (Ấn Độ)",
  "English (Trinidad)": "Tiếng Anh (Trinidad)",
  "English (United States)": "Tiếng Anh (Hoa Kỳ)",
  "English (South Africa)": "Tiếng Anh (Nam Phi)",
  "Esperanto": "Tiếng Quốc Tế Ngữ",
  "Spanish": "Tiếng Tây Ban Nha",
  "Spanish (Argentina)": "Tiếng Tây Ban Nha (Argentina)",
  "Spanish (Chile)": "Tiếng Tây Ban Nha (Chile)",
  "Spanish (Colombia)": "Tiếng Tây Ban Nha (Colombia)",
  "Spanish (Costa Rica)": "Tiếng Tây Ban Nha (Costa Rica)",
  "Spanish (Spain)": "Tiếng Tây Ban Nha (Tây Ban Nha)",
  "Spanish (Mexico)": "Tiếng Tây Ban Nha (Mexico)",
  "Spanish (Peru)": "Tiếng Tây Ban Nha (Peru)",
  "Estonian": "Tiếng Estonia",
  "Basque": "Tiếng Basque",
  "Persian": "Tiếng Ba Tư",
  "Dari": "Tiếng Dari",
  "Persian (Iran)": "Tiếng Ba Tư (Iran)",
  "Fula": "Tiếng Fulah",
  "Finnish": "Tiếng Phần Lan",
  "Finnish (Finland)": "Tiếng Phần Lan (Phần Lan)",
  "Filipino": "Tiếng Philippines",
  "French": "Tiếng Pháp",
  "French (Belgium)": "Tiếng Pháp (Bỉ)",
  "French (Canada)": "Tiếng Pháp (Canada)",
  "French (Switzerland)": "Tiếng Pháp (Thụy Sĩ)",
  "Irish": "Tiếng Ireland",
  "Galician": "Tiếng Galician",
  "Greek (Ancient)": "Tiếng Hy Lạp (cổ)",
  "Hausa": "Tiếng Hausa",
  "Hebrew": "Tiếng Do Thái",
  "Hebrew (Israel)": "Tiếng Do Thái (Israel)",
  "Hindi": "Tiếng Hindi",
  "Croatian": "Tiếng Croatia",
  "Croatian (Croatia)": "Tiếng Croatia (Croatia)",
  "Haitian Creole": "Tiếng Creole Haiti",
  "Hungarian": "Tiếng Hungary",
  "Hungarian (Hungary)": "Tiếng Hungary (Hungary)",
  "Armenian": "Tiếng Armenia",
  "Indonesian": "Tiếng Indonesia",
  "Igbo": "Tiếng Igbo",
  "Icelandic": "Tiếng Iceland",
  "Italian": "Tiếng Italy",
  "Italian (Italy)": "Tiếng Italy (Italy)",
  "Inuktitut": "Tiếng Inuktitut",
  "Japanese": "Tiếng Nhật",
  "Japanese (Japan)": "Tiếng Nhật (Nhật Bản)",
  "Georgian": "Tiếng Georgia",
  "Kabyle": "Tiếng Kabyle",
  "Kazakh": "Tiếng Kazakh",
  "Khmer": "Tiếng Khmer",
  "Kannada": "Tiếng Kannada",
  "Korean": "Tiếng Hàn",
  "Korean (Korea)": "Tiếng Hàn (Hàn Quốc)",
  "Latin": "Tiếng La-tinh",
  "Lakota": "Tiếng Lakota",
  "Lao": "Tiếng Lào",
  "Lithuanian": "Tiếng Litva",
  "Latvian": "Tiếng Latvia",
  "Māori": "Tiếng Māori",
  "Mongolian": "Tiếng Mông Cổ",
  "Marathi": "Tiếng Marathi",
  "Malay": "Tiếng Mã Lai",
  "Maltese": "Tiếng Malta",
  "Burmese": "Tiếng Miến Điện",
  "Norwegian (Bokmål)": "Tiếng Na Uy (Bokmål)",
  "Norwegian (Bokmål, Norway)": "Tiếng Na Uy (Bokmål, Na Uy)",
  "Nepali": "Tiếng Nepal",
  "Dutch": "Tiếng Hà Lan",
  "Flemish": "Tiếng Flemish",
  "Norwegian (Nynorsk)": "Tiếng Na Uy (Nynorsk)",
  "Navajo": "Tiếng Navajo",
  "Turkish (Ottoman)": "Tiếng Thổ Nhĩ Kỳ (Ottoman)",
  "Punjabi": "Tiếng Punjab",
  "Persian (Old)": "Tiếng Ba Tư (cổ)",
  "Polish": "Tiếng Ba Lan",
  "Pashto": "Tiếng Pashto",
  "Portuguese": "Tiếng Bồ Đào Nha",
  "Portuguese (Brazil)": "Tiếng Bồ Đào Nha (Brazil)",
  "Portuguese (Portugal)": "Tiếng Bồ Đào Nha (Bồ Đào Nha)",
  "Quechua": "Tiếng Quechua",
  "Romanian": "Tiếng Romania",
  "Russian": "Tiếng Nga",
  "Kinyarwanda": "Tiếng Kinyarwanda",
  "Sanskrit": "Tiếng Phạn",
  "Sami (Northern)": "Tiếng Sami (Miền Bắc)",
  "Sinhala": "Tiếng Sinhala",
  "Slovak": "Tiếng Slovak",
  "Slovak (Slovakia)": "Tiếng Slovak (Slovakia)",
  "Slovenian": "Tiếng Slovenia",
  "Slovenian (Slovenia)": "Tiếng Slovenia (Slovenia)",
  "Sami (Southern)": "Tiếng Sami (Miền Nam)",
  "Sami (Northern)": "Tiếng Sami (Miền Bắc)",
  "Sami (Lule)": "Tiếng Sami (Lule)",
  "Shona": "Tiếng Shona",
  "Serbian": "Tiếng Serbia",
  "Serbian (Latin)": "Tiếng Serbia (La-tinh)",
  "Swedish": "Tiếng Thụy Điển",
  "Swedish (Sweden)": "Tiếng Thụy Điển (Thụy Điển)",
  "Swahili": "Tiếng Swahili",
  "Swahili (Kenya)": "Tiếng Swahili (Kenya)",
  "Swahili (Tanzania)": "Tiếng Swahili (Tanzania)",
  "Syriac (Classical)": "Tiếng Syriac (cổ)",
  "Tamil": "Tiếng Tamil",
  "Telugu": "Tiếng Telugu",
  "Tajik": "Tiếng Tajik",
  "Thai": "Tiếng Thái",
  "Thai (Thailand)": "Tiếng Thái (Thái Lan)",
  "Turkmen": "Tiếng Turkmen",
  "Tagalog": "Tiếng Tagalog",
  "Turkish": "Tiếng Thổ Nhĩ Kỳ",
  "Turkish (Turkey)": "Tiếng Thổ Nhĩ Kỳ (Thổ Nhĩ Kỳ)",
  "Tatar": "Tiếng Tatar",
  "Uyghur": "Tiếng Uyghur",
  "Ukrainian": "Tiếng Ukraina",
  "Urdu": "Tiếng Urdu",
  "Uzbek": "Tiếng Uzbek",
  "Vietnamese": "Tiếng Việt",
  "Wolof": "Tiếng Wolof",
  "Xhosa": "Tiếng Xhosa",
  "Yiddish": "Tiếng Yiddish",
  "Yoruba": "Tiếng Yoruba",
  "Maya (Yucatec)": "Tiếng Maya (Yucatec)",
  "Chinese": "Tiếng Trung",
  "Chinese (Simplified)": "Tiếng Trung (Giản thể)",
  "Chinese (Simplified)": "Tiếng Trung (Giản thể)",
  "Chinese (Traditional)": "Tiếng Trung (Phồn thể)",
  "Chinese (Hong Kong)": "Tiếng Trung (Hồng Kông)",
  "Chinese (Singapore)": "Tiếng Trung (Singapore)",
  "Chinese (Traditional)": "Tiếng Trung (Đài Loan)",
  "Zulu": "Tiếng Zulu",
  "Zulu": "Tiếng Zulu (Nam Phi)"
});