tinymce.addI18n("vi_VN", {
  "Current language:": "Ngôn ngữ hiện tại:",
  "Set text language": "Đặt ngôn ngữ văn bản",
  "-Language Not Set-": "-Chưa Đặt Ngôn Ngữ-",
  "Choose languages": "Chọn ngôn ngữ",
  "Remove Language Markup": "Xóa Đánh Dấu Ngôn Ngữ",
  "Remove current lang value": "Xóa giá trị ngôn ngữ hiện tại",
  "Remove All lang markup": "Xóa tất cả đánh dấu ngôn ngữ",
  "Configure languages": "Cấu hình ngôn ngữ",
  "Set default document language": "Đặt ngôn ngữ mặc định của tài liệu",
  "Reveal lang markup": "Hiển thị đánh dấu ngôn ngữ",
  "Indicate current language": "Chỉ ra ngôn ngữ hiện tại",
  "Select the document's default language.": "Chọn ngôn ngữ mặc định của tài liệu.",
  "Choose from list": "Chọn từ danh sách",
  "Enter manually": "Nhập thủ công",
  "None": "Không có",
  "Other - Enter manually": "Khác - Nhập thủ công",
  "New Language:": "Ngôn Ngữ Mới:",
  "Enter new lang code (e.g., \"en-US\"):": "Nhập mã ngôn ngữ mới (ví dụ: \"vi-VN\"):",
  "Choose up to six languages": "Chọn tối đa sáu ngôn ngữ",
  "Select language {{number}}:": "Chọn ngôn ngữ {{number}}:",
  "Manually enter language {{number}}:": "Nhập thủ công ngôn ngữ {{number}}:",
  "Really remove all language markup from the document?": "Có thực sự xóa tất cả đánh dấu ngôn ngữ khỏi tài liệu không?",
  "Enter a valid language code with no spaces. Or, press cancel.": "Nhập mã ngôn ngữ hợp lệ không có khoảng trắng. Hoặc nhấn hủy.",
  "langName.af": "Tiếng Afrikaans",
  "langName.ak": "Tiếng Akan",
  "langName.ar": "Tiếng Ả Rập",
  "langName.az": "Tiếng Azerbaijan",
  "langName.bg": "Tiếng Bulgaria",
  "langName.bho": "Tiếng Bhojpuri",
  "langName.bm": "Tiếng Bambara",
  "langName.bn": "Tiếng Bengal",
  "langName.bo": "Tiếng Tây Tạng",
  "langName.bs": "Tiếng Bosnia",
  "langName.ca": "Tiếng Catalan; Valencia",
  "langName.cs": "Tiếng Séc",
  "langName.cu": "Tiếng Bulgaria Cổ",
  "langName.da": "Tiếng Đan Mạch",
  "langName.de": "Tiếng Đức",
  "langName.el": "Tiếng Hy Lạp",
  "langName.en": "Tiếng Anh",
  "langName.en-au": "Tiếng Anh (Úc)",
  "langName.en-gb": "Tiếng Anh (Vương Quốc Anh)",
  "langName.en-in": "Tiếng Anh (Ấn Độ)",
  "langName.en-ie": "Tiếng Anh (Ireland)",
  "langName.en-tt": "Tiếng Anh (Trinidad)",
  "langName.en-us": "Tiếng Anh (Hoa Kỳ)",
  "langName.en-za": "Tiếng Anh (Nam Phi)",
  "langName.es": "Tiếng Tây Ban Nha",
  "langName.es-ar": "Tiếng Tây Ban Nha (Argentina)",
  "langName.es-cl": "Tiếng Tây Ban Nha (Chile)",
  "langName.es-co": "Tiếng Tây Ban Nha (Colombia)",
  "langName.es-mx": "Tiếng Tây Ban Nha (Mexico)",
  "langName.es-pe": "Tiếng Tây Ban Nha (Peru)",
  "langName.et": "Tiếng Estonia",
  "langName.eu": "Tiếng Basque",
  "langName.fa": "Tiếng Ba Tư",
  "langName.fi": "Tiếng Phần Lan",
  "langName.fr": "Tiếng Pháp",
  "langName.fr-ca": "Tiếng Pháp (Canada)",
  "langName.gl": "Tiếng Galicia (Tây Ban Nha)",
  "langName.he": "Tiếng Hebrew",
  "langName.hi": "Tiếng Hindi",
  "langName.hr": "Tiếng Croatia",
  "langName.hu": "Tiếng Hungary",
  "langName.id": "Tiếng Indonesia",
  "langName.it": "Tiếng Ý",
  "langName.ja": "Tiếng Nhật",
  "langName.kk": "Tiếng Kazakh",
  "langName.kn": "Tiếng Kannada",
  "langName.ko": "Tiếng Hàn",
  "langName.la": "Tiếng Latin",
  "langName.lkt": "Tiếng Lakota",
  "langName.mn": "Tiếng Mông Cổ",
  "langName.mr": "Tiếng Marathi",
  "langName.nb": "Tiếng Na Uy Bokmål",
  "langName.nl": "Tiếng Hà Lan",
  "langName.nl-be": "Tiếng Hà Lan (Bỉ)",
  "langName.nn": "Tiếng Na Uy Nynorsk",
  "langName.pl": "Tiếng Ba Lan",
  "langName.ps": "Tiếng Pashto",
  "langName.pt": "Tiếng Bồ Đào Nha, Quốc tế",
  "langName.pt-br": "Tiếng Bồ Đào Nha (Brazil)",
  "langName.qu": "Tiếng Quechua",
  "langName.ro": "Tiếng Romania",
  "langName.ru": "Tiếng Nga",
  "langName.sa": "Tiếng Sanskrit",
  "langName.sk-sk": "Tiếng Slovakia",
  "langName.sl": "Tiếng Slovenia",
  "langName.sma": "Tiếng Sami Phía Nam",
  "langName.sme": "Tiếng Sami Phía Bắc",
  "langName.smj": "Tiếng Sami Lule",
  "langName.sr": "Tiếng Serbia",
  "langName.sv": "Tiếng Thụy Điển",
  "langName.sw": "Tiếng Swahili",
  "langName.ta": "Tiếng Tamil",
  "langName.te": "Tiếng Telugu",
  "langName.tg": "Tiếng Tajik",
  "langName.th": "Tiếng Thái",
  "langName.tr": "Tiếng Thổ Nhĩ Kỳ",
  "langName.ug": "Tiếng Uyghur",
  "langName.uk": "Tiếng Ukraine",
  "langName.ur": "Tiếng Urdu",
  "langName.uz": "Tiếng Uzbek",
  "langName.vi": "Tiếng Việt",
  "langName.wo": "Tiếng Wolof",
  "langName.yi": "Tiếng Yiddish",
  "langName.yo": "Tiếng Yoruba",
  "langName.yua": "Tiếng Maya Yucatec",
  "langName.zh": "Tiếng Trung",
  "langName.zh-cn": "Tiếng Trung (Trung Quốc)",
  "langName.zh-hk": "Tiếng Trung (Hồng Kông)",
  "langName.zh-tw": "Tiếng Trung (Đài Loan)",
  "langName.zh-hans": "Tiếng Trung, Giản thể",
  "langName.zh-hant": "Tiếng Trung, Phồn thể",
  "langName.zu": "Tiếng Zulu"
});