tinymce.addI18n('zh', {
  "Current language:": "当前语言：",
  "Set text language": "设置文本语言",
  "-Language Not Set-": "-未设置语言-",
  "Choose languages": "选择语言",
  "Remove Language Markup": "移除语言标记",
  "Remove current lang value": "移除当前语言值",
  "Remove All lang markup": "移除所有语言标记",
  "Configure languages": "配置语言",
  "Set default document language": "设置默认文档语言",
  "Reveal lang markup": "显示语言标记",
  "Indicate current language": "指示当前语言",
  "Select the document's default language.": "选择文档的默认语言。",
  "Choose from list": "从列表中选择",
  "Enter manually": "手动输入",
  "None": "无",
  "Other - Enter manually": "其他 - 手动输入",
  "New Language:": "新语言：",
  "Enter new lang code (e.g., \"en-US\"):": "输入新的语言代码（例如：\"en-US\"）：",
  "Choose up to six languages": "最多选择六种语言",
  "Select language {{number}}:": "选择语言{{number}}：",
  "Manually enter language {{number}}:": "手动输入语言{{number}}：",
  "Really remove all language markup from the document?": "确定要从文档中移除所有语言标记吗？",
  "Enter a valid language code with no spaces. Or, press cancel.": "请输入有效的语言代码，不能包含空格。或者按取消。",
  "langName.af": "南非荷兰语",
  "langName.ak": "阿肯语",
  "langName.ar": "阿拉伯语",
  "langName.az": "阿塞拜疆语",
  "langName.bg": "保加利亚语",
  "langName.bho": "博杰普尔语",
  "langName.bm": "班巴拉语",
  "langName.bn": "孟加拉语",
  "langName.bo": "藏语",
  "langName.bs": "波斯尼亚语",
  "langName.ca": "加泰罗尼亚语；巴伦西亚语",
  "langName.cs": "捷克语",
  "langName.cu": "古保加利亚语",
  "langName.da": "丹麦语",
  "langName.de": "德语",
  "langName.el": "希腊语",
  "langName.en": "英语",
  "langName.en-au": "英语（澳大利亚）",
  "langName.en-gb": "英语（英国）",
  "langName.en-in": "英语（印度）",
  "langName.en-ie": "英语（爱尔兰）",
  "langName.en-tt": "英语（特立尼达）",
  "langName.en-us": "英语（美国）",
  "langName.en-za": "英语（南非）",
  "langName.es": "西班牙语",
  "langName.es-ar": "西班牙语（阿根廷）",
  "langName.es-cl": "西班牙语（智利）",
  "langName.es-co": "西班牙语（哥伦比亚）",
  "langName.es-mx": "西班牙语（墨西哥）",
  "langName.es-pe": "西班牙语（秘鲁）",
  "langName.et": "爱沙尼亚语",
  "langName.eu": "巴斯克语",
  "langName.fa": "波斯语",
  "langName.fi": "芬兰语",
  "langName.fr": "法语",
  "langName.fr-ca": "法语（加拿大）",
  "langName.gl": "加利西亚语（西班牙）",
  "langName.he": "希伯来语",
  "langName.hi": "印地语",
  "langName.hr": "克罗地亚语",
  "langName.hu": "匈牙利语",
  "langName.id": "印度尼西亚语",
  "langName.it": "意大利语",
  "langName.ja": "日语",
  "langName.kk": "哈萨克语",
  "langName.kn": "卡纳达语",
  "langName.ko": "韩语",
  "langName.la": "拉丁语",
  "langName.lkt": "拉科塔语",
  "langName.mn": "蒙古语",
  "langName.mr": "马拉地语",
  "langName.nb": "挪威博克马尔语",
  "langName.nl": "荷兰语",
  "langName.nl-be": "荷兰语（比利时）",
  "langName.nn": "挪威新挪威语",
  "langName.pl": "波兰语",
  "langName.ps": "普什图语",
  "langName.pt": "葡萄牙语（国际）",
  "langName.pt-br": "葡萄牙语（巴西）",
  "langName.qu": "克丘亚语",
  "langName.ro": "罗马尼亚语",
  "langName.ru": "俄语",
  "langName.sa": "梵语",
  "langName.sk-sk": "斯洛伐克语",
  "langName.sl": "斯洛文尼亚语",
  "langName.sma": "南萨米语",
  "langName.sme": "北萨米语",
  "langName.smj": "吕勒萨米语",
  "langName.sr": "塞尔维亚语",
  "langName.sv": "瑞典语",
  "langName.sw": "斯瓦希里语",
  "langName.ta": "泰米尔语",
  "langName.te": "泰卢固语",
  "langName.tg": "塔吉克语",
  "langName.th": "泰语",
  "langName.tr": "土耳其语",
  "langName.ug": "维吾尔语",
  "langName.uk": "乌克兰语",
  "langName.ur": "乌尔都语",
  "langName.uz": "乌兹别克语",
  "langName.vi": "越南语",
  "langName.wo": "沃洛夫语",
  "langName.yi": "意第绪语",
  "langName.yo": "约鲁巴语",
  "langName.yua": "尤卡坦玛雅语",
  "langName.zh": "中文",
  "langName.zh-cn": "中文（中国）",
  "langName.zh-hk": "中文（香港）",
  "langName.zh-tw": "中文（台湾）",
  "langName.zh-hans": "中文（简体）",
  "langName.zh-hant": "中文（繁体）",
  "langName.zu": "祖鲁语"
});