tinymce.addI18n('zh_CN', {
  "-Language Not Set-": "-未设置语言-",
  "Choose from list": "从列表中选择",
  "Choose languages": "选择语言",
  "Choose up to six languages": "最多选择六种语言",
  "Configure languages": "配置语言",
  "Current language:": "当前语言：",
  "Enter a valid language code with no spaces. Or, press cancel.": "请输入有效的语言代码，不能包含空格。或者按取消。",
  "Enter manually": "手动输入",
  "Enter new lang code (e.g., \"en-US\"):": "输入新的语言代码（例如：\"zh-CN\"）：",
  "Indicate current language": "指示当前语言",
  "Manually enter language {{number}}:": "手动输入语言{{number}}：",
  "New Language:": "新语言：",
  "None": "无",
  "Other - Enter manually": "其他 - 手动输入",
  "Really remove all language markup from the document?": "确定要从文档中移除所有语言标记吗？",
  "Remove All lang markup": "移除所有语言标记",
  "Remove Language Markup": "移除语言标记",
  "Remove current lang value": "移除当前语言值",
  "Reveal lang markup": "显示语言标记",
  "Select language {{number}}:": "选择语言{{number}}：",
  "Select the document's default language.": "选择文档的默认语言。",
  "Set default document language": "设置默认文档语言",
  "Set text language": "设置文本语言",
  "langName.af": "南非荷兰语",
  "langName.af-za": "南非荷兰语（南非）",
  "langName.ak": "阿肯语",
  "langName.am": "阿姆哈拉语",
  "langName.ar": "阿拉伯语",
  "langName.ar-eg": "阿拉伯语（埃及）",
  "langName.ar-ma": "阿拉伯语（摩洛哥）",
  "langName.ar-sa": "阿拉伯语（沙特阿拉伯）",
  "langName.az": "阿塞拜疆语",
  "langName.be": "白俄罗斯语",
  "langName.bg": "保加利亚语",
  "langName.bg-bg": "保加利亚语（保加利亚）",
  "langName.bho": "博杰普尔语",
  "langName.bm": "班巴拉语",
  "langName.bn": "孟加拉语",
  "langName.bo": "藏语",
  "langName.bs": "波斯尼亚语",
  "langName.ca": "加泰罗尼亚语",
  "langName.cop": "科普特语",
  "langName.cr": "克里语",
  "langName.cs": "捷克语",
  "langName.cu": "教会斯拉夫语",
  "langName.cy": "威尔士语",
  "langName.da": "丹麦语",
  "langName.de": "德语",
  "langName.de-at": "德语（奥地利）",
  "langName.de-ch": "德语（瑞士）",
  "langName.de-de": "德语（德国）",
  "langName.dv": "迪维希语",
  "langName.el": "希腊语",
  "langName.en": "英语",
  "langName.en-au": "英语（澳大利亚）",
  "langName.en-ca": "英语（加拿大）",
  "langName.en-gb": "英语（英国）",
  "langName.en-ie": "英语（爱尔兰）",
  "langName.en-in": "英语（印度）",
  "langName.en-tt": "英语（特立尼达）",
  "langName.en-us": "英语（美国）",
  "langName.en-za": "英语（南非）",
  "langName.eo": "世界语",
  "langName.es": "西班牙语",
  "langName.es-ar": "西班牙语（阿根廷）",
  "langName.es-cl": "西班牙语（智利）",
  "langName.es-co": "西班牙语（哥伦比亚）",
  "langName.es-cr": "西班牙语（哥斯达黎加）",
  "langName.es-es": "西班牙语（西班牙）",
  "langName.es-mx": "西班牙语（墨西哥）",
  "langName.es-pe": "西班牙语（秘鲁）",
  "langName.et": "爱沙尼亚语",
  "langName.eu": "巴斯克语",
  "langName.fa": "波斯语",
  "langName.fa-af": "达里语",
  "langName.fa-ir": "波斯语（伊朗）",
  "langName.ff": "富拉语",
  "langName.fi": "芬兰语",
  "langName.fi-fi": "芬兰语（芬兰）",
  "langName.fil": "菲律宾语",
  "langName.fr": "法语",
  "langName.fr-be": "法语（比利时）",
  "langName.fr-ca": "法语（加拿大）",
  "langName.fr-ch": "法语（瑞士）",
  "langName.ga": "爱尔兰语",
  "langName.gl": "加利西亚语",
  "langName.grc": "希腊语（古代）",
  "langName.ha": "豪萨语",
  "langName.he": "希伯来语",
  "langName.he-il": "希伯来语（以色列）",
  "langName.hi": "印地语",
  "langName.hr": "克罗地亚语",
  "langName.hr-hr": "克罗地亚语（克罗地亚）",
  "langName.ht": "海地克里奥尔语",
  "langName.hu": "匈牙利语",
  "langName.hu-hu": "匈牙利语（匈牙利）",
  "langName.hy": "亚美尼亚语",
  "langName.id": "印度尼西亚语",
  "langName.ig": "伊博语",
  "langName.is": "冰岛语",
  "langName.it": "意大利语",
  "langName.it-it": "意大利语（意大利）",
  "langName.iu": "因纽特语",
  "langName.ja": "日语",
  "langName.ja-jp": "日语（日本）",
  "langName.ka": "格鲁吉亚语",
  "langName.kab": "卡拜尔语",
  "langName.kk": "哈萨克语",
  "langName.km": "高棉语",
  "langName.kn": "卡纳达语",
  "langName.ko": "韩语",
  "langName.ko-kr": "韩语（韩国）",
  "langName.la": "拉丁语",
  "langName.lkt": "拉科塔语",
  "langName.lo": "老挝语",
  "langName.lt": "立陶宛语",
  "langName.lv": "拉脱维亚语",
  "langName.mi": "毛利语",
  "langName.mn": "蒙古语",
  "langName.mr": "马拉地语",
  "langName.ms": "马来语",
  "langName.mt": "马耳他语",
  "langName.my": "缅甸语",
  "langName.nb": "挪威语（博克马尔）",
  "langName.nb-no": "挪威语（博克马尔，挪威）",
  "langName.ne": "尼泊尔语",
  "langName.nl": "荷兰语",
  "langName.nl-be": "佛兰德语",
  "langName.nn": "挪威语（新挪威语）",
  "langName.nv": "纳瓦霍语",
  "langName.ota": "土耳其语（奥斯曼）",
  "langName.pa": "旁遮普语",
  "langName.peo": "波斯语（古代）",
  "langName.pl": "波兰语",
  "langName.ps": "普什图语",
  "langName.pt": "葡萄牙语",
  "langName.pt-br": "葡萄牙语（巴西）",
  "langName.pt-pt": "葡萄牙语（葡萄牙）",
  "langName.qu": "克丘亚语",
  "langName.ro": "罗马尼亚语",
  "langName.ru": "俄语",
  "langName.rw": "卢旺达语",
  "langName.sa": "梵语",
  "langName.se": "萨米语（北部）",
  "langName.si": "僧伽罗语",
  "langName.sk": "斯洛伐克语",
  "langName.sk-sk": "斯洛伐克语（斯洛伐克）",
  "langName.sl": "斯洛文尼亚语",
  "langName.sl-si": "斯洛文尼亚语（斯洛文尼亚）",
  "langName.sma": "萨米语（南部）",
  "langName.sme": "萨米语（北部）",
  "langName.smj": "萨米语（吕勒）",
  "langName.sn": "绍纳语",
  "langName.sr": "塞尔维亚语",
  "langName.sr-latn": "塞尔维亚语（拉丁文）",
  "langName.sv": "瑞典语",
  "langName.sv-se": "瑞典语（瑞典）",
  "langName.sw": "斯瓦希里语",
  "langName.sw-ke": "斯瓦希里语（肯尼亚）",
  "langName.sw-tz": "斯瓦希里语（坦桑尼亚）",
  "langName.syc": "叙利亚语（古典）",
  "langName.ta": "泰米尔语",
  "langName.te": "泰卢固语",
  "langName.tg": "塔吉克语",
  "langName.th": "泰语",
  "langName.th-th": "泰语（泰国）",
  "langName.tk": "土库曼语",
  "langName.tl": "他加禄语",
  "langName.tr": "土耳其语",
  "langName.tr-tr": "土耳其语（土耳其）",
  "langName.tt": "鞑靼语",
  "langName.ug": "维吾尔语",
  "langName.uk": "乌克兰语",
  "langName.ur": "乌尔都语",
  "langName.uz": "乌兹别克语",
  "langName.vi": "越南语",
  "langName.wo": "沃洛夫语",
  "langName.xh": "科萨语",
  "langName.yi": "意第绪语",
  "langName.yo": "约鲁巴语",
  "langName.yua": "玛雅语（尤卡坦）",
  "langName.zh": "中文",
  "langName.zh-cn": "中文（简体）",
  "langName.zh-hans": "中文（简体）",
  "langName.zh-hant": "中文（繁体）",
  "langName.zh-hk": "中文（香港）",
  "langName.zh-sg": "中文（新加坡）",
  "langName.zh-tw": "中文（繁体）",
  "langName.zu": "祖鲁语",
  "langName.zu-za": "祖鲁语（南非）"
});