tinymce.addI18n('zh_Hant', {
  "Current language:": "目前語言：",
  "Set text language": "設定文字語言",
  "-Language Not Set-": "-未設定語言-",
  "Choose languages": "選擇語言",
  "Remove Language Markup": "移除語言標記",
  "Remove current lang value": "移除目前語言值",
  "Remove All lang markup": "移除所有語言標記",
  "Configure languages": "設定語言",
  "Set default document language": "設定預設文件語言",
  "Reveal lang markup": "顯示語言標記",
  "Indicate current language": "指示目前語言",
  "Select the document's default language.": "選擇文件的預設語言。",
  "Choose from list": "從清單中選擇",
  "Enter manually": "手動輸入",
  "None": "無",
  "Other - Enter manually": "其他 - 手動輸入",
  "New Language:": "新語言：",
  "Enter new lang code (e.g., \"en-US\"):": "輸入新的語言代碼（例如：\"en-US\"）：",
  "Choose up to six languages": "最多選擇六種語言",
  "Select language {{number}}:": "選擇語言{{number}}：",
  "Manually enter language {{number}}:": "手動輸入語言{{number}}：",
  "Really remove all language markup from the document?": "確定要從文件中移除所有語言標記嗎？",
  "Enter a valid language code with no spaces. Or, press cancel.": "請輸入有效的語言代碼，不能包含空格。或者按取消。",
  "langName.af": "南非荷蘭語",
  "langName.ak": "阿肯語",
  "langName.ar": "阿拉伯語",
  "langName.az": "亞塞拜然語",
  "langName.bg": "保加利亞語",
  "langName.bho": "博傑普爾語",
  "langName.bm": "班巴拉語",
  "langName.bn": "孟加拉語",
  "langName.bo": "藏語",
  "langName.bs": "波士尼亞語",
  "langName.ca": "加泰隆尼亞語；瓦倫西亞語",
  "langName.cs": "捷克語",
  "langName.cu": "古保加利亞語",
  "langName.da": "丹麥語",
  "langName.de": "德語",
  "langName.el": "希臘語",
  "langName.en": "英語",
  "langName.en-au": "英語（澳洲）",
  "langName.en-gb": "英語（英國）",
  "langName.en-in": "英語（印度）",
  "langName.en-ie": "英語（愛爾蘭）",
  "langName.en-tt": "英語（千里達）",
  "langName.en-us": "英語（美國）",
  "langName.en-za": "英語（南非）",
  "langName.es": "西班牙語",
  "langName.es-ar": "西班牙語（阿根廷）",
  "langName.es-cl": "西班牙語（智利）",
  "langName.es-co": "西班牙語（哥倫比亞）",
  "langName.es-mx": "西班牙語（墨西哥）",
  "langName.es-pe": "西班牙語（祕魯）",
  "langName.et": "愛沙尼亞語",
  "langName.eu": "巴斯克語",
  "langName.fa": "波斯語",
  "langName.fi": "芬蘭語",
  "langName.fr": "法語",
  "langName.fr-ca": "法語（加拿大）",
  "langName.gl": "加利西亞語（西班牙）",
  "langName.he": "希伯來語",
  "langName.hi": "印地語",
  "langName.hr": "克羅埃西亞語",
  "langName.hu": "匈牙利語",
  "langName.id": "印尼語",
  "langName.it": "義大利語",
  "langName.ja": "日語",
  "langName.kk": "哈薩克語",
  "langName.kn": "卡納達語",
  "langName.ko": "韓語",
  "langName.la": "拉丁語",
  "langName.lkt": "拉科塔語",
  "langName.mn": "蒙古語",
  "langName.mr": "馬拉地語",
  "langName.nb": "挪威博克馬爾語",
  "langName.nl": "荷蘭語",
  "langName.nl-be": "荷蘭語（比利時）",
  "langName.nn": "挪威新挪威語",
  "langName.pl": "波蘭語",
  "langName.ps": "普什圖語",
  "langName.pt": "葡萄牙語（國際）",
  "langName.pt-br": "葡萄牙語（巴西）",
  "langName.qu": "克丘亞語",
  "langName.ro": "羅馬尼亞語",
  "langName.ru": "俄語",
  "langName.sa": "梵語",
  "langName.sk-sk": "斯洛伐克語",
  "langName.sl": "斯洛維尼亞語",
  "langName.sma": "南薩米語",
  "langName.sme": "北薩米語",
  "langName.smj": "呂勒薩米語",
  "langName.sr": "塞爾維亞語",
  "langName.sv": "瑞典語",
  "langName.sw": "斯瓦希里語",
  "langName.ta": "泰米爾語",
  "langName.te": "泰盧固語",
  "langName.tg": "塔吉克語",
  "langName.th": "泰語",
  "langName.tr": "土耳其語",
  "langName.ug": "維吾爾語",
  "langName.uk": "烏克蘭語",
  "langName.ur": "烏爾都語",
  "langName.uz": "烏茲別克語",
  "langName.vi": "越南語",
  "langName.wo": "沃洛夫語",
  "langName.yi": "意第緒語",
  "langName.yo": "約魯巴語",
  "langName.yua": "尤卡坦馬雅語",
  "langName.zh": "中文",
  "langName.zh-cn": "中文（中國）",
  "langName.zh-hk": "中文（香港）",
  "langName.zh-tw": "中文（台灣）",
  "langName.zh-hans": "中文（簡體）",
  "langName.zh-hant": "中文（繁體）",
  "langName.zu": "祖魯語"
});