tinymce.addI18n('zh_TW', {
  "-Language Not Set-": "-未設定語言-",
  "Choose from list": "從清單中選擇",
  "Choose languages": "選擇語言",
  "Choose up to six languages": "最多選擇六種語言",
  "Configure languages": "設定語言",
  "Current language:": "目前語言：",
  "Enter a valid language code with no spaces. Or, press cancel.": "請輸入有效的語言代碼，不能包含空格。或者按取消。",
  "Enter manually": "手動輸入",
  "Enter new lang code (e.g., \"en-US\"):": "輸入新的語言代碼（例如：\"zh-TW\"）：",
  "Indicate current language": "指示目前語言",
  "Manually enter language {{number}}:": "手動輸入語言{{number}}：",
  "New Language:": "新語言：",
  "None": "無",
  "Other - Enter manually": "其他 - 手動輸入",
  "Really remove all language markup from the document?": "確定要從文件中移除所有語言標記嗎？",
  "Remove All lang markup": "移除所有語言標記",
  "Remove Language Markup": "移除語言標記",
  "Remove current lang value": "移除目前語言值",
  "Reveal lang markup": "顯示語言標記",
  "Select language {{number}}:": "選擇語言{{number}}：",
  "Select the document's default language.": "選擇文件的預設語言。",
  "Set default document language": "設定預設文件語言",
  "Set text language": "設定文字語言",
  "langName.af": "南非荷蘭文",
  "langName.af-za": "南非荷蘭文（南非）",
  "langName.ak": "阿坎文",
  "langName.am": "阿姆哈拉文",
  "langName.ar": "阿拉伯文",
  "langName.ar-eg": "阿拉伯文（埃及）",
  "langName.ar-ma": "阿拉伯文（摩洛哥）",
  "langName.ar-sa": "阿拉伯文（沙烏地阿拉伯）",
  "langName.az": "亞塞拜然文",
  "langName.be": "白俄羅斯文",
  "langName.bg": "保加利亞文",
  "langName.bg-bg": "保加利亞文（保加利亞）",
  "langName.bho": "博傑普爾文",
  "langName.bm": "班巴拉文",
  "langName.bn": "孟加拉文",
  "langName.bo": "藏文",
  "langName.bs": "波士尼亞文",
  "langName.ca": "加泰蘭文",
  "langName.cop": "科普特文",
  "langName.cr": "克里文",
  "langName.cs": "捷克文",
  "langName.cu": "宗教斯拉夫文",
  "langName.cy": "威爾斯文",
  "langName.da": "丹麥文",
  "langName.de": "德文",
  "langName.de-at": "德文（奧地利）",
  "langName.de-ch": "德文（瑞士）",
  "langName.de-de": "德文（德國）",
  "langName.dv": "迪維西文",
  "langName.el": "希臘文",
  "langName.en": "英文",
  "langName.en-au": "英文（澳洲）",
  "langName.en-ca": "英文（加拿大）",
  "langName.en-gb": "英文（英國）",
  "langName.en-ie": "英文（愛爾蘭）",
  "langName.en-in": "英文（印度）",
  "langName.en-tt": "英文（千里達）",
  "langName.en-us": "英文（美國）",
  "langName.en-za": "英文（南非）",
  "langName.eo": "世界文",
  "langName.es": "西班牙文",
  "langName.es-ar": "西班牙文（阿根廷）",
  "langName.es-cl": "西班牙文（智利）",
  "langName.es-co": "西班牙文（哥倫比亞）",
  "langName.es-cr": "西班牙文（哥斯大黎加）",
  "langName.es-es": "西班牙文（西班牙）",
  "langName.es-mx": "西班牙文（墨西哥）",
  "langName.es-pe": "西班牙文（祕魯）",
  "langName.et": "愛沙尼亞文",
  "langName.eu": "巴斯克文",
  "langName.fa": "波斯文",
  "langName.fa-af": "達里文",
  "langName.fa-ir": "波斯文（伊朗）",
  "langName.ff": "富拉文",
  "langName.fi": "芬蘭文",
  "langName.fi-fi": "芬蘭文（芬蘭）",
  "langName.fil": "菲律賓文",
  "langName.fr": "法文",
  "langName.fr-be": "法文（比利時）",
  "langName.fr-ca": "法文（加拿大）",
  "langName.fr-ch": "法文（瑞士）",
  "langName.ga": "愛爾蘭文",
  "langName.gl": "加利西亞文",
  "langName.grc": "希臘文（古代）",
  "langName.ha": "豪薩文",
  "langName.he": "希伯來文",
  "langName.he-il": "希伯來文（以色列）",
  "langName.hi": "印地文",
  "langName.hr": "克羅埃西亞文",
  "langName.hr-hr": "克羅埃西亞文（克羅埃西亞）",
  "langName.ht": "海地克里奧爾文",
  "langName.hu": "匈牙利文",
  "langName.hu-hu": "匈牙利文（匈牙利）",
  "langName.hy": "亞美尼亞文",
  "langName.id": "印尼文",
  "langName.ig": "伊布文",
  "langName.is": "冰島文",
  "langName.it": "義大利文",
  "langName.it-it": "義大利文（義大利）",
  "langName.iu": "因紐特文",
  "langName.ja": "日文",
  "langName.ja-jp": "日文（日本）",
  "langName.ka": "喬治亞文",
  "langName.kab": "卡比爾文",
  "langName.kk": "哈薩克文",
  "langName.km": "高棉文",
  "langName.kn": "坎那達文",
  "langName.ko": "韓文",
  "langName.ko-kr": "韓文（韓國）",
  "langName.la": "拉丁文",
  "langName.lkt": "拉科塔文",
  "langName.lo": "寮文",
  "langName.lt": "立陶宛文",
  "langName.lv": "拉脫維亞文",
  "langName.mi": "毛利文",
  "langName.mn": "蒙古文",
  "langName.mr": "馬拉地文",
  "langName.ms": "馬來文",
  "langName.mt": "馬爾他文",
  "langName.my": "緬甸文",
  "langName.nb": "挪威文（博克馬爾）",
  "langName.nb-no": "挪威文（博克馬爾，挪威）",
  "langName.ne": "尼泊爾文",
  "langName.nl": "荷蘭文",
  "langName.nl-be": "佛蘭德文",
  "langName.nn": "挪威文（新挪威文）",
  "langName.nv": "納瓦荷文",
  "langName.ota": "土耳其文（鄂圖曼）",
  "langName.pa": "旁遮普文",
  "langName.peo": "波斯文（古代）",
  "langName.pl": "波蘭文",
  "langName.ps": "普什圖文",
  "langName.pt": "葡萄牙文",
  "langName.pt-br": "葡萄牙文（巴西）",
  "langName.pt-pt": "葡萄牙文（葡萄牙）",
  "langName.qu": "蓋楚瓦文",
  "langName.ro": "羅馬尼亞文",
  "langName.ru": "俄文",
  "langName.rw": "盧安達文",
  "langName.sa": "梵文",
  "langName.se": "薩米文（北部）",
  "langName.si": "僧伽羅文",
  "langName.sk": "斯洛伐克文",
  "langName.sk-sk": "斯洛伐克文（斯洛伐克）",
  "langName.sl": "斯洛維尼亞文",
  "langName.sl-si": "斯洛維尼亞文（斯洛維尼亞）",
  "langName.sma": "薩米文（南部）",
  "langName.sme": "薩米文（北部）",
  "langName.smj": "薩米文（魯勒）",
  "langName.sn": "紹納文",
  "langName.sr": "塞爾維亞文",
  "langName.sr-latn": "塞爾維亞文（拉丁文）",
  "langName.sv": "瑞典文",
  "langName.sv-se": "瑞典文（瑞典）",
  "langName.sw": "史瓦希里文",
  "langName.sw-ke": "史瓦希里文（肯亞）",
  "langName.sw-tz": "史瓦希里文（坦尚尼亞）",
  "langName.syc": "敘利亞文（古代）",
  "langName.ta": "坦米爾文",
  "langName.te": "泰盧固文",
  "langName.tg": "塔吉克文",
  "langName.th": "泰文",
  "langName.th-th": "泰文（泰國）",
  "langName.tk": "土庫曼文",
  "langName.tl": "塔加路族文",
  "langName.tr": "土耳其文",
  "langName.tr-tr": "土耳其文（土耳其）",
  "langName.tt": "韃靼文",
  "langName.ug": "維吾爾文",
  "langName.uk": "烏克蘭文",
  "langName.ur": "烏都文",
  "langName.uz": "烏茲別克文",
  "langName.vi": "越南文",
  "langName.wo": "沃洛夫文",
  "langName.xh": "科薩文",
  "langName.yi": "意第緒文",
  "langName.yo": "約魯巴文",
  "langName.yua": "馬雅文（尤卡坦）",
  "langName.zh": "中文",
  "langName.zh-cn": "中文（簡體）",
  "langName.zh-hans": "中文（簡體）",
  "langName.zh-hant": "中文（繁體）",
  "langName.zh-hk": "中文（香港）",
  "langName.zh-sg": "中文（新加坡）",
  "langName.zh-tw": "中文（繁體）",
  "langName.zu": "祖魯文",
  "langName.zu-za": "祖魯文（南非）"
});