tinymce.addI18n('zh_TW', {
  "-Language Not Set-": "-未設定語言-",
  "Choose from list": "從清單中選擇",
  "Choose languages": "選擇語言",
  "Choose up to six languages": "最多選擇六種語言",
  "Configure languages": "設定語言",
  "Current language:": "目前語言：",
  "Enter a valid language code with no spaces. Or, press cancel.": "請輸入有效的語言代碼，不能包含空格。或者按取消。",
  "Enter manually": "手動輸入",
  "Enter new lang code (e.g., \"en-US\"):": "輸入新的語言代碼（例如：\"zh-TW\"）：",
  "Indicate current language": "指示目前語言",
  "Manually enter language {{number}}:": "手動輸入語言{{number}}：",
  "New Language:": "新語言：",
  "None": "無",
  "Other - Enter manually": "其他 - 手動輸入",
  "Really remove all language markup from the document?": "確定要從文件中移除所有語言標記嗎？",
  "Remove All lang markup": "移除所有語言標記",
  "Remove Language Markup": "移除語言標記",
  "Remove current lang value": "移除目前語言值",
  "Reveal lang markup": "顯示語言標記",
  "Select language {{number}}:": "選擇語言{{number}}：",
  "Select the document's default language.": "選擇文件的預設語言。",
  "Set default document language": "設定預設文件語言",
  "Set text language": "設定文字語言",
  "Afrikaans": "南非荷蘭文",
  "Afrikaans": "南非荷蘭文（南非）",
  "Akan": "阿坎文",
  "Amharic": "阿姆哈拉文",
  "Arabic": "阿拉伯文",
  "Arabic (Egypt)": "阿拉伯文（埃及）",
  "Arabic (Morocco)": "阿拉伯文（摩洛哥）",
  "Arabic (Saudi Arabia)": "阿拉伯文（沙烏地阿拉伯）",
  "Azerbaijani": "亞塞拜然文",
  "Belarusian": "白俄羅斯文",
  "Bulgarian": "保加利亞文",
  "Bulgarian (Bulgaria)": "保加利亞文（保加利亞）",
  "Bhojpuri": "博傑普爾文",
  "Bambara": "班巴拉文",
  "Bangla": "孟加拉文",
  "Tibetan": "藏文",
  "Bosnian": "波士尼亞文",
  "Catalan": "加泰蘭文",
  "Coptic": "科普特文",
  "Cree": "克里文",
  "Czech": "捷克文",
  "Church Slavic": "宗教斯拉夫文",
  "Welsh": "威爾斯文",
  "Danish": "丹麥文",
  "German": "德文",
  "German (Austria)": "德文（奧地利）",
  "German (Switzerland)": "德文（瑞士）",
  "German (Germany)": "德文（德國）",
  "Divehi": "迪維西文",
  "Greek": "希臘文",
  "English": "英文",
  "English (Australia)": "英文（澳洲）",
  "English (Canada)": "英文（加拿大）",
  "English (United Kingdom)": "英文（英國）",
  "English (Ireland)": "英文（愛爾蘭）",
  "English (India)": "英文（印度）",
  "English (Trinidad)": "英文（千里達）",
  "English (United States)": "英文（美國）",
  "English (South Africa)": "英文（南非）",
  "Esperanto": "世界文",
  "Spanish": "西班牙文",
  "Spanish (Argentina)": "西班牙文（阿根廷）",
  "Spanish (Chile)": "西班牙文（智利）",
  "Spanish (Colombia)": "西班牙文（哥倫比亞）",
  "Spanish (Costa Rica)": "西班牙文（哥斯大黎加）",
  "Spanish (Spain)": "西班牙文（西班牙）",
  "Spanish (Mexico)": "西班牙文（墨西哥）",
  "Spanish (Peru)": "西班牙文（祕魯）",
  "Estonian": "愛沙尼亞文",
  "Basque": "巴斯克文",
  "Persian": "波斯文",
  "Dari": "達里文",
  "Persian (Iran)": "波斯文（伊朗）",
  "Fula": "富拉文",
  "Finnish": "芬蘭文",
  "Finnish (Finland)": "芬蘭文（芬蘭）",
  "Filipino": "菲律賓文",
  "French": "法文",
  "French (Belgium)": "法文（比利時）",
  "French (Canada)": "法文（加拿大）",
  "French (Switzerland)": "法文（瑞士）",
  "Irish": "愛爾蘭文",
  "Galician": "加利西亞文",
  "Greek (Ancient)": "希臘文（古代）",
  "Hausa": "豪薩文",
  "Hebrew": "希伯來文",
  "Hebrew (Israel)": "希伯來文（以色列）",
  "Hindi": "印地文",
  "Croatian": "克羅埃西亞文",
  "Croatian (Croatia)": "克羅埃西亞文（克羅埃西亞）",
  "Haitian Creole": "海地克里奧爾文",
  "Hungarian": "匈牙利文",
  "Hungarian (Hungary)": "匈牙利文（匈牙利）",
  "Armenian": "亞美尼亞文",
  "Indonesian": "印尼文",
  "Igbo": "伊布文",
  "Icelandic": "冰島文",
  "Italian": "義大利文",
  "Italian (Italy)": "義大利文（義大利）",
  "Inuktitut": "因紐特文",
  "Japanese": "日文",
  "Japanese (Japan)": "日文（日本）",
  "Georgian": "喬治亞文",
  "Kabyle": "卡比爾文",
  "Kazakh": "哈薩克文",
  "Khmer": "高棉文",
  "Kannada": "坎那達文",
  "Korean": "韓文",
  "Korean (Korea)": "韓文（韓國）",
  "Latin": "拉丁文",
  "Lakota": "拉科塔文",
  "Lao": "寮文",
  "Lithuanian": "立陶宛文",
  "Latvian": "拉脫維亞文",
  "Māori": "毛利文",
  "Mongolian": "蒙古文",
  "Marathi": "馬拉地文",
  "Malay": "馬來文",
  "Maltese": "馬爾他文",
  "Burmese": "緬甸文",
  "Norwegian (Bokmål)": "挪威文（博克馬爾）",
  "Norwegian (Bokmål, Norway)": "挪威文（博克馬爾，挪威）",
  "Nepali": "尼泊爾文",
  "Dutch": "荷蘭文",
  "Flemish": "佛蘭德文",
  "Norwegian (Nynorsk)": "挪威文（新挪威文）",
  "Navajo": "納瓦荷文",
  "Turkish (Ottoman)": "土耳其文（鄂圖曼）",
  "Punjabi": "旁遮普文",
  "Persian (Old)": "波斯文（古代）",
  "Polish": "波蘭文",
  "Pashto": "普什圖文",
  "Portuguese": "葡萄牙文",
  "Portuguese (Brazil)": "葡萄牙文（巴西）",
  "Portuguese (Portugal)": "葡萄牙文（葡萄牙）",
  "Quechua": "蓋楚瓦文",
  "Romanian": "羅馬尼亞文",
  "Russian": "俄文",
  "Kinyarwanda": "盧安達文",
  "Sanskrit": "梵文",
  "Sami (Northern)": "薩米文（北部）",
  "Sinhala": "僧伽羅文",
  "Slovak": "斯洛伐克文",
  "Slovak (Slovakia)": "斯洛伐克文（斯洛伐克）",
  "Slovenian": "斯洛維尼亞文",
  "Slovenian (Slovenia)": "斯洛維尼亞文（斯洛維尼亞）",
  "Sami (Southern)": "薩米文（南部）",
  "Sami (Northern)": "薩米文（北部）",
  "Sami (Lule)": "薩米文（魯勒）",
  "Shona": "紹納文",
  "Serbian": "塞爾維亞文",
  "Serbian (Latin)": "塞爾維亞文（拉丁文）",
  "Swedish": "瑞典文",
  "Swedish (Sweden)": "瑞典文（瑞典）",
  "Swahili": "史瓦希里文",
  "Swahili (Kenya)": "史瓦希里文（肯亞）",
  "Swahili (Tanzania)": "史瓦希里文（坦尚尼亞）",
  "Syriac (Classical)": "敘利亞文（古代）",
  "Tamil": "坦米爾文",
  "Telugu": "泰盧固文",
  "Tajik": "塔吉克文",
  "Thai": "泰文",
  "Thai (Thailand)": "泰文（泰國）",
  "Turkmen": "土庫曼文",
  "Tagalog": "塔加路族文",
  "Turkish": "土耳其文",
  "Turkish (Turkey)": "土耳其文（土耳其）",
  "Tatar": "韃靼文",
  "Uyghur": "維吾爾文",
  "Ukrainian": "烏克蘭文",
  "Urdu": "烏都文",
  "Uzbek": "烏茲別克文",
  "Vietnamese": "越南文",
  "Wolof": "沃洛夫文",
  "Xhosa": "科薩文",
  "Yiddish": "意第緒文",
  "Yoruba": "約魯巴文",
  "Maya (Yucatec)": "馬雅文（尤卡坦）",
  "Chinese": "中文",
  "Chinese (Simplified)": "中文（簡體）",
  "Chinese (Simplified)": "中文（簡體）",
  "Chinese (Traditional)": "中文（繁體）",
  "Chinese (Hong Kong)": "中文（香港）",
  "Chinese (Singapore)": "中文（新加坡）",
  "Chinese (Traditional)": "中文（繁體）",
  "Zulu": "祖魯文",
  "Zulu": "祖魯文（南非）"
});