langAtts = {
  "af": "Afrikaans",
  "af-za": "Afrikaans (Suid-Afrika)",
  "ak": "Akan",
  "am": "አማርኛ",
  "ar": "العربية",
  "ar-eg": "العربية (مصر)",
  "ar-ma": "العربية (المغرب)",
  "ar-sa": "العربية (السعودية)",
  "az": "azərbaycan",
  "be": "беларуская",
  "bg": "български",
  "bg-bg": "български (България)",
  "bho": "भोजपुरी",
  "bm": "bamanakan",
  "bn": "বাংলা",
  "bo": "བོད་སྐད་",
  "bs": "bosanski",
  "ca": "català",
  "cop": "ⲘⲉⲧⲢⲉⲙⲛ̀ⲭⲏⲙⲓ",
  "cr": "ᓀᐦᐃᔭᐍᐏᐣ",
  "cs": "čeština",
  "cu": "ѩзыкъ словѣньскъ",
  "cy": "Cymraeg",
  "da": "dansk",
  "de": "Deutsch",
  "de-at": "Österreichisches Deutsch",
  "de-ch": "Schweizer Hochdeutsch",
  "de-de": "Deutsch (Deutschland)",
  "dv": "ދިވެހިބަސް",
  "el": "Ελληνικά",
  "en-au": "Australian English",
  "en-ca": "Canadian English",
  "en-gb": "British English",
  "en-ie": "English (Ireland)",
  "en-in": "English (Indian)",
  "en-tt": "English (Trinidad)",
  "en-us": "English (United States)",
  "en-za": "English (South Africa)",
  "en": "English",
  "eo": "Esperanto",
  "es-ar": "español de Argentina",
  "es-cl": "español de Chile",
  "es-co": "español de Colombia",
  "es-cr": "español de Costa Rica",
  "es-es": "español de España",
  "es-mx": "español de México",
  "es-pe": "español de Perú",
  "es": "español",
  "et": "eesti",
  "eu": "euskara",
  "fa": "فارسی",
  "fa-af": "دری",
  "fa-ir": "فارسی (ایران)",
  "ff": "Pulaar",
  "fi": "suomi",
  "fi-fi": "suomi (Suomi)",
  "fil": "Filipino",
  "fr-be": "français (Belgique)",
  "fr-ca": "français canadien",
  "fr-ch": "français suisse",
  "fr": "français",
  "ga": "Gaeilge",
  "gl": "galego",
  "grc": "Ἀρχαία ἑλληνικὴ",
  "ha": "Hausa",
  "he": "עברית",
  "he-il": "עברית (ישראל)",
  "hi": "हिन्दी",
  "hr": "hrvatski",
  "hr-hr": "hrvatski (Hrvatska)",
  "ht": "Kreyòl Ayisyen",
  "hu": "magyar",
  "hu-hu": "magyar (Magyarország)",
  "hy": "հայերեն",
  "id": "Indonesia",
  "ig": "Igbo",
  "is": "íslenska",
  "it": "italiano",
  "it-it": "italiano (Italia)",
  "iu": "ᐃᓄᒃᑎᑐᑦ",
  "ja": "日本語",
  "ja-jp": "日本語 (日本)",
  "ka": "ქართული",
  "kab": "Taqbaylit",
  "kk": "қазақ тілі",
  "km": "ខ្មែរ",
  "kn": "ಕನ್ನಡ",
  "ko": "한국어",
  "ko-kr": "한국어 (대한민국)",
  "la": "Latina",
  "lkt": "Lakȟólʼiyapi",
  "lo": "ລາວ",
  "lv": "latviešu",
  "lt": "lietuvių",
  "mi": "Māori",
  "mn": "монгол",
  "mr": "मराठी",
  "ms": "Melayu",
  "mt": "Malti",
  "my": "မြန်မာ",
  "nb": "norsk bokmål",
  "nb-no": "norsk bokmål (Norge)",
  "ne": "नेपाली",
  "nl-be": "Vlaams",
  "nl": "Nederlands",
  "nn": "norsk nynorsk",
  "nv": "Diné Bizaad",
  "ota": "لسان عثمانى",
  "pa": "ਪੰਜਾਬੀ",
  "peo": "𐎱𐎠𐎼𐎿",
  "pl": "polski",
  "ps": "پښتو",
  "pt-br": "Português do Brasil",
  "pt-pt": "português europeu",
  "pt": "português",
  "qu": "Runasimi",
  "ro": "română",
  "ru": "русский",
  "rw": "Ikinyarwanda",
  "sa": "संस्कृत भाषा",
  "se": "davvisámegiella",
  "sk-sk": "slovenčina (Slovensko)",
  "si": "සිංහල",
  "sl": "slovenščina",
  "sl-si": "slovenščina (Slovenija)",
  "sma": "Åarjelsaemien gïele",
  "sme": "davvisámegiella",
  "smj": "julevsámegiella",
  "sn": "chiShona",
  "sr": "српски",
  "sr-latn": "srpski (latinica)",
  "sv": "svenska",
  "sv-se": "svenska (Sverige)",
  "sw": "Kiswahili",
  "sw-ke": "Kiswahili (Kenya)",
  "sw-tz": "Kiswahili (Tanzania)",
  "syc": "ܠܫܢܐ ܣܘܪܝܝܐ",
  "ta": "தமிழ்",
  "te": "తెలుగు",
  "tg": "тоҷикӣ",
  "th": "ไทย",
  "th-th": "ไทย (ไทย)",
  "tk": "türkmen dili",
  "tl": "Tagalog",
  "tr": "Türkçe",
  "tr-tr": "Türkçe (Türkiye)",
  "tt": "татар",
  "ug": "ئۇيغۇرچە",
  "uk": "українська",
  "ur": "اردو",
  "uz": "o‘zbek",
  "vi": "Tiếng Việt",
  "wo": "Wolof",
  "xh": "IsiXhosa",
  "yi": "ייִדיש",
  "yo": "Èdè Yorùbá",
  "yua": "Maaya T'aan",
  "zh-cn": "中文（中国）",
  "zh-hans": "简体中文",
  "zh-hant": "繁體中文",
  "zh-hk": "中文（香港）",
  "zh-sg": "中文（新加坡）",
  "zh-tw": "中文（台灣）",
  "zh": "中文",
  "zu": "isiZulu",
  "zu-za": "isiZulu (iNingizimu Afrika)"
};